// ─── Generative Design i18n dictionary ────────────────────────────────────────

export const genDesignDict = {
  ko: {
    badge: '제너러티브 디자인',
    pageTitle: '제너러티브 디자인',
    pageDesc: '경계 조건을 설정하면 AI가 최소 중량·최대 강도를 위한 위상 최적화를 수행합니다',
    designDomain: '설계 영역',
    width: '너비',
    height: '높이',
    depth: '깊이',
    material: '재질',
    materialAluminum: '알루미늄',
    materialSteel: '스틸',
    materialTitanium: '티타늄',
    materialAbs: 'ABS',
    materialNylon: '나일론',
    boundaryConditions: '경계 조건',
    fixedFaces: '고정면 (구속)',
    loadFaces: '하중 적용',
    faceLabels: ['+X면', '-X면', '+Y면(상)', '-Y면(하)', '+Z면', '-Z면'],
    forceX: '힘 X (N)',
    forceY: '힘 Y (N)',
    forceZ: '힘 Z (N)',
    forceMagnitude: '힘 크기',
    forceDirection: '힘 방향',
    optimization: '최적화 설정',
    volumeFraction: '목표 체적 분율',
    resolution: '해상도',
    resLow: '낮음',
    resMedium: '보통',
    resHigh: '높음',
    penaltyFactor: '패널티 팩터',
    filterRadius: '필터 반경',
    maxIterations: '최대 반복 횟수',
    generate: '디자인 생성',
    generating: '최적화 중...',
    iterationLabel: '반복',
    complianceLabel: '컴플라이언스',
    volumeLabel: '체적 분율',
    changeLabel: '변화량',
    resultTitle: '최적화 결과',
    exportSTL: 'STL 내보내기',
    sendToQuote: '견적 요청',
    resetAll: '전체 초기화',
    clickFaceToFix: '면을 클릭하여 고정 구속을 설정하세요',
    clickFaceToLoad: '면을 클릭하여 하중을 적용하세요',
    noFixedFace: '고정면을 하나 이상 설정해 주세요',
    noLoadFace: '하중을 하나 이상 설정해 주세요',
    convergenceChart: '수렴 이력',
    estimatedWeight: '예상 무게',
    weightReduction: '중량 절감',
    originalWeight: '원래 무게',
    optimizedWeight: '최적화 무게',
    designDomainSize: '영역 크기',
    selectMode: '선택 모드',
    modeFixed: '고정',
    modeLoad: '하중',
    modeNone: '보기',
    facePlusX: '오른쪽 (+X)',
    faceMinusX: '왼쪽 (-X)',
    facePlusY: '위 (+Y)',
    faceMinusY: '아래 (-Y)',
    facePlusZ: '앞 (+Z)',
    faceMinusZ: '뒤 (-Z)',
  },
  en: {
    badge: 'Generative Design',
    pageTitle: 'Generative Design',
    pageDesc: 'Set boundary conditions and let AI optimize the topology for minimum weight and maximum strength',
    designDomain: 'Design Domain',
    width: 'Width',
    height: 'Height',
    depth: 'Depth',
    material: 'Material',
    materialAluminum: 'Aluminum',
    materialSteel: 'Steel',
    materialTitanium: 'Titanium',
    materialAbs: 'ABS',
    materialNylon: 'Nylon',
    boundaryConditions: 'Boundary Conditions',
    fixedFaces: 'Fixed Faces (Constraints)',
    loadFaces: 'Load Application',
    faceLabels: ['+X Face', '-X Face', '+Y Face (Top)', '-Y Face (Bottom)', '+Z Face', '-Z Face'],
    forceX: 'Force X (N)',
    forceY: 'Force Y (N)',
    forceZ: 'Force Z (N)',
    forceMagnitude: 'Force Magnitude',
    forceDirection: 'Force Direction',
    optimization: 'Optimization Settings',
    volumeFraction: 'Target Volume Fraction',
    resolution: 'Resolution',
    resLow: 'Low',
    resMedium: 'Medium',
    resHigh: 'High',
    penaltyFactor: 'Penalty Factor',
    filterRadius: 'Filter Radius',
    maxIterations: 'Max Iterations',
    generate: 'Generate Design',
    generating: 'Optimizing...',
    iterationLabel: 'Iteration',
    complianceLabel: 'Compliance',
    volumeLabel: 'Volume Fraction',
    changeLabel: 'Change',
    resultTitle: 'Optimization Result',
    exportSTL: 'Export STL',
    sendToQuote: 'Send to Quote',
    resetAll: 'Reset All',
    clickFaceToFix: 'Click a face to set as fixed constraint',
    clickFaceToLoad: 'Click a face to apply load',
    noFixedFace: 'Please set at least one fixed face',
    noLoadFace: 'Please set at least one load',
    convergenceChart: 'Convergence History',
    estimatedWeight: 'Estimated Weight',
    weightReduction: 'Weight Reduction',
    originalWeight: 'Original Weight',
    optimizedWeight: 'Optimized Weight',
    designDomainSize: 'Domain Size',
    selectMode: 'Selection Mode',
    modeFixed: 'Fix',
    modeLoad: 'Load',
    modeNone: 'View',
    facePlusX: 'Right (+X)',
    faceMinusX: 'Left (-X)',
    facePlusY: 'Top (+Y)',
    faceMinusY: 'Bottom (-Y)',
    facePlusZ: 'Front (+Z)',
    faceMinusZ: 'Back (-Z)',
  },
  ja: {
    badge: 'ジェネレーティブデザイン',
    pageTitle: 'ジェネレーティブデザイン',
    pageDesc: '境界条件を設定すると、AIが最小重量・最大強度のためのトポロジー最適化を実行します',
    designDomain: '設計領域',
    width: '幅',
    height: '高さ',
    depth: '奥行き',
    material: '材質',
    materialAluminum: 'アルミニウム',
    materialSteel: 'スチール',
    materialTitanium: 'チタン',
    materialAbs: 'ABS',
    materialNylon: 'ナイロン',
    boundaryConditions: '境界条件',
    fixedFaces: '固定面（拘束）',
    loadFaces: '荷重適用',
    faceLabels: ['+X面', '-X面', '+Y面（上）', '-Y面（下）', '+Z面', '-Z面'],
    forceX: '力 X (N)',
    forceY: '力 Y (N)',
    forceZ: '力 Z (N)',
    forceMagnitude: '力の大きさ',
    forceDirection: '力の方向',
    optimization: '最適化設定',
    volumeFraction: '目標体積率',
    resolution: '解像度',
    resLow: '低',
    resMedium: '中',
    resHigh: '高',
    penaltyFactor: 'ペナルティ係数',
    filterRadius: 'フィルタ半径',
    maxIterations: '最大反復回数',
    generate: 'デザイン生成',
    generating: '最適化中...',
    iterationLabel: '反復',
    complianceLabel: 'コンプライアンス',
    volumeLabel: '体積率',
    changeLabel: '変化量',
    resultTitle: '最適化結果',
    exportSTL: 'STLエクスポート',
    sendToQuote: '見積依頼',
    resetAll: '全てリセット',
    clickFaceToFix: '面をクリックして固定拘束を設定してください',
    clickFaceToLoad: '面をクリックして荷重を適用してください',
    noFixedFace: '固定面を1つ以上設定してください',
    noLoadFace: '荷重を1つ以上設定してください',
    convergenceChart: '収束履歴',
    estimatedWeight: '推定重量',
    weightReduction: '軽量化率',
    originalWeight: '元の重量',
    optimizedWeight: '最適化後の重量',
    designDomainSize: '領域サイズ',
    selectMode: '選択モード',
    modeFixed: '固定',
    modeLoad: '荷重',
    modeNone: '表示',
    facePlusX: '右 (+X)',
    faceMinusX: '左 (-X)',
    facePlusY: '上 (+Y)',
    faceMinusY: '下 (-Y)',
    facePlusZ: '前 (+Z)',
    faceMinusZ: '後 (-Z)',
  },
  cn: {
    badge: '生成式设计',
    pageTitle: '生成式设计',
    pageDesc: '设置边界条件，让AI优化拓扑结构以实现最轻重量和最大强度',
    designDomain: '设计域',
    width: '宽度',
    height: '高度',
    depth: '深度',
    material: '材料',
    materialAluminum: '铝',
    materialSteel: '钢',
    materialTitanium: '钛',
    materialAbs: 'ABS',
    materialNylon: '尼龙',
    boundaryConditions: '边界条件',
    fixedFaces: '固定面（约束）',
    loadFaces: '载荷施加',
    faceLabels: ['+X面', '-X面', '+Y面（顶）', '-Y面（底）', '+Z面', '-Z面'],
    forceX: '力 X (N)',
    forceY: '力 Y (N)',
    forceZ: '力 Z (N)',
    forceMagnitude: '力的大小',
    forceDirection: '力的方向',
    optimization: '优化设置',
    volumeFraction: '目标体积分数',
    resolution: '分辨率',
    resLow: '低',
    resMedium: '中',
    resHigh: '高',
    penaltyFactor: '惩罚因子',
    filterRadius: '过滤半径',
    maxIterations: '最大迭代次数',
    generate: '生成设计',
    generating: '优化中...',
    iterationLabel: '迭代',
    complianceLabel: '柔度',
    volumeLabel: '体积分数',
    changeLabel: '变化量',
    resultTitle: '优化结果',
    exportSTL: '导出 STL',
    sendToQuote: '发送报价',
    resetAll: '全部重置',
    clickFaceToFix: '点击面以设置固定约束',
    clickFaceToLoad: '点击面以施加载荷',
    noFixedFace: '请至少设置一个固定面',
    noLoadFace: '请至少设置一个载荷',
    convergenceChart: '收敛历史',
    estimatedWeight: '预估重量',
    weightReduction: '减重比例',
    originalWeight: '原始重量',
    optimizedWeight: '优化后重量',
    designDomainSize: '域尺寸',
    selectMode: '选择模式',
    modeFixed: '固定',
    modeLoad: '载荷',
    modeNone: '查看',
    facePlusX: '右 (+X)',
    faceMinusX: '左 (-X)',
    facePlusY: '顶 (+Y)',
    faceMinusY: '底 (-Y)',
    facePlusZ: '前 (+Z)',
    faceMinusZ: '后 (-Z)',
  },
  es: {
    badge: 'Diseno Generativo',
    pageTitle: 'Diseno Generativo',
    pageDesc: 'Establezca condiciones de contorno y deje que la IA optimice la topologia para minimo peso y maxima resistencia',
    designDomain: 'Dominio de Diseno',
    width: 'Ancho',
    height: 'Alto',
    depth: 'Profundidad',
    material: 'Material',
    materialAluminum: 'Aluminio',
    materialSteel: 'Acero',
    materialTitanium: 'Titanio',
    materialAbs: 'ABS',
    materialNylon: 'Nylon',
    boundaryConditions: 'Condiciones de Contorno',
    fixedFaces: 'Caras Fijas (Restricciones)',
    loadFaces: 'Aplicacion de Carga',
    faceLabels: ['Cara +X', 'Cara -X', 'Cara +Y (Sup.)', 'Cara -Y (Inf.)', 'Cara +Z', 'Cara -Z'],
    forceX: 'Fuerza X (N)',
    forceY: 'Fuerza Y (N)',
    forceZ: 'Fuerza Z (N)',
    forceMagnitude: 'Magnitud de Fuerza',
    forceDirection: 'Direccion de Fuerza',
    optimization: 'Ajustes de Optimizacion',
    volumeFraction: 'Fraccion de Volumen Objetivo',
    resolution: 'Resolucion',
    resLow: 'Baja',
    resMedium: 'Media',
    resHigh: 'Alta',
    penaltyFactor: 'Factor de Penalizacion',
    filterRadius: 'Radio de Filtro',
    maxIterations: 'Iteraciones Maximas',
    generate: 'Generar Diseno',
    generating: 'Optimizando...',
    iterationLabel: 'Iteracion',
    complianceLabel: 'Cumplimiento',
    volumeLabel: 'Fraccion de Volumen',
    changeLabel: 'Cambio',
    resultTitle: 'Resultado de Optimizacion',
    exportSTL: 'Exportar STL',
    sendToQuote: 'Enviar a Cotizacion',
    resetAll: 'Restablecer Todo',
    clickFaceToFix: 'Haga clic en una cara para fijar como restriccion',
    clickFaceToLoad: 'Haga clic en una cara para aplicar carga',
    noFixedFace: 'Establezca al menos una cara fija',
    noLoadFace: 'Establezca al menos una carga',
    convergenceChart: 'Historial de Convergencia',
    estimatedWeight: 'Peso Estimado',
    weightReduction: 'Reduccion de Peso',
    originalWeight: 'Peso Original',
    optimizedWeight: 'Peso Optimizado',
    designDomainSize: 'Tamano del Dominio',
    selectMode: 'Modo de Seleccion',
    modeFixed: 'Fijar',
    modeLoad: 'Carga',
    modeNone: 'Ver',
    facePlusX: 'Derecha (+X)',
    faceMinusX: 'Izquierda (-X)',
    facePlusY: 'Superior (+Y)',
    faceMinusY: 'Inferior (-Y)',
    facePlusZ: 'Frontal (+Z)',
    faceMinusZ: 'Posterior (-Z)',
  },
  ar: {
    badge: 'التصميم التوليدي',
    pageTitle: 'التصميم التوليدي',
    pageDesc: 'حدد شروط الحدود ودع الذكاء الاصطناعي يحسّن الطوبولوجيا لأقل وزن وأقصى متانة',
    designDomain: 'نطاق التصميم',
    width: 'العرض',
    height: 'الارتفاع',
    depth: 'العمق',
    material: 'المادة',
    materialAluminum: 'ألومنيوم',
    materialSteel: 'فولاذ',
    materialTitanium: 'تيتانيوم',
    materialAbs: 'ABS',
    materialNylon: 'نايلون',
    boundaryConditions: 'شروط الحدود',
    fixedFaces: 'الأوجه الثابتة (القيود)',
    loadFaces: 'تطبيق الحمل',
    faceLabels: ['وجه +X', 'وجه -X', 'وجه +Y (أعلى)', 'وجه -Y (أسفل)', 'وجه +Z', 'وجه -Z'],
    forceX: 'القوة X (نيوتن)',
    forceY: 'القوة Y (نيوتن)',
    forceZ: 'القوة Z (نيوتن)',
    forceMagnitude: 'مقدار القوة',
    forceDirection: 'اتجاه القوة',
    optimization: 'إعدادات التحسين',
    volumeFraction: 'نسبة الحجم المستهدفة',
    resolution: 'الدقة',
    resLow: 'منخفضة',
    resMedium: 'متوسطة',
    resHigh: 'عالية',
    penaltyFactor: 'معامل العقوبة',
    filterRadius: 'نصف قطر المرشح',
    maxIterations: 'أقصى عدد تكرارات',
    generate: 'توليد التصميم',
    generating: 'جارٍ التحسين...',
    iterationLabel: 'التكرار',
    complianceLabel: 'المطاوعة',
    volumeLabel: 'نسبة الحجم',
    changeLabel: 'التغيير',
    resultTitle: 'نتيجة التحسين',
    exportSTL: 'تصدير STL',
    sendToQuote: 'إرسال للتسعير',
    resetAll: 'إعادة تعيين الكل',
    clickFaceToFix: 'انقر على وجه لتعيينه كقيد ثابت',
    clickFaceToLoad: 'انقر على وجه لتطبيق الحمل',
    noFixedFace: 'يرجى تعيين وجه ثابت واحد على الأقل',
    noLoadFace: 'يرجى تعيين حمل واحد على الأقل',
    convergenceChart: 'سجل التقارب',
    estimatedWeight: 'الوزن المقدر',
    weightReduction: 'تخفيض الوزن',
    originalWeight: 'الوزن الأصلي',
    optimizedWeight: 'الوزن المحسّن',
    designDomainSize: 'حجم النطاق',
    selectMode: 'وضع التحديد',
    modeFixed: 'تثبيت',
    modeLoad: 'حمل',
    modeNone: 'عرض',
    facePlusX: 'يمين (+X)',
    faceMinusX: 'يسار (-X)',
    facePlusY: 'أعلى (+Y)',
    faceMinusY: 'أسفل (-Y)',
    facePlusZ: 'أمام (+Z)',
    faceMinusZ: 'خلف (-Z)',
  },
} as const;

export type GenDesignLang = keyof typeof genDesignDict;
