import { createHash } from 'node:crypto';
import { verifyRobotEvidenceBundle } from './robotEvidenceBundle';
import { verifyRobotCadIntegrationReview, type RobotCadIntegrationReview } from './robotCadIntegrationReview';
import { hashRobotCadIntegrationTarget, type RobotCadIntegrationPacket } from './robotCadIntegrationPacket';
import { selectRobotCatalogBytes } from './robotCatalogSelection'; import { evaluateRobotHousingFitEvidence } from './robotHousingFitEvidence';
import { validateAiAssemblyProgram, type AiAssemblyProgram } from '../aiAssemblyProgram'; import type { AiAssemblyRevisionPackage } from '../aiAssemblyRevision'; import type { TrustedReviewerKeys } from '@/lib/reference/nativeCadExpertReview';

type Artifact = { name: string; bytes: Uint8Array };
export type RobotPostIntegrationEvidence = { schema: 'nexyfab.robot-post-integration-evidence.v1'; postIntegrationStatus: 'passed' | 'failed' | 'not_run'; integrationAuthorized: boolean; selectedOccurrencesVerified: boolean; precisionStatus: 'passed' | 'failed' | 'not_run'; lineageId: string | null; revision: number | null; programHash: string; preciseReportHash: string; targetHash: string; catalogManifestSha256: string; housingSha256: string; counts: { selectedOccurrences: number; motionFrames: number; checkedMotionFrames: number; collisionFrames: number; preciseInterferences: number }; releaseReady: false; blockers: string[]; errors: string[]; sideEffects: { persisted: false; sourceModified: false; workspaceModified: false; quoteCreated: false; rfqSent: false } };

export async function verifyRobotPostIntegrationEvidence(input: { programBytes: Uint8Array; revisionManifestBytes: Uint8Array; preciseReportBytes: Uint8Array; applicationReceiptBytes: Uint8Array; packet: RobotCadIntegrationPacket; review: RobotCadIntegrationReview; housingBytes: Uint8Array; requirementsBytes: Uint8Array; catalogManifestBytes: Uint8Array; artifacts: readonly Artifact[]; trustedKeys: TrustedReviewerKeys }): Promise<RobotPostIntegrationEvidence> {
  const errors: string[] = []; const programHash = sha(input.programBytes), preciseReportHash = sha(input.preciseReportBytes); const selection = selectRobotCatalogBytes(input.requirementsBytes, input.catalogManifestBytes, input.artifacts), housing = evaluateRobotHousingFitEvidence(input.housingBytes, input.requirementsBytes, input.catalogManifestBytes, input.artifacts); const authorization = verifyRobotCadIntegrationReview(input.packet, input.review, input.trustedKeys);
  if (!authorization.approved) errors.push(...authorization.errors, 'integration authorization is invalid');
  if (hashRobotCadIntegrationTarget(input.packet) !== input.packet.targetHash) errors.push('integration packet target hash mismatch');
  let manifest: AiAssemblyRevisionPackage | null = null, program: AiAssemblyProgram | null = null, receipt: Record<string, unknown> | null = null;
  try { manifest = parse(input.revisionManifestBytes) as AiAssemblyRevisionPackage; } catch { errors.push('r+1 revision manifest must be valid UTF-8 JSON object'); }
  try { program = parse(input.programBytes) as AiAssemblyProgram; } catch { errors.push('r+1 program must be valid UTF-8 JSON object'); }
  try { receipt = parse(input.applicationReceiptBytes); } catch { errors.push('integration application receipt must be valid UTF-8 JSON object'); }
  if (!manifest || manifest.schema !== 'nexyfab.ai-assembly-revision-package.v1' || manifest.lineageId !== input.packet.lineageId || manifest.revision !== input.packet.revision + 1 || manifest.baseProgramHash !== input.packet.programHash || manifest.programHash !== programHash || manifest.programArtifact !== `editable-program-${programHash}.json` || manifest.sideEffects?.sourceModified !== false || manifest.sideEffects.quoteCreated !== false || manifest.sideEffects.rfqSent !== false) errors.push('r+1 revision manifest is not correctly bound to approved source');
  const receiptManifest = receipt?.manifest as Record<string, unknown> | undefined; if (!receipt || receipt.schema !== 'nexyfab.robot-cad-integration-application.v1' || receipt.ok !== true || receipt.targetHash !== input.packet.targetHash || receipt.cadRevisionCreated !== true || receipt.cadAppliedToWorkspace !== false || receipt.releaseReady !== false || receipt.reverificationRequired !== true || receiptManifest?.programHash !== programHash || receiptManifest?.revision !== input.packet.revision + 1) errors.push('integration application receipt is invalid or mismatched');
  if (program) { try { const issues = validateAiAssemblyProgram(program); if (issues.length) errors.push(`r+1 program invalid: ${issues[0]!.path}: ${issues[0]!.message}`); } catch { errors.push('r+1 program structure is invalid'); } }
  let precise: Awaited<ReturnType<typeof verifyRobotEvidenceBundle>> | null = null; try { precise = await verifyRobotEvidenceBundle(input.preciseReportBytes, input.programBytes); } catch (cause) { errors.push(cause instanceof Error ? cause.message : String(cause)); }
  if (precise && (precise.lineageId !== input.packet.lineageId || precise.revision !== input.packet.revision + 1 || precise.programHash !== programHash)) errors.push('precise report lineage/revision/program binding mismatch');
  const expected = new Set(input.packet.replacements.flatMap(item => [`J${item.joint}:motor:${item.selected.motor}`, `J${item.joint}:reducer:${item.selected.reducer}`, `J${item.joint}:bearing:${item.selected.bearing}`])); const ids = new Set(program?.assembly.parts.map(part => part.id) ?? []); const selectedOccurrencesVerified = expected.size === 18 && [...expected].every(id => ids.has(id)) && input.packet.replacements.every(item => !ids.has(item.placeholders.motor) && !ids.has(item.placeholders.reducer) && !ids.has(item.placeholders.bearing)); if (!selectedOccurrencesVerified) errors.push('r+1 does not contain the exact 18 approved selected occurrences');
  if (!selection.selectionReady) errors.push(...selection.errors, 'catalog selection revalidation failed'); if (housing.housingStatus !== 'passed') errors.push(...housing.errors, 'housing fit revalidation failed');
  const precisionStatus = !precise ? 'not_run' : precise.motionConverged === true && precise.motionFrames === 156 && precise.checkedMotionFrames === 156 && precise.collisionFrames === 0 && precise.flaggedInterferences === 0 ? 'passed' : 'failed'; if (precisionStatus === 'failed') errors.push('post-integration precise motion/interference verification did not pass');
  const evidenceReady = authorization.approved && selectedOccurrencesVerified && selection.selectionReady && housing.housingStatus === 'passed' && precisionStatus === 'passed' && errors.length === 0; const status = !precise || !authorization.approved || !selection.selectionReady || housing.housingStatus === 'not_run' ? 'not_run' : evidenceReady ? 'passed' : 'failed';
  const blockers = [...(precisionStatus !== 'passed' ? ['post_integration_precision_not_passed'] : []), ...(!selectedOccurrencesVerified ? ['selected_occurrences_not_verified'] : []), ...(!selection.selectionReady ? ['catalog_revalidation_not_passed'] : []), ...(housing.housingStatus !== 'passed' ? ['housing_revalidation_not_passed'] : []), 'nexyfab_exact_cad_evidence_required', 'manufacturing_validation_required', 'final_expert_release_review_required'];
  return { schema: 'nexyfab.robot-post-integration-evidence.v1', postIntegrationStatus: status, integrationAuthorized: authorization.approved, selectedOccurrencesVerified, precisionStatus, lineageId: precise?.lineageId ?? manifest?.lineageId ?? null, revision: precise?.revision ?? manifest?.revision ?? null, programHash, preciseReportHash, targetHash: input.packet.targetHash, catalogManifestSha256: selection.manifestSha256, housingSha256: housing.housingSha256, counts: { selectedOccurrences: [...expected].filter(id => ids.has(id)).length, motionFrames: precise?.motionFrames ?? 0, checkedMotionFrames: precise?.checkedMotionFrames ?? 0, collisionFrames: precise?.collisionFrames ?? 0, preciseInterferences: precise?.flaggedInterferences ?? 0 }, releaseReady: false, blockers: [...new Set(blockers)], errors: [...new Set(errors)], sideEffects: { persisted: false, sourceModified: false, workspaceModified: false, quoteCreated: false, rfqSent: false } };
}
function parse(bytes: Uint8Array) { const value = JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes)); if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(); return value as Record<string, unknown>; }
function sha(bytes: Uint8Array) { return createHash('sha256').update(bytes).digest('hex'); }
