import { createHash, createPublicKey, verify } from 'node:crypto'; import { z } from 'zod';
const sha = z.string().regex(/^[a-f0-9]{64}$/); const iso = z.string().datetime({ offset: false });
const nativeSchema = z.object({ schema: z.literal('nexyfab.robot-native-cad-evidence.v1'), programHash: sha, workerKind: z.enum(['solidworks-native', 'inventor-native', 'catia-native', 'creo-native', 'parasolid-native']), workerId: z.string().min(1), workerIdentitySha256: sha, nativeArtifactSha256: sha, roundtripStepSha256: sha, generatedAt: iso, jointCount: z.literal(6), occurrenceCount: z.number().int().min(25), checks: z.object({ nativeOpen: z.literal(true), assemblyTree: z.literal(true), jointSemantics: z.literal(true), units: z.literal(true), topology: z.literal(true), roundtrip: z.literal(true) }).strict(), signature: z.string().min(1) }).strict();
const manufacturingSchema = z.object({ schema: z.literal('nexyfab.robot-manufacturing-validation.v1'), programHash: sha, catalogArtifactSetSha256: sha, reviewerId: z.string().min(1), generatedAt: iso, selectedComponentCount: z.literal(18), checks: z.object({ dfm: z.literal(true), toleranceStack: z.literal(true), bom: z.literal(true), fasteners: z.literal(true), cableRouting: z.literal(true), materials: z.literal(true), processPlan: z.literal(true) }).strict(), signature: z.string().min(1) }).strict();
const postSchema = z.object({ schema: z.literal('nexyfab.robot-post-integration-evidence.v1'), postIntegrationStatus: z.literal('passed'), programHash: sha, targetHash: sha, catalogManifestSha256: sha, releaseReady: z.literal(false), errors: z.array(z.string()).length(0), counts: z.object({ selectedOccurrences: z.literal(18), motionFrames: z.literal(156), checkedMotionFrames: z.literal(156), collisionFrames: z.literal(0), preciseInterferences: z.literal(0) }).passthrough() }).passthrough();
type Native = z.infer<typeof nativeSchema>; type Manufacturing = z.infer<typeof manufacturingSchema>; export type TrustedRobotEvidenceKeys = Record<string, { publicKey: string; workerKind?: Native['workerKind'] }>;
export type RobotReleaseEvidenceAudit = { schema: 'nexyfab.robot-release-evidence-audit.v1'; status: 'ready_for_final_review' | 'not_ready'; releaseTargetHash: string | null; programHash: string | null; postIntegrationSha256: string; nativeEvidenceSha256: string | null; manufacturingEvidenceSha256: string | null; nativeEvidenceValid: boolean; manufacturingEvidenceValid: boolean; releaseReady: false; errors: string[]; blockers: string[]; sideEffects: { persisted: false; cadModified: false; quoteCreated: false; rfqSent: false } };
export function parseTrustedRobotEvidenceKeys(raw: string | undefined, requireWorkerKind: boolean): TrustedRobotEvidenceKeys { if (!raw) return {}; try { const value = JSON.parse(raw) as unknown; if (!value || typeof value !== 'object' || Array.isArray(value)) return {}; return Object.fromEntries(Object.entries(value).flatMap(([id, entry]) => { if (!id.trim() || !entry || typeof entry !== 'object' || Array.isArray(entry)) return []; const item = entry as { publicKey?: unknown; workerKind?: unknown }; if (typeof item.publicKey !== 'string' || !fingerprint(item.publicKey)) return []; const kinds = ['solidworks-native', 'inventor-native', 'catia-native', 'creo-native', 'parasolid-native'] as const; const workerKind = kinds.find(kind => kind === item.workerKind); if (requireWorkerKind && !workerKind) return []; return [[id, { publicKey: createPublicKey(item.publicKey).export({ type: 'spki', format: 'pem' }).toString(), ...(workerKind ? { workerKind } : {}) }]]; })); } catch { return {}; } }
export const robotNativeEvidencePayload = (v: Omit<Native, 'signature'>) => canonical(v); export const robotManufacturingEvidencePayload = (v: Omit<Manufacturing, 'signature'>) => canonical(v);
export function auditRobotReleaseEvidence(postBytes: Uint8Array, nativeBytes: Uint8Array | null, manufacturingBytes: Uint8Array | null, trustedWorkers: TrustedRobotEvidenceKeys, trustedManufacturing: TrustedRobotEvidenceKeys): RobotReleaseEvidenceAudit {
  const errors: string[] = [], postHash = digest(postBytes); const postRaw = decode(postBytes, 'post-integration evidence', errors), post = postSchema.safeParse(postRaw); if (!post.success) errors.push(...post.error.issues.map(i => `post.${i.path.join('.')}: ${i.message}`));
  const nativeHash = nativeBytes ? digest(nativeBytes) : null, manufacturingHash = manufacturingBytes ? digest(manufacturingBytes) : null; const native = nativeSchema.safeParse(nativeBytes ? decode(nativeBytes, 'native CAD evidence', errors) : null), manufacturing = manufacturingSchema.safeParse(manufacturingBytes ? decode(manufacturingBytes, 'manufacturing evidence', errors) : null);
  if (!nativeBytes) errors.push('native CAD evidence missing'); else if (!native.success) errors.push(...native.error.issues.map(i => `native.${i.path.join('.')}: ${i.message}`));
  if (!manufacturingBytes) errors.push('manufacturing evidence missing'); else if (!manufacturing.success) errors.push(...manufacturing.error.issues.map(i => `manufacturing.${i.path.join('.')}: ${i.message}`));
  let nativeValid = false, manufacturingValid = false;
  if (post.success && native.success) { const registration = trustedWorkers[native.data.workerId]; if (native.data.programHash !== post.data.programHash) errors.push('native evidence program hash mismatch'); if (!registration || registration.workerKind !== native.data.workerKind || fingerprint(registration.publicKey) !== native.data.workerIdentitySha256) errors.push('native worker identity is not trusted'); else if (!verifySignature(robotNativeEvidencePayload(withoutSignature(native.data)), native.data.signature, registration.publicKey)) errors.push('native worker signature invalid'); else if (native.data.programHash === post.data.programHash) nativeValid = true; }
  if (post.success && manufacturing.success) { const registration = trustedManufacturing[manufacturing.data.reviewerId]; if (manufacturing.data.programHash !== post.data.programHash) errors.push('manufacturing evidence program hash mismatch'); if (!registration) errors.push('manufacturing reviewer is not trusted'); else if (!verifySignature(robotManufacturingEvidencePayload(withoutSignature(manufacturing.data)), manufacturing.data.signature, registration.publicKey)) errors.push('manufacturing reviewer signature invalid'); else if (manufacturing.data.programHash === post.data.programHash) manufacturingValid = true; }
  const ready = post.success && nativeValid && manufacturingValid && errors.length === 0; const releaseTargetHash = ready ? digest(new TextEncoder().encode(canonical({ manufacturingEvidenceSha256: manufacturingHash, nativeEvidenceSha256: nativeHash, postIntegrationSha256: postHash, programHash: post.data.programHash }))) : null;
  return { schema: 'nexyfab.robot-release-evidence-audit.v1', status: ready ? 'ready_for_final_review' : 'not_ready', releaseTargetHash, programHash: post.success ? post.data.programHash : null, postIntegrationSha256: postHash, nativeEvidenceSha256: nativeHash, manufacturingEvidenceSha256: manufacturingHash, nativeEvidenceValid: nativeValid, manufacturingEvidenceValid: manufacturingValid, releaseReady: false, errors: [...new Set(errors)], blockers: ready ? ['final_release_dual_signoff_required'] : [...(!nativeValid ? ['external_native_cad_evidence_required'] : []), ...(!manufacturingValid ? ['manufacturing_validation_required'] : []), 'final_release_dual_signoff_required'], sideEffects: { persisted: false, cadModified: false, quoteCreated: false, rfqSent: false } };
}
function decode(bytes: Uint8Array, label: string, errors: string[]) { try { return JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes)); } catch { errors.push(`${label} must be valid UTF-8 JSON`); return null; } } function digest(bytes: Uint8Array) { return createHash('sha256').update(bytes).digest('hex'); } function canonical(v: unknown): string { if (Array.isArray(v)) return `[${v.map(canonical).join(',')}]`; if (v && typeof v === 'object') return `{${Object.entries(v).sort(([a], [b]) => a.localeCompare(b)).map(([k, x]) => `${JSON.stringify(k)}:${canonical(x)}`).join(',')}}`; return JSON.stringify(v); } function withoutSignature<T extends { signature: string }>(v: T): Omit<T, 'signature'> { const { signature: _signature, ...rest } = v; return rest; } function fingerprint(key: string) { try { return createHash('sha256').update(createPublicKey(key).export({ type: 'spki', format: 'der' })).digest('hex'); } catch { return null; } } function verifySignature(payload: string, signature: string, key: string) { try { return verify(null, Buffer.from(payload), key, Buffer.from(signature, 'base64')); } catch { return false; } }
