import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { generateRobot6Axis } from './robotGenerator';
import { ROBOT_6AXIS_DEMONSTRATOR_SPEC } from './robotDemonstrator';
import { buildRobotCadIntegrationPacket } from './robotCadIntegrationPacket';

const enc = (value: unknown) => new TextEncoder().encode(`${JSON.stringify(value)}\n`); const artifact = new TextEncoder().encode('integration evidence'); const hash = createHash('sha256').update(artifact).digest('hex');
const base = { manufacturer: 'M', revision: 'A', source: 'datasheet', artifactHash: hash, massSource: 'confirmed', interface: { axisRef: 'axis', mountingPlaneRef: 'face', shaftDiameterMm: 30 } };
const catalog = { schema: 'nexyfab.robot-component-catalog.v1', components: [{ ...base, id: 'M', model: 'M', kind: 'motor', massKg: 1, envelopeMm: { x: 60, y: 60, z: 100 }, ratedTorqueNm: 10, peakTorqueNm: 20, maxRpm: 5000, rotorInertiaKgM2: 0.01 }, { ...base, id: 'R', model: 'R', kind: 'reducer', massKg: 2, envelopeMm: { x: 90, y: 90, z: 80 }, ratio: 100, ratedOutputTorqueNm: 1000, peakOutputTorqueNm: 1500, maxInputRpm: 6000, efficiency: 0.9, backlashArcmin: 2 }, { ...base, id: 'B', model: 'B', kind: 'bearing', massKg: 0.5, envelopeMm: { x: 80, y: 80, z: 20 }, boreMm: 30, odMm: 80, widthMm: 20, dynamicLoadN: 20000, staticLoadN: 10000, limitingRpm: 5000 }], artifacts: [{ path: 'evidence.pdf', sha256: hash, source: 'datasheet' }] };
const requirements = { schema: 'nexyfab.robot-selection-requirements.v1', requirements: Array.from({ length: 6 }, (_, i) => ({ joint: i + 1, requiredOutputTorqueNm: 100, requiredOutputRpm: 10, radialLoadN: 1000, minShaftDiameterMm: 25, safetyFactor: 1.5 })) };
const housing = (z = 240) => ({ schema: 'nexyfab.robot-housing-capacities.v1', capacities: Array.from({ length: 6 }, (_, i) => ({ joint: i + 1, internalMm: { x: 110, y: 110, z }, radialClearanceMm: 5, axialClearanceMm: 10, source: 'measured CAD', artifactHash: hash })) });
function fixture(z = 240) { const programBytes = enc(generateRobot6Axis(ROBOT_6AXIS_DEMONSTRATOR_SPEC).program); const programHash = createHash('sha256').update(programBytes).digest('hex'); const revision = { schema: 'nexyfab.ai-assembly-revision-package.v1', lineageId: 'robot-lineage', revision: 2, baseProgramHash: 'a'.repeat(64), programHash, programArtifact: `editable-program-${programHash}.json`, createdAt: '2026-08-09T00:00:00.000Z', sideEffects: { sourceModified: false, quoteCreated: false, rfqSent: false } }; return { programBytes, revisionBytes: enc(revision), housingBytes: enc(housing(z)) }; }
const run = (z = 240) => { const f = fixture(z); return buildRobotCadIntegrationPacket(f.programBytes, f.revisionBytes, f.housingBytes, enc(requirements), enc(catalog), [{ name: 'evidence.pdf', bytes: artifact }]); };

describe('robot CAD integration review packet', () => {
  it('binds six replacement plans but applies nothing before expert review', () => { const result = run(); expect(result).toMatchObject({ readiness: 'review_pending', expertReviewRequired: true, cadIntegrationStatus: 'not_applied', releaseReady: false, errors: [], sideEffects: { persisted: false, sourceModified: false, cadModified: false, quoteCreated: false, rfqSent: false } }); expect(result.replacements).toHaveLength(6); expect(result.replacements[5]).toMatchObject({ joint: 6, selected: { motor: 'M', reducer: 'R', bearing: 'B' }, fitStatus: 'passed' }); expect(result.targetHash).toMatch(/^[a-f0-9]{64}$/); });
  it('fails closed when fit or revision binding is invalid', () => { expect(run(100)).toMatchObject({ readiness: 'not_ready', replacements: [], cadIntegrationStatus: 'not_applied' }); const f = fixture(); f.programBytes[0] ^= 1; const result = buildRobotCadIntegrationPacket(f.programBytes, f.revisionBytes, f.housingBytes, enc(requirements), enc(catalog), [{ name: 'evidence.pdf', bytes: artifact }]); expect(result.readiness).toBe('not_ready'); expect(result.errors.join(' ')).toContain('exact editable program bytes'); });
});
