import { generateKeyPairSync, sign } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { hashRobotCadIntegrationTarget } from './robotCadIntegrationPacket';
import { robotCadIntegrationSignoffPayload, verifyRobotCadIntegrationReview, type RobotCadIntegrationReview, type RobotCadIntegrationSignoff } from './robotCadIntegrationReview';
import type { TrustedReviewerKeys } from '@/lib/reference/nativeCadExpertReview';

const keys = () => { const pair = generateKeyPairSync('ed25519'); return { privateKey: pair.privateKey, publicKey: pair.publicKey.export({ type: 'spki', format: 'pem' }).toString() }; };
const domain = keys(), independent = keys();
const packet = (() => { const value = { schema: 'nexyfab.robot-cad-integration-review-packet.v1' as const, targetHash: '', lineageId: 'robot-lineage', revision: 2, baseProgramHash: 'a'.repeat(64), programHash: 'b'.repeat(64), revisionManifestSha256: 'c'.repeat(64), requirementsSha256: 'd'.repeat(64), catalogManifestSha256: 'e'.repeat(64), catalogArtifactSetSha256: 'f'.repeat(64), housingSha256: '1'.repeat(64), readiness: 'review_pending' as const, expertReviewRequired: true as const, cadIntegrationStatus: 'not_applied' as const, releaseReady: false as const, replacements: Array.from({ length: 6 }, (_, i) => ({ joint: i + 1, placeholders: { motor: `J${i + 1}:motor:old`, reducer: `J${i + 1}:reducer:old`, bearing: `J${i + 1}:bearing:old` }, selected: { motor: 'M', reducer: 'R', bearing: 'B' }, fitStatus: 'passed' as const })), errors: [], sideEffects: { persisted: false as const, sourceModified: false as const, cadModified: false as const, quoteCreated: false as const, rfqSent: false as const } }; value.targetHash = hashRobotCadIntegrationTarget(value); return value; })();
const trusted: TrustedReviewerKeys = { alice: { publicKey: domain.publicKey, roles: ['domain-reviewer'] }, bob: { publicKey: independent.publicKey, roles: ['independent-reviewer'] } };
function signed(role: RobotCadIntegrationSignoff['role'], reviewerId: string, privateKey: typeof domain.privateKey, targetHash = packet.targetHash): RobotCadIntegrationSignoff { const unsigned = { role, reviewerId, decision: 'approved' as const, reviewedAt: '2026-08-09T00:00:00.000Z', targetHash }; return { ...unsigned, signature: sign(null, Buffer.from(robotCadIntegrationSignoffPayload(unsigned)), privateKey).toString('base64') }; }
const review = (first = signed('domain-reviewer', 'alice', domain.privateKey), second = signed('independent-reviewer', 'bob', independent.privateKey)): RobotCadIntegrationReview => ({ schema: 'nexyfab.robot-cad-integration-review.v1', targetHash: packet.targetHash, signoffs: [first, second] });

describe('robot CAD integration expert review', () => {
  it('authorizes only the exact target while applying and releasing nothing', () => { expect(verifyRobotCadIntegrationReview(packet, review(), trusted, Date.parse('2026-08-09T00:01:00Z'))).toMatchObject({ approved: true, integrationAuthorized: true, cadApplied: false, releaseReady: false, nextStep: 'create_new_cad_revision_then_reverify', errors: [], sideEffects: { persisted: false, cadModified: false, quoteCreated: false, rfqSent: false } }); });
  it('rejects signature reuse on another target', () => { const changed = structuredClone(packet); changed.housingSha256 = '2'.repeat(64); changed.targetHash = hashRobotCadIntegrationTarget(changed); const result = verifyRobotCadIntegrationReview(changed, review(), trusted, Date.parse('2026-08-09T00:01:00Z')); expect(result.approved).toBe(false); expect(result.errors.join(' ')).toContain('target'); });
  it('rejects one person or one key filling both roles', () => { const samePerson = review(signed('domain-reviewer', 'alice', domain.privateKey), signed('independent-reviewer', 'alice', domain.privateKey)); expect(verifyRobotCadIntegrationReview(packet, samePerson, { alice: { publicKey: domain.publicKey, roles: ['domain-reviewer', 'independent-reviewer'] } }, Date.parse('2026-08-09T00:01:00Z')).errors).toContain('integration_reviewers_not_independent'); const sameKey = review(); expect(verifyRobotCadIntegrationReview(packet, sameKey, { alice: trusted.alice!, bob: { publicKey: domain.publicKey, roles: ['independent-reviewer'] } }, Date.parse('2026-08-09T00:01:00Z')).errors).toContain('integration_reviewer_keys_not_independent'); });
  it('rejects tampered packets and non-approval decisions', () => { const tampered = structuredClone(packet); tampered.replacements[0]!.selected.motor = 'OTHER'; expect(verifyRobotCadIntegrationReview(tampered, review(), trusted, Date.parse('2026-08-09T00:01:00Z')).errors).toContain('integration_packet_hash_mismatch'); const rejected = signed('domain-reviewer', 'alice', domain.privateKey); rejected.decision = 'rejected'; expect(verifyRobotCadIntegrationReview(packet, review(rejected), trusted, Date.parse('2026-08-09T00:01:00Z')).approved).toBe(false); });
});
