import { createHash, generateKeyPairSync, sign } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { generateRobot6Axis } from './robotGenerator'; import { ROBOT_6AXIS_DEMONSTRATOR_SPEC } from './robotDemonstrator';
import { buildRobotCadIntegrationPacket } from './robotCadIntegrationPacket'; import { robotCadIntegrationSignoffPayload, type RobotCadIntegrationSignoff } from './robotCadIntegrationReview'; import { createApprovedRobotCadIntegrationRevision } from './robotCadIntegrationApply';

const enc = (v: unknown) => new TextEncoder().encode(`${JSON.stringify(v)}\n`); const artifact = new TextEncoder().encode('apply evidence'); const hash = createHash('sha256').update(artifact).digest('hex');
const base = { manufacturer: 'M', revision: 'A', source: 'datasheet', artifactHash: hash, massSource: 'confirmed', interface: { axisRef: 'axis', mountingPlaneRef: 'face', shaftDiameterMm: 30 } };
const catalog = { schema: 'nexyfab.robot-component-catalog.v1', components: [{ ...base, id: 'M', model: 'Motor X', kind: 'motor', massKg: 1, envelopeMm: { x: 60, y: 60, z: 100 }, ratedTorqueNm: 10, peakTorqueNm: 20, maxRpm: 5000, rotorInertiaKgM2: 0.01 }, { ...base, id: 'R', model: 'Reducer X', kind: 'reducer', massKg: 2, envelopeMm: { x: 90, y: 90, z: 80 }, ratio: 100, ratedOutputTorqueNm: 1000, peakOutputTorqueNm: 1500, maxInputRpm: 6000, efficiency: 0.9, backlashArcmin: 2 }, { ...base, id: 'B', model: 'Bearing X', kind: 'bearing', massKg: 0.5, envelopeMm: { x: 80, y: 80, z: 20 }, boreMm: 30, odMm: 80, widthMm: 20, dynamicLoadN: 20000, staticLoadN: 10000, limitingRpm: 5000 }], artifacts: [{ path: 'evidence.pdf', sha256: hash, source: 'datasheet' }] }; const requirements = { schema: 'nexyfab.robot-selection-requirements.v1', requirements: Array.from({ length: 6 }, (_, i) => ({ joint: i + 1, requiredOutputTorqueNm: 100, requiredOutputRpm: 10, radialLoadN: 1000, minShaftDiameterMm: 25, safetyFactor: 1.5 })) }; const housing = { schema: 'nexyfab.robot-housing-capacities.v1', capacities: Array.from({ length: 6 }, (_, i) => ({ joint: i + 1, internalMm: { x: 110, y: 110, z: 240 }, radialClearanceMm: 5, axialClearanceMm: 10, source: 'measured CAD', artifactHash: hash })) };
const auxiliary = [{ ...base, id: 'BR', model: 'Brake', kind: 'brake', massKg: 0.8, envelopeMm: { x: 70, y: 70, z: 30 }, holdingTorqueNm: 50, maxRpm: 5000, ratedVoltageV: 24, releasePowerW: 20, responseTimeMs: 50 }, { ...base, id: 'EN', model: 'Encoder', kind: 'encoder', massKg: 0.2, envelopeMm: { x: 50, y: 50, z: 20 }, resolutionBits: 20, accuracyArcsec: 30, maxRpm: 6000, supplyVoltageV: 5 }, { ...base, id: 'HA', model: 'Harness', kind: 'harness', massKg: 1, envelopeMm: { x: 20, y: 20, z: 500 }, conductorCount: 20, ratedVoltageV: 300, ratedCurrentA: 5, outerDiameterMm: 12, minimumBendRadiusMm: 80, flexLifeCycles: 10_000_000 }, { ...base, id: 'TC', model: 'Tool connector', kind: 'tool_connector', massKg: 0.3, envelopeMm: { x: 60, y: 60, z: 30 }, contactCount: 12, ratedVoltageV: 60, ratedCurrentA: 3, matingCycles: 10_000, ipRating: 'IP67' }];
const mount = (parentPartId: string, z: number) => ({ parentPartId, parentAxisRef: 'bbox_axis_z_max', parentPlaneRef: 'f.cap.top', positionMm: { x: 0, y: 0, z }, orientation: { x: 0, y: 0, z: 0, w: 1 } });
const fullCatalog = { ...catalog, components: [...catalog.components, ...auxiliary] }; const fullRequirements = { ...requirements, auxiliarySelections: { brake: { componentId: 'BR', minimumHoldingTorqueNm: 40, minimumMaxRpm: 4000, requiredVoltageV: 24, mount: mount('base', 100) }, encoder: { componentId: 'EN', minimumResolutionBits: 18, maximumAccuracyArcsec: 60, minimumMaxRpm: 5000, requiredSupplyVoltageV: 5, mount: mount('shoulder', 200) }, harness: { componentId: 'HA', minimumConductorCount: 16, minimumRatedVoltageV: 250, minimumRatedCurrentA: 4, maximumMinimumBendRadiusMm: 100, minimumFlexLifeCycles: 5_000_000, mount: mount('upper-arm', 300) }, toolConnector: { componentId: 'TC', minimumContactCount: 8, minimumRatedVoltageV: 48, minimumRatedCurrentA: 2, minimumMatingCycles: 5_000, minimumIpRating: 'IP65', mount: mount('tool-flange', 900) } } };
function fixture(catalogValue: unknown = catalog, requirementsValue: unknown = requirements) { const programBytes = enc(generateRobot6Axis(ROBOT_6AXIS_DEMONSTRATOR_SPEC).program); const programHash = createHash('sha256').update(programBytes).digest('hex'); const revisionBytes = enc({ schema: 'nexyfab.ai-assembly-revision-package.v1', lineageId: 'robot-lineage', revision: 2, baseProgramHash: 'a'.repeat(64), programHash, programArtifact: `editable-program-${programHash}.json`, createdAt: new Date().toISOString(), sideEffects: { sourceModified: false, quoteCreated: false, rfqSent: false } }); const housingBytes = enc(housing), requirementsBytes = enc(requirementsValue), catalogManifestBytes = enc(catalogValue), artifacts = [{ name: 'evidence.pdf', bytes: artifact }]; const packet = buildRobotCadIntegrationPacket(programBytes, revisionBytes, housingBytes, requirementsBytes, catalogManifestBytes, artifacts); const ka = generateKeyPairSync('ed25519'), kb = generateKeyPairSync('ed25519'); const make = (role: RobotCadIntegrationSignoff['role'], reviewerId: string, key: typeof ka.privateKey) => { const unsigned = { role, reviewerId, decision: 'approved' as const, reviewedAt: new Date(Date.now() - 1000).toISOString(), targetHash: packet.targetHash }; return { ...unsigned, signature: sign(null, Buffer.from(robotCadIntegrationSignoffPayload(unsigned)), key).toString('base64') }; }; return { programBytes, revisionManifestBytes: revisionBytes, housingBytes, requirementsBytes, catalogManifestBytes, artifacts, packet, review: { schema: 'nexyfab.robot-cad-integration-review.v1' as const, targetHash: packet.targetHash, signoffs: [make('domain-reviewer', 'alice', ka.privateKey), make('independent-reviewer', 'bob', kb.privateKey)] }, trustedKeys: { alice: { publicKey: ka.publicKey.export({ type: 'spki', format: 'pem' }).toString(), roles: ['domain-reviewer' as const] }, bob: { publicKey: kb.publicKey.export({ type: 'spki', format: 'pem' }).toString(), roles: ['independent-reviewer' as const] } } }; }
describe('approved robot CAD integration revision', () => {
  it('creates a hash-bound r+1 only with exact drive18 + auxiliary4 and unresolved zero', async () => { const f = fixture(fullCatalog, fullRequirements); const result = await createApprovedRobotCadIntegrationRevision(f); expect(result).toMatchObject({ ok: true, sourceRevision: 2, outputRevision: 3, applicationHash: expect.stringMatching(/^[a-f0-9]{64}$/), catalogUnresolvedCount: 0, appliedOccurrenceCounts: { drive: 18, auxiliary: 4, total: 22 }, cadRevisionCreated: true, cadAppliedToWorkspace: false, releaseReady: false, reverificationRequired: true, errors: [], sideEffects: { persisted: false, sourceModified: false, workspaceModified: false, quoteCreated: false, rfqSent: false } }); expect(result.replacedOccurrences).toHaveLength(18); expect(result.addedOccurrences).toHaveLength(4); expect(result.manifest).toMatchObject({ revision: 3, baseProgramHash: f.packet.programHash }); expect(createHash('sha256').update(result.programBytes!).digest('hex')).toBe(result.manifest!.programHash); const program = JSON.parse(new TextDecoder().decode(result.programBytes!)); expect(program.assembly.parts.some((p: { id: string }) => p.id === 'J6:motor:M')).toBe(true); expect(JSON.stringify(program)).not.toContain('-unselected'); expect(program.parts.filter((p: { definitionId: string }) => p.definitionId.startsWith('catalog:'))).toHaveLength(22); expect(program.unresolved).toEqual([]); expect(program.assembly.mates.every((m: { a: { partId: string }; b: { partId: string } }) => !`${m.a.partId}${m.b.partId}`.includes('-unselected'))).toBe(true); });
  it('rejects a drive-only application that omits the four auxiliary occurrences', async () => { const result = await createApprovedRobotCadIntegrationRevision(fixture()); expect(result).toMatchObject({ ok: false, applicationHash: null, programBytes: null, manifestBytes: null, appliedOccurrenceCounts: { drive: 0, auxiliary: 0, total: 0 } }); expect(result.errors.join(' ')).toContain('exactly four approved auxiliary additions'); });
  it('fails closed on packet drift or invalid review without emitting bytes', async () => { const f = fixture(); f.packet.housingSha256 = '2'.repeat(64); const drift = await createApprovedRobotCadIntegrationRevision(f); expect(drift).toMatchObject({ ok: false, programBytes: null, manifestBytes: null, cadRevisionCreated: false }); const g = fixture(); g.review.signoffs = [g.review.signoffs[0]!]; const review = await createApprovedRobotCadIntegrationRevision(g); expect(review.ok).toBe(false); expect(review.programBytes).toBeNull(); });
  it('adds all four approved auxiliary occurrences and removes only their resolved blockers', async () => {
    const result = await createApprovedRobotCadIntegrationRevision(fixture(fullCatalog, fullRequirements));
    expect(result).toMatchObject({ ok: true, replacedOccurrences: expect.any(Array), addedOccurrences: [
      { kind: 'brake', occurrenceId: 'AUX:brake:BR', componentId: 'BR', parentPartId: 'base' },
      { kind: 'encoder', occurrenceId: 'AUX:encoder:EN', componentId: 'EN', parentPartId: 'shoulder' },
      { kind: 'harness', occurrenceId: 'AUX:harness:HA', componentId: 'HA', parentPartId: 'upper-arm' },
      { kind: 'tool_connector', occurrenceId: 'AUX:tool_connector:TC', componentId: 'TC', parentPartId: 'tool-flange' },
    ] });
    expect(result.replacedOccurrences).toHaveLength(18);
    const program = JSON.parse(new TextDecoder().decode(result.programBytes!));
    expect(program.parts).toHaveLength(29); expect(program.assembly.parts).toHaveLength(29); expect(program.assembly.mates).toHaveLength(68);
    expect(program.parts.filter((part: { definitionId: string }) => part.definitionId.startsWith('catalog:'))).toHaveLength(22);
    expect(program.unresolved).toEqual([]);
    expect(program.structure).toEqual(expect.arrayContaining([expect.objectContaining({ id: 'robot-auxiliary', instanceIds: ['AUX:brake:BR', 'AUX:encoder:EN', 'AUX:harness:HA', 'AUX:tool_connector:TC'] })]));
  });
});
