import { createHash, generateKeyPairSync, sign } from 'node:crypto';
import { describe, expect, it, vi } from 'vitest';

vi.mock('./robotEvidenceBundle', () => ({ verifyRobotEvidenceBundle: vi.fn(async (report: Uint8Array, program: Uint8Array) => { const overrides = JSON.parse(new TextDecoder().decode(report)); return { reportHash: createHash('sha256').update(report).digest('hex'), lineageId: 'robot-lineage', revision: 3, programHash: createHash('sha256').update(program).digest('hex'), programArtifact: '', editableParts: 29, mates: 68, rankDoF: 6, allowedDoF: 6, flaggedInterferences: overrides.flaggedInterferences ?? 0, collisionFrames: overrides.collisionFrames ?? 0, motionFrames: 156, checkedMotionFrames: 156, motionConverged: true, coordinatedMotionFrames: 49, checkedCoordinatedMotionFrames: 49, coordinatedCollisionFrames: overrides.coordinatedCollisionFrames ?? 0, coordinatedMotionConverged: true, catalogStatus: 'passed', housingStatus: 'passed', claimedReleaseReady: false, effectiveReleaseReady: false, blockers: [], interferenceQueue: [] }; }) }));

import { generateRobot6Axis } from './robotGenerator';
import { ROBOT_6AXIS_DEMONSTRATOR_SPEC } from './robotDemonstrator';
import { buildRobotCadIntegrationPacket } from './robotCadIntegrationPacket';
import { robotCadIntegrationSignoffPayload, type RobotCadIntegrationSignoff } from './robotCadIntegrationReview';
import { createApprovedRobotCadIntegrationRevision } from './robotCadIntegrationApply';
import { verifyRobotPostIntegrationEvidence } from './robotPostIntegrationEvidence';

const enc = (value: unknown) => new TextEncoder().encode(`${JSON.stringify(value)}\n`);
const artifact = new TextEncoder().encode('post evidence'); const artifactHash = createHash('sha256').update(artifact).digest('hex');
const base = { manufacturer: 'M', revision: 'A', source: 'datasheet', artifactHash, massSource: 'confirmed', interface: { axisRef: 'axis', mountingPlaneRef: 'face', shaftDiameterMm: 30 } };
const drive = [{ ...base, id: 'M', model: 'Motor', kind: 'motor', massKg: 1, envelopeMm: { x: 60, y: 60, z: 100 }, ratedTorqueNm: 10, peakTorqueNm: 20, maxRpm: 5000, rotorInertiaKgM2: 0.01 }, { ...base, id: 'R', model: 'Reducer', kind: 'reducer', massKg: 2, envelopeMm: { x: 90, y: 90, z: 80 }, ratio: 100, ratedOutputTorqueNm: 1000, peakOutputTorqueNm: 1500, maxInputRpm: 6000, efficiency: 0.9, backlashArcmin: 2 }, { ...base, id: 'B', model: 'Bearing', kind: 'bearing', massKg: 0.5, envelopeMm: { x: 80, y: 80, z: 20 }, boreMm: 30, odMm: 80, widthMm: 20, dynamicLoadN: 20000, staticLoadN: 10000, limitingRpm: 5000 }];
const auxiliary = [{ ...base, id: 'BR', model: 'Brake', kind: 'brake', massKg: 0.8, envelopeMm: { x: 70, y: 70, z: 30 }, holdingTorqueNm: 50, maxRpm: 5000, ratedVoltageV: 24, releasePowerW: 20, responseTimeMs: 50 }, { ...base, id: 'EN', model: 'Encoder', kind: 'encoder', massKg: 0.2, envelopeMm: { x: 50, y: 50, z: 20 }, resolutionBits: 20, accuracyArcsec: 30, maxRpm: 6000, supplyVoltageV: 5 }, { ...base, id: 'HA', model: 'Harness', kind: 'harness', massKg: 1, envelopeMm: { x: 20, y: 20, z: 500 }, conductorCount: 20, ratedVoltageV: 300, ratedCurrentA: 5, outerDiameterMm: 12, minimumBendRadiusMm: 80, flexLifeCycles: 10_000_000 }, { ...base, id: 'TC', model: 'Tool connector', kind: 'tool_connector', massKg: 0.3, envelopeMm: { x: 60, y: 60, z: 30 }, contactCount: 12, ratedVoltageV: 60, ratedCurrentA: 3, matingCycles: 10_000, ipRating: 'IP67' }];
const catalog = { schema: 'nexyfab.robot-component-catalog.v1', components: [...drive, ...auxiliary], artifacts: [{ path: 'evidence.pdf', sha256: artifactHash, source: 'datasheet' }] };
const mount = (parentPartId: string, z: number) => ({ parentPartId, parentAxisRef: 'bbox_axis_z_max', parentPlaneRef: 'f.cap.top', positionMm: { x: 0, y: 0, z }, orientation: { x: 0, y: 0, z: 0, w: 1 } });
const requirements = { schema: 'nexyfab.robot-selection-requirements.v1', requirements: Array.from({ length: 6 }, (_, index) => ({ joint: index + 1, requiredOutputTorqueNm: 100, requiredOutputRpm: 10, radialLoadN: 1000, minShaftDiameterMm: 25, safetyFactor: 1.5 })), auxiliarySelections: { brake: { componentId: 'BR', minimumHoldingTorqueNm: 40, minimumMaxRpm: 4000, requiredVoltageV: 24, mount: mount('base', 100) }, encoder: { componentId: 'EN', minimumResolutionBits: 18, maximumAccuracyArcsec: 60, minimumMaxRpm: 5000, requiredSupplyVoltageV: 5, mount: mount('shoulder', 200) }, harness: { componentId: 'HA', minimumConductorCount: 16, minimumRatedVoltageV: 250, minimumRatedCurrentA: 4, maximumMinimumBendRadiusMm: 100, minimumFlexLifeCycles: 5_000_000, mount: mount('upper-arm', 300) }, toolConnector: { componentId: 'TC', minimumContactCount: 8, minimumRatedVoltageV: 48, minimumRatedCurrentA: 2, minimumMatingCycles: 5_000, minimumIpRating: 'IP65', mount: mount('tool-flange', 900) } } };
const housing = { schema: 'nexyfab.robot-housing-capacities.v1', capacities: Array.from({ length: 6 }, (_, index) => ({ joint: index + 1, internalMm: { x: 110, y: 110, z: 240 }, radialClearanceMm: 5, axialClearanceMm: 10, source: 'measured CAD', artifactHash })) };

async function fixture() {
  const sourceProgramBytes = enc(generateRobot6Axis(ROBOT_6AXIS_DEMONSTRATOR_SPEC).program); const sourceProgramHash = createHash('sha256').update(sourceProgramBytes).digest('hex');
  const sourceRevisionBytes = enc({ schema: 'nexyfab.ai-assembly-revision-package.v1', lineageId: 'robot-lineage', revision: 2, baseProgramHash: '0'.repeat(64), programHash: sourceProgramHash, programArtifact: `editable-program-${sourceProgramHash}.json`, createdAt: new Date().toISOString(), sideEffects: { sourceModified: false, quoteCreated: false, rfqSent: false } });
  const housingBytes = enc(housing); const requirementsBytes = enc(requirements); const catalogManifestBytes = enc(catalog); const artifacts = [{ name: 'evidence.pdf', bytes: artifact }];
  const packet = buildRobotCadIntegrationPacket(sourceProgramBytes, sourceRevisionBytes, housingBytes, requirementsBytes, catalogManifestBytes, artifacts);
  const domain = generateKeyPairSync('ed25519'); const independent = generateKeyPairSync('ed25519');
  const make = (role: RobotCadIntegrationSignoff['role'], reviewerId: string, key: typeof domain.privateKey) => { const unsigned = { role, reviewerId, decision: 'approved' as const, reviewedAt: new Date(Date.now() - 1000).toISOString(), targetHash: packet.targetHash }; return { ...unsigned, signature: sign(null, Buffer.from(robotCadIntegrationSignoffPayload(unsigned)), key).toString('base64') }; };
  const review = { schema: 'nexyfab.robot-cad-integration-review.v1' as const, targetHash: packet.targetHash, signoffs: [make('domain-reviewer', 'alice', domain.privateKey), make('independent-reviewer', 'bob', independent.privateKey)] };
  const trustedKeys = { alice: { publicKey: domain.publicKey.export({ type: 'spki', format: 'pem' }).toString(), roles: ['domain-reviewer' as const] }, bob: { publicKey: independent.publicKey.export({ type: 'spki', format: 'pem' }).toString(), roles: ['independent-reviewer' as const] } };
  const applied = await createApprovedRobotCadIntegrationRevision({ programBytes: sourceProgramBytes, revisionManifestBytes: sourceRevisionBytes, packet, review, housingBytes, requirementsBytes, catalogManifestBytes, artifacts, trustedKeys });
  if (!applied.ok || !applied.programBytes || !applied.manifestBytes || !applied.manifest) throw new Error(applied.errors.join('; '));
  const receipt = { ...applied, programBytes: undefined, manifestBytes: undefined, manifest: applied.manifest };
  return { programBytes: applied.programBytes, revisionManifestBytes: applied.manifestBytes, preciseReportBytes: enc({}), applicationReceiptBytes: enc(receipt), packet, review, housingBytes, requirementsBytes, catalogManifestBytes, artifacts, trustedKeys };
}

describe('robot post-integration evidence', () => {
  it('passes only with a hash-bound drive18 + auxiliary4 r+1 while retaining final release blockers', async () => { const result = await verifyRobotPostIntegrationEvidence(await fixture()); expect(result).toMatchObject({ postIntegrationStatus: 'passed', integrationAuthorized: true, selectedOccurrencesVerified: true, precisionStatus: 'passed', revision: 3, applicationHash: expect.stringMatching(/^[a-f0-9]{64}$/), applicationReceiptHash: expect.stringMatching(/^[a-f0-9]{64}$/), counts: { selectedOccurrences: 18, auxiliaryOccurrences: 4, appliedOccurrences: 22, catalogUnresolved: 0, motionFrames: 156, checkedMotionFrames: 156, collisionFrames: 0, coordinatedMotionFrames: 49, checkedCoordinatedMotionFrames: 49, coordinatedCollisionFrames: 0, preciseInterferences: 0 }, releaseReady: false, errors: [], sideEffects: { persisted: false, sourceModified: false, workspaceModified: false } }); expect(result.blockers).toEqual(expect.arrayContaining(['nexyfab_exact_cad_evidence_required', 'manufacturing_validation_required', 'final_expert_release_review_required'])); });

  it('fails closed when a full apply receipt is paired with an r+1 missing one auxiliary occurrence', async () => { const value = await fixture(); const program = JSON.parse(new TextDecoder().decode(value.programBytes)); program.assembly.parts = program.assembly.parts.filter((item: { id: string }) => item.id !== 'AUX:tool_connector:TC'); program.parts = program.parts.filter((item: { instanceId: string }) => item.instanceId !== 'AUX:tool_connector:TC'); value.programBytes = enc(program); const result = await verifyRobotPostIntegrationEvidence(value); expect(result.postIntegrationStatus).toBe('failed'); expect(result.selectedOccurrencesVerified).toBe(false); expect(result.counts.auxiliaryOccurrences).toBe(3); expect(result.errors.join(' ')).toContain('exact 18 drive and 4 auxiliary'); });

  it('fails closed on target mismatch and a contradictory application count', async () => { const value = await fixture(); const receipt = JSON.parse(new TextDecoder().decode(value.applicationReceiptBytes)); receipt.targetHash = 'f'.repeat(64); receipt.appliedOccurrenceCounts.auxiliary = 3; value.applicationReceiptBytes = enc(receipt); const result = await verifyRobotPostIntegrationEvidence(value); expect(result.postIntegrationStatus).toBe('failed'); expect(result.errors).toEqual(expect.arrayContaining(['integration application receipt is invalid or mismatched', 'integration application hash mismatch'])); });

  it('fails closed when the precise report contradicts a passed collision claim', async () => { const value = await fixture(); value.preciseReportBytes = enc({ collisionFrames: 1 }); const result = await verifyRobotPostIntegrationEvidence(value); expect(result.postIntegrationStatus).toBe('failed'); expect(result.precisionStatus).toBe('failed'); expect(result.counts.collisionFrames).toBe(1); });
});
