import { timingSafeEqual } from 'node:crypto';
import { NextRequest, NextResponse } from 'next/server';
import { boundedJsonError, readBoundedJson } from '@/lib/boundedJsonBody';
import { getDbAdapter } from '@/lib/db-adapter';
import { getStorage } from '@/lib/storage';
import { getAgenticCommercialReceipt } from '@/lib/ai/agenticCommercialReceiptStore';
import { decodeAgenticCommercialReceiptEnvelope, encodeAgenticCommercialReceiptEnvelope } from '@/lib/ai/agenticCommercialReceiptCodec';
import { agenticCommercialSha256 } from '@/lib/ai/agenticCommercialQualificationReceipt';
import { createDbVerifiedAgenticCommercialReceiptStore } from '@/lib/ai/verifiedAgenticCommercialReceiptStore';
import { loadVerifiedAgenticCommercialReceiptForGeneration } from '@/lib/ai/loadVerifiedAgenticCommercialReceiptForGeneration';
import { loadServerAgenticCommercialTrust } from '@/lib/ai/serverAgenticCommercialTrust';
import { createDbExternalCommercialVerificationRequestStore, externalVerifierCallbackSha256, verifyExternalVerifierCallback, type ExternalVerifierCallback } from '@/lib/ai/externalCommercialVerificationRequest';
import { loadExternalCommercialVerifierRegistry } from '@/lib/ai/externalCommercialVerifierRegistry';
import { createDbCommercialGenerationStateStore } from '@/lib/ai/commercialGenerationStateStore';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
function authorized(request: NextRequest): boolean { const configured = process.env.NEXYFAB_EXTERNAL_VERIFIER_INTERNAL_SECRET; const supplied = request.headers.get('authorization')?.replace(/^Bearer\s+/i, '') ?? ''; if (!configured || !supplied) return false; const a = Buffer.from(configured); const b = Buffer.from(supplied); return a.length === b.length && timingSafeEqual(a, b); }
function isCallback(value: unknown): value is ExternalVerifierCallback { return !!value && typeof value === 'object' && (value as { schema?: unknown }).schema === 'nexyfab.external-commercial-verifier-callback.v1'; }
export async function POST(request: NextRequest) {
  try {
    if (!authorized(request)) return NextResponse.json({ ok: false, status: 'HOLD', code: 'INTERNAL_VERIFIER_UNAUTHORIZED' }, { status: 403 });
    if (process.env.NEXYFAB_COMMERCIAL_MODE === '1' && process.env.POSTGRES_MIGRATION_VERSION !== '2026082208') return NextResponse.json({ ok: false, status: 'HOLD', code: 'COMMERCIAL_GENERATION_MIGRATION_REQUIRED' }, { status: 503 });
    const body = await readBoundedJson<unknown>(request, 256 * 1024); if (!isCallback(body)) return NextResponse.json({ ok: false, status: 'HOLD', code: 'CALLBACK_SCHEMA_INVALID' }, { status: 400 });
    const callback = body; const registry = loadExternalCommercialVerifierRegistry(); if (!registry) return NextResponse.json({ ok: false, status: 'HOLD', code: 'EXTERNAL_VERIFIER_REGISTRY_NOT_CONFIGURED' }, { status: 503 });
    const db = getDbAdapter(); const requestStore = createDbExternalCommercialVerificationRequestStore(db); const requestValue = await requestStore.get(callback.requestId); if (!requestValue) return NextResponse.json({ ok: false, status: 'HOLD', code: 'REQUEST_NOT_FOUND' }, { status: 404 });
    const callbackSha = externalVerifierCallbackSha256(callback); const duplicate = await db.queryOne<Record<string, unknown>>('SELECT callback_sha256 FROM nf_external_commercial_verifier_callbacks WHERE request_id = ? AND sequence = ?', callback.requestId, callback.sequence);
    if (!verifyExternalVerifierCallback(requestValue, callback, registry, new Date())) return NextResponse.json({ ok: false, status: 'HOLD', code: 'CALLBACK_SIGNATURE_OR_BINDING_INVALID' }, { status: 400 });
    if (duplicate && duplicate.callback_sha256 !== callbackSha) return NextResponse.json({ ok: false, status: 'HOLD', code: 'CALLBACK_SEQUENCE_CONFLICT' }, { status: 409 });
    const claim = await db.queryOne<Record<string, unknown>>('SELECT verifier_key_id, verifier_fingerprint_sha256, lease_id, lease_expires_at, status FROM nf_external_commercial_verifier_claims WHERE request_id = ?', callback.requestId);
    const claimStatusOk = duplicate ? claim?.status === 'RELEASED' : claim?.status === 'CLAIMED' && Number(claim.lease_expires_at) > Date.now();
    if (!claim || !claimStatusOk || claim.lease_id !== callback.claimLeaseId || claim.verifier_key_id !== callback.keyId || claim.verifier_fingerprint_sha256 !== callback.fingerprintSha256) return NextResponse.json({ ok: false, status: 'HOLD', code: 'CLAIM_LEASE_INVALID' }, { status: 409 });
    const commonEvidence = requestValue.evidence.find(item => item.role === 'common_receipt');
    if (!commonEvidence) return NextResponse.json({ ok: false, status: 'HOLD', code: 'COMMON_RECEIPT_EVIDENCE_MISSING' }, { status: 409 });
    const receiptRow = await db.queryOne<{ receipt_id: string }>('SELECT receipt_id FROM nf_agentic_commercial_receipts WHERE tenant_id = ? AND project_id = ? AND execution_id = ? AND generation_run_id = ? AND target_sha256 = ? AND receipt_sha256 = ?', requestValue.tenantId, requestValue.projectId, requestValue.executionId, requestValue.generationRunId, requestValue.targetSha256, commonEvidence.sha256);
    if (!receiptRow) return NextResponse.json({ ok: false, status: 'HOLD', code: 'FINAL_RECEIPT_NOT_AVAILABLE' }, { status: 409 });
    const receipt = await getAgenticCommercialReceipt(db, getStorage(), requestValue.tenantId, requestValue.projectId, receiptRow.receipt_id); if (!receipt || receipt.receiptSha256 !== commonEvidence.sha256 || receipt.receiptBytes.length !== commonEvidence.size) return NextResponse.json({ ok: false, status: 'HOLD', code: 'CANDIDATE_RECEIPT_NOT_AVAILABLE' }, { status: 409 });
    let candidate: ReturnType<typeof decodeAgenticCommercialReceiptEnvelope>; try { candidate = decodeAgenticCommercialReceiptEnvelope(receipt.receiptBytes); } catch { return NextResponse.json({ ok: false, status: 'HOLD', code: 'CANDIDATE_ENVELOPE_INVALID' }, { status: 409 }); }
    if (candidate.kind !== 'candidate' || candidate.payload.executionId !== requestValue.executionId || candidate.payload.generationRunId !== requestValue.generationRunId || candidate.payload.targetSha256 !== requestValue.targetSha256 || (candidate.payload.project as Record<string, unknown> | undefined)?.projectId !== requestValue.projectId || (candidate.payload.project as Record<string, unknown> | undefined)?.modelContentHash !== requestValue.modelContentHash) return NextResponse.json({ ok: false, status: 'HOLD', code: 'CANDIDATE_ENVELOPE_BINDING_INVALID' }, { status: 409 });
    const candidatePayload = candidate.payload; const candidateProject = candidatePayload.project as Record<string, unknown> | undefined; const candidateParser = candidatePayload.parser as Record<string, unknown> | undefined; const candidateJournal = candidatePayload.executionJournal as Record<string, unknown> | undefined; const candidatePersistence = candidatePayload.persistenceReceipt as Record<string, unknown> | undefined; const candidateVerification = candidatePayload.verificationReceipt as Record<string, unknown> | undefined;
    const generation = await db.queryOne<Record<string, unknown>>('SELECT r.workspace_id, r.workspace_revision, r.head_revision, v.generation_program_sha256 FROM nf_commercial_generation_runs r JOIN nf_commercial_generation_revisions v ON v.tenant_id = r.tenant_id AND v.project_id = r.project_id AND v.run_id = r.run_id AND v.revision = r.head_revision WHERE r.tenant_id = ? AND r.project_id = ? AND r.run_id = ?', requestValue.tenantId, requestValue.projectId, requestValue.generationRunId);
    if (!generation || generation.workspace_id !== candidateProject?.workspaceId || Number(generation.workspace_revision) !== candidateProject?.revision || Number(generation.head_revision) !== candidatePayload.generationStateRevision || generation.generation_program_sha256 !== candidatePayload.generationProgramSha256) return NextResponse.json({ ok: false, status: 'HOLD', code: 'GENERATION_2207_BINDING_INVALID' }, { status: 409 });
    const journal = await db.queryOne<Record<string, unknown>>('SELECT lifecycle, project_id, workspace_id, receipt_hash, persistence_receipt_hash, verification_receipt_hash FROM nf_precision_cad_execution_journal WHERE execution_id = ?', requestValue.executionId); const parser = await db.queryOne<Record<string, unknown>>('SELECT parser_receipt_hash, manifest_sha256, target_hash, workspace_after_revision, workspace_after_content_hash FROM nf_precision_cad_commercial_native_parser_receipts WHERE execution_id = ?', requestValue.executionId); const persistence = await db.queryOne<Record<string, unknown>>('SELECT tenant_id, project_id, generation_run_id, parser_receipt_hash, persistence_receipt_hash, manifest_sha256, workspace_after_revision, workspace_after_content_hash, target_hash FROM nf_precision_cad_commercial_persistence_receipts WHERE execution_id = ?', requestValue.executionId); const commit = await db.queryOne<Record<string, unknown>>('SELECT project_id, workspace_id, after_revision, after_content_hash, target_hash FROM nf_precision_cad_commercial_workspace_commits WHERE execution_id = ?', requestValue.executionId);
    if (!journal || journal.lifecycle !== 'COMMITTED' || journal.project_id !== requestValue.projectId || journal.workspace_id !== candidateProject?.workspaceId || journal.receipt_hash !== candidateJournal?.sha256 || journal.persistence_receipt_hash !== candidatePersistence?.sha256 || journal.verification_receipt_hash !== candidateVerification?.sha256 || !parser || parser.target_hash !== requestValue.targetSha256 || parser.manifest_sha256 !== candidatePayload.artifactManifestSha256 || parser.parser_receipt_hash !== candidateParser?.receiptSha256 || !persistence || persistence.tenant_id !== requestValue.tenantId || persistence.project_id !== requestValue.projectId || persistence.generation_run_id !== requestValue.generationRunId || persistence.target_hash !== requestValue.targetSha256 || persistence.parser_receipt_hash !== parser.parser_receipt_hash || persistence.persistence_receipt_hash !== candidatePersistence?.sha256 || !commit || commit.project_id !== requestValue.projectId || commit.workspace_id !== candidateProject?.workspaceId || Number(commit.after_revision) !== candidateProject?.revision || commit.after_content_hash !== candidateProject?.contentHash || commit.target_hash !== requestValue.targetSha256) return NextResponse.json({ ok: false, status: 'HOLD', code: 'COMMITTED_ARTIFACT_PARSER_JOURNAL_BINDING_INVALID' }, { status: 409 });
    const finalBytes = encodeAgenticCommercialReceiptEnvelope('final', candidate.payload);
    const finalSha = agenticCommercialSha256(finalBytes);
    if (receipt.receiptSha256 === finalSha || finalSha !== callback.finalReceiptSha256) return NextResponse.json({ ok: false, status: 'HOLD', code: 'FINAL_ENVELOPE_HASH_INVALID' }, { status: 409 });
    const trust = loadServerAgenticCommercialTrust(); if (!trust.ok) return NextResponse.json({ ok: false, status: 'HOLD', releaseReady: false, code: 'SERVER_TRUST_NOT_CONFIGURED' }, { status: 503 });
    const finalStore = createDbVerifiedAgenticCommercialReceiptStore(db, getStorage());
    const stored = await finalStore.put({ receiptId: receiptRow.receipt_id, tenantId: requestValue.tenantId, projectId: requestValue.projectId, executionId: requestValue.executionId, generationRunId: requestValue.generationRunId, revision: requestValue.revision, modelContentHash: requestValue.modelContentHash, targetSha256: requestValue.targetSha256, candidateEnvelopeSha256: receipt.receiptSha256, finalEnvelopeBytes: finalBytes, verifierKeyId: callback.keyId, verifierFingerprintSha256: callback.fingerprintSha256, issuedAt: callback.issuedAt, expiresAt: callback.expiresAt });
    if (!stored.ok || stored.finalEnvelopeSha256 !== callback.finalReceiptSha256) return NextResponse.json({ ok: false, status: 'HOLD', releaseReady: false, code: stored.ok ? 'FINAL_ENVELOPE_HASH_INVALID' : stored.code }, { status: 409 });
    const finalVerification = await loadVerifiedAgenticCommercialReceiptForGeneration(finalStore, { tenantId: requestValue.tenantId, projectId: requestValue.projectId, receiptId: receiptRow.receipt_id, executionId: requestValue.executionId, generationRunId: requestValue.generationRunId, generationStateRevision: Number(candidatePayload.generationStateRevision), generationProgramSha256: String(candidatePayload.generationProgramSha256 ?? ''), revision: Number(candidateProject?.revision), modelContentHash: requestValue.modelContentHash, targetSha256: requestValue.targetSha256 }, trust.context); if (!finalVerification.ok) return NextResponse.json({ ok: false, status: 'HOLD', releaseReady: false, code: 'FINAL_ENVELOPE_RUNTIME_REVERIFICATION_FAILED', issues: finalVerification.issues }, { status: 409 });
    const receiptBinding = await createDbCommercialGenerationStateStore(db).bindReceipt({ tenantId: requestValue.tenantId, projectId: requestValue.projectId, runId: requestValue.generationRunId, receiptId: receiptRow.receipt_id, receiptSha256: callback.finalReceiptSha256, generationRevision: Number(candidatePayload.generationStateRevision), workspaceRevision: Number(candidateProject?.revision), generationProgramSha256: finalVerification.receipt?.generationProgramSha256 ?? '', targetSha256: requestValue.targetSha256, status: 'VERIFIED' });
    if (!receiptBinding.ok && receiptBinding.code !== 'RECEIPT_BINDING_CONFLICT') return NextResponse.json({ ok: false, status: 'HOLD', releaseReady: false, code: receiptBinding.code }, { status: 409 });
    if (!receiptBinding.ok) {
      const transitioned = await db.execute('UPDATE nf_commercial_generation_receipt_bindings SET receipt_sha256 = ?, status = ? WHERE receipt_id = ? AND tenant_id = ? AND project_id = ? AND run_id = ? AND generation_revision = ? AND workspace_revision = ? AND generation_program_sha256 = ? AND target_sha256 = ? AND status = ?', callback.finalReceiptSha256, 'VERIFIED', receiptRow.receipt_id, requestValue.tenantId, requestValue.projectId, requestValue.generationRunId, Number(candidatePayload.generationStateRevision), Number(candidateProject?.revision), finalVerification.receipt?.generationProgramSha256 ?? '', requestValue.targetSha256, 'PENDING');
      if (transitioned.changes !== 1) {
        const exact = await db.queryOne<Record<string, unknown>>('SELECT receipt_id FROM nf_commercial_generation_receipt_bindings WHERE receipt_id = ? AND receipt_sha256 = ? AND status = ?', receiptRow.receipt_id, callback.finalReceiptSha256, 'VERIFIED');
        if (!exact) return NextResponse.json({ ok: false, status: 'HOLD', releaseReady: false, code: 'RECEIPT_BINDING_CONFLICT' }, { status: 409 });
      }
    }
    if (duplicate) return NextResponse.json({ ok: true, status: 'VERIFIED', idempotent: true, releaseReady: true }, { status: 200, headers: { 'Cache-Control': 'private, no-store' } });
    const advanced = await db.transaction(async tx => { const status = await tx.execute('UPDATE nf_external_commercial_verification_requests SET status = ?, sequence = ?, updated_at = ? WHERE request_id = ? AND status = ? AND sequence = ?', 'VERIFIED', callback.sequence, Date.now(), callback.requestId, 'PENDING', requestValue.sequence); if (status.changes !== 1) return false; const inserted = await tx.execute('INSERT INTO nf_external_commercial_verifier_callbacks (request_id, sequence, callback_sha256, claim_lease_id, key_id, fingerprint_sha256, request_sha256, evidence_manifest_sha256, final_receipt_sha256, callback_json, issued_at, expires_at, received_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', callback.requestId, callback.sequence, callbackSha, callback.claimLeaseId, callback.keyId, callback.fingerprintSha256, callback.requestSha256, callback.evidenceManifestSha256, callback.finalReceiptSha256, JSON.stringify(callback), Date.parse(callback.issuedAt), Date.parse(callback.expiresAt), Date.now()); if (inserted.changes !== 1) throw new Error('callback_insert_failed'); await tx.execute('UPDATE nf_external_commercial_verifier_claims SET status = ? WHERE request_id = ? AND lease_id = ? AND status = ?', 'RELEASED', callback.requestId, callback.claimLeaseId, 'CLAIMED'); return true; }); if (!advanced) return NextResponse.json({ ok: false, status: 'HOLD', code: 'CALLBACK_SEQUENCE_ADVANCE_CONFLICT' }, { status: 409 });
    return NextResponse.json({ ok: true, status: 'VERIFIED', releaseReady: true, requestId: callback.requestId, callbackSha256: callbackSha }, { status: 200, headers: { 'Cache-Control': 'private, no-store' } });
  } catch (error) { const bounded = boundedJsonError(error); return NextResponse.json({ ok: false, status: 'HOLD', code: bounded?.code ?? 'CALLBACK_FAILED' }, { status: bounded?.status ?? 400 }); }
}
