import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const formsDir = path.resolve(process.argv[2] ?? 'docs/evidence/complex-holdout-lineage-v2-260807/phase-b-review-forms');
const submissionsDir = path.resolve(process.argv[3] ?? 'docs/evidence/complex-holdout-lineage-v2-260807/phase-b-review-submissions');
const output = path.resolve(process.argv[4] ?? 'docs/evidence/complex-holdout-lineage-v2-260807/phase-b-review-submission-validation.json');
type Index = { forms: Array<{ caseId: string; file: string; sha256: string }> };
type Form = { caseId: string; immutableTarget: { artifactSetHash: string; requiredAssertionIds: string[] }; submission: { revision: number; licenseReview: Decision; holdoutIsolationReview: Decision; assertionReviews: Array<Decision & { assertionId: string }>; signoffs: Array<Decision & { role: string; artifactSetHash: string; reviewedAssertionIds: string[] }> } };
type Decision = { decision: 'approved' | 'rejected' | 'changes_requested' | null; reviewerId: string | null; note: string | null; reviewedAt: string | null };
const index = JSON.parse(fs.readFileSync(path.join(formsDir, 'index.json'), 'utf8')) as Index;
const validDecision = (item: Decision) => Boolean(item.decision && item.reviewerId?.trim() && item.note?.trim() && item.reviewedAt && !Number.isNaN(Date.parse(item.reviewedAt)));
const exact = (a: string[], b: string[]) => a.slice().sort().join('|') === b.slice().sort().join('|');
const results = index.forms.map(entry => {
  const blankPath = path.join(formsDir, entry.file), blankBytes = fs.readFileSync(blankPath), blankHash = createHash('sha256').update(blankBytes).digest('hex');
  if (blankHash !== entry.sha256) return { caseId: entry.caseId, status: 'invalid', issues: ['blank_form_hash_mismatch'] };
  const submissionPath = path.join(submissionsDir, entry.file);
  if (!fs.existsSync(submissionPath)) return { caseId: entry.caseId, status: 'pending', issues: ['submission_missing'] };
  const blank = JSON.parse(blankBytes.toString('utf8')) as Form;
  const form = JSON.parse(fs.readFileSync(submissionPath, 'utf8')) as Form, issues: string[] = [];
  if (form.caseId !== entry.caseId) issues.push('submission_case_mismatch');
  if (JSON.stringify(form.immutableTarget) !== JSON.stringify(blank.immutableTarget)) issues.push('immutable_target_changed');
  if (!Number.isInteger(form.submission.revision) || form.submission.revision < 1) issues.push('submission_revision_invalid');
  if (!validDecision(form.submission.licenseReview)) issues.push('license_review_incomplete');
  if (!validDecision(form.submission.holdoutIsolationReview)) issues.push('holdout_review_incomplete');
  const assertionIds = form.submission.assertionReviews.map(item => item.assertionId);
  if (!exact(assertionIds, form.immutableTarget.requiredAssertionIds) || form.submission.assertionReviews.some(item => !validDecision(item))) issues.push('assertion_reviews_incomplete');
  const domain = form.submission.signoffs.find(item => item.role === 'domain-reviewer'), independent = form.submission.signoffs.find(item => item.role === 'independent-reviewer');
  if (!domain || !independent || !validDecision(domain) || !validDecision(independent)) issues.push('dual_signoff_incomplete');
  for (const signoff of form.submission.signoffs) if (signoff.artifactSetHash !== form.immutableTarget.artifactSetHash || !exact(signoff.reviewedAssertionIds, form.immutableTarget.requiredAssertionIds)) issues.push(`signoff_target_mismatch:${signoff.role}`);
  if (domain?.reviewerId && independent?.reviewerId && domain.reviewerId === independent.reviewerId) issues.push('reviewers_not_independent');
  if (independent?.reviewerId && form.submission.assertionReviews.some(item => item.reviewerId === independent.reviewerId)) issues.push('independent_reviewer_authored_assertions');
  const decisions = [form.submission.licenseReview, form.submission.holdoutIsolationReview, ...form.submission.assertionReviews, ...form.submission.signoffs].map(item => item.decision);
  const status = issues.length ? 'invalid' : decisions.includes('rejected') ? 'rejected' : decisions.includes('changes_requested') ? 'changes_requested' : decisions.every(item => item === 'approved') ? 'ready_for_import' : 'pending';
  return { caseId: entry.caseId, status, issues: [...new Set(issues)] };
});
const count = (status: string) => results.filter(item => item.status === status).length;
const artifact = { schema: 'nexyfab.ground-truth-review-submission-validation.v1', releaseReady: count('ready_for_import') === results.length, summary: { forms: results.length, pending: count('pending'), invalid: count('invalid'), rejected: count('rejected'), changesRequested: count('changes_requested'), readyForImport: count('ready_for_import') }, results };
fs.mkdirSync(path.dirname(output), { recursive: true }); fs.writeFileSync(output, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8');
console.log(JSON.stringify({ output: path.relative(process.cwd(), output), ...artifact.summary, releaseReady: artifact.releaseReady }));
if (artifact.summary.invalid) process.exitCode = 4;
