import { describe, expect, it } from 'vitest';
import { validateAssembly } from '@/lib/assembly/assemblyState';
import { computeMateResidual } from '@/lib/assembly/iterativeSolver';
import { buildCadProductBundleManifest } from './cadCorpusProductBundle';
import { adaptCadNativeAssembly } from './cadNativeAssemblyAdapter';
import type { CadNativeAssemblyEvidence } from './cadNativeAssemblyEvidence';
const bytes = (value: string) => new TextEncoder().encode(value), I = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];
describe('native assembly solver adapter', () => {
  const bundle = buildCadProductBundleManifest([{ relativePath: 'set/robot.snapshot.1/root.SLDASM', bytes: bytes('asm') }, { relativePath: 'set/robot.snapshot.1/link.SLDPRT', bytes: bytes('part') }]), source = bundle.members.find(item => item.role === 'native_assembly')!;
  const evidence = (): CadNativeAssemblyEvidence => ({ schema: 'nexyfab.native-assembly-evidence.v1.1', lineageId: bundle.lineageId, extractor: { name: 'fixture', version: '1', cadSystem: 'fixture', cadVersion: null }, coordinateSystem: { handedness: 'right', upAxis: 'z', forwardAxis: '+x', matrixLayout: 'row-major', vectorConvention: 'column-vector', transformScope: 'local-to-parent' }, units: { length: 'mm', angle: 'deg' }, sources: [{ relativePath: source.relativePath, sha256: source.sha256 }], definitions: [{ id: 'base', name: 'Base', sourceMember: source.relativePath, kind: 'assembly' }, { id: 'link', name: 'Link', sourceMember: bundle.members.find(item => item.role === 'native_part')!.relativePath, kind: 'part' }], occurrences: [{ id: 'base-1', definitionId: 'base', parentOccurrenceId: null, transform: I, suppressed: false, state: { resolved: true, suppressed: false, lightweight: false, flexible: false, hidden: false } }, { id: 'link-1', definitionId: 'link', parentOccurrenceId: 'base-1', transform: [1, 0, 0, 10, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1], suppressed: false, state: { resolved: true, suppressed: false, lightweight: false, flexible: false, hidden: false } }], joints: [{ id: 'shoulder', type: 'revolute', parentOccurrenceId: 'base-1', childOccurrenceId: 'link-1', axis: [0, 0, 1], originMm: [10, 0, 0], lowerLimit: -90, upperLimit: 90, frame: 'world' }] });
  it('preserves occurrence poses and compiles an exact signed hinge', () => { const result = adaptCadNativeAssembly(bundle, evidence()); expect(result).toMatchObject({ status: 'pass', releaseReady: true, compiledJointIds: ['native:shoulder'], unresolvedJoints: [] }); expect(result.state!.parts[1]!.position).toEqual({ x: 10, y: 0, z: 0 }); validateAssembly(result.state!); const mate = result.state!.mates[0]!, parts = new Map(result.state!.parts.map(item => [item.id, item])); expect(computeMateResidual(mate, parts.get(mate.a.partId)!, parts.get(mate.b.partId)!, result.resolve!)).toBeLessThan(1e-9); });
  it('does not disguise unsupported prismatic joints as slots', () => { const input = evidence(); input.joints[0]!.type = 'prismatic'; const result = adaptCadNativeAssembly(bundle, input); expect(result).toMatchObject({ status: 'not_run', releaseReady: false, compiledJointIds: [], unresolvedJoints: [{ id: 'shoulder', type: 'prismatic', reason: 'native_joint_prismatic_unsupported' }] }); });
  it('requires governed v1.1 coordinate metadata', () => { const input = evidence(); input.schema = 'nexyfab.native-assembly-evidence.v1'; delete input.coordinateSystem; delete input.units; input.definitions.forEach(item => delete item.kind); input.occurrences.forEach(item => delete item.state); input.joints.forEach(item => delete item.frame); expect(adaptCadNativeAssembly(bundle, input)).toMatchObject({ status: 'not_run', errors: ['native_assembly_adapter_requires_v1.1'] }); });
  it('composes nested source transforms before converting inches to millimetres', () => { const input = evidence(); input.units = { length: 'in', angle: 'deg' }; input.occurrences[0]!.transform = [1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]; input.occurrences[1]!.transform = [1, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]; input.joints[0]!.originMm = [3, 0, 0]; const result = adaptCadNativeAssembly(bundle, input); expect(result.state!.parts[0]!.position.x).toBeCloseTo(25.4); expect(result.state!.parts[1]!.position.x).toBeCloseTo(76.2); expect(result.status).toBe('pass'); });
});
