export type NativeExtractionAxis = 'part_definitions' | 'body_membership' | 'occurrences' | 'hierarchy' | 'transforms' | 'joints' | 'units';
export interface ComplexNativeExtractionRequest { schema: 'nexyfab.complex-native-extraction-request.v1'; caseId: string; sourceHash: string; format: string; localLocator: string; requiredAxes: NativeExtractionAxis[]; }
export interface NativeExtractedDefinition { id: string; name: string; kind: 'assembly' | 'part'; bodyCount?: number; bodyCountSource?: 'native_shape_solids'; }
export interface NativeExtractedOccurrence { id: string; definitionId: string; parentOccurrenceId: string | null; localToParent: number[]; suppressed: boolean; }
export interface NativeExtractedJoint { id: string; parentOccurrenceId: string; childOccurrenceId: string; type: 'fixed' | 'revolute' | 'prismatic' | 'cylindrical' | 'planar' | 'spherical'; }
export interface ComplexNativeExtractionResult { schema: 'nexyfab.complex-native-extraction-result.v1'; caseId: string; sourceHash: string; artifactHash: string; sourceMember?: { path: string; sha256: string }; extractor: { name: string; version: string; cadSystem: string; }; units: { length: 'mm' | 'cm' | 'm' | 'in'; angle: 'deg' | 'rad' } | null; definitions: NativeExtractedDefinition[]; occurrences: NativeExtractedOccurrence[]; joints: NativeExtractedJoint[]; jointSemanticsComplete: boolean; }
export interface NativeExtractionAxisVerdict { axis: NativeExtractionAxis; status: 'pass' | 'fail' | 'not_run'; reason: string; measured?: number | string; artifactHashes: string[]; }
export interface ComplexNativeExtractionValidation { status: 'pass' | 'fail' | 'not_run'; releaseReady: boolean; errors: string[]; axes: NativeExtractionAxisVerdict[]; }
const SHA256 = /^[a-f0-9]{64}$/;
const dot = (a: number[], b: number[]) => a.reduce((sum, value, index) => sum + value * b[index]!, 0);
function rigid(matrix: number[]): boolean { if (matrix.length !== 16 || !matrix.every(Number.isFinite)) return false; const columns = [[matrix[0]!, matrix[4]!, matrix[8]!], [matrix[1]!, matrix[5]!, matrix[9]!], [matrix[2]!, matrix[6]!, matrix[10]!]]; return columns.every(column => Math.abs(dot(column, column) - 1) <= 1e-7) && Math.abs(dot(columns[0]!, columns[1]!)) <= 1e-7 && Math.abs(dot(columns[0]!, columns[2]!)) <= 1e-7 && Math.abs(dot(columns[1]!, columns[2]!)) <= 1e-7 && Math.abs(matrix[12]!) <= 1e-9 && Math.abs(matrix[13]!) <= 1e-9 && Math.abs(matrix[14]!) <= 1e-9 && Math.abs(matrix[15]! - 1) <= 1e-9; }
const verdict = (axis: NativeExtractionAxis, status: NativeExtractionAxisVerdict['status'], reason: string, artifactHashes: string[], measured?: number | string): NativeExtractionAxisVerdict => ({ axis, status, reason, artifactHashes, ...(measured === undefined ? {} : { measured }) });

export function validateComplexNativeExtraction(request: ComplexNativeExtractionRequest, result?: ComplexNativeExtractionResult): ComplexNativeExtractionValidation {
  if (!result) return { status: 'not_run', releaseReady: false, errors: [], axes: request.requiredAxes.map(axis => verdict(axis, 'not_run', 'Native extractor result is unavailable.', [])) };
  const errors: string[] = [], hashes = SHA256.test(result.artifactHash) ? [result.artifactHash] : [];
  if (request.caseId !== result.caseId) errors.push('native_extraction_case_mismatch');
  if (request.sourceHash !== result.sourceHash) errors.push('native_extraction_source_hash_mismatch');
  if (!SHA256.test(request.sourceHash) || !SHA256.test(result.artifactHash)) errors.push('native_extraction_hash_invalid');
  if (result.sourceMember && (!result.sourceMember.path.trim() || result.sourceMember.path.startsWith('/') || /^[a-z]:/i.test(result.sourceMember.path) || result.sourceMember.path.replaceAll('\\', '/').split('/').includes('..') || !SHA256.test(result.sourceMember.sha256))) errors.push('native_extraction_source_member_invalid');
  if (![result.extractor.name, result.extractor.version, result.extractor.cadSystem].every(value => value.trim())) errors.push('native_extraction_identity_missing');
  const definitions = new Set<string>(); for (const item of result.definitions) { if (!item.id.trim() || definitions.has(item.id)) errors.push(`native_definition_invalid:${item.id}`); definitions.add(item.id); if (item.bodyCount !== undefined && (!Number.isInteger(item.bodyCount) || item.bodyCount < 1 || item.kind !== 'part' || item.bodyCountSource !== 'native_shape_solids')) errors.push(`native_definition_body_count_invalid:${item.id}`); }
  const occurrences = new Set<string>(); for (const item of result.occurrences) { if (!item.id.trim() || occurrences.has(item.id)) errors.push(`native_occurrence_invalid:${item.id}`); occurrences.add(item.id); if (!definitions.has(item.definitionId)) errors.push(`native_occurrence_definition_missing:${item.id}`); if (!rigid(item.localToParent)) errors.push(`native_occurrence_transform_invalid:${item.id}`); }
  for (const item of result.occurrences) if (item.parentOccurrenceId && !occurrences.has(item.parentOccurrenceId)) errors.push(`native_occurrence_parent_missing:${item.id}`);
  const roots = result.occurrences.filter(item => item.parentOccurrenceId === null); if (result.occurrences.length && roots.length !== 1) errors.push(`native_occurrence_root_count:${roots.length}`);
  const parent = new Map(result.occurrences.map(item => [item.id, item.parentOccurrenceId])); for (const item of result.occurrences) { const seen = new Set<string>(); let cursor: string | null = item.id; while (cursor) { if (seen.has(cursor)) { errors.push(`native_occurrence_cycle:${item.id}`); break; } seen.add(cursor); cursor = parent.get(cursor) ?? null; } }
  const joints = new Set<string>(); for (const item of result.joints) { if (!item.id.trim() || joints.has(item.id)) errors.push(`native_joint_invalid:${item.id}`); joints.add(item.id); if (!occurrences.has(item.parentOccurrenceId) || !occurrences.has(item.childOccurrenceId) || item.parentOccurrenceId === item.childOccurrenceId) errors.push(`native_joint_occurrence_invalid:${item.id}`); }
  if (errors.length) return { status: 'fail', releaseReady: false, errors, axes: request.requiredAxes.map(axis => verdict(axis, 'fail', 'Native extraction contract validation failed.', hashes)) };
  const available: Record<NativeExtractionAxis, NativeExtractionAxisVerdict> = {
    part_definitions: result.definitions.length ? verdict('part_definitions', 'pass', 'Native definitions extracted.', hashes, result.definitions.length) : verdict('part_definitions', 'not_run', 'No native definitions extracted.', hashes),
    body_membership: result.definitions.some(item => item.kind === 'part') && result.definitions.filter(item => item.kind === 'part').every(item => item.bodyCount !== undefined) ? verdict('body_membership', 'pass', 'Every native part definition has extractor-owned solid membership evidence.', hashes, result.definitions.filter(item => item.kind === 'part').reduce((sum, item) => sum + item.bodyCount!, 0)) : verdict('body_membership', 'not_run', 'Native solid membership is missing for one or more part definitions.', hashes),
    occurrences: result.occurrences.length ? verdict('occurrences', 'pass', 'Native occurrences extracted.', hashes, result.occurrences.length) : verdict('occurrences', 'not_run', 'No native occurrences extracted.', hashes),
    hierarchy: result.occurrences.length && roots.length === 1 ? verdict('hierarchy', 'pass', 'Native occurrence hierarchy validated.', hashes, result.occurrences.length - 1) : verdict('hierarchy', 'not_run', 'Native hierarchy unavailable.', hashes),
    transforms: result.occurrences.length ? verdict('transforms', 'pass', 'Every native occurrence has a validated rigid local transform.', hashes, result.occurrences.length) : verdict('transforms', 'not_run', 'Native transforms unavailable.', hashes),
    joints: result.jointSemanticsComplete ? verdict('joints', 'pass', 'Native joint extraction declared complete.', hashes, result.joints.length) : verdict('joints', 'not_run', 'Extractor did not declare joint semantics complete.', hashes),
    units: result.units ? verdict('units', 'pass', 'Native unit metadata extracted.', hashes, `${result.units.length}/${result.units.angle}`) : verdict('units', 'not_run', 'Native units unavailable.', hashes),
  };
  const axes = request.requiredAxes.map(axis => available[axis]), status = axes.some(axis => axis.status === 'not_run') ? 'not_run' : 'pass';
  return { status, releaseReady: status === 'pass', errors, axes };
}
