import { describe, expect, it } from 'vitest';
import { validateComplexNativeExtraction, type ComplexNativeExtractionRequest, type ComplexNativeExtractionResult } from './complexNativeExtraction';
const h = (value: string) => value.repeat(64).slice(0, 64), identity = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];
const request: ComplexNativeExtractionRequest = { schema: 'nexyfab.complex-native-extraction-request.v1', caseId: 'robot-1', sourceHash: h('a'), format: 'sldasm', localLocator: 'robot/model.sldasm', requiredAxes: ['part_definitions', 'body_membership', 'occurrences', 'hierarchy', 'transforms', 'joints', 'units'] };
const result = (): ComplexNativeExtractionResult => ({ schema: 'nexyfab.complex-native-extraction-result.v1', caseId: 'robot-1', sourceHash: h('a'), artifactHash: h('b'), extractor: { name: 'sw-bridge', version: '1', cadSystem: 'SolidWorks' }, units: { length: 'mm', angle: 'deg' }, definitions: [{ id: 'root-def', name: 'Robot', kind: 'assembly' }, { id: 'arm-def', name: 'Arm', kind: 'part', bodyCount: 2, bodyCountSource: 'native_shape_solids' }], occurrences: [{ id: 'root', definitionId: 'root-def', parentOccurrenceId: null, localToParent: [...identity], suppressed: false }, { id: 'arm-1', definitionId: 'arm-def', parentOccurrenceId: 'root', localToParent: [...identity], suppressed: false }], joints: [{ id: 'j1', parentOccurrenceId: 'root', childOccurrenceId: 'arm-1', type: 'revolute' }], jointSemanticsComplete: true });
describe('complex native extraction contract', () => {
  it('keeps a missing extractor result as not_run', () => expect(validateComplexNativeExtraction(request)).toMatchObject({ status: 'not_run', releaseReady: false }));
  it('passes complete hash-bound native structure', () => expect(validateComplexNativeExtraction(request, result())).toMatchObject({ status: 'pass', releaseReady: true, errors: [] }));
  it('fails source mismatch and non-rigid transforms', () => { const value = result(); value.sourceHash = h('c'); value.occurrences[1]!.localToParent[0] = 2; expect(validateComplexNativeExtraction(request, value)).toMatchObject({ status: 'fail', errors: expect.arrayContaining(['native_extraction_source_hash_mismatch', 'native_occurrence_transform_invalid:arm-1']) }); });
  it('does not claim joint accuracy without complete joint semantics', () => { const value = result(); value.jointSemanticsComplete = false; expect(validateComplexNativeExtraction(request, value)).toMatchObject({ status: 'not_run', releaseReady: false, axes: expect.arrayContaining([expect.objectContaining({ axis: 'joints', status: 'not_run' })]) }); });
  it('keeps absent body membership evidence as not_run', () => { const value = result(); delete value.definitions[1]!.bodyCount; delete value.definitions[1]!.bodyCountSource; expect(validateComplexNativeExtraction(request, value)).toMatchObject({ status: 'not_run', axes: expect.arrayContaining([expect.objectContaining({ axis: 'body_membership', status: 'not_run' })]) }); });
  it('rejects invalid or unowned body counts', () => { const value = result(); value.definitions[1]!.bodyCount = 0; expect(validateComplexNativeExtraction(request, value)).toMatchObject({ status: 'fail', errors: ['native_definition_body_count_invalid:arm-def'] }); });
  it('rejects unsafe or unhashed archive member lineage', () => { const value = result(); value.sourceMember = { path: '../part.step', sha256: 'bad' }; expect(validateComplexNativeExtraction(request, value)).toMatchObject({ status: 'fail', errors: ['native_extraction_source_member_invalid'] }); });
});
