import{describe,expect,it}from'vitest';import{verifyAssemblyAnimationFrames,verifyAssemblyAnimationWithRecovery}from'./assemblyAnimationVerification';import{IDENTITY_QUAT,type AssemblyState}from'./assemblyState';import type{AssemblyAnimation}from'./assemblyAnimation';
const state:AssemblyState={parts:[{id:'a',name:'a',partTemplateId:'a',position:{x:0,y:0,z:0},orientation:IDENTITY_QUAT,fixed:true},{id:'b',name:'b',partTemplateId:'b',position:{x:20,y:0,z:0},orientation:IDENTITY_QUAT}],mates:[]};const animation:AssemblyAnimation={version:1,name:'hit',fps:30,startFrame:0,endFrame:10,tracks:[{id:'b',targetPartId:'b',keyframes:[{frame:0,position:{x:20,y:0,z:0}},{frame:10,position:{x:0,y:0,z:0}}]}]};const box={min:{x:-2,y:-2,z:-2},max:{x:2,y:2,z:2}};
describe('animation frame verification',()=>{it('finds the first conservative collision frame',()=>{const r=verifyAssemblyAnimationFrames(state,animation,new Map([['a',box],['b',box]]));expect(r.verified).toBe(true);expect(r.collisionFree).toBe(false);expect(r.firstFailureFrame).not.toBeNull();expect(r.frames.at(-1)!.status).toBe('failed');});it('catches translation tunneling continuously between collision-free sampled endpoints',()=>{const passThrough:AssemblyAnimation={...animation,tracks:[{id:'b',targetPartId:'b',keyframes:[{frame:0,position:{x:-20,y:0,z:0}},{frame:10,position:{x:20,y:0,z:0}}]}]};const r=verifyAssemblyAnimationFrames(state,passThrough,new Map([['a',box],['b',box]]),{frameStep:10});expect(r.frames.every(frame=>frame.status==='passed')).toBe(true);expect(r.collisionFree).toBe(false);expect(r.continuous.candidates[0]).toMatchObject({partA:'a',partB:'b',method:'exact-linear-aabb'});});it('always includes intermediate keyframes so a path reversal cannot hide between coarse samples',()=>{const turn:AssemblyAnimation={...animation,tracks:[{id:'b',targetPartId:'b',keyframes:[{frame:0,position:{x:-20,y:0,z:0}},{frame:5,position:{x:20,y:0,z:0}},{frame:10,position:{x:-20,y:0,z:0}}]}]};const r=verifyAssemblyAnimationFrames(state,turn,new Map([['a',box],['b',box]]),{frameStep:10});expect(r.frames.map(frame=>frame.frame)).toEqual([0,5,10]);expect(r.continuous.candidates.length).toBe(2);});it('fails closed without geometry',()=>expect(verifyAssemblyAnimationFrames(state,animation,null).verified).toBe(false));});

describe('adaptive rotational CCD',()=>{
  const thin={min:{x:-5,y:-0.1,z:-0.1},max:{x:5,y:0.1,z:0.1}},small={min:{x:-0.1,y:-0.1,z:-0.1},max:{x:0.1,y:0.1,z:0.1}};
  const rotation=(x:number,y:number):{state:AssemblyState;animation:AssemblyAnimation}=>({state:{parts:[{id:'a',name:'a',partTemplateId:'a',position:{x,y,z:0},orientation:IDENTITY_QUAT,fixed:true},{id:'b',name:'b',partTemplateId:'b',position:{x:0,y:0,z:0},orientation:IDENTITY_QUAT}],mates:[]},animation:{version:1,name:'rotate',fps:30,startFrame:0,endFrame:10,tracks:[{id:'b',targetPartId:'b',keyframes:[{frame:0,orientation:IDENTITY_QUAT},{frame:10,orientation:{x:0,y:0,z:1,w:0}}]}]}});
  it('proves clear outside the swept radius instead of reporting the old sphere-envelope false positive',()=>{const input=rotation(4,4);const r=verifyAssemblyAnimationFrames(input.state,input.animation,new Map([['a',small],['b',thin]]),{frameStep:10});expect(r.verified).toBe(true);expect(r.collisionFree).toBe(true);expect(r.continuous.candidates).toEqual([]);});
  it('fails closed when the configured subdivision budget cannot decide a rotational interval',()=>{const input=rotation(3,3);const r=verifyAssemblyAnimationFrames(input.state,input.animation,new Map([['a',small],['b',thin]]),{frameStep:10,rotationalMaxDepth:0});expect(r.verified).toBe(false);expect(r.collisionFree).toBe(false);expect(r.continuous.unresolved[0]).toMatchObject({method:'adaptive-rotational-aabb',status:'unresolved',depth:0});});
  it('does not mistake one midpoint candidate for coverage of the surrounding interval',()=>{const input=rotation(0,3);const r=verifyAssemblyAnimationFrames(input.state,input.animation,new Map([['a',small],['b',thin]]),{frameStep:10,rotationalMaxDepth:0});expect(r.continuous.candidates.some(item=>item.status==='confirmed'&&item.startFrame===5&&item.endFrame===5)).toBe(true);expect(r.continuous.unresolved).toHaveLength(1);expect(r.verified).toBe(false);});
  it('automatically refines only the unresolved interval depth with a bounded evidence trail',()=>{const input=rotation(4,4);const r=verifyAssemblyAnimationWithRecovery(input.state,input.animation,new Map([['a',small],['b',thin]]),{frameStep:10,rotationalMaxDepth:0,rotationalDepthSchedule:[0,4,8]});expect(r.exhausted).toBe(false);expect(r.verification.collisionFree).toBe(true);expect(r.attempts.length).toBeGreaterThan(1);expect(r.attempts[0]!.unresolvedAfter).toBeGreaterThan(0);expect(r.attempts.at(-1)).toMatchObject({unresolvedAfter:0});});
  it('records exhaustion instead of looping when refinement cannot prove clearance',()=>{const input=rotation(3,3);const r=verifyAssemblyAnimationWithRecovery(input.state,input.animation,new Map([['a',small],['b',thin]]),{frameStep:10,rotationalMaxDepth:0,rotationalDepthSchedule:[0,1]});expect(r.exhausted).toBe(true);expect(r.attempts.map(x=>x.rotationalMaxDepth)).toEqual([0,1]);expect(r.verification.verified).toBe(false);});
});
