import { toIsoLang, type IsoLang } from '@/lib/i18n/normalize';
import type { DfmPdfGeometryInput } from './dfmPdfContract';

export interface DfmPdfCopy {
  reportTitle: string;
  untitledProject: string;
  user: string;
  bbox: string;
  volume: string;
  surface: string;
  triangles: string;
  feasible: string;
  notFeasible: string;
  noIssues: string;
  error: string;
  warning: string;
  info: string;
  freePlan: string;
  page: string;
  generatedBy: string;
  difficulties: Readonly<Record<'low' | 'moderate' | 'high', string>>;
}

const COPY: Readonly<Record<IsoLang, DfmPdfCopy>> = {
  ko: { reportTitle: '제조 가능성 분석 보고서', untitledProject: '제목 없는 프로젝트', user: '사용자', bbox: '경계 상자', volume: '부피', surface: '표면적', triangles: '삼각형', feasible: '제조 가능', notFeasible: '제조 불가', noIssues: '발견된 문제가 없습니다.', error: '오류', warning: '경고', info: '정보', freePlan: '무료 플랜', page: '페이지', generatedBy: 'NexyFab 생성', difficulties: { low: '낮음', moderate: '보통', high: '높음' } },
  en: { reportTitle: 'DFM Analysis Report', untitledProject: 'Untitled project', user: 'User', bbox: 'Bounding box', volume: 'Volume', surface: 'Surface area', triangles: 'triangles', feasible: 'Feasible', notFeasible: 'Not feasible', noIssues: 'No issues detected.', error: 'Error', warning: 'Warning', info: 'Info', freePlan: 'Free plan', page: 'Page', generatedBy: 'Generated by NexyFab', difficulties: { low: 'Low', moderate: 'Moderate', high: 'High' } },
  ja: { reportTitle: '製造性解析レポート', untitledProject: '無題のプロジェクト', user: 'ユーザー', bbox: '境界ボックス', volume: '体積', surface: '表面積', triangles: '三角形', feasible: '製造可能', notFeasible: '製造不可', noIssues: '問題は検出されませんでした。', error: 'エラー', warning: '警告', info: '情報', freePlan: '無料プラン', page: 'ページ', generatedBy: 'NexyFabで生成', difficulties: { low: '低', moderate: '中', high: '高' } },
  zh: { reportTitle: '可制造性分析报告', untitledProject: '未命名项目', user: '用户', bbox: '包围盒', volume: '体积', surface: '表面积', triangles: '三角形', feasible: '可制造', notFeasible: '不可制造', noIssues: '未检测到问题。', error: '错误', warning: '警告', info: '信息', freePlan: '免费方案', page: '页', generatedBy: '由NexyFab生成', difficulties: { low: '低', moderate: '中', high: '高' } },
  es: { reportTitle: 'Informe de análisis DFM', untitledProject: 'Proyecto sin título', user: 'Usuario', bbox: 'Caja delimitadora', volume: 'Volumen', surface: 'Área superficial', triangles: 'triángulos', feasible: 'Fabricable', notFeasible: 'No fabricable', noIssues: 'No se detectaron problemas.', error: 'Error', warning: 'Advertencia', info: 'Información', freePlan: 'Plan gratuito', page: 'Página', generatedBy: 'Generado por NexyFab', difficulties: { low: 'Baja', moderate: 'Moderada', high: 'Alta' } },
  ar: { reportTitle: 'تقرير تحليل قابلية التصنيع', untitledProject: 'مشروع بلا عنوان', user: 'المستخدم', bbox: 'الصندوق المحيط', volume: 'الحجم', surface: 'مساحة السطح', triangles: 'مثلثات', feasible: 'قابل للتصنيع', notFeasible: 'غير قابل للتصنيع', noIssues: 'لم تُكتشف مشكلات.', error: 'خطأ', warning: 'تحذير', info: 'معلومة', freePlan: 'الخطة المجانية', page: 'صفحة', generatedBy: 'تم الإنشاء بواسطة NexyFab', difficulties: { low: 'منخفضة', moderate: 'متوسطة', high: 'مرتفعة' } },
};

const LOCALE_TAG: Readonly<Record<IsoLang, string>> = { ko: 'ko-KR', en: 'en-US', ja: 'ja-JP', zh: 'zh-CN', es: 'es-ES', ar: 'ar' };

export function resolveDfmPdfLocale(explicit: string | undefined, acceptLanguage: string | null): IsoLang {
  return toIsoLang(explicit || acceptLanguage?.split(',')[0]);
}

export function getDfmPdfCopy(locale: IsoLang): DfmPdfCopy {
  return COPY[locale];
}

export function formatDfmPdfDate(value: string | undefined, locale: IsoLang): string {
  const date = new Date(value ?? Date.now());
  return new Intl.DateTimeFormat(LOCALE_TAG[locale], { dateStyle: 'medium', timeStyle: 'short' }).format(date);
}

export function formatDfmPdfNumber(value: number, locale: IsoLang, maximumFractionDigits = 2): string {
  return new Intl.NumberFormat(LOCALE_TAG[locale], { maximumFractionDigits, minimumFractionDigits: 0 }).format(value);
}

export function formatDfmPdfFacts(geometry: DfmPdfGeometryInput, locale: IsoLang): string[] {
  const copy = COPY[locale];
  return [
    geometry.bbox && `${copy.bbox}: ${formatDfmPdfNumber(geometry.bbox.w, locale, 1)} × ${formatDfmPdfNumber(geometry.bbox.h, locale, 1)} × ${formatDfmPdfNumber(geometry.bbox.d, locale, 1)} mm`,
    typeof geometry.volume_cm3 === 'number' && `${copy.volume}: ${formatDfmPdfNumber(geometry.volume_cm3, locale)} cm³`,
    typeof geometry.surface_area_cm2 === 'number' && `${copy.surface}: ${formatDfmPdfNumber(geometry.surface_area_cm2, locale)} cm²`,
    typeof geometry.triangleCount === 'number' && `${formatDfmPdfNumber(geometry.triangleCount, locale, 0)} ${copy.triangles}`,
  ].filter((value): value is string => Boolean(value));
}

export function formatDfmPdfDifficulty(value: string, locale: IsoLang): string {
  const normalized = value.trim().toLowerCase();
  if (/^(?:low|easy)$/.test(normalized)) return COPY[locale].difficulties.low;
  if (/^(?:medium|moderate|normal)$/.test(normalized)) return COPY[locale].difficulties.moderate;
  if (/^(?:high|hard|difficult|very hard)$/.test(normalized)) return COPY[locale].difficulties.high;
  return value;
}

export function dfmPdfSeverityLabel(severity: 'error' | 'warning' | 'info', locale: IsoLang): string {
  return COPY[locale][severity];
}
