// Deterministic draft emitter: intent → OpenSCAD text (methodology §2, §6.2).
//
// This is the DRAFT kernel path — fast preview, vision critique, drawing
// checkpoint. Record-kernel-only features (fillet/shell, routed 'occt' by
// routeFeature) are emitted as `// @nfab` tag comments in the existing
// emitScadFromFeatures convention: the geometry is omitted here and built
// exactly by the OCCT emitter from the SAME intent (§6 — geometry is never
// handed between kernels; intent is re-emitted).
//
// Determinism rules:
//   - No randomness, no dates: same intent → byte-identical SCAD. This is
//     what makes content-hash caching possible (§13 #2).
//   - Numbers formatted to ≤4 decimals with trailing zeros stripped.
//   - Domain assertions (cone angle, DFM gates) run in the TS verify layer
//     BEFORE emission — not as SCAD assert(), which would be unverifiable
//     decoration (the fake-assert trap).

import type {
  AssemblyIntent,
  ComponentIntent,
  IntentFeature,
  Placement,
  Profile2D,
} from './schema';
import { routeFeature } from './schema';

const INDENT = '  ';
const DEFAULT_FN = 96;

export function fmt(n: number): string {
  if (!Number.isFinite(n)) throw new Error(`emitOpenScad: non-finite number ${n}`);
  const r = Math.round(n * 10000) / 10000;
  return Object.is(r, -0) ? '0' : r.toString();
}

function emitPolygon(profile: Profile2D): string {
  const pts = profile.points.map((p) => `[${fmt(p.x)}, ${fmt(p.y)}]`).join(', ');
  return `polygon(points=[${pts}]);`;
}

function wrapPlacement(at: Placement | undefined, body: string): string {
  let out = body;
  if (at?.rotateDeg) {
    const [rx, ry, rz] = at.rotateDeg;
    if (rx || ry || rz) out = `rotate([${fmt(rx)}, ${fmt(ry)}, ${fmt(rz)}]) ${out}`;
  } else if (at?.rotateZDeg) {
    out = `rotate([0, 0, ${fmt(at.rotateZDeg)}]) ${out}`;
  }
  if (at?.translate) {
    const [x, y, z] = at.translate;
    out = `translate([${fmt(x)}, ${fmt(y)}, ${fmt(z)}]) ${out}`;
  }
  return out;
}

function emitFeature(f: IntentFeature, fn: number): string[] {
  // Record-kernel features: tag, don't build (§6.2 draft omission).
  if (routeFeature(f) === 'occt') {
    if (f.kind === 'fillet') {
      return [
        `// @nfab fillet radius=${fmt(f.radius)} source=${f.selector.sourceFeature} ` +
        `filter=${f.selector.filter}`,
      ];
    }
    if (f.kind === 'shell') {
      return [`// @nfab shell thickness=${fmt(f.thickness)}`];
    }
    return [`// @nfab ${f.kind} (record-kernel only)`];
  }

  let core: string;
  switch (f.kind) {
    case 'revolve':
      core =
        `rotate_extrude(angle=${fmt(f.angleDeg ?? 360)}, $fn=${fn}) ` +
        emitPolygon(f.profile);
      break;
    case 'extrude':
      core = `linear_extrude(height=${fmt(f.height)}) ` + emitPolygon(f.profile);
      break;
    case 'cylinder':
      core =
        `cylinder(h=${fmt(f.height)}, d=${fmt(f.diameter)}, ` +
        `center=${f.centered ? 'true' : 'false'}, $fn=${fn});`;
      break;
    case 'sphere':
      core = `sphere(d=${fmt(f.diameter)}, $fn=${fn});`;
      break;
    case 'fillet':
    case 'shell':
      // routeFeature() diverted these above; reaching here is a router bug.
      throw new Error(`emitOpenScad: ${f.kind} is record-kernel-only (router bug)`);
  }

  const placed = wrapPlacement(f.at, core);

  if (f.pattern?.type === 'circular' && f.pattern.count > 1) {
    const sweep = f.pattern.sweepDeg ?? 360;
    const step = sweep / f.pattern.count;
    return [
      `for (a = [0 : ${fmt(step)} : ${fmt(sweep - step)}])`,
      `${INDENT}rotate([0, 0, a]) ${placed}`,
    ];
  }
  return [placed];
}

function scadIdent(id: string): string {
  return id.replace(/[^A-Za-z0-9_]/g, '_');
}

export function emitComponent(c: ComponentIntent, fn = DEFAULT_FN): string {
  const lines: string[] = [];
  lines.push(`// component: ${c.name} (${c.shapeClass})`);
  if (c.material) lines.push(`// material: ${c.material.grade}${c.material.thicknessMm ? ` ${c.material.thicknessMm}t` : ''}`);
  lines.push(`module comp_${scadIdent(c.id)}() {`);
  lines.push(`${INDENT}union() {`);
  for (const f of c.features) {
    for (const line of emitFeature(f, fn)) lines.push(`${INDENT}${INDENT}${line}`);
  }
  lines.push(`${INDENT}}`);
  lines.push(`}`);
  return lines.join('\n');
}

export interface EmitAssemblyOpts {
  fn?: number;
  /** Extra header lines (drawing ref, spec source) — MUST be deterministic. */
  headerComments?: string[];
}

export function emitAssembly(a: AssemblyIntent, opts: EmitAssemblyOpts = {}): string {
  const fn = opts.fn ?? DEFAULT_FN;
  const lines: string[] = [];
  lines.push(`// ${a.name} — generated by NexyFab intent emitter (draft kernel)`);
  lines.push(`// methodology: docs/drawing-to-3d-methodology.md`);
  for (const h of opts.headerComments ?? []) lines.push(`// ${h}`);
  lines.push(`$fn = ${fn};`);
  lines.push('');

  for (const pc of a.components) {
    lines.push(emitComponent(pc.component, fn));
    lines.push('');
  }

  lines.push(`// assembly`);
  for (const pc of a.components) {
    lines.push(wrapPlacement(pc.at, `comp_${scadIdent(pc.component.id)}();`));
  }

  // Joints are validation data (§12.7.3), not geometry — record for
  // downstream checkers and human readers.
  for (const j of a.joints) {
    const band = j.allowedPenetrationMm
      ? ` band=[${fmt(j.allowedPenetrationMm[0])}, ${fmt(j.allowedPenetrationMm[1])}]`
      : '';
    lines.push(`// @nfab joint type=${j.type} a=${j.a} b=${j.b}${band}`);
  }

  return lines.join('\n') + '\n';
}
