/**
 * 엔지니어링 검증 버티컬 섹션 사전 (라이브 데모·분야 카드·검증 숫자·개발자/API·FAQ).
 * 정직성 원칙: 모든 숫자는 실측(골든벤치 37/37, 공표예제 재현 6건, KDS 현행 10종,
 * 코퍼스 7,579청크) — 근거 없는 마케팅 수치 금지 (feedback_landing_no_mock).
 */
export const engDict = {
  ko: {
    // ── 라이브 데모 패널 ──
    demoKicker: 'LIVE DEMO — 지금 바로 실행',
    demoTitle: '구조 검토를 계산기처럼',
    demoSub: '가입 없이 실제 검증 엔진을 호출합니다. 결과에는 KDS 근거 조항이 함께 표시됩니다.',
    demoTabBeam: 'H형강 단순보 검토',
    demoTabWall: '옹벽 안정 검토',
    fldSection: '단면 (KS D 3502)',
    fldSpan: '지간 L (m)',
    fldLoad: '등분포하중 w (kN/m)',
    fldWallH: '벽 높이 H (m)',
    fldPhi: '뒤채움 내부마찰각 φ (°)',
    fldGamma: '뒤채움 단위중량 γ (kN/m³)',
    fldSurcharge: '상재하중 q (kPa)',
    fldBearing: '허용지지력 (kPa)',
    runBtn: '검토 실행',
    running: '계산 중…',
    verdictPass: '만족 (PASS)',
    verdictFail: '불만족 (FAIL)',
    checkNames: { bending: '휨', shear: '전단', deflection: '처짐', overturning: '전도', sliding: '활동', eccentricity: '편심', bearing: '지지력' } as Record<string, string>,
    usageLabel: '사용률',
    demoQuota: '오늘 남은 데모 호출: {n}회',
    demoRefs: '근거 조항',
    demoError: '요청 실패 — 잠시 후 다시 시도해 주세요',
    demoDisclaimer: '구조 검토 참고자료(비법정). 법정 계산서는 기술사 날인 영역입니다.',
    // ── 분야 카드 ──
    domKicker: 'DOMAINS',
    domTitle: '지금 실제로 돌아가는 분야만 보여드립니다',
    domSub: '준비 중인 칸은 만들지 않습니다. 카드가 있다면 계산기·코퍼스·API가 라이브라는 뜻입니다.',
    domLive: 'LIVE',
    dom1Title: '기계·장비 설계 → 제조',
    dom1Desc: '브라우저 3D 설계, AI DFM 분석, 제조사 연결까지 — NexyFab의 본업.',
    dom1Tags: ['#3D모델러', '#DFM분석', '#견적·발주'],
    dom2Title: '가설구조·랙',
    dom2Desc: '랙 프레임 2D 해석 + 포스트 좌굴·빔 휨·수평변위 검토를 한 번에.',
    dom2Tags: ['#랙프레임검토', '#frame2d해석', '#단면최적화'],
    dom3Title: '토목 — 옹벽·강구조',
    dom3Desc: 'Rankine 옹벽 안정(전도·활동·지지력), 기둥 좌굴, 볼트 접합 — KDS 조항 인용 포함.',
    dom3Tags: ['#옹벽안정', '#기둥좌굴', '#볼트접합'],
    // ── 검증 숫자 + 개발자/API ──
    devKicker: 'VERIFIED · AI-NATIVE',
    devTitle: '고객 자랑 대신, 검증을 자랑합니다',
    devSub: '계산은 LLM이 아니라 결정론 엔진이 수행하고, 모든 결과에 기준 조항이 인용됩니다.',
    ver1Num: '37/37', ver1Label: '골든벤치 테스트 통과',
    ver2Num: '6건', ver2Label: '공표 예제 재현 검증',
    ver3Num: '10종', ver3Label: 'KDS 현행 기준 원문 대조',
    ver4Num: '7,579', ver4Label: '검증 코퍼스 청크',
    devCurlTitle: 'REST API — 당신의 코드에서',
    devMcpTitle: 'MCP — 당신의 AI에서',
    devMcpDesc: 'Claude 등 AI 에이전트에 MCP 서버로 연결하면, AI가 계산기 8종과 기준 검색을 도구로 씁니다. 계산은 항상 결정론 엔진이 수행합니다.',
    devKeyCta: 'API 키 문의',
    devAttribution: 'KDS 원문: 국가건설기준센터(국토교통부), 공공누리 제1유형 · 미 연방 간행물: 퍼블릭 도메인',
    // ── FAQ ──
    faqTitle: '자주 묻는 질문',
    faqs: [
      { q: '계산 결과를 법정 구조계산서로 쓸 수 있나요?', a: '아니요. NexyFab의 결과는 구조 검토 참고자료(비법정)입니다. 인허가용 법정 계산서는 기술사 날인 영역이며, 모든 응답에 이 한계가 명시됩니다.' },
      { q: '어떤 설계기준을 지원하나요?', a: 'KDS 현행 기준 10종(강구조·옹벽 등)을 원문 대조로 탑재했고 AISC 360, AASHTO LRFD를 선택할 수 있습니다. 결과에는 근거 조항 번호가 함께 인용됩니다.' },
      { q: 'AI가 계산하나요? 믿을 수 있나요?', a: '계산 자체는 AI가 아니라 결정론 엔진이 수행합니다. AI는 입력 구성과 결과 해석을 돕는 역할입니다. 엔진은 골든벤치 37케이스와 공표 예제 재현 6건으로 검증됐습니다.' },
      { q: '우리 서비스나 AI에 연동할 수 있나요?', a: '네. REST API(API 키)와 MCP 서버 두 가지로 연동합니다. 계산기 목록·입력 스키마를 API가 제공하므로 function-calling 도구 스펙을 자동 생성할 수 있습니다.' },
    ],
  },
  en: {
    demoKicker: 'LIVE DEMO — run it now',
    demoTitle: 'Structural checks, as easy as a calculator',
    demoSub: 'No sign-up — this calls the real verification engine. Results cite the governing KDS clauses.',
    demoTabBeam: 'H-beam simple beam check',
    demoTabWall: 'Retaining wall stability',
    fldSection: 'Section (KS D 3502)',
    fldSpan: 'Span L (m)',
    fldLoad: 'UDL w (kN/m)',
    fldWallH: 'Wall height H (m)',
    fldPhi: 'Backfill friction angle φ (°)',
    fldGamma: 'Backfill unit weight γ (kN/m³)',
    fldSurcharge: 'Surcharge q (kPa)',
    fldBearing: 'Allowable bearing (kPa)',
    runBtn: 'Run check',
    running: 'Computing…',
    verdictPass: 'PASS',
    verdictFail: 'FAIL',
    checkNames: { bending: 'Bending', shear: 'Shear', deflection: 'Deflection', overturning: 'Overturning', sliding: 'Sliding', eccentricity: 'Eccentricity', bearing: 'Bearing' } as Record<string, string>,
    usageLabel: 'Utilization',
    demoQuota: 'Demo calls left today: {n}',
    demoRefs: 'Code references',
    demoError: 'Request failed — please try again shortly',
    demoDisclaimer: 'Engineering reference only (non-statutory). Sealed calculations remain the domain of licensed engineers.',
    domKicker: 'DOMAINS',
    domTitle: 'We only show domains that actually run today',
    domSub: 'No "coming soon" tiles. If a card exists, its calculators, corpus, and API are live.',
    domLive: 'LIVE',
    dom1Title: 'Machinery — design to manufacturing',
    dom1Desc: 'Browser 3D design, AI DFM analysis, and manufacturer matching — the NexyFab core.',
    dom1Tags: ['#3DModeler', '#DFM', '#RFQ'],
    dom2Title: 'Temporary structures & racks',
    dom2Desc: '2D rack-frame analysis with post buckling, beam bending, and sway checks in one call.',
    dom2Tags: ['#RackFrame', '#Frame2D', '#SectionOptimizer'],
    dom3Title: 'Civil — retaining walls & steel',
    dom3Desc: 'Rankine wall stability (overturning/sliding/bearing), column buckling, bolted connections — with KDS clause citations.',
    dom3Tags: ['#RetainingWall', '#ColumnBuckling', '#BoltedJoint'],
    devKicker: 'VERIFIED · AI-NATIVE',
    devTitle: 'We brag about verification, not customers',
    devSub: 'A deterministic engine does the math — never an LLM — and every result cites its code clause.',
    ver1Num: '37/37', ver1Label: 'golden-bench tests passing',
    ver2Num: '6', ver2Label: 'published examples reproduced',
    ver3Num: '10', ver3Label: 'current KDS codes cross-checked',
    ver4Num: '7,579', ver4Label: 'verified corpus chunks',
    devCurlTitle: 'REST API — from your code',
    devMcpTitle: 'MCP — from your AI',
    devMcpDesc: 'Connect the MCP server to Claude or any agent: the AI gets 8 calculators and code search as tools, while a deterministic engine always does the math.',
    devKeyCta: 'Request an API key',
    devAttribution: 'KDS source: KCSC (MOLIT), KOGL Type 1 · US federal publications: public domain',
    faqTitle: 'Frequently asked questions',
    faqs: [
      { q: 'Can I use the results as sealed structural calculations?', a: 'No. NexyFab outputs are non-statutory engineering references. Sealed calculations for permits remain the domain of licensed engineers, and every response states this limit.' },
      { q: 'Which design codes are supported?', a: '10 current KDS codes (steel, retaining walls, and more), cross-checked against the official text, plus AISC 360 and AASHTO LRFD. Every result cites its governing clause.' },
      { q: 'Does an AI do the math? Can I trust it?', a: 'No — a deterministic engine performs all calculations; AI only assists with input setup and interpretation. The engine passes 37 golden-bench cases and reproduces 6 published worked examples.' },
      { q: 'Can I integrate it into my service or AI?', a: 'Yes, via REST API (API key) or the MCP server. The API exposes calculator lists and input schemas, so you can auto-generate function-calling tool specs.' },
    ],
  },
  ja: {
    demoKicker: 'LIVE DEMO — 今すぐ実行',
    demoTitle: '構造チェックを電卓のように',
    demoSub: '登録不要で実際の検証エンジンを呼び出します。結果には根拠となるKDS条項が表示されます。',
    demoTabBeam: 'H形鋼 単純梁チェック',
    demoTabWall: '擁壁 安定チェック',
    fldSection: '断面 (KS D 3502)',
    fldSpan: 'スパン L (m)',
    fldLoad: '等分布荷重 w (kN/m)',
    fldWallH: '壁高 H (m)',
    fldPhi: '裏込め内部摩擦角 φ (°)',
    fldGamma: '裏込め単位体積重量 γ (kN/m³)',
    fldSurcharge: '上載荷重 q (kPa)',
    fldBearing: '許容支持力 (kPa)',
    runBtn: 'チェック実行',
    running: '計算中…',
    verdictPass: 'OK (PASS)',
    verdictFail: 'NG (FAIL)',
    checkNames: { bending: '曲げ', shear: 'せん断', deflection: 'たわみ', overturning: '転倒', sliding: '滑動', eccentricity: '偏心', bearing: '支持力' } as Record<string, string>,
    usageLabel: '使用率',
    demoQuota: '本日の残りデモ回数: {n}回',
    demoRefs: '根拠条項',
    demoError: 'リクエスト失敗 — 少し待って再試行してください',
    demoDisclaimer: '構造検討の参考資料(非法定)。法定計算書は技術士の押印領域です。',
    domKicker: 'DOMAINS',
    domTitle: '実際に稼働している分野だけを表示します',
    domSub: '「準備中」の枠は作りません。カードがあれば計算機・コーパス・APIが稼働中です。',
    domLive: 'LIVE',
    dom1Title: '機械・装置 設計→製造',
    dom1Desc: 'ブラウザ3D設計、AI DFM分析、製造パートナー接続 — NexyFabの本業。',
    dom1Tags: ['#3Dモデラー', '#DFM分析', '#見積・発注'],
    dom2Title: '仮設構造・ラック',
    dom2Desc: 'ラックフレーム2D解析+支柱座屈・梁曲げ・水平変位チェックを一度に。',
    dom2Tags: ['#ラック検討', '#Frame2D解析', '#断面最適化'],
    dom3Title: '土木 — 擁壁・鋼構造',
    dom3Desc: 'Rankine擁壁安定(転倒・滑動・支持力)、柱座屈、ボルト接合 — KDS条項引用付き。',
    dom3Tags: ['#擁壁安定', '#柱座屈', '#ボルト接合'],
    devKicker: 'VERIFIED · AI-NATIVE',
    devTitle: '顧客自慢の代わりに、検証を自慢します',
    devSub: '計算はLLMではなく決定論エンジンが実行し、全結果に基準条項が引用されます。',
    ver1Num: '37/37', ver1Label: 'ゴールデンベンチ通過',
    ver2Num: '6件', ver2Label: '公表例題の再現検証',
    ver3Num: '10種', ver3Label: 'KDS現行基準の原文照合',
    ver4Num: '7,579', ver4Label: '検証コーパスチャンク',
    devCurlTitle: 'REST API — あなたのコードから',
    devMcpTitle: 'MCP — あなたのAIから',
    devMcpDesc: 'MCPサーバーをClaude等のAIエージェントに接続すると、AIが計算機8種と基準検索をツールとして使えます。計算は常に決定論エンジンが実行します。',
    devKeyCta: 'APIキーのお問い合わせ',
    devAttribution: 'KDS原文: 国家建設基準センター(国土交通部)、公共ヌリ第1類型 · 米連邦刊行物: パブリックドメイン',
    faqTitle: 'よくある質問',
    faqs: [
      { q: '計算結果を法定構造計算書として使えますか?', a: 'いいえ。NexyFabの結果は非法定の参考資料です。許認可用の法定計算書は技術士の押印領域であり、全応答にこの限界が明示されます。' },
      { q: 'どの設計基準に対応していますか?', a: 'KDS現行基準10種(鋼構造・擁壁など)を原文照合で搭載し、AISC 360、AASHTO LRFDも選択できます。結果には根拠条項番号が引用されます。' },
      { q: 'AIが計算するのですか?信頼できますか?', a: '計算自体はAIではなく決定論エンジンが実行します。AIは入力構成と結果解釈の補助役です。エンジンはゴールデンベンチ37ケースと公表例題再現6件で検証済みです。' },
      { q: '自社サービスやAIに連携できますか?', a: 'はい。REST API(APIキー)とMCPサーバーの2通りです。APIが計算機一覧・入力スキーマを提供するため、function-callingツール仕様を自動生成できます。' },
    ],
  },
  cn: {
    demoKicker: 'LIVE DEMO — 立即运行',
    demoTitle: '结构验算,像计算器一样简单',
    demoSub: '无需注册,直接调用真实验证引擎。结果附带 KDS 依据条款。',
    demoTabBeam: 'H型钢简支梁验算',
    demoTabWall: '挡土墙稳定验算',
    fldSection: '截面 (KS D 3502)',
    fldSpan: '跨度 L (m)',
    fldLoad: '均布荷载 w (kN/m)',
    fldWallH: '墙高 H (m)',
    fldPhi: '回填内摩擦角 φ (°)',
    fldGamma: '回填重度 γ (kN/m³)',
    fldSurcharge: '超载 q (kPa)',
    fldBearing: '容许承载力 (kPa)',
    runBtn: '运行验算',
    running: '计算中…',
    verdictPass: '满足 (PASS)',
    verdictFail: '不满足 (FAIL)',
    checkNames: { bending: '弯曲', shear: '剪切', deflection: '挠度', overturning: '倾覆', sliding: '滑移', eccentricity: '偏心', bearing: '承载力' } as Record<string, string>,
    usageLabel: '利用率',
    demoQuota: '今日剩余演示次数: {n}',
    demoRefs: '依据条款',
    demoError: '请求失败 — 请稍后重试',
    demoDisclaimer: '结构验算参考资料(非法定)。法定计算书属注册工程师盖章范畴。',
    domKicker: 'DOMAINS',
    domTitle: '只展示今天真正可用的领域',
    domSub: '不做"敬请期待"的空格子。有卡片,就意味着计算器、语料库和 API 均已上线。',
    domLive: 'LIVE',
    dom1Title: '机械·装备 设计→制造',
    dom1Desc: '浏览器3D设计、AI DFM分析、制造商对接 — NexyFab 的主业。',
    dom1Tags: ['#3D建模', '#DFM分析', '#询价下单'],
    dom2Title: '临时结构·货架',
    dom2Desc: '货架框架2D解析+立柱屈曲·横梁弯曲·水平位移验算一次完成。',
    dom2Tags: ['#货架验算', '#Frame2D', '#截面优化'],
    dom3Title: '土木 — 挡土墙·钢结构',
    dom3Desc: 'Rankine 挡土墙稳定(倾覆·滑移·承载力)、柱屈曲、螺栓连接 — 附 KDS 条款引用。',
    dom3Tags: ['#挡土墙', '#柱屈曲', '#螺栓连接'],
    devKicker: 'VERIFIED · AI-NATIVE',
    devTitle: '我们不炫耀客户,炫耀验证',
    devSub: '计算由确定性引擎完成 — 绝非 LLM — 且每个结果都引用规范条款。',
    ver1Num: '37/37', ver1Label: '黄金基准测试通过',
    ver2Num: '6例', ver2Label: '公开例题复现验证',
    ver3Num: '10部', ver3Label: 'KDS 现行规范原文核对',
    ver4Num: '7,579', ver4Label: '验证语料块',
    devCurlTitle: 'REST API — 在你的代码中',
    devMcpTitle: 'MCP — 在你的 AI 中',
    devMcpDesc: '将 MCP 服务器接入 Claude 等 AI 智能体,AI 即可将 8 个计算器与规范检索作为工具使用。计算始终由确定性引擎执行。',
    devKeyCta: '申请 API 密钥',
    devAttribution: 'KDS 原文: 国家建设基准中心(国土交通部),公共Nuri第1类 · 美国联邦出版物: 公有领域',
    faqTitle: '常见问题',
    faqs: [
      { q: '计算结果能用作法定结构计算书吗?', a: '不能。NexyFab 的结果是非法定的参考资料。报批用法定计算书属注册工程师盖章范畴,每个响应都注明此限制。' },
      { q: '支持哪些设计规范?', a: '已按原文核对搭载 10 部 KDS 现行规范(钢结构、挡土墙等),并可选 AISC 360、AASHTO LRFD。结果均引用依据条款编号。' },
      { q: '是 AI 在计算吗?可信吗?', a: '计算本身由确定性引擎执行,并非 AI;AI 仅辅助输入构建与结果解读。引擎通过 37 个黄金基准用例并复现 6 个公开例题。' },
      { q: '能接入我们的服务或 AI 吗?', a: '可以,通过 REST API(API 密钥)或 MCP 服务器。API 提供计算器列表与输入模式,可自动生成 function-calling 工具规格。' },
    ],
  },
  es: {
    demoKicker: 'LIVE DEMO — pruébalo ahora',
    demoTitle: 'Verificación estructural, tan fácil como una calculadora',
    demoSub: 'Sin registro: esto llama al motor de verificación real. Los resultados citan las cláusulas KDS aplicables.',
    demoTabBeam: 'Viga simple de perfil H',
    demoTabWall: 'Estabilidad de muro de contención',
    fldSection: 'Sección (KS D 3502)',
    fldSpan: 'Luz L (m)',
    fldLoad: 'Carga distribuida w (kN/m)',
    fldWallH: 'Altura del muro H (m)',
    fldPhi: 'Ángulo de fricción φ (°)',
    fldGamma: 'Peso unitario del relleno γ (kN/m³)',
    fldSurcharge: 'Sobrecarga q (kPa)',
    fldBearing: 'Capacidad portante admisible (kPa)',
    runBtn: 'Ejecutar verificación',
    running: 'Calculando…',
    verdictPass: 'CUMPLE (PASS)',
    verdictFail: 'NO CUMPLE (FAIL)',
    checkNames: { bending: 'Flexión', shear: 'Cortante', deflection: 'Deflexión', overturning: 'Vuelco', sliding: 'Deslizamiento', eccentricity: 'Excentricidad', bearing: 'Capacidad portante' } as Record<string, string>,
    usageLabel: 'Utilización',
    demoQuota: 'Llamadas de demo restantes hoy: {n}',
    demoRefs: 'Referencias normativas',
    demoError: 'Error en la solicitud — inténtalo de nuevo en un momento',
    demoDisclaimer: 'Referencia de ingeniería (no estatutaria). Los cálculos sellados corresponden a ingenieros licenciados.',
    domKicker: 'DOMINIOS',
    domTitle: 'Solo mostramos dominios que funcionan hoy',
    domSub: 'Sin casillas de "próximamente". Si hay una tarjeta, sus calculadoras, corpus y API están en vivo.',
    domLive: 'LIVE',
    dom1Title: 'Maquinaria — del diseño a la fabricación',
    dom1Desc: 'Diseño 3D en el navegador, análisis DFM con IA y conexión con fabricantes — el núcleo de NexyFab.',
    dom1Tags: ['#Modelador3D', '#DFM', '#RFQ'],
    dom2Title: 'Estructuras temporales y estanterías',
    dom2Desc: 'Análisis 2D de estanterías con pandeo de postes, flexión de vigas y desplome en una sola llamada.',
    dom2Tags: ['#Estanterías', '#Frame2D', '#OptimizadorDeSección'],
    dom3Title: 'Civil — muros de contención y acero',
    dom3Desc: 'Estabilidad Rankine (vuelco/deslizamiento/capacidad), pandeo de columnas, uniones atornilladas — con citas de cláusulas KDS.',
    dom3Tags: ['#MuroDeContención', '#PandeoDeColumna', '#UniónAtornillada'],
    devKicker: 'VERIFICADO · AI-NATIVE',
    devTitle: 'Presumimos de verificación, no de clientes',
    devSub: 'Un motor determinista hace los cálculos — nunca un LLM — y cada resultado cita su cláusula normativa.',
    ver1Num: '37/37', ver1Label: 'pruebas golden-bench superadas',
    ver2Num: '6', ver2Label: 'ejemplos publicados reproducidos',
    ver3Num: '10', ver3Label: 'códigos KDS vigentes cotejados',
    ver4Num: '7,579', ver4Label: 'fragmentos de corpus verificados',
    devCurlTitle: 'REST API — desde tu código',
    devMcpTitle: 'MCP — desde tu IA',
    devMcpDesc: 'Conecta el servidor MCP a Claude o a cualquier agente: la IA obtiene 8 calculadoras y búsqueda normativa como herramientas, mientras un motor determinista siempre hace los cálculos.',
    devKeyCta: 'Solicitar una clave API',
    devAttribution: 'Fuente KDS: KCSC (MOLIT), KOGL Tipo 1 · Publicaciones federales de EE. UU.: dominio público',
    faqTitle: 'Preguntas frecuentes',
    faqs: [
      { q: '¿Puedo usar los resultados como cálculos estructurales sellados?', a: 'No. Los resultados de NexyFab son referencias de ingeniería no estatutarias. Los cálculos sellados para permisos corresponden a ingenieros licenciados, y cada respuesta indica este límite.' },
      { q: '¿Qué códigos de diseño se admiten?', a: '10 códigos KDS vigentes (acero, muros de contención y más), cotejados con el texto oficial, además de AISC 360 y AASHTO LRFD. Cada resultado cita su cláusula aplicable.' },
      { q: '¿Calcula una IA? ¿Es confiable?', a: 'No: un motor determinista realiza todos los cálculos; la IA solo asiste en la configuración de entradas y la interpretación. El motor supera 37 casos golden-bench y reproduce 6 ejemplos publicados.' },
      { q: '¿Puedo integrarlo en mi servicio o IA?', a: 'Sí, mediante REST API (clave API) o el servidor MCP. La API expone listas de calculadoras y esquemas de entrada para autogenerar especificaciones de function-calling.' },
    ],
  },
  ar: {
    demoKicker: 'LIVE DEMO — جرّبه الآن',
    demoTitle: 'التحقق الإنشائي بسهولة الآلة الحاسبة',
    demoSub: 'بدون تسجيل — هذا استدعاء لمحرك التحقق الحقيقي. تُذكر في النتائج بنود KDS المرجعية.',
    demoTabBeam: 'فحص جسر بسيط بمقطع H',
    demoTabWall: 'استقرار الجدار الاستنادي',
    fldSection: 'المقطع (KS D 3502)',
    fldSpan: 'البحر L (م)',
    fldLoad: 'حمل موزع w (kN/m)',
    fldWallH: 'ارتفاع الجدار H (م)',
    fldPhi: 'زاوية الاحتكاك الداخلي φ (°)',
    fldGamma: 'الوزن الحجمي للردم γ (kN/m³)',
    fldSurcharge: 'حمل إضافي q (kPa)',
    fldBearing: 'قدرة التحمل المسموحة (kPa)',
    runBtn: 'تشغيل الفحص',
    running: 'جارٍ الحساب…',
    verdictPass: 'مستوفٍ (PASS)',
    verdictFail: 'غير مستوفٍ (FAIL)',
    checkNames: { bending: 'الانحناء', shear: 'القص', deflection: 'الترخيم', overturning: 'الانقلاب', sliding: 'الانزلاق', eccentricity: 'اللامركزية', bearing: 'قدرة التحمل' } as Record<string, string>,
    usageLabel: 'نسبة الاستخدام',
    demoQuota: 'محاولات العرض المتبقية اليوم: {n}',
    demoRefs: 'البنود المرجعية',
    demoError: 'فشل الطلب — يرجى المحاولة بعد قليل',
    demoDisclaimer: 'مرجع هندسي (غير قانوني). الحسابات المختومة من اختصاص المهندسين المرخّصين.',
    domKicker: 'المجالات',
    domTitle: 'نعرض فقط المجالات العاملة فعلاً اليوم',
    domSub: 'لا خانات "قريباً". إن وُجدت البطاقة فحاسباتها ومكتبتها وواجهتها البرمجية تعمل.',
    domLive: 'LIVE',
    dom1Title: 'الآلات — من التصميم إلى التصنيع',
    dom1Desc: 'تصميم ثلاثي الأبعاد في المتصفح، تحليل DFM بالذكاء الاصطناعي، وربط بالمصنّعين — جوهر NexyFab.',
    dom1Tags: ['#نمذجة3D', '#DFM', '#طلب_تسعير'],
    dom2Title: 'المنشآت المؤقتة والرفوف',
    dom2Desc: 'تحليل ثنائي الأبعاد لإطار الرفوف مع فحص انبعاج الأعمدة وانحناء الجسور والإزاحة الأفقية دفعة واحدة.',
    dom2Tags: ['#فحص_الرفوف', '#Frame2D', '#تحسين_المقطع'],
    dom3Title: 'مدني — جدران استنادية وفولاذ',
    dom3Desc: 'استقرار Rankine (انقلاب/انزلاق/تحمل)، انبعاج الأعمدة، الوصلات المبرغلة — مع اقتباس بنود KDS.',
    dom3Tags: ['#جدار_استنادي', '#انبعاج_عمود', '#وصلة_مبرغلة'],
    devKicker: 'VERIFIED · AI-NATIVE',
    devTitle: 'نتباهى بالتحقق، لا بالعملاء',
    devSub: 'محرك حتمي يقوم بالحسابات — وليس LLM أبداً — وكل نتيجة تقتبس بندها المرجعي.',
    ver1Num: '37/37', ver1Label: 'اختبارات المعيار الذهبي ناجحة',
    ver2Num: '6', ver2Label: 'أمثلة منشورة أعيد إنتاجها',
    ver3Num: '10', ver3Label: 'كودات KDS سارية مطابقة للنص الأصلي',
    ver4Num: '7,579', ver4Label: 'مقاطع مكتبة موثّقة',
    devCurlTitle: 'REST API — من شيفرتك',
    devMcpTitle: 'MCP — من ذكائك الاصطناعي',
    devMcpDesc: 'اربط خادم MCP بـ Claude أو أي وكيل: يحصل الذكاء الاصطناعي على 8 حاسبات وبحث في الكودات كأدوات، بينما يقوم المحرك الحتمي دوماً بالحسابات.',
    devKeyCta: 'طلب مفتاح API',
    devAttribution: 'نص KDS: مركز معايير البناء الوطني (وزارة الأراضي الكورية)، KOGL النوع 1 · المنشورات الفيدرالية الأمريكية: ملك عام',
    faqTitle: 'الأسئلة الشائعة',
    faqs: [
      { q: 'هل يمكن استخدام النتائج كحسابات إنشائية مختومة؟', a: 'لا. مخرجات NexyFab مراجع هندسية غير قانونية. الحسابات المختومة للتراخيص من اختصاص المهندسين المرخّصين، وكل استجابة تُبيّن هذا الحد.' },
      { q: 'ما الكودات التصميمية المدعومة؟', a: '10 كودات KDS سارية (فولاذ، جدران استنادية وغيرها) مطابقة للنص الرسمي، إضافة إلى AISC 360 وAASHTO LRFD. كل نتيجة تقتبس بندها المرجعي.' },
      { q: 'هل الذكاء الاصطناعي هو من يحسب؟ هل النتائج موثوقة؟', a: 'لا — محرك حتمي ينفذ جميع الحسابات؛ الذكاء الاصطناعي يساعد فقط في إعداد المدخلات والتفسير. المحرك يجتاز 37 حالة معيارية ويعيد إنتاج 6 أمثلة منشورة.' },
      { q: 'هل يمكن دمجه في خدمتي أو ذكائي الاصطناعي؟', a: 'نعم، عبر REST API (بمفتاح) أو خادم MCP. توفر الواجهة قوائم الحاسبات ومخططات الإدخال لتوليد مواصفات أدوات function-calling تلقائياً.' },
    ],
  },
};
