/**
 * 엔지니어링 검증 버티컬 섹션 사전 (라이브 데모·분야 카드·검증 숫자·개발자/API·FAQ).
 * 정직성 원칙: 모든 숫자는 실측(골든벤치 37/37, 공표예제 재현 6건, KDS 현행 10종,
 * 코퍼스 7,579청크) — 근거 없는 마케팅 수치 금지 (feedback_landing_no_mock).
 */
export const engDict = {
  ko: {
    // ── 라이브 데모 패널 ──
    demoKicker: 'LIVE DEMO — 지금 바로 실행',
    demoTitle: '구조 검토를 계산기처럼',
    demoSub: '가입 없이 실제 검증 엔진을 호출합니다. 결과에는 KDS 근거 조항이 함께 표시됩니다.',
    demoTabBeam: 'H형강 단순보 검토',
    demoTabWall: '옹벽 안정 검토',
    fldSection: '단면 (KS D 3502)',
    fldSpan: '지간 L (m)',
    fldLoad: '등분포하중 w (kN/m)',
    fldWallH: '벽 높이 H (m)',
    fldPhi: '뒤채움 내부마찰각 φ (°)',
    fldGamma: '뒤채움 단위중량 γ (kN/m³)',
    fldSurcharge: '상재하중 q (kPa)',
    fldBearing: '허용지지력 (kPa)',
    runBtn: '검토 실행',
    running: '계산 중…',
    verdictPass: '만족 (PASS)',
    verdictFail: '불만족 (FAIL)',
    checkNames: { bending: '휨', shear: '전단', deflection: '처짐', overturning: '전도', sliding: '활동', eccentricity: '편심', bearing: '지지력' } as Record<string, string>,
    usageLabel: '사용률',
    demoQuota: '오늘 남은 데모 호출: {n}회',
    demoRefs: '근거 조항',
    demoError: '요청 실패 — 잠시 후 다시 시도해 주세요',
    demoDisclaimer: '구조 검토 참고자료(비법정). 법정 계산서는 기술사 날인 영역입니다.',
    // ── 분야 카드 ──
    domKicker: 'DOMAINS',
    domTitle: '지금 실제로 돌아가는 분야만 보여드립니다',
    domSub: '준비 중인 칸은 만들지 않습니다. 카드가 있다면 계산기·코퍼스·API가 라이브라는 뜻입니다.',
    domLive: 'LIVE',
    dom1Title: '기계·장비 설계 → 제조',
    dom1Desc: '브라우저 3D 설계, AI DFM 분석, 제조사 연결까지 — NexyFab의 본업.',
    dom1Tags: ['#3D모델러', '#DFM분석', '#견적·발주'],
    dom2Title: '가설구조·랙',
    dom2Desc: '랙 프레임 2D 해석 + 포스트 좌굴·빔 휨·수평변위 검토를 한 번에.',
    dom2Tags: ['#랙프레임검토', '#frame2d해석', '#단면최적화'],
    dom3Title: '토목 — 옹벽·강구조',
    dom3Desc: 'Rankine 옹벽 안정(전도·활동·지지력), 기둥 좌굴, 볼트 접합 — KDS 조항 인용 포함.',
    dom3Tags: ['#옹벽안정', '#기둥좌굴', '#볼트접합'],
    dom4Title: '건축 — RC 부재검토',
    dom4Desc: 'RC 보 휨·전단 검토(강도설계법) — KDS 14 20 원문 대조 계수, 근거 조항 인용.',
    dom4Tags: ['#RC보검토', '#강도설계법', '#KDS1420'],
    dom5Title: '조경 — 배수·기준검색',
    dom5Desc: '우수 배수 검토(합리식+Manning)와 KDS 34 조경 기준 검색. 미학·식재 디자인은 범위 외.',
    dom5Tags: ['#우수배수', '#Manning관거', '#KDS34'],
    // ── 검증 숫자 + 개발자/API ──
    devKicker: 'API · MCP · CLI',
    devTitle: '코드·AI·터미널, 어디서든 호출',
    devSub: '“말로 설계” 파이프라인(설명→결정론 빌드→게이트 검증)을 REST API·MCP·CLI로 그대로 부릅니다. 형상 생성·검증은 항상 결정론 엔진이 수행합니다.',
    ver1Num: '37/37', ver1Label: '수계산 대조 테스트 통과 (골든벤치)',
    ver2Num: '6건', ver2Label: 'FHWA·AISC 공표 예제 재현',
    ver3Num: '10종', ver3Label: 'KDS 현행 기준 원문 대조',
    ver4Num: '7,579', ver4Label: '기준 문서 조항·단락 색인',
    devCurlTitle: 'REST API — 당신의 코드에서',
    devMcpTitle: 'MCP — 당신의 AI에서',
    devCliTitle: 'CLI — 당신의 터미널에서',
    devMcpDesc: 'Claude 등 AI 클라이언트에 MCP로 연결하면, AI가 설계·수정 도구(assemble·compose·edit·face_drag·part_op·domain_design)를 호출합니다. 형상·검증은 결정론 엔진이 수행합니다.',
    devKeyCta: 'API 키 문의', pricingCta: '요금 보기',
    devAttribution: 'KDS 원문: 국가건설기준센터(국토교통부), 공공누리 제1유형 · 미 연방 간행물: 퍼블릭 도메인',
    // ── FAQ ──
    faqTitle: '자주 묻는 질문',
    faqs: [
      { q: '계산 결과를 법정 구조계산서로 쓸 수 있나요?', a: '아니요. NexyFab의 결과는 구조 검토 참고자료(비법정)입니다. 인허가용 법정 계산서는 기술사 날인 영역이며, 모든 응답에 이 한계가 명시됩니다.' },
      { q: '어떤 설계기준을 지원하나요?', a: 'KDS 현행 기준 10종(강구조·옹벽 등)을 원문 대조로 탑재했고 AISC 360, AASHTO LRFD를 선택할 수 있습니다. 결과에는 근거 조항 번호가 함께 인용됩니다.' },
      { q: 'AI가 계산하나요? 믿을 수 있나요?', a: '계산 자체는 AI가 아니라 결정론 엔진이 수행합니다. AI는 입력 구성과 결과 해석을 돕는 역할입니다. 엔진은 골든벤치 37케이스와 공표 예제 재현 6건으로 검증됐습니다.' },
      { q: '우리 서비스나 AI에 연동할 수 있나요?', a: '네. REST API(API 키)와 MCP 서버 두 가지로 연동합니다. 계산기 목록·입력 스키마를 API가 제공하므로 function-calling 도구 스펙을 자동 생성할 수 있습니다.' },
    ],
  },
  en: {
    demoKicker: 'LIVE DEMO — run it now',
    demoTitle: 'Structural checks, as easy as a calculator',
    demoSub: 'No sign-up — this calls the real verification engine. Results cite the governing KDS clauses.',
    demoTabBeam: 'H-beam simple beam check',
    demoTabWall: 'Retaining wall stability',
    fldSection: 'Section (KS D 3502)',
    fldSpan: 'Span L (m)',
    fldLoad: 'UDL w (kN/m)',
    fldWallH: 'Wall height H (m)',
    fldPhi: 'Backfill friction angle φ (°)',
    fldGamma: 'Backfill unit weight γ (kN/m³)',
    fldSurcharge: 'Surcharge q (kPa)',
    fldBearing: 'Allowable bearing (kPa)',
    runBtn: 'Run check',
    running: 'Computing…',
    verdictPass: 'PASS',
    verdictFail: 'FAIL',
    checkNames: { bending: 'Bending', shear: 'Shear', deflection: 'Deflection', overturning: 'Overturning', sliding: 'Sliding', eccentricity: 'Eccentricity', bearing: 'Bearing' } as Record<string, string>,
    usageLabel: 'Utilization',
    demoQuota: 'Demo calls left today: {n}',
    demoRefs: 'Code references',
    demoError: 'Request failed — please try again shortly',
    demoDisclaimer: 'Engineering reference only (non-statutory). Sealed calculations remain the domain of licensed engineers.',
    domKicker: 'DOMAINS',
    domTitle: 'We only show domains that actually run today',
    domSub: 'No "coming soon" tiles. If a card exists, its calculators, corpus, and API are live.',
    domLive: 'LIVE',
    dom1Title: 'Machinery — design to manufacturing',
    dom1Desc: 'Browser 3D design, AI DFM analysis, and manufacturer matching — the NexyFab core.',
    dom1Tags: ['#3DModeler', '#DFM', '#RFQ'],
    dom2Title: 'Temporary structures & racks',
    dom2Desc: '2D rack-frame analysis with post buckling, beam bending, and sway checks in one call.',
    dom2Tags: ['#RackFrame', '#Frame2D', '#SectionOptimizer'],
    dom3Title: 'Civil — retaining walls & steel',
    dom3Desc: 'Rankine wall stability (overturning/sliding/bearing), column buckling, bolted connections — with KDS clause citations.',
    dom3Tags: ['#RetainingWall', '#ColumnBuckling', '#BoltedJoint'],
    dom4Title: 'Building — RC member checks',
    dom4Desc: 'RC beam flexure/shear checks (strength design) — coefficients cross-checked against KDS 14 20, with clause citations.',
    dom4Tags: ['#RCBeam', '#StrengthDesign', '#KDS1420'],
    dom5Title: 'Landscape — drainage & code search',
    dom5Desc: 'Storm drainage checks (rational method + Manning) and KDS 34 landscape code search. Aesthetics and planting design are out of scope.',
    dom5Tags: ['#StormDrainage', '#Manning', '#KDS34'],
    devKicker: 'API · MCP · CLI',
    devTitle: 'Call it from code, your AI, or the terminal',
    devSub: 'Drive the “design-in-words” pipeline (prompt → deterministic build → gated verification) via REST API, MCP, and CLI. Geometry and verification always run on a deterministic engine.',
    ver1Num: '37/37', ver1Label: 'hand-calculation-verified tests passing',
    ver2Num: '6', ver2Label: 'FHWA & AISC published examples reproduced',
    ver3Num: '10', ver3Label: 'current KDS codes cross-checked',
    ver4Num: '7,579', ver4Label: 'indexed code clauses & passages',
    devCurlTitle: 'REST API — from your code',
    devMcpTitle: 'MCP — from your AI',
    devCliTitle: 'CLI — from your terminal',
    devMcpDesc: 'Connect via MCP to Claude or any AI client: the AI calls design/edit tools (assemble, compose, edit, face_drag, part_op, domain_design), while a deterministic engine handles geometry and verification.',
    devKeyCta: 'Request an API key', pricingCta: 'View pricing',
    devAttribution: 'KDS source: KCSC (MOLIT), KOGL Type 1 · US federal publications: public domain',
    faqTitle: 'Frequently asked questions',
    faqs: [
      { q: 'Can I use the results as sealed structural calculations?', a: 'No. NexyFab outputs are non-statutory engineering references. Sealed calculations for permits remain the domain of licensed engineers, and every response states this limit.' },
      { q: 'Which design codes are supported?', a: '10 current KDS codes (steel, retaining walls, and more), cross-checked against the official text, plus AISC 360 and AASHTO LRFD. Every result cites its governing clause.' },
      { q: 'Does an AI do the math? Can I trust it?', a: 'No — a deterministic engine performs all calculations; AI only assists with input setup and interpretation. The engine passes 37 golden-bench cases and reproduces 6 published worked examples.' },
      { q: 'Can I integrate it into my service or AI?', a: 'Yes, via REST API (API key) or the MCP server. The API exposes calculator lists and input schemas, so you can auto-generate function-calling tool specs.' },
    ],
  },
  ja: {
    demoKicker: 'LIVE DEMO — 今すぐ実行',
    demoTitle: '構造チェックを電卓のように',
    demoSub: '登録不要で実際の検証エンジンを呼び出します。結果には根拠となるKDS条項が表示されます。',
    demoTabBeam: 'H形鋼 単純梁チェック',
    demoTabWall: '擁壁 安定チェック',
    fldSection: '断面 (KS D 3502)',
    fldSpan: 'スパン L (m)',
    fldLoad: '等分布荷重 w (kN/m)',
    fldWallH: '壁高 H (m)',
    fldPhi: '裏込め内部摩擦角 φ (°)',
    fldGamma: '裏込め単位体積重量 γ (kN/m³)',
    fldSurcharge: '上載荷重 q (kPa)',
    fldBearing: '許容支持力 (kPa)',
    runBtn: 'チェック実行',
    running: '計算中…',
    verdictPass: 'OK (PASS)',
    verdictFail: 'NG (FAIL)',
    checkNames: { bending: '曲げ', shear: 'せん断', deflection: 'たわみ', overturning: '転倒', sliding: '滑動', eccentricity: '偏心', bearing: '支持力' } as Record<string, string>,
    usageLabel: '使用率',
    demoQuota: '本日の残りデモ回数: {n}回',
    demoRefs: '根拠条項',
    demoError: 'リクエスト失敗 — 少し待って再試行してください',
    demoDisclaimer: '構造検討の参考資料(非法定)。法定計算書は技術士の押印領域です。',
    domKicker: 'DOMAINS',
    domTitle: '実際に稼働している分野だけを表示します',
    domSub: '「準備中」の枠は作りません。カードがあれば計算機・コーパス・APIが稼働中です。',
    domLive: 'LIVE',
    dom1Title: '機械・装置 設計→製造',
    dom1Desc: 'ブラウザ3D設計、AI DFM分析、製造パートナー接続 — NexyFabの本業。',
    dom1Tags: ['#3Dモデラー', '#DFM分析', '#見積・発注'],
    dom2Title: '仮設構造・ラック',
    dom2Desc: 'ラックフレーム2D解析+支柱座屈・梁曲げ・水平変位チェックを一度に。',
    dom2Tags: ['#ラック検討', '#Frame2D解析', '#断面最適化'],
    dom3Title: '土木 — 擁壁・鋼構造',
    dom3Desc: 'Rankine擁壁安定(転倒・滑動・支持力)、柱座屈、ボルト接合 — KDS条項引用付き。',
    dom3Tags: ['#擁壁安定', '#柱座屈', '#ボルト接合'],
    dom4Title: '建築 — RC部材チェック',
    dom4Desc: 'RC梁の曲げ・せん断チェック(強度設計法) — KDS 14 20原文照合係数、根拠条項引用付き。',
    dom4Tags: ['#RC梁', '#強度設計法', '#KDS1420'],
    dom5Title: '造園 — 排水・基準検索',
    dom5Desc: '雨水排水チェック(合理式+Manning)とKDS 34造園基準検索。美観・植栽デザインは範囲外。',
    dom5Tags: ['#雨水排水', '#Manning', '#KDS34'],
    devKicker: 'API · MCP · CLI',
    devTitle: 'コード・AI・ターミナル、どこからでも呼び出し',
    devSub: '「言葉で設計」パイプライン(説明→決定論ビルド→ゲート検証)をREST API・MCP・CLIでそのまま呼び出します。形状生成・検証は常に決定論エンジンが実行します。',
    ver1Num: '37/37', ver1Label: '手計算照合テスト通過',
    ver2Num: '6件', ver2Label: 'FHWA・AISC公表例題の再現',
    ver3Num: '10種', ver3Label: 'KDS現行基準の原文照合',
    ver4Num: '7,579', ver4Label: '基準文書の条項・段落索引',
    devCurlTitle: 'REST API — あなたのコードから',
    devMcpTitle: 'MCP — あなたのAIから',
    devCliTitle: 'CLI — あなたのターミナルから',
    devMcpDesc: 'MCPでClaude等のAIクライアントに接続すると、AIが設計・修正ツール(assemble・compose・edit・face_drag・part_op・domain_design)を呼び出します。形状・検証は決定論エンジンが実行します。',
    devKeyCta: 'APIキーのお問い合わせ', pricingCta: '料金を見る',
    devAttribution: 'KDS原文: 国家建設基準センター(国土交通部)、公共ヌリ第1類型 · 米連邦刊行物: パブリックドメイン',
    faqTitle: 'よくある質問',
    faqs: [
      { q: '計算結果を法定構造計算書として使えますか?', a: 'いいえ。NexyFabの結果は非法定の参考資料です。許認可用の法定計算書は技術士の押印領域であり、全応答にこの限界が明示されます。' },
      { q: 'どの設計基準に対応していますか?', a: 'KDS現行基準10種(鋼構造・擁壁など)を原文照合で搭載し、AISC 360、AASHTO LRFDも選択できます。結果には根拠条項番号が引用されます。' },
      { q: 'AIが計算するのですか?信頼できますか?', a: '計算自体はAIではなく決定論エンジンが実行します。AIは入力構成と結果解釈の補助役です。エンジンはゴールデンベンチ37ケースと公表例題再現6件で検証済みです。' },
      { q: '自社サービスやAIに連携できますか?', a: 'はい。REST API(APIキー)とMCPサーバーの2通りです。APIが計算機一覧・入力スキーマを提供するため、function-callingツール仕様を自動生成できます。' },
    ],
  },
  cn: {
    demoKicker: 'LIVE DEMO — 立即运行',
    demoTitle: '结构验算,像计算器一样简单',
    demoSub: '无需注册,直接调用真实验证引擎。结果附带 KDS 依据条款。',
    demoTabBeam: 'H型钢简支梁验算',
    demoTabWall: '挡土墙稳定验算',
    fldSection: '截面 (KS D 3502)',
    fldSpan: '跨度 L (m)',
    fldLoad: '均布荷载 w (kN/m)',
    fldWallH: '墙高 H (m)',
    fldPhi: '回填内摩擦角 φ (°)',
    fldGamma: '回填重度 γ (kN/m³)',
    fldSurcharge: '超载 q (kPa)',
    fldBearing: '容许承载力 (kPa)',
    runBtn: '运行验算',
    running: '计算中…',
    verdictPass: '满足 (PASS)',
    verdictFail: '不满足 (FAIL)',
    checkNames: { bending: '弯曲', shear: '剪切', deflection: '挠度', overturning: '倾覆', sliding: '滑移', eccentricity: '偏心', bearing: '承载力' } as Record<string, string>,
    usageLabel: '利用率',
    demoQuota: '今日剩余演示次数: {n}',
    demoRefs: '依据条款',
    demoError: '请求失败 — 请稍后重试',
    demoDisclaimer: '结构验算参考资料(非法定)。法定计算书属注册工程师盖章范畴。',
    domKicker: 'DOMAINS',
    domTitle: '只展示今天真正可用的领域',
    domSub: '不做"敬请期待"的空格子。有卡片,就意味着计算器、语料库和 API 均已上线。',
    domLive: 'LIVE',
    dom1Title: '机械·装备 设计→制造',
    dom1Desc: '浏览器3D设计、AI DFM分析、制造商对接 — NexyFab 的主业。',
    dom1Tags: ['#3D建模', '#DFM分析', '#询价下单'],
    dom2Title: '临时结构·货架',
    dom2Desc: '货架框架2D解析+立柱屈曲·横梁弯曲·水平位移验算一次完成。',
    dom2Tags: ['#货架验算', '#Frame2D', '#截面优化'],
    dom3Title: '土木 — 挡土墙·钢结构',
    dom3Desc: 'Rankine 挡土墙稳定(倾覆·滑移·承载力)、柱屈曲、螺栓连接 — 附 KDS 条款引用。',
    dom3Tags: ['#挡土墙', '#柱屈曲', '#螺栓连接'],
    dom4Title: '建筑 — RC构件验算',
    dom4Desc: 'RC梁弯剪验算(强度设计法) — 系数经KDS 14 20原文核对,附依据条款引用。',
    dom4Tags: ['#RC梁', '#强度设计法', '#KDS1420'],
    dom5Title: '园林 — 排水·规范检索',
    dom5Desc: '雨水排水验算(推理公式+Manning)与KDS 34园林规范检索。美学·种植设计不在范围内。',
    dom5Tags: ['#雨水排水', '#Manning', '#KDS34'],
    devKicker: 'API · MCP · CLI',
    devTitle: '代码、AI、终端,随处调用',
    devSub: '通过 REST API·MCP·CLI 直接调用“用语言设计”流水线(描述→确定性构建→门控验证)。几何生成与验证始终由确定性引擎执行。',
    ver1Num: '37/37', ver1Label: '手算核对测试全部通过',
    ver2Num: '6例', ver2Label: 'FHWA·AISC公开例题复现',
    ver3Num: '10部', ver3Label: 'KDS 现行规范原文核对',
    ver4Num: '7,579', ver4Label: '规范条款·段落索引',
    devCurlTitle: 'REST API — 在你的代码中',
    devMcpTitle: 'MCP — 在你的 AI 中',
    devCliTitle: 'CLI — 在你的终端中',
    devMcpDesc: '通过 MCP 接入 Claude 等 AI 客户端,AI 即可调用设计·修改工具(assemble·compose·edit·face_drag·part_op·domain_design)。几何与验证由确定性引擎执行。',
    devKeyCta: '申请 API 密钥', pricingCta: '查看价格',
    devAttribution: 'KDS 原文: 国家建设基准中心(国土交通部),公共Nuri第1类 · 美国联邦出版物: 公有领域',
    faqTitle: '常见问题',
    faqs: [
      { q: '计算结果能用作法定结构计算书吗?', a: '不能。NexyFab 的结果是非法定的参考资料。报批用法定计算书属注册工程师盖章范畴,每个响应都注明此限制。' },
      { q: '支持哪些设计规范?', a: '已按原文核对搭载 10 部 KDS 现行规范(钢结构、挡土墙等),并可选 AISC 360、AASHTO LRFD。结果均引用依据条款编号。' },
      { q: '是 AI 在计算吗?可信吗?', a: '计算本身由确定性引擎执行,并非 AI;AI 仅辅助输入构建与结果解读。引擎通过 37 个黄金基准用例并复现 6 个公开例题。' },
      { q: '能接入我们的服务或 AI 吗?', a: '可以,通过 REST API(API 密钥)或 MCP 服务器。API 提供计算器列表与输入模式,可自动生成 function-calling 工具规格。' },
    ],
  },
  es: {
    demoKicker: 'LIVE DEMO — pruébalo ahora',
    demoTitle: 'Verificación estructural, tan fácil como una calculadora',
    demoSub: 'Sin registro: esto llama al motor de verificación real. Los resultados citan las cláusulas KDS aplicables.',
    demoTabBeam: 'Viga simple de perfil H',
    demoTabWall: 'Estabilidad de muro de contención',
    fldSection: 'Sección (KS D 3502)',
    fldSpan: 'Luz L (m)',
    fldLoad: 'Carga distribuida w (kN/m)',
    fldWallH: 'Altura del muro H (m)',
    fldPhi: 'Ángulo de fricción φ (°)',
    fldGamma: 'Peso unitario del relleno γ (kN/m³)',
    fldSurcharge: 'Sobrecarga q (kPa)',
    fldBearing: 'Capacidad portante admisible (kPa)',
    runBtn: 'Ejecutar verificación',
    running: 'Calculando…',
    verdictPass: 'CUMPLE (PASS)',
    verdictFail: 'NO CUMPLE (FAIL)',
    checkNames: { bending: 'Flexión', shear: 'Cortante', deflection: 'Deflexión', overturning: 'Vuelco', sliding: 'Deslizamiento', eccentricity: 'Excentricidad', bearing: 'Capacidad portante' } as Record<string, string>,
    usageLabel: 'Utilización',
    demoQuota: 'Llamadas de demo restantes hoy: {n}',
    demoRefs: 'Referencias normativas',
    demoError: 'Error en la solicitud — inténtalo de nuevo en un momento',
    demoDisclaimer: 'Referencia de ingeniería (no estatutaria). Los cálculos sellados corresponden a ingenieros licenciados.',
    domKicker: 'DOMINIOS',
    domTitle: 'Solo mostramos dominios que funcionan hoy',
    domSub: 'Sin casillas de "próximamente". Si hay una tarjeta, sus calculadoras, corpus y API están en vivo.',
    domLive: 'LIVE',
    dom1Title: 'Maquinaria — del diseño a la fabricación',
    dom1Desc: 'Diseño 3D en el navegador, análisis DFM con IA y conexión con fabricantes — el núcleo de NexyFab.',
    dom1Tags: ['#Modelador3D', '#DFM', '#RFQ'],
    dom2Title: 'Estructuras temporales y estanterías',
    dom2Desc: 'Análisis 2D de estanterías con pandeo de postes, flexión de vigas y desplome en una sola llamada.',
    dom2Tags: ['#Estanterías', '#Frame2D', '#OptimizadorDeSección'],
    dom3Title: 'Civil — muros de contención y acero',
    dom3Desc: 'Estabilidad Rankine (vuelco/deslizamiento/capacidad), pandeo de columnas, uniones atornilladas — con citas de cláusulas KDS.',
    dom3Tags: ['#MuroDeContención', '#PandeoDeColumna', '#UniónAtornillada'],
    dom4Title: 'Edificación — verificación de miembros RC',
    dom4Desc: 'Verificación de flexión/cortante de vigas RC (diseño por resistencia) — coeficientes cotejados con KDS 14 20, con citas de cláusulas.',
    dom4Tags: ['#VigaRC', '#DiseñoPorResistencia', '#KDS1420'],
    dom5Title: 'Paisajismo — drenaje y búsqueda normativa',
    dom5Desc: 'Verificación de drenaje pluvial (método racional + Manning) y búsqueda en códigos KDS 34. La estética y el diseño de plantación quedan fuera del alcance.',
    dom5Tags: ['#DrenajePluvial', '#Manning', '#KDS34'],
    devKicker: 'API · MCP · CLI',
    devTitle: 'Llámalo desde tu código, tu IA o la terminal',
    devSub: 'Usa la canalización de “diseño con palabras” (descripción → construcción determinista → verificación con gates) vía REST API, MCP y CLI. La geometría y la verificación siempre corren en un motor determinista.',
    ver1Num: '37/37', ver1Label: 'pruebas verificadas con cálculo manual',
    ver2Num: '6', ver2Label: 'ejemplos de FHWA y AISC reproducidos',
    ver3Num: '10', ver3Label: 'códigos KDS vigentes cotejados',
    ver4Num: '7,579', ver4Label: 'cláusulas y pasajes normativos indexados',
    devCurlTitle: 'REST API — desde tu código',
    devMcpTitle: 'MCP — desde tu IA',
    devCliTitle: 'CLI — desde tu terminal',
    devMcpDesc: 'Conecta vía MCP a Claude o a cualquier cliente de IA: la IA invoca herramientas de diseño/edición (assemble, compose, edit, face_drag, part_op, domain_design), mientras un motor determinista gestiona la geometría y la verificación.',
    devKeyCta: 'Solicitar una clave API', pricingCta: 'Ver precios',
    devAttribution: 'Fuente KDS: KCSC (MOLIT), KOGL Tipo 1 · Publicaciones federales de EE. UU.: dominio público',
    faqTitle: 'Preguntas frecuentes',
    faqs: [
      { q: '¿Puedo usar los resultados como cálculos estructurales sellados?', a: 'No. Los resultados de NexyFab son referencias de ingeniería no estatutarias. Los cálculos sellados para permisos corresponden a ingenieros licenciados, y cada respuesta indica este límite.' },
      { q: '¿Qué códigos de diseño se admiten?', a: '10 códigos KDS vigentes (acero, muros de contención y más), cotejados con el texto oficial, además de AISC 360 y AASHTO LRFD. Cada resultado cita su cláusula aplicable.' },
      { q: '¿Calcula una IA? ¿Es confiable?', a: 'No: un motor determinista realiza todos los cálculos; la IA solo asiste en la configuración de entradas y la interpretación. El motor supera 37 casos golden-bench y reproduce 6 ejemplos publicados.' },
      { q: '¿Puedo integrarlo en mi servicio o IA?', a: 'Sí, mediante REST API (clave API) o el servidor MCP. La API expone listas de calculadoras y esquemas de entrada para autogenerar especificaciones de function-calling.' },
    ],
  },
  ar: {
    demoKicker: 'LIVE DEMO — جرّبه الآن',
    demoTitle: 'التحقق الإنشائي بسهولة الآلة الحاسبة',
    demoSub: 'بدون تسجيل — هذا استدعاء لمحرك التحقق الحقيقي. تُذكر في النتائج بنود KDS المرجعية.',
    demoTabBeam: 'فحص جسر بسيط بمقطع H',
    demoTabWall: 'استقرار الجدار الاستنادي',
    fldSection: 'المقطع (KS D 3502)',
    fldSpan: 'البحر L (م)',
    fldLoad: 'حمل موزع w (kN/m)',
    fldWallH: 'ارتفاع الجدار H (م)',
    fldPhi: 'زاوية الاحتكاك الداخلي φ (°)',
    fldGamma: 'الوزن الحجمي للردم γ (kN/m³)',
    fldSurcharge: 'حمل إضافي q (kPa)',
    fldBearing: 'قدرة التحمل المسموحة (kPa)',
    runBtn: 'تشغيل الفحص',
    running: 'جارٍ الحساب…',
    verdictPass: 'مستوفٍ (PASS)',
    verdictFail: 'غير مستوفٍ (FAIL)',
    checkNames: { bending: 'الانحناء', shear: 'القص', deflection: 'الترخيم', overturning: 'الانقلاب', sliding: 'الانزلاق', eccentricity: 'اللامركزية', bearing: 'قدرة التحمل' } as Record<string, string>,
    usageLabel: 'نسبة الاستخدام',
    demoQuota: 'محاولات العرض المتبقية اليوم: {n}',
    demoRefs: 'البنود المرجعية',
    demoError: 'فشل الطلب — يرجى المحاولة بعد قليل',
    demoDisclaimer: 'مرجع هندسي (غير قانوني). الحسابات المختومة من اختصاص المهندسين المرخّصين.',
    domKicker: 'المجالات',
    domTitle: 'نعرض فقط المجالات العاملة فعلاً اليوم',
    domSub: 'لا خانات "قريباً". إن وُجدت البطاقة فحاسباتها ومكتبتها وواجهتها البرمجية تعمل.',
    domLive: 'LIVE',
    dom1Title: 'الآلات — من التصميم إلى التصنيع',
    dom1Desc: 'تصميم ثلاثي الأبعاد في المتصفح، تحليل DFM بالذكاء الاصطناعي، وربط بالمصنّعين — جوهر NexyFab.',
    dom1Tags: ['#نمذجة3D', '#DFM', '#طلب_تسعير'],
    dom2Title: 'المنشآت المؤقتة والرفوف',
    dom2Desc: 'تحليل ثنائي الأبعاد لإطار الرفوف مع فحص انبعاج الأعمدة وانحناء الجسور والإزاحة الأفقية دفعة واحدة.',
    dom2Tags: ['#فحص_الرفوف', '#Frame2D', '#تحسين_المقطع'],
    dom3Title: 'مدني — جدران استنادية وفولاذ',
    dom3Desc: 'استقرار Rankine (انقلاب/انزلاق/تحمل)، انبعاج الأعمدة، الوصلات المبرغلة — مع اقتباس بنود KDS.',
    dom3Tags: ['#جدار_استنادي', '#انبعاج_عمود', '#وصلة_مبرغلة'],
    dom4Title: 'المباني — فحص عناصر الخرسانة المسلحة',
    dom4Desc: 'فحص الانحناء/القص لجسور RC (تصميم المقاومة) — معاملات مطابقة لنص KDS 14 20 مع اقتباس البنود.',
    dom4Tags: ['#جسر_RC', '#تصميم_المقاومة', '#KDS1420'],
    dom5Title: 'تنسيق المواقع — الصرف والبحث في الكودات',
    dom5Desc: 'فحص صرف مياه الأمطار (الطريقة العقلانية + Manning) والبحث في كودات KDS 34. الجماليات وتصميم الغرس خارج النطاق.',
    dom5Tags: ['#صرف_الأمطار', '#Manning', '#KDS34'],
    devKicker: 'API · MCP · CLI',
    devTitle: 'استدعِه من شيفرتك أو ذكائك الاصطناعي أو الطرفية',
    devSub: 'شغّل مسار «التصميم بالكلمات» (وصف ← بناء حتمي ← تحقق ببوابات) عبر REST API وMCP وCLI. توليد الأشكال والتحقق يجري دوماً على محرك حتمي.',
    ver1Num: '37/37', ver1Label: 'اختبارات موثّقة بالحساب اليدوي ناجحة',
    ver2Num: '6', ver2Label: 'أمثلة FHWA وAISC المنشورة أعيد إنتاجها',
    ver3Num: '10', ver3Label: 'كودات KDS سارية مطابقة للنص الأصلي',
    ver4Num: '7,579', ver4Label: 'بنود وفقرات الكودات المفهرسة',
    devCurlTitle: 'REST API — من شيفرتك',
    devMcpTitle: 'MCP — من ذكائك الاصطناعي',
    devCliTitle: 'CLI — من طرفيتك',
    devMcpDesc: 'اتصل عبر MCP بـ Claude أو أي عميل ذكاء اصطناعي: يستدعي الذكاء الاصطناعي أدوات التصميم/التعديل (assemble، compose، edit، face_drag، part_op، domain_design)، بينما يتولى المحرك الحتمي توليد الأشكال والتحقق.',
    devKeyCta: 'طلب مفتاح API', pricingCta: 'عرض الأسعار',
    devAttribution: 'نص KDS: مركز معايير البناء الوطني (وزارة الأراضي الكورية)، KOGL النوع 1 · المنشورات الفيدرالية الأمريكية: ملك عام',
    faqTitle: 'الأسئلة الشائعة',
    faqs: [
      { q: 'هل يمكن استخدام النتائج كحسابات إنشائية مختومة؟', a: 'لا. مخرجات NexyFab مراجع هندسية غير قانونية. الحسابات المختومة للتراخيص من اختصاص المهندسين المرخّصين، وكل استجابة تُبيّن هذا الحد.' },
      { q: 'ما الكودات التصميمية المدعومة؟', a: '10 كودات KDS سارية (فولاذ، جدران استنادية وغيرها) مطابقة للنص الرسمي، إضافة إلى AISC 360 وAASHTO LRFD. كل نتيجة تقتبس بندها المرجعي.' },
      { q: 'هل الذكاء الاصطناعي هو من يحسب؟ هل النتائج موثوقة؟', a: 'لا — محرك حتمي ينفذ جميع الحسابات؛ الذكاء الاصطناعي يساعد فقط في إعداد المدخلات والتفسير. المحرك يجتاز 37 حالة معيارية ويعيد إنتاج 6 أمثلة منشورة.' },
      { q: 'هل يمكن دمجه في خدمتي أو ذكائي الاصطناعي؟', a: 'نعم، عبر REST API (بمفتاح) أو خادم MCP. توفر الواجهة قوائم الحاسبات ومخططات الإدخال لتوليد مواصفات أدوات function-calling تلقائياً.' },
    ],
  },
};
