export const homeDict = {
    ko: {
        heroKicker: 'Nexyfab · 제조사 찾기.',
        heroTitle: '최적의 개발 파트너를<br/>검색해보세요',
        heroSub: '제품 키워드만 입력하면, 한·중 공장 DB에서<br/>관련 제조사를 바로 검색합니다.',
        searchPlaceholder: '예: 배터리 자동화 설비',
        placeholderList: ['배터리 자동화 설비', '식품 생산 설비', '정밀 부품 가공', '물류 이송 시스템', '반도체 세정 장비'],
        searchBtn: '검색',
        searching: '검색 중...',
        searchingSub: '(약 30초 이내)',
        manufacturer: '제조사',
        industry: '업종',
        score: '적합도',
        contactTitle: '📨 연락처 입력',
        contactCompany: '이름(회사명)',
        contactPhone: '연락처',
        contactEmail: '이메일',
        contactSubmit: '문의하기',
        tabKoFactories: '한국 등록공장',
        tabCnFactories: '중국 공장',
        noKoResults: '일치하는 한국 공장이 없습니다.',
        noCnResults: '일치하는 중국 공장이 없습니다.',
        applyDashboard: '대시보드에서 바로 신청하기',
        loginApply: '로그인해서 신청하기',
        applyDesc: 'AI RFP 자동생성 · 견적 비교 · 전담 지원',
        gotoDashboard: '신청하기 →',
        signIn: '로그인 →',
        orDirectContact: '또는 직접 문의',
        statCount: '30만+',
        formSubmitting: '처리 중...',
        alertSuccess: '문의가 성공적으로 전달되었습니다.',
        alertError: '오류가 발생했습니다. 나중에 다시 시도해 주세요.',
        totalResults: '전체',
        contactGuide: '* 이름(회사명), 연락처, 이메일은 필수 입력 항목입니다.',
        statKr: '한국/중국 공장',
        statRef: '협력사 누적 레퍼런스',
        heroNote: '* 실제 회사명은 고객 화면에 노출되지 않으며,<br/>문의 제출 시 내부 확인용으로만 전달됩니다.',

        howKicker: 'Nexyfab · How it Works.',
        howTitle: '키워드 입력부터 연결까지',
        howSub: '검색 → 분석 → 선별 → 연결 → 실제 프로젝트 진행',
        step1Title: '요구사항 입력',
        step1Desc: '요구사항을 키워드로 입력하면 분석 기준이 생성됩니다.',
        step1Tag1: '배터리 자동화 설비', step1Tag2: '특수목적 장비', step1Tag3: '공정 개선',
        step2Title: 'DB 검색',
        step2Desc: '키워드를 해석하고 유사 레퍼런스/제조 역량 데이터를 기반으로 후보군을 정리합니다.',
        step2List1: '의미 확장(동의어/유사 카테고리)',
        step2List2: '유사 레퍼런스 기반 적합도 산출',
        step2List3: '업종/설비/공정 조건 필터링',
        step3Title: '적합 파트너 선별',
        step3Desc: '"가능한 곳"이 아니라 "가장 적합한 곳"을 우선 검토 후보로 압축합니다.',
        step3List1: '기술 난이도/분야 매칭',
        step3List2: '수행 범위 및 신뢰도 반영',
        step3List3: '중복·부적합 후보 제외',
        step4Title: '문의 연결',
        step4Desc: '프로젝트 정보는 외부에 공개되지 않으며, 내부 검토 후 필요한 범위에서 연결됩니다.',
        step4Note: '* 실제 회사명은 고객 화면에 노출되지 않으며 내부 확인용으로만 전달됩니다.',
        howBottomTitle: '키워드 검색부터 시작하세요.',
        howBottomSub: '짧은 키워드만으로도 시작할 수 있어요.',
        howBottomBtn: '키워드 검색',

        whyKicker: 'Nexyfab · Why.',
        whyTitle: '"연결"의 기준이 다릅니다',
        whySub: '단순한 매칭이 아닌, 실제 수행 가능성과 적합성을 기준으로 매칭합니다.',
        why1Title: '무작위 견적 요청이 아닙니다',
        why1Desc: '요구사항에 부합하는 적격 후보만 선별하여 전달하므로 소통 비용이 절감됩니다.',
        why2Title: '데이터 기반 필터링',
        why2Desc: '단순 키워드를 넘어 유사 레퍼런스 및 업종/설비/공정 조건을 모두 반영합니다.',
        why3Title: '프로젝트 정보 비공개 원칙',
        why3Desc: '실제 회사명은 고객에게 노출되지 않으며, 내부 검토 및 연결을 위해서만 제한적으로 사용됩니다.',
        why4Title: '의사결정까지 빠르게',
        why4Desc: '"가능할 수도 있는 목록"이 아닌, "가장 먼저 검토해야 할 적합 후보군"으로 압축합니다.',
        whyCtaTitle: '지금 바로 매칭을 시작해볼까요?',
        whyCtaBtn: '프로젝트 문의',

        caseKicker: 'Nexyfab · Use Cases.',
        caseTitle: '이런 프로젝트에 강합니다',
        caseSub: '실제 기업/고객명은 노출하지 않고,<br/>오직 <b>프로젝트 유형</b>을 기준으로 예시를 제공합니다.',
        case1Title: '자동화 설비',
        case1Desc: '공정 조건/레이아웃/안전 요구사항등을 반영하여 최적의 자동화 파트너를 선별합니다.',
        case1Tag1: '조립/검사', case1Tag2: '물류/이송', case1Tag3: '라인 증설',
        case1Pill1: '유사 사례', case1Pill2: '제조/자동화',
        case2Title: '특수 목적 장비',
        case2Desc: '특수 장비는 "제조 가능성"이 핵심이므로, 유사레퍼런스를 최우선으로 검토합니다.',
        case2Tag1: '지그/툴', case2Tag2: '정밀 구동', case2Tag3: '특수 사양',
        case2Pill1: '유사 사례', case2Pill2: '특수 장비',
        case3Title: 'R&D 시제품',
        case3Desc: '유사 레퍼런스와 기술 범위를 기반으로 실제 구현 가능성이 높은 제조 파트너만 압축합니다.',
        case3Tag1: 'PoC', case3Tag2: '프로토타입', case3Tag3: '성능 검증',
        case3Pill1: '유사 사례', case3Pill2: 'R&D',
        case4Title: '플랜트/설비',
        case4Desc: '규모가 큰 플랜트 설비의 경우 유사성, 안전성, 납기를 기준으로 빠르게 연계합니다.',
        case4Tag1: '유사성', case4Tag2: '정밀도', case4Tag3: '안전/규제',
        case4Pill1: '유사 사례', case4Pill2: '플랜트',
        caseNoteTitle: '기업명/프로젝트명은 외부에 노출되지 않습니다.',
        caseNoteSub: '구체적인 정보는 진행 단계에 맞춰 요청하며,<br/>내부 검토 후 적합 파트너에게만 제한적으로 공유됩니다.',


        revenueKicker: 'Nexyfab · Revenue Model.',
        revenueTitle: '업계 최저 수수료 4%에 도전하다, Nexyfab 책임 매칭 시스템',
        revenueSub: '문의부터 설계·양산 착수까지, 최종 수수료는 견적의 4~7%(VAT 별도)만 부담합니다.',
        revenueStep1Title: 'Step 1. 매칭 신청금',
        revenueStep1Price: '50만 원 (VAT 별도)',
        revenueStep1Value: '기술 검토 및 파트너 선별 (실패 시 결제 금액 환불)',
        revenueStep1Desc: '단순 연결을 넘어 전문 기술 검토를 통해 최적의 제조사를 선별합니다. 적합한 파트너를 찾지 못할 경우 결제하신 금액을 환불해 드리는 No-Risk 정책을 운영합니다.',
        revenueStep2Title: 'Step 2. 계약 체결 및 수수료 정산',
        revenueStep2Rate: '기본 수수료 4~7%',
        revenueStep2Value: '계약 체결 시 (Step 1 신청금 100% 공제)',
        revenueStep2Desc: '파트너 매칭 후 계약 체결 시 기본 수수료(4~7%, VAT 별도)를 정산합니다. Step 1 신청금은 수수료에서 100% 공제됩니다.',
        revenueStep3Title: 'Step 3. 설계·양산 착수 및 납품 관리',
        revenueStep3Reward: '납품 완료까지 책임 관리',
        revenueStep3Value: '설계부터 납품까지 전담 오퍼레이터 밀착 지원',
        revenueStep3Desc: '계약 체결 이후 설계 착수부터 납품 완료까지 전담 오퍼레이터가 일정 관리, 품질 확인, 이슈 대응 등 원활한 진행을 위해 파트너사와 함께 도움을 드립니다.',
        revenueFooterNote1: '',
        revenueFooterNote2: '',
        revenueFooterNote3: '* 최소 수수료는 50만 원(Step 1 비용, VAT 별도)으로 설정됩니다.',
        revenueFooterNote4: '* 수수료 및 위약금에 대한 상세 정책은 서비스 이용약관을 확인해 주세요.',
        revenueFlow1: '50만원 매칭 신청금',
        revenueFlow2: '계약 체결 시 수수료 정산',
        revenueFlow3: '설계·양산 착수 및 납품 관리',

        // ── New: Platform positioning ──
        platformKicker: 'NexyFab · Design to Manufacturing.',
        platformTitle: '설계부터 제조까지,\n하나의 플랫폼에서',
        platformSub: '브라우저에서 바로 3D CAD 설계, 구조 해석, 위상 최적화까지.\n설계가 끝나면 30만+ 공장 DB에서 즉시 견적을 받고 최적의 제조사와 연결됩니다.',
        platformCta1: '3D 설계 시작하기',
        platformCta2: '제조사 매칭 받기',
        factories: '공장 DB 검색',
        platformMicro: '무료 · 가입 불필요 · 브라우저에서 바로 시작',
        platformSearchPlaceholder: '제조사 바로 검색해보세요',
        platformSearchBtn: '검색',
        socialStat1: '300,000+',
        socialStat1Label: '한·중 공장 DB',
        socialStat2: '16종',
        socialStat2Label: '3D 형상 라이브러리',
        socialStat3: '무료',
        socialStat3Label: '기본 플랜 제공',
        wf1Hint: '파라메트릭 3D CAD · 16개 형상 · 스케치→돌출',
        wf2Hint: 'FEA 구조 해석 · 모달 분석 · 열전달 시뮬레이션',
        wf3Hint: 'SIMP 위상 최적화 · DFM 체크 · 경량화',
        wf4Hint: '자동 2D 도면 · 비용 산출 · 제조사 비교',
        wf5Hint: '공장 검색 · 30만+ 공장 DB · NDA 지원',
        featTabDesign: '설계',
        featTabAnalysis: '해석',
        featTabMfg: '제조',
        platformBadge1: '무료 3D CAD',
        platformBadge2: 'FEA 해석',
        platformBadge3: 'AI 최적화',
        platformBadge4: '즉시 견적',

        // ── New: Feature showcase ──
        featKicker: 'NexyFab · Capabilities.',
        featTitle: '엔지니어를 위한 올인원 도구',
        featSub: '설계, 해석, 최적화, 견적까지 — SolidWorks급 기능을 브라우저에서 무료로.',
        feat1Title: '파라메트릭 3D CAD',
        feat1Desc: '16가지 형상, 스케치 → 돌출, 필렛, 챔퍼, 패턴 등 전문 피처로 부품을 설계하세요.',
        feat2Title: '구조 해석 (FEA)',
        feat2Desc: '응력, 변위, 안전 계수를 시뮬레이션하여 설계 검증을 수행합니다.',
        feat3Title: '위상 최적화',
        feat3Desc: 'SIMP 알고리즘으로 강도를 유지하면서 재료를 최대 40% 절감하는 최적 구조를 생성합니다.',
        feat4Title: '모달 & 열해석',
        feat4Desc: '고유진동수 분석과 열전달 시뮬레이션으로 동적/열적 안정성을 확인합니다.',
        feat5Title: 'DFM 분석',
        feat5Desc: '제조 가능성을 자동 분석하고, 벽 두께·언더컷·공차 문제를 사전에 감지합니다.',
        feat6Title: '자동 도면 & 견적',
        feat6Desc: '2D 도면 자동 생성, 비용 산출, 제조사 매칭까지 원클릭으로 완료합니다.',

        // ── New: Workflow ──
        wfKicker: 'NexyFab · Workflow.',
        wfTitle: '설계에서 제조까지 5단계',
        wfSub: '아이디어가 실제 부품이 되기까지, 하나의 플랫폼에서 끝냅니다.',
        wf1Title: '설계',
        wf1Desc: '브라우저에서 파라메트릭 3D 모델링',
        wf2Title: '해석',
        wf2Desc: 'FEA, 열해석, 모달 분석으로 검증',
        wf3Title: '최적화',
        wf3Desc: '위상 최적화로 경량화 & DFM 체크',
        wf4Title: '견적',
        wf4Desc: '즉시 비용 산출 & 제조사 비교',
        wf5Title: '제조',
        wf5Desc: '공장 DB 검색으로 최적 제조사 연결',

        // ── New: Persona cards ──
        personaKicker: 'NexyFab · For You.',
        personaTitle: '누구를 위한 플랫폼인가요?',
        persona1Title: '설계 엔지니어',
        persona1Desc: 'SolidWorks 없이도 전문 설계 & 해석. 브라우저에서 바로 작업하세요.',
        persona1Cta: '3D 설계 시작',
        persona2Title: '구매 담당자',
        persona2Desc: '도면 업로드 → 즉시 견적 비교. 검증된 제조사만 추천합니다.',
        persona2Cta: '견적 요청',
        persona3Title: '스타트업 / 메이커',
        persona3Desc: '아이디어를 시제품으로. 무료 CAD + 소량 생산 견적을 한 번에.',
        persona3Cta: '무료로 시작',

        ctaKicker: 'Nexyfab · Get Started.',
        ctaTitle: '이제 프로젝트를 시작해볼까요?',
        ctaSub: '짧은 키워드 한 줄이면 충분합니다.<br/>내부 검토 후 가장 적합한 파트너와 연결해 드립니다.',
        ctaBtn1: '프로젝트 문의',
        ctaBtn2: '키워드 검색',

        // ── Onboarding overlay ──
        onboardingTitle: '어떤 작업을 하시나요?',
        onboardingSub: '목적에 맞는 경로로 바로 안내해 드릴게요.',
        onboardingPath1: '3D 설계 시작',
        onboardingPath1Desc: '브라우저에서 바로 CAD 설계 · 해석 · 최적화',
        onboardingPath2: '제조 문의',
        onboardingPath2Desc: '도면 업로드 · 견적 비교 · 제조사 매칭',
        onboardingPath3: '파트너 찾기',
        onboardingPath3Desc: '키워드로 최적의 제조사를 검색',
        onboardingSkip: '건너뛰기',
        howPage: {
            heroTitle: 'How we Work',
            heroSub: '키워드 검색부터 납품까지, 전문 기술 검토와 데이터 기반 매칭으로<br/>최적의 제조 파트너를 찾아드립니다.',
            step1Tag: 'Step 1',
            step1Title: 'AI 정밀 분석 (Smart Analysis)',
            step1Desc: '프로젝트 키워드를 기반으로 제조 관점에서 필요한 공정 구조와 기술 범위를 정리합니다. 매칭을 위한 분석 기준이 이 단계에서 정의됩니다.<br/><br/><strong style="color:#0b5cff;">[Input] 프로젝트 키워드 → [Output] 매칭 기준 및 기술 범위 도출</strong>',
            step2Tag: 'Step 2',
            step2Title: '글로벌 DB 매칭 (Global DB Matching)',
            step2Desc: '한국과 중국의 제조 DB를 기반으로, 보유 설비·유사 레퍼런스·공정 적합도를 종합 분석하여 우선 검토 대상 파트너를 압축합니다.<br/><br/><strong style="color:#0b5cff;">[Input] 분석 기준 → [Output] 적합 후보 3~5곳 및 추천 및 근거</strong>',
            step3Tag: 'Step 3',
            step3Title: '연결 및 협업 지원 (Connection & Support)',
            step3Desc: '선별된 파트너의 수행 이력과 역량 정보를 확인한 후, 플랫폼을 통해 문의·견적·발주 과정을 지원합니다.<br/><br/><strong style="color:#0b5cff;">[Input] 후보 선택 → [Output] NDA 지원 및 협업 진행</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* 선별 기준: 유사 레퍼런스 / 보유 설비 / 품질 관련 인증 보유 여부</span>',
            whyTitle: '기술적 차별점 (Why us?)',
            why1Title: '데이터 기반 매칭 근거',
            why1Desc: '단순 검색 결과가 아닌, 보유 설비·유사 프로젝트 수행 이력·공정 범위를 기반으로 추천 사유를 객관적 데이터로 제공합니다.',
            diagramTitle: '한·중 제조 워크플로우',
            diagramStep1: 'AI 스마트 분석',
            diagramStep1Sub: '요구스펙 자동 도출',
            diagramStep2: '글로벌 DB 매칭',
            diagramStep2Sub: 'Top 3~5 파트너 추천',
            diagramStep3: '검증된 연결',
            diagramStep3Sub: '소개 + NDA 지원',
            why2Title: '한·중 통합 제조 DB',
            why2Desc: '한국과 중국 제조 인프라를 통합한 DB를 기반으로, 기술 이해를 바탕으로 한 매칭을 지원합니다. 단순 중개가 아닌, 개발 관점이 반영된 연결이 강점입니다.',
            why3Title: '품질 기준 정보 제공 (Q/C)',
            why3Desc: '파트너의 보유 설비, 품질 인증 여부, 수행 이력 등의 정보를 사전 검토 기준으로 제공합니다.<br/>※ 단. 넥시팹를 통하지 않은 생산 품질에 대한 최종 책임은 계약 당사자 간에 귀속됩니다.',
            why4Title: '보안 및 기밀 유지 (NDA)',
            why4Desc: '플랫폼 내 NDA 체결 절차를 지원하며, 프로젝트 정보는 내부 검토 범위 내에서만 공유됩니다.',
            statsTitle: '제조의 고민, 데이터로 해답을 찾다',
            statsSub: '한국과 중국의 통합 제조 DB와 축적된 레퍼런스로 최적의 매칭을 약속합니다.',
            statsFactories: '300,000+',
            statsFactoriesLabel: '공장 데이터베이스 (DB)',
            statsRefs: '10,000+',
            statsRefsLabel: '협력사 누적 프로젝트 레퍼런스',
            casePrompt: '실제로 배터리 관리 시스템(BMS)이나 AI 서버 하드웨어 매칭이 어떻게 이루어졌는지 확인해 보세요.',
            caseBtn: '실제 매칭 사례 보기',
            ssTitle: '성공 사례 (Success Stories)',
            ssRef1: 'BMS(배터리 관리 시스템) 최적 매칭',
            ssRef2: 'AI 서버 하드웨어 개발 협력'
        }
    },
    en: {
        heroKicker: 'Nexyfab · Find Manufacturers.',
        heroTitle: 'Find Your Ideal<br/>Development Partner',
        heroSub: 'Enter product keywords to instantly search<br/>300k+ Korean & Chinese factory database.',
        searchPlaceholder: 'Ex: Battery Automation',
        placeholderList: ['Battery Automation', 'Food Production Tools', 'Precision Machining', 'Logistics Systems', 'Semiconductor Tools'],
        searchBtn: 'Search',
        searching: 'Searching...',
        searchingSub: '(within 30 sec)',
        manufacturer: 'Manufacturer',
        industry: 'Industry',
        score: 'Score',
        contactTitle: '📨 Enter Contact Information',
        contactCompany: 'Name (Company)',
        contactPhone: 'Phone Number',
        contactEmail: 'Email',
        contactSubmit: 'Inquire',
        tabKoFactories: 'Korean Factories',
        tabCnFactories: 'Chinese Factories',
        noKoResults: 'No Korean factories found.',
        noCnResults: 'No Chinese factories found.',
        applyDashboard: 'Apply Now with Dashboard',
        loginApply: 'Login & Apply',
        applyDesc: 'AI RFP generation · quote comparison · dedicated support',
        gotoDashboard: 'Go to Dashboard →',
        signIn: 'Sign In →',
        orDirectContact: 'or contact us directly',
        statCount: '300k+',
        formSubmitting: 'Processing...',
        alertSuccess: 'Your inquiry has been successfully submitted.',
        alertError: 'An error occurred. Please try again later.',
        totalResults: 'Total',
        contactGuide: '* Name (Company), Phone, and Email are required to submit.',
        statKr: 'Korea/China Factories',
        statRef: 'Partner References',
        heroNote: '* Actual company names are not shown to customers,<br/>and are transferred for internal verification only upon inquiry submission.',

        howKicker: 'Nexyfab · How it Works.',
        howTitle: 'From Keyword to Connection',
        howSub: 'Search → Analysis → Selection → Connection → Actual Project Progress',
        step1Title: 'Requirements Input',
        step1Desc: 'Enter requirements as keywords to create analysis criteria.',
        step1Tag1: 'Battery Automation Equipment', step1Tag2: 'Special Purpose Equipment', step1Tag3: 'Process Improvement',
        step2Title: 'DB Search',
        step2Desc: 'Interpret keywords and organize candidates based on similar references/manufacturing capability data.',
        step2List1: 'Semantic expansion (synonyms/similar categories)',
        step2List2: 'Calculate suitability based on similar references',
        step2List3: 'Filter by industry/equipment/process conditions',
        step3Title: 'Selection of Suitable Partners',
        step3Desc: 'We narrow down the candidates to those who are "most suitable" rather than just "available".',
        step3List1: 'Tech difficulty/field matching',
        step3List2: 'Reflecting scope and reliability',
        step3List3: 'Exclude overlapping/unsuitable candidates',
        step4Title: 'Inquiry Connection',
        step4Desc: 'Project information is not disclosed externally, and is connected within the necessary scope after internal review.',
        step4Note: '* Actual company names are not shown to customers and are only transferred for internal verification.',
        howBottomTitle: 'Start with keyword search.',
        howBottomSub: 'You can start with just short keywords.',
        howBottomBtn: 'Keyword Search',

        whyKicker: 'Nexyfab · Why.',
        whyTitle: 'Different Standard of Connection',
        whySub: 'Not just simple matching, but matching based on actual feasibility and suitability.',
        why1Title: 'Not Random Quote Requests',
        why1Desc: 'Only qualified candidates are selected and delivered, reducing communication costs.',
        why2Title: 'Data-Based Filtering',
        why2Desc: 'Keyword interpretation, similar references, industry/equipment/process suitability are all reflected.',
        why3Title: 'Project Info Confidentiality Principle',
        why3Desc: 'Actual company names are not shown to customers, and are managed only for internal verification.',
        why4Title: 'Fast to Decision-Making',
        why4Desc: 'Not a "list of possible companies", but compressed "suitable candidates to review first".',
        whyCtaTitle: 'Shall we start matching right now?',
        whyCtaBtn: 'Project Inquiry',

        caseKicker: 'Nexyfab · Use Cases.',
        caseTitle: 'Strong in these projects',
        caseSub: 'We provide examples based only on <b><br/>project types</b>, without disclosing actual company/customer names.',
        case1Title: 'Automation Equipment',
        case1Desc: 'We select automation equipment partners by reflecting <br/>process conditions/layout/safety requirements.',
        case1Tag1: 'Assembly/Inspection', case1Tag2: 'Logistics/Transfer', case1Tag3: 'Line Expansion',
        case1Pill1: 'Similar Case', case1Pill2: 'Manu/Auto',
        case2Title: 'Special Purpose Equipment',
        case2Desc: 'Since "manufacturing feasibility" is key for special equipment, <br/>we prioritize similar references.',
        case2Tag1: 'Tools/Jigs', case2Tag2: 'Precision Drive', case2Tag3: 'Special Specs',
        case2Pill1: 'Similar Case', case2Pill2: 'Special Equipment',
        case3Title: 'R&D Prototype',
        case3Desc: 'Based on similar references and technical scope, we only narrow down manufacturing partners with high actual implementation possibility.',
        case3Tag1: 'PoC', case3Tag2: 'Prototype', case3Tag3: 'Performance Verification',
        case3Pill1: 'Similar Case', case3Pill2: 'R&D',
        case4Title: 'Plant/Equipment',
        case4Desc: 'For plant equipment, candidates are quickly connected <br/>based on similarity, safety, and delivery time.',
        case4Tag1: 'Similarity', case4Tag2: 'Precision', case4Tag3: 'Safety/Regulations',
        case4Pill1: 'Similar Case', case4Pill2: 'Plant',
        caseNoteTitle: 'Company/Project names are not disclosed externally.',
        caseNoteSub: 'Required information is requested according to the progress stage, <br/>and shared only with suitable partners after internal review.',


        revenueKicker: 'Nexyfab · Revenue Model.',
        revenueTitle: "Challenging Industry Lowest 4%, Nexyfab's Responsible Matching System",
        revenueSub: 'From inquiry to design & production kickoff—your final fee is only 4~7% of the quote (excl. VAT).',
        revenueStep1Title: 'Step 1. Matching Application Fee',
        revenueStep1Price: '400 USD (excl. VAT)',
        revenueStep1Value: 'Tech Review & Selection (Full Refund on Failure)',
        revenueStep1Desc: 'We go beyond simple connection to select the best manufacturer through professional tech review. We operate a No-Risk policy where the full application fee is refunded if no suitable partner is found.',
        revenueStep2Title: 'Step 2. Contract & Fee Settlement',
        revenueStep2Rate: 'Base Fee 4~7%',
        revenueStep2Value: 'Upon Contract (Step 1 Fee 100% Credited)',
        revenueStep2Desc: 'After partner matching, the base fee (4~7%, excl. VAT) is settled at contract signing. Your Step 1 application fee is fully credited toward this amount.',
        revenueStep3Title: 'Step 3. Design & Production Kickoff Management',
        revenueStep3Reward: 'Managed Until Delivery',
        revenueStep3Value: 'Dedicated operator support from design to delivery',
        revenueStep3Desc: 'After contract signing, a dedicated operator assists with scheduling, quality checks, and issue coordination throughout the design and production process, working alongside your partner to help ensure smooth delivery.',
        revenueFooterNote1: '',
        revenueFooterNote2: '',
        revenueFooterNote3: '* The minimum commission is set at 400 USD (Step 1 cost, excl. VAT).',
        revenueFooterNote4: '* For detailed fee and penalty policies, please refer to the Terms of Service.',
        revenueFlow1: '400 USD Application Fee',
        revenueFlow2: 'Fee Settlement at Contract',
        revenueFlow3: 'Design & Production Kickoff Management',

        // ── New: Platform positioning ──
        platformKicker: 'NexyFab · Design to Manufacturing.',
        platformTitle: 'From Design to Manufacturing,\nAll in One Platform',
        platformSub: '3D CAD, structural analysis, and topology optimization right in your browser.\nOnce your design is ready, get instant quotes from 300,000+ factories and connect with the best manufacturers.',
        platformCta1: 'Start 3D Design',
        platformCta2: 'Find Manufacturers',
        factories: 'Browse Factories',
        platformMicro: 'Free · No signup · Start in your browser',
        platformSearchPlaceholder: 'Search manufacturers now',
        platformSearchBtn: 'Search',
        socialStat1: '300,000+',
        socialStat1Label: 'Korea/China Factory DB',
        socialStat2: '16',
        socialStat2Label: '3D Shape Library',
        socialStat3: 'Free',
        socialStat3Label: 'Free Plan Available',
        wf1Hint: 'Parametric 3D CAD · 16 shapes · Sketch to Extrude',
        wf2Hint: 'FEA Structural · Modal Analysis · Thermal Simulation',
        wf3Hint: 'SIMP Topology Optimization · DFM Check · Lightweighting',
        wf4Hint: 'Auto 2D Drawing · Cost Estimation · Manufacturer Comparison',
        wf5Hint: 'Factory Search · 300k+ Factory DB · NDA Support',
        featTabDesign: 'Design',
        featTabAnalysis: 'Analysis',
        featTabMfg: 'Manufacturing',
        platformBadge1: 'Free 3D CAD',
        platformBadge2: 'FEA Analysis',
        platformBadge3: 'AI Optimization',
        platformBadge4: 'Instant Quotes',

        // ── New: Feature showcase ──
        featKicker: 'NexyFab · Capabilities.',
        featTitle: 'All-in-One Tools for Engineers',
        featSub: 'Design, analyze, optimize, and quote — SolidWorks-level features, free in your browser.',
        feat1Title: 'Parametric 3D CAD',
        feat1Desc: '16 shapes, sketch-to-extrude, fillets, chamfers, patterns, and professional features.',
        feat2Title: 'Structural Analysis (FEA)',
        feat2Desc: 'Simulate stress, displacement, and safety factors to validate your design.',
        feat3Title: 'Topology Optimization',
        feat3Desc: 'SIMP algorithm generates optimal structures, reducing material by up to 40% while maintaining strength.',
        feat4Title: 'Modal & Thermal Analysis',
        feat4Desc: 'Natural frequency analysis and heat transfer simulation for dynamic/thermal stability.',
        feat5Title: 'DFM Analysis',
        feat5Desc: 'Automated manufacturability checks — wall thickness, undercuts, and tolerance issues detected upfront.',
        feat6Title: 'Auto Drawing & Quoting',
        feat6Desc: 'Auto-generate 2D drawings, cost estimates, and manufacturer matching in one click.',

        // ── New: Workflow ──
        wfKicker: 'NexyFab · Workflow.',
        wfTitle: 'Design to Manufacturing in 5 Steps',
        wfSub: 'From idea to real parts — all in one platform.',
        wf1Title: 'Design',
        wf1Desc: 'Parametric 3D modeling in your browser',
        wf2Title: 'Analyze',
        wf2Desc: 'Validate with FEA, thermal, and modal analysis',
        wf3Title: 'Optimize',
        wf3Desc: 'Topology optimization & DFM checks',
        wf4Title: 'Quote',
        wf4Desc: 'Instant cost estimation & manufacturer comparison',
        wf5Title: 'Manufacture',
        wf5Desc: 'Search factory DB to find the best manufacturer',

        // ── New: Persona cards ──
        personaKicker: 'NexyFab · For You.',
        personaTitle: 'Who is this platform for?',
        persona1Title: 'Design Engineers',
        persona1Desc: 'Professional CAD & FEA without SolidWorks. Design directly in your browser.',
        persona1Cta: 'Start 3D Design',
        persona2Title: 'Procurement Managers',
        persona2Desc: 'Upload drawings → instant quote comparison. Only verified manufacturers.',
        persona2Cta: 'Request Quote',
        persona3Title: 'Startups & Makers',
        persona3Desc: 'Turn ideas into prototypes. Free CAD + small-batch quotes, all in one place.',
        persona3Cta: 'Start Free',

        ctaKicker: 'Nexyfab · Get Started.',
        ctaTitle: 'Shall we start your project now?',
        ctaSub: 'Just one line of keywords is enough.<br/>After internal review, we will connect you with the most suitable partner.',
        ctaBtn1: 'Submit Project',
        ctaBtn2: 'Keyword Search',

        // ── Onboarding overlay ──
        onboardingTitle: 'What are you looking for?',
        onboardingSub: 'We\'ll guide you to the right place.',
        onboardingPath1: 'Start 3D Design',
        onboardingPath1Desc: 'CAD modeling, analysis & optimization in browser',
        onboardingPath2: 'Manufacturing Inquiry',
        onboardingPath2Desc: 'Upload drawings · Compare quotes · Match manufacturers',
        onboardingPath3: 'Find Partners',
        onboardingPath3Desc: 'Search for the best manufacturers by keyword',
        onboardingSkip: 'Skip',

        howPage: {
            heroTitle: 'How we Work',
            heroSub: 'From search to connection — proceed from design to mass production<br/>based on a verified partner shortlist and objective matching data.',
            step1Tag: 'Step 1',
            step1Title: 'AI Smart Analysis',
            step1Desc: 'Based on project keywords, we organize the necessary process structure and technical scope from a manufacturing perspective. Analysis criteria for matching are defined at this stage.<br/><br/><strong style="color:#0b5cff;">[Input] Project Keywords → [Output] Deriving Matching Criteria & Tech Scope</strong>',
            step2Tag: 'Step 2',
            step2Title: 'Global DB Matching',
            step2Desc: 'Based on manufacturing DBs in Korea and China, we comprehensively analyze equipment, similar references, and process suitability to narrow down partners for priority review.<br/><br/><strong style="color:#0b5cff;">[Input] Analysis Criteria → [Output] 3–5 Suitable Candidates with Recommendation Rationale</strong>',
            step3Tag: 'Step 3',
            step3Title: 'Connection & Support',
            step3Desc: 'After verifying the performance history and capability information of the selected partners, we support the inquiry, quotation, and ordering process through the platform.<br/><br/><strong style="color:#0b5cff;">[Input] Candidate Selection → [Output] NDA Support & Collaboration Progress</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* Selection Criteria: Similar References / Equipment / Quality-related Certifications</span>',
            whyTitle: 'Why Nexyfab?',
            why1Title: 'Data-driven Rationale',
            why1Desc: 'We provide objective data for recommendation reasons—based on equipment, similar project history, and process scope—rather than just simple search results.',
            diagramTitle: 'Korea-China Manufacturing Workflow',
            diagramStep1: 'AI Smart Analysis',
            diagramStep1Sub: 'Required specs summary',
            diagramStep2: 'Global DB Matching',
            diagramStep2Sub: 'Top 3–5 factories',
            diagramStep3: 'Verified Connection',
            diagramStep3Sub: 'Intro + NDA support',
            why2Title: 'Integrated Korea-China Mfg. DB',
            why2Desc: 'Based on an integrated DB of Korea and China manufacturing infrastructure, we support matching founded on technical understanding. Our strength is a connection that reflects a development perspective, not just simple mediation.',
            why3Title: 'Providing Quality Standard Info (Q/C)',
            why3Desc: 'We provide information such as the partner\'s equipment, quality certifications, and performance history as preliminary review criteria.<br/>*Note: Final responsibility for production quality not processed through Nexyfab lies with the contracting parties.',
            why4Title: 'Security & NDA',
            why4Desc: 'We support NDA signing procedures within the platform, and project information is shared only within the scope of internal review.',
            statsTitle: 'Solving Manufacturing Challenges with Data',
            statsSub: 'Promising optimal matching through our integrated Korea-China manufacturing database and accumulated references.',
            statsFactories: '300,000+',
            statsFactoriesLabel: 'Factory Database',
            statsRefs: '10,000+',
            statsRefsLabel: 'Verified Partner Project References',
            casePrompt: 'Check out how battery management systems (BMS) or AI server hardware matching actually happened.',
            caseBtn: 'See Example Matches',
            ssTitle: 'Success Stories',
            ssRef1: 'BMS (Battery Management System) Matching',
            ssRef2: 'AI Server Hardware Development'
        }
    },
    ja: {
        heroKicker: 'Nexyfab · メーカー検索.',
        heroTitle: '最適な開発パートナーを<br/>検索してみましょう',
        heroSub: '製品キーワードを入力するだけで、韓国・中国の工場DB 30万件以上から<br/>関連メーカーをすぐに検索できます.',
        searchPlaceholder: '例: バッテリー自動化設備',
        placeholderList: ['バッテリー自動化設備', '食品生産設備', '精密部品加工', '物流搬送システム', '半導体洗浄装置'],
        searchBtn: '検索',
        searching: '検索中...',
        searchingSub: '(約30秒以内)',
        manufacturer: 'メーカー',
        industry: '業種',
        score: '適合度',
        contactTitle: '📨 連絡先の入力',
        contactCompany: '名前（会社名）',
        contactPhone: '電話番号',
        contactEmail: 'メールアドレス',
        contactSubmit: '問い合わせ',
        tabKoFactories: '韓国の工場',
        tabCnFactories: '中国の工場',
        noKoResults: '該当する韓国の工場はありません。',
        noCnResults: '該当する中国の工場はありません。',
        applyDashboard: 'ダッシュボードで申請',
        loginApply: 'ログインして申請',
        applyDesc: 'AI RFP自動生成・見積比較・専任サポート',
        gotoDashboard: 'ダッシュボードへ →',
        signIn: 'ログイン →',
        orDirectContact: 'または直接お問い合わせ',
        statCount: '30万+',
        formSubmitting: '処理中...',
        alertSuccess: 'お問い合わせが送信されました。',
        alertError: 'エラーが発生しました。後でもう一度お試しください。',
        totalResults: '全',
        contactGuide: '* 名前（会社名）、電話番号、メールアドレスは必須入力項目です。',
        statKr: '韓国・中国の工場',
        statRef: '提携先累積実績',
        heroNote: '* 実際の会社名は顧客画面に表示されず、<br/>問い合わせ提出時に内部確認用としてのみ伝達されます。',

        howKicker: 'Nexyfab · How it Works.',
        howTitle: 'キーワード入力から接続まで',
        howSub: '検索 → 分析 → 選定 → 接続 → 実際のプロジェクト進行',
        step1Title: '要件入力',
        step1Desc: '要件をキーワードとして入力すると、分析基準が生成されます。',
        step1Tag1: 'バッテリー自動化設備', step1Tag2: '特殊目的機器', step1Tag3: '工程改善',
        step2Title: 'DB検索',
        step2Desc: 'キーワードをもとに、韓国・中国の工場DBから関連メーカーを検索します。',
        step2List1: '意味拡張(同義語/類似カテゴリ)',
        step2List2: '類似リファレンスに基づく適合度算出',
        step2List3: '業種/設備/工程条件によるフィルタリング',
        step3Title: '適合パートナーの選別',
        step3Desc: '「可能な場所」ではなく「最も適合する場所」を優先検討候補として圧縮します。',
        step3List1: '技術難易度/分野マッチング',
        step3List2: '遂行範囲と信頼性の反映',
        step3List3: '重複・不適合候補の除外',
        step4Title: '問い合わせの接続',
        step4Desc: 'プロジェクト情報は外部に公開されず、内部検討後、必要な範囲で接続されます。',
        step4Note: '* 実際の会社名は顧客画面에 표시되지 않으며, 内部確認用としてのみ伝達されます。',
        howBottomTitle: 'キーワード検索から始めましょう。',
        howBottomSub: '短いキーワードだけでも始めることができます。',
        howBottomBtn: 'キーワード検索',

        whyKicker: 'Nexyfab · Why.',
        whyTitle: '「接続」の基準が異なります',
        whySub: '単純なマッチングではなく、実際の遂行可能性と適合性を基準にマッチングします。',
        why1Title: '無作為な見積もり依頼ではありません',
        why1Desc: '要件に合致する適格な候補のみを選別して伝達するため、コミュニケーション費用が削減されます.',
        why2Title: 'データ基盤のフィルタリング',
        why2Desc: 'キーワード解釈、類似リファレンス、業種/設備/工程条件をすべて反映します。',
        why3Title: 'プロジェクト情報非公開の原則',
        why3Desc: '実際の会社名は顧客に公開されず、内部確認のためにのみ管理されます。',
        why4Title: '意思決定まで迅速に',
        why4Desc: '「可能なリスト」ではなく、「最初に検討すべき適合候補群」に圧縮します。',
        whyCtaTitle: '今すぐマッチングを始めましょうか？',
        whyCtaBtn: 'プロジェクトお問い合わせ',

        caseKicker: 'Nexyfab · Use Cases.',
        caseTitle: 'こんなプロジェクト에 강합니다',
        caseSub: '実際の企業/顧客名は公開せず、<br/><b>プロジェクトタイプ</b>のみに基づいて例を提供します。',
        case1Title: '自動化設備',
        case1Desc: '工程条件/レイアウト/安全要件などを反映して<br/>最適な自動化パートナーを選別します。',
        case1Tag1: '組立/検査', case1Tag2: '物流/搬送', case1Tag3: 'ライン増設',
        case1Pill1: '類似事例', case1Pill2: '製造/自動化',
        case2Title: '特殊目的機器',
        case2Desc: '特殊機器は「製造可能性」が重要であるため、<br/>類似リファレン스를 최우선으로 검토합니다.',
        case2Tag1: '治具/ツール', case2Tag2: '精密駆動', case2Tag3: '特別仕様',
        case2Pill1: '類似事例', case2Pill2: '特殊機器',
        case3Title: 'R&Dプロトタイプ',
        case3Desc: '類似のリファレンスと技術範囲に基づき、実際の実現可能性が高い製造パートナーのみを厳選します。',
        case3Tag1: 'PoC', case3Tag2: 'プロトタイプ', case3Tag3: '性能検証',
        case3Pill1: '類似事例', case3Pill2: 'R&D',
        case4Title: 'プラント/設備',
        case4Desc: 'プラント設備の場合、類似性、安全性、<br/>納期を基準に迅速に連携します。',
        case4Tag1: '類似性', case4Tag2: '精度', case4Tag3: '安全/規制',
        case4Pill1: '類似事例', case4Pill2: 'プラント',
        caseNoteTitle: '企業名/プロジェクト名は外部에 노출되지 않습니다.',
        caseNoteSub: '進行段階に合わせて必要な情報をリクエストし、<br/>内部検討後、適合パートナーにのみ共有されます。',

        reviewKicker: 'Nexyfab · Reviews.',
        reviewTitle: '顧客レビュー',
        reviewSub: '「レビュー」では感想よりも<b>結果</b>が重要です。<br/>実際のプロセスでよくあるフィードバックを整理しました。',
        reviewKpi1Title: 'リードタイムの短縮',
        reviewKpi1Desc: '候補の発見/検証時間を短縮し、意思決定を迅速にします。',
        reviewKpi2Title: '要件の整理',
        reviewKpi2Desc: '曖昧な初期段階でも、開発の方向性を明確に確立します。',
        reviewKpi3Title: 'カスタムマッチング',
        reviewKpi3Desc: '類似リファレンス/業種/難易度を基準に候補を圧縮します。',
        review1Tag: 'Featured', review1Pill1: 'PoC', review1Pill2: '新規開発', review1Pill3: 'リードタイム',
        review1Quote: '適切なパートナーを迅速に接続してくれたため、<br/>短期間でPoCを成功させることができました。',
        review1Who: '大企業 A', review1WhoSub: '新製品開発', review1Chip: 'Enterprise',
        review2Tag: 'ベンダーソーシング', review2Pill1: 'DB基盤', review2Pill2: '検証',
        review2Quote: 'メーカーDBのおかげで、市場調査に<br/>費やす時間が半分に短縮されました。',
        review2Who: '中堅企業 B', review2WhoSub: 'ソーシング', review2Chip: 'Mid-size',
        review3Tag: '開発戦略', review3Pill1: 'ロードマップ',
        review3Quote: '単なる制作の連携ではなく、開発の方向性と範囲をまず整理してくれたため、プロジェクトの定義が非常に明確になりました。',
        review3Who: '中小企業 C', review3WhoSub: '戦略/コスト最適化', review3Chip1: 'ロードマップ', review3Chip2: 'SME',
        review4Tag: 'MVP', review4Pill1: 'コスト削減', review4Pill2: 'スケジュール',
        review4Quote: '見積もりコストが大幅に下がり、コミュニケーション基準が明確なため、<br/>開発がスムーズに進んでいます。',
        review4Who: 'スタートアップ S', review4WhoSub: 'MVP · コスト 절감', review4Chip: 'Startup',
        review5Tag: '工程管理', review5Pill1: '要件', review5Pill2: '品質',
        review5Quote: '要件が変更された場合でも基準を再調整し、<br/>最終的な成果物の一貫性を保ちます。',
        review5Who: 'メーカー D', review5WhoSub: '開発 · 品質', review5Chip1: '安定性', review5Chip2: 'Manufacturing',

        revenueKicker: 'Nexyfab · Revenue Model.',
        revenueTitle: '業界最低水準4%に挑戦, Nexyfab「責任マッチング」システム',
        revenueSub: 'お問い合わせから設計・量産着手まで、最終手数料は見積もりの4~7%（税別）のみです。',
        revenueStep1Title: 'Step 1. マッチング申請金',
        revenueStep1Price: '60,000 JPY（税別）',
        revenueStep1Value: '技術検討およびパートナー選別 (失敗時 全額返金)',
        revenueStep1Desc: '単なる接続を超え、専門的な技術検討を通じて最適な製造社を選別します。適切なパートナーが見つからない場合、申請金の全額を即座に返金するNo-Riskポリシーを運営しています。',
        revenueStep2Title: 'Step 2. 契約締結・手数料精算',
        revenueStep2Rate: '基本手数料 4~7%',
        revenueStep2Value: '契約締結時 (Step 1 申請金 100% 控除)',
        revenueStep2Desc: 'パートナーマッチング後、契約締結時に基本手数料（4~7%、税別）を精算します。Step 1 申請金は手数料から100%控除されます。',
        revenueStep3Title: 'Step 3. 設計・量産着手および納品管理',
        revenueStep3Reward: '納品完了まで責任管理',
        revenueStep3Value: '設計から納品まで専任オペレーターが密着サポート',
        revenueStep3Desc: '契約締結後、設計着手から納品完了まで専任オペレーターがスケジュール管理、品質確認、問題対応など、円滑な進行のためにパートナー企業とともにサポートいたします。',
        revenueFooterNote1: '',
        revenueFooterNote2: '',
        revenueFooterNote3: '* 最小手数料は 60,000 JPY（Step 1費用、税別）に設定されます。',
        revenueFooterNote4: '* 手数料および違約金の詳細については、サービス利用規約をご確認ください。',
        revenueFlow1: '60,000 JPY 申請金',
        revenueFlow2: '契約時 手数料精算',
        revenueFlow3: '設計・量産着手および納品管理',

        // ── New: Platform positioning ──
        platformKicker: 'NexyFab · Design to Manufacturing.',
        platformTitle: '設計から製造まで、\nひとつのプラットフォームで',
        platformSub: 'ブラウザで3D CAD設計、構造解析、トポロジー最適化まで。\n設計完了後、30万社以上の工場DBから即座に見積もりを取得し最適なメーカーと接続。',
        platformCta1: '3D設計を始める',
        platformCta2: 'メーカーマッチング',
        factories: '工場を探す',
        platformMicro: '無料 · 登録不要 · ブラウザですぐ開始',
        platformSearchPlaceholder: 'メーカーを検索してみましょう',
        platformSearchBtn: '検索',
        socialStat1: '300,000+',
        socialStat1Label: '韓中工場DB',
        socialStat2: '16種',
        socialStat2Label: '3D形状ライブラリ',
        socialStat3: '無料',
        socialStat3Label: '無料プラン提供',
        wf1Hint: 'パラメトリック3D CAD · 16形状 · スケッチ→押し出し',
        wf2Hint: 'FEA構造解析 · モーダル分析 · 熱伝達シミュレーション',
        wf3Hint: 'SIMPトポロジー最適化 · DFMチェック · 軽量化',
        wf4Hint: '自動2D図面 · コスト算出 · メーカー比較',
        wf5Hint: '工場DB検索 · 30万+工場DB · NDAサポート',
        featTabDesign: '設計',
        featTabAnalysis: '解析',
        featTabMfg: '製造',
        platformBadge1: '無料3D CAD',
        platformBadge2: 'FEA解析',
        platformBadge3: 'AI最適化',
        platformBadge4: '即時見積もり',

        // ── New: Feature showcase ──
        featKicker: 'NexyFab · Capabilities.',
        featTitle: 'エンジニアのためのオールインワンツール',
        featSub: '設計・解析・最適化・見積もり — SolidWorksレベルの機能をブラウザで無料で。',
        feat1Title: 'パラメトリック3D CAD',
        feat1Desc: '16種類の形状、スケッチ→押し出し、フィレット、面取り、パターンなどプロフェッショナル機能。',
        feat2Title: '構造解析（FEA）',
        feat2Desc: '応力、変位、安全係数をシミュレーションして設計を検証。',
        feat3Title: 'トポロジー最適化',
        feat3Desc: 'SIMPアルゴリズムで強度を維持しながら材料を最大40%削減する最適構造を生成。',
        feat4Title: 'モーダル＆熱解析',
        feat4Desc: '固有振動数解析と熱伝達シミュレーションで動的/熱的安定性を確認。',
        feat5Title: 'DFM分析',
        feat5Desc: '製造可能性を自動分析、壁厚・アンダーカット・公差問題を事前に検出。',
        feat6Title: '自動図面＆見積もり',
        feat6Desc: '2D図面自動生成、コスト算出、メーカーマッチングまでワンクリック。',

        // ── New: Workflow ──
        wfKicker: 'NexyFab · Workflow.',
        wfTitle: '設計から製造まで5ステップ',
        wfSub: 'アイデアから実際の部品まで、ひとつのプラットフォームで完結。',
        wf1Title: '設計',
        wf1Desc: 'ブラウザでパラメトリック3Dモデリング',
        wf2Title: '解析',
        wf2Desc: 'FEA・熱解析・モーダル解析で検証',
        wf3Title: '最適化',
        wf3Desc: 'トポロジー最適化＆DFMチェック',
        wf4Title: '見積もり',
        wf4Desc: '即時コスト算出＆メーカー比較',
        wf5Title: '製造',
        wf5Desc: '工場DB検索で最適メーカーに接続',

        // ── New: Persona cards ──
        personaKicker: 'NexyFab · For You.',
        personaTitle: 'どなた向けのプラットフォーム？',
        persona1Title: '設計エンジニア',
        persona1Desc: 'SolidWorksなしでプロの設計＆解析。ブラウザですぐに作業。',
        persona1Cta: '3D設計を開始',
        persona2Title: '購買担当者',
        persona2Desc: '図面アップロード→即時見積もり比較。検証済みメーカーのみ推薦。',
        persona2Cta: '見積もり依頼',
        persona3Title: 'スタートアップ',
        persona3Desc: 'アイデアを試作品に。無料CAD＋少量生産見積もりをまとめて。',
        persona3Cta: '無料で開始',

        ctaKicker: 'Nexyfab · Get Started.',
        ctaTitle: '今すぐプロジェクトを始めましょうか？',
        ctaSub: '短いキーワード1行で十分です。<br/>内部検討後、最適なパートナーと接続します。',
        ctaBtn1: 'プロジェクトお問い合わせ',
        ctaBtn2: 'キーワード検索',

        // ── Onboarding overlay ──
        onboardingTitle: 'どの作業をしますか？',
        onboardingSub: '目的に合ったページへご案内します。',
        onboardingPath1: '3D設計を始める',
        onboardingPath1Desc: 'ブラウザでCAD設計・解析・最適化',
        onboardingPath2: '製造問い合わせ',
        onboardingPath2Desc: '図面アップロード・見積比較・メーカーマッチング',
        onboardingPath3: 'パートナー検索',
        onboardingPath3Desc: 'キーワードで最適なメーカーを検索',
        onboardingSkip: 'スキップ',
        howPage: {
            heroTitle: 'How we Work',
            heroSub: '検索から接続まで、検証済みパートナー候補リストと<br/>客観的データを居に、設計から量産まで進めましょう。',
            step1Tag: 'Step 1',
            step1Title: 'AI精密分析 (Smart Analysis)',
            step1Desc: 'プロジェクトキーワードに基づき、製造の観点から必要な工程構造と技術範囲を整理します。マッチングのための分析基準はこの段階で定義されます。<br/><br/><strong style="color:#0b5cff;">[Input] プロジェクトキーワード → [Output] マッチング基準および技術範囲の導出</strong>',
            step2Tag: 'Step 2',
            step2Title: 'グローバルDBマッチング (Global DB Matching)',
            step2Desc: '韓国と中国の製造DBに基づき、保有設備・類似リファレンス・工程適合度を総合的に分析し、優先検討対象のパートナーを厳選します。<br/><br/><strong style="color:#0b5cff;">[Input] 分析基準 → [Output] 適合候補3〜5社および推薦根拠</strong>',
            step3Tag: 'Step 3',
            step3Title: '接続および連携サポート (Connection & Support)',
            step3Desc: '選定されたパートナーの遂行履歴と能力情報を確認した後、プラットフォームを通じてのお問い合わせ・見積・発注のプロセスをサポートします。<br/><br/><strong style="color:#0b5cff;">[Input] 候補選択 → [Output] NDAサポートおよび連携の進行</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* 選定基準：類似リファレンス / 保有設備 / 品質関連認証の有無</span>',
            whyTitle: '技術的な差別化 (Why us?)',
            why1Title: 'データに基づくマッチング根拠',
            why1Desc: '単なる検索結果ではなく、保有設備・類似プロジェクトの遂행 이력・工程範囲に基づき、推薦理由を客観的なデータとして提供します。',
            diagramTitle: '韓中製造ワークフロー',
            diagramStep1: 'AIスマート分析',
            diagramStep1Sub: 'スペック自動整理',
            diagramStep2: 'グローバルDBマッチング',
            diagramStep2Sub: '上位3〜5社推薦',
            diagramStep3: '検証済みコネクション',
            diagramStep3Sub: '紹介＋NDAサポート',
            why2Title: '韓中統合製造DB',
            why2Desc: '韓国と中国の製造インフラを統合したDBに基づき、技術理解に基づいたマッチングをサポートします。単なる仲介ではなく、開発の観点が反映された連携が強みです。',
            why3Title: '品質基準情報の提供 (Q/C)',
            why3Desc: 'パートナーの保有設備、品質認証の有無、遂行履歴などの情報を事前検討基準として提供します。<br/>※ただし、Nexyfabを通さない生産品質に関する最終的な責任は、契約当事者間に帰属します。',
            why4Title: 'セキュリティと機密保持 (NDA)',
            why4Desc: 'プラットフォーム内のNDA締結手続きをサポートし、プロジェクト情報は内部検討の範囲内でのみ共有されます。',
            statsTitle: '製造の悩みを描いたデータで解決',
            statsSub: '韓国と中国の統合製造DBと蓄積されたリファレンスで最適なマッチングをお約束します。',
            statsFactories: '300,000+',
            statsFactoriesLabel: '工場データベース (DB)',
            statsRefs: '10,000+',
            statsRefsLabel: '検証済みの提携先プロジェクト実績',
            casePrompt: 'バッテリー管理システム（BMS）やAIサーバーハードウェアのマッチングが実際どのように行われたか確認してみてください。',
            caseBtn: '実際のマッチング事例を見る',
            ssTitle: '成功事例 (Success Stories)',
            ssRef1: 'BMS (バッテリー管理システム) 最適マッチング',
            ssRef2: 'AIサーバーハードウェア開発協力'
        }
    },
    cn: {
        heroKicker: 'Nexyfab · 查找制造商.',
        heroTitle: '寻找您的理想<br/>开发合作伙伴',
        heroSub: '输入产品关键词，即可在30万+韩中工厂数据库中<br/>直接搜索相关制造商。',
        searchPlaceholder: '例：电池自动化设备',
        placeholderList: ['电池自动化设备', '食品生产设备', '精密零件加工', '物流输送系统', '半导体清洗设备'],
        ssTitle: '成功案例 (Success Stories)',
        ssRef1: 'BMS (电池管理系统) 最佳匹配',
        ssRef2: 'AI 服务器硬件开发合作',
        searchBtn: '搜索',
        searching: '搜索中...',
        searchingSub: '（约30秒内）',
        manufacturer: '制造商',
        industry: '行业',
        score: '匹配度',
        contactTitle: '📨 输入联系信息',
        contactCompany: '姓名（公司名称）',
        contactPhone: '电话号码',
        contactEmail: '电子邮箱',
        contactSubmit: '咨询',
        tabKoFactories: '韩国工厂',
        tabCnFactories: '中国工厂',
        noKoResults: '未找到韩国工厂。',
        noCnResults: '未找到中国工厂。',
        applyDashboard: '通过控制台申请',
        loginApply: '登录并申请',
        applyDesc: 'AI自动RFP · 报价比较 · 专属支持',
        gotoDashboard: '前往控制台 →',
        signIn: '登录 →',
        orDirectContact: '或直接联系我们',
        statCount: '30万+',
        formSubmitting: '处理中...',
        alertSuccess: '您的咨询已成功提交。',
        alertError: '发生错误，请稍后再试。',
        totalResults: '全',
        contactGuide: '* 姓名（公司名称）、电话和邮箱是必填项。',
        statKr: '韩国/中国工厂',
        statRef: '入驻企业累计案例',
        heroNote: '* 实际公司名称不会向客户显示，<br/>提交咨询时仅用于内部验证。',

        howKicker: 'Nexyfab · How it Works.',
        howTitle: '从关键词到成功对接',
        howSub: '搜索 → 分析 → 筛选 → 对接 → 实际项目推进',
        step1Title: '需求输入',
        step1Desc: '将需求作为关键词输入以生成分析标准。',
        step1Tag1: '电池自动化设备', step1Tag2: '专用设备', step1Tag3: '工艺改进',
        step2Title: 'DB搜索',
        step2Desc: '根据关键词，从韩中工厂数据库中搜索相关制造商。',
        step2List1: '语义扩展 (同义词/相似分类)',
        step2List2: '根据类似案例计算适合度',
        step2List3: '按行业/设备/工艺条件过滤',
        step3Title: '挑选合适的合作伙伴',
        step3Desc: '我们将候选对象从“可选”缩小为“最适合”的首选候选人。',
        step3List1: '技术难度/领域匹配',
        step3List2: '反映执行范围和可靠性',
        step3List3: '排除重复/不适合的候选对象',
        step4Title: '咨询对接',
        step4Desc: '项目信息不会对外公开，在内部评估后连接到必要范围。',
        step4Note: '* 实际公司名称不会向客户显示，仅传递以供内部审查。',
        howBottomTitle: '从关键词搜索开始。',
        howBottomSub: '只需简短关键词即可启动。',
        howBottomBtn: '关键词搜索',

        whyKicker: 'Nexyfab · Why.',
        whyTitle: '不同的“对接”标准',
        whySub: '不仅仅是简单的匹配，而是基于实际可行性和适合性的匹配。',
        why1Title: '拒绝盲目报价',
        why1Desc: '只筛选和传递符合要求的合格候选人，从而降低沟通成本。',
        why2Title: '基于数据的过滤',
        why2Desc: '不仅反映关键词解读，还综合考虑相似案例及行业/设备/工艺条件。',
        why3Title: '项目信息保密原则',
        why3Desc: '实际公司名称不会向客户披露，仅由内部管理部门查看。',
        why4Title: '加速决策进程',
        why4Desc: '不提供“可能的公司列表”，而是压缩为“优先审查的合适候选对象”群组。',
        whyCtaTitle: '我们要现在开始匹配吗？',
        whyCtaBtn: '项目咨询',

        caseKicker: 'Nexyfab · Use Cases.',
        caseTitle: '在这些项目中我们很有优势',
        caseSub: '我们在不披露实际公司/客户名称的情况下，<br/>仅根据<b>项目类型</b>提供示例。',
        case1Title: '自动化设备',
        case1Desc: '我们通过反映工艺条件/布局/安全要求来筛选<br/>最佳的自动化合作伙伴。',
        case1Tag1: '装配/检查', case1Tag2: '物流/转移', case1Tag3: '产线扩建',
        case1Pill1: '相似案例', case1Pill2: '制造/自动化',
        case2Title: '专用设备',
        case2Desc: '由于“制造可行性”是专用设备的关键，<br/>我们会优先审查类似案例。',
        case2Tag1: '工装/夹具', case2Tag2: '精密驱动', case2Tag3: '特殊规格',
        case2Pill1: '相似案例', case2Pill2: '专用设备',
        case3Title: '研发原型',
        case3Desc: '基于类似案例和技术范围，仅筛选出实现可能性高的制造合作伙伴。',
        case3Tag1: '概念验证 (PoC)', case3Tag2: '原型件', case3Tag3: '性能验证',
        case3Pill1: '相似案例', case3Pill2: '研发 (R&D)',
        case4Title: '工厂/设备',
        case4Desc: '对于大型厂房设备，我们将根据相似性、<br/>安全性和交期快速完成对接。',
        case4Tag1: '相似性', case4Tag2: '精度', case4Tag3: '安全/合规',
        case4Pill1: '相似案例', case4Pill2: '工厂',
        caseNoteTitle: '企业/项目名称不对外公开。',
        caseNoteSub: '详细信息会根据项目进度被要求提供，<br/>并在内部审核后仅与适合的合作伙伴共享。',

        reviewKicker: 'Nexyfab · Reviews.',
        reviewTitle: '客户评价',
        reviewSub: '在“评价”中，<b>结果</b>比感受更重要。<br/>我们梳理了实际流程中最常见的反馈。',
        reviewKpi1Title: '缩短交货时间',
        reviewKpi1Desc: '减少了发现/验证候选人的时间，并加快了决策速度。',
        reviewKpi2Title: '梳理需求',
        reviewKpi2Desc: '即使在模糊的早期阶段，开发方向也已明确确立。',
        reviewKpi3Title: '定制化匹配',
        reviewKpi3Desc: '根据相似参考文献/行业/难度压缩候选人。',
        review1Tag: 'Featured', review1Pill1: '概念验证(PoC)', review1Pill2: '新开发', review1Pill3: '交货时间',
        review1Quote: '他们迅速为我们对接到了合适的合作伙伴，<br/>帮助我们在短时间内成功完成了PoC。',
        review1Who: '大型企业 A', review1WhoSub: '新产品开发', review1Chip: '企业',
        review2Tag: '供应商采购', review2Pill1: '基于数据库', review2Pill2: '认证',
        review2Quote: '得益于制造商数据库，我们在市场调查上<br/>耗费的时间减少了一半。',
        review2Who: '中型企业 B', review2WhoSub: '采购', review2Chip: '中型',
        review3Tag: '开发战略', review3Pill1: '路线图',
        review3Quote: '不仅仅是简单的制作对接，而是先梳理了开发方向和范围，使项目定义变得更加清晰。',
        review3Who: '中小企业 C', review3WhoSub: '战略/成本优化', review3Chip1: '路线图', review3Chip2: '中小企业',
        review4Tag: 'MVP', review4Pill1: '降低成本', review4Pill2: '时间表',
        review4Quote: '预估成本大幅下降，并且因为沟通标准清晰，<br/>开发进行得非常顺利。',
        review4Who: '初创公司 S', review4WhoSub: 'MVP · 降低成本', review4Chip: '初创公司',
        review5Tag: '过程管理', review5Pill1: '要求', review5Pill2: '质量',
        review5Quote: '即使需求发生变化，他们也会重新调整标准，<br/>以确保最终产出的一致性。',
        review5Who: '制造商 D', review5WhoSub: '开发 · 品质', review5Chip1: '稳定性', review5Chip2: '制造',

        revenueKicker: 'Nexyfab · Revenue Model.',
        revenueTitle: '挑战行业最低佣金4%, Nexyfab"责任匹配"系统',
        revenueSub: '从咨询到设计·量产启动，最终佣金仅为报价的4~7%（不含税）。',
        revenueStep1Title: 'Step 1. 匹配申请费',
        revenueStep1Price: '3,000 CNY（不含税）',
        revenueStep1Value: '技术审查与合作伙伴筛选 (失败时全额退款)',
        revenueStep1Desc: '超越简单的连接，通过专业的技术审查筛选最适合的制造商。如未能找到合适的合作伙伴，我们将立即全额退还申请费，实行无风险政策。',
        revenueStep2Title: 'Step 2. 合同签署与费用结算',
        revenueStep2Rate: '基础佣金 4~7%',
        revenueStep2Value: '签署合同时 (Step 1 费用 100% 抵扣)',
        revenueStep2Desc: '与合作伙伴匹配后，签约时结算基础佣金（4~7%，不含税）。Step 1 申请费将100%从佣金中抵扣。',
        revenueStep3Title: 'Step 3. 设计·量产启动及交付管理',
        revenueStep3Reward: '交付完成前全程管理',
        revenueStep3Value: '从设计到交付，专属运营人员全程陪同支持',
        revenueStep3Desc: '合同签署后，从设计启动到交付完成，专属运营人员将协助进行进度管理、质量确认及问题协调，与合作伙伴携手确保项目顺利推进。',
        revenueFooterNote1: '',
        revenueFooterNote2: '',
        revenueFooterNote3: '* 最低佣金设定为 3,000 CNY（Step 1 费用，不含税）。',
        revenueFooterNote4: '* 有关费用及违约金的详细政策，请参阅服务条款。',
        revenueFlow1: '3,000 CNY 申请费',
        revenueFlow2: '签约时 费用结算',
        revenueFlow3: '设计·量产启动及交付管理',

        // ── New: Platform positioning ──
        platformKicker: 'NexyFab · Design to Manufacturing.',
        platformTitle: '从设计到制造，\n一个平台搞定',
        platformSub: '在浏览器中进行3D CAD设计、结构分析和拓扑优化。\n设计完成后，从30万+工厂数据库立即获取报价并连接最佳制造商。',
        platformCta1: '开始3D设计',
        platformCta2: '寻找制造商',
        factories: '浏览工厂',
        platformMicro: '免费 · 无需注册 · 浏览器直接开始',
        platformSearchPlaceholder: '立即搜索制造商',
        platformSearchBtn: '搜索',
        socialStat1: '300,000+',
        socialStat1Label: '韩中工厂数据库',
        socialStat2: '16种',
        socialStat2Label: '3D形状库',
        socialStat3: '免费',
        socialStat3Label: '免费基础计划',
        wf1Hint: '参数化3D CAD · 16种形状 · 草图到拉伸',
        wf2Hint: 'FEA结构分析 · 模态分析 · 热传导仿真',
        wf3Hint: 'SIMP拓扑优化 · DFM检查 · 轻量化',
        wf4Hint: '自动2D图纸 · 成本估算 · 制造商比较',
        wf5Hint: '工厂DB搜索 · 30万+工厂DB · NDA支持',
        featTabDesign: '设计',
        featTabAnalysis: '分析',
        featTabMfg: '制造',
        platformBadge1: '免费3D CAD',
        platformBadge2: 'FEA分析',
        platformBadge3: 'AI优化',
        platformBadge4: '即时报价',

        // ── New: Feature showcase ──
        featKicker: 'NexyFab · Capabilities.',
        featTitle: '工程师的一站式工具',
        featSub: '设计、分析、优化、报价 — SolidWorks级功能，浏览器中免费使用。',
        feat1Title: '参数化3D CAD',
        feat1Desc: '16种形状、草图到拉伸、倒角、圆角、阵列等专业功能。',
        feat2Title: '结构分析（FEA）',
        feat2Desc: '模拟应力、位移和安全系数，验证您的设计。',
        feat3Title: '拓扑优化',
        feat3Desc: 'SIMP算法生成最优结构，在保持强度的同时减少最多40%的材料。',
        feat4Title: '模态与热分析',
        feat4Desc: '固有频率分析和热传导仿真，确认动态/热稳定性。',
        feat5Title: 'DFM分析',
        feat5Desc: '自动分析可制造性 — 提前检测壁厚、底切和公差问题。',
        feat6Title: '自动图纸与报价',
        feat6Desc: '一键自动生成2D图纸、成本估算和制造商匹配。',

        // ── New: Workflow ──
        wfKicker: 'NexyFab · Workflow.',
        wfTitle: '从设计到制造5个步骤',
        wfSub: '从创意到实际零件 — 全部在一个平台完成。',
        wf1Title: '设计',
        wf1Desc: '在浏览器中进行参数化3D建模',
        wf2Title: '分析',
        wf2Desc: '通过FEA、热分析、模态分析验证',
        wf3Title: '优化',
        wf3Desc: '拓扑优化和DFM检查',
        wf4Title: '报价',
        wf4Desc: '即时成本估算和制造商比较',
        wf5Title: '制造',
        wf5Desc: '工厂DB搜索连接最佳制造商',

        // ── New: Persona cards ──
        personaKicker: 'NexyFab · For You.',
        personaTitle: '这个平台适合谁？',
        persona1Title: '设计工程师',
        persona1Desc: '无需SolidWorks的专业设计和分析。直接在浏览器中工作。',
        persona1Cta: '开始3D设计',
        persona2Title: '采购经理',
        persona2Desc: '上传图纸→即时报价比较。仅推荐经过验证的制造商。',
        persona2Cta: '请求报价',
        persona3Title: '创业公司',
        persona3Desc: '将创意变为原型。免费CAD + 小批量报价，一站式搞定。',
        persona3Cta: '免费开始',

        ctaKicker: 'Nexyfab · Get Started.',
        ctaTitle: '我们现在开始您的项目吗？',
        ctaSub: '只需一行简短的关键词即可。<br/>内部审核后，我们将为您对接最合适的合作伙伴。',
        ctaBtn1: '项目咨询',
        ctaBtn2: '关键词搜索',

        // ── Onboarding overlay ──
        onboardingTitle: '您想做什么？',
        onboardingSub: '我们将引导您到合适的页面。',
        onboardingPath1: '开始3D设计',
        onboardingPath1Desc: '在浏览器中进行CAD设计·分析·优化',
        onboardingPath2: '制造咨询',
        onboardingPath2Desc: '上传图纸·比较报价·匹配制造商',
        onboardingPath3: '查找合作伙伴',
        onboardingPath3Desc: '通过关键词搜索最佳制造商',
        onboardingSkip: '跳过',
        howPage: {
            heroTitle: 'How we Work',
            heroSub: '从搜索到对接，基于验证合作伙伴候选名单与<br/>客观数据，完成从设计到量产的全流程。',
            step1Tag: 'Step 1',
            step1Title: 'AI精准分析 (Smart Analysis)',
            step1Desc: '基于项目关键词，从制造角度梳理所需的工艺结构和技术范围。对接所需的分析标准在此阶段定义。<br/><br/><strong style="color:#0b5cff;">[Input] 项目关键词 → [Output] 推导匹配标准及技术范围</strong>',
            step2Tag: 'Step 2',
            step2Title: '全球匹配 (Global DB Matching)',
            step2Desc: '基于中韩制造数据库，综合分析现有设备、类似案例、工艺匹配度，筛选出优先考虑的合作伙伴。<br/><br/><strong style="color:#0b5cff;">[Input] 分析标准 → [Output] 3–5家合适候选及推荐理由</strong>',
            step3Tag: 'Step 3',
            step3Title: '对接与协作支持 (Connection & Support)',
            step3Desc: '在确认筛选出的合作伙伴的履约记录和能力信息后，通过平台支持咨询、报价、下单流程。<br/><br/><strong style="color:#0b5cff;">[Input] 选择候选 → [Output] NDA支持及协作进行</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* 筛选标准：类似案例 / 现有设备 / 是否持有品质相关认证</span>',
            whyTitle: '技术优势 (Why us?)',
            why1Title: '基于数据的匹配依据',
            why1Desc: '提供客观的数据推荐理由，基于现有设备、类似项目履约记录、工艺范围，而非单纯的搜索结果。',
            diagramTitle: '中韩制造工作流程',
            diagramStep1: 'AI智能分析',
            diagramStep1Sub: '规格自动整理',
            diagramStep2: '全球DB匹配',
            diagramStep2Sub: '推荐Top3~5工厂',
            diagramStep3: '验证对接',
            diagramStep3Sub: '介绍+NDA支持',
            why2Title: '中韩联合制造数据库',
            why2Desc: '基于整合的中韩制造基础设施数据库，支持基于技术理解的匹配。我们的优势在于反映开发视角的对接，而不仅仅是简单的中介。',
            why3Title: '提供品质标准信息 (Q/C)',
            why3Desc: '提供合作伙伴的现有设备、品质认证情况、履约记录等信息作为初步审核标准。<br/>※注：未通过 Nexyfab 进行的生产品质的最终责任归属于合同双方。',
            why4Title: '安全保护与保密协议 (NDA)',
            why4Desc: '支持平台内的 NDA 签署流程，项目信息仅在内部审核范围内共享。',
            statsTitle: '用数据解决制造难题',
            statsSub: '通过中韩整合的制造数据库(DB)和积累的案例，我们承诺提供最佳的匹配服务。',
            statsFactories: '300,000+',
            statsFactoriesLabel: '工厂数据库 (DB)',
            statsRefs: '10,000+',
            statsRefsLabel: '已验证合作伙伴项目案例',
            casePrompt: '了解电池管理系统 (BMS) 或 AI 服务器硬件匹配是如何实际实现的。',
            caseBtn: '查看实际匹配案例',
            ssTitle: '成功案例 (Success Stories)',
            ssRef1: 'BMS (电池管理系统) 最佳匹配',
            ssRef2: 'AI 服务器硬件开发合作'
        }
    },
    es: {
        heroKicker: 'Nexyfab · Buscar Fabricantes.',
        heroTitle: 'Encuentre su socio<br/>de desarrollo ideal',
        heroSub: 'Ingrese palabras clave del producto y busque al instante<br/>en más de 300k fábricas de Corea y China.',
        searchPlaceholder: 'Ej: Automatización de baterías',
        placeholderList: ['Automatización de baterías', 'Equipos de producción alimentaria', 'Mecanizado de precisión', 'Sistemas logísticos', 'Equipos semiconductores'],
        searchBtn: 'Buscar',
        searching: 'Buscando...',
        searchingSub: '(en menos de 30 seg)',
        manufacturer: 'Fabricante',
        industry: 'Sector',
        score: 'Compatibilidad',
        contactTitle: '📨 Información de contacto',
        contactCompany: 'Nombre (Empresa)',
        contactPhone: 'Teléfono',
        contactEmail: 'Correo electrónico',
        contactSubmit: 'Consultar',
        tabKoFactories: 'Fábricas Coreanas',
        tabCnFactories: 'Fábricas Chinas',
        noKoResults: 'No se encontraron fábricas coreanas.',
        noCnResults: 'No se encontraron fábricas chinas.',
        applyDashboard: 'Solicitar desde el Panel',
        loginApply: 'Iniciar sesión y Solicitar',
        applyDesc: 'Generación AI RFP · comparación de cotizaciones · soporte dedicado',
        gotoDashboard: 'Ir al Panel →',
        signIn: 'Iniciar sesión →',
        orDirectContact: 'o contáctenos directamente',
        statCount: '300k+',
        formSubmitting: 'Procesando...',
        alertSuccess: 'Su consulta ha sido enviada exitosamente.',
        alertError: 'Ocurrió un error. Por favor, inténtelo más tarde.',
        totalResults: 'Total',
        contactGuide: '* Nombre (Empresa), Teléfono y Correo electrónico son campos obligatorios.',
        statKr: 'Fábricas en Corea/China',
        statRef: 'Referencias acumuladas de socios',
        heroNote: '* Los nombres reales de las empresas no se muestran a los clientes<br/>y solo se transmiten para verificación interna al enviar una consulta.',

        howKicker: 'Nexyfab · How it Works.',
        howTitle: 'De la palabra clave a la conexión',
        howSub: 'Búsqueda → Análisis → Selección → Conexión → Avance real del proyecto',
        step1Title: 'Ingreso de requisitos',
        step1Desc: 'Ingrese sus requisitos como palabras clave para generar criterios de análisis.',
        step1Tag1: 'Equipos de automatización de baterías', step1Tag2: 'Equipos de uso especial', step1Tag3: 'Mejora de procesos',
        step2Title: 'Búsqueda en DB',
        step2Desc: 'Buscamos fabricantes relevantes en la base de datos de fábricas de Corea y China usando las palabras clave ingresadas.',
        step2List1: 'Expansión semántica (sinónimos/categorías similares)',
        step2List2: 'Cálculo de idoneidad basado en referencias similares',
        step2List3: 'Filtrado por sector/equipos/condiciones de proceso',
        step3Title: 'Selección de socios adecuados',
        step3Desc: 'Reducimos los candidatos a los "más adecuados", no solo a los "disponibles".',
        step3List1: 'Dificultad técnica / compatibilidad de campo',
        step3List2: 'Alcance de ejecución y fiabilidad',
        step3List3: 'Exclusión de candidatos duplicados o no aptos',
        step4Title: 'Conexión de consulta',
        step4Desc: 'La información del proyecto no se divulga externamente y se conecta dentro del alcance necesario tras una revisión interna.',
        step4Note: '* Los nombres reales de las empresas no se muestran a los clientes y solo se transmiten para verificación interna.',
        howBottomTitle: 'Comience con una búsqueda por palabras clave.',
        howBottomSub: 'Con unas pocas palabras clave es suficiente para empezar.',
        howBottomBtn: 'Búsqueda por palabras clave',

        whyKicker: 'Nexyfab · Why.',
        whyTitle: 'Un estándar de conexión diferente',
        whySub: 'No es un simple emparejamiento, sino una conexión basada en viabilidad real y compatibilidad.',
        why1Title: 'No son solicitudes de cotización al azar',
        why1Desc: 'Solo seleccionamos y entregamos candidatos calificados que cumplen los requisitos, reduciendo costos de comunicación.',
        why2Title: 'Filtrado basado en datos',
        why2Desc: 'Consideramos la interpretación de palabras clave, referencias similares y condiciones de sector/equipos/proceso.',
        why3Title: 'Principio de confidencialidad del proyecto',
        why3Desc: 'Los nombres reales de las empresas no se muestran a los clientes y se gestionan únicamente para verificación interna.',
        why4Title: 'Decisiones más rápidas',
        why4Desc: 'No ofrecemos una "lista de posibles empresas", sino un grupo reducido de "candidatos idóneos para revisión prioritaria".',
        whyCtaTitle: '¿Comenzamos con el emparejamiento ahora?',
        whyCtaBtn: 'Consulta de proyecto',

        caseKicker: 'Nexyfab · Use Cases.',
        caseTitle: 'Destacamos en estos proyectos',
        caseSub: 'Proporcionamos ejemplos basados únicamente en<br/><b>tipos de proyecto</b>, sin divulgar nombres reales de empresas o clientes.',
        case1Title: 'Equipos de automatización',
        case1Desc: 'Seleccionamos socios de automatización considerando<br/>condiciones de proceso/diseño/requisitos de seguridad.',
        case1Tag1: 'Ensamblaje/Inspección', case1Tag2: 'Logística/Transporte', case1Tag3: 'Ampliación de línea',
        case1Pill1: 'Caso similar', case1Pill2: 'Fabricación/Automatización',
        case2Title: 'Equipos de uso especial',
        case2Desc: 'Dado que la "viabilidad de fabricación" es clave en equipos especiales,<br/>priorizamos la revisión de referencias similares.',
        case2Tag1: 'Herramientas/Utillajes', case2Tag2: 'Accionamiento de precisión', case2Tag3: 'Especificaciones especiales',
        case2Pill1: 'Caso similar', case2Pill2: 'Equipo especial',
        case3Title: 'Prototipos de I+D',
        case3Desc: 'Basándonos en referencias similares y alcance técnico, seleccionamos únicamente socios de fabricación con alta viabilidad de implementación.',
        case3Tag1: 'PoC', case3Tag2: 'Prototipo', case3Tag3: 'Verificación de rendimiento',
        case3Pill1: 'Caso similar', case3Pill2: 'I+D',
        case4Title: 'Plantas/Equipamiento',
        case4Desc: 'Para equipamiento de plantas, conectamos rápidamente<br/>basándonos en similitud, seguridad y plazos de entrega.',
        case4Tag1: 'Similitud', case4Tag2: 'Precisión', case4Tag3: 'Seguridad/Normativa',
        case4Pill1: 'Caso similar', case4Pill2: 'Planta',
        caseNoteTitle: 'Los nombres de empresas/proyectos no se divulgan externamente.',
        caseNoteSub: 'La información detallada se solicita según la etapa de avance<br/>y se comparte solo con socios adecuados tras una revisión interna.',

        reviewKicker: 'Nexyfab · Reviews.',
        reviewTitle: 'Opiniones de clientes',
        reviewSub: 'En las "opiniones", los <b>resultados</b> importan más que las impresiones.<br/>Hemos recopilado los comentarios más frecuentes del proceso real.',
        reviewKpi1Title: 'Reducción de plazos',
        reviewKpi1Desc: 'Reducimos el tiempo de búsqueda y verificación de candidatos, acelerando la toma de decisiones.',
        reviewKpi2Title: 'Clarificación de requisitos',
        reviewKpi2Desc: 'Incluso en etapas iniciales ambiguas, establecemos una dirección de desarrollo clara.',
        reviewKpi3Title: 'Emparejamiento personalizado',
        reviewKpi3Desc: 'Reducimos candidatos según referencias similares, sector y nivel de dificultad.',
        review1Tag: 'Destacado', review1Pill1: 'PoC', review1Pill2: 'Nuevo desarrollo', review1Pill3: 'Plazo de entrega',
        review1Quote: 'Nos conectaron rápidamente con el socio adecuado,<br/>lo que nos permitió completar el PoC en poco tiempo.',
        review1Who: 'Gran empresa A', review1WhoSub: 'Desarrollo de nuevos productos', review1Chip: 'Enterprise',
        review2Tag: 'Búsqueda de proveedores', review2Pill1: 'Basado en BD', review2Pill2: 'Verificación',
        review2Quote: 'Gracias a la base de datos de fabricantes,<br/>redujimos a la mitad el tiempo de investigación de mercado.',
        review2Who: 'Mediana empresa B', review2WhoSub: 'Aprovisionamiento', review2Chip: 'Mediana',
        review3Tag: 'Estrategia de desarrollo', review3Pill1: 'Hoja de ruta',
        review3Quote: 'No fue solo una conexión de fabricación; primero organizaron la dirección y el alcance del desarrollo, lo que definió el proyecto con mucha claridad.',
        review3Who: 'Pyme C', review3WhoSub: 'Estrategia/Optimización de costos', review3Chip1: 'Hoja de ruta', review3Chip2: 'Pyme',
        review4Tag: 'MVP', review4Pill1: 'Reducción de costos', review4Pill2: 'Cronograma',
        review4Quote: 'Los costos estimados bajaron significativamente y, gracias a criterios de comunicación claros,<br/>el desarrollo avanza sin contratiempos.',
        review4Who: 'Startup S', review4WhoSub: 'MVP · Reducción de costos', review4Chip: 'Startup',
        review5Tag: 'Gestión de procesos', review5Pill1: 'Requisitos', review5Pill2: 'Calidad',
        review5Quote: 'Incluso cuando cambiaron los requisitos, reajustaron los criterios<br/>y mantuvieron la consistencia del entregable final.',
        review5Who: 'Fabricante D', review5WhoSub: 'Desarrollo · Calidad', review5Chip1: 'Estabilidad', review5Chip2: 'Fabricación',

        revenueKicker: 'Nexyfab · Revenue Model.',
        revenueTitle: 'Desafiando la comisión más baja del sector: 4%. Sistema de emparejamiento responsable de Nexyfab',
        revenueSub: 'Desde la consulta hasta el inicio del diseño y producción, la comisión final es solo del 4~7% (IVA excl.).',
        revenueStep1Title: 'Paso 1. Tarifa de solicitud de emparejamiento',
        revenueStep1Price: '400 USD',
        revenueStep1Value: 'Revisión técnica y selección de socios (reembolso total si no hay resultado)',
        revenueStep1Desc: 'Vamos más allá de una simple conexión: seleccionamos al mejor fabricante mediante una revisión técnica profesional. Si no encontramos un socio adecuado, reembolsamos íntegramente la tarifa de solicitud bajo nuestra política sin riesgo.',
        revenueStep2Title: 'Paso 2. Contrato y liquidación de comisión',
        revenueStep2Rate: 'Comisión base 4~7%',
        revenueStep2Value: 'Al firmar el contrato (deducción del 100% del Paso 1)',
        revenueStep2Desc: 'Tras el emparejamiento con el socio, se liquida la comisión base (4~7%, IVA excl.) al firmar el contrato. La tarifa del Paso 1 se deduce íntegramente.',
        revenueStep3Title: 'Paso 3. Inicio de diseño y producción, y gestión de entrega',
        revenueStep3Reward: 'Gestión hasta la entrega',
        revenueStep3Value: 'Soporte dedicado desde el diseño hasta la entrega',
        revenueStep3Desc: 'Tras la firma del contrato, un operador dedicado asiste en la gestión de plazos, control de calidad y resolución de incidencias, trabajando junto al socio fabricante para facilitar una entrega sin contratiempos.',
        revenueFooterNote1: '',
        revenueFooterNote2: '',
        revenueFooterNote3: '* La comisión mínima se establece en 400 USD (costo del Paso 1, IVA excl.).',
        revenueFooterNote4: '* Para políticas detalladas de comisiones y penalizaciones, consulte los Términos de Servicio.',
        revenueFlow1: 'Tarifa de solicitud 400 USD',
        revenueFlow2: 'Liquidación de comisión al contrato',
        revenueFlow3: 'Gestión de inicio y entrega',

        // ── New: Platform positioning ──
        platformKicker: 'NexyFab · Design to Manufacturing.',
        platformTitle: 'Del Diseno a la Fabricacion,\nTodo en Una Plataforma',
        platformSub: 'CAD 3D, analisis estructural y optimizacion topologica en tu navegador.\nUna vez listo tu diseno, obtén cotizaciones instantáneas de 300.000+ fabricas y conecta con los mejores.',
        platformCta1: 'Iniciar Diseno 3D',
        platformCta2: 'Buscar Fabricantes',
        factories: 'Explorar Fábricas',
        platformMicro: 'Gratis · Sin registro · Empieza en tu navegador',
        platformSearchPlaceholder: 'Busca fabricantes ahora',
        platformSearchBtn: 'Buscar',
        socialStat1: '300,000+',
        socialStat1Label: 'Fabricas Corea/China',
        socialStat2: '16',
        socialStat2Label: 'Biblioteca 3D',
        socialStat3: 'Gratis',
        socialStat3Label: 'Plan Gratuito',
        wf1Hint: 'CAD 3D Parametrico · 16 formas · Boceto a Extruir',
        wf2Hint: 'FEA Estructural · Analisis Modal · Simulacion Termica',
        wf3Hint: 'SIMP Topologia · DFM Check · Aligeramiento',
        wf4Hint: 'Plano 2D Auto · Estimacion de Costos · Comparacion',
        wf5Hint: 'Búsqueda DB · 300k+ Fábricas · NDA',
        featTabDesign: 'Diseno',
        featTabAnalysis: 'Analisis',
        featTabMfg: 'Fabricacion',
        platformBadge1: 'CAD 3D Gratis',
        platformBadge2: 'Analisis FEA',
        platformBadge3: 'Optimización IA',
        platformBadge4: 'Cotizacion Instantanea',

        // ── New: Feature showcase ──
        featKicker: 'NexyFab · Capabilities.',
        featTitle: 'Herramientas Todo-en-Uno para Ingenieros',
        featSub: 'Disena, analiza, optimiza y cotiza — funciones nivel SolidWorks, gratis en tu navegador.',
        feat1Title: 'CAD 3D Parametrico',
        feat1Desc: '16 formas, boceto a extruir, filetes, chaflanes, patrones y funciones profesionales.',
        feat2Title: 'Analisis Estructural (FEA)',
        feat2Desc: 'Simula esfuerzos, desplazamiento y factores de seguridad para validar tu diseno.',
        feat3Title: 'Optimizacion Topologica',
        feat3Desc: 'Algoritmo SIMP genera estructuras optimas, reduciendo material hasta 40%.',
        feat4Title: 'Analisis Modal y Termico',
        feat4Desc: 'Analisis de frecuencia natural y simulacion termica para estabilidad dinamica.',
        feat5Title: 'Analisis DFM',
        feat5Desc: 'Verificacion automatica de fabricabilidad — detecta problemas de espesor y tolerancias.',
        feat6Title: 'Planos y Cotizacion Auto',
        feat6Desc: 'Genera planos 2D, estimaciones de costo y emparejamiento con fabricantes en un clic.',

        // ── New: Workflow ──
        wfKicker: 'NexyFab · Workflow.',
        wfTitle: 'Del Diseno a Fabricacion en 5 Pasos',
        wfSub: 'De la idea a piezas reales — todo en una plataforma.',
        wf1Title: 'Disenar',
        wf1Desc: 'Modelado 3D parametrico en tu navegador',
        wf2Title: 'Analizar',
        wf2Desc: 'Validar con FEA, analisis termico y modal',
        wf3Title: 'Optimizar',
        wf3Desc: 'Optimizacion topologica y verificacion DFM',
        wf4Title: 'Cotizar',
        wf4Desc: 'Estimacion de costos y comparacion de fabricantes',
        wf5Title: 'Fabricar',
        wf5Desc: 'Búsqueda en DB para conectar con el mejor fabricante',

        // ── New: Persona cards ──
        personaKicker: 'NexyFab · For You.',
        personaTitle: '¿Para quién es esta plataforma?',
        persona1Title: 'Ingenieros de Diseno',
        persona1Desc: 'CAD y FEA profesional sin SolidWorks. Disena directo en tu navegador.',
        persona1Cta: 'Iniciar Diseno 3D',
        persona2Title: 'Gerentes de Compras',
        persona2Desc: 'Sube planos → comparacion instantanea de cotizaciones. Solo fabricantes verificados.',
        persona2Cta: 'Solicitar Cotizacion',
        persona3Title: 'Startups y Makers',
        persona3Desc: 'Convierte ideas en prototipos. CAD gratis + cotizaciones de produccion en un solo lugar.',
        persona3Cta: 'Comenzar Gratis',

        ctaKicker: 'Nexyfab · Get Started.',
        ctaTitle: '¿Comenzamos su proyecto ahora?',
        ctaSub: 'Con una sola línea de palabras clave es suficiente.<br/>Tras una revisión interna, le conectaremos con el socio más adecuado.',
        ctaBtn1: 'Consulta de proyecto',
        ctaBtn2: 'Búsqueda por palabras clave',

        // ── Onboarding overlay ──
        onboardingTitle: '¿Qué necesitas hacer?',
        onboardingSub: 'Te guiaremos al lugar correcto.',
        onboardingPath1: 'Iniciar diseño 3D',
        onboardingPath1Desc: 'Diseño CAD, análisis y optimización en el navegador',
        onboardingPath2: 'Consulta de fabricación',
        onboardingPath2Desc: 'Subir planos · Comparar presupuestos · Encontrar fabricantes',
        onboardingPath3: 'Buscar socios',
        onboardingPath3Desc: 'Busca los mejores fabricantes por palabra clave',
        onboardingSkip: 'Omitir',
        howPage: {
            heroTitle: 'How we Work',
            heroSub: 'De la búsqueda a la conexión: avance del diseño a la producción en serie<br/>con una lista verificada de socios y datos de emparejamiento objetivos.',
            step1Tag: 'Paso 1',
            step1Title: 'Análisis inteligente con IA (Smart Analysis)',
            step1Desc: 'A partir de las palabras clave del proyecto, organizamos la estructura de procesos y el alcance técnico necesarios desde la perspectiva de fabricación. Los criterios de análisis para el emparejamiento se definen en esta etapa.<br/><br/><strong style="color:#0b5cff;">[Entrada] Palabras clave del proyecto → [Salida] Criterios de emparejamiento y alcance técnico</strong>',
            step2Tag: 'Paso 2',
            step2Title: 'Emparejamiento con BD global (Global DB Matching)',
            step2Desc: 'Con base en las BD de fabricación de Corea y China, analizamos integralmente equipos, referencias similares e idoneidad de procesos para priorizar socios candidatos.<br/><br/><strong style="color:#0b5cff;">[Entrada] Criterios de análisis → [Salida] 3–5 candidatos adecuados con fundamento de recomendación</strong>',
            step3Tag: 'Paso 3',
            step3Title: 'Conexión y soporte de colaboración (Connection & Support)',
            step3Desc: 'Tras verificar el historial de desempeño y la información de capacidad de los socios seleccionados, apoyamos el proceso de consulta, cotización y pedido a través de la plataforma.<br/><br/><strong style="color:#0b5cff;">[Entrada] Selección de candidato → [Salida] Soporte de NDA y avance de colaboración</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* Criterios de selección: Referencias similares / Equipos / Certificaciones de calidad</span>',
            whyTitle: '¿Por qué Nexyfab?',
            why1Title: 'Fundamento basado en datos',
            why1Desc: 'Proporcionamos datos objetivos como base de recomendación, basados en equipos, historial de proyectos similares y alcance de procesos, no solo resultados de búsqueda.',
            diagramTitle: 'Flujo de trabajo de fabricación Corea-China',
            diagramStep1: 'Análisis inteligente con IA',
            diagramStep1Sub: 'Resumen de especificaciones',
            diagramStep2: 'Emparejamiento con BD global',
            diagramStep2Sub: 'Top 3–5 fábricas',
            diagramStep3: 'Conexión verificada',
            diagramStep3Sub: 'Presentación + soporte NDA',
            why2Title: 'BD integrada de fabricación Corea-China',
            why2Desc: 'Basándonos en una BD integrada de infraestructura de fabricación de Corea y China, ofrecemos un emparejamiento con comprensión técnica. Nuestra fortaleza es una conexión que refleja la perspectiva de desarrollo, no una simple intermediación.',
            why3Title: 'Información de estándares de calidad (Q/C)',
            why3Desc: 'Proporcionamos información sobre equipos del socio, certificaciones de calidad e historial de desempeño como criterios de revisión preliminar.<br/>*Nota: La responsabilidad final sobre la calidad de producción no gestionada a través de Nexyfab recae en las partes contratantes.',
            why4Title: 'Seguridad y NDA',
            why4Desc: 'Facilitamos los procedimientos de firma de NDA dentro de la plataforma, y la información del proyecto se comparte únicamente dentro del alcance de la revisión interna.',
            statsTitle: 'Resolviendo desafíos de fabricación con datos',
            statsSub: 'Garantizamos un emparejamiento óptimo a través de nuestra base de datos integrada de fabricación Corea-China y referencias acumuladas.',
            statsFactories: '300,000+',
            statsFactoriesLabel: 'Base de datos de fábricas',
            statsRefs: '10,000+',
            statsRefsLabel: 'Referencias verificadas de proyectos de socios',
            casePrompt: 'Descubra cómo se realizó el emparejamiento de sistemas de gestión de baterías (BMS) o hardware de servidores de IA.',
            caseBtn: 'Ver casos de emparejamiento',
            ssTitle: 'Casos de éxito (Success Stories)',
            ssRef1: 'Emparejamiento óptimo de BMS (Sistema de gestión de baterías)',
            ssRef2: 'Desarrollo de hardware de servidores de IA'
        }
    },
    ar: {
        heroKicker: 'Nexyfab · البحث عن المصنّعين.',
        heroTitle: 'ابحث عن شريك<br/>التطوير المثالي',
        heroSub: 'أدخل كلمات مفتاحية للمنتج وابحث فورًا<br/>في قاعدة بيانات تضم أكثر من 300 ألف مصنع كوري وصيني.',
        searchPlaceholder: 'مثال: أتمتة البطاريات',
        placeholderList: ['أتمتة البطاريات', 'معدات إنتاج الأغذية', 'التشغيل الدقيق', 'أنظمة لوجستية', 'معدات أشباه الموصلات'],
        searchBtn: 'بحث',
        searching: 'جارٍ البحث...',
        searchingSub: '(خلال 30 ثانية)',
        manufacturer: 'المصنّع',
        industry: 'القطاع',
        score: 'التوافق',
        contactTitle: '📨 معلومات الاتصال',
        contactCompany: 'الاسم (الشركة)',
        contactPhone: 'رقم الهاتف',
        contactEmail: 'البريد الإلكتروني',
        contactSubmit: 'استفسار',
        tabKoFactories: 'مصانع كورية',
        tabCnFactories: 'مصانع صينية',
        noKoResults: 'لم يتم العثور على مصانع كورية.',
        noCnResults: 'لم يتم العثور على مصانع صينية.',
        applyDashboard: 'التقديم عبر لوحة التحكم',
        loginApply: 'تسجيل الدخول والتقديم',
        applyDesc: 'إنشاء RFP بالذكاء الاصطناعي · مقارنة العروض · دعم مخصص',
        gotoDashboard: 'الذهاب للوحة التحكم →',
        signIn: 'تسجيل الدخول →',
        orDirectContact: 'أو تواصل معنا مباشرة',
        statCount: '+300 ألف',
        formSubmitting: 'جاري المعالجة...',
        alertSuccess: 'تم إرسال استفسارك بنجاح.',
        alertError: 'حدث خطأ. يرجى المحاولة لاحقاً.',
        totalResults: 'الإجمالي',
        contactGuide: '* الاسم (الشركة) ورقم الهاتف والبريد الإلكتروني حقول إلزامية.',
        statKr: 'مصانع كوريا/الصين',
        statRef: 'مراجع الشركاء المتراكمة',
        heroNote: '* لا تُعرض أسماء الشركات الفعلية للعملاء،<br/>وتُنقل فقط للتحقق الداخلي عند تقديم الاستفسار.',

        howKicker: 'Nexyfab · How it Works.',
        howTitle: 'من الكلمة المفتاحية إلى الربط',
        howSub: 'بحث ← تحليل ← اختيار ← ربط ← تقدّم فعلي في المشروع',
        step1Title: 'إدخال المتطلبات',
        step1Desc: 'أدخل متطلباتك ككلمات مفتاحية لإنشاء معايير التحليل.',
        step1Tag1: 'معدات أتمتة البطاريات', step1Tag2: 'معدات ذات أغراض خاصة', step1Tag3: 'تحسين العمليات',
        step2Title: 'بحث في قاعدة البيانات',
        step2Desc: 'نبحث عن المصنّعين ذوي الصلة في قاعدة بيانات المصانع الكورية والصينية باستخدام الكلمات المفتاحية.',
        step2List1: 'توسيع دلالي (مرادفات/فئات مشابهة)',
        step2List2: 'حساب الملاءمة بناءً على مراجع مماثلة',
        step2List3: 'تصفية حسب القطاع/المعدات/ظروف العملية',
        step3Title: 'اختيار الشركاء المناسبين',
        step3Desc: 'نضيّق المرشحين إلى "الأكثر ملاءمة" وليس فقط "المتاحين".',
        step3List1: 'مطابقة الصعوبة التقنية/المجال',
        step3List2: 'نطاق التنفيذ والموثوقية',
        step3List3: 'استبعاد المرشحين المكررين أو غير المناسبين',
        step4Title: 'ربط الاستفسار',
        step4Desc: 'لا تُفصح معلومات المشروع خارجيًا، ويتم الربط ضمن النطاق اللازم بعد المراجعة الداخلية.',
        step4Note: '* لا تُعرض أسماء الشركات الفعلية للعملاء وتُنقل فقط للتحقق الداخلي.',
        howBottomTitle: 'ابدأ بالبحث عبر الكلمات المفتاحية.',
        howBottomSub: 'بضع كلمات مفتاحية قصيرة كافية للبدء.',
        howBottomBtn: 'البحث بالكلمات المفتاحية',

        whyKicker: 'Nexyfab · Why.',
        whyTitle: 'معيار مختلف للربط',
        whySub: 'ليس مجرد مطابقة بسيطة، بل ربط قائم على الجدوى الفعلية والملاءمة.',
        why1Title: 'ليست طلبات عروض أسعار عشوائية',
        why1Desc: 'نختار ونقدّم فقط المرشحين المؤهلين الذين يستوفون المتطلبات، مما يقلل تكاليف التواصل.',
        why2Title: 'تصفية قائمة على البيانات',
        why2Desc: 'نأخذ بعين الاعتبار تفسير الكلمات المفتاحية والمراجع المشابهة وظروف القطاع/المعدات/العمليات.',
        why3Title: 'مبدأ سرية المشروع',
        why3Desc: 'لا تُعرض أسماء الشركات الفعلية للعملاء وتُدار فقط للتحقق الداخلي.',
        why4Title: 'قرارات أسرع',
        why4Desc: 'لا نقدّم "قائمة شركات محتملة"، بل مجموعة مختصرة من "المرشحين الأنسب للمراجعة ذات الأولوية".',
        whyCtaTitle: 'هل نبدأ المطابقة الآن؟',
        whyCtaBtn: 'استفسار عن مشروع',

        caseKicker: 'Nexyfab · Use Cases.',
        caseTitle: 'نتميّز في هذه المشاريع',
        caseSub: 'نقدّم أمثلة بناءً على <b>أنواع المشاريع</b> فقط،<br/>دون الكشف عن أسماء الشركات أو العملاء الفعليين.',
        case1Title: 'معدات الأتمتة',
        case1Desc: 'نختار شركاء الأتمتة مع مراعاة<br/>ظروف العملية/التخطيط/متطلبات السلامة.',
        case1Tag1: 'تجميع/فحص', case1Tag2: 'لوجستيات/نقل', case1Tag3: 'توسيع خط الإنتاج',
        case1Pill1: 'حالة مشابهة', case1Pill2: 'تصنيع/أتمتة',
        case2Title: 'معدات ذات أغراض خاصة',
        case2Desc: 'بما أن "جدوى التصنيع" هي المفتاح للمعدات الخاصة،<br/>نعطي الأولوية لمراجعة المراجع المماثلة.',
        case2Tag1: 'أدوات/تجهيزات', case2Tag2: 'تشغيل دقيق', case2Tag3: 'مواصفات خاصة',
        case2Pill1: 'حالة مشابهة', case2Pill2: 'معدات خاصة',
        case3Title: 'نماذج أولية للبحث والتطوير',
        case3Desc: 'بناءً على مراجع مشابهة ونطاق تقني، نختار فقط شركاء التصنيع ذوي الجدوى التنفيذية العالية.',
        case3Tag1: 'إثبات المفهوم (PoC)', case3Tag2: 'نموذج أولي', case3Tag3: 'التحقق من الأداء',
        case3Pill1: 'حالة مشابهة', case3Pill2: 'بحث وتطوير',
        case4Title: 'المنشآت/المعدات',
        case4Desc: 'بالنسبة لمعدات المنشآت، نربطكم بسرعة<br/>بناءً على التشابه والسلامة ومواعيد التسليم.',
        case4Tag1: 'التشابه', case4Tag2: 'الدقة', case4Tag3: 'السلامة/التنظيم',
        case4Pill1: 'حالة مشابهة', case4Pill2: 'منشأة',
        caseNoteTitle: 'لا تُفصح أسماء الشركات/المشاريع خارجيًا.',
        caseNoteSub: 'تُطلب المعلومات التفصيلية وفقًا لمرحلة التقدم<br/>وتُشارك فقط مع الشركاء المناسبين بعد المراجعة الداخلية.',

        reviewKicker: 'Nexyfab · Reviews.',
        reviewTitle: 'آراء العملاء',
        reviewSub: 'في "الآراء"، <b>النتائج</b> أهم من الانطباعات.<br/>جمعنا أبرز الملاحظات من العمليات الفعلية.',
        reviewKpi1Title: 'تقليص المهل الزمنية',
        reviewKpi1Desc: 'نقلّص وقت البحث عن المرشحين والتحقق منهم، مما يسرّع اتخاذ القرار.',
        reviewKpi2Title: 'توضيح المتطلبات',
        reviewKpi2Desc: 'حتى في المراحل المبكرة الغامضة، نحدد اتجاه التطوير بوضوح.',
        reviewKpi3Title: 'مطابقة مخصصة',
        reviewKpi3Desc: 'نضيّق المرشحين بناءً على مراجع مشابهة والقطاع ومستوى الصعوبة.',
        review1Tag: 'مميّز', review1Pill1: 'إثبات المفهوم', review1Pill2: 'تطوير جديد', review1Pill3: 'مهلة التسليم',
        review1Quote: 'ربطونا بسرعة بالشريك المناسب،<br/>مما مكّننا من إنجاز إثبات المفهوم في وقت قصير.',
        review1Who: 'شركة كبرى أ', review1WhoSub: 'تطوير منتجات جديدة', review1Chip: 'مؤسسة كبرى',
        review2Tag: 'البحث عن موردين', review2Pill1: 'قائم على قاعدة البيانات', review2Pill2: 'التحقق',
        review2Quote: 'بفضل قاعدة بيانات المصنّعين،<br/>اختصرنا وقت أبحاث السوق إلى النصف.',
        review2Who: 'شركة متوسطة ب', review2WhoSub: 'التوريد', review2Chip: 'متوسطة',
        review3Tag: 'استراتيجية التطوير', review3Pill1: 'خارطة الطريق',
        review3Quote: 'لم يكن مجرد ربط تصنيعي؛ بل نظّموا أولاً اتجاه التطوير ونطاقه، مما جعل تعريف المشروع واضحًا للغاية.',
        review3Who: 'شركة صغيرة ج', review3WhoSub: 'الاستراتيجية/تحسين التكاليف', review3Chip1: 'خارطة الطريق', review3Chip2: 'شركة صغيرة',
        review4Tag: 'MVP', review4Pill1: 'خفض التكاليف', review4Pill2: 'الجدول الزمني',
        review4Quote: 'انخفضت التكاليف المقدّرة بشكل ملحوظ، وبفضل معايير التواصل الواضحة،<br/>يسير التطوير بسلاسة.',
        review4Who: 'شركة ناشئة س', review4WhoSub: 'MVP · خفض التكاليف', review4Chip: 'شركة ناشئة',
        review5Tag: 'إدارة العمليات', review5Pill1: 'المتطلبات', review5Pill2: 'الجودة',
        review5Quote: 'حتى عند تغيّر المتطلبات، أعادوا ضبط المعايير<br/>وحافظوا على اتساق المخرجات النهائية.',
        review5Who: 'مصنّع د', review5WhoSub: 'التطوير · الجودة', review5Chip1: 'الاستقرار', review5Chip2: 'التصنيع',

        revenueKicker: 'Nexyfab · Revenue Model.',
        revenueTitle: 'نتحدى أدنى عمولة في القطاع بنسبة 4%، نظام المطابقة المسؤولة من Nexyfab',
        revenueSub: 'من الاستفسار إلى انطلاق التصميم والإنتاج، العمولة النهائية فقط 4~7% من عرض السعر (بدون ضريبة).',
        revenueStep1Title: 'الخطوة 1. رسوم طلب المطابقة',
        revenueStep1Price: '400 USD',
        revenueStep1Value: 'مراجعة فنية واختيار الشركاء (استرداد كامل في حال عدم النجاح)',
        revenueStep1Desc: 'نتجاوز مجرد الربط البسيط لاختيار أفضل مصنّع من خلال مراجعة فنية احترافية. في حال عدم العثور على شريك مناسب، نُعيد كامل رسوم الطلب فورًا وفق سياستنا الخالية من المخاطر.',
        revenueStep2Title: 'الخطوة 2. توقيع العقد وتسوية العمولة',
        revenueStep2Rate: 'عمولة أساسية 4~7%',
        revenueStep2Value: 'عند توقيع العقد (خصم 100% من رسوم الخطوة 1)',
        revenueStep2Desc: 'بعد المطابقة مع الشريك، تُسوَّى العمولة الأساسية (4~7%، بدون ضريبة) عند توقيع العقد. رسوم الخطوة 1 تُخصم بالكامل من المبلغ.',
        revenueStep3Title: 'الخطوة 3. انطلاق التصميم والإنتاج وإدارة التسليم',
        revenueStep3Reward: 'إدارة حتى التسليم',
        revenueStep3Value: 'دعم مخصص من التصميم حتى التسليم',
        revenueStep3Desc: 'بعد توقيع العقد، يساعد مشغل مخصص في إدارة الجداول الزمنية ومراقبة الجودة والتنسيق في حال وقوع أي مشكلات، بالتعاون مع الشريك المصنّع لضمان سير المشروع بسلاسة.',
        revenueFooterNote1: '',
        revenueFooterNote2: '',
        revenueFooterNote3: '* الحد الأدنى للعمولة هو 400 دولار أمريكي (تكلفة الخطوة 1، بدون ضريبة).',
        revenueFooterNote4: '* للاطلاع على تفاصيل سياسات العمولة والغرامات، يرجى مراجعة شروط الخدمة.',
        revenueFlow1: 'رسوم طلب 400 دولار',
        revenueFlow2: 'تسوية العمولة عند التعاقد',
        revenueFlow3: 'إدارة الانطلاق والتسليم',

        // ── New: Platform positioning ──
        platformKicker: 'NexyFab · Design to Manufacturing.',
        platformTitle: 'من التصميم إلى التصنيع،\nكل شيء في منصة واحدة',
        platformSub: 'تصميم CAD ثلاثي الأبعاد وتحليل هيكلي وتحسين طوبولوجي مباشرة في متصفحك.\nبمجرد جاهزية التصميم، احصل على عروض أسعار فورية من أكثر من 300,000 مصنع واتصل بأفضلهم.',
        platformCta1: 'بدء التصميم ثلاثي الأبعاد',
        platformCta2: 'البحث عن مصنعين',
        factories: 'تصفح المصانع',
        platformMicro: 'مجاني · بدون تسجيل · ابدأ في متصفحك',
        platformSearchPlaceholder: 'ابحث عن مصنعين الآن',
        platformSearchBtn: 'بحث',
        socialStat1: '300,000+',
        socialStat1Label: 'قاعدة بيانات المصانع',
        socialStat2: '16',
        socialStat2Label: 'مكتبة النماذج ثلاثية الأبعاد',
        socialStat3: 'مجاني',
        socialStat3Label: 'خطة مجانية متاحة',
        wf1Hint: 'CAD ثلاثي الأبعاد · 16 شكل · رسم إلى بثق',
        wf2Hint: 'تحليل FEA · تحليل اهتزازي · محاكاة حرارية',
        wf3Hint: 'تحسين طوبولوجي · فحص DFM · تخفيف الوزن',
        wf4Hint: 'رسم ثنائي الأبعاد تلقائي · تقدير التكلفة · مقارنة',
        wf5Hint: 'بحث في قاعدة البيانات · 300 ألف+ مصنع · دعم NDA',
        featTabDesign: 'تصميم',
        featTabAnalysis: 'تحليل',
        featTabMfg: 'تصنيع',
        platformBadge1: 'CAD ثلاثي الأبعاد مجاني',
        platformBadge2: 'تحليل FEA',
        platformBadge3: 'تحسين بالذكاء الاصطناعي',
        platformBadge4: 'عروض أسعار فورية',

        // ── New: Feature showcase ──
        featKicker: 'NexyFab · Capabilities.',
        featTitle: 'أدوات شاملة للمهندسين',
        featSub: 'صمم وحلل وحسّن واحصل على عروض أسعار — ميزات بمستوى SolidWorks مجانًا في متصفحك.',
        feat1Title: 'CAD ثلاثي الأبعاد بارامتري',
        feat1Desc: '16 شكلًا، من الرسم إلى البثق، تقريب الحواف، الأنماط والميزات الاحترافية.',
        feat2Title: 'التحليل الهيكلي (FEA)',
        feat2Desc: 'محاكاة الإجهاد والإزاحة ومعاملات الأمان للتحقق من التصميم.',
        feat3Title: 'تحسين الطوبولوجيا',
        feat3Desc: 'خوارزمية SIMP تولد هياكل مثالية، تقلل المواد بنسبة تصل إلى 40%.',
        feat4Title: 'تحليل الاهتزاز والحراري',
        feat4Desc: 'تحليل التردد الطبيعي ومحاكاة نقل الحرارة للاستقرار الديناميكي.',
        feat5Title: 'تحليل DFM',
        feat5Desc: 'فحص تلقائي لقابلية التصنيع — كشف مبكر لمشاكل السماكة والتفاوتات.',
        feat6Title: 'رسومات وعروض أسعار تلقائية',
        feat6Desc: 'إنشاء رسومات ثنائية الأبعاد وتقديرات التكلفة ومطابقة المصنعين بنقرة واحدة.',

        // ── New: Workflow ──
        wfKicker: 'NexyFab · Workflow.',
        wfTitle: 'من التصميم إلى التصنيع في 5 خطوات',
        wfSub: 'من الفكرة إلى القطع الحقيقية — كل شيء في منصة واحدة.',
        wf1Title: 'تصميم',
        wf1Desc: 'نمذجة ثلاثية الأبعاد بارامترية في متصفحك',
        wf2Title: 'تحليل',
        wf2Desc: 'التحقق عبر FEA والتحليل الحراري والاهتزازي',
        wf3Title: 'تحسين',
        wf3Desc: 'تحسين الطوبولوجيا وفحص DFM',
        wf4Title: 'عرض سعر',
        wf4Desc: 'تقدير فوري للتكلفة ومقارنة المصنعين',
        wf5Title: 'تصنيع',
        wf5Desc: 'بحث في قاعدة البيانات للتواصل مع أفضل مصنع',

        // ── New: Persona cards ──
        personaKicker: 'NexyFab · For You.',
        personaTitle: 'لمن هذه المنصة؟',
        persona1Title: 'مهندسو التصميم',
        persona1Desc: 'CAD وFEA احترافي بدون SolidWorks. صمم مباشرة في متصفحك.',
        persona1Cta: 'بدء التصميم ثلاثي الأبعاد',
        persona2Title: 'مديرو المشتريات',
        persona2Desc: 'ارفع الرسومات ← مقارنة فورية لعروض الأسعار. مصنعون موثقون فقط.',
        persona2Cta: 'طلب عرض سعر',
        persona3Title: 'الشركات الناشئة',
        persona3Desc: 'حوّل الأفكار إلى نماذج أولية. CAD مجاني + عروض أسعار للإنتاج الصغير.',
        persona3Cta: 'ابدأ مجانًا',

        ctaKicker: 'Nexyfab · Get Started.',
        ctaTitle: 'هل نبدأ مشروعكم الآن؟',
        ctaSub: 'سطر واحد من الكلمات المفتاحية يكفي.<br/>بعد المراجعة الداخلية، سنربطكم بالشريك الأنسب.',
        ctaBtn1: 'استفسار عن مشروع',
        ctaBtn2: 'البحث بالكلمات المفتاحية',

        // ── Onboarding overlay ──
        onboardingTitle: 'ماذا تريد أن تفعل؟',
        onboardingSub: 'سنوجهك إلى المكان المناسب.',
        onboardingPath1: 'بدء التصميم ثلاثي الأبعاد',
        onboardingPath1Desc: 'تصميم CAD والتحليل والتحسين في المتصفح',
        onboardingPath2: 'استفسار التصنيع',
        onboardingPath2Desc: 'تحميل الرسومات · مقارنة العروض · مطابقة المصنعين',
        onboardingPath3: 'البحث عن شركاء',
        onboardingPath3Desc: 'ابحث عن أفضل المصنعين بالكلمات المفتاحية',
        onboardingSkip: 'تخطي',
        howPage: {
            heroTitle: 'How we Work',
            heroSub: 'من البحث إلى الربط — انطلقوا من التصميم إلى الإنتاج الضخم<br/>بالاعتماد على قائمة شركاء موثقة وبيانات مطابقة موضوعية.',
            step1Tag: 'الخطوة 1',
            step1Title: 'التحليل الذكي بالذكاء الاصطناعي (Smart Analysis)',
            step1Desc: 'بناءً على الكلمات المفتاحية للمشروع، ننظّم هيكل العمليات والنطاق التقني المطلوب من منظور التصنيع. تُحدد معايير التحليل للمطابقة في هذه المرحلة.<br/><br/><strong style="color:#0b5cff;">[المدخلات] الكلمات المفتاحية للمشروع ← [المخرجات] معايير المطابقة والنطاق التقني</strong>',
            step2Tag: 'الخطوة 2',
            step2Title: 'المطابقة مع قاعدة البيانات العالمية (Global DB Matching)',
            step2Desc: 'استنادًا إلى قواعد بيانات التصنيع في كوريا والصين، نحلل بشمولية المعدات والمراجع المشابهة وملاءمة العمليات لتحديد أولوية الشركاء المرشحين.<br/><br/><strong style="color:#0b5cff;">[المدخلات] معايير التحليل ← [المخرجات] 3–5 مرشحين مناسبين مع مبررات التوصية</strong>',
            step3Tag: 'الخطوة 3',
            step3Title: 'الربط ودعم التعاون (Connection & Support)',
            step3Desc: 'بعد التحقق من سجل الأداء ومعلومات القدرات للشركاء المختارين، ندعم عملية الاستفسار وعروض الأسعار والطلبات عبر المنصة.<br/><br/><strong style="color:#0b5cff;">[المدخلات] اختيار المرشح ← [المخرجات] دعم اتفاقية عدم الإفصاح وتقدّم التعاون</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* معايير الاختيار: مراجع مشابهة / معدات / شهادات الجودة</span>',
            whyTitle: 'لماذا Nexyfab؟',
            why1Title: 'أساس قائم على البيانات',
            why1Desc: 'نوفر بيانات موضوعية كأساس للتوصية، استنادًا إلى المعدات وسجل المشاريع المشابهة ونطاق العمليات، وليس مجرد نتائج بحث.',
            diagramTitle: 'سير عمل التصنيع كوريا-الصين',
            diagramStep1: 'التحليل الذكي بالذكاء الاصطناعي',
            diagramStep1Sub: 'ملخص المواصفات',
            diagramStep2: 'المطابقة مع قاعدة البيانات العالمية',
            diagramStep2Sub: 'أفضل 3–5 مصانع',
            diagramStep3: 'ربط موثّق',
            diagramStep3Sub: 'تقديم + دعم NDA',
            why2Title: 'قاعدة بيانات تصنيع متكاملة كوريا-الصين',
            why2Desc: 'بناءً على قاعدة بيانات متكاملة للبنية التحتية التصنيعية في كوريا والصين، نوفر مطابقة قائمة على الفهم التقني. قوتنا تكمن في ربط يعكس منظور التطوير، وليس مجرد وساطة بسيطة.',
            why3Title: 'معلومات معايير الجودة (Q/C)',
            why3Desc: 'نوفر معلومات عن معدات الشريك وشهادات الجودة وسجل الأداء كمعايير مراجعة أولية.<br/>*ملاحظة: المسؤولية النهائية عن جودة الإنتاج غير المُدارة عبر Nexyfab تقع على عاتق الأطراف المتعاقدة.',
            why4Title: 'الأمان واتفاقية عدم الإفصاح (NDA)',
            why4Desc: 'ندعم إجراءات توقيع اتفاقية عدم الإفصاح داخل المنصة، وتُشارك معلومات المشروع فقط ضمن نطاق المراجعة الداخلية.',
            statsTitle: 'حل تحديات التصنيع بالبيانات',
            statsSub: 'نضمن مطابقة مثالية من خلال قاعدة بياناتنا التصنيعية المتكاملة لكوريا والصين والمراجع المتراكمة.',
            statsFactories: '300,000+',
            statsFactoriesLabel: 'قاعدة بيانات المصانع',
            statsRefs: '10,000+',
            statsRefsLabel: 'مراجع مشاريع شركاء موثقة',
            casePrompt: 'اكتشفوا كيف تمت مطابقة أنظمة إدارة البطاريات (BMS) أو أجهزة خوادم الذكاء الاصطناعي.',
            caseBtn: 'عرض حالات المطابقة',
            ssTitle: 'قصص النجاح (Success Stories)',
            ssRef1: 'المطابقة المثلى لنظام إدارة البطاريات (BMS)',
            ssRef2: 'تطوير أجهزة خوادم الذكاء الاصطناعي'
        }
    }
};
