/**
 * SVG export for sketch entities.
 *
 * Phase 1 of the sketch-export pipeline: produce a self-contained SVG
 * document that downstream CAD tools (Inkscape, LibreCAD, Fusion 360 via
 * SVG import, etc.) can read. DXF (the real CAD interchange format) is
 * a Phase 2 wishlist item — DXF's record structure is materially more
 * complex (group codes, BLOCK/TABLES sections, layer state) and warrants
 * its own module rather than being shoehorned alongside this one.
 *
 * Coordinate system:
 *   Sketch space (solver) uses +Y up, mathematician-style. SVG uses +Y
 *   down. We could flip every coordinate up-front, but that would force
 *   the bbox/viewBox computation to track flipped values too. Instead we
 *   compute the bbox in sketch space and emit a single
 *   `transform="translate(...) scale(1, -1)"` wrapper so the *content*
 *   is rendered upright while the viewBox stays a simple top-left
 *   rectangle. (Standard SVG-from-math idiom; see e.g. tikz2svg.)
 *
 * Arc encoding:
 *   SVG `<path d="...A">` is the only arc primitive; we encode each arc
 *   as `M x0 y0  A r r 0 large sweep x1 y1`. With `startAngle` / `endAngle`
 *   as the solver gives them:
 *     x0 = cx + r * cos(startAngle)
 *     y0 = cy + r * sin(startAngle)
 *     x1 = cx + r * cos(endAngle)
 *     y1 = cy + r * sin(endAngle)
 *   `large-arc-flag = (|delta| > pi) ? 1 : 0` where delta is the unwrapped
 *   sweep `endAngle - startAngle`. Because the entire content is wrapped
 *   in a scale(1,-1) Y-flip, *sweep direction also flips*: a CCW arc in
 *   sketch space is CW in SVG screen space. We compensate by setting
 *   `sweep-flag = (delta > 0) ? 0 : 1` (inverted from the usual choice).
 *
 * Units:
 *   Width/height are emitted in mm so the document opens at true scale
 *   in CAD tools that respect the unit attribute. The viewBox stays
 *   unit-less and matches the bbox 1:1 — caller-supplied document
 *   dimensions only set the rendered page size.
 *
 * No-op safety:
 *   Empty entity set still produces a valid SVG document (just with no
 *   content elements). Callers can chain export → download without
 *   special-casing the empty sketch.
 */

export interface SketchSvgOptions {
  /** Document dimensions in mm. */
  width: number;
  height: number;
  /** Margin around content (mm). Defaults to 10. */
  margin?: number;
  /** Stroke width (mm). Defaults to 0.25 (typical CAD line weight). */
  strokeWidth?: number;
  /** <title> metadata. */
  title?: string;
  /** Render a faint background grid. Defaults to false. */
  showGrid?: boolean;
  /** Render dimension annotations (Phase 2 placeholder; currently no-op). */
  showDimensions?: boolean;
}

export interface SvgPoint {
  id: string;
  x: number;
  y: number;
  isFixed?: boolean;
}

export interface SvgLine {
  id: string;
  p1: string;
  p2: string;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export interface SvgCircle {
  id: string;
  cx: number;
  cy: number;
  radius: number;
}

export interface SvgArc {
  id: string;
  cx: number;
  cy: number;
  radius: number;
  /** Radians. */
  startAngle: number;
  /** Radians. */
  endAngle: number;
}

export interface SketchEntities {
  points: ReadonlyArray<SvgPoint>;
  lines: ReadonlyArray<SvgLine>;
  circles: ReadonlyArray<SvgCircle>;
  arcs: ReadonlyArray<SvgArc>;
}

interface BBox {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

const GENERATOR = 'NexyFab sketchSvgExport v1';

// ─── public API ──────────────────────────────────────────────────────────

/**
 * Serialize the supplied entities to an SVG document string.
 *
 * The document is self-contained (no external CSS, no scripts) and uses
 * mm units so CAD-grade tools open it at true scale.
 */
export function exportSketchToSvg(
  entities: SketchEntities,
  opts: SketchSvgOptions,
): string {
  const margin = opts.margin ?? 10;
  const strokeWidth = opts.strokeWidth ?? 0.25;
  const title = opts.title ?? 'NexyFab Sketch';

  const bbox = computeBBox(entities, margin);
  // viewBox covers the bbox 1:1 in sketch-space units. The Y-flip wrapper
  // converts +Y-up math coords to +Y-down screen coords without distorting
  // the viewBox math.
  const vbW = bbox.maxX - bbox.minX;
  const vbH = bbox.maxY - bbox.minY;
  const viewBox = `${fmt(bbox.minX)} ${fmt(bbox.minY)} ${fmt(vbW)} ${fmt(vbH)}`;

  const widthAttr = `${fmt(opts.width)}mm`;
  const heightAttr = `${fmt(opts.height)}mm`;

  const parts: string[] = [];
  parts.push(`<?xml version="1.0" encoding="UTF-8" standalone="no"?>`);
  parts.push(
    `<svg xmlns="http://www.w3.org/2000/svg" version="1.1" ` +
      `width="${widthAttr}" height="${heightAttr}" ` +
      `viewBox="${viewBox}">`,
  );
  parts.push(`<title>${escapeXml(title)}</title>`);
  parts.push(
    `<desc>Generated by ${escapeXml(GENERATOR)}. ` +
      `Sketch in mm; +Y up flipped to SVG +Y down via scale(1,-1).</desc>`,
  );
  parts.push(`<metadata>generator=${escapeXml(GENERATOR)}</metadata>`);

  // Y-flip wrapper. We translate by (minX + maxX, minY + maxY) before
  // scaling by (1, -1) so that the original bbox maps onto the same
  // viewBox rectangle after the flip. Concretely: a point (x, y) becomes
  // (x, (minY+maxY) - y), which preserves x and reflects y about the
  // bbox vertical center.
  const tx = 0;
  const ty = bbox.minY + bbox.maxY;
  parts.push(`<g transform="translate(${fmt(tx)} ${fmt(ty)}) scale(1 -1)">`);

  if (opts.showGrid) {
    parts.push(renderGrid(bbox));
  }

  // Entities — emit in stable order so two equal inputs serialize byte-equal:
  // circles → arcs → lines → points. Points last so they sit on top.
  for (const c of entities.circles) {
    parts.push(renderCircle(c, strokeWidth));
  }
  for (const a of entities.arcs) {
    parts.push(renderArc(a, strokeWidth));
  }
  for (const ln of entities.lines) {
    parts.push(renderLine(ln, strokeWidth));
  }
  for (const p of entities.points) {
    parts.push(renderPoint(p, strokeWidth));
  }

  parts.push(`</g>`);
  parts.push(`</svg>`);
  return parts.join('\n');
}

/**
 * Trigger a download of the supplied sketch as an SVG file. Browser-only —
 * relies on `URL.createObjectURL` and a transient `<a>` element click.
 *
 * Throws if invoked outside a DOM (e.g., bare Node) so callers fail loudly
 * instead of silently no-op'ing.
 */
export function downloadSketchAsSvg(
  entities: SketchEntities,
  filename: string,
  opts: SketchSvgOptions,
): void {
  if (typeof window === 'undefined' || typeof document === 'undefined') {
    throw new Error('downloadSketchAsSvg: requires a browser (window/document)');
  }
  if (typeof URL === 'undefined' || typeof URL.createObjectURL !== 'function') {
    throw new Error('downloadSketchAsSvg: URL.createObjectURL unavailable');
  }
  const svg = exportSketchToSvg(entities, opts);
  const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.svg') ? filename : `${filename}.svg`;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Defer revoke a tick so Safari/Firefox have time to start the download.
  setTimeout(() => {
    try {
      URL.revokeObjectURL(url);
    } catch {
      // best-effort cleanup
    }
  }, 0);
}

// ─── internals ───────────────────────────────────────────────────────────

/**
 * Compute the bounding box of all entities in sketch space, padded by
 * `margin`. When the input is empty we fall back to a small default box
 * centered on the origin so the resulting SVG is still well-formed.
 */
function computeBBox(entities: SketchEntities, margin: number): BBox {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  const expand = (x: number, y: number): void => {
    if (x < minX) minX = x;
    if (y < minY) minY = y;
    if (x > maxX) maxX = x;
    if (y > maxY) maxY = y;
  };

  for (const p of entities.points) expand(p.x, p.y);
  for (const ln of entities.lines) {
    expand(ln.x1, ln.y1);
    expand(ln.x2, ln.y2);
  }
  for (const c of entities.circles) {
    expand(c.cx - c.radius, c.cy - c.radius);
    expand(c.cx + c.radius, c.cy + c.radius);
  }
  for (const a of entities.arcs) {
    // Conservative: use the full bounding circle rather than the actual
    // arc extents. Slightly wasteful but never clips the arc.
    expand(a.cx - a.radius, a.cy - a.radius);
    expand(a.cx + a.radius, a.cy + a.radius);
  }

  if (!Number.isFinite(minX)) {
    // Empty sketch — synthesize a sensible default box around origin.
    minX = -10;
    minY = -10;
    maxX = 10;
    maxY = 10;
  }

  return {
    minX: minX - margin,
    minY: minY - margin,
    maxX: maxX + margin,
    maxY: maxY + margin,
  };
}

function renderPoint(p: SvgPoint, strokeWidth: number): string {
  // r scales with strokeWidth so points stay visible at any zoom but never
  // dwarf the geometry. The 1mm spec is the minimum size at small sketches.
  const r = Math.max(1, strokeWidth * 3);
  const fill = p.isFixed ? 'red' : 'black';
  return (
    `<circle data-sketch-id="${escapeXml(p.id)}" data-kind="point" ` +
    `cx="${fmt(p.x)}" cy="${fmt(p.y)}" r="${fmt(r)}" fill="${fill}" />`
  );
}

function renderLine(ln: SvgLine, strokeWidth: number): string {
  return (
    `<line data-sketch-id="${escapeXml(ln.id)}" data-kind="line" ` +
    `x1="${fmt(ln.x1)}" y1="${fmt(ln.y1)}" ` +
    `x2="${fmt(ln.x2)}" y2="${fmt(ln.y2)}" ` +
    `stroke="black" stroke-width="${fmt(strokeWidth)}" stroke-linecap="round" />`
  );
}

function renderCircle(c: SvgCircle, strokeWidth: number): string {
  return (
    `<circle data-sketch-id="${escapeXml(c.id)}" data-kind="circle" ` +
    `cx="${fmt(c.cx)}" cy="${fmt(c.cy)}" r="${fmt(c.radius)}" ` +
    `fill="none" stroke="black" stroke-width="${fmt(strokeWidth)}" />`
  );
}

/**
 * Render an arc as an SVG path. See module-level comment for the math.
 */
function renderArc(a: SvgArc, strokeWidth: number): string {
  const { cx, cy, radius, startAngle, endAngle } = a;
  const x0 = cx + radius * Math.cos(startAngle);
  const y0 = cy + radius * Math.sin(startAngle);
  const x1 = cx + radius * Math.cos(endAngle);
  const y1 = cy + radius * Math.sin(endAngle);

  // Unwrapped sweep delta. We keep the sign so we can pick sweep-flag.
  const delta = endAngle - startAngle;
  const absDelta = Math.abs(delta);
  const largeArc = absDelta > Math.PI ? 1 : 0;
  // Sketch space is +Y up; inside the scale(1,-1) wrapper a CCW arc
  // (positive delta) reads as CW on screen, so the SVG sweep-flag we
  // emit is the INVERSE of the standard choice. CCW delta>0 → sweep=0.
  const sweep = delta > 0 ? 0 : 1;

  const d =
    `M ${fmt(x0)} ${fmt(y0)} ` +
    `A ${fmt(radius)} ${fmt(radius)} 0 ${largeArc} ${sweep} ${fmt(x1)} ${fmt(y1)}`;

  return (
    `<path data-sketch-id="${escapeXml(a.id)}" data-kind="arc" ` +
    `d="${d}" fill="none" stroke="black" stroke-width="${fmt(strokeWidth)}" />`
  );
}

/**
 * Faint major/minor grid lines inside the bbox. Spacing auto-picks
 * between 1/5/10/50/100 mm depending on the bbox size so the grid stays
 * legible at any scale.
 */
function renderGrid(bbox: BBox): string {
  const w = bbox.maxX - bbox.minX;
  const h = bbox.maxY - bbox.minY;
  const span = Math.max(w, h);
  // Aim for ~20 minor divisions across the larger axis.
  const candidates = [1, 5, 10, 50, 100, 500];
  let step = 10;
  for (const c of candidates) {
    if (span / c <= 50) {
      step = c;
      break;
    }
  }
  const parts: string[] = [`<g data-kind="grid" stroke="#e5e5ea" stroke-width="0.1" fill="none">`];
  const startX = Math.floor(bbox.minX / step) * step;
  const startY = Math.floor(bbox.minY / step) * step;
  for (let x = startX; x <= bbox.maxX; x += step) {
    parts.push(
      `<line x1="${fmt(x)}" y1="${fmt(bbox.minY)}" x2="${fmt(x)}" y2="${fmt(bbox.maxY)}" />`,
    );
  }
  for (let y = startY; y <= bbox.maxY; y += step) {
    parts.push(
      `<line x1="${fmt(bbox.minX)}" y1="${fmt(y)}" x2="${fmt(bbox.maxX)}" y2="${fmt(y)}" />`,
    );
  }
  parts.push(`</g>`);
  return parts.join('\n');
}

/**
 * Format a number with up to 6 decimals, dropping trailing zeros. Keeps
 * the SVG compact and avoids `1.2000000004` artefacts from FP arithmetic.
 */
function fmt(n: number): string {
  if (!Number.isFinite(n)) return '0';
  // Round to 6 decimals to keep diffs stable.
  const rounded = Math.round(n * 1_000_000) / 1_000_000;
  // Avoid `-0` showing up in the output (cosmetic).
  const safe = Object.is(rounded, -0) ? 0 : rounded;
  return String(safe);
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
