export const cn = {
    heroKicker: 'Nexyfab · 查找制造商.',
    heroTitle: '寻找您的理想<br/>开发合作伙伴',
    heroSub: '输入产品关键词<br/>在已验证韩中工厂数据库中搜索相关制造商。',
    searchPlaceholder: '例：电池自动化设备',
    placeholderList: ['电池自动化设备', '食品生产设备', '精密零件加工', '物流输送系统', '半导体清洗设备'],
    ssTitle: '使用场景',
    ssRef1: '精密加工零件 (CNC · 钣金) 匹配',
    ssRef2: '小批量多品种样品制作',
    searchBtn: '搜索',
    searching: '搜索中...',
    searchingSub: '（约30秒内）',
    manufacturer: '制造商',
    industry: '行业',
    score: '匹配度',
    contactTitle: '📨 输入联系信息',
    contactCompany: '姓名（公司名称）',
    contactPhone: '电话号码',
    contactEmail: '电子邮箱',
    contactSubmit: '咨询',
    tabKoFactories: '韩国工厂',
    tabCnFactories: '中国工厂',
    noKoResults: '未找到韩国工厂。',
    noCnResults: '未找到中国工厂。',
    applyDashboard: '通过控制台申请',
    loginApply: '登录并申请',
    applyDesc: 'AI自动RFP · 报价比较 · 专属支持',
    gotoDashboard: '前往控制台 →',
    signIn: '登录 →',
    orDirectContact: '或直接联系我们',
    statCount: '30万+',
    formSubmitting: '处理中...',
    alertSuccess: '您的咨询已成功提交。',
    alertError: '发生错误，请稍后再试。',
    totalResults: '全',
    contactGuide: '* 姓名（公司名称）、电话和邮箱是必填项。',
    statKr: '韩国/中国工厂',
    statRef: '入驻企业累计案例',
    heroNote: '* 实际公司名称不会向客户显示，<br/>提交咨询时仅用于内部验证。',

    howKicker: 'Nexyfab · How it Works.',
    howTitle: '从关键词到成功对接',
    howSub: '搜索 → 分析 → 筛选 → 对接 → 实际项目推进',
    step1Title: '需求输入',
    step1Desc: '将需求作为关键词输入以生成分析标准。',
    step1Tag1: '电池自动化设备', step1Tag2: '专用设备', step1Tag3: '工艺改进',
    step2Title: 'DB搜索',
    step2Desc: '根据关键词，从韩中工厂数据库中搜索相关制造商。',
    step2List1: '语义扩展 (同义词/相似分类)',
    step2List2: '根据类似案例计算适合度',
    step2List3: '按行业/设备/工艺条件过滤',
    step3Title: '挑选合适的合作伙伴',
    step3Desc: '我们将候选对象从"可选"缩小为"最适合"的首选候选人。',
    step3List1: '技术难度/领域匹配',
    step3List2: '反映执行范围和可靠性',
    step3List3: '排除重复/不适合的候选对象',
    step4Title: '咨询对接',
    step4Desc: '项目信息不会对外公开，在内部评估后连接到必要范围。',
    step4Note: '* 实际公司名称不会向客户显示，仅传递以供内部审查。',
    howBottomTitle: '从关键词搜索开始。',
    howBottomSub: '只需简短关键词即可启动。',
    howBottomBtn: '关键词搜索',

    whyKicker: 'Nexyfab · Why.',
    whyTitle: '不同的"对接"标准',
    whySub: '不仅仅是简单的匹配，而是基于实际可行性和适合性的匹配。',
    why1Title: '拒绝盲目报价',
    why1Desc: '只筛选和传递符合要求的合格候选人，从而降低沟通成本。',
    why2Title: '基于数据的过滤',
    why2Desc: '不仅反映关键词解读，还综合考虑相似案例及行业/设备/工艺条件。',
    why3Title: '项目信息保密原则',
    why3Desc: '实际公司名称不会向客户披露，仅由内部管理部门查看。',
    why4Title: '加速决策进程',
    why4Desc: '不提供"可能的公司列表"，而是压缩为"优先审查的合适候选对象"群组。',
    whyCtaTitle: '我们要现在开始匹配吗？',
    whyCtaBtn: '项目咨询',

    caseKicker: 'Nexyfab · Use Cases.',
    caseTitle: '在这些项目中我们很有优势',
    caseSub: '我们在不披露实际公司/客户名称的情况下，<br/>仅根据<b>项目类型</b>提供示例。',
    case1Title: '自动化设备',
    case1Desc: '我们通过反映工艺条件/布局/安全要求来筛选<br/>最佳的自动化合作伙伴。',
    case1Tag1: '装配/检查', case1Tag2: '物流/转移', case1Tag3: '产线扩建',
    case1Pill1: '相似案例', case1Pill2: '制造/自动化',
    case2Title: '专用设备',
    case2Desc: '由于"制造可行性"是专用设备的关键，<br/>我们会优先审查类似案例。',
    case2Tag1: '工装/夹具', case2Tag2: '精密驱动', case2Tag3: '特殊规格',
    case2Pill1: '相似案例', case2Pill2: '专用设备',
    case3Title: '研发原型',
    case3Desc: '基于类似案例和技术范围，仅筛选出实现可能性高的制造合作伙伴。',
    case3Tag1: '概念验证 (PoC)', case3Tag2: '原型件', case3Tag3: '性能验证',
    case3Pill1: '相似案例', case3Pill2: '研发 (R&D)',
    case4Title: '工厂/设备',
    case4Desc: '对于大型厂房设备，我们将根据相似性、<br/>安全性和交期快速完成对接。',
    case4Tag1: '相似性', case4Tag2: '精度', case4Tag3: '安全/合规',
    case4Pill1: '相似案例', case4Pill2: '工厂',
    caseNoteTitle: '企业/项目名称不对外公开。',
    caseNoteSub: '详细信息会根据项目进度被要求提供，<br/>并在内部审核后仅与适合的合作伙伴共享。',

    reviewKicker: 'Nexyfab · Reviews.',
    reviewTitle: '客户评价',
    reviewSub: '在"评价"中，<b>结果</b>比感受更重要。<br/>我们梳理了实际流程中最常见的反馈。',
    reviewKpi1Title: '缩短交货时间',
    reviewKpi1Desc: '减少了发现/验证候选人的时间，并加快了决策速度。',
    reviewKpi2Title: '梳理需求',
    reviewKpi2Desc: '即使在模糊的早期阶段，开发方向也已明确确立。',
    reviewKpi3Title: '定制化匹配',
    reviewKpi3Desc: '根据相似参考文献/行业/难度压缩候选人。',
    review1Tag: 'Featured', review1Pill1: '概念验证(PoC)', review1Pill2: '新开发', review1Pill3: '交货时间',
    review1Quote: '他们迅速为我们对接到了合适的合作伙伴，<br/>帮助我们在短时间内成功完成了PoC。',
    review1Who: '大型企业 A', review1WhoSub: '新产品开发', review1Chip: '企业',
    review2Tag: '供应商采购', review2Pill1: '基于数据库', review2Pill2: '认证',
    review2Quote: '得益于制造商数据库，我们在市场调查上<br/>耗费的时间减少了一半。',
    review2Who: '中型企业 B', review2WhoSub: '采购', review2Chip: '中型',
    review3Tag: '开发战略', review3Pill1: '路线图',
    review3Quote: '不仅仅是简单的制作对接，而是先梳理了开发方向和范围，使项目定义变得更加清晰。',
    review3Who: '中小企业 C', review3WhoSub: '战略/成本优化', review3Chip1: '路线图', review3Chip2: '中小企业',
    review4Tag: 'MVP', review4Pill1: '降低成本', review4Pill2: '时间表',
    review4Quote: '预估成本大幅下降，并且因为沟通标准清晰，<br/>开发进行得非常顺利。',
    review4Who: '初创公司 S', review4WhoSub: 'MVP · 降低成本', review4Chip: '初创公司',
    review5Tag: '过程管理', review5Pill1: '要求', review5Pill2: '质量',
    review5Quote: '即使需求发生变化，他们也会重新调整标准，<br/>以确保最终产出的一致性。',
    review5Who: '制造商 D', review5WhoSub: '开发 · 品质', review5Chip1: '稳定性', review5Chip2: '制造',

    revenueKicker: 'Nexyfab · Revenue Model.',
    revenueTitle: '挑战行业最低佣金4%, Nexyfab"责任匹配"系统',
    revenueSub: '从咨询到设计·量产启动，最终佣金仅为报价的4~7%（不含税）。',
    revenueStep1Title: 'Step 1. 匹配申请费',
    revenueStep1Price: '3,000 CNY（不含税）',
    revenueStep1Value: '技术审查与合作伙伴筛选 (失败时全额退款)',
    revenueStep1Desc: '超越简单的连接，通过专业的技术审查筛选最适合的制造商。如未能找到合适的合作伙伴，我们将立即全额退还申请费，实行无风险政策。',
    revenueStep2Title: 'Step 2. 合同签署与费用结算',
    revenueStep2Rate: '基础佣金 4~7%',
    revenueStep2Value: '签署合同时 (Step 1 费用 100% 抵扣)',
    revenueStep2Desc: '与合作伙伴匹配后，签约时结算基础佣金（4~7%，不含税）。Step 1 申请费将100%从佣金中抵扣。',
    revenueStep3Title: 'Step 3. 设计·量产启动及交付管理',
    revenueStep3Reward: '交付完成前全程管理',
    revenueStep3Value: '从设计到交付，专属运营人员全程陪同支持',
    revenueStep3Desc: '合同签署后，从设计启动到交付完成，专属运营人员将协助进行进度管理、质量确认及问题协调，与合作伙伴携手确保项目顺利推进。',
    revenueFooterNote1: '',
    revenueFooterNote2: '',
    revenueFooterNote3: '* 最低佣金设定为 3,000 CNY（Step 1 费用，不含税）。',
    revenueFooterNote4: '* 有关费用及违约金的详细政策，请参阅服务条款。',
    revenueFlow1: '3,000 CNY 申请费',
    revenueFlow2: '签约时 费用结算',
    revenueFlow3: '设计·量产启动及交付管理',

    platformKicker: 'NexyFab · Design to Manufacturing.',
    platformTitle: '从设计到制造，\n一个平台搞定',
    platformSub: '在浏览器中进行3D CAD设计、结构分析和拓扑优化。\n设计完成后，从30万+工厂数据库立即获取报价并连接最佳制造商。',
    platformCta1: '开始3D设计',
    platformCta2: '寻找制造商',
    factories: '浏览工厂',
    platformMicro: '免费 · 无需注册 · 浏览器直接开始',
    platformDemoMigrate: '💾 注册前的工作将在创建账户时自动迁移',
    platformSearchPlaceholder: '立即搜索制造商',
    platformSearchBtn: '搜索',
    socialStat1: '300,000+',
    socialStat1Label: '韩中工厂数据库',
    socialStat2: '16种',
    socialStat2Label: '3D形状库',
    socialStat3: '免费',
    socialStat3Label: '免费基础计划',
    wf1Hint: '参数化3D CAD · 16种形状 · 草图到拉伸',
    wf2Hint: 'FEA结构分析 · 模态分析 · 热传导仿真',
    wf3Hint: 'SIMP拓扑优化 · DFM检查 · 轻量化',
    wf4Hint: '自动2D图纸 · 成本估算 · 制造商比较',
    wf5Hint: '工厂DB搜索 · 30万+工厂DB · 匿名匹配',
    featTabDesign: '设计',
    featTabAnalysis: '分析',
    featTabMfg: '制造',
    platformBadge1: '免费3D CAD',
    platformBadge2: 'FEA分析',
    platformBadge3: 'AI优化',
    platformBadge4: '即时报价',

    featKicker: 'NexyFab · Capabilities.',
    featTitle: '工程师的一站式工具',
    featSub: '设计、分析、优化、报价 — SolidWorks级功能，浏览器中免费使用。',
    feat1Title: '参数化3D CAD',
    feat1Desc: '16种形状、草图到拉伸、倒角、圆角、阵列等专业功能。',
    feat2Title: '结构分析（FEA）',
    feat2Desc: '模拟应力、位移和安全系数，验证您的设计。',
    feat3Title: '拓扑优化',
    feat3Desc: 'SIMP算法生成最优结构，在保持强度的同时减少最多40%的材料。',
    feat4Title: '模态与热分析',
    feat4Desc: '固有频率分析和热传导仿真，确认动态/热稳定性。',
    feat5Title: 'DFM分析',
    feat5Desc: '自动分析可制造性 — 壁厚、孔径、脱模角度、圆角半径、长宽比 自动检查。',
    feat6Title: '自动图纸与报价',
    feat6Desc: '一键自动生成2D图纸、成本估算和制造商匹配。',

    wfKicker: 'NexyFab · Workflow.',
    wfTitle: '从设计到制造5个步骤',
    wfSub: '从创意到实际零件 — 全部在一个平台完成。',
    wf1Title: '设计',
    wf1Desc: '在浏览器中进行参数化3D建模',
    wf2Title: '分析',
    wf2Desc: '通过FEA、热分析、模态分析验证',
    wf3Title: '优化',
    wf3Desc: '拓扑优化和DFM检查',
    wf4Title: '报价',
    wf4Desc: '即时成本估算和制造商比较',
    wf5Title: '制造',
    wf5Desc: '工厂DB搜索连接最佳制造商',

    personaKicker: 'NexyFab · For You.',
    personaTitle: '这个平台适合谁？',
    persona1Title: '设计工程师',
    persona1Desc: '无需SolidWorks的专业设计和分析。直接在浏览器中工作。',
    persona1Cta: '开始3D设计',
    persona2Title: '采购经理',
    persona2Desc: '上传图纸→即时报价比较。仅推荐经过验证的制造商。',
    persona2Cta: '请求报价',
    persona3Title: '创业公司',
    persona3Desc: '将创意变为原型。免费CAD + 小批量报价，一站式搞定。',
    persona3Cta: '免费开始',

    ctaKicker: 'Nexyfab · Get Started.',
    ctaTitle: '我们现在开始您的项目吗？',
    ctaSub: '只需一行简短的关键词即可。<br/>内部审核后，我们将为您对接最合适的合作伙伴。',
    ctaBtn1: '项目咨询',
    ctaBtn2: '关键词搜索',

    onboardingTitle: '您想做什么？',
    onboardingSub: '我们将引导您到合适的页面。',
    onboardingPath1: '开始3D设计',
    onboardingPath1Desc: '在浏览器中进行CAD设计·分析·优化',
    onboardingPath2: '制造咨询',
    onboardingPath2Desc: '上传图纸·比较报价·匹配制造商',
    onboardingPath3: '查找合作伙伴',
    onboardingPath3Desc: '通过关键词搜索最佳制造商',
    onboardingSkip: '跳过',
    howPage: {
        heroTitle: 'How we Work',
        heroSub: '从搜索到对接，基于验证合作伙伴候选名单与<br/>客观数据，完成从设计到量产的全流程。',
        step1Tag: 'Step 1',
        step1Title: 'AI精准分析 (Smart Analysis)',
        step1Desc: '基于项目关键词，从制造角度梳理所需的工艺结构和技术范围。对接所需的分析标准在此阶段定义。<br/><br/><strong style="color:#0b5cff;">[Input] 项目关键词 → [Output] 推导匹配标准及技术范围</strong>',
        step2Tag: 'Step 2',
        step2Title: '全球匹配 (Global DB Matching)',
        step2Desc: '基于中韩制造数据库，综合分析现有设备、类似案例、工艺匹配度，筛选出优先考虑的合作伙伴。<br/><br/><strong style="color:#0b5cff;">[Input] 分析标准 → [Output] 3–5家合适候选及推荐理由</strong>',
        step3Tag: 'Step 3',
        step3Title: '对接与协作支持 (Connection & Support)',
        step3Desc: '在确认筛选出的合作伙伴的履约记录和能力信息后，通过平台支持咨询、报价、下单流程。<br/><br/><strong style="color:#0b5cff;">[Input] 选择候选 → [Output] 匿名匹配及协作进行</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* 筛选标准：类似案例 / 现有设备 / 是否持有品质相关认证</span>',
        whyTitle: '技术优势 (Why us?)',
        why1Title: '基于数据的匹配依据',
        why1Desc: '提供客观的数据推荐理由，基于现有设备、类似项目履约记录、工艺范围，而非单纯的搜索结果。',
        diagramTitle: '中韩制造工作流程',
        diagramStep1: 'AI智能分析',
        diagramStep1Sub: '规格自动整理',
        diagramStep2: '全球DB匹配',
        diagramStep2Sub: '推荐Top3~5工厂',
        diagramStep3: '验证对接',
        diagramStep3Sub: '介绍+匿名匹配',
        why2Title: '中韩联合制造数据库',
        why2Desc: '基于整合的中韩制造基础设施数据库，支持基于技术理解的匹配。我们的优势在于反映开发视角的对接，而不仅仅是简单的中介。',
        why3Title: '提供品质标准信息 (Q/C)',
        why3Desc: '提供合作伙伴的现有设备、品质认证情况、履约记录等信息作为初步审核标准。<br/>※注：未通过 Nexyfab 进行的生产品质的最终责任归属于合同双方。',
        why4Title: '买方匿名匹配',
        why4Desc: '初期匹配阶段不向合作伙伴披露买方公司名称。仅在双方达成意向后才会共享身份信息。',
        statsTitle: '用数据解决制造难题',
        statsSub: '通过中韩整合的制造数据库(DB)和积累的案例，我们承诺提供最佳的匹配服务。',
        statsFactories: '300,000+',
        statsFactoriesLabel: '工厂数据库 (DB)',
        statsRefs: '6,000+',
        statsRefsLabel: '已认证合作伙伴池',
        casePrompt: '使用演示模式亲身体验真实的匹配流程。',
        caseBtn: '体验演示模式',
        ssTitle: '使用场景',
        ssRef1: '精密加工零件 (CNC · 钣金) 匹配',
        ssRef2: '小批量多品种样品制作',
    },
};
