export const en = {
    heroKicker: 'Nexyfab · Find Manufacturers.',
    heroTitle: 'Find Your Ideal<br/>Development Partner',
    heroSub: 'Enter product keywords to instantly search<br/>our Korean & Chinese factory database.',
    searchPlaceholder: 'Ex: Battery Automation',
    placeholderList: ['Battery Automation', 'Food Production Tools', 'Precision Machining', 'Logistics Systems', 'Semiconductor Tools'],
    searchBtn: 'Search',
    searching: 'Searching...',
    searchingSub: '(within 30 sec)',
    manufacturer: 'Manufacturer',
    industry: 'Industry',
    score: 'Score',
    contactTitle: '📨 Enter Contact Information',
    contactCompany: 'Name (Company)',
    contactPhone: 'Phone Number',
    contactEmail: 'Email',
    contactSubmit: 'Inquire',
    tabKoFactories: 'Korean Factories',
    tabCnFactories: 'Chinese Factories',
    noKoResults: 'No Korean factories found.',
    noCnResults: 'No Chinese factories found.',
    applyDashboard: 'Apply Now with Dashboard',
    loginApply: 'Login & Apply',
    applyDesc: 'AI RFP generation · quote comparison · dedicated support',
    gotoDashboard: 'Go to Dashboard →',
    signIn: 'Sign In →',
    orDirectContact: 'or contact us directly',
    statCount: '300k+',
    formSubmitting: 'Processing...',
    alertSuccess: 'Your inquiry has been successfully submitted.',
    alertError: 'An error occurred. Please try again later.',
    totalResults: 'Total',
    contactGuide: '* Name (Company), Phone, and Email are required to submit.',
    statKr: 'Korea/China Factories',
    statRef: 'Partner References',
    heroNote: '* Actual company names are not shown to customers,<br/>and are transferred for internal verification only upon inquiry submission.',

    howKicker: 'Nexyfab · How it Works.',
    howTitle: 'From Keyword to Connection',
    howSub: 'Search → Analysis → Selection → Connection → Actual Project Progress',
    step1Title: 'Requirements Input',
    step1Desc: 'Enter requirements as keywords to create analysis criteria.',
    step1Tag1: 'Battery Automation Equipment', step1Tag2: 'Special Purpose Equipment', step1Tag3: 'Process Improvement',
    step2Title: 'DB Search',
    step2Desc: 'Interpret keywords and organize candidates based on similar references/manufacturing capability data.',
    step2List1: 'Semantic expansion (synonyms/similar categories)',
    step2List2: 'Calculate suitability based on similar references',
    step2List3: 'Filter by industry/equipment/process conditions',
    step3Title: 'Selection of Suitable Partners',
    step3Desc: 'We narrow down the candidates to those who are "most suitable" rather than just "available".',
    step3List1: 'Tech difficulty/field matching',
    step3List2: 'Reflecting scope and reliability',
    step3List3: 'Exclude overlapping/unsuitable candidates',
    step4Title: 'Inquiry Connection',
    step4Desc: 'Project information is not disclosed externally, and is connected within the necessary scope after internal review.',
    step4Note: '* Actual company names are not shown to customers and are only transferred for internal verification.',
    howBottomTitle: 'Start with keyword search.',
    howBottomSub: 'You can start with just short keywords.',
    howBottomBtn: 'Keyword Search',

    whyKicker: 'Nexyfab · Why.',
    whyTitle: 'Different Standard of Connection',
    whySub: 'Not just simple matching, but matching based on actual feasibility and suitability.',
    why1Title: 'Not Random Quote Requests',
    why1Desc: 'Only qualified candidates are selected and delivered, reducing communication costs.',
    why2Title: 'Data-Based Filtering',
    why2Desc: 'Keyword interpretation, similar references, industry/equipment/process suitability are all reflected.',
    why3Title: 'Project Info Confidentiality Principle',
    why3Desc: 'Actual company names are not shown to customers, and are managed only for internal verification.',
    why4Title: 'Fast to Decision-Making',
    why4Desc: 'Not a "list of possible companies", but compressed "suitable candidates to review first".',
    whyCtaTitle: 'Shall we start matching right now?',
    whyCtaBtn: 'Project Inquiry',

    caseKicker: 'Nexyfab · Use Cases.',
    caseTitle: 'Strong in these projects',
    caseSub: 'We provide examples based only on <b><br/>project types</b>, without disclosing actual company/customer names.',
    case1Title: 'Automation Equipment',
    case1Desc: 'We select automation equipment partners by reflecting <br/>process conditions/layout/safety requirements.',
    case1Tag1: 'Assembly/Inspection', case1Tag2: 'Logistics/Transfer', case1Tag3: 'Line Expansion',
    case1Pill1: 'Similar Case', case1Pill2: 'Manu/Auto',
    case2Title: 'Special Purpose Equipment',
    case2Desc: 'Since "manufacturing feasibility" is key for special equipment, <br/>we prioritize similar references.',
    case2Tag1: 'Tools/Jigs', case2Tag2: 'Precision Drive', case2Tag3: 'Special Specs',
    case2Pill1: 'Similar Case', case2Pill2: 'Special Equipment',
    case3Title: 'R&D Prototype',
    case3Desc: 'Based on similar references and technical scope, we only narrow down manufacturing partners with high actual implementation possibility.',
    case3Tag1: 'PoC', case3Tag2: 'Prototype', case3Tag3: 'Performance Verification',
    case3Pill1: 'Similar Case', case3Pill2: 'R&D',
    case4Title: 'Plant/Equipment',
    case4Desc: 'For plant equipment, candidates are quickly connected <br/>based on similarity, safety, and delivery time.',
    case4Tag1: 'Similarity', case4Tag2: 'Precision', case4Tag3: 'Safety/Regulations',
    case4Pill1: 'Similar Case', case4Pill2: 'Plant',
    caseNoteTitle: 'Company/Project names are not disclosed externally.',
    caseNoteSub: 'Required information is requested according to the progress stage, <br/>and shared only with suitable partners after internal review.',

    revenueKicker: 'Nexyfab · Revenue Model.',
    revenueTitle: "Challenging Industry Lowest 4%, Nexyfab's Responsible Matching System",
    revenueSub: 'From inquiry to design & production kickoff—your final fee is only 4~7% of the quote (excl. VAT).',
    revenueStep1Title: 'Step 1. Matching Application Fee',
    revenueStep1Price: '400 USD (excl. VAT)',
    revenueStep1Value: 'Tech Review & Selection (Full Refund on Failure)',
    revenueStep1Desc: 'We go beyond simple connection to select the best manufacturer through professional tech review. We operate a No-Risk policy where the full application fee is refunded if no suitable partner is found.',
    revenueStep2Title: 'Step 2. Contract & Fee Settlement',
    revenueStep2Rate: 'Base Fee 4~7%',
    revenueStep2Value: 'Upon Contract (Step 1 Fee 100% Credited)',
    revenueStep2Desc: 'After partner matching, the base fee (4~7%, excl. VAT) is settled at contract signing. Your Step 1 application fee is fully credited toward this amount.',
    revenueStep3Title: 'Step 3. Design & Production Kickoff Management',
    revenueStep3Reward: 'Managed Until Delivery',
    revenueStep3Value: 'Dedicated operator support from design to delivery',
    revenueStep3Desc: 'After contract signing, a dedicated operator assists with scheduling, quality checks, and issue coordination throughout the design and production process, working alongside your partner to help ensure smooth delivery.',
    revenueFooterNote1: '',
    revenueFooterNote2: '',
    revenueFooterNote3: '* The minimum commission is set at 400 USD (Step 1 cost, excl. VAT).',
    revenueFooterNote4: '* For detailed fee and penalty policies, please refer to the Terms of Service.',
    revenueFlow1: '400 USD Application Fee',
    revenueFlow2: 'Fee Settlement at Contract',
    revenueFlow3: 'Design & Production Kickoff Management',

    platformKicker: 'NexyFab · Design to Manufacturing.',
    platformTitle: 'From Design to Manufacturing,\nAll in One Platform',
    platformSub: 'Instantly turn your ideas into 3D designs with AI, and perform structural analysis and topology optimization right in your browser.\nOnce your design is ready, our AI explores the 286,000+ factory database to surface suitable manufacturer candidates.',
    platformCta1: 'Start 3D Design',
    platformCta2: 'Find Manufacturers',
    factories: 'Browse Factories',
    platformMicro: 'Free · No signup · Start in your browser',
    platformDemoMigrate: '💾 Work you start without signup auto-migrates when you create an account',
    platformSearchPlaceholder: 'Search manufacturers now',
    platformSearchBtn: 'Search',
    socialStat1: '286,000+',
    socialStat1Label: 'Korea/China Factory DB',
    socialStat2: '16',
    socialStat2Label: '3D Shape Library',
    socialStat3: 'Free',
    socialStat3Label: 'Free Plan Available',
    wf1Hint: 'Parametric 3D CAD · 16 shapes · Sketch to Extrude',
    wf2Hint: 'FEA Structural · Modal Analysis · Thermal Simulation',
    wf3Hint: 'SIMP Topology Optimization · DFM Check · Lightweighting',
    wf4Hint: 'Auto 2D Drawing · Cost Estimation · Manufacturer Comparison',
    wf5Hint: 'Factory Search · 300k+ Factory DB · Anonymous Matching',
    featTabDesign: 'Design',
    featTabAnalysis: 'Analysis',
    featTabMfg: 'Manufacturing',
    platformBadge1: 'Free 3D CAD',
    platformBadge2: 'FEA Analysis',
    platformBadge3: 'AI Optimization',
    platformBadge4: 'Manufacturer Matching',

    featKicker: 'NexyFab · Capabilities.',
    featTitle: 'All-in-One Tools for Engineers',
    featSub: 'Design → quote → Korea-partner fulfillment in one chain. OpenSCAD-friendly · collaborative · no install.',
    feat1Title: 'Parametric 3D CAD',
    feat1Desc: '16 shapes, sketch-to-extrude, fillets, chamfers, patterns, and professional features.',
    feat2Title: 'Structural Analysis (FEA)',
    feat2Desc: 'Simulate stress, displacement, and safety factors to validate your design.',
    feat3Title: 'Topology Optimization',
    feat3Desc: 'SIMP algorithm generates optimal structures, reducing material by up to 40% while maintaining strength.',
    feat4Title: 'Modal & Thermal Analysis',
    feat4Desc: 'Natural frequency analysis and heat transfer simulation for dynamic/thermal stability.',
    feat5Title: 'DFM Analysis',
    feat5Desc: 'Automated manufacturability checks — wall thickness, hole diameter, draft angle, fillet radius, and aspect ratio.',
    feat6Title: 'Auto Drawing & Quoting',
    feat6Desc: 'Auto-generate 2D drawings, cost estimates, and manufacturer matching in one click.',

    wfKicker: 'NexyFab · Workflow.',
    wfTitle: 'Design to Manufacturing in 5 Steps',
    wfSub: 'From idea to real parts — all in one platform.',
    wf1Title: 'Design',
    wf1Desc: 'Parametric 3D modeling in your browser',
    wf2Title: 'Analyze',
    wf2Desc: 'Validate with FEA, thermal, and modal analysis',
    wf3Title: 'Optimize',
    wf3Desc: 'Topology optimization & DFM checks',
    wf4Title: 'Quote',
    wf4Desc: 'Cost estimation & manufacturer comparison',
    wf5Title: 'Manufacture',
    wf5Desc: 'Search factory DB to find the best manufacturer',

    personaKicker: 'NexyFab · For You.',
    personaTitle: 'Who is this platform for?',
    persona1Title: 'Design Engineers',
    persona1Desc: 'Browser-based parametric CAD with bidirectional OpenSCAD code. Optimized for standard part design and drawing output.',
    persona1Cta: 'Start 3D Design',
    persona2Title: 'Procurement Managers',
    persona2Desc: 'Upload drawings → instant cost estimate. Candidates from our Korea-China factory database.',
    persona2Cta: 'Request Quote',
    persona3Title: 'Startups & Makers',
    persona3Desc: 'Turn ideas into prototypes. Free CAD + small-batch quotes, all in one place.',
    persona3Cta: 'Start Free',

    ctaKicker: 'Nexyfab · Get Started.',
    ctaTitle: 'Shall we start your project now?',
    ctaSub: 'Just one line of keywords is enough.<br/>After internal review, we will connect you with the most suitable partner.',
    ctaBtn1: 'Submit Project',
    ctaBtn2: 'Keyword Search',

    onboardingTitle: 'What are you looking for?',
    onboardingSub: "We'll guide you to the right place.",
    onboardingPath1: 'Start 3D Design',
    onboardingPath1Desc: 'CAD modeling, analysis & optimization in browser',
    onboardingPath2: 'Manufacturing Inquiry',
    onboardingPath2Desc: 'Upload drawings · Compare quotes · Match manufacturers',
    onboardingPath3: 'Find Partners',
    onboardingPath3Desc: 'Search for the best manufacturers by keyword',
    onboardingSkip: 'Skip',

    howPage: {
        heroTitle: 'How we Work',
        heroSub: 'From search to connection — proceed from design to mass production<br/>based on a curated partner shortlist and objective matching data.',
        step1Tag: 'Step 1',
        step1Title: 'AI Smart Analysis',
        step1Desc: 'Based on project keywords, we organize the necessary process structure and technical scope from a manufacturing perspective. Analysis criteria for matching are defined at this stage.<br/><br/><strong style="color:#0b5cff;">[Input] Project Keywords → [Output] Deriving Matching Criteria & Tech Scope</strong>',
        step2Tag: 'Step 2',
        step2Title: 'Global DB Matching',
        step2Desc: 'Based on manufacturing DBs in Korea and China, we comprehensively analyze equipment, similar references, and process suitability to narrow down partners for priority review.<br/><br/><strong style="color:#0b5cff;">[Input] Analysis Criteria → [Output] 3–5 Suitable Candidates with Recommendation Rationale</strong>',
        step3Tag: 'Step 3',
        step3Title: 'Connection & Support',
        step3Desc: 'After verifying the performance history and capability information of the selected partners, we support the inquiry, quotation, and ordering process through the platform.<br/><br/><strong style="color:#0b5cff;">[Input] Candidate Selection → [Output] Anonymous Matching & Collaboration Progress</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* Selection Criteria: Similar References / Equipment / Quality-related Certifications</span>',
        whyTitle: 'Why Nexyfab?',
        why1Title: 'Data-driven Rationale',
        why1Desc: 'We provide objective data for recommendation reasons—based on equipment, similar project history, and process scope—rather than just simple search results.',
        diagramTitle: 'Korea-China Manufacturing Workflow',
        diagramStep1: 'AI Smart Analysis',
        diagramStep1Sub: 'Required specs summary',
        diagramStep2: 'Global DB Matching',
        diagramStep2Sub: 'Top 3–5 factories',
        diagramStep3: 'Anonymous Connection',
        diagramStep3Sub: 'Intro + Anonymous Matching',
        why2Title: 'Integrated Korea-China Mfg. DB',
        why2Desc: "Based on an integrated DB of Korea and China manufacturing infrastructure, we support matching founded on technical understanding. Our strength is a connection that reflects a development perspective, not just simple mediation.",
        why3Title: 'Providing Quality Standard Info (Q/C)',
        why3Desc: "We provide information such as the partner's equipment, quality certifications, and performance history as preliminary review criteria.<br/>*Note: Final responsibility for production quality not processed through Nexyfab lies with the contracting parties.",
        why4Title: 'Anonymous Buyer Matching',
        why4Desc: 'Your company name is hidden from partners during initial matching. Identities are revealed only after both sides agree to engage.',
        statsTitle: 'Solving Manufacturing Challenges with Data',
        statsSub: 'Promising optimal matching through our integrated Korea-China manufacturing database and accumulated references.',
        statsFactories: '286,000+',
        statsFactoriesLabel: 'Factory Database',
        statsRefs: '6,000+',
        statsRefsLabel: 'Korea-China Factory Database',
        casePrompt: 'Try the demo mode to walk through a real matching flow yourself.',
        caseBtn: 'Try Demo Mode',
        ssTitle: 'Use Case Scenarios',
        ssRef1: 'Precision Machining (CNC · Sheet Metal) Matching',
        ssRef2: 'Low-volume / Multi-variant Prototype Production',
    },
};
