export const es = {
    heroKicker: 'Nexyfab · Buscar Fabricantes.',
    heroTitle: 'Encuentre su socio<br/>de desarrollo ideal',
    heroSub: 'Ingrese palabras clave del producto<br/>busque en nuestra base verificada de fábricas coreanas y chinas.',
    searchPlaceholder: 'Ej: Automatización de baterías',
    placeholderList: ['Automatización de baterías', 'Equipos de producción alimentaria', 'Mecanizado de precisión', 'Sistemas logísticos', 'Equipos semiconductores'],
    searchBtn: 'Buscar',
    searching: 'Buscando...',
    searchingSub: '(en menos de 30 seg)',
    manufacturer: 'Fabricante',
    industry: 'Sector',
    score: 'Compatibilidad',
    contactTitle: '📨 Información de contacto',
    contactCompany: 'Nombre (Empresa)',
    contactPhone: 'Teléfono',
    contactEmail: 'Correo electrónico',
    contactSubmit: 'Consultar',
    tabKoFactories: 'Fábricas Coreanas',
    tabCnFactories: 'Fábricas Chinas',
    noKoResults: 'No se encontraron fábricas coreanas.',
    noCnResults: 'No se encontraron fábricas chinas.',
    applyDashboard: 'Solicitar desde el Panel',
    loginApply: 'Iniciar sesión y Solicitar',
    applyDesc: 'Generación AI RFP · comparación de cotizaciones · soporte dedicado',
    gotoDashboard: 'Ir al Panel →',
    signIn: 'Iniciar sesión →',
    orDirectContact: 'o contáctenos directamente',
    statCount: '300k+',
    formSubmitting: 'Procesando...',
    alertSuccess: 'Su consulta ha sido enviada exitosamente.',
    alertError: 'Ocurrió un error. Por favor, inténtelo más tarde.',
    totalResults: 'Total',
    contactGuide: '* Nombre (Empresa), Teléfono y Correo electrónico son campos obligatorios.',
    statKr: 'Fábricas en Corea/China',
    statRef: 'Referencias acumuladas de socios',
    heroNote: '* Los nombres reales de las empresas no se muestran a los clientes<br/>y solo se transmiten para verificación interna al enviar una consulta.',

    howKicker: 'Nexyfab · How it Works.',
    howTitle: 'De la palabra clave a la conexión',
    howSub: 'Búsqueda → Análisis → Selección → Conexión → Avance real del proyecto',
    step1Title: 'Ingreso de requisitos',
    step1Desc: 'Ingrese sus requisitos como palabras clave para generar criterios de análisis.',
    step1Tag1: 'Equipos de automatización de baterías', step1Tag2: 'Equipos de uso especial', step1Tag3: 'Mejora de procesos',
    step2Title: 'Búsqueda en DB',
    step2Desc: 'Buscamos fabricantes relevantes en la base de datos de fábricas de Corea y China usando las palabras clave ingresadas.',
    step2List1: 'Expansión semántica (sinónimos/categorías similares)',
    step2List2: 'Cálculo de idoneidad basado en referencias similares',
    step2List3: 'Filtrado por sector/equipos/condiciones de proceso',
    step3Title: 'Selección de socios adecuados',
    step3Desc: 'Reducimos los candidatos a los "más adecuados", no solo a los "disponibles".',
    step3List1: 'Dificultad técnica / compatibilidad de campo',
    step3List2: 'Alcance de ejecución y fiabilidad',
    step3List3: 'Exclusión de candidatos duplicados o no aptos',
    step4Title: 'Conexión de consulta',
    step4Desc: 'La información del proyecto no se divulga externamente y se conecta dentro del alcance necesario tras una revisión interna.',
    step4Note: '* Los nombres reales de las empresas no se muestran a los clientes y solo se transmiten para verificación interna.',
    howBottomTitle: 'Comience con una búsqueda por palabras clave.',
    howBottomSub: 'Con unas pocas palabras clave es suficiente para empezar.',
    howBottomBtn: 'Búsqueda por palabras clave',

    whyKicker: 'Nexyfab · Why.',
    whyTitle: 'Un estándar de conexión diferente',
    whySub: 'No es un simple emparejamiento, sino una conexión basada en viabilidad real y compatibilidad.',
    why1Title: 'No son solicitudes de cotización al azar',
    why1Desc: 'Solo seleccionamos y entregamos candidatos calificados que cumplen los requisitos, reduciendo costos de comunicación.',
    why2Title: 'Filtrado basado en datos',
    why2Desc: 'Consideramos la interpretación de palabras clave, referencias similares y condiciones de sector/equipos/proceso.',
    why3Title: 'Principio de confidencialidad del proyecto',
    why3Desc: 'Los nombres reales de las empresas no se muestran a los clientes y se gestionan únicamente para verificación interna.',
    why4Title: 'Decisiones más rápidas',
    why4Desc: 'No ofrecemos una "lista de posibles empresas", sino un grupo reducido de "candidatos idóneos para revisión prioritaria".',
    whyCtaTitle: '¿Comenzamos con el emparejamiento ahora?',
    whyCtaBtn: 'Consulta de proyecto',

    caseKicker: 'Nexyfab · Use Cases.',
    caseTitle: 'Destacamos en estos proyectos',
    caseSub: 'Proporcionamos ejemplos basados únicamente en<br/><b>tipos de proyecto</b>, sin divulgar nombres reales de empresas o clientes.',
    case1Title: 'Equipos de automatización',
    case1Desc: 'Seleccionamos socios de automatización considerando<br/>condiciones de proceso/diseño/requisitos de seguridad.',
    case1Tag1: 'Ensamblaje/Inspección', case1Tag2: 'Logística/Transporte', case1Tag3: 'Ampliación de línea',
    case1Pill1: 'Caso similar', case1Pill2: 'Fabricación/Automatización',
    case2Title: 'Equipos de uso especial',
    case2Desc: 'Dado que la "viabilidad de fabricación" es clave en equipos especiales,<br/>priorizamos la revisión de referencias similares.',
    case2Tag1: 'Herramientas/Utillajes', case2Tag2: 'Accionamiento de precisión', case2Tag3: 'Especificaciones especiales',
    case2Pill1: 'Caso similar', case2Pill2: 'Equipo especial',
    case3Title: 'Prototipos de I+D',
    case3Desc: 'Basándonos en referencias similares y alcance técnico, seleccionamos únicamente socios de fabricación con alta viabilidad de implementación.',
    case3Tag1: 'PoC', case3Tag2: 'Prototipo', case3Tag3: 'Verificación de rendimiento',
    case3Pill1: 'Caso similar', case3Pill2: 'I+D',
    case4Title: 'Plantas/Equipamiento',
    case4Desc: 'Para equipamiento de plantas, conectamos rápidamente<br/>basándonos en similitud, seguridad y plazos de entrega.',
    case4Tag1: 'Similitud', case4Tag2: 'Precisión', case4Tag3: 'Seguridad/Normativa',
    case4Pill1: 'Caso similar', case4Pill2: 'Planta',
    caseNoteTitle: 'Los nombres de empresas/proyectos no se divulgan externamente.',
    caseNoteSub: 'La información detallada se solicita según la etapa de avance<br/>y se comparte solo con socios adecuados tras una revisión interna.',

    reviewKicker: 'Nexyfab · Reviews.',
    reviewTitle: 'Opiniones de clientes',
    reviewSub: 'En las "opiniones", los <b>resultados</b> importan más que las impresiones.<br/>Hemos recopilado los comentarios más frecuentes del proceso real.',
    reviewKpi1Title: 'Reducción de plazos',
    reviewKpi1Desc: 'Reducimos el tiempo de búsqueda y verificación de candidatos, acelerando la toma de decisiones.',
    reviewKpi2Title: 'Clarificación de requisitos',
    reviewKpi2Desc: 'Incluso en etapas iniciales ambiguas, establecemos una dirección de desarrollo clara.',
    reviewKpi3Title: 'Emparejamiento personalizado',
    reviewKpi3Desc: 'Reducimos candidatos según referencias similares, sector y nivel de dificultad.',
    review1Tag: 'Destacado', review1Pill1: 'PoC', review1Pill2: 'Nuevo desarrollo', review1Pill3: 'Plazo de entrega',
    review1Quote: 'Nos conectaron rápidamente con el socio adecuado,<br/>lo que nos permitió completar el PoC en poco tiempo.',
    review1Who: 'Gran empresa A', review1WhoSub: 'Desarrollo de nuevos productos', review1Chip: 'Enterprise',
    review2Tag: 'Búsqueda de proveedores', review2Pill1: 'Basado en BD', review2Pill2: 'Verificación',
    review2Quote: 'Gracias a la base de datos de fabricantes,<br/>redujimos a la mitad el tiempo de investigación de mercado.',
    review2Who: 'Mediana empresa B', review2WhoSub: 'Aprovisionamiento', review2Chip: 'Mediana',
    review3Tag: 'Estrategia de desarrollo', review3Pill1: 'Hoja de ruta',
    review3Quote: 'No fue solo una conexión de fabricación; primero organizaron la dirección y el alcance del desarrollo, lo que definió el proyecto con mucha claridad.',
    review3Who: 'Pyme C', review3WhoSub: 'Estrategia/Optimización de costos', review3Chip1: 'Hoja de ruta', review3Chip2: 'Pyme',
    review4Tag: 'MVP', review4Pill1: 'Reducción de costos', review4Pill2: 'Cronograma',
    review4Quote: 'Los costos estimados bajaron significativamente y, gracias a criterios de comunicación claros,<br/>el desarrollo avanza sin contratiempos.',
    review4Who: 'Startup S', review4WhoSub: 'MVP · Reducción de costos', review4Chip: 'Startup',
    review5Tag: 'Gestión de procesos', review5Pill1: 'Requisitos', review5Pill2: 'Calidad',
    review5Quote: 'Incluso cuando cambiaron los requisitos, reajustaron los criterios<br/>y mantuvieron la consistencia del entregable final.',
    review5Who: 'Fabricante D', review5WhoSub: 'Desarrollo · Calidad', review5Chip1: 'Estabilidad', review5Chip2: 'Fabricación',

    revenueKicker: 'Nexyfab · Revenue Model.',
    revenueTitle: 'Desafiando la comisión más baja del sector: 4%. Sistema de emparejamiento responsable de Nexyfab',
    revenueSub: 'Desde la consulta hasta el inicio del diseño y producción, la comisión final es solo del 4~7% (IVA excl.).',
    revenueStep1Title: 'Paso 1. Tarifa de solicitud de emparejamiento',
    revenueStep1Price: '400 USD',
    revenueStep1Value: 'Revisión técnica y selección de socios (reembolso total si no hay resultado)',
    revenueStep1Desc: 'Vamos más allá de una simple conexión: seleccionamos al mejor fabricante mediante una revisión técnica profesional. Si no encontramos un socio adecuado, reembolsamos íntegramente la tarifa de solicitud bajo nuestra política sin riesgo.',
    revenueStep2Title: 'Paso 2. Contrato y liquidación de comisión',
    revenueStep2Rate: 'Comisión base 4~7%',
    revenueStep2Value: 'Al firmar el contrato (deducción del 100% del Paso 1)',
    revenueStep2Desc: 'Tras el emparejamiento con el socio, se liquida la comisión base (4~7%, IVA excl.) al firmar el contrato. La tarifa del Paso 1 se deduce íntegramente.',
    revenueStep3Title: 'Paso 3. Inicio de diseño y producción, y gestión de entrega',
    revenueStep3Reward: 'Gestión hasta la entrega',
    revenueStep3Value: 'Soporte dedicado desde el diseño hasta la entrega',
    revenueStep3Desc: 'Tras la firma del contrato, un operador dedicado asiste en la gestión de plazos, control de calidad y resolución de incidencias, trabajando junto al socio fabricante para facilitar una entrega sin contratiempos.',
    revenueFooterNote1: '',
    revenueFooterNote2: '',
    revenueFooterNote3: '* La comisión mínima se establece en 400 USD (costo del Paso 1, IVA excl.).',
    revenueFooterNote4: '* Para políticas detalladas de comisiones y penalizaciones, consulte los Términos de Servicio.',
    revenueFlow1: 'Tarifa de solicitud 400 USD',
    revenueFlow2: 'Liquidación de comisión al contrato',
    revenueFlow3: 'Gestión de inicio y entrega',

    platformKicker: 'NexyFab · Design to Manufacturing.',
    platformTitle: 'Del Diseno a la Fabricacion,\nTodo en Una Plataforma',
    platformSub: 'CAD 3D, analisis estructural y optimizacion topologica en tu navegador.\nUna vez listo tu diseno, obtén cotizaciones instantáneas de 300.000+ fabricas y conecta con los mejores.',
    platformCta1: 'Iniciar Diseno 3D',
    platformCta2: 'Buscar Fabricantes',
    factories: 'Explorar Fábricas',
    platformMicro: 'Gratis · Sin registro · Empieza en tu navegador',
    platformDemoMigrate: '💾 El trabajo iniciado sin registro se migra automáticamente al crear cuenta',
    platformSearchPlaceholder: 'Busca fabricantes ahora',
    platformSearchBtn: 'Buscar',
    socialStat1: '300,000+',
    socialStat1Label: 'Fabricas Corea/China',
    socialStat2: '16',
    socialStat2Label: 'Biblioteca 3D',
    socialStat3: 'Gratis',
    socialStat3Label: 'Plan Gratuito',
    wf1Hint: 'CAD 3D Parametrico · 16 formas · Boceto a Extruir',
    wf2Hint: 'FEA Estructural · Analisis Modal · Simulacion Termica',
    wf3Hint: 'SIMP Topologia · DFM Check · Aligeramiento',
    wf4Hint: 'Plano 2D Auto · Estimacion de Costos · Comparacion',
    wf5Hint: 'Búsqueda DB · 300k+ Fábricas · Coincidencia Anónima',
    featTabDesign: 'Diseno',
    featTabAnalysis: 'Analisis',
    featTabMfg: 'Fabricacion',
    platformBadge1: 'CAD 3D Gratis',
    platformBadge2: 'Analisis FEA',
    platformBadge3: 'Optimización IA',
    platformBadge4: 'Cotizacion Instantanea',

    featKicker: 'NexyFab · Capabilities.',
    featTitle: 'Herramientas Todo-en-Uno para Ingenieros',
    featSub: 'Diseno → cotizacion → pedido a partner coreano en una sola cadena. Compatible con OpenSCAD · colaborativo · sin instalacion.',
    feat1Title: 'CAD 3D Parametrico',
    feat1Desc: '16 formas, boceto a extruir, filetes, chaflanes, patrones y funciones profesionales.',
    feat2Title: 'Analisis Estructural (FEA)',
    feat2Desc: 'Simula esfuerzos, desplazamiento y factores de seguridad para validar tu diseno.',
    feat3Title: 'Optimizacion Topologica',
    feat3Desc: 'Algoritmo SIMP genera estructuras optimas, reduciendo material hasta 40%.',
    feat4Title: 'Analisis Modal y Termico',
    feat4Desc: 'Analisis de frecuencia natural y simulacion termica para estabilidad dinamica.',
    feat5Title: 'Analisis DFM',
    feat5Desc: 'Verificación automática de fabricabilidad — espesor de pared, diámetro de orificios, ángulos de salida, radios de filete y relación de aspecto.',
    feat6Title: 'Planos y Cotizacion Auto',
    feat6Desc: 'Genera planos 2D, estimaciones de costo y emparejamiento con fabricantes en un clic.',

    wfKicker: 'NexyFab · Workflow.',
    wfTitle: 'Del Diseno a Fabricacion en 5 Pasos',
    wfSub: 'De la idea a piezas reales — todo en una plataforma.',
    wf1Title: 'Disenar',
    wf1Desc: 'Modelado 3D parametrico en tu navegador',
    wf2Title: 'Analizar',
    wf2Desc: 'Validar con FEA, analisis termico y modal',
    wf3Title: 'Optimizar',
    wf3Desc: 'Optimizacion topologica y verificacion DFM',
    wf4Title: 'Cotizar',
    wf4Desc: 'Estimacion de costos y comparacion de fabricantes',
    wf5Title: 'Fabricar',
    wf5Desc: 'Búsqueda en DB para conectar con el mejor fabricante',

    personaKicker: 'NexyFab · For You.',
    personaTitle: '¿Para quién es esta plataforma?',
    persona1Title: 'Ingenieros de Diseno',
    persona1Desc: 'CAD parametrico en navegador con codigo OpenSCAD bidireccional. Optimizado para diseno de piezas estandar y salida de planos.',
    persona1Cta: 'Iniciar Diseno 3D',
    persona2Title: 'Gerentes de Compras',
    persona2Desc: 'Sube planos → comparacion instantanea de cotizaciones. Solo fabricantes verificados.',
    persona2Cta: 'Solicitar Cotizacion',
    persona3Title: 'Startups y Makers',
    persona3Desc: 'Convierte ideas en prototipos. CAD gratis + cotizaciones de produccion en un solo lugar.',
    persona3Cta: 'Comenzar Gratis',

    ctaKicker: 'Nexyfab · Get Started.',
    ctaTitle: '¿Comenzamos su proyecto ahora?',
    ctaSub: 'Con una sola línea de palabras clave es suficiente.<br/>Tras una revisión interna, le conectaremos con el socio más adecuado.',
    ctaBtn1: 'Consulta de proyecto',
    ctaBtn2: 'Búsqueda por palabras clave',

    onboardingTitle: '¿Qué necesitas hacer?',
    onboardingSub: 'Te guiaremos al lugar correcto.',
    onboardingPath1: 'Iniciar diseño 3D',
    onboardingPath1Desc: 'Diseño CAD, análisis y optimización en el navegador',
    onboardingPath2: 'Consulta de fabricación',
    onboardingPath2Desc: 'Subir planos · Comparar presupuestos · Encontrar fabricantes',
    onboardingPath3: 'Buscar socios',
    onboardingPath3Desc: 'Busca los mejores fabricantes por palabra clave',
    onboardingSkip: 'Omitir',
    howPage: {
        heroTitle: 'How we Work',
        heroSub: 'De la búsqueda a la conexión: avance del diseño a la producción en serie<br/>con una lista verificada de socios y datos de emparejamiento objetivos.',
        step1Tag: 'Paso 1',
        step1Title: 'Análisis inteligente con IA (Smart Analysis)',
        step1Desc: 'A partir de las palabras clave del proyecto, organizamos la estructura de procesos y el alcance técnico necesarios desde la perspectiva de fabricación. Los criterios de análisis para el emparejamiento se definen en esta etapa.<br/><br/><strong style="color:#0b5cff;">[Entrada] Palabras clave del proyecto → [Salida] Criterios de emparejamiento y alcance técnico</strong>',
        step2Tag: 'Paso 2',
        step2Title: 'Emparejamiento con BD global (Global DB Matching)',
        step2Desc: 'Con base en las BD de fabricación de Corea y China, analizamos integralmente equipos, referencias similares e idoneidad de procesos para priorizar socios candidatos.<br/><br/><strong style="color:#0b5cff;">[Entrada] Criterios de análisis → [Salida] 3–5 candidatos adecuados con fundamento de recomendación</strong>',
        step3Tag: 'Paso 3',
        step3Title: 'Conexión y soporte de colaboración (Connection & Support)',
        step3Desc: 'Tras verificar el historial de desempeño y la información de capacidad de los socios seleccionados, apoyamos el proceso de consulta, cotización y pedido a través de la plataforma.<br/><br/><strong style="color:#0b5cff;">[Entrada] Selección de candidato → [Salida] Coincidencia anónima y avance de colaboración</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* Criterios de selección: Referencias similares / Equipos / Certificaciones de calidad</span>',
        whyTitle: '¿Por qué Nexyfab?',
        why1Title: 'Fundamento basado en datos',
        why1Desc: 'Proporcionamos datos objetivos como base de recomendación, basados en equipos, historial de proyectos similares y alcance de procesos, no solo resultados de búsqueda.',
        diagramTitle: 'Flujo de trabajo de fabricación Corea-China',
        diagramStep1: 'Análisis inteligente con IA',
        diagramStep1Sub: 'Resumen de especificaciones',
        diagramStep2: 'Emparejamiento con BD global',
        diagramStep2Sub: 'Top 3–5 fábricas',
        diagramStep3: 'Conexión verificada',
        diagramStep3Sub: 'Presentación + coincidencia anónima',
        why2Title: 'BD integrada de fabricación Corea-China',
        why2Desc: 'Basándonos en una BD integrada de infraestructura de fabricación de Corea y China, ofrecemos un emparejamiento con comprensión técnica. Nuestra fortaleza es una conexión que refleja la perspectiva de desarrollo, no una simple intermediación.',
        why3Title: 'Información de estándares de calidad (Q/C)',
        why3Desc: 'Proporcionamos información sobre equipos del socio, certificaciones de calidad e historial de desempeño como criterios de revisión preliminar.<br/>*Nota: La responsabilidad final sobre la calidad de producción no gestionada a través de Nexyfab recae en las partes contratantes.',
        why4Title: 'Coincidencia con nombre de empresa privado',
        why4Desc: 'El nombre de su empresa permanece privado durante la fase de coincidencia. La información del proyecto se comparte únicamente dentro del alcance de la revisión interna.',
        statsTitle: 'Resolviendo desafíos de fabricación con datos',
        statsSub: 'Garantizamos un emparejamiento óptimo a través de nuestra base de datos integrada de fabricación Corea-China y referencias acumuladas.',
        statsFactories: '300,000+',
        statsFactoriesLabel: 'Base de datos de fábricas',
        statsRefs: '6,000+',
        statsRefsLabel: 'Socios con certificaciones verificadas',
        casePrompt: 'Pruebe el modo demo y vea cómo funciona el emparejamiento sin necesidad de registrarse.',
        caseBtn: 'Iniciar modo demo',
        ssTitle: 'Casos de éxito (Success Stories)',
        ssRef1: 'Emparejamiento de CNC y chapa metálica',
        ssRef2: 'Prototipos de bajo volumen y alta variedad',
    },
};
