export const ja = {
    heroKicker: 'Nexyfab · メーカー検索.',
    heroTitle: '最適な開発パートナーを<br/>検索してみましょう',
    heroSub: '製品キーワードを入力するだけで<br/>韓国・中国の工場DBから関連メーカーを検索。',
    searchPlaceholder: '例: バッテリー自動化設備',
    placeholderList: ['バッテリー自動化設備', '食品生産設備', '精密部品加工', '物流搬送システム', '半導体洗浄装置'],
    searchBtn: '検索',
    searching: '検索中...',
    searchingSub: '(約30秒以内)',
    manufacturer: 'メーカー',
    industry: '業種',
    score: '適合度',
    contactTitle: '📨 連絡先の入力',
    contactCompany: '名前（会社名）',
    contactPhone: '電話番号',
    contactEmail: 'メールアドレス',
    contactSubmit: '問い合わせ',
    tabKoFactories: '韓国の工場',
    tabCnFactories: '中国の工場',
    noKoResults: '該当する韓国の工場はありません。',
    noCnResults: '該当する中国の工場はありません。',
    applyDashboard: 'ダッシュボードで申請',
    loginApply: 'ログインして申請',
    applyDesc: 'AI RFP自動生成・見積比較・専任サポート',
    gotoDashboard: 'ダッシュボードへ →',
    signIn: 'ログイン →',
    orDirectContact: 'または直接お問い合わせ',
    statCount: '28万+',
    formSubmitting: '処理中...',
    alertSuccess: 'お問い合わせが送信されました。',
    alertError: 'エラーが発生しました。後でもう一度お試しください。',
    totalResults: '全',
    contactGuide: '* 名前（会社名）、電話番号、メールアドレスは必須入力項目です。',
    statKr: '韓国・中国の工場',
    statRef: '提携先累積実績',
    heroNote: '* 実際の会社名は顧客画面に表示されず、<br/>問い合わせ提出時に内部確認用としてのみ伝達されます。',

    howKicker: 'Nexyfab · How it Works.',
    howTitle: 'キーワード入力から接続まで',
    howSub: '検索 → 分析 → 選定 → 接続 → 実際のプロジェクト進行',
    step1Title: '要件入力',
    step1Desc: '要件をキーワードとして入力すると、分析基準が生成されます。',
    step1Tag1: 'バッテリー自動化設備', step1Tag2: '特殊目的機器', step1Tag3: '工程改善',
    step2Title: 'DB検索',
    step2Desc: 'キーワードをもとに、韓国・中国の工場DBから関連メーカーを検索します。',
    step2List1: '意味拡張(同義語/類似カテゴリ)',
    step2List2: '類似リファレンスに基づく適合度算出',
    step2List3: '業種/設備/工程条件によるフィルタリング',
    step3Title: '適合パートナーの選別',
    step3Desc: '「可能な場所」ではなく「最も適合する場所」を優先検討候補として圧縮します。',
    step3List1: '技術難易度/分野マッチング',
    step3List2: '遂行範囲と信頼性の反映',
    step3List3: '重複・不適合候補の除外',
    step4Title: '問い合わせの接続',
    step4Desc: 'プロジェクト情報は外部に公開されず、内部検討後、必要な範囲で接続されます。',
    step4Note: '* 実際の会社名は顧客画面에 표시되지 않으며, 内部確認用としてのみ伝達されます。',
    howBottomTitle: 'キーワード検索から始めましょう。',
    howBottomSub: '短いキーワードだけでも始めることができます。',
    howBottomBtn: 'キーワード検索',

    whyKicker: 'Nexyfab · Why.',
    whyTitle: '「接続」の基準が異なります',
    whySub: '単純なマッチングではなく、実際の遂行可能性と適合性を基準にマッチングします。',
    why1Title: '無作為な見積もり依頼ではありません',
    why1Desc: '要件に合致する適格な候補のみを選別して伝達するため、コミュニケーション費用が削減されます.',
    why2Title: 'データ基盤のフィルタリング',
    why2Desc: 'キーワード解釈、類似リファレンス、業種/設備/工程条件をすべて反映します。',
    why3Title: 'プロジェクト情報非公開の原則',
    why3Desc: '実際の会社名は顧客に公開されず、内部確認のためにのみ管理されます。',
    why4Title: '意思決定まで迅速に',
    why4Desc: '「可能なリスト」ではなく、「最初に検討すべき適合候補群」に圧縮します。',
    whyCtaTitle: '今すぐマッチングを始めましょうか？',
    whyCtaBtn: 'プロジェクトお問い合わせ',

    caseKicker: 'Nexyfab · Use Cases.',
    caseTitle: 'こんなプロジェクト에 강합니다',
    caseSub: '実際の企業/顧客名は公開せず、<br/><b>プロジェクトタイプ</b>のみに基づいて例を提供します。',
    case1Title: '自動化設備',
    case1Desc: '工程条件/レイアウト/安全要件などを反映して<br/>最適な自動化パートナーを選別します。',
    case1Tag1: '組立/検査', case1Tag2: '物流/搬送', case1Tag3: 'ライン増設',
    case1Pill1: '類似事例', case1Pill2: '製造/自動化',
    case2Title: '特殊目的機器',
    case2Desc: '特殊機器は「製造可能性」が重要であるため、<br/>類似リファレン스를 최우선으로 검토합니다.',
    case2Tag1: '治具/ツール', case2Tag2: '精密駆動', case2Tag3: '特別仕様',
    case2Pill1: '類似事例', case2Pill2: '特殊機器',
    case3Title: 'R&Dプロトタイプ',
    case3Desc: '類似のリファレンスと技術範囲に基づき、実際の実現可能性が高い製造パートナーのみを厳選します。',
    case3Tag1: 'PoC', case3Tag2: 'プロトタイプ', case3Tag3: '性能検証',
    case3Pill1: '類似事例', case3Pill2: 'R&D',
    case4Title: 'プラント/設備',
    case4Desc: 'プラント設備の場合、類似性、安全性、<br/>納期を基準に迅速に連携します。',
    case4Tag1: '類似性', case4Tag2: '精度', case4Tag3: '安全/規制',
    case4Pill1: '類似事例', case4Pill2: 'プラント',
    caseNoteTitle: '企業名/プロジェクト名は外部에 노출되지 않습니다.',
    caseNoteSub: '進行段階に合わせて必要な情報をリクエストし、<br/>内部検討後、適合パートナーにのみ共有されます。',

    reviewKicker: 'Nexyfab · Reviews.',
    reviewTitle: '顧客レビュー',
    reviewSub: '「レビュー」では感想よりも<b>結果</b>が重要です。<br/>実際のプロセスでよくあるフィードバックを整理しました。',
    reviewKpi1Title: 'リードタイムの短縮',
    reviewKpi1Desc: '候補の発見/検証時間を短縮し、意思決定を迅速にします。',
    reviewKpi2Title: '要件の整理',
    reviewKpi2Desc: '曖昧な初期段階でも、開発の方向性を明確に確立します。',
    reviewKpi3Title: 'カスタムマッチング',
    reviewKpi3Desc: '類似リファレンス/業種/難易度を基準に候補を圧縮します。',
    review1Tag: 'Featured', review1Pill1: 'PoC', review1Pill2: '新規開発', review1Pill3: 'リードタイム',
    review1Quote: '適切なパートナーを迅速に接続してくれたため、<br/>短期間でPoCを成功させることができました。',
    review1Who: '大企業 A', review1WhoSub: '新製品開発', review1Chip: 'Enterprise',
    review2Tag: 'ベンダーソーシング', review2Pill1: 'DB基盤', review2Pill2: '検証',
    review2Quote: 'メーカーDBのおかげで、市場調査に<br/>費やす時間が半分に短縮されました。',
    review2Who: '中堅企業 B', review2WhoSub: 'ソーシング', review2Chip: 'Mid-size',
    review3Tag: '開発戦略', review3Pill1: 'ロードマップ',
    review3Quote: '単なる制作の連携ではなく、開発の方向性と範囲をまず整理してくれたため、プロジェクトの定義が非常に明確になりました。',
    review3Who: '中小企業 C', review3WhoSub: '戦略/コスト最適化', review3Chip1: 'ロードマップ', review3Chip2: 'SME',
    review4Tag: 'MVP', review4Pill1: 'コスト削減', review4Pill2: 'スケジュール',
    review4Quote: '見積もりコストが大幅に下がり、コミュニケーション基準が明確なため、<br/>開発がスムーズに進んでいます。',
    review4Who: 'スタートアップ S', review4WhoSub: 'MVP · コスト 절감', review4Chip: 'Startup',
    review5Tag: '工程管理', review5Pill1: '要件', review5Pill2: '品質',
    review5Quote: '要件が変更された場合でも基準を再調整し、<br/>最終的な成果物の一貫性を保ちます。',
    review5Who: 'メーカー D', review5WhoSub: '開発 · 品質', review5Chip1: '安定性', review5Chip2: 'Manufacturing',

    revenueKicker: 'Nexyfab · Revenue Model.',
    revenueTitle: '業界最低水準4%に挑戦, Nexyfab「責任マッチング」システム',
    revenueSub: 'お問い合わせから設計・量産着手まで、最終手数料は見積もりの4~7%（税別）のみです。',
    revenueStep1Title: 'Step 1. マッチング申請金',
    revenueStep1Price: '60,000 JPY（税別）',
    revenueStep1Value: '技術検討およびパートナー選別 (失敗時 全額返金)',
    revenueStep1Desc: '単なる接続を超え、専門的な技術検討を通じて最適な製造社を選別します。適切なパートナーが見つからない場合、申請金の全額を即座に返金するNo-Riskポリシーを運営しています。',
    revenueStep2Title: 'Step 2. 契約締結・手数料精算',
    revenueStep2Rate: '基本手数料 4~7%',
    revenueStep2Value: '契約締結時 (Step 1 申請金 100% 控除)',
    revenueStep2Desc: 'パートナーマッチング後、契約締結時に基本手数料（4~7%、税別）を精算します。Step 1 申請金は手数料から100%控除されます。',
    revenueStep3Title: 'Step 3. 設計・量産着手および納品管理',
    revenueStep3Reward: '納品完了まで責任管理',
    revenueStep3Value: '設計から納品まで専任オペレーターが密着サポート',
    revenueStep3Desc: '契約締結後、設計着手から納品完了まで専任オペレーターがスケジュール管理、品質確認、問題対応など、円滑な進行のためにパートナー企業とともにサポートいたします。',
    revenueFooterNote1: '',
    revenueFooterNote2: '',
    revenueFooterNote3: '* 最小手数料は 60,000 JPY（Step 1費用、税別）に設定されます。',
    revenueFooterNote4: '* 手数料および違約金の詳細については、サービス利用規約をご確認ください。',
    revenueFlow1: '60,000 JPY 申請金',
    revenueFlow2: '契約時 手数料精算',
    revenueFlow3: '設計・量産着手および納品管理',

    platformKicker: 'NexyFab · Design to Manufacturing.',
    platformTitle: '設計から製造まで、\nひとつのプラットフォームで',
    platformSub: 'AIを活用してアイデアを即座に3D設計として具現化し、ブラウザで構造解析からトポロジー最適化まで。\n設計完了後、AIが28万社以上の工場DBを探索し、適したメーカー候補をご提案します。',
    platformCta1: '3D設計を始める',
    platformCta2: 'メーカーマッチング',
    factories: '工場を探す',
    platformMicro: '無料 · 登録不要 · ブラウザですぐ開始',
    platformDemoMigrate: '💾 登録前の作業はアカウント作成時に自動で引き継がれます',
    platformSearchPlaceholder: 'メーカーを検索してみましょう',
    platformSearchBtn: '検索',
    socialStat1: '286,000+',
    socialStat1Label: '韓中工場DB',
    socialStat2: '16種',
    socialStat2Label: '3D形状ライブラリ',
    socialStat3: '無料',
    socialStat3Label: '無料プラン提供',
    wf1Hint: 'パラメトリック3D CAD · 16形状 · スケッチ→押し出し',
    wf2Hint: 'FEA構造解析 · モーダル分析 · 熱伝達シミュレーション',
    wf3Hint: 'SIMPトポロジー最適化 · DFMチェック · 軽量化',
    wf4Hint: '自動2D図面 · コスト算出 · メーカー比較',
    wf5Hint: '工場DB検索 · 28万+工場DB · 匿名',
    featTabDesign: '設計',
    featTabAnalysis: '解析',
    featTabMfg: '製造',
    platformBadge1: '無料3D CAD',
    platformBadge2: 'FEA解析',
    platformBadge3: 'AI最適化',
    platformBadge4: 'メーカーマッチング',

    featKicker: 'NexyFab · Capabilities.',
    featTitle: 'エンジニアのためのオールインワンツール',
    featSub: 'ブラウザで設計 → 見積もり → 韓国パートナー発注まで一本道。OpenSCAD連携・協業対応・インストール不要。',
    feat1Title: 'パラメトリック3D CAD',
    feat1Desc: '16種類の形状、スケッチ→押し出し、フィレット、面取り、パターンなどプロフェッショナル機能。',
    feat2Title: '構造解析（FEA）',
    feat2Desc: '応力、変位、安全係数をシミュレーションして設計を検証。',
    feat3Title: 'トポロジー最適化',
    feat3Desc: 'SIMPアルゴリズムで強度を維持しながら材料を最大40%削減する最適構造を生成。',
    feat4Title: 'モーダル＆熱解析',
    feat4Desc: '固有振動数解析と熱伝達シミュレーションで動的/熱的安定性を確認。',
    feat5Title: 'DFM分析',
    feat5Desc: '製造可能性を自動分析、壁厚・穴径・抜き勾配・フィレット半径・縦横比を事前検査。',
    feat6Title: '自動図面＆見積もり',
    feat6Desc: '2D図面自動生成、コスト算出、メーカーマッチングまでワンクリック。',

    wfKicker: 'NexyFab · Workflow.',
    wfTitle: '設計から製造まで5ステップ',
    wfSub: 'アイデアから実際の部品まで、ひとつのプラットフォームで完結。',
    wf1Title: '設計',
    wf1Desc: 'ブラウザでパラメトリック3Dモデリング',
    wf2Title: '解析',
    wf2Desc: 'FEA・熱解析・モーダル解析で検証',
    wf3Title: '最適化',
    wf3Desc: 'トポロジー最適化＆DFMチェック',
    wf4Title: '見積もり',
    wf4Desc: '予想コスト算出＆メーカー比較',
    wf5Title: '製造',
    wf5Desc: '工場DB検索で最適メーカーに接続',

    personaKicker: 'NexyFab · For You.',
    personaTitle: 'どなた向けのプラットフォーム？',
    persona1Title: '設計エンジニア',
    persona1Desc: 'ブラウザ完結のパラメトリックCAD + OpenSCADコード双方向。標準部品設計と図面出力に最適。',
    persona1Cta: '3D設計を開始',
    persona2Title: '購買担当者',
    persona2Desc: '図面アップロード→即時コスト見積もり。韓中工場DBから候補をご提案。',
    persona2Cta: '見積もり依頼',
    persona3Title: 'スタートアップ',
    persona3Desc: 'アイデアを試作品に。無料CAD＋少量生産見積もりをまとめて。',
    persona3Cta: '無料で開始',

    ctaKicker: 'Nexyfab · Get Started.',
    ctaTitle: '今すぐプロジェクトを始めましょうか？',
    ctaSub: '短いキーワード1行で十分です。<br/>内部検討後、最適なパートナーと接続します。',
    ctaBtn1: 'プロジェクトお問い合わせ',
    ctaBtn2: 'キーワード検索',

    onboardingTitle: 'どの作業をしますか？',
    onboardingSub: '目的に合ったページへご案内します。',
    onboardingPath1: '3D設計を始める',
    onboardingPath1Desc: 'ブラウザでCAD設計・解析・最適化',
    onboardingPath2: '製造問い合わせ',
    onboardingPath2Desc: '図面アップロード・見積比較・メーカーマッチング',
    onboardingPath3: 'パートナー検索',
    onboardingPath3Desc: 'キーワードで最適なメーカーを検索',
    onboardingSkip: 'スキップ',
    howPage: {
        heroTitle: 'How we Work',
        heroSub: '検索から接続まで、厳選パートナー候補リストと<br/>客観的データを居に、設計から量産まで進めましょう。',
        step1Tag: 'Step 1',
        step1Title: 'AI精密分析 (Smart Analysis)',
        step1Desc: 'プロジェクトキーワードに基づき、製造の観点から必要な工程構造と技術範囲を整理します。マッチングのための分析基準はこの段階で定義されます。<br/><br/><strong style="color:#0b5cff;">[Input] プロジェクトキーワード → [Output] マッチング基準および技術範囲の導出</strong>',
        step2Tag: 'Step 2',
        step2Title: 'グローバルDBマッチング (Global DB Matching)',
        step2Desc: '韓国と中国の製造DBに基づき、保有設備・類似リファレンス・工程適合度を総合的に分析し、優先検討対象のパートナーを厳選します。<br/><br/><strong style="color:#0b5cff;">[Input] 分析基準 → [Output] 適合候補3〜5社および推薦根拠</strong>',
        step3Tag: 'Step 3',
        step3Title: '接続および連携サポート (Connection & Support)',
        step3Desc: '選定されたパートナーの遂行履歴と能力情報を確認した後、プラットフォームを通じてのお問い合わせ・見積・発注のプロセスをサポートします。<br/><br/><strong style="color:#0b5cff;">[Input] 候補選択 → [Output] 匿名マッチングおよび連携の進行</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* 選定基準：類似リファレンス / 保有設備 / 品質関連認証の有無</span>',
        whyTitle: '技術的な差別化 (Why us?)',
        why1Title: 'データに基づくマッチング根拠',
        why1Desc: '単なる検索結果ではなく、保有設備・類似プロジェクトの遂行 이력・工程範囲に基づき、推薦理由を客観的なデータとして提供します。',
        diagramTitle: '韓中製造ワークフロー',
        diagramStep1: 'AIスマート分析',
        diagramStep1Sub: 'スペック自動整理',
        diagramStep2: 'グローバルDBマッチング',
        diagramStep2Sub: '上位3〜5社推薦',
        diagramStep3: '匿名コネクション',
        diagramStep3Sub: '紹介＋匿名マッチング',
        why2Title: '韓中統合製造DB',
        why2Desc: '韓国と中国の製造インフラを統合したDBに基づき、技術理解に基づいたマッチングをサポートします。単なる仲介ではなく、開発の観点が反映された連携が強みです。',
        why3Title: '品質基準情報の提供 (Q/C)',
        why3Desc: 'パートナーの保有設備、品質認証の有無、遂行履歴などの情報を事前検討基準として提供します。<br/>※ただし、Nexyfabを通さない生産品質に関する最終的な責任は、契約当事者間に帰属します。',
        why4Title: '依頼者の匿名マッチング',
        why4Desc: '初期マッチング段階では、依頼者の会社名はパートナーに開示されません。双方の同意後にのみ相互情報が共有されます。',
        statsTitle: '製造の悩みを描いたデータで解決',
        statsSub: '韓国と中国の統合製造DBと蓄積されたリファレンスで最適なマッチングをお約束します。',
        statsFactories: '286,000+',
        statsFactoriesLabel: '工場データベース (DB)',
        statsRefs: '6,000+',
        statsRefsLabel: '韓中工場DB',
        casePrompt: 'デモモードで実際のマッチングフローを体験してみてください。',
        caseBtn: 'デモモード体験',
        ssTitle: '活用シナリオ',
        ssRef1: '精密加工部品 (CNC・板金) マッチング',
        ssRef2: '少量多品種試作生産',
    },
};
