export const ko = {
    heroKicker: 'Nexyfab · 제조사 찾기.',
    heroTitle: '최적의 개발 파트너를<br/>검색해보세요',
    heroSub: '제품 키워드만 입력하면<br/>검증된 한·중 공장 DB에서 매칭합니다.',
    searchPlaceholder: '예: 배터리 자동화 설비',
    placeholderList: ['배터리 자동화 설비', '식품 생산 설비', '정밀 부품 가공', '물류 이송 시스템', '반도체 세정 장비'],
    searchBtn: '검색',
    searching: '검색 중...',
    searchingSub: '(약 30초 이내)',
    manufacturer: '제조사',
    industry: '업종',
    score: '적합도',
    contactTitle: '📨 연락처 입력',
    contactCompany: '이름(회사명)',
    contactPhone: '연락처',
    contactEmail: '이메일',
    contactSubmit: '문의하기',
    tabKoFactories: '한국 등록공장',
    tabCnFactories: '중국 공장',
    noKoResults: '일치하는 한국 공장이 없습니다.',
    noCnResults: '일치하는 중국 공장이 없습니다.',
    applyDashboard: '대시보드에서 바로 신청하기',
    loginApply: '로그인해서 신청하기',
    applyDesc: 'AI RFP 자동생성 · 견적 비교 · 전담 지원',
    gotoDashboard: '신청하기 →',
    signIn: '로그인 →',
    orDirectContact: '또는 직접 문의',
    statCount: '30만+',
    formSubmitting: '처리 중...',
    alertSuccess: '문의가 성공적으로 전달되었습니다.',
    alertError: '오류가 발생했습니다. 나중에 다시 시도해 주세요.',
    totalResults: '전체',
    contactGuide: '* 이름(회사명), 연락처, 이메일은 필수 입력 항목입니다.',
    statKr: '한국/중국 공장',
    statRef: '협력사 누적 레퍼런스',
    heroNote: '* 실제 회사명은 고객 화면에 노출되지 않으며,<br/>문의 제출 시 내부 확인용으로만 전달됩니다.',

    howKicker: 'Nexyfab · How it Works.',
    howTitle: '키워드 입력부터 연결까지',
    howSub: '검색 → 분석 → 선별 → 연결 → 실제 프로젝트 진행',
    step1Title: '요구사항 입력',
    step1Desc: '요구사항을 키워드로 입력하면 분석 기준이 생성됩니다.',
    step1Tag1: '배터리 자동화 설비', step1Tag2: '특수목적 장비', step1Tag3: '공정 개선',
    step2Title: 'DB 검색',
    step2Desc: '키워드를 해석하고 유사 레퍼런스/제조 역량 데이터를 기반으로 후보군을 정리합니다.',
    step2List1: '의미 확장(동의어/유사 카테고리)',
    step2List2: '유사 레퍼런스 기반 적합도 산출',
    step2List3: '업종/설비/공정 조건 필터링',
    step3Title: '적합 파트너 선별',
    step3Desc: '"가능한 곳"이 아니라 "가장 적합한 곳"을 우선 검토 후보로 압축합니다.',
    step3List1: '기술 난이도/분야 매칭',
    step3List2: '수행 범위 및 신뢰도 반영',
    step3List3: '중복·부적합 후보 제외',
    step4Title: '문의 연결',
    step4Desc: '프로젝트 정보는 외부에 공개되지 않으며, 내부 검토 후 필요한 범위에서 연결됩니다.',
    step4Note: '* 실제 회사명은 고객 화면에 노출되지 않으며 내부 확인용으로만 전달됩니다.',
    howBottomTitle: '키워드 검색부터 시작하세요.',
    howBottomSub: '짧은 키워드만으로도 시작할 수 있어요.',
    howBottomBtn: '키워드 검색',

    whyKicker: 'Nexyfab · Why.',
    whyTitle: '"연결"의 기준이 다릅니다',
    whySub: '단순한 매칭이 아닌, 실제 수행 가능성과 적합성을 기준으로 매칭합니다.',
    why1Title: '무작위 견적 요청이 아닙니다',
    why1Desc: '요구사항에 부합하는 적격 후보만 선별하여 전달하므로 소통 비용이 절감됩니다.',
    why2Title: '데이터 기반 필터링',
    why2Desc: '단순 키워드를 넘어 유사 레퍼런스 및 업종/설비/공정 조건을 모두 반영합니다.',
    why3Title: '프로젝트 정보 비공개 원칙',
    why3Desc: '실제 회사명은 고객에게 노출되지 않으며, 내부 검토 및 연결을 위해서만 제한적으로 사용됩니다.',
    why4Title: '의사결정까지 빠르게',
    why4Desc: '"가능할 수도 있는 목록"이 아닌, "가장 먼저 검토해야 할 적합 후보군"으로 압축합니다.',
    whyCtaTitle: '지금 바로 매칭을 시작해볼까요?',
    whyCtaBtn: '프로젝트 문의',

    caseKicker: 'Nexyfab · Use Cases.',
    caseTitle: '이런 프로젝트에 강합니다',
    caseSub: '실제 기업/고객명은 노출하지 않고,<br/>오직 <b>프로젝트 유형</b>을 기준으로 예시를 제공합니다.',
    case1Title: '자동화 설비',
    case1Desc: '공정 조건/레이아웃/안전 요구사항등을 반영하여 최적의 자동화 파트너를 선별합니다.',
    case1Tag1: '조립/검사', case1Tag2: '물류/이송', case1Tag3: '라인 증설',
    case1Pill1: '유사 사례', case1Pill2: '제조/자동화',
    case2Title: '특수 목적 장비',
    case2Desc: '특수 장비는 "제조 가능성"이 핵심이므로, 유사레퍼런스를 최우선으로 검토합니다.',
    case2Tag1: '지그/툴', case2Tag2: '정밀 구동', case2Tag3: '특수 사양',
    case2Pill1: '유사 사례', case2Pill2: '특수 장비',
    case3Title: 'R&D 시제품',
    case3Desc: '유사 레퍼런스와 기술 범위를 기반으로 실제 구현 가능성이 높은 제조 파트너만 압축합니다.',
    case3Tag1: 'PoC', case3Tag2: '프로토타입', case3Tag3: '성능 검증',
    case3Pill1: '유사 사례', case3Pill2: 'R&D',
    case4Title: '플랜트/설비',
    case4Desc: '규모가 큰 플랜트 설비의 경우 유사성, 안전성, 납기를 기준으로 빠르게 연계합니다.',
    case4Tag1: '유사성', case4Tag2: '정밀도', case4Tag3: '안전/규제',
    case4Pill1: '유사 사례', case4Pill2: '플랜트',
    caseNoteTitle: '기업명/프로젝트명은 외부에 노출되지 않습니다.',
    caseNoteSub: '구체적인 정보는 진행 단계에 맞춰 요청하며,<br/>내부 검토 후 적합 파트너에게만 제한적으로 공유됩니다.',

    revenueKicker: 'Nexyfab · Revenue Model.',
    revenueTitle: '업계 최저 수수료 4%에 도전하다, Nexyfab 책임 매칭 시스템',
    revenueSub: '문의부터 설계·양산 착수까지, 최종 수수료는 견적의 4~7%(VAT 별도)만 부담합니다.',
    revenueStep1Title: 'Step 1. 매칭 신청금',
    revenueStep1Price: '50만 원 (VAT 별도)',
    revenueStep1Value: '기술 검토 및 파트너 선별 (실패 시 결제 금액 환불)',
    revenueStep1Desc: '단순 연결을 넘어 전문 기술 검토를 통해 최적의 제조사를 선별합니다. 적합한 파트너를 찾지 못할 경우 결제하신 금액을 환불해 드리는 No-Risk 정책을 운영합니다.',
    revenueStep2Title: 'Step 2. 계약 체결 및 수수료 정산',
    revenueStep2Rate: '기본 수수료 4~7%',
    revenueStep2Value: '계약 체결 시 (Step 1 신청금 100% 공제)',
    revenueStep2Desc: '파트너 매칭 후 계약 체결 시 기본 수수료(4~7%, VAT 별도)를 정산합니다. Step 1 신청금은 수수료에서 100% 공제됩니다.',
    revenueStep3Title: 'Step 3. 설계·양산 착수 및 납품 관리',
    revenueStep3Reward: '납품 완료까지 책임 관리',
    revenueStep3Value: '설계부터 납품까지 전담 오퍼레이터 밀착 지원',
    revenueStep3Desc: '계약 체결 이후 설계 착수부터 납품 완료까지 전담 오퍼레이터가 일정 관리, 품질 확인, 이슈 대응 등 원활한 진행을 위해 파트너사와 함께 도움을 드립니다.',
    revenueFooterNote1: '',
    revenueFooterNote2: '',
    revenueFooterNote3: '* 최소 수수료는 50만 원(Step 1 비용, VAT 별도)으로 설정됩니다.',
    revenueFooterNote4: '* 수수료 및 위약금에 대한 상세 정책은 서비스 이용약관을 확인해 주세요.',
    revenueFlow1: '50만원 매칭 신청금',
    revenueFlow2: '계약 체결 시 수수료 정산',
    revenueFlow3: '설계·양산 착수 및 납품 관리',

    platformKicker: 'NexyFab · Design to Manufacturing.',
    platformTitle: '설계부터 제조까지,\n하나의 플랫폼에서',
    platformSub: 'AI로 아이디어를 즉시 3D 설계로 구현하고, 브라우저에서 구조 해석과 위상 최적화까지.\n설계가 끝나면 AI가 30만+ 공장 DB를 탐색하여 최적의 제조사를 찾아 매칭해 드립니다.',
    platformCta1: '3D 설계 시작하기',
    platformCta2: '제조사 매칭 받기',
    factories: '공장 DB 검색',
    platformMicro: '무료 · 가입 불필요 · 브라우저에서 바로 시작',
    platformDemoMigrate: '💾 가입 전 작업은 계정 생성 시 자동으로 이관됩니다',
    platformSearchPlaceholder: '제조사 바로 검색해보세요',
    platformSearchBtn: '검색',
    socialStat1: '300,000+',
    socialStat1Label: '한·중 공장 DB',
    socialStat2: '16종',
    socialStat2Label: '3D 형상 라이브러리',
    socialStat3: '무료',
    socialStat3Label: '기본 플랜 제공',
    wf1Hint: '파라메트릭 3D CAD · 16개 형상 · 스케치→돌출',
    wf2Hint: 'FEA 구조 해석 · 모달 분석 · 열전달 시뮬레이션',
    wf3Hint: 'SIMP 위상 최적화 · DFM 체크 · 경량화',
    wf4Hint: '자동 2D 도면 · 비용 산출 · 제조사 비교',
    wf5Hint: '공장 검색 · 30만+ 공장 DB · 회사명 비공개 매칭',
    featTabDesign: '설계',
    featTabAnalysis: '해석',
    featTabMfg: '제조',
    platformBadge1: '무료 3D CAD',
    platformBadge2: 'FEA 해석',
    platformBadge3: 'AI 최적화',
    platformBadge4: '제조사 매칭',

    featKicker: 'NexyFab · Capabilities.',
    featTitle: '엔지니어를 위한 올인원 도구',
    featSub: '브라우저에서 설계 → 견적 → 한국 파트너 발주까지 한 사슬. OpenSCAD 친화 · 협업 가능 · 설치 불필요.',
    feat1Title: '파라메트릭 3D CAD',
    feat1Desc: '16가지 형상, 스케치 → 돌출, 필렛, 챔퍼, 패턴 등 전문 피처로 부품을 설계하세요.',
    feat2Title: '구조 해석 (FEA)',
    feat2Desc: '응력, 변위, 안전 계수를 시뮬레이션하여 설계 검증을 수행합니다.',
    feat3Title: '위상 최적화',
    feat3Desc: 'SIMP 알고리즘으로 강도를 유지하면서 재료를 최대 40% 절감하는 최적 구조를 생성합니다.',
    feat4Title: '모달 & 열해석',
    feat4Desc: '고유진동수 분석과 열전달 시뮬레이션으로 동적/열적 안정성을 확인합니다.',
    feat5Title: 'DFM 분석',
    feat5Desc: '제조 가능성을 자동 분석하고, 벽 두께·구멍 직경·드래프트 각도·필렛 반지름·종횡비를 사전 검사합니다.',
    feat6Title: '자동 도면 & 견적',
    feat6Desc: '2D 도면 자동 생성, 비용 산출, 제조사 매칭까지 원클릭으로 완료합니다.',

    wfKicker: 'NexyFab · Workflow.',
    wfTitle: '설계에서 제조까지 5단계',
    wfSub: '아이디어가 실제 부품이 되기까지, 하나의 플랫폼에서 끝냅니다.',
    wf1Title: '설계',
    wf1Desc: '브라우저에서 파라메트릭 3D 모델링',
    wf2Title: '해석',
    wf2Desc: 'FEA, 열해석, 모달 분석으로 검증',
    wf3Title: '최적화',
    wf3Desc: '위상 최적화로 경량화 & DFM 체크',
    wf4Title: '견적',
    wf4Desc: '예상 비용 산출 & 제조사 비교',
    wf5Title: '제조',
    wf5Desc: '공장 DB 검색으로 최적 제조사 연결',

    personaKicker: 'NexyFab · For You.',
    personaTitle: '누구를 위한 플랫폼인가요?',
    persona1Title: '설계 엔지니어',
    persona1Desc: '브라우저 기반 파라메트릭 CAD + OpenSCAD 코드 양방향. 표준 부품 설계와 도면 출력에 최적화.',
    persona1Cta: '3D 설계 시작',
    persona2Title: '구매 담당자',
    persona2Desc: '도면 업로드 → 즉시 견적 비교. 검증된 제조사만 추천합니다.',
    persona2Cta: '견적 요청',
    persona3Title: '스타트업 / 메이커',
    persona3Desc: '아이디어를 시제품으로. 무료 CAD + 소량 생산 견적을 한 번에.',
    persona3Cta: '무료로 시작',

    ctaKicker: 'Nexyfab · Get Started.',
    ctaTitle: '이제 프로젝트를 시작해볼까요?',
    ctaSub: '짧은 키워드 한 줄이면 충분합니다.<br/>내부 검토 후 가장 적합한 파트너와 연결해 드립니다.',
    ctaBtn1: '프로젝트 문의',
    ctaBtn2: '키워드 검색',

    onboardingTitle: '어떤 작업을 하시나요?',
    onboardingSub: '목적에 맞는 경로로 바로 안내해 드릴게요.',
    onboardingPath1: '3D 설계 시작',
    onboardingPath1Desc: '브라우저에서 바로 CAD 설계 · 해석 · 최적화',
    onboardingPath2: '제조 문의',
    onboardingPath2Desc: '도면 업로드 · 견적 비교 · 제조사 매칭',
    onboardingPath3: '파트너 찾기',
    onboardingPath3Desc: '키워드로 최적의 제조사를 검색',
    onboardingSkip: '건너뛰기',
    howPage: {
        heroTitle: 'How we Work',
        heroSub: '키워드 검색부터 납품까지, 전문 기술 검토와 데이터 기반 매칭으로<br/>최적의 제조 파트너를 찾아드립니다.',
        step1Tag: 'Step 1',
        step1Title: 'AI 정밀 분석 (Smart Analysis)',
        step1Desc: '프로젝트 키워드를 기반으로 제조 관점에서 필요한 공정 구조와 기술 범위를 정리합니다. 매칭을 위한 분석 기준이 이 단계에서 정의됩니다.<br/><br/><strong style="color:#0b5cff;">[Input] 프로젝트 키워드 → [Output] 매칭 기준 및 기술 범위 도출</strong>',
        step2Tag: 'Step 2',
        step2Title: '글로벌 DB 매칭 (Global DB Matching)',
        step2Desc: '한국과 중국의 제조 DB를 기반으로, 보유 설비·유사 레퍼런스·공정 적합도를 종합 분석하여 우선 검토 대상 파트너를 압축합니다.<br/><br/><strong style="color:#0b5cff;">[Input] 분석 기준 → [Output] 적합 후보 3~5곳 및 추천 및 근거</strong>',
        step3Tag: 'Step 3',
        step3Title: '연결 및 협업 지원 (Connection & Support)',
        step3Desc: '선별된 파트너의 수행 이력과 역량 정보를 확인한 후, 플랫폼을 통해 문의·견적·발주 과정을 지원합니다.<br/><br/><strong style="color:#0b5cff;">[Input] 후보 선택 → [Output] 익명 매칭 및 협업 진행</strong><br/><span style="color:#64748b;font-size:14px;display:inline-block;margin-top:4px;">* 선별 기준: 유사 레퍼런스 / 보유 설비 / 품질 관련 인증 보유 여부</span>',
        whyTitle: '기술적 차별점 (Why us?)',
        why1Title: '데이터 기반 매칭 근거',
        why1Desc: '단순 검색 결과가 아닌, 보유 설비·유사 프로젝트 수행 이력·공정 범위를 기반으로 추천 사유를 객관적 데이터로 제공합니다.',
        diagramTitle: '한·중 제조 워크플로우',
        diagramStep1: 'AI 스마트 분석',
        diagramStep1Sub: '요구스펙 자동 도출',
        diagramStep2: '글로벌 DB 매칭',
        diagramStep2Sub: 'Top 3~5 파트너 추천',
        diagramStep3: '검증된 연결',
        diagramStep3Sub: '소개 + 익명 매칭',
        why2Title: '한·중 통합 제조 DB',
        why2Desc: '한국과 중국 제조 인프라를 통합한 DB를 기반으로, 기술 이해를 바탕으로 한 매칭을 지원합니다. 단순 중개가 아닌, 개발 관점이 반영된 연결이 강점입니다.',
        why3Title: '품질 기준 정보 제공 (Q/C)',
        why3Desc: '파트너의 보유 설비, 품질 인증 여부, 수행 이력 등의 정보를 사전 검토 기준으로 제공합니다.<br/>※ 단. 넥시팹를 통하지 않은 생산 품질에 대한 최종 책임은 계약 당사자 간에 귀속됩니다.',
        why4Title: '회사명 비공개 매칭',
        why4Desc: '초기 매칭 단계에서 의뢰자 회사명은 파트너에게 노출되지 않습니다. 양측이 합의한 이후에만 상호 정보가 공유됩니다.',
        statsTitle: '제조의 고민, 데이터로 해답을 찾다',
        statsSub: '한국과 중국의 통합 제조 DB와 축적된 레퍼런스로 최적의 매칭을 약속합니다.',
        statsFactories: '300,000+',
        statsFactoriesLabel: '공장 데이터베이스 (DB)',
        statsRefs: '6,000+',
        statsRefsLabel: '검증 인증 보유 파트너',
        casePrompt: '데모 모드에서 실제 매칭 흐름을 직접 체험해 보세요.',
        caseBtn: '데모 모드 체험',
        ssTitle: '플랫폼 활용 시나리오',
        ssRef1: '정밀 가공 부품 (CNC·판금) 매칭',
        ssRef2: '소량 다품종 시제품 제작',
    },
};
