import { NextRequest, NextResponse } from 'next/server'; import { verifyRobotPostIntegrationEvidence } from '@/lib/ai/robot/robotPostIntegrationEvidence'; import type { RobotCadIntegrationPacket } from '@/lib/ai/robot/robotCadIntegrationPacket'; import type { RobotCadIntegrationReview } from '@/lib/ai/robot/robotCadIntegrationReview'; import { parseTrustedReviewerKeys } from '@/lib/reference/nativeCadExpertReview'; import { getTrustedClientIp } from '@/lib/client-ip'; import { rateLimitAsync } from '@/lib/rate-limit';
export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
export async function POST(req: NextRequest) {
  const ip = getTrustedClientIp(req.headers); if (!(await rateLimitAsync(`cad-v1-robot-integration-post-verify:${ip}`, 5, 60_000)).allowed) return NextResponse.json({ ok: false, code: 'RATE_LIMIT' }, { status: 429 });
  const form = await req.formData().catch(() => null); const keys = ['program', 'revision', 'preciseReport', 'receipt', 'packet', 'review', 'housing', 'requirements', 'manifest'] as const; const values = Object.fromEntries(keys.map(key => [key, form?.get(key)])) as Record<(typeof keys)[number], FormDataEntryValue | null | undefined>; const artifacts = form?.getAll('artifact') ?? [];
  if (keys.some(key => !(values[key] instanceof File)) || artifacts.length < 1 || artifacts.some(item => !(item instanceof File))) return NextResponse.json({ ok: false, code: 'BAD_REQUEST', message: `${keys.join(', ')} and artifact files are required` }, { status: 400 });
  const filesByKey = values as unknown as Record<(typeof keys)[number], File>, artifactsFiles = artifacts as File[], total = artifactsFiles.reduce((sum, file) => sum + file.size, 0);
  if (filesByKey.program.size < 1 || filesByKey.program.size > 50_000_000 || filesByKey.preciseReport.size < 1 || filesByKey.preciseReport.size > 5_000_000 || filesByKey.packet.size < 1 || filesByKey.packet.size > 5_000_000 || ['revision', 'receipt', 'review', 'housing', 'requirements'].some(key => { const file = filesByKey[key as keyof typeof filesByKey]; return file.size < 1 || file.size > 1_000_000; }) || filesByKey.manifest.size < 1 || filesByKey.manifest.size > 2_000_000 || artifactsFiles.length > 25 || artifactsFiles.some(file => file.size < 1 || file.size > 100_000_000) || total > 250_000_000) return NextResponse.json({ ok: false, code: 'TOO_LARGE' }, { status: 413 });
  try { const bytes = async (key: keyof typeof filesByKey) => new Uint8Array(await filesByKey[key].arrayBuffer()); const packet = parse(await filesByKey.packet.arrayBuffer(), 'packet') as RobotCadIntegrationPacket, review = parse(await filesByKey.review.arrayBuffer(), 'review') as RobotCadIntegrationReview; const report = await verifyRobotPostIntegrationEvidence({ programBytes: await bytes('program'), revisionManifestBytes: await bytes('revision'), preciseReportBytes: await bytes('preciseReport'), applicationReceiptBytes: await bytes('receipt'), packet, review, housingBytes: await bytes('housing'), requirementsBytes: await bytes('requirements'), catalogManifestBytes: await bytes('manifest'), artifacts: await Promise.all(artifactsFiles.map(async file => ({ name: file.name, bytes: new Uint8Array(await file.arrayBuffer()) }))), trustedKeys: parseTrustedReviewerKeys() }); return NextResponse.json({ ok: report.postIntegrationStatus === 'passed', report, releaseReady: false, cadModified: false, quoteOrRfqSideEffects: false }, { status: report.postIntegrationStatus === 'passed' ? 200 : 422 }); }
  catch (cause) { return NextResponse.json({ ok: false, code: 'INVALID_POST_INTEGRATION_EVIDENCE', message: cause instanceof Error ? cause.message : String(cause), releaseReady: false, cadModified: false, quoteOrRfqSideEffects: false }, { status: 422 }); }
}
function parse(bytes: ArrayBuffer, label: string) { const value = JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes)); if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error(`${label} must be a UTF-8 JSON object`); return value; }
