export const simDict = {
    ko: {
        pdfReport: 'PDF 리포트',
        excelReport: '엑셀 리포트',
        simulatorTitle: '글로벌 제조 시뮬레이터',
        simulatorSub: '글로벌 제조 원가 및 생산 전략 시뮬레이터',
        mobilePromptTitle: 'PC 버전으로 볼까요?',
        mobilePromptDesc: '제조 시뮬레이터는 넓은 화면에 최적화되어 있습니다. PC 버전으로 전환하면 더 많은 정보를 편하게 확인할 수 있습니다.',
        pcVersionBtn: 'PC 버전으로 보기',
        industryType: '산업 업종 (HS 2단위)',
        industryPlaceholder: '업종 검색 또는 직접 입력...',
        projectPlaceholder: '프로젝트명을 입력하세요...',
        volumePlaceholder: '수량 직접 입력',
        auto: '자동',
        landedCostLabel: 'LANDED COST (CERT/INV포함)',
        originLabel: 'ORIGIN (RVC%)',
        leadTimeLabel: 'LEAD TIME / LOGISTICS',
        edit: '편집',
        save: '저장',
        productTitle: '프로젝트 및 제품명 (Project Title)',
        scenarioSetup: '시나리오 변수 설정',
        assemblyHub: '제조 허브 (Assembly)',
        targetMarket: '타겟 마켓 (Target Market)',
        moq: '물동량 (MOQ)',
        autoDiscount: '자동 할인 적용',
        restoreDiscount: '자동 할인으로 복원',
        customDiscount: '직접 할인율 조정 (Overrides)',
        targetWeight: '단품 목표 중량',
        bomBuilder: 'BOM (자재 명세서) 빌더',
        aiReport: 'AI 분석 및 리포트 생성',
        saveScenario: '시나리오 데이터 저장',
        costStructure: '비용 원가 구조',
        savedScenarios: '저장된 시나리오',
        scenarioCompare: '시나리오 비교',
        bomCost: '자재비(BOM)',
        procCost: '가공비',
        fixedCost: '고정비',
        logisticsCost: '물류비(전체)',
        taxCost: '세금/관세(Tax)',
        freightMode: '물류 모드 (Freight Method)',
        totalContainerFreight: '총 컨테이너/기본 운임',
        weightFreight: '무게 비례 단가',
        expectedFreight: '개당 예상 운임 (순수 물류비)',
        supplyTimeline: '공급망 타임라인 (Supply Chain Timeline)',
        exwDetail: '제조 원가(EXW) 상세 산출 내역 예시',
        closeDetail: '상세 닫기',
        openDetail: '+ 상세 펼치기',
        bridges: '물류·조세·최종가 연결 (Bridge to Quote)',
        addMaterial: '+ 자재 추가',
        industryExample: '산업별 예시 템플릿 로드',
        aiSimReport: 'AI 시뮬레이션 통합 리포트',
        emptyScenario: '저장된 시나리오가 없습니다.',
        compareMode: '비교 모드',
        tablePart: '부품명',
        tableOrigin: '생산지',
        tablePrice: '원가',
        tableHs: 'HS Code',
        tableAction: '기능',
        popupBlocked: '팝업 차단을 해제해주셔야 리포트 출력이 가능합니다.',
        oldScenario: '이 시나리오는 상세 정보를 포함하고 있지 않습니다 (구버전 데이터).',
        maxScenario: '시나리오는 최대 3개까지만 비교 및 저장할 수 있습니다. 기존 시나리오를 삭제 후 추가해주세요.'
    },
    en: {
        pdfReport: 'PDF Report',
        excelReport: 'Excel Report',
        simulatorTitle: 'Global Manufacturing Simulator',
        simulatorSub: 'Global Manufacturing Cost & Strategy Simulator',
        mobilePromptTitle: 'Switch to PC Version?',
        mobilePromptDesc: 'The Manufacturing Simulator is optimized for large screens. Switching to the PC version allows you to view more information comfortably.',
        pcVersionBtn: 'View PC Version',
        industryType: 'Industry Category (HS 2-digit)',
        industryPlaceholder: 'Search industry or enter directly...',
        projectPlaceholder: 'Enter project title...',
        volumePlaceholder: 'Enter volume directly',
        auto: 'Auto',
        landedCostLabel: 'LANDED COST (Inc. CERT/INV)',
        originLabel: 'ORIGIN (RVC%)',
        leadTimeLabel: 'LEAD TIME / LOGISTICS',
        edit: 'Edit',
        save: 'Save',
        productTitle: 'Project & Product Title',
        scenarioSetup: 'Scenario Variables Setup',
        assemblyHub: 'Assembly Hub',
        targetMarket: 'Target Market',
        moq: 'Order Volume (MOQ)',
        autoDiscount: 'Auto Discount Applied',
        restoreDiscount: 'Restore Auto Discount',
        customDiscount: 'Custom Discount Overrides',
        targetWeight: 'Target Unit Weight',
        bomBuilder: 'BOM (Bill of Materials) Builder',
        aiReport: 'Generate AI Analysis & Report',
        saveScenario: 'Save Scenario Data',
        costStructure: 'Cost Structure',
        savedScenarios: 'Saved Scenarios',
        scenarioCompare: 'Scenario Comparison',
        bomCost: 'BOM Cost',
        procCost: 'Processing',
        fixedCost: 'Fixed Cost',
        logisticsCost: 'Logistics (Total)',
        taxCost: 'Taxes/Duties',
        freightMode: 'Freight Method',
        totalContainerFreight: 'Total Container/Base Freight',
        weightFreight: 'Weight-based Rate',
        expectedFreight: 'Expected Freight (Net per Unit)',
        supplyTimeline: 'Supply Chain Timeline',
        exwDetail: 'EXW Cost Breakdown Example',
        closeDetail: 'Close Details',
        openDetail: '+ Open Details',
        bridges: 'Logistics·Tax·Quote Bridge',
        addMaterial: '+ Add Material',
        industryExample: 'Load Industry Template',
        aiSimReport: 'AI Simulation Integrated Report',
        emptyScenario: 'No saved scenarios.',
        compareMode: 'Compare Mode',
        tablePart: 'Part Name',
        tableOrigin: 'Origin',
        tablePrice: 'Price',
        tableHs: 'HS Code',
        tableAction: 'Action',
        popupBlocked: 'Please disable the popup blocker to export the report.',
        oldScenario: 'This scenario does not contain detailed information (legacy data).',
        maxScenario: 'You can save and compare up to 3 scenarios. Please delete an existing scenario before adding a new one.'
    },
    ja: {
        pdfReport: 'PDFレポート',
        excelReport: 'Excelレポート',
        simulatorTitle: 'グローバル製造シミュレーター',
        simulatorSub: 'グローバル製造原価および生産戦略シミュレーター',
        mobilePromptTitle: 'PC版で表示しますか？',
        mobilePromptDesc: '製造シミュレーターは広い画面に最適化されています。PC版に切り替えると、より多くの情報を快適に確認できます。',
        pcVersionBtn: 'PC版で表示',
        industryType: '産業業種 (HS 2桁)',
        industryPlaceholder: '業種検索または直接入力...',
        projectPlaceholder: 'プロジェクト名を入力してください...',
        volumePlaceholder: '数量を直接入力',
        auto: '自動',
        landedCostLabel: '着地原価 (LANDED COST)',
        originLabel: '原産地 (RVC%)',
        leadTimeLabel: 'リードタイム / 物流',
        edit: '編集',
        save: '保存',
        productTitle: 'プロジェクトおよび製品名',
        scenarioSetup: 'シナリオ変数設定',
        assemblyHub: '製造ハブ (Assembly)',
        targetMarket: 'ターゲット市場',
        moq: '発注量 (MOQ)',
        autoDiscount: '自動割引適用',
        restoreDiscount: '自動割引に戻す',
        customDiscount: 'カスタム割引調整',
        targetWeight: '単一目標重量',
        bomBuilder: 'BOM（部品表）ビルダー',
        aiReport: 'AI分析＆レポート生成',
        saveScenario: 'シナリオデータ保存',
        costStructure: '原価構造',
        savedScenarios: '保存済みシナリオ',
        scenarioCompare: 'シナリオ比較',
        bomCost: '資材費(BOM)',
        procCost: '加工費',
        fixedCost: '固定費',
        logisticsCost: '物流費(全体)',
        taxCost: '税金・関税',
        freightMode: '物流モード (Freight Method)',
        totalContainerFreight: 'コンテナ総運賃/基本運賃',
        weightFreight: '重量比例単価',
        expectedFreight: '予想運賃(単価)',
        supplyTimeline: 'サプライチェーンタイムライン',
        exwDetail: '製造原価(EXW)詳細計算例',
        closeDetail: '詳細を閉じる',
        openDetail: '+ 詳細を開く',
        bridges: '物流・税制・最終価格構成(Bridge)',
        addMaterial: '+ 資材追加',
        industryExample: '業界別テンプレート読込',
        aiSimReport: 'AIシミュレーション統合レポート',
        emptyScenario: '保存されたシナリオがありません。',
        compareMode: '比較モード',
        tablePart: '部品名',
        tableOrigin: '生産地',
        tablePrice: '原価',
        tableHs: 'HS Code',
        tableAction: 'アクション',
        popupBlocked: 'ポップアップブロックを解除してレポートを出力してください。',
        oldScenario: 'このシナリオには詳細情報が含まれていません（旧バージョンデータ）。',
        maxScenario: 'シナリオは最大3件まで比較・保存できます。既存のシナリオを削除してから追加してください。'
    },
    cn: {
        pdfReport: 'PDF报告',
        excelReport: 'Excel报告',
        simulatorTitle: '全球制造模拟器',
        simulatorSub: '全球制造成本与生产战略模拟器',
        mobilePromptTitle: '切换到电脑版？',
        mobilePromptDesc: '制造模拟器已针对大屏幕进行优化。切换到电脑版可以更方便地查看更多信息。',
        pcVersionBtn: '查看电脑版',
        industryType: '工业行业 (HS 2位)',
        industryPlaceholder: '搜索行业或直接输入...',
        projectPlaceholder: '请输入项目名称...',
        volumePlaceholder: '直接输入数量',
        auto: '自动',
        landedCostLabel: '落地成本 (LANDED COST)',
        originLabel: '原产地 (RVC%)',
        leadTimeLabel: '交期 / 物流',
        edit: '编辑',
        save: '保存',
        productTitle: '项目及产品名称',
        scenarioSetup: '方案变量设置',
        assemblyHub: '制造中心 (Assembly)',
        targetMarket: '目标市场',
        moq: '订单量 (MOQ)',
        autoDiscount: '已应用自动折扣',
        restoreDiscount: '恢复自动折扣',
        customDiscount: '自定义折扣调整',
        targetWeight: '单件目标重量',
        bomBuilder: 'BOM（物料清单）构建器',
        aiReport: '生成AI分析及报告',
        saveScenario: '保存方案数据',
        costStructure: '成本结构',
        savedScenarios: '已保存方案',
        scenarioCompare: '方案比较',
        bomCost: '物料费(BOM)',
        procCost: '加工费',
        fixedCost: '固定费',
        logisticsCost: '物流费(总计)',
        taxCost: '税金/关税',
        freightMode: '物流方式 (Freight Method)',
        totalContainerFreight: '集装箱总运费/基础运费',
        weightFreight: '重量比例单价',
        expectedFreight: '预计运费(单件净物流)',
        supplyTimeline: '供应链时间轴',
        exwDetail: '制造成本(EXW)详细明细示例',
        closeDetail: '收起详情',
        openDetail: '+ 展开详情',
        bridges: '物流·税金·最终报价桥接',
        addMaterial: '+ 添加物料',
        industryExample: '加载行业模板',
        aiSimReport: 'AI模拟综合报告',
        emptyScenario: '暂无保存的方案。',
        compareMode: '对比模式',
        tablePart: '部件名',
        tableOrigin: '原产地',
        tablePrice: '成本',
        tableHs: 'HS Code',
        tableAction: '操作',
        popupBlocked: '请关闭弹窗拦截器以导出报告。',
        oldScenario: '该方案不包含详细信息（旧版数据）。',
        maxScenario: '最多只能比较和保存3个方案。请删除现有方案后再添加。'
    },
    es: {
        pdfReport: 'Informe PDF',
        excelReport: 'Informe Excel',
        simulatorTitle: 'Simulador de Manufactura Global',
        simulatorSub: 'Simulador de Costos de Manufactura Global y Estrategia de Producción',
        mobilePromptTitle: '¿Cambiar a la versión de PC?',
        mobilePromptDesc: 'El Simulador de Manufactura está optimizado para pantallas grandes. Al cambiar a la versión de PC podrá ver más información cómodamente.',
        pcVersionBtn: 'Ver versión de PC',
        industryType: 'Categoría Industrial (HS 2 dígitos)',
        industryPlaceholder: 'Buscar industria o ingresar directamente...',
        projectPlaceholder: 'Ingrese el título del proyecto...',
        volumePlaceholder: 'Ingresar volumen directamente',
        auto: 'Auto',
        landedCostLabel: 'COSTO PUESTO EN DESTINO (Inc. CERT/INV)',
        originLabel: 'ORIGEN (RVC%)',
        leadTimeLabel: 'TIEMPO DE ENTREGA / LOGÍSTICA',
        edit: 'Editar',
        save: 'Guardar',
        productTitle: 'Título del Proyecto y Producto',
        scenarioSetup: 'Configuración de Variables del Escenario',
        assemblyHub: 'Centro de Ensamblaje',
        targetMarket: 'Mercado Objetivo',
        moq: 'Volumen de Pedido (MOQ)',
        autoDiscount: 'Descuento Automático Aplicado',
        restoreDiscount: 'Restaurar Descuento Automático',
        customDiscount: 'Ajuste de Descuento Personalizado',
        targetWeight: 'Peso Objetivo por Unidad',
        bomBuilder: 'Constructor de BOM (Lista de Materiales)',
        aiReport: 'Generar Análisis y Reporte con IA',
        saveScenario: 'Guardar Datos del Escenario',
        costStructure: 'Estructura de Costos',
        savedScenarios: 'Escenarios Guardados',
        scenarioCompare: 'Comparación de Escenarios',
        bomCost: 'Costo de Materiales (BOM)',
        procCost: 'Procesamiento',
        fixedCost: 'Costo Fijo',
        logisticsCost: 'Logística (Total)',
        taxCost: 'Impuestos/Aranceles',
        freightMode: 'Método de Flete',
        totalContainerFreight: 'Flete Total de Contenedor/Base',
        weightFreight: 'Tarifa por Peso',
        expectedFreight: 'Flete Estimado (Neto por Unidad)',
        supplyTimeline: 'Línea de Tiempo de la Cadena de Suministro',
        exwDetail: 'Desglose de Costo de Fabricación (EXW)',
        closeDetail: 'Cerrar Detalles',
        openDetail: '+ Abrir Detalles',
        bridges: 'Puente Logística·Impuestos·Cotización',
        addMaterial: '+ Agregar Material',
        industryExample: 'Cargar Plantilla Industrial',
        aiSimReport: 'Reporte Integrado de Simulación IA',
        emptyScenario: 'No hay escenarios guardados.',
        compareMode: 'Modo Comparación',
        tablePart: 'Nombre de Pieza',
        tableOrigin: 'Origen',
        tablePrice: 'Precio',
        tableHs: 'Código HS',
        tableAction: 'Acción',
        popupBlocked: 'Por favor, desactive el bloqueador de ventanas emergentes para exportar el informe.',
        oldScenario: 'Este escenario no contiene información detallada (datos de versión anterior).',
        maxScenario: 'Puede guardar y comparar hasta 3 escenarios. Elimine un escenario existente antes de agregar uno nuevo.'
    },
    ar: {
        pdfReport: 'تقرير PDF',
        excelReport: 'تقرير Excel',
        simulatorTitle: 'محاكي التصنيع العالمي',
        simulatorSub: 'محاكي تكاليف التصنيع العالمي واستراتيجية الإنتاج',
        mobilePromptTitle: 'التبديل إلى إصدار الكمبيوتر؟',
        mobilePromptDesc: 'تم تحسين محاكي التصنيع للشاشات الكبيرة. التبديل إلى إصدار الكمبيوتر يتيح لك عرض المزيد من المعلومات بشكل مريح.',
        pcVersionBtn: 'عرض إصدار الكمبيوتر',
        industryType: 'فئة الصناعة (HS مكون من رقمين)',
        industryPlaceholder: 'البحث عن الصناعة أو الإدخال مباشرة...',
        projectPlaceholder: 'أدخل عنوان المشروع...',
        volumePlaceholder: 'إدخال الكمية مباشرة',
        auto: 'تلقائي',
        landedCostLabel: 'التكلفة الإجمالية (شاملة الشهادات/الفواتير)',
        originLabel: 'المنشأ (RVC%)',
        leadTimeLabel: 'وقت التسليم / اللوجستيات',
        edit: 'تعديل',
        save: 'حفظ',
        productTitle: 'عنوان المشروع والمنتج',
        scenarioSetup: 'إعداد متغيرات السيناريو',
        assemblyHub: 'مركز التجميع',
        targetMarket: 'السوق المستهدف',
        moq: 'حجم الطلب (MOQ)',
        autoDiscount: 'تم تطبيق الخصم التلقائي',
        restoreDiscount: 'استعادة الخصم التلقائي',
        customDiscount: 'تعديل الخصم المخصص',
        targetWeight: 'الوزن المستهدف للوحدة',
        bomBuilder: 'منشئ قائمة المواد (BOM)',
        aiReport: 'إنشاء تحليل وتقرير بالذكاء الاصطناعي',
        saveScenario: 'حفظ بيانات السيناريو',
        costStructure: 'هيكل التكاليف',
        savedScenarios: 'السيناريوهات المحفوظة',
        scenarioCompare: 'مقارنة السيناريوهات',
        bomCost: 'تكلفة المواد (BOM)',
        procCost: 'تكلفة المعالجة',
        fixedCost: 'التكلفة الثابتة',
        logisticsCost: 'اللوجستيات (الإجمالي)',
        taxCost: 'الضرائب/الرسوم الجمركية',
        freightMode: 'طريقة الشحن',
        totalContainerFreight: 'إجمالي شحن الحاوية/الشحن الأساسي',
        weightFreight: 'سعر الشحن حسب الوزن',
        expectedFreight: 'الشحن المتوقع (صافي لكل وحدة)',
        supplyTimeline: 'الجدول الزمني لسلسلة التوريد',
        exwDetail: 'تفصيل تكلفة التصنيع (EXW)',
        closeDetail: 'إغلاق التفاصيل',
        openDetail: '+ فتح التفاصيل',
        bridges: 'جسر اللوجستيات·الضرائب·التسعير',
        addMaterial: '+ إضافة مادة',
        industryExample: 'تحميل قالب صناعي',
        aiSimReport: 'تقرير محاكاة متكامل بالذكاء الاصطناعي',
        emptyScenario: 'لا توجد سيناريوهات محفوظة.',
        compareMode: 'وضع المقارنة',
        tablePart: 'اسم القطعة',
        tableOrigin: 'المنشأ',
        tablePrice: 'السعر',
        tableHs: 'رمز HS',
        tableAction: 'إجراء',
        popupBlocked: 'يرجى تعطيل حاجب النوافذ المنبثقة لتصدير التقرير.',
        oldScenario: 'هذا السيناريو لا يحتوي على معلومات تفصيلية (بيانات إصدار قديم).',
        maxScenario: 'يمكنك حفظ ومقارنة ما يصل إلى 3 سيناريوهات. يرجى حذف سيناريو موجود قبل إضافة سيناريو جديد.'
    }
};
