// @vitest-environment jsdom

/**
 * useActivityFeed.test.tsx — Wave 2 Phase 3 W7 Track Z7.
 *
 * Coverage:
 *  - returns empty log on first mount
 *  - append API writes via doc when bound
 *  - append API falls back to in-memory when no doc
 *  - subscribes to activity root → re-renders on Y.Array change
 *  - subscribes to sketches root → local-origin op generates entry
 *  - subscribes to tree root → array delta produces add/remove entries
 *  - filters out remote-origin updates (skip logging)
 *  - clearLocalView hides existing entries until next op
 *  - isReplicating true when bound to doc, false otherwise
 *  - disabled option short-circuits subscription
 *  - peer override applied as author of locally-logged ops
 *  - hook unsubscribes on unmount
 */

import 'fake-indexeddb/auto';
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { renderHook, act, cleanup } from '@testing-library/react';
import * as Y from 'yjs';

import { useActivityFeed } from '../useActivityFeed';
import {
  appendActivityToDoc,
  readActivityLog,
  ORIGIN_REMOTE_UPDATE,
  ORIGIN_LOCAL_UI,
} from '../ActivityFeedYjs';
import { applySketchOp } from '../sketchYjs';

beforeEach(() => {
  vi.useRealTimers();
});

afterEach(() => {
  cleanup();
});

describe('useActivityFeed · basics', () => {
  it('returns empty entries on first mount with no doc', () => {
    const { result } = renderHook(() => useActivityFeed({ disabled: true }));
    expect(result.current.entries).toEqual([]);
    expect(result.current.isReplicating).toBe(false);
  });

  it('isReplicating=true when doc is bound', () => {
    const doc = new Y.Doc();
    const { result } = renderHook(() => useActivityFeed({ doc }));
    expect(result.current.isReplicating).toBe(true);
  });

  it('isReplicating=false when explicit doc=null', () => {
    const { result } = renderHook(() => useActivityFeed({ doc: null }));
    expect(result.current.isReplicating).toBe(false);
  });

  it('disabled option short-circuits binding even when doc supplied', () => {
    const doc = new Y.Doc();
    const { result } = renderHook(() => useActivityFeed({ doc, disabled: true }));
    expect(result.current.isReplicating).toBe(false);
  });
});

describe('useActivityFeed · append', () => {
  it('writes via doc when bound', () => {
    const doc = new Y.Doc();
    const { result } = renderHook(() =>
      useActivityFeed({
        doc,
        peer: { id: 'peer-x', name: 'Xavier', color: 'hsl(0,65%,58%)' },
      }),
    );
    act(() => {
      result.current.append('tree:addNode', 'added foo', 'foo-1');
    });
    expect(readActivityLog(doc).length).toBe(1);
    expect(result.current.entries[0]?.summary).toBe('added foo');
    expect(result.current.entries[0]?.peerId).toBe('peer-x');
    expect(result.current.entries[0]?.entityId).toBe('foo-1');
  });

  it('uses anonymous fallback peer when not supplied', () => {
    const doc = new Y.Doc();
    const { result } = renderHook(() => useActivityFeed({ doc }));
    act(() => {
      result.current.append('tree:addNode', 'a');
    });
    expect(result.current.entries[0]?.peerId).toBe('anonymous');
  });
});

describe('useActivityFeed · Y.Doc subscription', () => {
  it('re-renders when activity root receives a remote-origin entry', async () => {
    const doc = new Y.Doc();
    const { result } = renderHook(() => useActivityFeed({ doc }));
    await act(async () => {
      appendActivityToDoc(doc, {
        id: 'R1',
        kind: 'tree:addNode',
        peerId: 'remote',
        peerName: 'Bob',
        peerColor: 'hsl(120,65%,58%)',
        timestamp: Date.now(),
        summary: 'from remote',
      }, ORIGIN_REMOTE_UPDATE);
    });
    expect(result.current.entries.map((e) => e.id)).toContain('R1');
  });

  it('logs ITS OWN local sketch op via source-root observer', async () => {
    const doc = new Y.Doc();
    // Seed a sketch entity so applySketchOp can target it.
    applySketchOp(doc, {
      kind: 'createSketch',
      sketch: {
        id: 'sk1',
        plane: 'xy',
        planeOffset: 0,
        operation: 'add',
        faceFrame: null,
        config: {
          mode: 'extrude',
          depth: 50,
          revolveAngle: 360,
          revolveAxis: 'y',
          segments: 32,
        },
        segments: [],
        constraints: [],
        dimensions: [],
      },
    }, ORIGIN_LOCAL_UI);

    const { result } = renderHook(() =>
      useActivityFeed({
        doc,
        peer: { id: 'me', name: 'Me', color: 'hsl(0,65%,58%)' },
      }),
    );

    await act(async () => {
      applySketchOp(doc, {
        kind: 'addSegment',
        sketchId: 'sk1',
        segment: {
          id: 'seg-X',
          type: 'line',
          points: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
      }, ORIGIN_LOCAL_UI);
    });

    // One entry should have been generated by the source-root subscription.
    const log = result.current.entries.filter((e) => e.kind === 'sketch:addSegment');
    expect(log.length).toBeGreaterThan(0);
    expect(log[0]?.peerId).toBe('me');
    expect(log[0]?.entityId).toBe('seg-X');
  });

  it('does NOT log remote-origin sketch ops (avoids double-logging)', async () => {
    const doc = new Y.Doc();
    applySketchOp(doc, {
      kind: 'createSketch',
      sketch: {
        id: 'sk1',
        plane: 'xy',
        planeOffset: 0,
        operation: 'add',
        faceFrame: null,
        config: {
          mode: 'extrude',
          depth: 50,
          revolveAngle: 360,
          revolveAxis: 'y',
          segments: 32,
        },
        segments: [],
        constraints: [],
        dimensions: [],
      },
    }, ORIGIN_LOCAL_UI);

    const { result } = renderHook(() =>
      useActivityFeed({
        doc,
        peer: { id: 'me', name: 'Me', color: 'hsl(0,65%,58%)' },
      }),
    );

    const before = result.current.entries.filter((e) => e.kind === 'sketch:addSegment').length;

    await act(async () => {
      applySketchOp(doc, {
        kind: 'addSegment',
        sketchId: 'sk1',
        segment: {
          id: 'remote-seg',
          type: 'line',
          points: [{ x: 0, y: 0 }, { x: 1, y: 1 }],
        },
      }, 'remote-update');
    });

    const after = result.current.entries.filter((e) => e.kind === 'sketch:addSegment').length;
    // Remote-origin op should NOT have produced a new entry from this peer.
    expect(after).toBe(before);
  });
});

describe('useActivityFeed · clearLocalView', () => {
  it('hides existing entries without touching the doc', async () => {
    const doc = new Y.Doc();
    const { result } = renderHook(() =>
      useActivityFeed({
        doc,
        peer: { id: 'me', name: 'Me', color: 'hsl(0,65%,58%)' },
      }),
    );
    act(() => {
      result.current.append('tree:addNode', 'one');
    });
    expect(result.current.entries.length).toBe(1);

    // Mock Date.now to be greater than the timestamp of the entry above.
    const realNow = Date.now;
    const futureT = realNow() + 10_000;
    Date.now = () => futureT;
    try {
      act(() => result.current.clearLocalView());
    } finally {
      Date.now = realNow;
    }

    expect(result.current.entries.length).toBe(0);
    // Doc still has the entry.
    expect(readActivityLog(doc).length).toBe(1);
  });

  it('next op repopulates the view', async () => {
    const doc = new Y.Doc();
    const { result } = renderHook(() =>
      useActivityFeed({
        doc,
        peer: { id: 'me', name: 'Me', color: 'hsl(0,65%,58%)' },
      }),
    );
    act(() => {
      result.current.append('tree:addNode', 'old');
    });
    const realNow = Date.now;
    // Clear at T+10s, then advance again so the next op's timestamp is
    // strictly > the clear cursor.
    Date.now = () => realNow() + 10_000;
    act(() => result.current.clearLocalView());
    Date.now = () => realNow() + 20_000;
    try {
      act(() => result.current.append('tree:addNode', 'new'));
    } finally {
      Date.now = realNow;
    }
    expect(result.current.entries.length).toBe(1);
    expect(result.current.entries[0]?.summary).toBe('new');
  });
});

describe('useActivityFeed · lifecycle', () => {
  it('unsubscribes on unmount (no further appends after teardown)', async () => {
    const doc = new Y.Doc();
    const { result, unmount } = renderHook(() =>
      useActivityFeed({
        doc,
        peer: { id: 'me', name: 'Me', color: 'hsl(0,65%,58%)' },
      }),
    );
    act(() => {
      result.current.append('tree:addNode', 'one');
    });
    unmount();
    // Append directly to the doc — the hook is no longer rendering so
    // no error should occur, and there's no observer to fire.
    await act(async () => {
      appendActivityToDoc(doc, {
        id: 'POST-UNMOUNT',
        kind: 'tree:addNode',
        peerId: 'someone',
        peerName: 'Other',
        peerColor: 'hsl(60,65%,58%)',
        timestamp: Date.now(),
        summary: 'after unmount',
      });
    });
    // Doc has 2 entries; the unmounted hook held 1 entry view.
    expect(readActivityLog(doc).length).toBe(2);
  });
});
