import { NextRequest, NextResponse } from 'next/server'; import { getTrustedClientIp } from '@/lib/client-ip'; import { rateLimit } from '@/lib/rate-limit'; import { buildIfcGeometryRecoveryRequests } from '@/lib/reference/ifcGeometryRecoveryRequests'; import { boundedJsonError, readBoundedJson } from '@/lib/boundedJsonBody'; import { MAX_INLINE_IFC_BYTES, MAX_SINGLE_IFC_JSON_BYTES } from '../bodyLimits';
export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
export async function POST(req: NextRequest) {
  const ip = getTrustedClientIp(req.headers); if (!rateLimit(`cad-v1-ifc-recovery-plan:${ip}`, 20, 60_000).allowed) return NextResponse.json({ ok: false, code: 'RATE_LIMIT' }, { status: 429 });
  let body: unknown; try { body = await readBoundedJson(req, MAX_SINGLE_IFC_JSON_BYTES); } catch (error) { const boundary = boundedJsonError(error); if (boundary?.code === 'PAYLOAD_TOO_LARGE') return NextResponse.json({ ok: false, code: 'PAYLOAD_TOO_LARGE' }, { status: 413 }); return NextResponse.json({ ok: false, code: 'BAD_REQUEST', message: 'One inline IFC document is required; paths and URLs are forbidden.' }, { status: 400 }); }
  if (!body || typeof body !== 'object' || Array.isArray(body) || Object.keys(body).some(key => key !== 'ifc') || typeof (body as {ifc?:unknown}).ifc !== 'string') return NextResponse.json({ ok: false, code: 'BAD_REQUEST', message: 'One inline IFC document is required; paths and URLs are forbidden.' }, { status: 400 });
  const source = (body as {ifc:string}).ifc; if (!source.trim()) return NextResponse.json({ ok: false, code: 'BAD_REQUEST' }, { status: 400 }); if (Buffer.byteLength(source, 'utf8') > MAX_INLINE_IFC_BYTES) return NextResponse.json({ ok: false, code: 'PAYLOAD_TOO_LARGE', maxIfcBytes: MAX_INLINE_IFC_BYTES }, { status: 413 });
  try { const report = buildIfcGeometryRecoveryRequests(source); return NextResponse.json({ ok: true, ...report, sourceReturned: false, quoteOrRfqSideEffects: false }); }
  catch (error) { return NextResponse.json({ ok: false, code: 'IFC_RECOVERY_PLAN_FAILED', message: error instanceof Error ? error.message : String(error), quoteOrRfqSideEffects: false }, { status: 422 }); }
}
