// Shape Generator 로컬 레이블 & 상수 — page.tsx 에서 분리
// 직접 수정하지 말고 각 언어별 키를 여기서 유지하세요.

// ─── Constants ──────────────────────────────────────────────────────────────

const SHAPE_ICONS: Record<string, string> = {
  box: '📦', cylinder: '🔩', sphere: '🔮', cone: '🔺', torus: '🍩', wedge: '🔻',
  pipe: '🔧', lBracket: '📐', flange: '⚙️', plateBend: '🔨',
  gear: '⚙️', fanBlade: '🌀', sprocket: '🔗', pulley: '🎡',
  sweep: '🔀', loft: '🔄',
  bolt: '🔩', spring: '🌀', tSlot: '⊓',
  hexNut: '⬡', washer: '⭕', iBeam: 'Ⅰ', bearing: '⊚',
};


type TabMode = 'design' | 'optimize';
type ViewMode = 'gallery' | 'workspace';

const TAB_LABELS: Record<string, { design: string; optimize: string }> = {
  ko: { design: '형상 설계', optimize: '위상 최적화' },
  en: { design: 'Shape Design', optimize: 'Topology Optimization' },
  ja: { design: '形状設計', optimize: 'トポロジー最適化' },
  cn: { design: '形状设计', optimize: '拓扑优化' },
  es: { design: 'Diseño de Forma', optimize: 'Optimización Topológica' },
  ar: { design: 'تصميم الشكل', optimize: 'تحسين الطوبولوجيا' },
};

/** Fusion-style workspace switcher (dropdown labels). Keys match CadWorkspaceId. */
const CAD_WORKSPACE_LABELS: Record<
  string,
  Record<
    | 'design'
    | 'optimize'
    | 'generative'
    | 'render'
    | 'animation'
    | 'simulation'
    | 'thermal'
    | 'modal'
    | 'manufacture'
    | 'drawing'
    | 'electronics',
    string
  >
> = {
  ko: {
    design: '설계',
    optimize: '최적화',
    generative: '제너레이티브',
    render: '렌더',
    animation: '모션',
    simulation: '구조 시뮬레이션',
    thermal: '열 해석',
    modal: '모달 해석',
    manufacture: '제조',
    drawing: '도면',
    electronics: '전자',
  },
  en: {
    design: 'Design',
    optimize: 'Optimize',
    generative: 'Generative Design',
    render: 'Render',
    animation: 'Animation',
    simulation: 'Simulation',
    thermal: 'Thermal',
    modal: 'Modal',
    manufacture: 'Manufacture',
    drawing: 'Drawing',
    electronics: 'Electronics',
  },
  ja: {
    design: '設計',
    optimize: '最適化',
    generative: 'ジェネレーティブ',
    render: 'レンダリング',
    animation: 'アニメーション',
    simulation: 'シミュレーション',
    thermal: '熱解析',
    modal: 'モード解析',
    manufacture: '製造',
    drawing: '図面',
    electronics: 'エレクトロニクス',
  },
  cn: {
    design: '设计',
    optimize: '优化',
    generative: '衍生式设计',
    render: '渲染',
    animation: '动画',
    simulation: '结构仿真',
    thermal: '热分析',
    modal: '模态分析',
    manufacture: '制造',
    drawing: '工程图',
    electronics: '电子',
  },
  es: {
    design: 'Diseño',
    optimize: 'Optimizar',
    generative: 'Diseño generativo',
    render: 'Renderizado',
    animation: 'Animación',
    simulation: 'Simulación',
    thermal: 'Térmico',
    modal: 'Modal',
    manufacture: 'Fabricación',
    drawing: 'Dibujo',
    electronics: 'Electrónica',
  },
  ar: {
    design: 'التصميم',
    optimize: 'التحسين',
    generative: 'التصميم التوليدي',
    render: 'العرض',
    animation: 'الحركة',
    simulation: 'المحاكاة',
    thermal: 'حراري',
    modal: 'Modal',
    manufacture: 'التصنيع',
    drawing: 'الرسم',
    electronics: 'الإلكترونيات',
  },
};

const CAD_WORKSPACE_SWITCHER_HEADING: Record<string, string> = {
  ko: '작업공간',
  en: 'Workspace',
  ja: 'ワークスペース',
  cn: '工作区',
  es: 'Espacio de trabajo',
  ar: 'مساحة العمل',
};

// ─── Local i18n dictionary (hardcoded strings migrated from ternaries) ─────────
const LOCAL_LABELS = {
  ko: {
    // toasts / messages
    assemblyLabel: '어셈블리',
    remoteResolvedComment: '✅ 원격 사용자가 코멘트를 해결했습니다.',
    mentionedYou: '님이 멘션했습니다',
    invalidShareLink: '잘못된 공유 링크입니다',
    designLoaded: '설계를 불러왔습니다',
    designLoadFailed: '설계 로드에 실패했습니다',
    sharedModelLoaded: '공유된 모델을 불러왔습니다',
    sharedModelLoadFailed: '공유 모델 로드 실패',
    snapshotSaved: '스냅샷이 저장되었습니다',
    versionRestored: '버전이 복원되었습니다',
    featureCannotRestore: '피처를 복원할 수 없습니다',
    featureRestored: '피처가 복원되었습니다',
    closeProfileFirst: '프로파일을 먼저 닫아주세요',
    sketchModeExitPreserved: '스케치 모드 종료. 스케치 내용은 보존됩니다. 다시 S를 눌러 재진입하세요.',
    sketchPreflightPointsNoConstraints: '점은 있으나 구속이 없습니다 — 기하가 흐를 수 있습니다.',
    sketchPreflightConstraintsNoPoints: '구속은 있는데 점이 없습니다 — 스케치 상태가 일치하지 않습니다.',
    sketchPreflightLargeConstraintSet: '구속이 매우 많습니다 — 저사양 기기에서 풀이가 느릴 수 있습니다.',
    sketchLargeConstraintInfo: '스케치 구속이 매우 많습니다. 자동 풀이가 다소 느려질 수 있습니다.',
    interferenceRunHeavyHint: '쌍 비교가 많아 검사에 시간이 걸릴 수 있습니다. 저장한 뒤 실행하세요.',
    camHeavyMeshHint: '메시 정점이 많습니다. CAM 경로 계산·시뮬에 시간이 걸릴 수 있습니다.',
    perfSuppressLoadToasts: '부하·스케치 안내 토스트 끄기 (CAM·간섭·다구속)',
    composeRefining: 'AI 가 새 조합을 합성 중...',
    composeSearching: 'AI 가 최적 설계 조합을 찾는 중...',
    composeSubtitle: '부품 · 제조법 · 재료 매칭 · JSCAD 합성',
    stepExportFeature: 'STEP 내보내기',
    gltfExportFeature: 'GLTF 내보내기',
    dxfExportFeature: 'DXF 내보내기',
    rhinoExportFeature: 'Rhino 내보내기 (Team+)',
    grasshopperExportFeature: 'Grasshopper 내보내기 (Team+)',
    dfmAnalysisFeature: 'DFM 분석',
    doubleClickSketchHint: '(더블클릭=스케치)',
    aiShapeGenPanel: '⚙ AI·JSCAD 코드 형상',
    ideaDesignSource: (label: string) => `아이디어 설계: ${label}`,
    unitCostHint: (cost: number | string) => `예상 단가 ≈ $${cost}/개`,
    leadTimeHint: (a: number | string, b: number | string) => `납기 ${a}~${b}일`,
    selectedFaceMsg: (lbl: string, area: string, normal: string) => `[선택된 면: ${lbl}, 면적 ${area}mm², 법선 (${normal})]`,
    selectedEdgeMsg: (length: string, pos: string) => `[선택된 엣지: 길이 ${length}mm, 위치 (${pos})]`,
    useThisFaceAsBase: '이 면을 기준으로 작업해줘.',
    addedToFeatureTree: '피처 트리에 추가됨',
    undoLabel: '되돌리기',
    retryLabel: '다시 시도',
    booleanApplied: 'Boolean 연산 완료',
    booleanFailed: 'Boolean 연산 실패',
    body1: '바디 1',
    bodyGeometryMissing: '바디 데이터 없음',
    bodySplitComplete: '바디 분리 완료',
    splitFailed: '분리 실패',
    mergedBody: '합체 바디',
    bodiesMerged: '바디 합체 완료',
    mergeFailed: '합체 실패',
    stlSaved: 'STL 저장됨',
    stlExportFailed: 'STL 내보내기 실패',
    pdfExportFailed: 'PDF 내보내기 실패',
    stepExportFailed: 'STEP 내보내기 실패',
    /** Toast after STEP + manufacturing.json + MANUFACTURING.txt */
    stepExportBundleSuccess: '제조 패키지 ZIP을 받았습니다. 압축 해제 시 STEP·STL·메타데이터(JSON)·요약(TXT)이 포함됩니다.',
    dxfExported: 'DXF 내보내기 완료',
    dxfExportFailed: 'DXF 내보내기 실패',
    createShapeFirst: '형상을 먼저 생성하세요',
    flatDxfExported: '전개도 DXF 내보내기 완료',
    rhinoExported: 'Rhino JSON 내보내기 완료',
    rhinoFailed: 'Rhino JSON 내보내기 실패',
    grasshopperExported: 'Grasshopper 포인트 내보내기 완료',
    grasshopperFailed: 'Grasshopper 내보내기 실패',
    sceneSaveFailed: '씬 저장 실패',
    sceneLoadFailed: '씬 불러오기 실패',
    loadSceneFirst: '씬을 먼저 로드하세요',
    glbExportFailed: 'GLB 내보내기 실패',
    printAnalysisComplete: '3D 프린팅 분석 완료',
    generateShapeFirst: '먼저 형상을 생성하세요',
    alreadyOptimalOrientation: '이미 최적 방향입니다',
    exportFailed: '익스포트 실패',
    optimalOrientationApplied: '최적 방향 적용됨',
    dfmAnalysisComplete: '제조 가능성 분석 완료',
    noGeometryToAnalyze: '분석할 지오메트리가 없습니다',
    allFacesModable: '모든 면 성형 가능',
    noRelatedFeature: '관련 피처를 찾지 못했습니다',
    feaAnalysisComplete: '응력 해석 완료',
    noInterference: '간섭이 발견되지 않았습니다',
    bendApplied: '굽힘 적용됨',
    flangeApplied: '플랜지 적용됨',
    flatPatternGenerated: '전개도 생성됨',
    goDesignTabFirst: 'Design 탭에서 먼저 형상을 생성하세요.',
    workspaceEmptyNeedShape: (ws: string) =>
      `「${ws}」을(를) 쓰려면 먼저 형상이 필요합니다. 왼쪽에서 프리셋을 고르거나 스케치(S)로 시작하세요.`,
    workspaceEmptyGoDesign: '설계로',
    cadWorkspaceSelectAria: '작업공간(리본) 선택',
    optimizeEmptyNeedMesh:
      '토폴로지를 돌리려면 Design 탭에서 형상을 만든 뒤, 고정면·하중을 설정하고 Generate 를 누르세요.',
    edgeEditHint: '엣지를 클릭해 필렛/챔퍼 적용. 미드포인트 드래그로 이동.',
    /** Status bar — vertex mode: no single-click “confirm”; drag to move; orbit uses middle mouse (left no longer rotates). */
    vertexEditPointerHint: '버텍스는 왼쪽으로 누른 채 드래그해야 이동합니다(클릭만으로는 확정되지 않음). 카메라 회전: 마우스 가운데 버튼 드래그 · 팬: 우클릭.',
    edgeEditPointerHint: '엣지 미드포인트를 왼쪽으로 드래그. 카메라 회전: 가운데 버튼 · Boolean(⊕)은 패널이 열립니다.',
    booleanPanelOpened: 'Boolean 연산 패널이 열렸습니다. 연산·도구를 고른 뒤 적용하세요.',
    faceEditHint: '면을 클릭해 선택, 초록 화살표 드래그로 Push/Pull.',
    /** Shown inside 3D view when Face edit is on but no face is selected yet */
    faceEditViewportCalloutTitle: '면 편집 (Push/Pull)',
    faceEditViewportCallout: '① 면 클릭 → ② 초록 화살표 드래그',
    faceEditViewportCalloutTip:
      '면이 안 잡히면 상단에서 「면」 필터와 「솔리드」 보기를 켜 보세요. 스프링·기본 형상은 왼쪽 슬라이더로도 크기를 바꿀 수 있습니다.',
    faceEditCalloutDismiss: '닫기',
    /** Shown in workspace status when a solid exists and user is not in sketch/direct-edit — where to click. */
    designEditQuickGuide:
      '고치는 법: 왼쪽 패널 슬라이더(외경·높이 등 치수) · 아래 «직접 편집»에서 면·엣지·꼭짓점(가운데 3D를 클릭) · «피처» 탭에서 돌출·필렛. 면 고르기는 «솔리드» 보기가 더 쉽습니다.',
    designOn3dPc: '3D 설계는 PC에서',
    mobileHint: 'NexyFab 3D 모델링 도구는 마우스와 키보드가 필요한 데스크톱 전용 기능입니다.\n모바일에서는 아래 기능을 이용해 주세요.',
    dashboard: '대시보드',
    checkProjects: '프로젝트 현황 확인',
    marketplace: '제조사 마켓',
    browseMfrs: '제조사 검색 및 견적 요청',
    orderTracking: '주문 추적',
    trackMfgProgress: '실시간 제조 진행 확인',
    rfqQuotes: 'RFQ 견적',
    manageQuotes: '견적 요청 조회 및 관리',
    desktopHint: '💻 PC 브라우저에서 nexyfab.com을 열면\n3D 모델링을 시작할 수 있습니다.',
    mobileShareViewTitle: '공유로 받은 3D 링크',
    mobileShareViewBody: '이메일·메신저로 받은 전체 주소를 브라우저 주소창에 붙여 넣으면, 휴대폰에서도 회전·확대하여 볼 수 있어요. 편집은 PC에서 해 주세요.',
    simpleModeOfferTitle: '처음이신가요?',
    simpleModeOfferDesc: '간편 모드는 분석·고급 패널을 줄여 형상·견적 작업에 집중할 수 있어요.',
    simpleModeOfferEnable: '간편 모드 켜기',
    simpleModeOfferDismiss: '전체 기능 유지',
    simpleModeOfferRegion: '간편 모드 안내',
    workspaceStatusLabel: '작업 안내',
    featureSelectedPrefix: '선택된 피처:',
    measureToolActive: '측정 모드 — 두 점 또는 모서리를 클릭하세요.',
    dropFileHere: '파일을 여기에 놓으세요',
    loadingFile: '파일 불러오는 중...',
    smallScreenDetected: '화면이 작습니다',
    smallScreenHint: '전체화면 모드에서 더 편하게 작업할 수 있어요.',
    goFullscreen: '전체화면으로',
    noThanks: '괜찮아요',
    stepLoadedIntoViewport: 'STEP 형상을 뷰포트에 로드했습니다',
    getQuoteArrow: '견적 받기 →',
    aiPreviewMode: 'AI 미리보기 모드',
    aiPreviewHint: '— 채팅에서 적용 또는 취소를 선택하세요',
    cancelLabel: '취소',
    viewerOnlyMode: '🔒 뷰어 전용 모드 — 편집이 비활성화되어 있습니다.',
    pluginsLabel: '플러그인',
    manageLabel: '관리',
    directEdit: '직접 편집:',
    faceEditMode: '면 편집 (Push/Pull)',
    vertexEditMode: '버텍스 편집',
    edgeEditMode: '엣지 편집',
    doubleClickSketchFace: '더블클릭 = 면 스케치',
    booleanOps: 'Boolean 연산 (Union/Subtract/Intersect)',
    booleanShort: 'Boolean',
    exitEdit: '편집 종료',
    depthMm: '깊이 (mm)',
    extrude: '돌출 (Extrude)',
    revolve: '회전',
    continueEditing: '계속 편집',
    sketchClickHint: '첫 점을 클릭하거나 더블클릭하여 프로파일 닫기',
    show3dPreview: '3D 프리뷰 표시',
    hide3dPreview: '3D 프리뷰 숨기기',
    hideLabel: '숨기기',
    viewportPreviewInMain: '3D 뷰는 가운데 작업 영역에 표시됩니다.',
    partPlacement: '파트 배치 패널',
    partsLabel: '배치',
    assemblyTools: '어셈블리 도구',
    assemblyShort: '어셈블리',
    geometryValidation: '지오메트리 검증 결과',
    manifold: '매니폴드',
    closedMesh: '닫힌 메시',
    consistentNormals: '일관된 노말',
    openEdges: '열린 에지',
    nonManifoldEdges: '비매니폴드 에지',
    degenerateTri: '퇴화 삼각형',
    duplicateVertices: '중복 정점',
    totalTriangles: '총 삼각형',
    totalVertices: '총 정점',
    volumeLabel: '체적',
    surfaceAreaLabel: '표면적',
    issuesLabel: '검사 결과',
    standardPartsLibrary: '표준 부품 라이브러리',
    fastenersLabel: '체결류',
    structuralLabel: '구조재',
    bearingsLabel: '베어링',
    hexBolt: '육각 볼트',
    hexNut: '육각 너트',
    socketHeadCapScrew: '소켓 캡스크류',
    flatWasher: '평와셔',
    springWasher: '스프링 와셔',
    iBeam: 'I빔',
    angleBracket: 'L앵글',
    channelBeam: 'C채널',
    ballBearing: '볼 베어링',
    bushing: '부싱',
    screenshotSaved: '스크린샷이 저장되었습니다',
    feaRunning: 'FEA 응력 해석 중...',
    dfmRunning: 'DFM 분석 중...',
    csgRunning: 'CSG 연산 중...',
    rebuildingGeometry: '지오메트리 계산 중...',
    occtEngine: 'OCCT 토폴로지 엔진 (실험)',
    suggestionReapplied: '제안을 다시 적용했습니다',
    noApplicableChanges: '적용할 변경사항이 없습니다',
    selectManufacturer: '제조사 선택',
    quoteRequestMessage: '견적을 요청드립니다.',
    collabPanel: '협업 패널',
    pinComments: '핀 코멘트',
    chatLabel: '채팅',
    ipProtectedShare: 'IP 보호 공유 링크',
    ipShareInfo: '72시간 유효 · 다운로드 불가 · 워터마크 포함',
    linkCopied: '링크 복사됨',
    copyLabel: '복사',
    closeLabel: '닫기',
    optimalStructureDone: '최적 구조 생성 완료!',
    pcbHeatMappingDone: 'PCB 열분포 매핑 완료!',
    showOriginal: '원본 보기',
    showPcbHeatMap: 'PCB 열분포 보기',
    showOptimized: '최적화 결과 보기',
    modalAnalysisDone: '모달 해석 완료',
    bestParamsApplied: '최적 파라미터 적용됨',
    surfaceAnalysisDone: '곡률 분석 완료',
    sketchGeometryFailed: '지오메트리 생성 실패 — 자체 교차 또는 잘못된 형상을 확인하세요',
    shapeGeneratedGuide: '3D 형상 생성 완료! 왼쪽 패널에서 재질을 선택하고 Export하거나 RFQ로 보내세요.',
    sketchPlaneSwitched: (plane: string) => `스케치 평면이 ${plane}로 전환됨. 기존 형상은 새 평면에 매핑됩니다.`,
    sketchRefBadFileType: '참조에는 이미지 또는 STL/STEP/DXF 파일만 사용할 수 있습니다.',
    sketchRefLoading: '참조 지오메트리 처리 중…',
    importFileMenuHint: '3D 워크스페이스용 부품 가져오기. 스케치 착시 참조는 스케치 탭 → 삽입을 사용하세요.',
    sketchPickFilterAll: '모두 — 선분 선택 + 점 드래그',
    sketchPickFilterSegments: '선분만 — 점 드래그 비활성',
    sketchPickFilterPoints: '점만 — 선분 선택 비활성',
    exitSketchBeforeOptimize: '스케치 모드를 종료한 후 최적화 탭으로 이동하세요. 현재 스케치는 유지됩니다.',
    mateCoincident: '면 일치',
    mateConcentric: '동축',
    mateDistance: '거리',
    feaUpgradeFeature: 'FEA 응력 해석',
    // templated
    brokenExpression: (key: string, expression: string, missing: string, extra: number) =>
      `식 의존성 끊김: '${key}' = '${expression}' (없는 변수: ${missing}${extra > 0 ? ` 외 ${extra}건` : ''})`,
    cannotApplyFeature: (msg: string) => `피쳐를 적용할 수 없습니다: ${msg}`,
    featureFailed: (label: string, hint: string) => `⚠ ${label} 실행 실패 — ${hint}`,
    branchCreated: (name: string) => `브랜치 "${name}" 생성됨`,
    branchSwitched: (name: string) => `브랜치 "${name}"(으)로 전환`,
    branchDeleted: (name: string) => `브랜치 "${name}" 삭제됨`,
    branchMerged: (src: string, tgt: string) => `"${src}" -> "${tgt}" 병합 완료`,
    pipelineFailed: (msg: string) => `지오메트리 계산 실패: ${msg}`,
    shapeNotFound: (id: string) => `형상 "${id}"을 찾을 수 없습니다`,
    sketchEmpty: (where: string) => `스케치가 비어있습니다${where}`,
    sketchTooFew: (where: string) => `선분 3개 이상이 필요합니다${where}`,
    sketchGap: (where: string) => `프로파일이 닫히지 않았습니다 — 끝점을 시작점에 연결하세요${where}`,
    sketchNotClosed: (where: string) => `프로파일을 닫아주세요 — 마지막 점을 첫 점에 연결하거나 자동 닫기를 사용하세요${where}`,
    aiAppliedChanges: (count: number) => `AI 변경 ${count}개 적용됨`,
    shapeFromText: (id: string) => `"${id}" 형상이 텍스트에서 생성되었습니다`,
    mateAdded: (label: string, a: string, b: string) => `${label} 합치 추가됨 (${a} ↔ ${b})`,
    flatDxfFailed: (msg: string) => `전개도 DXF 실패: ${msg}`,
    gcodeGenerated: (post: string, passes: number, lines: number, time: number, warning: string) =>
      `G-code 생성 완료 (${post}) — ${passes}개 패스, ${lines}줄, 예상 ${time}분${warning ? ` ⚠ ${warning}` : ''}`,
    orientationSaves: (label: string, pct: number) => `${label} 방향 권장 — 서포트 ${pct}% 절감`,
    printReadyDownloaded: '슬라이서용 파일을 다운로드했습니다 (.stl + .3mf)',
    dfmFailed: (msg: string) => `DFM 분석 실패: ${msg}`,
    autoFixApplied: (label: string) => `자동 수정 적용: ${label}`,
    aiAnalysisFailed: (msg: string) => `AI 분석 실패: ${msg}`,
    undercutsDetected: (count: string) => `언더컷 ${count}개 검출됨`,
    facesNeedDraft: (count: string) => `구배 부족 ${count}개 면`,
    draftFailed: (msg: string) => `구배 분석 실패: ${msg}`,
    jumpToFeature: (type: string) => `피처로 이동: ${type}`,
    noFeatureInTree: (list: string) => `'${list}' 피처가 없습니다 — 추가해 보세요`,
    feaFailed: (msg: string) => `FEA 해석 실패: ${msg}`,
    interferenceFound: (n: number) => `${n}건의 간섭이 발견되었습니다`,
    interferenceFailed: (msg: string) => `간섭 검사 실패: ${msg}`,
    interferenceCancelled: '간섭 검사를 취소했습니다.',
    interferenceTimelineLabel: '간섭 검사',
    importFailed: (msg: string) => `불러오기 실패: ${msg}`,
    designApplied: (summary: string) => `✅ 설계 적용됨${summary ? ` (${summary})` : ''} — DFM 자동 분석 중`,
    importedFile: (name: string) => `"${name}" 불러오기 완료`,
    importFailedFile: (msg: string) => `파일 불러오기 실패: ${msg}`,
    cotsAddedToBom: (name: string) => `${name} BOM에 추가됨`,
    standardHoleAdded: (d: string) => `표준 규격 홀 추가됨 (Ø${d}mm)`,
    versionSaved: (name: string) => `💾 "${name}" 저장됨`,
    versionApplied: (name: string) => `↻ "${name}" 적용됨`,
    partLoaded: (name: string) => `📚 "${name}" 불러옴`,
    processMatchingSuppliers: (p: string) => `${p} 공정 → 공급사 매칭 시작`,
    rfqSent: (mfr: string, qty: number) => `${mfr}에 RFQ 전송 완료 (${qty}개)`,
    materialSwitched: (id: string) => `재료를 ${id}(으)로 변경했습니다`,
    aiShapeGenerated: (desc: string) => `AI 형상 생성 완료: ${desc}…`,
    quoteRequestSent: (name: string) => `${name}에 견적 요청을 전송했습니다`,
    thermalFeaDone: '열해석 완료 — 3D 뷰에 온도 분포가 표시됩니다',
    quoteRequested: (id: string) => `제조사 ${id}에 견적 요청됨`,
    designFailed: (err: string) => `설계 생성 실패: ${err}`,
    networkError: (err: string) => `네트워크 오류: ${err}`,
  },
  en: {
    assemblyLabel: 'Assembly',
    remoteResolvedComment: '✅ A collaborator resolved a comment.',
    mentionedYou: 'mentioned you',
    invalidShareLink: 'Invalid share link',
    designLoaded: 'Design loaded from cloud',
    designLoadFailed: 'Failed to load design',
    sharedModelLoaded: 'Shared model loaded',
    sharedModelLoadFailed: 'Failed to load shared model',
    snapshotSaved: 'Snapshot saved',
    versionRestored: 'Version restored',
    featureCannotRestore: 'Cannot restore feature',
    featureRestored: 'Feature restored',
    closeProfileFirst: 'Close the profile first',
    sketchModeExitPreserved: 'Sketch mode exited. Your sketch is preserved. Press S to re-enter.',
    sketchPreflightPointsNoConstraints: 'Sketch has points but no constraints — geometry may drift.',
    sketchPreflightConstraintsNoPoints: 'Constraints exist but no sketch points — inconsistent sketch state.',
    sketchPreflightLargeConstraintSet: 'Large constraint set — solve may be slower on low-end devices.',
    sketchLargeConstraintInfo: 'Very many sketch constraints — auto-solve may feel slower.',
    interferenceRunHeavyHint: 'Many pairwise checks — the run may take a while. Save your work first.',
    camHeavyMeshHint: 'High vertex count — CAM path generation and simulation may take longer.',
    perfSuppressLoadToasts: 'Suppress load/sketch info toasts (CAM, interference, many constraints)',
    composeRefining: 'AI is synthesizing a new combination...',
    composeSearching: 'AI is finding the best design combination...',
    composeSubtitle: 'Parts · Process · Material · JSCAD synthesis',
    stepExportFeature: 'STEP Export',
    gltfExportFeature: 'GLTF Export',
    dxfExportFeature: 'DXF Export',
    rhinoExportFeature: 'Rhino Export (Team+)',
    grasshopperExportFeature: 'Grasshopper Export (Team+)',
    dfmAnalysisFeature: 'DFM Analysis',
    doubleClickSketchHint: '(dbl-click = sketch)',
    aiShapeGenPanel: '⚙ AI + JSCAD code shapes',
    ideaDesignSource: (label: string) => `Idea design: ${label}`,
    unitCostHint: (cost: number | string) => `Est. unit cost ≈ $${cost}/ea`,
    leadTimeHint: (a: number | string, b: number | string) => `Lead time ${a}–${b} days`,
    selectedFaceMsg: (lbl: string, area: string, normal: string) => `[Selected face: ${lbl}, area ${area}mm², normal (${normal})]`,
    selectedEdgeMsg: (length: string, pos: string) => `[Selected edge: length ${length}mm, position (${pos})]`,
    useThisFaceAsBase: 'Please use this face as the reference.',
    addedToFeatureTree: 'Added to feature tree',
    undoLabel: 'Undo',
    retryLabel: 'Retry',
    booleanApplied: 'Boolean operation applied',
    booleanFailed: 'Boolean operation failed',
    body1: 'Body 1',
    bodyGeometryMissing: 'Body geometry not found',
    bodySplitComplete: 'Body split complete',
    splitFailed: 'Split failed',
    mergedBody: 'Merged Body',
    bodiesMerged: 'Bodies merged',
    mergeFailed: 'Merge failed',
    stlSaved: 'STL saved',
    stlExportFailed: 'STL export failed',
    pdfExportFailed: 'Drawing PDF export failed',
    stepExportFailed: 'STEP export failed',
    stepExportBundleSuccess: 'Manufacturing bundle (ZIP) downloaded — extract for STEP, STL, manifest JSON, and README.',
    dxfExported: 'DXF exported successfully',
    dxfExportFailed: 'DXF export failed',
    createShapeFirst: 'Create a shape first',
    flatDxfExported: 'Flat pattern DXF exported',
    rhinoExported: 'Rhino JSON exported successfully',
    rhinoFailed: 'Rhino JSON export failed',
    grasshopperExported: 'Grasshopper points exported successfully',
    grasshopperFailed: 'Grasshopper export failed',
    sceneSaveFailed: 'Scene save failed',
    sceneLoadFailed: 'Scene import failed',
    loadSceneFirst: 'Load a scene first',
    glbExportFailed: 'GLB export failed',
    printAnalysisComplete: '3D Print analysis complete',
    generateShapeFirst: 'Generate a shape first',
    alreadyOptimalOrientation: 'Already in optimal orientation',
    exportFailed: 'Export failed',
    optimalOrientationApplied: 'Optimal orientation applied',
    dfmAnalysisComplete: 'DFM analysis complete',
    noGeometryToAnalyze: 'No geometry to analyze',
    allFacesModable: 'All faces are moldable',
    noRelatedFeature: 'No related feature found',
    feaAnalysisComplete: 'FEA analysis complete',
    noInterference: 'No interference detected',
    bendApplied: 'Bend applied',
    flangeApplied: 'Flange applied',
    flatPatternGenerated: 'Flat pattern generated',
    goDesignTabFirst: 'Go to Design tab first to generate a shape.',
    workspaceEmptyNeedShape: (ws: string) =>
      `Create a solid first to use “${ws}” — pick a preset on the left or press S to sketch.`,
    workspaceEmptyGoDesign: 'Design',
    cadWorkspaceSelectAria: 'Select CAD workspace',
    optimizeEmptyNeedMesh:
      'To run topology optimization, create a solid on the Design tab, set fixed faces and loads, then click Generate.',
    edgeEditHint: 'Click edge for fillet/chamfer. Drag midpoint to move.',
    vertexEditPointerHint: 'Drag a vertex with the left button to move it (a click alone does not commit). Orbit: middle mouse drag · Pan: right drag.',
    edgeEditPointerHint: 'Drag an edge midpoint to move it. Orbit: middle mouse. Boolean (⊕) opens a panel.',
    booleanPanelOpened: 'Boolean panel opened — pick an operation and tool, then Apply.',
    faceEditHint: 'Click face to select, drag green arrow to Push/Pull.',
    faceEditViewportCalloutTitle: 'Face edit (Push/Pull)',
    faceEditViewportCallout: '① Click a face → ② Drag the green arrow',
    faceEditViewportCalloutTip:
      'If picking fails, enable the Face filter and Solid view in the toolbar. Springs and templates can also be resized with the left sliders.',
    faceEditCalloutDismiss: 'Dismiss',
    designEditQuickGuide:
      'To edit: left panel sliders (diameter, height…) · Direct edit below for face / edge / vertex (click the 3D view) · Solid tab for extrude & fillets. Solid display mode picks faces more easily.',
    designOn3dPc: '3D Design on Desktop',
    mobileHint: 'The NexyFab 3D modeler requires a mouse and keyboard.\nPlease use a desktop browser for the full experience.',
    dashboard: 'Dashboard',
    checkProjects: 'Check your projects',
    marketplace: 'Marketplace',
    browseMfrs: 'Browse manufacturers & quote',
    orderTracking: 'Order Tracking',
    trackMfgProgress: 'Track manufacturing progress',
    rfqQuotes: 'RFQ Quotes',
    manageQuotes: 'View and manage quotes',
    desktopHint: '💻 Open nexyfab.com on a desktop browser\nto start 3D modeling.',
    mobileShareViewTitle: 'View a shared 3D link',
    mobileShareViewBody: 'Paste the full URL you received into the browser address bar — you can orbit and zoom on your phone. Editing stays on desktop.',
    simpleModeOfferTitle: 'New here?',
    simpleModeOfferDesc: 'Simple mode hides advanced analysis panels so you can focus on shape design and quoting.',
    simpleModeOfferEnable: 'Turn on simple mode',
    simpleModeOfferDismiss: 'Keep full workspace',
    simpleModeOfferRegion: 'Simple mode suggestion',
    workspaceStatusLabel: 'Workspace guide',
    featureSelectedPrefix: 'Selected feature:',
    measureToolActive: 'Measure mode — click two points or edges.',
    dropFileHere: 'Drop file here',
    loadingFile: 'Loading file...',
    smallScreenDetected: 'Small Screen Detected',
    smallScreenHint: 'Switch to fullscreen for a better experience.',
    goFullscreen: 'Go Fullscreen',
    noThanks: 'No thanks',
    stepLoadedIntoViewport: 'STEP geometry loaded into viewport',
    getQuoteArrow: 'Get Quote →',
    aiPreviewMode: 'AI Preview Mode',
    aiPreviewHint: '— Choose Apply or Cancel in the chat panel',
    cancelLabel: 'Cancel',
    viewerOnlyMode: '🔒 View-Only Mode — Editing is disabled.',
    pluginsLabel: 'Plugins',
    manageLabel: 'Manage',
    directEdit: 'Direct Edit:',
    faceEditMode: 'Face Edit (Push/Pull)',
    vertexEditMode: 'Vertex Edit',
    edgeEditMode: 'Edge Edit',
    doubleClickSketchFace: 'Double-click = Sketch on face',
    booleanOps: 'Boolean Operations',
    booleanShort: 'Boolean',
    exitEdit: 'Exit Edit',
    depthMm: 'Depth (mm)',
    extrude: 'Extrude',
    revolve: 'Revolve',
    continueEditing: 'Continue Editing',
    sketchClickHint: 'Click first point or double-click to close profile',
    show3dPreview: 'Show 3D Preview',
    hide3dPreview: 'Hide 3D Preview',
    hideLabel: 'Hide',
    viewportPreviewInMain: 'The 3D view is shown in the main workspace.',
    partPlacement: 'Part Placement',
    partsLabel: 'Parts',
    assemblyTools: 'Assembly Tools',
    assemblyShort: 'Assembly',
    geometryValidation: 'Geometry Validation',
    manifold: 'Manifold',
    closedMesh: 'Closed',
    consistentNormals: 'Consistent Normals',
    openEdges: 'Open Edges',
    nonManifoldEdges: 'Non-manifold Edges',
    degenerateTri: 'Degenerate Tri',
    duplicateVertices: 'Duplicate Vertices',
    totalTriangles: 'Total Triangles',
    totalVertices: 'Total Vertices',
    volumeLabel: 'Volume',
    surfaceAreaLabel: 'Surface Area',
    issuesLabel: 'Issues',
    standardPartsLibrary: 'Standard Parts Library',
    fastenersLabel: 'Fasteners',
    structuralLabel: 'Structural',
    bearingsLabel: 'Bearings',
    hexBolt: 'Hex Bolt',
    hexNut: 'Hex Nut',
    socketHeadCapScrew: 'Socket Cap Screw',
    flatWasher: 'Flat Washer',
    springWasher: 'Spring Washer',
    iBeam: 'I-Beam',
    angleBracket: 'Angle Bracket',
    channelBeam: 'Channel',
    ballBearing: 'Ball Bearing',
    bushing: 'Bushing',
    screenshotSaved: 'Screenshot saved',
    feaRunning: 'FEA running...',
    dfmRunning: 'DFM running...',
    csgRunning: 'CSG running...',
    rebuildingGeometry: 'Rebuilding geometry...',
    occtEngine: 'OCCT topology engine (experimental)',
    suggestionReapplied: 'Suggestion re-applied',
    noApplicableChanges: 'No applicable changes',
    selectManufacturer: 'Select Manufacturer',
    quoteRequestMessage: 'I would like to request a quote.',
    collabPanel: 'Collaboration',
    pinComments: 'Pin Comments',
    chatLabel: 'Chat',
    ipProtectedShare: 'IP-Protected Share Link',
    ipShareInfo: '72 hrs · No download · Watermarked',
    linkCopied: 'Link copied',
    copyLabel: 'Copy',
    closeLabel: 'Close',
    optimalStructureDone: 'Optimal structure generated!',
    pcbHeatMappingDone: 'PCB heat mapping complete!',
    showOriginal: 'Show Original',
    showPcbHeatMap: 'Show PCB Heat Map',
    showOptimized: 'Show Optimized',
    modalAnalysisDone: 'Modal analysis complete',
    bestParamsApplied: 'Best parameters applied',
    surfaceAnalysisDone: 'Surface analysis complete',
    sketchGeometryFailed: 'Failed to build geometry — check for self-intersection or invalid shape',
    shapeGeneratedGuide: '3D shape generated! Select a material in the left panel, then export or send to RFQ.',
    sketchPlaneSwitched: (plane: string) => `Sketch plane switched to ${plane}. Existing profile is remapped to the new plane.`,
    sketchRefBadFileType: 'Use an image or an STL/STEP/DXF file as reference.',
    sketchRefLoading: 'Processing reference geometry…',
    importFileMenuHint: 'Import part geometry into the 3D workspace. For sketch tracing underlay, use Sketch tab → Insert.',
    sketchPickFilterAll: 'All — select edges and drag vertices',
    sketchPickFilterSegments: 'Edges only — no vertex drag',
    sketchPickFilterPoints: 'Vertices only — no edge selection',
    exitSketchBeforeOptimize: 'Exit sketch mode before switching to Optimize. Your sketch will be preserved.',
    mateCoincident: 'Coincident',
    mateConcentric: 'Concentric',
    mateDistance: 'Distance',
    feaUpgradeFeature: 'FEA Analysis',
    brokenExpression: (key: string, expression: string, missing: string, extra: number) =>
      `Broken expression: '${key}' = '${expression}' (missing: ${missing}${extra > 0 ? ` +${extra} more` : ''})`,
    cannotApplyFeature: (msg: string) => `Cannot apply feature: ${msg}`,
    featureFailed: (label: string, hint: string) => `⚠ ${label} failed — ${hint}`,
    branchCreated: (name: string) => `Branch "${name}" created`,
    branchSwitched: (name: string) => `Switched to branch "${name}"`,
    branchDeleted: (name: string) => `Branch "${name}" deleted`,
    branchMerged: (src: string, tgt: string) => `Merged "${src}" into "${tgt}"`,
    pipelineFailed: (msg: string) => `Geometry pipeline failed: ${msg}`,
    shapeNotFound: (id: string) => `Shape "${id}" not found`,
    sketchEmpty: (where: string) => `Sketch is empty${where}`,
    sketchTooFew: (where: string) => `At least 3 segments required${where}`,
    sketchGap: (where: string) => `Profile is not closed — endpoint does not meet start${where}`,
    sketchNotClosed: (where: string) => `Close the profile before extruding${where}`,
    aiAppliedChanges: (count: number) => `AI applied ${count} change${count !== 1 ? 's' : ''}`,
    shapeFromText: (id: string) => `"${id}" shape generated from text`,
    mateAdded: (label: string, a: string, b: string) => `${label} mate added (${a} ↔ ${b})`,
    flatDxfFailed: (msg: string) => `Flat pattern DXF failed: ${msg}`,
    gcodeGenerated: (post: string, passes: number, lines: number, time: number, warning: string) =>
      `G-code generated (${post}) — ${passes} passes, ${lines} lines, est. ${time} min${warning ? ` ⚠ ${warning}` : ''}`,
    orientationSaves: (label: string, pct: number) => `Try ${label} — ${pct}% less support`,
    printReadyDownloaded: 'Print-ready files downloaded (.stl + .3mf)',
    dfmFailed: (msg: string) => `DFM failed: ${msg}`,
    autoFixApplied: (label: string) => `Auto-fix applied: ${label}`,
    aiAnalysisFailed: (msg: string) => `AI analysis failed: ${msg}`,
    undercutsDetected: (count: string) => `${count} undercut faces detected`,
    facesNeedDraft: (count: string) => `${count} faces need more draft`,
    draftFailed: (msg: string) => `Draft analysis failed: ${msg}`,
    jumpToFeature: (type: string) => `Jumped to feature: ${type}`,
    noFeatureInTree: (list: string) => `No '${list}' feature in tree — try adding one`,
    feaFailed: (msg: string) => `FEA failed: ${msg}`,
    interferenceFound: (n: number) => `${n} interference(s) found`,
    interferenceFailed: (msg: string) => `Interference check failed: ${msg}`,
    interferenceCancelled: 'Interference check cancelled.',
    interferenceTimelineLabel: 'Interference',
    importFailed: (msg: string) => `Import failed: ${msg}`,
    designApplied: (summary: string) => `Design applied${summary ? ` (${summary})` : ''} — auto DFM check running`,
    importedFile: (name: string) => `Imported "${name}" successfully`,
    importFailedFile: (msg: string) => `Import failed: ${msg}`,
    cotsAddedToBom: (name: string) => `${name} added to BOM`,
    standardHoleAdded: (d: string) => `Standard hole added (Ø${d}mm)`,
    versionSaved: (name: string) => `💾 Saved "${name}"`,
    versionApplied: (name: string) => `↻ Applied "${name}"`,
    partLoaded: (name: string) => `📚 Loaded "${name}"`,
    processMatchingSuppliers: (p: string) => `${p} → matching suppliers`,
    rfqSent: (mfr: string, qty: number) => `RFQ sent to ${mfr} (${qty} pcs)`,
    materialSwitched: (id: string) => `Material switched to ${id}`,
    aiShapeGenerated: (desc: string) => `Shape generated: ${desc}…`,
    quoteRequestSent: (name: string) => `Quote request sent to ${name}`,
    thermalFeaDone: 'Thermal FEA complete — temperature distribution shown in 3D view',
    quoteRequested: (id: string) => `Quote requested from ${id}`,
    designFailed: (err: string) => `Design generation failed: ${err}`,
    networkError: (err: string) => `Network error: ${err}`,
  },
  ja: {
    assemblyLabel: 'アセンブリ',
    remoteResolvedComment: '✅ リモートユーザーがコメントを解決しました。',
    mentionedYou: 'さんがメンションしました',
    invalidShareLink: '無効な共有リンクです',
    designLoaded: '設計を読み込みました',
    designLoadFailed: '設計の読み込みに失敗しました',
    sharedModelLoaded: '共有モデルを読み込みました',
    sharedModelLoadFailed: '共有モデルの読み込みに失敗',
    snapshotSaved: 'スナップショットを保存しました',
    versionRestored: 'バージョンを復元しました',
    featureCannotRestore: 'フィーチャを復元できません',
    featureRestored: 'フィーチャを復元しました',
    closeProfileFirst: '先にプロファイルを閉じてください',
    sketchModeExitPreserved: 'スケッチモード終了。スケッチ内容は保存されます。再度 S を押して再入場してください。',
    sketchPreflightPointsNoConstraints: '点はあるが拘束がありません — 形状が流れることがあります。',
    sketchPreflightConstraintsNoPoints: '拘束はあるが点がありません — スケッチ状態が矛盾しています。',
    sketchPreflightLargeConstraintSet: '拘束が非常に多いです — 低スペック端末では解くのに時間がかかることがあります。',
    sketchLargeConstraintInfo: 'スケッチ拘束が非常に多いです。自動求解が遅く感じる場合があります。',
    interferenceRunHeavyHint: 'ペア比較が多く、検査に時間がかかることがあります。保存してから実行してください。',
    camHeavyMeshHint: 'メッシュの頂点が多いです。CAM パス生成・シミュレーションに時間がかかる場合があります。',
    perfSuppressLoadToasts: '負荷・スケッチの案内トーストを出さない（CAM・干渉・多数拘束）',
    composeRefining: 'AI が新しい組み合わせを合成中...',
    composeSearching: 'AI が最適な設計の組み合わせを探索中...',
    composeSubtitle: '部品 · 製法 · 材料マッチング · JSCAD 合成',
    stepExportFeature: 'STEP エクスポート',
    gltfExportFeature: 'GLTF エクスポート',
    dxfExportFeature: 'DXF エクスポート',
    rhinoExportFeature: 'Rhino エクスポート (Team+)',
    grasshopperExportFeature: 'Grasshopper エクスポート (Team+)',
    dfmAnalysisFeature: 'DFM 解析',
    doubleClickSketchHint: '(ダブルクリック=スケッチ)',
    aiShapeGenPanel: '⚙ AI·JSCAD コード形状',
    ideaDesignSource: (label: string) => `アイデア設計: ${label}`,
    unitCostHint: (cost: number | string) => `単価目安 ≈ $${cost}/個`,
    leadTimeHint: (a: number | string, b: number | string) => `納期 ${a}〜${b}日`,
    selectedFaceMsg: (lbl: string, area: string, normal: string) => `[選択面: ${lbl}, 面積 ${area}mm², 法線 (${normal})]`,
    selectedEdgeMsg: (length: string, pos: string) => `[選択エッジ: 長さ ${length}mm, 位置 (${pos})]`,
    useThisFaceAsBase: 'この面を基準に作業してください。',
    addedToFeatureTree: 'フィーチャツリーに追加',
    undoLabel: '元に戻す',
    retryLabel: '再試行',
    booleanApplied: 'Boolean 演算完了',
    booleanFailed: 'Boolean 演算失敗',
    body1: 'ボディ 1',
    bodyGeometryMissing: 'ボディデータなし',
    bodySplitComplete: 'ボディ分割完了',
    splitFailed: '分割失敗',
    mergedBody: '結合ボディ',
    bodiesMerged: 'ボディ結合完了',
    mergeFailed: '結合失敗',
    stlSaved: 'STL 保存済み',
    stlExportFailed: 'STL エクスポート失敗',
    pdfExportFailed: '図面 PDF エクスポート失敗',
    stepExportFailed: 'STEP エクスポート失敗',
    stepExportBundleSuccess: '製造用ZIPをダウンロードしました。展開するとSTEP・STL・JSON・TXTが含まれます。',
    dxfExported: 'DXF エクスポート完了',
    dxfExportFailed: 'DXF エクスポート失敗',
    createShapeFirst: '先に形状を作成してください',
    flatDxfExported: '展開図 DXF エクスポート完了',
    rhinoExported: 'Rhino JSON エクスポート完了',
    rhinoFailed: 'Rhino JSON エクスポート失敗',
    grasshopperExported: 'Grasshopper ポイントエクスポート完了',
    grasshopperFailed: 'Grasshopper エクスポート失敗',
    sceneSaveFailed: 'シーン保存失敗',
    sceneLoadFailed: 'シーン読み込み失敗',
    loadSceneFirst: '先にシーンを読み込んでください',
    glbExportFailed: 'GLB エクスポート失敗',
    printAnalysisComplete: '3D プリント解析完了',
    generateShapeFirst: '先に形状を生成してください',
    alreadyOptimalOrientation: 'すでに最適な方向です',
    exportFailed: 'エクスポート失敗',
    optimalOrientationApplied: '最適方向を適用しました',
    dfmAnalysisComplete: '製造可能性解析完了',
    noGeometryToAnalyze: '解析するジオメトリがありません',
    allFacesModable: 'すべての面が成形可能',
    noRelatedFeature: '関連するフィーチャが見つかりません',
    feaAnalysisComplete: '応力解析完了',
    noInterference: '干渉は検出されませんでした',
    bendApplied: '曲げを適用',
    flangeApplied: 'フランジを適用',
    flatPatternGenerated: '展開図を生成',
    goDesignTabFirst: 'まず Design タブで形状を生成してください。',
    workspaceEmptyNeedShape: (ws: string) =>
      `「${ws}」を使うにはまずソリッドが必要です。左のプリセットを選ぶか S でスケッチを開始してください。`,
    workspaceEmptyGoDesign: '設計へ',
    cadWorkspaceSelectAria: 'ワークスペースを選択',
    optimizeEmptyNeedMesh:
      'トポロジー最適化を行うには Design でソリッドを作成し、固定面と荷重を設定してから Generate を押してください。',
    edgeEditHint: 'エッジをクリックしてフィレット/面取り。中点ドラッグで移動。',
    vertexEditPointerHint: '頂点は左ドラッグで移動（クリックのみでは確定しません）。回転:ホイール押しドラッグ・パン:右ドラッグ。',
    edgeEditPointerHint: 'エッジ中点を左ドラッグ。回転:ホイールドラッグ。Boolean(⊕)はパネルが開きます。',
    booleanPanelOpened: 'Boolean パネルを開きました。演算とツールを選んで適用してください。',
    faceEditHint: '面をクリックして選択、緑の矢印をドラッグして Push/Pull。',
    faceEditViewportCalloutTitle: '面編集 (Push/Pull)',
    faceEditViewportCallout: '① 面をクリック → ② 緑の矢印をドラッグ',
    faceEditViewportCalloutTip:
      '面が選べないときはツールバーで「面」フィルタと「ソリッド」を試してください。スプリング等は左のスライダーでも調整できます。',
    faceEditCalloutDismiss: '閉じる',
    designEditQuickGuide:
      '編集の流れ: 左パネルのスライダー(寸法) · 下の「直接編集」で面/エッジ/頂点(中央3Dをクリック) · 「フィーチャー」タブで押し出し等。面の選択は「ソリッド」表示がおすすめです。',
    designOn3dPc: '3D 設計は PC で',
    mobileHint: 'NexyFab 3D モデリングツールはマウスとキーボードが必要なデスクトップ専用機能です。\nモバイルでは以下の機能をご利用ください。',
    dashboard: 'ダッシュボード',
    checkProjects: 'プロジェクト状況を確認',
    marketplace: 'メーカーマーケット',
    browseMfrs: 'メーカー検索・見積依頼',
    orderTracking: '注文追跡',
    trackMfgProgress: 'リアルタイム製造進捗確認',
    rfqQuotes: 'RFQ 見積',
    manageQuotes: '見積依頼の確認・管理',
    desktopHint: '💻 PC ブラウザで nexyfab.com を開けば\n3D モデリングを開始できます。',
    mobileShareViewTitle: '共有の3Dリンク',
    mobileShareViewBody: '受け取ったURLをアドレスバーに貼り付けると、スマホでも回転・ズームして閲覧できます。編集はPCでお願いします。',
    simpleModeOfferTitle: 'はじめてですか？',
    simpleModeOfferDesc: 'シンプルモードでは高度な解析パネルを抑え、形状と見積に集中できます。',
    simpleModeOfferEnable: 'シンプルモードをオン',
    simpleModeOfferDismiss: 'フル機能のまま',
    simpleModeOfferRegion: 'シンプルモード案内',
    workspaceStatusLabel: '作業ガイド',
    featureSelectedPrefix: '選択中のフィーチャ:',
    measureToolActive: '測定モード — 2点またはエッジをクリックしてください。',
    dropFileHere: 'ファイルをここにドロップ',
    loadingFile: 'ファイル読み込み中...',
    smallScreenDetected: '画面が小さいです',
    smallScreenHint: '全画面モードでより快適に作業できます。',
    goFullscreen: '全画面へ',
    noThanks: 'いいえ',
    stepLoadedIntoViewport: 'STEP 形状をビューポートに読み込みました',
    getQuoteArrow: '見積もり →',
    aiPreviewMode: 'AI プレビューモード',
    aiPreviewHint: '— チャットで適用または取消を選択してください',
    cancelLabel: 'キャンセル',
    viewerOnlyMode: '🔒 ビューア専用モード — 編集は無効です。',
    pluginsLabel: 'プラグイン',
    manageLabel: '管理',
    directEdit: '直接編集:',
    faceEditMode: '面編集 (Push/Pull)',
    vertexEditMode: '頂点編集',
    edgeEditMode: 'エッジ編集',
    doubleClickSketchFace: 'ダブルクリック = 面スケッチ',
    booleanOps: 'Boolean 演算 (Union/Subtract/Intersect)',
    booleanShort: 'Boolean',
    exitEdit: '編集終了',
    depthMm: '深さ (mm)',
    extrude: '押し出し (Extrude)',
    revolve: '回転',
    continueEditing: '編集を続ける',
    sketchClickHint: '最初の点をクリックするか、ダブルクリックでプロファイルを閉じる',
    show3dPreview: '3D プレビュー表示',
    hide3dPreview: '3D プレビュー非表示',
    hideLabel: '非表示',
    viewportPreviewInMain: '3Dビューは中央の作業エリアに表示されます。',
    partPlacement: 'パーツ配置',
    partsLabel: '配置',
    assemblyTools: 'アセンブリツール',
    assemblyShort: 'アセンブリ',
    geometryValidation: 'ジオメトリ検証結果',
    manifold: 'マニホールド',
    closedMesh: '閉じたメッシュ',
    consistentNormals: '一貫した法線',
    openEdges: '開いたエッジ',
    nonManifoldEdges: '非マニホールドエッジ',
    degenerateTri: '退化三角形',
    duplicateVertices: '重複頂点',
    totalTriangles: '合計三角形',
    totalVertices: '合計頂点',
    volumeLabel: '体積',
    surfaceAreaLabel: '表面積',
    issuesLabel: '検査結果',
    standardPartsLibrary: '標準部品ライブラリ',
    fastenersLabel: '締結類',
    structuralLabel: '構造材',
    bearingsLabel: 'ベアリング',
    hexBolt: '六角ボルト',
    hexNut: '六角ナット',
    socketHeadCapScrew: 'ソケットキャップスクリュー',
    flatWasher: '平ワッシャー',
    springWasher: 'スプリングワッシャー',
    iBeam: 'I ビーム',
    angleBracket: 'L アングル',
    channelBeam: 'C チャネル',
    ballBearing: 'ボールベアリング',
    bushing: 'ブッシング',
    screenshotSaved: 'スクリーンショットを保存しました',
    feaRunning: 'FEA 応力解析中...',
    dfmRunning: 'DFM 解析中...',
    csgRunning: 'CSG 演算中...',
    rebuildingGeometry: 'ジオメトリ計算中...',
    occtEngine: 'OCCT トポロジエンジン (実験)',
    suggestionReapplied: '提案を再適用しました',
    noApplicableChanges: '適用する変更がありません',
    selectManufacturer: 'メーカー選択',
    quoteRequestMessage: '見積もりを依頼します。',
    collabPanel: 'コラボレーション',
    pinComments: 'ピンコメント',
    chatLabel: 'チャット',
    ipProtectedShare: 'IP 保護共有リンク',
    ipShareInfo: '72時間有効 · ダウンロード不可 · ウォーターマーク付き',
    linkCopied: 'リンクをコピーしました',
    copyLabel: 'コピー',
    closeLabel: '閉じる',
    optimalStructureDone: '最適構造の生成完了!',
    pcbHeatMappingDone: 'PCB 熱分布マッピング完了!',
    showOriginal: '元を表示',
    showPcbHeatMap: 'PCB 熱分布を表示',
    showOptimized: '最適化結果を表示',
    modalAnalysisDone: 'モーダル解析完了',
    bestParamsApplied: '最適パラメータを適用',
    surfaceAnalysisDone: '曲率解析完了',
    sketchGeometryFailed: 'ジオメトリ生成失敗 — 自己交差または無効な形状を確認してください',
    shapeGeneratedGuide: '3D 形状生成完了!左パネルで材質を選択してエクスポートするか RFQ に送信してください。',
    sketchPlaneSwitched: (plane: string) => `スケッチ平面が ${plane} に切り替えられました。既存の形状は新しい平面にマッピングされます。`,
    sketchRefBadFileType: '参照には画像または STL/STEP/DXF ファイルのみ使用できます。',
    sketchRefLoading: '参照ジオメトリを処理中…',
    importFileMenuHint: '3Dワークスペースへ部品を取り込みます。スケッチの下絵はスケッチタブ→挿入を使ってください。',
    sketchPickFilterAll: 'すべて — 辺の選択と頂点ドラッグ',
    sketchPickFilterSegments: '辺のみ — 頂点ドラッグなし',
    sketchPickFilterPoints: '頂点のみ — 辺の選択なし',
    exitSketchBeforeOptimize: '最適化タブに移動する前にスケッチモードを終了してください。現在のスケッチは保持されます。',
    mateCoincident: '面一致',
    mateConcentric: '同軸',
    mateDistance: '距離',
    feaUpgradeFeature: 'FEA 応力解析',
    brokenExpression: (key: string, expression: string, missing: string, extra: number) =>
      `式依存関係切断: '${key}' = '${expression}' (欠落変数: ${missing}${extra > 0 ? ` 他 ${extra} 件` : ''})`,
    cannotApplyFeature: (msg: string) => `フィーチャを適用できません: ${msg}`,
    featureFailed: (label: string, hint: string) => `⚠ ${label} 実行失敗 — ${hint}`,
    branchCreated: (name: string) => `ブランチ "${name}" を作成`,
    branchSwitched: (name: string) => `ブランチ "${name}" に切り替え`,
    branchDeleted: (name: string) => `ブランチ "${name}" を削除`,
    branchMerged: (src: string, tgt: string) => `"${src}" -> "${tgt}" マージ完了`,
    pipelineFailed: (msg: string) => `ジオメトリ計算失敗: ${msg}`,
    shapeNotFound: (id: string) => `形状 "${id}" が見つかりません`,
    sketchEmpty: (where: string) => `スケッチが空です${where}`,
    sketchTooFew: (where: string) => `3 セグメント以上必要です${where}`,
    sketchGap: (where: string) => `プロファイルが閉じていません — 終点を始点に接続してください${where}`,
    sketchNotClosed: (where: string) => `プロファイルを閉じてください${where}`,
    aiAppliedChanges: (count: number) => `AI 変更 ${count} 件適用`,
    shapeFromText: (id: string) => `"${id}" 形状をテキストから生成しました`,
    mateAdded: (label: string, a: string, b: string) => `${label} メイト追加 (${a} ↔ ${b})`,
    flatDxfFailed: (msg: string) => `展開図 DXF 失敗: ${msg}`,
    gcodeGenerated: (post: string, passes: number, lines: number, time: number, warning: string) =>
      `G-code 生成完了 (${post}) — ${passes} パス、${lines} 行、予想 ${time} 分${warning ? ` ⚠ ${warning}` : ''}`,
    orientationSaves: (label: string, pct: number) => `${label} 方向推奨 — サポート ${pct}% 削減`,
    printReadyDownloaded: 'スライサー用ファイルをダウンロードしました (.stl + .3mf)',
    dfmFailed: (msg: string) => `DFM 解析失敗: ${msg}`,
    autoFixApplied: (label: string) => `自動修正適用: ${label}`,
    aiAnalysisFailed: (msg: string) => `AI 解析失敗: ${msg}`,
    undercutsDetected: (count: string) => `アンダーカット ${count} 個検出`,
    facesNeedDraft: (count: string) => `抜き勾配不足 ${count} 面`,
    draftFailed: (msg: string) => `抜き勾配解析失敗: ${msg}`,
    jumpToFeature: (type: string) => `フィーチャに移動: ${type}`,
    noFeatureInTree: (list: string) => `'${list}' フィーチャがありません — 追加してみてください`,
    feaFailed: (msg: string) => `FEA 解析失敗: ${msg}`,
    interferenceFound: (n: number) => `${n} 件の干渉が検出されました`,
    interferenceFailed: (msg: string) => `干渉検査失敗: ${msg}`,
    interferenceCancelled: '干渉チェックをキャンセルしました。',
    interferenceTimelineLabel: '干渉チェック',
    importFailed: (msg: string) => `読み込み失敗: ${msg}`,
    designApplied: (summary: string) => `✅ 設計適用${summary ? ` (${summary})` : ''} — DFM 自動解析中`,
    importedFile: (name: string) => `"${name}" 読み込み完了`,
    importFailedFile: (msg: string) => `ファイル読み込み失敗: ${msg}`,
    cotsAddedToBom: (name: string) => `${name} を BOM に追加`,
    standardHoleAdded: (d: string) => `標準規格ホール追加 (Ø${d}mm)`,
    versionSaved: (name: string) => `💾 "${name}" 保存`,
    versionApplied: (name: string) => `↻ "${name}" 適用`,
    partLoaded: (name: string) => `📚 "${name}" 読み込み`,
    processMatchingSuppliers: (p: string) => `${p} 工程 → サプライヤーマッチング開始`,
    rfqSent: (mfr: string, qty: number) => `${mfr} に RFQ 送信完了 (${qty} 個)`,
    materialSwitched: (id: string) => `材料を ${id} に変更しました`,
    aiShapeGenerated: (desc: string) => `AI 形状生成完了: ${desc}…`,
    quoteRequestSent: (name: string) => `${name} に見積依頼を送信しました`,
    thermalFeaDone: '熱解析完了 — 3D ビューに温度分布が表示されます',
    quoteRequested: (id: string) => `メーカー ${id} に見積依頼`,
    designFailed: (err: string) => `設計生成失敗: ${err}`,
    networkError: (err: string) => `ネットワークエラー: ${err}`,
  },
  cn: {
    assemblyLabel: '装配',
    remoteResolvedComment: '✅ 远程用户已解决评论。',
    mentionedYou: '提到了你',
    invalidShareLink: '无效的分享链接',
    designLoaded: '已加载设计',
    designLoadFailed: '加载设计失败',
    sharedModelLoaded: '已加载共享模型',
    sharedModelLoadFailed: '加载共享模型失败',
    snapshotSaved: '已保存快照',
    versionRestored: '已还原版本',
    featureCannotRestore: '无法还原特征',
    featureRestored: '已还原特征',
    closeProfileFirst: '请先关闭剖面',
    sketchModeExitPreserved: '已退出草图模式。草图内容已保留。按 S 重新进入。',
    sketchPreflightPointsNoConstraints: '有点无约束 — 几何可能漂移。',
    sketchPreflightConstraintsNoPoints: '有约束无点 — 草图状态不一致。',
    sketchPreflightLargeConstraintSet: '约束非常多 — 在低配设备上求解可能较慢。',
    sketchLargeConstraintInfo: '草图约束过多，自动求解可能较慢。',
    interferenceRunHeavyHint: '成对比较很多，检查可能较久。请先保存再运行。',
    camHeavyMeshHint: '网格顶点很多，CAM 生成与仿真可能较久。',
    perfSuppressLoadToasts: '关闭负载/草图提示（CAM、干涉、大量约束）',
    composeRefining: 'AI 正在合成新组合...',
    composeSearching: 'AI 正在寻找最佳设计组合...',
    composeSubtitle: '零件 · 工艺 · 材料匹配 · JSCAD 合成',
    stepExportFeature: 'STEP 导出',
    gltfExportFeature: 'GLTF 导出',
    dxfExportFeature: 'DXF 导出',
    rhinoExportFeature: 'Rhino 导出 (Team+)',
    grasshopperExportFeature: 'Grasshopper 导出 (Team+)',
    dfmAnalysisFeature: 'DFM 分析',
    doubleClickSketchHint: '(双击=草图)',
    aiShapeGenPanel: '⚙ AI·JSCAD 代码形状',
    ideaDesignSource: (label: string) => `创意设计: ${label}`,
    unitCostHint: (cost: number | string) => `预计单价 ≈ $${cost}/件`,
    leadTimeHint: (a: number | string, b: number | string) => `交期 ${a}~${b} 天`,
    selectedFaceMsg: (lbl: string, area: string, normal: string) => `[选中面: ${lbl}, 面积 ${area}mm², 法线 (${normal})]`,
    selectedEdgeMsg: (length: string, pos: string) => `[选中边: 长度 ${length}mm, 位置 (${pos})]`,
    useThisFaceAsBase: '请以此面为基准进行操作。',
    addedToFeatureTree: '已添加到特征树',
    undoLabel: '撤销',
    retryLabel: '重试',
    booleanApplied: 'Boolean 运算完成',
    booleanFailed: 'Boolean 运算失败',
    body1: '实体 1',
    bodyGeometryMissing: '未找到实体数据',
    bodySplitComplete: '实体分离完成',
    splitFailed: '分离失败',
    mergedBody: '合并实体',
    bodiesMerged: '实体合并完成',
    mergeFailed: '合并失败',
    stlSaved: 'STL 已保存',
    stlExportFailed: 'STL 导出失败',
    pdfExportFailed: '图纸 PDF 导出失败',
    stepExportFailed: 'STEP 导出失败',
    stepExportBundleSuccess: '已下载制造包（ZIP），解压后含 STEP、STL、JSON、TXT。',
    dxfExported: 'DXF 导出完成',
    dxfExportFailed: 'DXF 导出失败',
    createShapeFirst: '请先创建形状',
    flatDxfExported: '展开图 DXF 导出完成',
    rhinoExported: 'Rhino JSON 导出完成',
    rhinoFailed: 'Rhino JSON 导出失败',
    grasshopperExported: 'Grasshopper 点导出完成',
    grasshopperFailed: 'Grasshopper 导出失败',
    sceneSaveFailed: '场景保存失败',
    sceneLoadFailed: '场景加载失败',
    loadSceneFirst: '请先加载场景',
    glbExportFailed: 'GLB 导出失败',
    printAnalysisComplete: '3D 打印分析完成',
    generateShapeFirst: '请先生成形状',
    alreadyOptimalOrientation: '已经是最佳方向',
    exportFailed: '导出失败',
    optimalOrientationApplied: '已应用最佳方向',
    dfmAnalysisComplete: '可制造性分析完成',
    noGeometryToAnalyze: '没有可分析的几何体',
    allFacesModable: '所有面均可成型',
    noRelatedFeature: '未找到相关特征',
    feaAnalysisComplete: '应力分析完成',
    noInterference: '未检测到干涉',
    bendApplied: '已应用弯曲',
    flangeApplied: '已应用折边',
    flatPatternGenerated: '已生成展开图',
    goDesignTabFirst: '请先在 Design 标签页生成形状。',
    workspaceEmptyNeedShape: (ws: string) =>
      `使用「${ws}」前请先创建实体 — 在左侧选择预设或按 S 开始草图。`,
    workspaceEmptyGoDesign: '设计',
    cadWorkspaceSelectAria: '选择 CAD 工作区',
    optimizeEmptyNeedMesh:
      '要进行拓扑优化，请先在「设计」标签生成实体，设置固定面和载荷后点击 Generate。',
    edgeEditHint: '点击边进行圆角/倒角。拖动中点进行移动。',
    vertexEditPointerHint: '顶点需按住左键拖动才能移动（单击不会提交）。旋转：按住滚轮拖动 · 平移：右键拖动。',
    edgeEditPointerHint: '拖动边中点。旋转：滚轮拖动。Boolean(⊕) 会打开面板。',
    booleanPanelOpened: '已打开 Boolean 面板 — 选择运算与工具后点击应用。',
    faceEditHint: '点击面选择,拖动绿色箭头进行 Push/Pull。',
    faceEditViewportCalloutTitle: '面编辑 (Push/Pull)',
    faceEditViewportCallout: '① 点击面 → ② 拖动绿色箭头',
    faceEditViewportCalloutTip:
      '若选不中面，请在工具栏开启「面」筛选并尝试「实体」显示。弹簧等也可用左侧滑块调整。',
    faceEditCalloutDismiss: '关闭',
    designEditQuickGuide:
      '如何修改: 左侧面板滑块(尺寸) · 下方「直接编辑」选面/边/顶点(点击中间 3D) ·「特征」选项卡做拉伸等。选面建议用「实体」显示模式。',
    designOn3dPc: '3D 设计请在 PC 上',
    mobileHint: 'NexyFab 3D 建模工具需要鼠标和键盘,是桌面专用功能。\n手机上请使用以下功能。',
    dashboard: '仪表板',
    checkProjects: '查看项目状况',
    marketplace: '制造商市场',
    browseMfrs: '搜索制造商 & 请求报价',
    orderTracking: '订单跟踪',
    trackMfgProgress: '实时制造进度查询',
    rfqQuotes: 'RFQ 报价',
    manageQuotes: '查看和管理报价',
    desktopHint: '💻 在 PC 浏览器打开 nexyfab.com\n即可开始 3D 建模。',
    mobileShareViewTitle: '查看分享的 3D 链接',
    mobileShareViewBody: '将收到的完整链接粘贴到浏览器地址栏，即可在手机旋转、缩放查看。编辑请在电脑上进行。',
    simpleModeOfferTitle: '第一次使用？',
    simpleModeOfferDesc: '简洁模式会隐藏部分高级分析面板，便于专注建模与报价。',
    simpleModeOfferEnable: '开启简洁模式',
    simpleModeOfferDismiss: '保持完整工作区',
    simpleModeOfferRegion: '简洁模式提示',
    workspaceStatusLabel: '操作提示',
    featureSelectedPrefix: '已选特征:',
    measureToolActive: '测量模式 — 请点击两点或边。',
    dropFileHere: '将文件拖放到此处',
    loadingFile: '正在加载文件...',
    smallScreenDetected: '屏幕较小',
    smallScreenHint: '全屏模式体验更佳。',
    goFullscreen: '切换全屏',
    noThanks: '不用了',
    stepLoadedIntoViewport: 'STEP 形状已加载到视口',
    getQuoteArrow: '获取报价 →',
    aiPreviewMode: 'AI 预览模式',
    aiPreviewHint: '— 请在聊天面板选择应用或取消',
    cancelLabel: '取消',
    viewerOnlyMode: '🔒 仅查看模式 — 编辑已禁用。',
    pluginsLabel: '插件',
    manageLabel: '管理',
    directEdit: '直接编辑:',
    faceEditMode: '面编辑 (Push/Pull)',
    vertexEditMode: '顶点编辑',
    edgeEditMode: '边编辑',
    doubleClickSketchFace: '双击 = 在面上草图',
    booleanOps: 'Boolean 运算 (Union/Subtract/Intersect)',
    booleanShort: 'Boolean',
    exitEdit: '退出编辑',
    depthMm: '深度 (mm)',
    extrude: '拉伸 (Extrude)',
    revolve: '旋转',
    continueEditing: '继续编辑',
    sketchClickHint: '点击第一个点或双击以闭合剖面',
    show3dPreview: '显示 3D 预览',
    hide3dPreview: '隐藏 3D 预览',
    hideLabel: '隐藏',
    viewportPreviewInMain: '3D 视图显示在中央工作区。',
    partPlacement: '零件放置',
    partsLabel: '放置',
    assemblyTools: '装配工具',
    assemblyShort: '装配',
    geometryValidation: '几何验证结果',
    manifold: '流形',
    closedMesh: '封闭网格',
    consistentNormals: '一致法线',
    openEdges: '开放边',
    nonManifoldEdges: '非流形边',
    degenerateTri: '退化三角形',
    duplicateVertices: '重复顶点',
    totalTriangles: '总三角形',
    totalVertices: '总顶点',
    volumeLabel: '体积',
    surfaceAreaLabel: '表面积',
    issuesLabel: '检测结果',
    standardPartsLibrary: '标准件库',
    fastenersLabel: '紧固件',
    structuralLabel: '结构件',
    bearingsLabel: '轴承',
    hexBolt: '六角螺栓',
    hexNut: '六角螺母',
    socketHeadCapScrew: '内六角螺钉',
    flatWasher: '平垫圈',
    springWasher: '弹簧垫圈',
    iBeam: 'I 梁',
    angleBracket: 'L 角铁',
    channelBeam: 'C 槽钢',
    ballBearing: '球轴承',
    bushing: '衬套',
    screenshotSaved: '截图已保存',
    feaRunning: 'FEA 应力分析中...',
    dfmRunning: 'DFM 分析中...',
    csgRunning: 'CSG 运算中...',
    rebuildingGeometry: '正在重建几何...',
    occtEngine: 'OCCT 拓扑引擎 (实验)',
    suggestionReapplied: '已重新应用建议',
    noApplicableChanges: '无可应用的变更',
    selectManufacturer: '选择制造商',
    quoteRequestMessage: '请求报价。',
    collabPanel: '协作',
    pinComments: '图钉评论',
    chatLabel: '聊天',
    ipProtectedShare: 'IP 保护分享链接',
    ipShareInfo: '72 小时 · 不可下载 · 含水印',
    linkCopied: '已复制链接',
    copyLabel: '复制',
    closeLabel: '关闭',
    optimalStructureDone: '最优结构生成完成!',
    pcbHeatMappingDone: 'PCB 热分布映射完成!',
    showOriginal: '显示原图',
    showPcbHeatMap: '显示 PCB 热图',
    showOptimized: '显示优化结果',
    modalAnalysisDone: '模态分析完成',
    bestParamsApplied: '已应用最优参数',
    surfaceAnalysisDone: '曲率分析完成',
    sketchGeometryFailed: '几何生成失败 — 请检查自相交或无效形状',
    shapeGeneratedGuide: '3D 形状生成完成!在左侧面板选择材料,然后导出或发送到 RFQ。',
    sketchPlaneSwitched: (plane: string) => `草图平面切换到 ${plane}。现有形状将映射到新平面。`,
    sketchRefBadFileType: '参考底图请使用图片或 STL/STEP/DXF 文件。',
    sketchRefLoading: '正在处理参考几何…',
    importFileMenuHint: '将零件几何导入三维工作区。草图描图底图请用「草图」选项卡 →「插入」。',
    sketchPickFilterAll: '全部 — 选边并可拖顶点',
    sketchPickFilterSegments: '仅边 — 不拖顶点',
    sketchPickFilterPoints: '仅顶点 — 不选边',
    exitSketchBeforeOptimize: '请在切换到优化标签前退出草图模式。您的草图将被保留。',
    mateCoincident: '重合',
    mateConcentric: '同轴',
    mateDistance: '距离',
    feaUpgradeFeature: 'FEA 应力分析',
    brokenExpression: (key: string, expression: string, missing: string, extra: number) =>
      `表达式依赖断开: '${key}' = '${expression}' (缺失变量: ${missing}${extra > 0 ? ` 及其他 ${extra} 个` : ''})`,
    cannotApplyFeature: (msg: string) => `无法应用特征: ${msg}`,
    featureFailed: (label: string, hint: string) => `⚠ ${label} 执行失败 — ${hint}`,
    branchCreated: (name: string) => `已创建分支 "${name}"`,
    branchSwitched: (name: string) => `已切换到分支 "${name}"`,
    branchDeleted: (name: string) => `已删除分支 "${name}"`,
    branchMerged: (src: string, tgt: string) => `"${src}" -> "${tgt}" 合并完成`,
    pipelineFailed: (msg: string) => `几何计算失败: ${msg}`,
    shapeNotFound: (id: string) => `未找到形状 "${id}"`,
    sketchEmpty: (where: string) => `草图为空${where}`,
    sketchTooFew: (where: string) => `至少需要 3 段线段${where}`,
    sketchGap: (where: string) => `剖面未闭合 — 终点未与起点连接${where}`,
    sketchNotClosed: (where: string) => `请闭合剖面${where}`,
    aiAppliedChanges: (count: number) => `AI 应用了 ${count} 处变更`,
    shapeFromText: (id: string) => `"${id}" 形状已从文本生成`,
    mateAdded: (label: string, a: string, b: string) => `${label} 配合已添加 (${a} ↔ ${b})`,
    flatDxfFailed: (msg: string) => `展开图 DXF 失败: ${msg}`,
    gcodeGenerated: (post: string, passes: number, lines: number, time: number, warning: string) =>
      `G-code 生成完成 (${post}) — ${passes} 条路径, ${lines} 行, 预计 ${time} 分钟${warning ? ` ⚠ ${warning}` : ''}`,
    orientationSaves: (label: string, pct: number) => `推荐 ${label} 方向 — 支撑减少 ${pct}%`,
    printReadyDownloaded: '已下载切片文件 (.stl + .3mf)',
    dfmFailed: (msg: string) => `DFM 分析失败: ${msg}`,
    autoFixApplied: (label: string) => `自动修复已应用: ${label}`,
    aiAnalysisFailed: (msg: string) => `AI 分析失败: ${msg}`,
    undercutsDetected: (count: string) => `检测到 ${count} 个底切面`,
    facesNeedDraft: (count: string) => `${count} 个面需要更多拔模`,
    draftFailed: (msg: string) => `拔模分析失败: ${msg}`,
    jumpToFeature: (type: string) => `跳转到特征: ${type}`,
    noFeatureInTree: (list: string) => `特征树中没有 '${list}' — 尝试添加一个`,
    feaFailed: (msg: string) => `FEA 分析失败: ${msg}`,
    interferenceFound: (n: number) => `发现 ${n} 处干涉`,
    interferenceFailed: (msg: string) => `干涉检查失败: ${msg}`,
    interferenceCancelled: '已取消干涉检查。',
    interferenceTimelineLabel: '干涉检查',
    importFailed: (msg: string) => `导入失败: ${msg}`,
    designApplied: (summary: string) => `✅ 设计已应用${summary ? ` (${summary})` : ''} — DFM 自动分析中`,
    importedFile: (name: string) => `已导入 "${name}"`,
    importFailedFile: (msg: string) => `文件导入失败: ${msg}`,
    cotsAddedToBom: (name: string) => `${name} 已添加到 BOM`,
    standardHoleAdded: (d: string) => `已添加标准孔 (Ø${d}mm)`,
    versionSaved: (name: string) => `💾 已保存 "${name}"`,
    versionApplied: (name: string) => `↻ 已应用 "${name}"`,
    partLoaded: (name: string) => `📚 已加载 "${name}"`,
    processMatchingSuppliers: (p: string) => `${p} 工序 → 开始匹配供应商`,
    rfqSent: (mfr: string, qty: number) => `已向 ${mfr} 发送 RFQ (${qty} 件)`,
    materialSwitched: (id: string) => `材料已切换为 ${id}`,
    aiShapeGenerated: (desc: string) => `AI 形状生成完成: ${desc}…`,
    quoteRequestSent: (name: string) => `已向 ${name} 发送报价请求`,
    thermalFeaDone: '热分析完成 — 3D 视图中显示温度分布',
    quoteRequested: (id: string) => `已向制造商 ${id} 请求报价`,
    designFailed: (err: string) => `设计生成失败: ${err}`,
    networkError: (err: string) => `网络错误: ${err}`,
  },
  es: {
    assemblyLabel: 'Ensamblaje',
    remoteResolvedComment: '✅ Un colaborador resolvió un comentario.',
    mentionedYou: 'te mencionó',
    invalidShareLink: 'Enlace compartido no válido',
    designLoaded: 'Diseño cargado desde la nube',
    designLoadFailed: 'Error al cargar el diseño',
    sharedModelLoaded: 'Modelo compartido cargado',
    sharedModelLoadFailed: 'Error al cargar el modelo compartido',
    snapshotSaved: 'Instantánea guardada',
    versionRestored: 'Versión restaurada',
    featureCannotRestore: 'No se puede restaurar la feature',
    featureRestored: 'Feature restaurada',
    closeProfileFirst: 'Cierre el perfil primero',
    sketchModeExitPreserved: 'Modo de croquis cerrado. Su croquis se conserva. Pulse S para volver a entrar.',
    sketchPreflightPointsNoConstraints: 'Hay puntos pero sin restricciones — la geometría puede moverse.',
    sketchPreflightConstraintsNoPoints: 'Hay restricciones pero sin puntos — estado de croquis inconsistente.',
    sketchPreflightLargeConstraintSet: 'Muchas restricciones — la resolución puede ser lenta en equipos modestos.',
    sketchLargeConstraintInfo: 'Muchas restricciones de croquis — la resolución automática puede ir más lenta.',
    interferenceRunHeavyHint: 'Muchas comparaciones — la comprobación puede tardar. Guarde antes de ejecutar.',
    camHeavyMeshHint: 'Malla con muchos vértices — el CAM y la simulación pueden tardar más.',
    perfSuppressLoadToasts: 'Ocultar avisos de carga/boceto (CAM, interferencia, muchas restricciones)',
    composeRefining: 'La IA está sintetizando una nueva combinación...',
    composeSearching: 'La IA está encontrando la mejor combinación de diseño...',
    composeSubtitle: 'Piezas · Proceso · Material · Síntesis JSCAD',
    stepExportFeature: 'Exportación STEP',
    gltfExportFeature: 'Exportación GLTF',
    dxfExportFeature: 'Exportación DXF',
    rhinoExportFeature: 'Exportación Rhino (Team+)',
    grasshopperExportFeature: 'Exportación Grasshopper (Team+)',
    dfmAnalysisFeature: 'Análisis DFM',
    doubleClickSketchHint: '(doble clic = croquis)',
    aiShapeGenPanel: '⚙ IA + JSCAD',
    ideaDesignSource: (label: string) => `Diseño de idea: ${label}`,
    unitCostHint: (cost: number | string) => `Costo unit. est. ≈ $${cost}/ud`,
    leadTimeHint: (a: number | string, b: number | string) => `Plazo ${a}–${b} días`,
    selectedFaceMsg: (lbl: string, area: string, normal: string) => `[Cara seleccionada: ${lbl}, área ${area}mm², normal (${normal})]`,
    selectedEdgeMsg: (length: string, pos: string) => `[Arista seleccionada: longitud ${length}mm, posición (${pos})]`,
    useThisFaceAsBase: 'Por favor, usa esta cara como referencia.',
    addedToFeatureTree: 'Añadido al árbol de features',
    undoLabel: 'Deshacer',
    retryLabel: 'Reintentar',
    booleanApplied: 'Operación Boolean aplicada',
    booleanFailed: 'Operación Boolean fallida',
    body1: 'Cuerpo 1',
    bodyGeometryMissing: 'Geometría del cuerpo no encontrada',
    bodySplitComplete: 'División del cuerpo completa',
    splitFailed: 'División fallida',
    mergedBody: 'Cuerpo Fusionado',
    bodiesMerged: 'Cuerpos fusionados',
    mergeFailed: 'Fusión fallida',
    stlSaved: 'STL guardado',
    stlExportFailed: 'Exportación STL fallida',
    pdfExportFailed: 'Exportación PDF fallida',
    stepExportFailed: 'Exportación STEP fallida',
    stepExportBundleSuccess: 'Paquete ZIP de fabricación descargado (STEP, STL, JSON, TXT al descomprimir).',
    dxfExported: 'DXF exportado correctamente',
    dxfExportFailed: 'Exportación DXF fallida',
    createShapeFirst: 'Cree una forma primero',
    flatDxfExported: 'Patrón plano DXF exportado',
    rhinoExported: 'Rhino JSON exportado correctamente',
    rhinoFailed: 'Exportación Rhino JSON fallida',
    grasshopperExported: 'Puntos Grasshopper exportados',
    grasshopperFailed: 'Exportación Grasshopper fallida',
    sceneSaveFailed: 'Error al guardar la escena',
    sceneLoadFailed: 'Error al importar la escena',
    loadSceneFirst: 'Cargue una escena primero',
    glbExportFailed: 'Exportación GLB fallida',
    printAnalysisComplete: 'Análisis de impresión 3D completo',
    generateShapeFirst: 'Genere una forma primero',
    alreadyOptimalOrientation: 'Ya está en orientación óptima',
    exportFailed: 'Exportación fallida',
    optimalOrientationApplied: 'Orientación óptima aplicada',
    dfmAnalysisComplete: 'Análisis DFM completo',
    noGeometryToAnalyze: 'No hay geometría para analizar',
    allFacesModable: 'Todas las caras son moldeables',
    noRelatedFeature: 'No se encontró feature relacionada',
    feaAnalysisComplete: 'Análisis FEA completo',
    noInterference: 'No se detectó interferencia',
    bendApplied: 'Doblado aplicado',
    flangeApplied: 'Brida aplicada',
    flatPatternGenerated: 'Patrón plano generado',
    goDesignTabFirst: 'Vaya a la pestaña Design primero para generar una forma.',
    workspaceEmptyNeedShape: (ws: string) =>
      `Necesita un sólido antes de usar “${ws}”: elija un preset a la izquierda o pulse S para dibujar.`,
    workspaceEmptyGoDesign: 'Diseño',
    cadWorkspaceSelectAria: 'Seleccionar espacio de trabajo CAD',
    optimizeEmptyNeedMesh:
      'Para optimizar topología, cree un sólido en Design, fije caras y cargas, luego pulse Generate.',
    edgeEditHint: 'Haga clic en el borde para filete/chaflán. Arrastre el punto medio para mover.',
    vertexEditPointerHint: 'Arrastre un vértice con el botón izquierdo (un clic no confirma). Órbita: botón central · Pan: derecho.',
    edgeEditPointerHint: 'Arrastre el punto medio de la arista. Órbita: botón central. Boolean (⊕) abre un panel.',
    booleanPanelOpened: 'Panel Boolean abierto: elija operación y herramienta, luego Aplicar.',
    faceEditHint: 'Haga clic en la cara para seleccionar, arrastre la flecha verde para Push/Pull.',
    faceEditViewportCalloutTitle: 'Edición de cara (Push/Pull)',
    faceEditViewportCallout: '① Clic en cara → ② Arrastre la flecha verde',
    faceEditViewportCalloutTip:
      'Active el filtro Cara y la vista Sólido. Resortes y plantillas: también deslizadores izquierdos.',
    faceEditCalloutDismiss: 'Cerrar',
    designEditQuickGuide:
      'Cómo editar: deslizadores del panel izquierdo (tamaño) · «Edición directa» abajo para cara/arista/vértice (clic en el 3D central) · pestaña «Features» para extruir, etc. Modo sólido facilita elegir caras.',
    designOn3dPc: 'Diseño 3D en Escritorio',
    mobileHint: 'El modelador 3D NexyFab requiere ratón y teclado.\nUse un navegador de escritorio para la experiencia completa.',
    dashboard: 'Panel',
    checkProjects: 'Revisar sus proyectos',
    marketplace: 'Marketplace',
    browseMfrs: 'Explorar fabricantes y cotizar',
    orderTracking: 'Seguimiento de Pedidos',
    trackMfgProgress: 'Seguir el progreso de fabricación',
    rfqQuotes: 'Cotizaciones RFQ',
    manageQuotes: 'Ver y gestionar cotizaciones',
    desktopHint: '💻 Abra nexyfab.com en un navegador de escritorio\npara empezar con el modelado 3D.',
    mobileShareViewTitle: 'Ver enlace 3D compartido',
    mobileShareViewBody: 'Pegue la URL completa en la barra de direcciones: puede orbitar y hacer zoom en el móvil. La edición completa es en escritorio.',
    simpleModeOfferTitle: '¿Primera vez?',
    simpleModeOfferDesc: 'El modo simple oculta paneles avanzados para centrarse en la forma y el presupuesto.',
    simpleModeOfferEnable: 'Activar modo simple',
    simpleModeOfferDismiss: 'Mantener todo',
    simpleModeOfferRegion: 'Sugerencia de modo simple',
    workspaceStatusLabel: 'Guía del espacio de trabajo',
    featureSelectedPrefix: 'Función seleccionada:',
    measureToolActive: 'Modo medida — haga clic en dos puntos o aristas.',
    dropFileHere: 'Suelte el archivo aquí',
    loadingFile: 'Cargando archivo...',
    smallScreenDetected: 'Pantalla Pequeña Detectada',
    smallScreenHint: 'Cambie a pantalla completa para una mejor experiencia.',
    goFullscreen: 'Pantalla Completa',
    noThanks: 'No gracias',
    stepLoadedIntoViewport: 'Geometría STEP cargada en el viewport',
    getQuoteArrow: 'Obtener Cotización →',
    aiPreviewMode: 'Modo Vista Previa IA',
    aiPreviewHint: '— Elija Aplicar o Cancelar en el panel de chat',
    cancelLabel: 'Cancelar',
    viewerOnlyMode: '🔒 Modo Solo Vista — La edición está deshabilitada.',
    pluginsLabel: 'Plugins',
    manageLabel: 'Gestionar',
    directEdit: 'Edición Directa:',
    faceEditMode: 'Edición de Cara (Push/Pull)',
    vertexEditMode: 'Edición de Vértice',
    edgeEditMode: 'Edición de Borde',
    doubleClickSketchFace: 'Doble clic = Sketch en cara',
    booleanOps: 'Operaciones Boolean (Union/Subtract/Intersect)',
    booleanShort: 'Boolean',
    exitEdit: 'Salir de Edición',
    depthMm: 'Profundidad (mm)',
    extrude: 'Extruir',
    revolve: 'Revolucionar',
    continueEditing: 'Continuar Editando',
    sketchClickHint: 'Haga clic en el primer punto o doble clic para cerrar el perfil',
    show3dPreview: 'Mostrar Vista Previa 3D',
    hide3dPreview: 'Ocultar Vista Previa 3D',
    hideLabel: 'Ocultar',
    viewportPreviewInMain: 'La vista 3D se muestra en el área de trabajo principal.',
    partPlacement: 'Colocación de Partes',
    partsLabel: 'Partes',
    assemblyTools: 'Herramientas de Ensamblaje',
    assemblyShort: 'Ensamblaje',
    geometryValidation: 'Validación de Geometría',
    manifold: 'Variedad',
    closedMesh: 'Cerrado',
    consistentNormals: 'Normales Consistentes',
    openEdges: 'Bordes Abiertos',
    nonManifoldEdges: 'Bordes No Variedad',
    degenerateTri: 'Tri Degenerado',
    duplicateVertices: 'Vértices Duplicados',
    totalTriangles: 'Total Triángulos',
    totalVertices: 'Total Vértices',
    volumeLabel: 'Volumen',
    surfaceAreaLabel: 'Área de Superficie',
    issuesLabel: 'Problemas',
    standardPartsLibrary: 'Biblioteca de Partes Estándar',
    fastenersLabel: 'Fijaciones',
    structuralLabel: 'Estructural',
    bearingsLabel: 'Rodamientos',
    hexBolt: 'Perno Hexagonal',
    hexNut: 'Tuerca Hexagonal',
    socketHeadCapScrew: 'Tornillo Allen',
    flatWasher: 'Arandela Plana',
    springWasher: 'Arandela de Presión',
    iBeam: 'Viga I',
    angleBracket: 'Ángulo',
    channelBeam: 'Canal',
    ballBearing: 'Rodamiento de Bolas',
    bushing: 'Casquillo',
    screenshotSaved: 'Captura de pantalla guardada',
    feaRunning: 'FEA ejecutándose...',
    dfmRunning: 'DFM ejecutándose...',
    csgRunning: 'CSG ejecutándose...',
    rebuildingGeometry: 'Reconstruyendo geometría...',
    occtEngine: 'Motor de topología OCCT (experimental)',
    suggestionReapplied: 'Sugerencia re-aplicada',
    noApplicableChanges: 'No hay cambios aplicables',
    selectManufacturer: 'Seleccionar Fabricante',
    quoteRequestMessage: 'Me gustaría solicitar una cotización.',
    collabPanel: 'Colaboración',
    pinComments: 'Comentarios',
    chatLabel: 'Chat',
    ipProtectedShare: 'Enlace Compartido Protegido IP',
    ipShareInfo: '72 hrs · Sin descarga · Con marca de agua',
    linkCopied: 'Enlace copiado',
    copyLabel: 'Copiar',
    closeLabel: 'Cerrar',
    optimalStructureDone: '¡Estructura óptima generada!',
    pcbHeatMappingDone: '¡Mapeo térmico PCB completo!',
    showOriginal: 'Mostrar Original',
    showPcbHeatMap: 'Mostrar Mapa Térmico PCB',
    showOptimized: 'Mostrar Optimizado',
    modalAnalysisDone: 'Análisis modal completo',
    bestParamsApplied: 'Mejores parámetros aplicados',
    surfaceAnalysisDone: 'Análisis de superficie completo',
    sketchGeometryFailed: 'Error al construir geometría — verifique autointersección o forma inválida',
    shapeGeneratedGuide: '¡Forma 3D generada! Seleccione un material en el panel izquierdo, luego exporte o envíe a RFQ.',
    sketchPlaneSwitched: (plane: string) => `Plano de sketch cambiado a ${plane}. El perfil existente se remapea al nuevo plano.`,
    sketchRefBadFileType: 'Use una imagen o un archivo STL/STEP/DXF como referencia.',
    sketchRefLoading: 'Procesando geometría de referencia…',
    importFileMenuHint: 'Importa la pieza al espacio 3D. Para trazar en boceto, use la pestaña Boceto → Insertar.',
    sketchPickFilterAll: 'Todo — aristas y vértices',
    sketchPickFilterSegments: 'Solo aristas — sin arrastrar vértices',
    sketchPickFilterPoints: 'Solo vértices — sin seleccionar aristas',
    exitSketchBeforeOptimize: 'Salga del modo sketch antes de cambiar a Optimize. Su sketch se conservará.',
    mateCoincident: 'Coincidente',
    mateConcentric: 'Concéntrico',
    mateDistance: 'Distancia',
    feaUpgradeFeature: 'Análisis FEA',
    brokenExpression: (key: string, expression: string, missing: string, extra: number) =>
      `Expresión rota: '${key}' = '${expression}' (faltantes: ${missing}${extra > 0 ? ` +${extra} más` : ''})`,
    cannotApplyFeature: (msg: string) => `No se puede aplicar feature: ${msg}`,
    featureFailed: (label: string, hint: string) => `⚠ ${label} falló — ${hint}`,
    branchCreated: (name: string) => `Rama "${name}" creada`,
    branchSwitched: (name: string) => `Cambiado a rama "${name}"`,
    branchDeleted: (name: string) => `Rama "${name}" eliminada`,
    branchMerged: (src: string, tgt: string) => `Fusionado "${src}" en "${tgt}"`,
    pipelineFailed: (msg: string) => `Pipeline de geometría falló: ${msg}`,
    shapeNotFound: (id: string) => `Forma "${id}" no encontrada`,
    sketchEmpty: (where: string) => `Sketch está vacío${where}`,
    sketchTooFew: (where: string) => `Se requieren al menos 3 segmentos${where}`,
    sketchGap: (where: string) => `Perfil no cerrado — el punto final no coincide con el inicio${where}`,
    sketchNotClosed: (where: string) => `Cierre el perfil antes de extruir${where}`,
    aiAppliedChanges: (count: number) => `IA aplicó ${count} cambio${count !== 1 ? 's' : ''}`,
    shapeFromText: (id: string) => `"${id}" forma generada desde texto`,
    mateAdded: (label: string, a: string, b: string) => `${label} añadido (${a} ↔ ${b})`,
    flatDxfFailed: (msg: string) => `Patrón plano DXF falló: ${msg}`,
    gcodeGenerated: (post: string, passes: number, lines: number, time: number, warning: string) =>
      `G-code generado (${post}) — ${passes} pasadas, ${lines} líneas, est. ${time} min${warning ? ` ⚠ ${warning}` : ''}`,
    orientationSaves: (label: string, pct: number) => `Pruebe ${label} — ${pct}% menos soporte`,
    printReadyDownloaded: 'Archivos listos para imprimir descargados (.stl + .3mf)',
    dfmFailed: (msg: string) => `DFM falló: ${msg}`,
    autoFixApplied: (label: string) => `Corrección automática aplicada: ${label}`,
    aiAnalysisFailed: (msg: string) => `Análisis IA falló: ${msg}`,
    undercutsDetected: (count: string) => `${count} caras con undercut detectadas`,
    facesNeedDraft: (count: string) => `${count} caras necesitan más draft`,
    draftFailed: (msg: string) => `Análisis de draft falló: ${msg}`,
    jumpToFeature: (type: string) => `Saltar a feature: ${type}`,
    noFeatureInTree: (list: string) => `Sin feature '${list}' en el árbol — intente añadir una`,
    feaFailed: (msg: string) => `FEA falló: ${msg}`,
    interferenceFound: (n: number) => `${n} interferencia(s) encontrada(s)`,
    interferenceFailed: (msg: string) => `Verificación de interferencia falló: ${msg}`,
    interferenceCancelled: 'Verificación de interferencia cancelada.',
    interferenceTimelineLabel: 'Interferencia',
    importFailed: (msg: string) => `Importación falló: ${msg}`,
    designApplied: (summary: string) => `Diseño aplicado${summary ? ` (${summary})` : ''} — DFM automático ejecutándose`,
    importedFile: (name: string) => `"${name}" importado correctamente`,
    importFailedFile: (msg: string) => `Importación falló: ${msg}`,
    cotsAddedToBom: (name: string) => `${name} añadido a BOM`,
    standardHoleAdded: (d: string) => `Agujero estándar añadido (Ø${d}mm)`,
    versionSaved: (name: string) => `💾 Guardado "${name}"`,
    versionApplied: (name: string) => `↻ Aplicado "${name}"`,
    partLoaded: (name: string) => `📚 Cargado "${name}"`,
    processMatchingSuppliers: (p: string) => `${p} → emparejando proveedores`,
    rfqSent: (mfr: string, qty: number) => `RFQ enviado a ${mfr} (${qty} piezas)`,
    materialSwitched: (id: string) => `Material cambiado a ${id}`,
    aiShapeGenerated: (desc: string) => `Forma generada: ${desc}…`,
    quoteRequestSent: (name: string) => `Solicitud de cotización enviada a ${name}`,
    thermalFeaDone: 'FEA térmico completo — distribución de temperatura mostrada en vista 3D',
    quoteRequested: (id: string) => `Cotización solicitada de ${id}`,
    designFailed: (err: string) => `Generación de diseño falló: ${err}`,
    networkError: (err: string) => `Error de red: ${err}`,
  },
  ar: {
    assemblyLabel: 'التجميع',
    remoteResolvedComment: '✅ قام متعاون بحل تعليق.',
    mentionedYou: 'أشار إليك',
    invalidShareLink: 'رابط مشاركة غير صالح',
    designLoaded: 'تم تحميل التصميم من السحابة',
    designLoadFailed: 'فشل تحميل التصميم',
    sharedModelLoaded: 'تم تحميل النموذج المشترك',
    sharedModelLoadFailed: 'فشل تحميل النموذج المشترك',
    snapshotSaved: 'تم حفظ اللقطة',
    versionRestored: 'تمت استعادة الإصدار',
    featureCannotRestore: 'لا يمكن استعادة الميزة',
    featureRestored: 'تمت استعادة الميزة',
    closeProfileFirst: 'أغلق الملف الشخصي أولاً',
    sketchModeExitPreserved: 'تم الخروج من وضع الرسم. تم الحفاظ على الرسم. اضغط S للعودة.',
    sketchPreflightPointsNoConstraints: 'هناك نقاط دون قيود — قد تتحرك الهندسة.',
    sketchPreflightConstraintsNoPoints: 'هناك قيود دون نقاط — حالة الرسم غير متسقة.',
    sketchPreflightLargeConstraintSet: 'عدد كبير من القيود — قد يصبح الحل أبطأ على الأجهزة الضعيفة.',
    sketchLargeConstraintInfo: 'قيود رسم كثيرة جدًا — قد يصبح الحل التلقائي أبطأ.',
    interferenceRunHeavyHint: 'مقارنات كثيرة — قد يستغرق الفحص وقتًا طويلًا. احفظ ثم نفّذ.',
    camHeavyMeshHint: 'عدد كبير من رؤوس الشبكة — قد يستغرق توليد مسار CAM والمحاكاة وقتًا أطول.',
    perfSuppressLoadToasts: 'إيقاف تنبيهات الأداء/الرسم (CAM، التداخل، قيود كثيرة)',
    composeRefining: 'الذكاء الاصطناعي يقوم بتوليد تركيبة جديدة...',
    composeSearching: 'الذكاء الاصطناعي يبحث عن أفضل تركيبة تصميم...',
    composeSubtitle: 'قطع · عملية · مطابقة المواد · توليف JSCAD',
    stepExportFeature: 'تصدير STEP',
    gltfExportFeature: 'تصدير GLTF',
    dxfExportFeature: 'تصدير DXF',
    rhinoExportFeature: 'تصدير Rhino (Team+)',
    grasshopperExportFeature: 'تصدير Grasshopper (Team+)',
    dfmAnalysisFeature: 'تحليل DFM',
    doubleClickSketchHint: '(نقر مزدوج = رسم)',
    aiShapeGenPanel: '⚙ AI + JSCAD',
    ideaDesignSource: (label: string) => `تصميم الفكرة: ${label}`,
    unitCostHint: (cost: number | string) => `التكلفة التقديرية ≈ $${cost}/قطعة`,
    leadTimeHint: (a: number | string, b: number | string) => `مدة التسليم ${a}-${b} يوم`,
    selectedFaceMsg: (lbl: string, area: string, normal: string) => `[الوجه المحدد: ${lbl}, المساحة ${area}mm², العمود (${normal})]`,
    selectedEdgeMsg: (length: string, pos: string) => `[الحافة المحددة: الطول ${length}mm, الموقع (${pos})]`,
    useThisFaceAsBase: 'يرجى استخدام هذا الوجه كمرجع.',
    addedToFeatureTree: 'تمت الإضافة إلى شجرة الميزات',
    undoLabel: 'تراجع',
    retryLabel: 'إعادة المحاولة',
    booleanApplied: 'تم تطبيق عملية Boolean',
    booleanFailed: 'فشلت عملية Boolean',
    body1: 'الجسم 1',
    bodyGeometryMissing: 'هندسة الجسم غير موجودة',
    bodySplitComplete: 'اكتمل تقسيم الجسم',
    splitFailed: 'فشل التقسيم',
    mergedBody: 'جسم مدمج',
    bodiesMerged: 'تم دمج الأجسام',
    mergeFailed: 'فشل الدمج',
    stlSaved: 'تم حفظ STL',
    stlExportFailed: 'فشل تصدير STL',
    pdfExportFailed: 'فشل تصدير PDF',
    stepExportFailed: 'فشل تصدير STEP',
    stepExportBundleSuccess: 'تم تنزيل حزمة ZIP للتصنيع (STEP وSTL وJSON وTXT بعد فك الضغط).',
    dxfExported: 'تم تصدير DXF بنجاح',
    dxfExportFailed: 'فشل تصدير DXF',
    createShapeFirst: 'أنشئ شكلاً أولاً',
    flatDxfExported: 'تم تصدير النمط المسطح DXF',
    rhinoExported: 'تم تصدير Rhino JSON',
    rhinoFailed: 'فشل تصدير Rhino JSON',
    grasshopperExported: 'تم تصدير نقاط Grasshopper',
    grasshopperFailed: 'فشل تصدير Grasshopper',
    sceneSaveFailed: 'فشل حفظ المشهد',
    sceneLoadFailed: 'فشل استيراد المشهد',
    loadSceneFirst: 'حمّل مشهدًا أولاً',
    glbExportFailed: 'فشل تصدير GLB',
    printAnalysisComplete: 'اكتمل تحليل الطباعة ثلاثية الأبعاد',
    generateShapeFirst: 'أنشئ شكلاً أولاً',
    alreadyOptimalOrientation: 'الاتجاه الأمثل بالفعل',
    exportFailed: 'فشل التصدير',
    optimalOrientationApplied: 'تم تطبيق الاتجاه الأمثل',
    dfmAnalysisComplete: 'اكتمل تحليل DFM',
    noGeometryToAnalyze: 'لا توجد هندسة للتحليل',
    allFacesModable: 'جميع الوجوه قابلة للتشكيل',
    noRelatedFeature: 'لم يتم العثور على ميزة ذات صلة',
    feaAnalysisComplete: 'اكتمل تحليل FEA',
    noInterference: 'لم يتم اكتشاف تداخل',
    bendApplied: 'تم تطبيق الانحناء',
    flangeApplied: 'تم تطبيق الشفة',
    flatPatternGenerated: 'تم إنشاء النمط المسطح',
    goDesignTabFirst: 'انتقل إلى علامة Design أولاً لإنشاء شكل.',
    workspaceEmptyNeedShape: (ws: string) =>
      `يلزم وجود جسم صلب أولًا لاستخدام «${ws}» — اختر قالبًا يسارًا أو اضغط S للرسم.`,
    workspaceEmptyGoDesign: 'تصميم',
    cadWorkspaceSelectAria: 'اختيار مساحة عمل CAD',
    optimizeEmptyNeedMesh:
      'لتشغيل تحسين الطوبولوجيا، أنشئ جسمًا صلبًا في تبويب Design وثبّت الوجوه والأحمال ثم اضغط Generate.',
    edgeEditHint: 'انقر على الحافة للتدوير/الشطف. اسحب نقطة المنتصف للتحريك.',
    vertexEditPointerHint: 'اسحب الرأس بالزر الأيسر للتحريك (النقر وحده لا يثبت). الدوران: زر العجلة · التحريك: اليمين.',
    edgeEditPointerHint: 'اسحب منتصف الحافة. الدوران: زر العجلة. Boolean (⊕) يفتح لوحة.',
    booleanPanelOpened: 'تم فتح لوحة Boolean — اختر العملية والأداة ثم تطبيق.',
    faceEditHint: 'انقر على الوجه للاختيار، اسحب السهم الأخضر لـ Push/Pull.',
    faceEditViewportCalloutTitle: 'تحرير الوجه (Push/Pull)',
    faceEditViewportCallout: '① انقر الوجه → ② اسحب السهم الأخضر',
    faceEditViewportCalloutTip:
      'فعّل مرشح الوجه وعرض الصلب. الزنبرك: استخدم المنزلقات اليسرى أيضًا.',
    faceEditCalloutDismiss: 'إغلاق',
    designEditQuickGuide:
      'للتعديل: أشرطة الجانب الأيسر (الأبعاد) · «تحرير مباشر» للوجه/الحافة/الرأس (انقر في العرض 3D) · تبويب «الميزات» للبثق وغيره. وضع الصلب يسهّل اختيار الوجوه.',
    designOn3dPc: 'التصميم ثلاثي الأبعاد على سطح المكتب',
    mobileHint: 'يتطلب مصمم NexyFab ثلاثي الأبعاد ماوسًا ولوحة مفاتيح.\nيُرجى استخدام متصفح سطح المكتب للتجربة الكاملة.',
    dashboard: 'لوحة التحكم',
    checkProjects: 'تحقق من مشاريعك',
    marketplace: 'السوق',
    browseMfrs: 'تصفح المصنعين واطلب عرضًا',
    orderTracking: 'تتبع الطلبات',
    trackMfgProgress: 'تتبع تقدم التصنيع',
    rfqQuotes: 'عروض RFQ',
    manageQuotes: 'عرض وإدارة العروض',
    desktopHint: '💻 افتح nexyfab.com على متصفح سطح المكتب\nلبدء النمذجة ثلاثية الأبعاد.',
    mobileShareViewTitle: 'عرض رابط ثلاثي الأبعاد مشترك',
    mobileShareViewBody: 'الصق عنوان URL الكامل في شريط العنوان — يمكنك الدوران والتكبير على الهاتف. التحرير الكامل على سطح المكتب.',
    simpleModeOfferTitle: 'أول مرة؟',
    simpleModeOfferDesc: 'الوضع البسيط يخفي لوحات التحليل المتقدمة للتركيز على الشكل والعرض.',
    simpleModeOfferEnable: 'تشغيل الوضع البسيط',
    simpleModeOfferDismiss: 'الإبقاء على الوضع الكامل',
    simpleModeOfferRegion: 'اقتراح الوضع البسيط',
    workspaceStatusLabel: 'دليل مساحة العمل',
    featureSelectedPrefix: 'الميزة المحددة:',
    measureToolActive: 'وضع القياس — انقر على نقطتين أو حافتين.',
    dropFileHere: 'أسقط الملف هنا',
    loadingFile: 'جارٍ تحميل الملف...',
    smallScreenDetected: 'تم اكتشاف شاشة صغيرة',
    smallScreenHint: 'انتقل إلى ملء الشاشة لتجربة أفضل.',
    goFullscreen: 'ملء الشاشة',
    noThanks: 'لا شكراً',
    stepLoadedIntoViewport: 'تم تحميل هندسة STEP في العرض',
    getQuoteArrow: 'احصل على عرض سعر →',
    aiPreviewMode: 'وضع معاينة الذكاء الاصطناعي',
    aiPreviewHint: '— اختر تطبيق أو إلغاء في لوحة الدردشة',
    cancelLabel: 'إلغاء',
    viewerOnlyMode: '🔒 وضع العرض فقط — التحرير معطل.',
    pluginsLabel: 'الإضافات',
    manageLabel: 'إدارة',
    directEdit: 'التحرير المباشر:',
    faceEditMode: 'تحرير الوجه (Push/Pull)',
    vertexEditMode: 'تحرير الرأس',
    edgeEditMode: 'تحرير الحافة',
    doubleClickSketchFace: 'نقر مزدوج = رسم على الوجه',
    booleanOps: 'عمليات Boolean (Union/Subtract/Intersect)',
    booleanShort: 'Boolean',
    exitEdit: 'إنهاء التحرير',
    depthMm: 'العمق (mm)',
    extrude: 'البثق',
    revolve: 'التدوير',
    continueEditing: 'متابعة التحرير',
    sketchClickHint: 'انقر على النقطة الأولى أو انقر نقرًا مزدوجًا لإغلاق الملف',
    show3dPreview: 'عرض المعاينة ثلاثية الأبعاد',
    hide3dPreview: 'إخفاء المعاينة ثلاثية الأبعاد',
    hideLabel: 'إخفاء',
    viewportPreviewInMain: 'يُعرض العرض ثلاثي الأبعاد في مساحة العمل الرئيسية.',
    partPlacement: 'وضع الأجزاء',
    partsLabel: 'الأجزاء',
    assemblyTools: 'أدوات التجميع',
    assemblyShort: 'التجميع',
    geometryValidation: 'التحقق من الهندسة',
    manifold: 'متشعب',
    closedMesh: 'مغلق',
    consistentNormals: 'معامدات متناسقة',
    openEdges: 'حواف مفتوحة',
    nonManifoldEdges: 'حواف غير متشعبة',
    degenerateTri: 'مثلثات متدهورة',
    duplicateVertices: 'رؤوس مكررة',
    totalTriangles: 'إجمالي المثلثات',
    totalVertices: 'إجمالي الرؤوس',
    volumeLabel: 'الحجم',
    surfaceAreaLabel: 'المساحة السطحية',
    issuesLabel: 'المشكلات',
    standardPartsLibrary: 'مكتبة الأجزاء القياسية',
    fastenersLabel: 'المثبتات',
    structuralLabel: 'إنشائي',
    bearingsLabel: 'المحامل',
    hexBolt: 'برغي سداسي',
    hexNut: 'صامولة سداسية',
    socketHeadCapScrew: 'برغي رأس مقبس',
    flatWasher: 'وردة مسطحة',
    springWasher: 'وردة زنبركية',
    iBeam: 'عارضة I',
    angleBracket: 'زاوية L',
    channelBeam: 'قناة C',
    ballBearing: 'محمل كروي',
    bushing: 'جلبة',
    screenshotSaved: 'تم حفظ لقطة الشاشة',
    feaRunning: 'يعمل FEA...',
    dfmRunning: 'يعمل DFM...',
    csgRunning: 'يعمل CSG...',
    rebuildingGeometry: 'إعادة بناء الهندسة...',
    occtEngine: 'محرك طوبولوجيا OCCT (تجريبي)',
    suggestionReapplied: 'تمت إعادة تطبيق الاقتراح',
    noApplicableChanges: 'لا توجد تغييرات قابلة للتطبيق',
    selectManufacturer: 'اختيار الشركة المصنعة',
    quoteRequestMessage: 'أود طلب عرض سعر.',
    collabPanel: 'التعاون',
    pinComments: 'تعليقات',
    chatLabel: 'الدردشة',
    ipProtectedShare: 'رابط مشاركة محمي الملكية',
    ipShareInfo: '72 ساعة · لا تحميل · بعلامة مائية',
    linkCopied: 'تم نسخ الرابط',
    copyLabel: 'نسخ',
    closeLabel: 'إغلاق',
    optimalStructureDone: 'تم إنشاء الهيكل الأمثل!',
    pcbHeatMappingDone: 'اكتمل تعيين الحرارة PCB!',
    showOriginal: 'عرض الأصل',
    showPcbHeatMap: 'عرض خريطة حرارة PCB',
    showOptimized: 'عرض النتيجة المحسنة',
    modalAnalysisDone: 'اكتمل التحليل النمطي',
    bestParamsApplied: 'تم تطبيق أفضل المعلمات',
    surfaceAnalysisDone: 'اكتمل تحليل السطح',
    sketchGeometryFailed: 'فشل بناء الهندسة — تحقق من التقاطع الذاتي أو الشكل غير الصالح',
    shapeGeneratedGuide: 'تم إنشاء الشكل ثلاثي الأبعاد! اختر مادة في اللوحة اليسرى، ثم صدّر أو أرسل إلى RFQ.',
    sketchPlaneSwitched: (plane: string) => `تم تبديل مستوى الرسم إلى ${plane}. يتم إعادة تعيين الملف الحالي إلى المستوى الجديد.`,
    sketchRefBadFileType: 'استخدم صورة أو ملف STL/STEP/DXF كمرجع.',
    sketchRefLoading: 'جارٍ معالجة هندسة المرجع…',
    importFileMenuHint: 'استيراد الشكل إلى مساحة العمل ثلاثية الأبعاد. للتتبع على الرسم استخدم تبويب الرسم ← إدراج.',
    sketchPickFilterAll: 'الكل — حواف ورؤوس',
    sketchPickFilterSegments: 'حواف فقط — بدون سحب الرؤوس',
    sketchPickFilterPoints: 'رؤوس فقط — بدون اختيار الحواف',
    exitSketchBeforeOptimize: 'اخرج من وضع الرسم قبل التبديل إلى Optimize. سيتم الاحتفاظ بالرسم.',
    mateCoincident: 'متطابق',
    mateConcentric: 'متحد المركز',
    mateDistance: 'مسافة',
    feaUpgradeFeature: 'تحليل FEA',
    brokenExpression: (key: string, expression: string, missing: string, extra: number) =>
      `تعبير معطل: '${key}' = '${expression}' (مفقود: ${missing}${extra > 0 ? ` +${extra} أخرى` : ''})`,
    cannotApplyFeature: (msg: string) => `لا يمكن تطبيق الميزة: ${msg}`,
    featureFailed: (label: string, hint: string) => `⚠ فشل ${label} — ${hint}`,
    branchCreated: (name: string) => `تم إنشاء الفرع "${name}"`,
    branchSwitched: (name: string) => `تم التبديل إلى الفرع "${name}"`,
    branchDeleted: (name: string) => `تم حذف الفرع "${name}"`,
    branchMerged: (src: string, tgt: string) => `تم دمج "${src}" في "${tgt}"`,
    pipelineFailed: (msg: string) => `فشل خط الهندسة: ${msg}`,
    shapeNotFound: (id: string) => `الشكل "${id}" غير موجود`,
    sketchEmpty: (where: string) => `الرسم فارغ${where}`,
    sketchTooFew: (where: string) => `مطلوب 3 مقاطع على الأقل${where}`,
    sketchGap: (where: string) => `الملف غير مغلق — النقطة النهائية لا تلتقي بالبداية${where}`,
    sketchNotClosed: (where: string) => `أغلق الملف قبل البثق${where}`,
    aiAppliedChanges: (count: number) => `طبق الذكاء الاصطناعي ${count} تغيير`,
    shapeFromText: (id: string) => `تم إنشاء الشكل "${id}" من النص`,
    mateAdded: (label: string, a: string, b: string) => `${label} تمت إضافته (${a} ↔ ${b})`,
    flatDxfFailed: (msg: string) => `فشل النمط المسطح DXF: ${msg}`,
    gcodeGenerated: (post: string, passes: number, lines: number, time: number, warning: string) =>
      `تم إنشاء G-code (${post}) — ${passes} مسارات، ${lines} أسطر، حوالي ${time} دقيقة${warning ? ` ⚠ ${warning}` : ''}`,
    orientationSaves: (label: string, pct: number) => `جرب ${label} — ${pct}% دعم أقل`,
    printReadyDownloaded: 'تم تنزيل ملفات جاهزة للطباعة (.stl + .3mf)',
    dfmFailed: (msg: string) => `فشل DFM: ${msg}`,
    autoFixApplied: (label: string) => `تم تطبيق الإصلاح التلقائي: ${label}`,
    aiAnalysisFailed: (msg: string) => `فشل تحليل الذكاء الاصطناعي: ${msg}`,
    undercutsDetected: (count: string) => `تم اكتشاف ${count} وجوه undercut`,
    facesNeedDraft: (count: string) => `${count} وجوه تحتاج مزيدًا من draft`,
    draftFailed: (msg: string) => `فشل تحليل draft: ${msg}`,
    jumpToFeature: (type: string) => `الانتقال إلى الميزة: ${type}`,
    noFeatureInTree: (list: string) => `لا توجد ميزة '${list}' في الشجرة — حاول إضافة واحدة`,
    feaFailed: (msg: string) => `فشل FEA: ${msg}`,
    interferenceFound: (n: number) => `تم العثور على ${n} تداخل`,
    interferenceFailed: (msg: string) => `فشل فحص التداخل: ${msg}`,
    interferenceCancelled: 'تم إلغاء فحص التداخل.',
    interferenceTimelineLabel: 'فحص التداخل',
    importFailed: (msg: string) => `فشل الاستيراد: ${msg}`,
    designApplied: (summary: string) => `✅ تم تطبيق التصميم${summary ? ` (${summary})` : ''} — يعمل DFM تلقائيًا`,
    importedFile: (name: string) => `تم استيراد "${name}" بنجاح`,
    importFailedFile: (msg: string) => `فشل الاستيراد: ${msg}`,
    cotsAddedToBom: (name: string) => `تمت إضافة ${name} إلى BOM`,
    standardHoleAdded: (d: string) => `تمت إضافة ثقب قياسي (Ø${d}mm)`,
    versionSaved: (name: string) => `💾 تم حفظ "${name}"`,
    versionApplied: (name: string) => `↻ تم تطبيق "${name}"`,
    partLoaded: (name: string) => `📚 تم تحميل "${name}"`,
    processMatchingSuppliers: (p: string) => `${p} → مطابقة الموردين`,
    rfqSent: (mfr: string, qty: number) => `تم إرسال RFQ إلى ${mfr} (${qty} قطعة)`,
    materialSwitched: (id: string) => `تم تبديل المادة إلى ${id}`,
    aiShapeGenerated: (desc: string) => `تم إنشاء الشكل: ${desc}…`,
    quoteRequestSent: (name: string) => `تم إرسال طلب عرض السعر إلى ${name}`,
    thermalFeaDone: 'اكتمل التحليل الحراري — توزيع الحرارة يظهر في العرض ثلاثي الأبعاد',
    quoteRequested: (id: string) => `تم طلب عرض سعر من ${id}`,
    designFailed: (err: string) => `فشل إنشاء التصميم: ${err}`,
    networkError: (err: string) => `خطأ في الشبكة: ${err}`,
  },
} as const;


export { SHAPE_ICONS, TAB_LABELS, CAD_WORKSPACE_LABELS, CAD_WORKSPACE_SWITCHER_HEADING, LOCAL_LABELS };
export type { TabMode, ViewMode };
