import { describe, expect, it } from 'vitest'; import { cacheVerifiedPartArtifact, createGenerationRun, generationArtifactHash, invalidateGenerationForEdit, lastVerifiedCheckpoint, planGenerationStageRecovery, recordGenerationStage, GENERATION_STAGES } from '../generationRunState';
const pass = (state: ReturnType<typeof createGenerationRun>, stage: typeof GENERATION_STAGES[number], value: unknown) => recordGenerationStage(state, { stage, input: { prior: state.revision }, output: value, status: 'passed', timestamp: '2026-08-05T00:00:00.000Z' });
describe('generation run state machine', () => {
  it('uses canonical hashes independent of object key order', () => expect(generationArtifactHash({ b: 2, a: 1 })).toBe(generationArtifactHash({ a: 1, b: 2 })));
  it('requires ordered stages and creates immutable verified checkpoints', () => { let state = createGenerationRun('run-1'); expect(() => pass(state, 'kernel', {})).toThrow(/Previous stage/); state = pass(state, 'intent', { requirements: [] }); expect(state.stages.intent).toMatchObject({ status: 'passed', attempt: 1 }); expect(state.stages.intent.checkpointHash).toHaveLength(64); expect(lastVerifiedCheckpoint(state)?.stage).toBe('intent'); });
  it('invalidates downstream evidence when an upstream input changes', () => { let state = createGenerationRun('run-2'); state = pass(state, 'intent', {}); state = pass(state, 'decomposition', { parts: ['a'] }); state = pass(state, 'interfaces', {}); state = recordGenerationStage(state, { stage: 'decomposition', input: { changed: true }, output: { parts: ['a', 'b'] }, status: 'passed', timestamp: '2026-08-05T00:00:01.000Z' }); expect(state.stages.interfaces.status).toBe('not_run'); expect(state.stages.decomposition.status).toBe('passed'); });
  it('retries only failed parts while preserving verified independent artifacts', () => { let state = createGenerationRun('run-3'); for (const stage of GENERATION_STAGES.slice(0, 9)) state = pass(state, stage, { stage }); state = cacheVerifiedPartArtifact(state, 'good', { brep: 'hashable' }); state = recordGenerationStage(state, { stage: 'roundtrip', input: {}, status: 'failed', errorCodes: ['INVALID_BREP'], affectedPartIds: ['bad'], timestamp: '2026-08-05T00:00:02.000Z' }); expect(planGenerationStageRecovery(state, 'roundtrip', [])).toMatchObject({ action: 'retry_stage', retryPartIds: ['bad'], preservePartIds: ['good'] }); });
  it('stops an identical failure fingerprint after the bounded retry budget', () => { let state = createGenerationRun('run-4'); state = recordGenerationStage(state, { stage: 'intent', input: {}, status: 'failed', errorCodes: ['MISSING_DIMENSION'], timestamp: '2026-08-05T00:00:00.000Z' }); const fp = state.stages.intent.failureFingerprint!; expect(planGenerationStageRecovery(state, 'intent', [fp, fp])).toMatchObject({ action: 'stop' }); });
  it('invalidates only the edited part and the minimum downstream stage slice', () => { let state = createGenerationRun('run-5'); for (const stage of GENERATION_STAGES.slice(0, 9)) state = pass(state, stage, { stage }); state = cacheVerifiedPartArtifact(state, 'edited', {}); state = cacheVerifiedPartArtifact(state, 'untouched', {}); state = invalidateGenerationForEdit(state, { operations: [{ kind: 'set_feature_parameter' }], affected: { parts: ['edited'] } }); expect(state.stages.part_programs.status).toBe('passed'); expect(state.stages.kernel.status).toBe('not_run'); expect(state.verifiedPartArtifacts.edited).toBeUndefined(); expect(state.verifiedPartArtifacts.untouched).toBeDefined(); });
});
