import { generateKeyPairSync, sign } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { NextRequest } from 'next/server';
import { hashRobotCadIntegrationTarget } from '@/lib/ai/robot/robotCadIntegrationPacket';
import { robotCadIntegrationSignoffPayload } from '@/lib/ai/robot/robotCadIntegrationReview';
import { POST } from './route';

const key = () => { const pair = generateKeyPairSync('ed25519'); return { privateKey: pair.privateKey, publicKey: pair.publicKey.export({ type: 'spki', format: 'pem' }).toString() }; }; const a = key(), b = key();
const packet = (() => { const value = { schema: 'nexyfab.robot-cad-integration-review-packet.v1', targetHash: '', lineageId: 'robot-lineage', revision: 2, baseProgramHash: 'a'.repeat(64), programHash: 'b'.repeat(64), revisionManifestSha256: 'c'.repeat(64), requirementsSha256: 'd'.repeat(64), catalogManifestSha256: 'e'.repeat(64), catalogArtifactSetSha256: 'f'.repeat(64), housingSha256: '1'.repeat(64), readiness: 'review_pending', expertReviewRequired: true, cadIntegrationStatus: 'not_applied', releaseReady: false, replacements: Array.from({ length: 6 }, (_, i) => ({ joint: i + 1, placeholders: { motor: `J${i + 1}:motor:old`, reducer: `J${i + 1}:reducer:old`, bearing: `J${i + 1}:bearing:old` }, selected: { motor: 'M', reducer: 'R', bearing: 'B' }, fitStatus: 'passed' })), errors: [], sideEffects: { persisted: false, sourceModified: false, cadModified: false, quoteCreated: false, rfqSent: false } }; value.targetHash = hashRobotCadIntegrationTarget(value as never); return value; })();
const makeSignoff = (role: 'domain-reviewer' | 'independent-reviewer', reviewerId: string, privateKey: typeof a.privateKey) => { const unsigned = { role, reviewerId, decision: 'approved' as const, reviewedAt: new Date(Date.now() - 1000).toISOString(), targetHash: packet.targetHash }; return { ...unsigned, signature: sign(null, Buffer.from(robotCadIntegrationSignoffPayload(unsigned)), privateKey).toString('base64') }; };
function request(review: unknown, ip: string) { const form = new FormData(); form.set('packet', new File([JSON.stringify(packet)], 'packet.json')); form.set('review', new File([JSON.stringify(review)], 'review.json')); return new NextRequest('http://localhost/api/cad/v1/robot/integration/review', { method: 'POST', body: form, headers: { 'x-forwarded-for': ip } }); }
describe('CAD v1 robot integration review', () => {
  it('validates two trusted signatures but still applies and releases nothing', async () => { const previous = process.env.NEXYFAB_CAD_REVIEWER_KEYS; process.env.NEXYFAB_CAD_REVIEWER_KEYS = JSON.stringify({ alice: { publicKey: a.publicKey, roles: ['domain-reviewer'] }, bob: { publicKey: b.publicKey, roles: ['independent-reviewer'] } }); try { const review = { schema: 'nexyfab.robot-cad-integration-review.v1', targetHash: packet.targetHash, signoffs: [makeSignoff('domain-reviewer', 'alice', a.privateKey), makeSignoff('independent-reviewer', 'bob', b.privateKey)] }; const response = await POST(request(review, 'review-ok')); expect(response.status).toBe(200); expect(await response.json()).toMatchObject({ ok: true, cadApplied: false, releaseReady: false, quoteOrRfqSideEffects: false, result: { approved: true, integrationAuthorized: true, cadApplied: false, releaseReady: false, nextStep: 'create_new_cad_revision_then_reverify' } }); } finally { if (previous === undefined) delete process.env.NEXYFAB_CAD_REVIEWER_KEYS; else process.env.NEXYFAB_CAD_REVIEWER_KEYS = previous; } });
  it('fails closed without trusted keys or required files', async () => { const previous = process.env.NEXYFAB_CAD_REVIEWER_KEYS; delete process.env.NEXYFAB_CAD_REVIEWER_KEYS; try { const response = await POST(request({ schema: 'nexyfab.robot-cad-integration-review.v1', targetHash: packet.targetHash, signoffs: [] }, 'review-none')); expect(response.status).toBe(422); expect(await response.json()).toMatchObject({ ok: false, cadApplied: false, releaseReady: false }); } finally { if (previous !== undefined) process.env.NEXYFAB_CAD_REVIEWER_KEYS = previous; } const empty = await POST(new NextRequest('http://localhost/api/cad/v1/robot/integration/review', { method: 'POST', body: new FormData(), headers: { 'x-forwarded-for': 'review-empty' } })); expect(empty.status).toBe(400); });
});
