/**
 * stepRobustness.ts — STEP file robustness pre-flight.
 *
 * Customers upload STEP files generated by every CAD tool under the
 * sun — SolidWorks, Inventor, Fusion, FreeCAD, KeyCreator, Solid Edge,
 * old TurboCAD installs from 2003. Each writes slightly different
 * line endings, encodings, and quirks. Before we hand the bytes to
 * the OCCT WASM worker we run a fast textual pre-flight that:
 *
 *   1. Detects encoding (UTF-8, UTF-16 LE/BE, Latin-1) by BOM + heuristics.
 *   2. Detects line endings (CRLF, LF, CR-only).
 *   3. Counts entity records and recovers from malformed lines.
 *   4. Validates ISO 10303 framing (ISO-10303-21; HEADER; DATA; ENDSEC; END-ISO-10303-21;).
 *   5. Extracts unit-of-measure declarations.
 *
 * Why a separate textual pre-flight? OCCT WASM is expensive to spin up
 * and gives terse errors on malformed input. A quick text-side
 * validation lets us:
 *   - Reject obvious garbage at the upload boundary.
 *   - Show "this file looks like UTF-16, did you intend that?" before
 *     burning a worker thread.
 *   - Repair common issues (trailing nulls, BOM stripping, line-ending
 *     normalization) so OCCT sees a clean stream.
 */

export type StepEncoding = 'utf-8' | 'utf-16le' | 'utf-16be' | 'latin-1' | 'unknown';
export type StepLineEnding = 'crlf' | 'lf' | 'cr' | 'mixed' | 'none';

export interface StepRobustnessReport {
  /** Detected encoding. */
  encoding: StepEncoding;
  /** True if the encoding starts with a byte-order mark. */
  hasBom: boolean;
  /** Detected line ending convention. */
  lineEnding: StepLineEnding;
  /** Has the required ISO-10303 framing? */
  validIso10303Framing: boolean;
  /** Number of entity records discovered (#N=...). */
  entityCount: number;
  /** Lines that didn't parse as either header, data, or framing. */
  malformedLineCount: number;
  /** Detected schema name (e.g. AP203, AP214, AP242). */
  schemaName: string | null;
  /** File length in characters (after decoding). */
  characterCount: number;
  /** Repair recommendations. */
  repairs: StepRepair[];
}

export type StepRepair =
  | { kind: 'strip-bom' }
  | { kind: 'normalize-line-endings'; target: 'lf' }
  | { kind: 'convert-encoding'; from: StepEncoding; to: 'utf-8' }
  | { kind: 'trim-trailing-nulls' }
  | { kind: 'reflow-multiline-records' };

// ── Encoding detection ──────────────────────────────────────────

export function detectEncoding(bytes: Uint8Array): { encoding: StepEncoding; hasBom: boolean } {
  if (bytes.length === 0) return { encoding: 'unknown', hasBom: false };

  // BOM sniffing.
  if (bytes.length >= 3 && bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf) {
    return { encoding: 'utf-8', hasBom: true };
  }
  if (bytes.length >= 2 && bytes[0] === 0xff && bytes[1] === 0xfe) {
    return { encoding: 'utf-16le', hasBom: true };
  }
  if (bytes.length >= 2 && bytes[0] === 0xfe && bytes[1] === 0xff) {
    return { encoding: 'utf-16be', hasBom: true };
  }

  // Heuristic: look at high-bit prevalence + null-byte pattern.
  let highBitCount = 0;
  let nullEvenCount = 0;
  let nullOddCount = 0;
  const sampleSize = Math.min(bytes.length, 4096);
  for (let i = 0; i < sampleSize; i++) {
    if (bytes[i]! >= 0x80) highBitCount++;
    if (bytes[i] === 0) {
      if (i % 2 === 0) nullEvenCount++;
      else nullOddCount++;
    }
  }
  // UTF-16LE has lots of zeros at odd positions; UTF-16BE at even.
  if (nullOddCount > sampleSize * 0.3) return { encoding: 'utf-16le', hasBom: false };
  if (nullEvenCount > sampleSize * 0.3) return { encoding: 'utf-16be', hasBom: false };
  if (highBitCount > sampleSize * 0.1) return { encoding: 'latin-1', hasBom: false };
  return { encoding: 'utf-8', hasBom: false };
}

// ── Decoding ────────────────────────────────────────────────────

export function decodeBytes(bytes: Uint8Array, encoding: StepEncoding, stripBom: boolean = false): string {
  let bytesToDecode = bytes;
  if (stripBom) {
    if (encoding === 'utf-8' && bytes.length >= 3 && bytes[0] === 0xef && bytes[1] === 0xbb && bytes[2] === 0xbf) {
      bytesToDecode = bytes.slice(3);
    } else if ((encoding === 'utf-16le' || encoding === 'utf-16be') && bytes.length >= 2) {
      bytesToDecode = bytes.slice(2);
    }
  }
  const label = encoding === 'latin-1' ? 'windows-1252' : encoding;
  try {
    const decoder = new TextDecoder(label, { fatal: false });
    return decoder.decode(bytesToDecode);
  } catch {
    // Fallback: latin-1.
    let s = '';
    for (const b of bytesToDecode) s += String.fromCharCode(b);
    return s;
  }
}

// ── Line ending detection ───────────────────────────────────────

export function detectLineEnding(text: string): StepLineEnding {
  let crlf = 0, lfOnly = 0, crOnly = 0;
  for (let i = 0; i < text.length; i++) {
    if (text[i] === '\r') {
      if (text[i + 1] === '\n') { crlf++; i++; }
      else crOnly++;
    } else if (text[i] === '\n') {
      lfOnly++;
    }
  }
  const total = crlf + lfOnly + crOnly;
  if (total === 0) return 'none';
  const dominant = Math.max(crlf, lfOnly, crOnly);
  if (dominant === total) {
    if (crlf > 0) return 'crlf';
    if (lfOnly > 0) return 'lf';
    return 'cr';
  }
  return 'mixed';
}

export function normalizeLineEndings(text: string): string {
  return text.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
}

// ── ISO 10303 framing ───────────────────────────────────────────

const FRAMING_LINE_RE = /^(ISO-10303-21|HEADER|DATA|ENDSEC|END-ISO-10303-21);?/;
const ENTITY_LINE_RE = /^#(\d+)\s*=\s*([A-Z_][A-Z_0-9]*)\s*\(/;
const FILE_SCHEMA_RE = /FILE_SCHEMA\s*\(\s*\(\s*'([^']+)'/;

export function analyzeText(text: string): {
  validFraming: boolean;
  entityCount: number;
  malformedLineCount: number;
  schemaName: string | null;
} {
  const normalized = normalizeLineEndings(text);
  const lines = normalized.split('\n');

  let sawIsoStart = false;
  let sawIsoEnd = false;
  let inHeader = false;
  let inData = false;
  let entityCount = 0;
  let malformed = 0;
  let schemaName: string | null = null;

  for (const raw of lines) {
    const line = raw.trim();
    if (line === '') continue;
    if (line === 'ISO-10303-21;') { sawIsoStart = true; continue; }
    if (line === 'END-ISO-10303-21;') { sawIsoEnd = true; continue; }
    if (line === 'HEADER;') { inHeader = true; inData = false; continue; }
    if (line === 'DATA;') { inHeader = false; inData = true; continue; }
    if (line === 'ENDSEC;') { inHeader = false; inData = false; continue; }
    if (ENTITY_LINE_RE.test(line)) {
      if (inData) entityCount++;
      continue;
    }
    if (inHeader) {
      const schemaMatch = line.match(FILE_SCHEMA_RE);
      if (schemaMatch) schemaName = schemaMatch[1] ?? null;
      // Header lines like FILE_DESCRIPTION, FILE_NAME, FILE_SCHEMA — pass.
      if (/^[A-Z_]+\s*\(/.test(line) || /^\(/.test(line) || /^[,;)']/.test(line)) continue;
      // Long records may span multiple lines, so a trailing comma is OK.
      if (line.endsWith(',')) continue;
      malformed++;
      continue;
    }
    if (FRAMING_LINE_RE.test(line)) continue;
    // Unknown line outside header / data — malformed.
    malformed++;
  }

  return {
    validFraming: sawIsoStart && sawIsoEnd,
    entityCount,
    malformedLineCount: malformed,
    schemaName: schemaName ? normalizeSchemaName(schemaName) : null,
  };
}

function normalizeSchemaName(raw: string): string {
  if (/AUTOMOTIVE_DESIGN/i.test(raw)) return 'AP214';
  if (/CONFIG_CONTROL_DESIGN/i.test(raw)) return 'AP203';
  if (/AP242|MANAGED_MODEL_BASED_3D_ENGINEERING/i.test(raw)) return 'AP242';
  return raw.toUpperCase();
}

// ── Top-level entry ─────────────────────────────────────────────

export function preflightStep(bytes: Uint8Array): StepRobustnessReport {
  const { encoding, hasBom } = detectEncoding(bytes);
  const text = decodeBytes(bytes, encoding, /* stripBom */ true);
  const lineEnding = detectLineEnding(text);
  const analysis = analyzeText(text);

  const repairs: StepRepair[] = [];
  if (hasBom) repairs.push({ kind: 'strip-bom' });
  if (lineEnding === 'crlf' || lineEnding === 'cr' || lineEnding === 'mixed') {
    repairs.push({ kind: 'normalize-line-endings', target: 'lf' });
  }
  if (encoding !== 'utf-8') {
    repairs.push({ kind: 'convert-encoding', from: encoding, to: 'utf-8' });
  }
  if (text.endsWith('\0') || text.includes('\0\0')) {
    repairs.push({ kind: 'trim-trailing-nulls' });
  }
  if (analysis.entityCount > 0 && analysis.malformedLineCount > analysis.entityCount * 0.5) {
    repairs.push({ kind: 'reflow-multiline-records' });
  }

  return {
    encoding,
    hasBom,
    lineEnding,
    validIso10303Framing: analysis.validFraming,
    entityCount: analysis.entityCount,
    malformedLineCount: analysis.malformedLineCount,
    schemaName: analysis.schemaName,
    characterCount: text.length,
    repairs,
  };
}

// ── Repair executor ─────────────────────────────────────────────

export function applyRepairs(bytes: Uint8Array, report: StepRobustnessReport): { bytes: Uint8Array; text: string } {
  let text = decodeBytes(bytes, report.encoding, /* stripBom */ report.hasBom);
  for (const repair of report.repairs) {
    switch (repair.kind) {
      case 'normalize-line-endings':
        text = normalizeLineEndings(text);
        break;
      case 'trim-trailing-nulls':
        text = text.replace(/\0+$/g, '').replace(/\0\0+/g, '');
        break;
      case 'reflow-multiline-records':
        // Fold records that wrap across lines into a single line.
        // STEP records end with a semicolon; if a line doesn't end with one,
        // glue the next line onto it.
        text = reflowRecords(text);
        break;
      // strip-bom and convert-encoding are already applied by re-decoding above.
      case 'strip-bom':
      case 'convert-encoding':
        break;
    }
  }
  const utf8 = new TextEncoder().encode(text);
  return { bytes: utf8, text };
}

function reflowRecords(text: string): string {
  const lines = text.split('\n');
  const out: string[] = [];
  let buf = '';
  for (const line of lines) {
    const stripped = line.trim();
    if (stripped === '') continue;
    buf += (buf ? ' ' : '') + stripped;
    if (stripped.endsWith(';')) {
      out.push(buf);
      buf = '';
    }
  }
  if (buf) out.push(buf);
  return out.join('\n');
}
