import { type Manufacturer } from './manufacturers-types';

export const MANUFACTURERS: Manufacturer[] = [
  {
    id: 'mfr-001',
    name: 'KoreaPrecision Co.',
    nameKo: '코리아프리시전',
    region: 'KR',
    processes: ['cnc_milling', 'cnc_turning'],
    minLeadTime: 5,
    maxLeadTime: 14,
    rating: 4.8,
    reviewCount: 312,
    priceLevel: 'medium',
    certifications: ['ISO9001', 'AS9100'],
    description: 'High-precision CNC machining specialist based in Incheon, South Korea. Serving aerospace and automotive OEMs since 2005.',
    descriptionKo: '인천에 위치한 고정밀 CNC 가공 전문 업체. 2005년부터 항공·자동차 OEM 납품.',
  },
  {
    id: 'mfr-002',
    name: 'HanilMold Tech',
    nameKo: '한일몰드텍',
    region: 'KR',
    processes: ['injection_molding'],
    minLeadTime: 10,
    maxLeadTime: 30,
    rating: 4.6,
    reviewCount: 185,
    priceLevel: 'low',
    certifications: ['ISO9001', 'IATF16949'],
    description: 'Injection mold design and production in Gyeonggi-do. Specializes in complex multi-cavity tools for consumer electronics.',
    descriptionKo: '경기도 소재 사출 금형 설계·제작 전문. 소비자 전자제품용 복잡 다캐비티 금형 특화.',
  },
  {
    id: 'mfr-003',
    name: 'SungwonSheet',
    nameKo: '성원판금',
    region: 'KR',
    processes: ['sheet_metal', 'cnc_milling'],
    minLeadTime: 3,
    maxLeadTime: 10,
    rating: 4.5,
    reviewCount: 423,
    priceLevel: 'low',
    certifications: ['ISO9001'],
    description: 'Fast-turnaround sheet metal fabrication and light CNC in Busan. Custom enclosures and brackets at competitive prices.',
    descriptionKo: '부산 기반 고속 판금 및 경량 CNC 가공. 주문형 인클로저 및 브라켓 경쟁력 있는 가격.',
  },
  {
    id: 'mfr-004',
    name: 'AdditiveMind GmbH',
    nameKo: '어디티브마인드',
    region: 'DE',
    processes: ['3d_printing'],
    minLeadTime: 2,
    maxLeadTime: 7,
    rating: 4.9,
    reviewCount: 98,
    priceLevel: 'high',
    certifications: ['ISO9001', 'ISO13485'],
    description: 'German additive manufacturing bureau specializing in SLS, SLA, and MJF. Medical-grade materials available.',
    descriptionKo: '독일 적층 제조 전문 업체. SLS, SLA, MJF 특화. 의료 등급 소재 제공 가능.',
  },
  {
    id: 'mfr-005',
    name: 'Pacific Casting Works',
    nameKo: '퍼시픽캐스팅',
    region: 'US',
    processes: ['casting', 'cnc_milling'],
    minLeadTime: 15,
    maxLeadTime: 45,
    rating: 4.4,
    reviewCount: 67,
    priceLevel: 'medium',
    certifications: ['ISO9001', 'NADCA'],
    description: 'California-based die casting and investment casting foundry. Aluminum, zinc, and magnesium alloys.',
    descriptionKo: '캘리포니아 소재 다이캐스팅·인베스트먼트 주조 업체. 알루미늄, 아연, 마그네슘 합금.',
  },
  {
    id: 'mfr-006',
    name: 'Shenzhen Rapid Parts',
    nameKo: '심천래피드파츠',
    region: 'CN',
    processes: ['cnc_milling', 'cnc_turning', '3d_printing', 'injection_molding'],
    minLeadTime: 1,
    maxLeadTime: 7,
    rating: 4.2,
    reviewCount: 1024,
    priceLevel: 'low',
    certifications: ['ISO9001'],
    description: 'High-volume rapid prototyping and production from Shenzhen. Online quoting with next-day shipping options.',
    descriptionKo: '심천 기반 대용량 래피드 프로토타이핑 및 양산. 온라인 견적, 익일 배송 옵션.',
  },
  {
    id: 'mfr-007',
    name: 'Yamamoto Seiki',
    nameKo: '야마모토세이키',
    region: 'JP',
    processes: ['cnc_milling', 'cnc_turning', 'sheet_metal'],
    minLeadTime: 7,
    maxLeadTime: 21,
    rating: 4.7,
    reviewCount: 204,
    priceLevel: 'high',
    certifications: ['ISO9001', 'JIS Q 9100'],
    description: 'Osaka precision machining company with 40+ years of experience. Mirror-finish capabilities and tight tolerances for semiconductor equipment.',
    descriptionKo: '오사카 소재 40년 이상 경력의 정밀 가공 업체. 경면 사상 및 반도체 장비용 초정밀 공차.',
  },
  {
    id: 'mfr-008',
    name: 'DaewonCast',
    nameKo: '대원주조',
    region: 'KR',
    processes: ['casting'],
    minLeadTime: 20,
    maxLeadTime: 60,
    rating: 4.3,
    reviewCount: 89,
    priceLevel: 'low',
    certifications: ['ISO9001', 'KS'],
    description: 'Traditional and sand casting foundry in Changwon, South Korea. Gray iron, ductile iron, and aluminum castings for industrial machinery.',
    descriptionKo: '창원 소재 일반 및 사형 주조 업체. 회주철, 구상흑연주철, 알루미늄 주물 제작.',
  },
  {
    id: 'mfr-009',
    name: 'ProtoLabs USA',
    nameKo: '프로토랩스 US',
    region: 'US',
    processes: ['cnc_milling', 'cnc_turning', 'injection_molding', '3d_printing', 'sheet_metal'],
    minLeadTime: 1,
    maxLeadTime: 15,
    rating: 4.6,
    reviewCount: 3200,
    priceLevel: 'high',
    certifications: ['ISO9001', 'AS9100', 'ISO13485'],
    description: 'Full-service digital manufacturing network across the USA. Instant online quoting, automated DFM feedback, and fast fulfillment.',
    descriptionKo: '미국 전역 풀서비스 디지털 제조 네트워크. 즉시 온라인 견적, 자동 DFM 피드백, 신속 납품.',
  },
  {
    id: 'mfr-010',
    name: 'EuroPrint Advanced',
    nameKo: '유로프린트 어드밴스드',
    region: 'DE',
    processes: ['3d_printing', 'casting'],
    minLeadTime: 3,
    maxLeadTime: 12,
    rating: 4.5,
    reviewCount: 142,
    priceLevel: 'medium',
    certifications: ['ISO9001', 'DIN EN 9100'],
    description: 'Munich-based metal additive and investment casting bureau. DMLS titanium and Inconel for aerospace and motorsport clients.',
    descriptionKo: '뮌헨 소재 금속 적층·인베스트먼트 주조 전문. 항공우주·모터스포츠용 DMLS 티타늄 및 인코넬.',
  },
];
