import { describe, expect, it } from 'vitest';
import { canonicalCommercialExecution, commercialExecutionJobBinding, hmacCommercialTransport, sha256Commercial, validateCommercialExecutionInput, validateCommercialExecutionJob, validateCommercialTransport, verifyCommercialTransportHmac, type CommercialExecutionInput, type CommercialTransportEnvelope } from './commercialPrecisionExecution';
const argumentsValue = { assembly: 'fixture-1' };
const job = { contractVersion: 'nexyfab.precision-cad-commercial-execution.v3' as const, jobId: 'job-1', tenantId: 'tenant-1', projectId: 'project-1', executionId: 'exec-1', generationRunId: 'run-1', generationStateRevision: 11, generationProgramSha256: '9'.repeat(64), workspaceId: 'workspace-1', workspaceRevision: 7, workspaceContentHash: 'a'.repeat(64), tool: 'build_assembly', scope: 'apply' as const, callId: 'call-1', argumentsHash: '', commandHash: 'c'.repeat(64), targetHash: 'd'.repeat(64), journalVersion: 3, attempt: 1, leaseGeneration: 1, inputArtifact: { artifactId: 'input-1', objectKey: 'private/commercial/jobs/job-1/input.json', contentSha256: 'e'.repeat(64), byteLength: 256, mediaType: 'application/json' as const } };
const endpoints = { callbackUrl: 'https://core.example.test/callback', inputDownloadUrl: 'https://core.example.test/input?jobId=job-1', artifactGatewayUrl: 'https://core.example.test/output' };
describe('commercial precision execution contract v3', () => {
  it('binds immutable input, deterministic job identity, and HMAC transport', async () => { job.argumentsHash = await sha256Commercial(argumentsValue); expect(validateCommercialExecutionJob(job)).toEqual([]); const input: CommercialExecutionInput = { schema: 'nexyfab.precision-cad-commercial-input.v1', job: commercialExecutionJobBinding(job), arguments: argumentsValue }; expect(await validateCommercialExecutionInput(input, job)).toEqual([]); expect(canonicalCommercialExecution(input)).toContain('fixture-1'); const unsigned = { schema: 'nexyfab.precision-cad-commercial-execution.v3' as const, job, issuedAt: '2026-08-22T00:00:00.000Z', expiresAt: '2026-08-22T00:04:00.000Z', ...endpoints, leaseCapability: 'x'.repeat(43) }; const envelope: CommercialTransportEnvelope = { ...unsigned, transportHmac: await hmacCommercialTransport('s'.repeat(32), unsigned) }; expect(validateCommercialTransport(envelope)).toEqual([]); expect(await verifyCommercialTransportHmac('s'.repeat(32), envelope)).toBe(true); expect(await verifyCommercialTransportHmac('x'.repeat(32), envelope)).toBe(false); });
  it('rejects substituted input, unsafe endpoints, and stale transport', async () => { job.argumentsHash = await sha256Commercial(argumentsValue); const input: CommercialExecutionInput = { schema: 'nexyfab.precision-cad-commercial-input.v1', job: commercialExecutionJobBinding(job), arguments: { assembly: 'substituted' } }; expect(await validateCommercialExecutionInput(input, job)).toContain('input_arguments_hash_mismatch'); const unsigned = { schema: 'nexyfab.precision-cad-commercial-execution.v3' as const, job, issuedAt: '2026-08-22T00:00:00.000Z', expiresAt: '2026-08-22T01:00:00.000Z', ...endpoints, leaseCapability: 'x'.repeat(43) }; const envelope = { ...unsigned, transportHmac: await hmacCommercialTransport('s'.repeat(32), unsigned) }; expect(validateCommercialTransport(envelope)).toContain('transport_expiry_invalid'); expect(validateCommercialTransport({ ...envelope, callbackUrl: 'http://127.0.0.1/callback' })).toContain('callback_url_invalid'); expect(validateCommercialTransport({ ...envelope, inputDownloadUrl: 'http://localhost/input' })).toContain('input_download_url_invalid'); });
});
