import { describe, expect, it } from 'vitest';
import { hmacCommercialTransport, type CommercialTransportEnvelope } from '../../../packages/job-contracts/src/commercialPrecisionExecution';
import { executeCommercialWorker, prepareCommercialWorkerExecution } from './commercial';

const job = { contractVersion: 'nexyfab.precision-cad-commercial-execution.v2' as const, jobId: 'job-1', tenantId: 'tenant-1', projectId: 'project-1', executionId: 'exec-1', generationRunId: 'run-1', generationStateRevision: 11, generationProgramSha256: '9'.repeat(64), workspaceId: 'workspace-1', workspaceRevision: 7, workspaceContentHash: 'a'.repeat(64), tool: 'build_assembly', scope: 'apply' as const, callId: 'call-1', argumentsHash: 'b'.repeat(64), commandHash: 'c'.repeat(64), targetHash: 'd'.repeat(64), journalVersion: 3, attempt: 1, leaseGeneration: 1 };
async function envelope(): Promise<CommercialTransportEnvelope> { const unsigned = { schema: 'nexyfab.precision-cad-commercial-execution.v2' as const, job, issuedAt: '2026-08-22T00:00:00.000Z', expiresAt: '2026-08-22T00:04:00.000Z', callbackUrl: 'https://worker.example.test/callback', leaseCapability: 'x'.repeat(43) }; return { ...unsigned, transportHmac: await hmacCommercialTransport('s'.repeat(32), unsigned) }; }
describe('commercial worker boundary', () => {
  it('does not call executor before endpoint, expiry, and HMAC validation', async () => { let calls = 0; const value = await executeCommercialWorker({ envelope: await envelope(), transportSecret: 'x'.repeat(32), workerEndpoint: 'https://worker.example.test', executor: async () => { calls += 1; throw new Error('must not run'); }, now: Date.parse('2026-08-22T00:01:00.000Z') }); expect(value).toMatchObject({ ok: false, code: 'TRANSPORT_INVALID' }); expect(calls).toBe(0); });
  it('rejects SSRF and missing external configuration as HOLD', async () => { const value = await prepareCommercialWorkerExecution({ envelope: await envelope(), transportSecret: 's'.repeat(32), workerEndpoint: 'https://127.0.0.1' }); expect(value).toMatchObject({ ok: false, code: 'SSRF_BLOCKED' }); const missing = await prepareCommercialWorkerExecution({ envelope: await envelope() }); expect(missing).toMatchObject({ ok: false, code: 'WORKER_ENDPOINT_NOT_CONFIGURED' }); });
});
