/**
 * finishingPassGenerator.ts — Generate finishing toolpaths for CNC
 * after roughing.
 *
 * Finishing pass goals:
 *
 *   - Remove the small stock allowance left after roughing.
 *   - Achieve target surface finish.
 *   - Match part geometry within tolerance.
 *
 * Strategies generated by this module (high level — caller produces
 * actual g-code from the resulting passes):
 *
 *   - **Parallel raster** (zig-zag): horizontal sweep across the
 *     surface at a fixed stepover.
 *   - **Constant scallop** (3D contour): adjust stepover so peak
 *     scallop height stays constant.
 *   - **Spiral**: tool spirals from outside to center (or vice
 *     versa) for flat / shallow areas.
 *   - **Pencil cleanup**: trace edge corners + concave fillets
 *     where the previous tool couldn't reach.
 */

export type FinishingStrategy = 'parallel-raster' | 'constant-scallop' | 'spiral' | 'pencil-cleanup';

export interface SurfaceRegion {
  id: string;
  /** Bounding box in 2D projection. */
  bboxMin: { x: number; y: number };
  bboxMax: { x: number; y: number };
  /** Approximate slope (degrees) — 0 = flat, 90 = vertical wall. */
  slopeDeg: number;
  /** Surface area (mm²). */
  areaMm2: number;
}

export interface FinishingOptions {
  /** Tool diameter, mm. */
  toolDiameterMm: number;
  /** Stepover, mm (used for parallel / spiral). */
  stepoverMm: number;
  /** Target scallop height, mm (used for constant-scallop). */
  scallopHeightMm: number;
  /** Stock allowance left, mm. */
  stockAllowanceMm: number;
  /** Strategy. */
  strategy: FinishingStrategy;
}

export const DEFAULT_OPTIONS: FinishingOptions = {
  toolDiameterMm: 6,
  stepoverMm: 0.5,
  scallopHeightMm: 0.005,
  stockAllowanceMm: 0.2,
  strategy: 'parallel-raster',
};

export interface FinishingPass {
  id: string;
  strategy: FinishingStrategy;
  /** Ordered toolpath points in (x, y, z). */
  points: Array<{ x: number; y: number; z: number }>;
  /** Cumulative length, mm. */
  totalLengthMm: number;
  /** Estimated cutting time at default feed, sec. */
  estimatedTimeSec: number;
}

export interface FinishingResult {
  passes: FinishingPass[];
  /** Strategy actually selected per region. */
  strategyByRegion: Map<string, FinishingStrategy>;
  totalLengthMm: number;
  totalTimeSec: number;
}

// ── Top-level entry ────────────────────────────────────────────

export function generateFinishingPasses(
  regions: SurfaceRegion[],
  options: Partial<FinishingOptions> = {},
  feedMmPerMin: number = 1500,
): FinishingResult {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const passes: FinishingPass[] = [];
  const strategyByRegion = new Map<string, FinishingStrategy>();
  for (const r of regions) {
    // Auto-pick a strategy if user said "parallel-raster" but the
    // region looks better-suited to spiral / pencil.
    const strategy = selectStrategy(r, opts.strategy);
    strategyByRegion.set(r.id, strategy);
    const pass = buildPass(r, strategy, opts, feedMmPerMin);
    passes.push(pass);
  }
  const totalLen = passes.reduce((s, p) => s + p.totalLengthMm, 0);
  const totalTime = passes.reduce((s, p) => s + p.estimatedTimeSec, 0);
  return { passes, strategyByRegion, totalLengthMm: totalLen, totalTimeSec: totalTime };
}

// ── Strategy selection ────────────────────────────────────────

function selectStrategy(region: SurfaceRegion, requested: FinishingStrategy): FinishingStrategy {
  // Override only for clearly mis-matched regions.
  if (region.slopeDeg < 10 && requested === 'pencil-cleanup') {
    return 'parallel-raster';
  }
  if (region.slopeDeg > 70 && requested === 'spiral') {
    return 'parallel-raster';
  }
  // Caller-chosen strategy otherwise.
  return requested;
}

// ── Per-strategy build ────────────────────────────────────────

function buildPass(region: SurfaceRegion, strategy: FinishingStrategy, opts: FinishingOptions, feed: number): FinishingPass {
  const points: Array<{ x: number; y: number; z: number }> = [];
  switch (strategy) {
    case 'parallel-raster':
      buildRaster(region, opts, points);
      break;
    case 'constant-scallop':
      buildConstantScallop(region, opts, points);
      break;
    case 'spiral':
      buildSpiral(region, opts, points);
      break;
    case 'pencil-cleanup':
      buildPencilCleanup(region, opts, points);
      break;
  }
  const length = polylineLength(points);
  const time = feed > 0 ? (length / feed) * 60 : 0;
  return {
    id: `${region.id}-${strategy}`,
    strategy,
    points,
    totalLengthMm: length,
    estimatedTimeSec: time,
  };
}

function buildRaster(region: SurfaceRegion, opts: FinishingOptions, out: Array<{ x: number; y: number; z: number }>): void {
  const w = region.bboxMax.x - region.bboxMin.x;
  const h = region.bboxMax.y - region.bboxMin.y;
  const rows = Math.max(1, Math.floor(h / opts.stepoverMm));
  for (let r = 0; r <= rows; r++) {
    const y = region.bboxMin.y + r * opts.stepoverMm;
    if (r % 2 === 0) {
      out.push({ x: region.bboxMin.x, y, z: 0 });
      out.push({ x: region.bboxMin.x + w, y, z: 0 });
    } else {
      out.push({ x: region.bboxMin.x + w, y, z: 0 });
      out.push({ x: region.bboxMin.x, y, z: 0 });
    }
  }
}

function buildConstantScallop(region: SurfaceRegion, opts: FinishingOptions, out: Array<{ x: number; y: number; z: number }>): void {
  // For scallop height h and tool radius r:
  //   effective stepover = 2 · sqrt(r² - (r - h)²) ≈ 2 · sqrt(2rh) for small h.
  const r = opts.toolDiameterMm / 2;
  const h = opts.scallopHeightMm;
  const stepover = 2 * Math.sqrt(Math.max(0, r * r - (r - h) ** 2));
  const optsCopy = { ...opts, stepoverMm: Math.max(0.01, stepover) };
  buildRaster(region, optsCopy, out);
}

function buildSpiral(region: SurfaceRegion, opts: FinishingOptions, out: Array<{ x: number; y: number; z: number }>): void {
  const cx = (region.bboxMin.x + region.bboxMax.x) / 2;
  const cy = (region.bboxMin.y + region.bboxMax.y) / 2;
  const maxR = Math.min(region.bboxMax.x - cx, region.bboxMax.y - cy);
  const turns = Math.max(1, Math.floor(maxR / opts.stepoverMm));
  const samplesPerTurn = 32;
  for (let i = 0; i <= turns * samplesPerTurn; i++) {
    const t = i / samplesPerTurn;
    const r = (t / turns) * maxR;
    const theta = t * 2 * Math.PI;
    out.push({
      x: cx + r * Math.cos(theta),
      y: cy + r * Math.sin(theta),
      z: 0,
    });
  }
}

function buildPencilCleanup(region: SurfaceRegion, opts: FinishingOptions, out: Array<{ x: number; y: number; z: number }>): void {
  // Walk perimeter for pencil-style cleanup.
  const { bboxMin: a, bboxMax: b } = region;
  out.push({ x: a.x, y: a.y, z: 0 });
  out.push({ x: b.x, y: a.y, z: 0 });
  out.push({ x: b.x, y: b.y, z: 0 });
  out.push({ x: a.x, y: b.y, z: 0 });
  out.push({ x: a.x, y: a.y, z: 0 });
  void opts;
}

function polylineLength(points: Array<{ x: number; y: number; z: number }>): number {
  let total = 0;
  for (let i = 1; i < points.length; i++) {
    const a = points[i - 1]!;
    const b = points[i]!;
    total += Math.hypot(b.x - a.x, b.y - a.y, b.z - a.z);
  }
  return total;
}

// ── Summary ────────────────────────────────────────────────────

export interface FinishingSummary {
  passCount: number;
  totalLengthMm: number;
  totalTimeMin: number;
  longestPassId: string;
}

export function summarize(result: FinishingResult): FinishingSummary {
  const longest = result.passes.reduce((m, p) => p.totalLengthMm > (m?.totalLengthMm ?? 0) ? p : m, undefined as FinishingPass | undefined);
  return {
    passCount: result.passes.length,
    totalLengthMm: result.totalLengthMm,
    totalTimeMin: result.totalTimeSec / 60,
    longestPassId: longest?.id ?? '',
  };
}
