import { describe, expect, it } from 'vitest';
import { DOMAIN_AUTHORITY_SCHEMA, hashDomainAuthorityManifest, validateDomainAuthorityManifest, type DomainAuthorityManifest } from './domainAuthorityManifest';

const manifest = (): DomainAuthorityManifest => ({ schemaVersion: DOMAIN_AUTHORITY_SCHEMA, domain: 'mechanical', projectId: 'p-1', projectRevision: { id: 'r-1', sha256: 'a'.repeat(64) }, sourceRevision: { id: 's-1', sha256: 'b'.repeat(64) }, authorities: [{ id: 'iso-9001', kind: 'standard', sourceRef: 'https://example.test/iso-9001', contentSha256: 'c'.repeat(64), capturedAt: '2026-08-24T00:00:00Z', reviewedAt: '2026-08-24T00:00:00Z', status: 'APPROVED', rights: { status: 'APPROVED', receiptSha256: 'd'.repeat(64) } }] });

describe('domain authority manifest', () => {
  it('passes a complete, rights-bound manifest and hashes key order canonically', () => { const value = manifest(); const result = validateDomainAuthorityManifest(value); expect(result.status).toBe('PASS'); expect(result.canonicalSha256).toBe(hashDomainAuthorityManifest(value)); const reordered: DomainAuthorityManifest = { ...value, authorities: [{ ...value.authorities[0]!, rights: { receiptSha256: 'd'.repeat(64), status: 'APPROVED' } }] }; expect(hashDomainAuthorityManifest(reordered)).toBe(hashDomainAuthorityManifest(value)); });
  it('rejects unknown keys, unsafe/duplicate IDs and blockers without fabricating PASS', () => { const value: any = manifest(); value.extra = true; value.authorities[0].id = 'bad id'; value.authorities.push({ ...value.authorities[0], id: 'safe-duplicate' }, { ...value.authorities[0], id: 'safe-duplicate' }); value.authorities[0].status = 'STALE'; value.authorities[0].rights.status = 'HOLD'; const result = validateDomainAuthorityManifest(value); expect(result.status).toBe('HOLD'); expect(result.canonicalSha256).toBeUndefined(); expect(result.issues).toEqual(expect.arrayContaining(['manifest.extra:unknown_key', 'authorities[0].id:unsafe_id', 'authorities[2].id:duplicate', 'authorities[0].status:stale_blocker', 'authorities[0].rights.status:hold_blocker'])); });
  it('requires receipt hashes for approved rights and bounds finite input', () => { const value: any = manifest(); delete value.authorities[0].rights.receiptSha256; value.authorities = Array(101).fill(value.authorities[0]); const result = validateDomainAuthorityManifest(value); expect(result.status).toBe('HOLD'); expect(result.issues).toContain('authorities:invalid_count'); expect(result.issues).toContain('authorities[0].rights.receiptSha256:required_for_approval'); });
});
