import fs from 'node:fs';
import path from 'node:path';

const input = path.resolve(process.argv[2] ?? 'docs/evidence/complex-holdout-review-260806/ifc-native-results.json');
const output = path.resolve(process.argv[3] ?? 'docs/evidence/external-step-structure-coverage-260806/ifc-fidelity-run-1.json');
type Measurement = { caseId: string; imported: number; exact: number; approx: number; exactMeshVolume: number; exactDisplayMesh?: number; openSurfaceMesh?: number; topologyPromotedClosedMesh?: number; degenerateRepairParts?: number; removedDegenerateFaces?: number; boundaryEdges?: number; boundaryComponents?: number; closedBoundaryLoops?: number; openBoundaryChains?: number; branchedBoundaryComponents?: number; planarClosedBoundaryLoops?: number; microGapCandidates?: number; totalBoundaryLengthMm?: number; nonManifoldEdges?: number; degenerateFaces?: number; aabbOnly: number; skipped: number; skipByClass: Record<string, number> };
const batch = JSON.parse(fs.readFileSync(input, 'utf8')) as { failures: unknown[]; measurements: Measurement[] };
const cases = batch.measurements.map(item => {
  const entries = Object.entries(item.skipByClass); const excludedContainers = entries.filter(([key]) => /:(spatial|aggregate)$/.test(key)).reduce((sum, [, count]) => sum + count, 0); const unsupportedPhysical = entries.filter(([key]) => !/:(spatial|aggregate)$/.test(key)).reduce((sum, [, count]) => sum + count, 0);
  const physicalCandidates = item.imported + unsupportedPhysical; const physicalImportCoverage = physicalCandidates ? item.imported / physicalCandidates : 0; const exactVolumeCoverage = item.imported ? (item.exact + item.exactMeshVolume) / item.imported : 0; const exactDisplayGeometryCoverage = item.imported ? (item.exact + (item.exactDisplayMesh ?? 0)) / item.imported : 0;
  const openSurfaceMesh = item.openSurfaceMesh ?? 0, releaseReady = unsupportedPhysical === 0 && exactVolumeCoverage >= 0.95 && exactDisplayGeometryCoverage >= 0.95 && openSurfaceMesh === 0;
  return { caseId: item.caseId, status: unsupportedPhysical ? 'fail' : 'pass', releaseReady, counts: { imported: item.imported, exactExtrusionDisplay: item.exact, exactMeshVolume: item.exactMeshVolume, exactDisplayMesh: item.exactDisplayMesh ?? 0, openSurfaceMesh, topologyPromotedClosedMesh: item.topologyPromotedClosedMesh ?? 0, degenerateRepairParts: item.degenerateRepairParts ?? 0, removedDegenerateFaces: item.removedDegenerateFaces ?? 0, boundaryEdges: item.boundaryEdges ?? 0, boundaryComponents: item.boundaryComponents ?? 0, closedBoundaryLoops: item.closedBoundaryLoops ?? 0, openBoundaryChains: item.openBoundaryChains ?? 0, branchedBoundaryComponents: item.branchedBoundaryComponents ?? 0, planarClosedBoundaryLoops: item.planarClosedBoundaryLoops ?? 0, microGapCandidates: item.microGapCandidates ?? 0, totalBoundaryLengthMm: item.totalBoundaryLengthMm ?? 0, nonManifoldEdges: item.nonManifoldEdges ?? 0, degenerateFaces: item.degenerateFaces ?? 0, aabbOnly: item.aabbOnly, excludedContainers, unsupportedPhysical }, coverage: { physicalImportCoverage, exactVolumeCoverage, exactDisplayGeometryCoverage }, gates: { physicalImport: physicalImportCoverage >= 0.95 ? 'pass' : 'fail', exactVolume: exactVolumeCoverage >= 0.95 ? 'pass' : 'fail', exactDisplayGeometry: exactDisplayGeometryCoverage >= 0.95 ? 'pass' : 'fail', closedManufacturingSolids: openSurfaceMesh === 0 ? 'pass' : 'fail' } };
});
const totalKeys = ['imported', 'exactExtrusionDisplay', 'exactMeshVolume', 'exactDisplayMesh', 'openSurfaceMesh', 'topologyPromotedClosedMesh', 'degenerateRepairParts', 'removedDegenerateFaces', 'boundaryEdges', 'boundaryComponents', 'closedBoundaryLoops', 'openBoundaryChains', 'branchedBoundaryComponents', 'planarClosedBoundaryLoops', 'microGapCandidates', 'totalBoundaryLengthMm', 'nonManifoldEdges', 'degenerateFaces', 'aabbOnly', 'excludedContainers', 'unsupportedPhysical'] as const;
const totals = cases.reduce((sum, item) => { for (const key of totalKeys) sum[key] += item.counts[key]; return sum; }, Object.fromEntries(totalKeys.map(key => [key, 0])) as Record<typeof totalKeys[number], number>);
const artifact = { schema: 'nexyfab.ifc-fidelity-evidence.v1', generatedAt: new Date().toISOString(), scoreEligible: false, releaseReady: cases.every(item => item.releaseReady), policy: { excludedContainersAreNotPhysicalFailures: true, exactMeshVolumeDoesNotImplyExactDisplayGeometry: true, openSurfaceMeshDoesNotImplyManufacturingSolid: true, aabbOnlyCannotPassManufacturingGeometry: true }, summary: { cases: cases.length, failures: batch.failures.length, totals, physicalImportCoverage: totals.imported / (totals.imported + totals.unsupportedPhysical), exactVolumeCoverage: (totals.exactExtrusionDisplay + totals.exactMeshVolume) / totals.imported, exactDisplayGeometryCoverage: (totals.exactExtrusionDisplay + totals.exactDisplayMesh) / totals.imported }, cases };
fs.mkdirSync(path.dirname(output), { recursive: true }); fs.writeFileSync(output, `${JSON.stringify(artifact, null, 2)}\n`, 'utf8'); console.log(JSON.stringify({ output: path.relative(process.cwd(), output), releaseReady: artifact.releaseReady, ...artifact.summary }));
