import {
  AI_DESIGN_DURABLE_OUTBOX_MAX_DELIVERY_ATTEMPTS, AI_DESIGN_DURABLE_OUTBOX_MAX_PAYLOAD_BYTES, DurableStoreError,
  assertId, assertProjectSession, assertTimestamp, backoffMs, clone, nowIso, payloadDigest, type DurableStoreMode,
} from './aiDesignDurableJobPrimitives';

export const TRANSACTIONAL_OUTBOX_CONTRACT_V1_SCHEMA = 'nexyfab.transactional-outbox-contract.v1' as const;
export type TransactionalOutboxStatusV1 = 'PENDING' | 'LEASED' | 'DELIVERED' | 'DEAD_LETTER';
export interface TransactionalOutboxEventV1 {
  schema: typeof TRANSACTIONAL_OUTBOX_CONTRACT_V1_SCHEMA; eventId: string; dedupeKey: string; aggregateId: string; projectId: string; sessionId: string;
  sequence: number; revision: number; transactionId: string; eventType: string; payloadDigest: string; payloadBytes: number; status: TransactionalOutboxStatusV1; deliveryAttempts: number;
  availableAt: string; createdAt: string; updatedAt: string; lease: { owner: string; expiresAt: string } | null; lastErrorCode: string | null;
}
export interface TransactionalOutboxContractV1 {
  append(input: { eventId: string; dedupeKey: string; aggregateId: string; projectId: string; sessionId: string; eventType: string; payload: unknown; expectedPreviousSequence: number; transactionId: string; now?: string }): TransactionalOutboxEventV1;
  get(scope: { projectId: string; sessionId: string; eventId: string }): TransactionalOutboxEventV1 | null;
  claim(input: { projectId: string; sessionId: string; eventId: string; owner: string; leaseMs: number; expectedRevision: number; now?: string }): TransactionalOutboxEventV1;
  ack(input: { projectId: string; sessionId: string; eventId: string; owner: string; expectedRevision: number; now?: string }): TransactionalOutboxEventV1;
  retry(input: { projectId: string; sessionId: string; eventId: string; owner: string; errorCode: string; expectedRevision: number; now?: string }): TransactionalOutboxEventV1;
  replay(input: { projectId: string; sessionId: string; eventId: string }): TransactionalOutboxEventV1;
}
function checkMs(value: number): void { if (!Number.isSafeInteger(value) || value < 1 || value > 24 * 60 * 60 * 1_000) throw new DurableStoreError('INVALID_INPUT', 'lease_ms_invalid'); }
function scope(input: { projectId: string; sessionId: string; eventId?: string }): void { assertProjectSession(input.projectId, input.sessionId); if (input.eventId !== undefined) assertId(input.eventId, 'event_id'); }

/** Reference-only memory adapter. It is intentionally unusable in commercial mode until backed by a DB transaction. */
export class InMemoryTransactionalOutboxV1 implements TransactionalOutboxContractV1 {
  private readonly rows = new Map<string, TransactionalOutboxEventV1>(); private readonly dedupe = new Map<string, string>(); private readonly sequence = new Map<string, number>();
  constructor(private readonly options: { mode: DurableStoreMode; now?: () => number }) {}
  private ensure(): void { if (this.options.mode === 'commercial') throw new DurableStoreError('COMMERCIAL_PERSISTENCE_REQUIRED', 'commercial_transactional_outbox_required'); }
  private clock = (): number => this.options.now?.() ?? Date.now();
  private key(projectId: string, sessionId: string, eventId: string): string { return `${projectId}\0${sessionId}\0${eventId}`; }
  private aggregateKey(projectId: string, sessionId: string, aggregateId: string): string { return `${projectId}\0${sessionId}\0${aggregateId}`; }
  private require(input: { projectId: string; sessionId: string; eventId: string }): TransactionalOutboxEventV1 { scope(input); const row = this.rows.get(this.key(input.projectId, input.sessionId, input.eventId)); if (!row) throw new DurableStoreError('NOT_FOUND', 'outbox_event_not_found'); return row; }
  append(input: { eventId: string; dedupeKey: string; aggregateId: string; projectId: string; sessionId: string; eventType: string; payload: unknown; expectedPreviousSequence: number; transactionId: string; now?: string }): TransactionalOutboxEventV1 {
    this.ensure(); scope(input); assertId(input.dedupeKey, 'dedupe_key'); assertId(input.aggregateId, 'aggregate_id'); assertId(input.eventType, 'event_type'); assertId(input.transactionId, 'transaction_id'); if (!Number.isSafeInteger(input.expectedPreviousSequence) || input.expectedPreviousSequence < 0) throw new DurableStoreError('INVALID_INPUT', 'outbox_sequence_invalid'); const digest = payloadDigest(input.payload, AI_DESIGN_DURABLE_OUTBOX_MAX_PAYLOAD_BYTES); const dedupeKey = `${input.projectId}\0${input.sessionId}\0${input.dedupeKey}`; const existingId = this.dedupe.get(dedupeKey);
    if (existingId) { const prior = this.rows.get(this.key(input.projectId, input.sessionId, existingId))!; if (prior.payloadDigest !== digest.digest || prior.eventType !== input.eventType) throw new DurableStoreError('IDEMPOTENCY_CONFLICT', 'outbox_dedupe_payload_mismatch'); return clone(prior); }
    const eventKey = this.key(input.projectId, input.sessionId, input.eventId); if (this.rows.has(eventKey)) throw new DurableStoreError('IDEMPOTENCY_CONFLICT', 'outbox_event_exists'); const now = input.now ?? nowIso(() => this.clock()); assertTimestamp(now); const aggregateKey = this.aggregateKey(input.projectId, input.sessionId, input.aggregateId); const previousSequence = this.sequence.get(aggregateKey) ?? 0; if (previousSequence !== input.expectedPreviousSequence) throw new DurableStoreError('CAS_CONFLICT', 'outbox_sequence_conflict'); const sequence = previousSequence + 1;
    const row: TransactionalOutboxEventV1 = { schema: TRANSACTIONAL_OUTBOX_CONTRACT_V1_SCHEMA, eventId: input.eventId, dedupeKey: input.dedupeKey, aggregateId: input.aggregateId, projectId: input.projectId, sessionId: input.sessionId, sequence, revision: 0, transactionId: input.transactionId, eventType: input.eventType, payloadDigest: digest.digest, payloadBytes: digest.bytes, status: 'PENDING', deliveryAttempts: 0, availableAt: now, createdAt: now, updatedAt: now, lease: null, lastErrorCode: null };
    this.rows.set(eventKey, row); this.dedupe.set(dedupeKey, input.eventId); this.sequence.set(aggregateKey, sequence); return clone(row);
  }
  get(input: { projectId: string; sessionId: string; eventId: string }): TransactionalOutboxEventV1 | null { this.ensure(); scope(input); return clone(this.rows.get(this.key(input.projectId, input.sessionId, input.eventId)) ?? null); }
  private cas(row: TransactionalOutboxEventV1, expectedRevision: number): void { if (!Number.isSafeInteger(expectedRevision) || expectedRevision < 0 || row.revision !== expectedRevision) throw new DurableStoreError('CAS_CONFLICT', 'outbox_revision_conflict'); }
  private priorPending(row: TransactionalOutboxEventV1): boolean { for (const candidate of this.rows.values()) if (candidate.projectId === row.projectId && candidate.sessionId === row.sessionId && candidate.aggregateId === row.aggregateId && candidate.sequence < row.sequence && candidate.status !== 'DELIVERED') return true; return false; }
  claim(input: { projectId: string; sessionId: string; eventId: string; owner: string; leaseMs: number; expectedRevision: number; now?: string }): TransactionalOutboxEventV1 {
    this.ensure(); const row = this.require(input); this.cas(row, input.expectedRevision); assertId(input.owner, 'lease_owner'); checkMs(input.leaseMs); const now = input.now ?? nowIso(() => this.clock()); assertTimestamp(now); if (row.status === 'DELIVERED' || row.status === 'DEAD_LETTER') throw new DurableStoreError('TERMINAL', 'outbox_terminal'); if (Date.parse(row.availableAt) > Date.parse(now)) throw new DurableStoreError('LEASE_CONFLICT', 'outbox_not_available'); if (this.priorPending(row)) throw new DurableStoreError('ORDERING_BLOCKED', 'outbox_prior_event_pending'); if (row.lease && Date.parse(row.lease.expiresAt) > Date.parse(now)) { if (row.lease.owner !== input.owner) throw new DurableStoreError('LEASE_CONFLICT', 'outbox_lease_owned'); return clone(row); } row.deliveryAttempts += 1; if (row.deliveryAttempts > AI_DESIGN_DURABLE_OUTBOX_MAX_DELIVERY_ATTEMPTS) { row.status = 'DEAD_LETTER'; row.lastErrorCode = 'DELIVERY_ATTEMPTS_EXCEEDED'; row.lease = null; row.updatedAt = now; row.revision += 1; throw new DurableStoreError('RETRY_EXHAUSTED', 'outbox_delivery_attempts_exceeded'); } row.status = 'LEASED'; row.lease = { owner: input.owner, expiresAt: new Date(Date.parse(now) + input.leaseMs).toISOString() }; row.updatedAt = now; row.revision += 1; return clone(row);
  }
  ack(input: { projectId: string; sessionId: string; eventId: string; owner: string; expectedRevision: number; now?: string }): TransactionalOutboxEventV1 { this.ensure(); const row = this.require(input); this.cas(row, input.expectedRevision); const now = input.now ?? nowIso(() => this.clock()); assertTimestamp(now); if (!row.lease || row.lease.owner !== input.owner || Date.parse(row.lease.expiresAt) <= Date.parse(now)) throw new DurableStoreError('LEASE_CONFLICT', 'outbox_lease_invalid'); row.status = 'DELIVERED'; row.lease = null; row.updatedAt = now; row.revision += 1; return clone(row); }
  retry(input: { projectId: string; sessionId: string; eventId: string; owner: string; errorCode: string; expectedRevision: number; now?: string }): TransactionalOutboxEventV1 { this.ensure(); const row = this.require(input); this.cas(row, input.expectedRevision); const now = input.now ?? nowIso(() => this.clock()); assertTimestamp(now); assertId(input.errorCode, 'error_code'); if (!row.lease || row.lease.owner !== input.owner || Date.parse(row.lease.expiresAt) <= Date.parse(now)) throw new DurableStoreError('LEASE_CONFLICT', 'outbox_lease_invalid'); row.lease = null; row.lastErrorCode = input.errorCode; if (row.deliveryAttempts >= AI_DESIGN_DURABLE_OUTBOX_MAX_DELIVERY_ATTEMPTS) row.status = 'DEAD_LETTER'; else { row.status = 'PENDING'; row.availableAt = new Date(Date.parse(now) + backoffMs(row.deliveryAttempts)).toISOString(); } row.updatedAt = now; row.revision += 1; return clone(row); }
  replay(input: { projectId: string; sessionId: string; eventId: string }): TransactionalOutboxEventV1 { this.ensure(); return clone(this.require(input)); }
}
