import { describe, expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { createProductStructureGraph } from './aiDesignProductStructureGraph';
import { createAiDesignGraphPartitions, validateAiDesignGraphPartition, createAiDesignHierarchicalCandidateArtifact, validateAiDesignHierarchicalCandidateArtifact, validateAiDesignHierarchicalCandidateSet } from './aiDesignHierarchicalCandidatePartition';

const graph = createProductStructureGraph({ projectId: 'project-1', sessionId: 's1', revision: 'r1', rootNodeId: 'assembly-1', nodes: [{ nodeId: 'assembly-1', kind: 'assembly', label: 'Root', parentId: null, sourceIntentNodeIds: [] }, { nodeId: 'part-1', kind: 'component', label: 'Part', parentId: 'assembly-1', sourceIntentNodeIds: [] }, { nodeId: 'part-2', kind: 'component', label: 'Part 2', parentId: 'assembly-1', sourceIntentNodeIds: [] }], edges: [{ edgeId: 'e1', kind: 'contains', from: 'assembly-1', to: 'part-1' }, { edgeId: 'e2', kind: 'contains', from: 'assembly-1', to: 'part-2' }], interfaces: [] });

describe('hierarchical candidate partition contract', () => {
  it('creates deterministic complete partitions with explicit authority not-run', () => { const result = createAiDesignGraphPartitions(graph, [{ partitionId: 'p1', artifactId: 'a1', nodeIds: ['assembly-1', 'part-1'] }, { partitionId: 'p2', artifactId: 'a2', nodeIds: ['part-2'] }]); expect(result.coverage).toBe('complete'); expect(result.issues).toEqual([]); expect(validateAiDesignGraphPartition(result.partitions[0], graph)).toEqual([]); expect(result.partitions[0]?.exactGeometryStatus).toBe('not_run'); });
  it('rejects overlap without explicit boundary and detects partial coverage', () => { const result = createAiDesignGraphPartitions(graph, [{ partitionId: 'p1', artifactId: 'a1', nodeIds: ['assembly-1', 'part-1'] }, { partitionId: 'p2', artifactId: 'a2', nodeIds: ['part-1'] }]); expect(result.coverage).toBe('partial'); expect(result.issues).toContain('partition_overlap_without_boundary:part-1'); });
  it('binds a hierarchy without changing the exact candidate authority', () => { const parentMaterial = { schema: 'nexyfab.ai-design-candidate-artifact.v1' as const, artifactId: 'a1', candidateId: 'c1', projectId: 'project-1', sessionId: 's1', baseRevision: 'r1', artifactRevision: 1, status: 'published' as const, createdAt: '2026-08-24T00:00:00.000Z', contentDigest: 'a'.repeat(64), designDigest: 'b'.repeat(64), dependencies: { intentNodeIds: [], parameterIds: [], gaugeIds: [], featureIds: [] }, evidence: [], server: { generatorId: 'g1', modelId: 'm1', runtimeId: 'r1', workerBuildDigest: 'c'.repeat(64), generationRunId: 'run1' }, supersedes: null }; const canonical = (value: unknown): string => Array.isArray(value) ? `[${value.map(canonical).join(',')}]` : value && typeof value === 'object' ? `{${Object.keys(value as Record<string, unknown>).sort().map(key => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(',')}}` : JSON.stringify(value); const parent = { ...parentMaterial, manifestDigest: createHash('sha256').update(canonical(parentMaterial)).digest('hex') }; const item = createAiDesignHierarchicalCandidateArtifact({ artifact: parent, level: 'assembly', parentArtifactId: null, childArtifactIds: [], graphPartitionIds: ['p1'], graphCoverage: 'complete' }); expect(validateAiDesignHierarchicalCandidateArtifact(item)).toEqual([]); });
  it('rejects hierarchy cycles and inconsistent child links', () => { const base = { schema: 'nexyfab.ai-design-candidate-artifact.v1' as const, candidateId: 'c1', projectId: 'project-1', sessionId: 's1', baseRevision: 'r1', artifactRevision: 1, status: 'published' as const, createdAt: '2026-08-24T00:00:00.000Z', contentDigest: 'a'.repeat(64), designDigest: 'b'.repeat(64), dependencies: { intentNodeIds: [], parameterIds: [], gaugeIds: [], featureIds: [] }, evidence: [], server: { generatorId: 'g1', modelId: 'm1', runtimeId: 'r1', workerBuildDigest: 'c'.repeat(64), generationRunId: 'run1' }, supersedes: null }; const fake = (artifactId: string) => ({ ...base, artifactId, manifestDigest: 'd'.repeat(64) }); const a = createAiDesignHierarchicalCandidateArtifact({ artifact: fake('a1'), level: 'assembly', parentArtifactId: 'a2', childArtifactIds: ['a2'], graphPartitionIds: ['p1'], graphCoverage: 'complete' }); const b = createAiDesignHierarchicalCandidateArtifact({ artifact: fake('a2'), level: 'subassembly', parentArtifactId: 'a1', childArtifactIds: ['a1'], graphPartitionIds: ['p2'], graphCoverage: 'complete' }); expect(validateAiDesignHierarchicalCandidateSet([a, b])).toEqual(expect.arrayContaining(['hierarchical_cycle:a1', 'hierarchical_cycle:a2'])); });
});
