import { describe, expect, it } from 'vitest';
import { DurableStoreError } from './aiDesignDurableJobPrimitives';
import { InMemoryTransactionalOutboxV1 } from './aiDesignTransactionalOutbox';

const base = { projectId: 'p1', sessionId: 's1' };
describe('TransactionalOutboxContractV1 reference contract', () => {
  it('assigns ordered sequences and blocks later delivery until earlier event is delivered', () => {
    const outbox = new InMemoryTransactionalOutboxV1({ mode: 'reference' }); outbox.append({ ...base, eventId: 'e1', dedupeKey: 'd1', aggregateId: 'job1', eventType: 'JOB_CREATED', payload: { n: 1 }, expectedPreviousSequence: 0, transactionId: 'tx1', now: '2026-08-24T00:00:00.000Z' }); outbox.append({ ...base, eventId: 'e2', dedupeKey: 'd2', aggregateId: 'job1', eventType: 'JOB_STARTED', payload: { n: 2 }, expectedPreviousSequence: 1, transactionId: 'tx2', now: '2026-08-24T00:00:00.000Z' }); expect(() => outbox.claim({ ...base, eventId: 'e2', owner: 'w', leaseMs: 1000, expectedRevision: 0, now: '2026-08-24T00:00:00.000Z' })).toThrowError(DurableStoreError); const one = outbox.claim({ ...base, eventId: 'e1', owner: 'w', leaseMs: 1000, expectedRevision: 0, now: '2026-08-24T00:00:00.000Z' }); expect(one.sequence).toBe(1); outbox.ack({ ...base, eventId: 'e1', owner: 'w', expectedRevision: one.revision, now: '2026-08-24T00:00:00.000Z' }); expect(outbox.claim({ ...base, eventId: 'e2', owner: 'w', leaseMs: 1000, expectedRevision: 0, now: '2026-08-24T00:00:00.000Z' }).sequence).toBe(2);
  });
  it('deduplicates replay and requires the lease owner to acknowledge', () => {
    const outbox = new InMemoryTransactionalOutboxV1({ mode: 'reference' }); const event = outbox.append({ ...base, eventId: 'e1', dedupeKey: 'd1', aggregateId: 'job1', eventType: 'JOB_CREATED', payload: { ok: true }, expectedPreviousSequence: 0, transactionId: 'tx1', now: '2026-08-24T00:00:00.000Z' }); expect(outbox.append({ ...base, eventId: 'e9', dedupeKey: 'd1', aggregateId: 'job1', eventType: 'JOB_CREATED', payload: { ok: true }, expectedPreviousSequence: 0, transactionId: 'tx9' })).toEqual(event); const leased = outbox.claim({ ...base, eventId: 'e1', owner: 'w', leaseMs: 1000, expectedRevision: 0, now: '2026-08-24T00:00:00.000Z' }); expect(() => outbox.ack({ ...base, eventId: 'e1', owner: 'other', expectedRevision: leased.revision, now: '2026-08-24T00:00:00.000Z' })).toThrowError(DurableStoreError); expect(outbox.replay({ ...base, eventId: 'e1' }).status).toBe('LEASED');
  });
  it('requires sequence and row CAS, and fails closed commercially', () => { const local = new InMemoryTransactionalOutboxV1({ mode: 'reference' }); local.append({ ...base, eventId: 'e1', dedupeKey: 'd1', aggregateId: 'j', eventType: 'X', payload: {}, expectedPreviousSequence: 0, transactionId: 'tx1' }); expect(() => local.append({ ...base, eventId: 'e2', dedupeKey: 'd2', aggregateId: 'j', eventType: 'Y', payload: {}, expectedPreviousSequence: 0, transactionId: 'tx2' })).toThrowError(/sequence/); const outbox = new InMemoryTransactionalOutboxV1({ mode: 'commercial' }); expect(() => outbox.append({ ...base, eventId: 'e1', dedupeKey: 'd1', aggregateId: 'j', eventType: 'X', payload: {}, expectedPreviousSequence: 0, transactionId: 'tx1' })).toThrowError(/commercial/); });
});
