import { describe, expect, it } from 'vitest';
import { createAiDesignCrossDomainConstraintGraph, invalidateAiDesignCrossDomainGraph, validateAiDesignCrossDomainConstraintGraph } from './aiDesignCrossDomainConstraintGraph';
const hash = 'a'.repeat(64);
const node = (id: string, domain: 'mechanical' | 'electrical' | 'thermal', key: string, value: unknown) => ({ id, kind: 'constraint' as const, domain, key, value, sourceIds: [`source-${id}`], sourceHashes: [hash], confidence: 0.9 });
describe('cross-domain constraint graph', () => {
  it('supports all engineering domains and preserves interface links', () => { const graph = createAiDesignCrossDomainConstraintGraph({ projectId: 'project-1', sessionId: 'session-1', graphRevision: 2, sourceContentHash: hash, nodes: [node('m', 'mechanical', 'load', 10), node('e', 'electrical', 'voltage', 24)], edges: [{ kind: 'interface_link', from: 'm', to: 'e', interfaceKey: 'mounting-power' }] }); expect(graph.edges[0]?.kind).toBe('interface_link'); expect(validateAiDesignCrossDomainConstraintGraph(graph)).toEqual([]); expect(graph.contentHash).toMatch(/^[a-f0-9]{64}$/); });
  it('creates a conflict node instead of selecting a cross-domain value', () => { const graph = createAiDesignCrossDomainConstraintGraph({ projectId: 'project-1', sessionId: 'session-1', graphRevision: 2, sourceContentHash: hash, nodes: [node('m', 'mechanical', 'temperature', 40), node('t', 'thermal', 'temperature', 80)] }); expect(graph.nodes.some(item => item.kind === 'conflict')).toBe(true); expect(graph.nodes.find(item => item.kind === 'conflict')?.alternatives).toHaveLength(2); });
  it('invalidates dependent nodes transitively and deterministically', () => { const graph = createAiDesignCrossDomainConstraintGraph({ projectId: 'project-1', sessionId: 'session-1', graphRevision: 2, sourceContentHash: hash, nodes: [node('a', 'mechanical', 'a', 1), node('b', 'electrical', 'b', 2), node('c', 'thermal', 'c', 3)], edges: [{ kind: 'depends_on', from: 'a', to: 'b' }, { kind: 'interface_link', from: 'b', to: 'c', interfaceKey: 'power-thermal' }] }); const next = invalidateAiDesignCrossDomainGraph(graph, ['a']); expect(next.nodes.filter(item => item.status === 'invalidated').map(item => item.id)).toEqual(['a', 'b', 'c']); expect(next.graphRevision).toBe(3); expect(next.contentHash).not.toBe(graph.contentHash); });
});
