import { describe, expect, it } from 'vitest';
import { createAiDesignCrossDomainConstraintGraph } from './aiDesignCrossDomainConstraintGraph';
import { createAiDesignIntentResolutionArtifact, InMemoryAiDesignIntentResolutionStore, validateAiDesignIntentResolutionCommand } from './aiDesignIntentResolution';
const hash = 'b'.repeat(64);
const graph = createAiDesignCrossDomainConstraintGraph({ projectId: 'project-1', sessionId: 'session-1', graphRevision: 4, sourceContentHash: hash, nodes: [{ id: 'constraint-1', kind: 'constraint', domain: 'mechanical', key: 'material', value: 'steel', sourceIds: ['source-1'], sourceHashes: [hash], confidence: 0.8 }, { id: 'constraint-2', kind: 'constraint', domain: 'thermal', key: 'material', value: 'aluminium', sourceIds: ['source-2'], sourceHashes: [hash], confidence: 0.7 }] });
describe('intent resolution command and immutable store', () => {
  it('requires an explicit selection and binds it to the graph revision', () => { const conflict = graph.nodes.find(item => item.kind === 'conflict')!; const command = { schema: 'nexyfab.ai-design-intent-resolution-command.v1' as const, commandId: 'command-1', projectId: 'project-1', sessionId: 'session-1', expectedGraphRevision: 4, graphContentHash: graph.contentHash, targetNodeId: conflict.id, selection: { type: 'select_alternative' as const, alternativeIndex: 0 }, rationale: 'User selected the approved material.', provenance: { sourceIds: ['source-1'], sourceHashes: [hash] } }; expect(validateAiDesignIntentResolutionCommand(command)).toEqual([]); const artifact = createAiDesignIntentResolutionArtifact(command, graph, { artifactId: 'artifact-1', trustedServer: true, createdAt: '2026-08-24T00:00:00.000Z' }); expect(artifact.trustedServer).toBe(true); expect(artifact.graphRevision).toBe(5); expect(artifact.resultingContentHash).toMatch(/^[a-f0-9]{64}$/); expect(artifact.impactedNodeIds).toEqual([]); });
  it('rejects client evidence claims and stale graph revisions', () => { const command = { schema: 'nexyfab.ai-design-intent-resolution-command.v1' as const, commandId: 'command-2', projectId: 'project-1', sessionId: 'session-1', expectedGraphRevision: 4, graphContentHash: graph.contentHash, targetNodeId: 'constraint-1', selection: { type: 'provide_value' as const, value: { verificationPass: true } }, rationale: 'try', provenance: { sourceIds: [], sourceHashes: [] } }; expect(validateAiDesignIntentResolutionCommand(command)).toContain('resolution_selection_invalid'); expect(() => createAiDesignIntentResolutionArtifact({ ...command, selection: { type: 'provide_value', value: 'copper' } }, { ...graph, graphRevision: 5 }, { artifactId: 'artifact-2', trustedServer: true })).toThrow('resolution_graph_revision_conflict'); });
  it('is append-only and replay-safe without allowing overwrite', () => { const store = new InMemoryAiDesignIntentResolutionStore(); const conflict = graph.nodes.find(item => item.kind === 'conflict')!; const command = { schema: 'nexyfab.ai-design-intent-resolution-command.v1' as const, commandId: 'command-3', projectId: 'project-1', sessionId: 'session-1', expectedGraphRevision: 4, graphContentHash: graph.contentHash, targetNodeId: conflict.id, selection: { type: 'provide_value' as const, value: 'titanium' }, rationale: 'User provided a value.', provenance: { sourceIds: [], sourceHashes: [] } }; const artifact = createAiDesignIntentResolutionArtifact(command, graph, { artifactId: 'artifact-3', trustedServer: true }); expect(store.append(artifact)).toEqual({ ok: true }); expect(store.append(artifact)).toEqual({ ok: true }); expect(store.append({ ...artifact, artifactId: 'other-artifact' })).toEqual({ ok: false, issues: ['resolution_artifact_digest_mismatch'] }); expect(store.list({ projectId: 'project-1', sessionId: 'session-1' })).toHaveLength(1); });
});
