import { createHash } from 'node:crypto';
import type { ExactLineWall } from './architectureInteriorExactGeometry';
import type { ArchitectureExactKernelAdapter } from './architectureInteriorExactGeometry';

export const ARCHITECTURE_OPENING_EXACT_CONTRACT_VERSION = 'nexyfab.architecture-opening-exact.v1';
type V2 = readonly [number, number];
type V3 = readonly [number, number, number];

export interface OpeningExactBinding { projectId: string; architectureDocumentId: string; workspaceRevision: number; workspaceContentHash: string }
export interface OpeningExactFrame { id: string; parentId: string; originMm: V3; rotationDeg: V3 }
export interface OpeningExactLevel { storeyId: string; spaceId: string; elevationMm: number; heightMm: number; sourceHash: string }
export interface OpeningExactSpec {
  id: string;
  kind: 'door' | 'window';
  hostWallId: string;
  offsetMm: number;
  widthMm: number;
  heightMm: number;
  sillMm: number;
  handing: 'left' | 'right' | 'none';
  swing: 'in' | 'out' | 'none';
  swingClearanceMm: number;
  sourceHash: string;
}
export interface OpeningExactFrameSpec { jambMm: number; headMm: number; depthMm: number; sourceHash: string }
export interface OpeningExactLeafSpec { thicknessMm: number; insetMm: number; sourceHash: string }
export interface OpeningExactGlazingSpec { thicknessMm: number; insetMm: number; sourceHash: string }
export interface ArchitectureOpeningExactGeometryRequest {
  contractVersion: typeof ARCHITECTURE_OPENING_EXACT_CONTRACT_VERSION;
  units: 'mm'; toleranceMm: number; binding: OpeningExactBinding; coordinateFrame: OpeningExactFrame;
  hostWall: ExactLineWall; hostWallSourceHash: string; hostLevel: OpeningExactLevel; opening: OpeningExactSpec;
  frame: OpeningExactFrameSpec; leaf: OpeningExactLeafSpec; glazing?: OpeningExactGlazingSpec;
}
export interface OpeningExactShapeReceipt {
  kind: 'host_wall_final' | 'frame_jamb' | 'frame_head' | 'leaf' | 'glazing'; elementId: string; sourceHash: string;
  stepText: string; stepBytes: number; stepSha256: string; shapeHash: string; absoluteVolume: number;
  bbox: { min: { x: number; y: number; z: number }; max: { x: number; y: number; z: number } }; manifoldSolid: boolean; maxToleranceMm: number;
}
export interface ArchitectureOpeningExactGeometryReceipt {
  contractVersion: typeof ARCHITECTURE_OPENING_EXACT_CONTRACT_VERSION; units: 'mm'; binding: OpeningExactBinding; coordinateFrame: OpeningExactFrame;
  hostWallId: string; storeyId: string; spaceId: string; openingId: string; openingKind: 'door' | 'window';
  offsetMm: number; widthMm: number; heightMm: number; sillMm: number; handing: OpeningExactSpec['handing']; swing: OpeningExactSpec['swing']; swingClearanceMm: number;
  jambMm: number; headMm: number; frameDepthMm: number; leafThicknessMm: number; glazingThicknessMm?: number;
  hostVolumeBeforeCut: number; hostVolumeAfterCut: number; hostWallSourceHash: string; levelSourceHash: string; openingSourceHash: string; frameSourceHash: string; leafSourceHash: string; glazingSourceHash?: string;
  hostWall: OpeningExactShapeReceipt; frameJambs: readonly [OpeningExactShapeReceipt, OpeningExactShapeReceipt]; frameHead: OpeningExactShapeReceipt; leaf: OpeningExactShapeReceipt; glazing?: OpeningExactShapeReceipt;
  contentHash: string; releaseReady: false; hold: readonly ['fire_acoustic_thermal_not_run', 'code_hardware_schedule_not_run', 'native_ifc_drawing_not_run', 'field_measurement_not_run', 'independent_step_reimport_not_run'];
}
export type ArchitectureOpeningExactGeometryResult = { ok: true; receipt: ArchitectureOpeningExactGeometryReceipt } | { ok: false; code: 'EXACT_OPENING_INVALID_REQUEST' | 'EXACT_OPENING_KERNEL_FAILED' | 'EXACT_OPENING_VERIFICATION_FAILED' | 'EXACT_OPENING_STALE'; details: string[] };

const ID = /^[A-Za-z][A-Za-z0-9._:-]{0,127}$/; const HASH = /^[a-f0-9]{64}$/; const MAX = 1_000_000_000;
const HOLD = ['fire_acoustic_thermal_not_run', 'code_hardware_schedule_not_run', 'native_ifc_drawing_not_run', 'field_measurement_not_run', 'independent_step_reimport_not_run'] as const;
const fail = (code: Extract<ArchitectureOpeningExactGeometryResult, { ok: false }>['code'], ...details: string[]): ArchitectureOpeningExactGeometryResult => ({ ok: false, code, details });
const sha256 = (value: string): string => createHash('sha256').update(value, 'utf8').digest('hex');
const canonical = (value: unknown): string => { if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if (value && typeof value === 'object') return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(',')}}`; return JSON.stringify(value); };
const finite = (value: number): boolean => typeof value === 'number' && Number.isFinite(value) && Math.abs(value) <= MAX;
const positive = (value: number): boolean => finite(value) && value > 0;
const hash = (value: string): boolean => typeof value === 'string' && HASH.test(value);
const vec = (value: readonly number[] | undefined, n: number): boolean => !!value && Array.isArray(value) && value.length === n && value.every(finite);

interface OpeningGeometry { wallStart: V2; wallEnd: V2; tangent: V2; normal: V2; wallLengthMm: number; z0: number; openingStart: number; openingEnd: number; openingZ: number }
function geometry(request: ArchitectureOpeningExactGeometryRequest): OpeningGeometry | undefined {
  const [sx, sy] = request.hostWall.startMm, [ex, ey] = request.hostWall.endMm; const dx = ex - sx, dy = ey - sy; const length = Math.hypot(dx, dy); if (length <= 0) return undefined;
  return { wallStart: [sx, sy], wallEnd: [ex, ey], tangent: [dx / length, dy / length], normal: [-dy / length, dx / length], wallLengthMm: length, z0: request.hostWall.z0Mm, openingStart: request.opening.offsetMm, openingEnd: request.opening.offsetMm + request.opening.widthMm, openingZ: request.hostWall.z0Mm + request.opening.sillMm };
}
function validateRequest(request: ArchitectureOpeningExactGeometryRequest): string[] {
  const issues: string[] = []; const wall = request?.hostWall; const opening = request?.opening; const frame = request?.frame; const leaf = request?.leaf;
  if (!request || request.contractVersion !== ARCHITECTURE_OPENING_EXACT_CONTRACT_VERSION) issues.push('contract_version_invalid'); if (request?.units !== 'mm') issues.push('units_must_be_mm'); if (!finite(request?.toleranceMm) || request.toleranceMm <= 0 || request.toleranceMm > 10) issues.push('tolerance_invalid');
  const binding = request?.binding; if (!binding || !ID.test(binding.projectId) || !ID.test(binding.architectureDocumentId) || !Number.isSafeInteger(binding.workspaceRevision) || binding.workspaceRevision < 0 || !hash(binding.workspaceContentHash)) issues.push('workspace_binding_invalid');
  const coordinateFrame = request?.coordinateFrame; if (!coordinateFrame || !ID.test(coordinateFrame.id) || !ID.test(coordinateFrame.parentId) || !vec(coordinateFrame.originMm, 3) || !vec(coordinateFrame.rotationDeg, 3) || coordinateFrame.originMm.some(value => value !== 0) || coordinateFrame.rotationDeg.some(value => value !== 0)) issues.push('identity_frame_required');
  if (!wall || !ID.test(wall.id) || wall.kind !== 'line' || !vec(wall.startMm, 2) || !vec(wall.endMm, 2) || !positive(wall.thicknessMm) || !positive(wall.heightMm) || !finite(wall.z0Mm)) issues.push('host_wall_invalid');
  const level = request?.hostLevel; if (!level || !ID.test(level.storeyId) || !ID.test(level.spaceId) || !finite(level.elevationMm) || !positive(level.heightMm) || !hash(level.sourceHash)) issues.push('host_level_invalid');
  if (!hash(request?.hostWallSourceHash)) issues.push('host_wall_source_hash_invalid');
  if (!opening || !ID.test(opening.id) || !ID.test(opening.hostWallId) || opening.hostWallId !== wall?.id || !finite(opening.offsetMm) || !positive(opening.widthMm) || !positive(opening.heightMm) || !finite(opening.sillMm) || opening.sillMm < 0 || !['left', 'right', 'none'].includes(opening.handing) || !['in', 'out', 'none'].includes(opening.swing) || !finite(opening.swingClearanceMm) || opening.swingClearanceMm < 0 || !hash(opening.sourceHash)) issues.push('opening_semantics_invalid');
  if (!frame || !positive(frame.jambMm) || !positive(frame.headMm) || !positive(frame.depthMm) || !hash(frame.sourceHash)) issues.push('frame_spec_invalid'); if (!leaf || !positive(leaf.thicknessMm) || !finite(leaf.insetMm) || leaf.insetMm < 0 || !hash(leaf.sourceHash)) issues.push('leaf_spec_invalid');
  if (opening?.kind === 'window' && (!request.glazing || !positive(request.glazing.thicknessMm) || !finite(request.glazing.insetMm) || request.glazing.insetMm < 0 || !hash(request.glazing.sourceHash) || request.glazing.insetMm * 2 >= opening.widthMm || request.glazing.insetMm * 2 >= opening.heightMm)) issues.push('window_glazing_invalid'); if (opening?.kind === 'door' && request.glazing) issues.push('door_glazing_not_supported');
  const g = request && geometry(request); if (!g) issues.push('host_wall_geometry_invalid');
  if (g && opening && (opening.offsetMm < 0 || opening.offsetMm + opening.widthMm > g.wallLengthMm + request.toleranceMm || opening.sillMm + opening.heightMm > wall!.heightMm + request.toleranceMm)) issues.push('opening_outside_host_wall');
  if (g && level && Math.abs(wall!.z0Mm - level.elevationMm) > request.toleranceMm) issues.push('host_level_mismatch'); if (g && level && level.elevationMm + level.heightMm < wall!.z0Mm + wall!.heightMm - request.toleranceMm) issues.push('host_wall_outside_level');
  if (opening && ((opening.kind === 'door' && opening.swing === 'none') || (opening.kind === 'window' && opening.swing !== 'none') || (opening.kind === 'window' && opening.handing !== 'none') || (opening.kind === 'door' && opening.swingClearanceMm <= 0))) issues.push('handing_swing_clearance_invalid');
  if (opening && frame && leaf && (frame.jambMm * 2 + request.toleranceMm >= opening.widthMm || frame.headMm + request.toleranceMm >= opening.heightMm || leaf.insetMm + leaf.thicknessMm >= opening.widthMm)) issues.push('frame_or_leaf_clearance_invalid');
  return issues;
}
function loop(g: OpeningGeometry, start: number, end: number, normalOffset: number, width: number): readonly { x: number; y: number }[] { const half = width / 2; const cx0 = g.wallStart[0] + g.tangent[0] * start + g.normal[0] * normalOffset, cy0 = g.wallStart[1] + g.tangent[1] * start + g.normal[1] * normalOffset, cx1 = g.wallStart[0] + g.tangent[0] * end + g.normal[0] * normalOffset, cy1 = g.wallStart[1] + g.tangent[1] * end + g.normal[1] * normalOffset; return [{ x: cx0 - g.normal[0] * half, y: cy0 - g.normal[1] * half }, { x: cx1 - g.normal[0] * half, y: cy1 - g.normal[1] * half }, { x: cx1 + g.normal[0] * half, y: cy1 + g.normal[1] * half }, { x: cx0 + g.normal[0] * half, y: cy0 + g.normal[1] * half }]; }
function bounds(points: readonly { x: number; y: number }[], z: number, h: number): { min: V3; max: V3 } { const xs = points.map(p => p.x), ys = points.map(p => p.y); return { min: [Math.min(...xs), Math.min(...ys), z], max: [Math.max(...xs), Math.max(...ys), z + h] }; }
async function receipt(adapter: ArchitectureExactKernelAdapter, kind: OpeningExactShapeReceipt['kind'], elementId: string, sourceHash: string, built: { ok: boolean; shape?: import('@/lib/occt/types').OcctShape }, expected: { min: V3; max: V3 }, toleranceMm: number): Promise<OpeningExactShapeReceipt | ArchitectureOpeningExactGeometryResult> { if (!built.ok || !built.shape) return fail('EXACT_OPENING_KERNEL_FAILED', `${elementId}:build_failed`); try { const inspection = await adapter.inspectShape(built.shape); const detailed = adapter.inspectShapeDetailed ? await adapter.inspectShapeDetailed(built.shape) : undefined; const b = detailed && detailed.bbox.min.x >= expected.min[0] - toleranceMm && detailed.bbox.min.y >= expected.min[1] - toleranceMm && detailed.bbox.min.z >= expected.min[2] - toleranceMm && detailed.bbox.max.x <= expected.max[0] + toleranceMm && detailed.bbox.max.y <= expected.max[1] + toleranceMm && detailed.bbox.max.z <= expected.max[2] + toleranceMm; if (!inspection.valid || inspection.solidCount !== 1 || !detailed?.valid || detailed.solidCount !== 1 || detailed.maxTolerance === undefined || detailed.maxTolerance > toleranceMm || !b || detailed.absoluteVolume <= 0) return fail('EXACT_OPENING_VERIFICATION_FAILED', `${elementId}:solid_bounds_or_tolerance_invalid`); const stepText = await adapter.exportSTEP(built.shape); if (!stepText.includes('ISO-10303-21;') || !stepText.includes('MANIFOLD_SOLID_BREP') || !stepText.includes('END-ISO-10303-21;')) return fail('EXACT_OPENING_VERIFICATION_FAILED', `${elementId}:step_not_manifold_solid`); const stepSha256 = sha256(stepText); return { kind, elementId, sourceHash, stepText, stepBytes: Buffer.byteLength(stepText, 'utf8'), stepSha256, shapeHash: stepSha256, absoluteVolume: detailed.absoluteVolume, bbox: detailed.bbox, manifoldSolid: true, maxToleranceMm: detailed.maxTolerance }; } catch (error) { return fail('EXACT_OPENING_KERNEL_FAILED', `${elementId}:${error instanceof Error ? error.message : 'inspection_or_step_failed'}`); } finally { try { adapter.release(built.shape); } catch { /* best effort */ } } }
function strip(shape: OpeningExactShapeReceipt): Omit<OpeningExactShapeReceipt, 'stepText'> { const { stepText: _stepText, ...rest } = shape; return rest; }
function contentHash(receiptValue: Omit<ArchitectureOpeningExactGeometryReceipt, 'contentHash'>): string { return sha256(canonical({ ...receiptValue, hostWall: strip(receiptValue.hostWall), frameJambs: receiptValue.frameJambs.map(strip), frameHead: strip(receiptValue.frameHead), leaf: strip(receiptValue.leaf), glazing: receiptValue.glazing ? strip(receiptValue.glazing) : undefined })); }
function shapeConsistent(shape: OpeningExactShapeReceipt): boolean { if (!shape || typeof shape.stepText !== 'string' || !shape.bbox?.min || !shape.bbox.max) return false; return ID.test(shape.elementId) && hash(shape.sourceHash) && hash(shape.stepSha256) && shape.shapeHash === shape.stepSha256 && shape.stepBytes === Buffer.byteLength(shape.stepText, 'utf8') && shape.stepText.includes('ISO-10303-21;') && shape.stepText.includes('MANIFOLD_SOLID_BREP') && shape.stepText.includes('END-ISO-10303-21;') && shape.manifoldSolid === true && Number.isFinite(shape.absoluteVolume) && shape.absoluteVolume > 0 && Number.isFinite(shape.maxToleranceMm) && shape.maxToleranceMm >= 0 && [shape.bbox.min.x, shape.bbox.min.y, shape.bbox.min.z, shape.bbox.max.x, shape.bbox.max.y, shape.bbox.max.z].every(finite) && sha256(shape.stepText) === shape.stepSha256; }
function bboxMatches(actual: OpeningExactShapeReceipt, expected: { min: V3; max: V3 }, tolerance: number): boolean { return [actual.bbox.min.x - expected.min[0], actual.bbox.min.y - expected.min[1], actual.bbox.min.z - expected.min[2], actual.bbox.max.x - expected.max[0], actual.bbox.max.y - expected.max[1], actual.bbox.max.z - expected.max[2]].every(value => Math.abs(value) <= tolerance); }
function volumeMatches(actual: number, expected: number, toleranceMm: number): boolean { return Number.isFinite(actual) && Math.abs(actual - expected) <= Math.max(1e-3, Math.abs(expected) * 1e-8, toleranceMm * Math.max(1, Math.cbrt(Math.abs(expected)))); }
function expectedOpeningBounds(request: ArchitectureOpeningExactGeometryRequest): { host: { min: V3; max: V3 }; jambLeft: { min: V3; max: V3 }; jambRight: { min: V3; max: V3 }; head: { min: V3; max: V3 }; leaf: { min: V3; max: V3 }; glazing?: { min: V3; max: V3 } } | undefined { const g = geometry(request); if (!g) return undefined; const wallLoop = loop(g, 0, g.wallLengthMm, 0, request.hostWall.thicknessMm); const leftLoop = loop(g, request.opening.offsetMm, request.opening.offsetMm + request.frame.jambMm, 0, request.frame.depthMm); const rightStart = request.opening.offsetMm + request.opening.widthMm - request.frame.jambMm; const rightLoop = loop(g, rightStart, rightStart + request.frame.jambMm, 0, request.frame.depthMm); const headLoop = loop(g, request.opening.offsetMm, request.opening.offsetMm + request.opening.widthMm, 0, request.frame.depthMm); const leafStart = request.opening.offsetMm + request.frame.jambMm + request.leaf.insetMm; const leafWidth = request.opening.widthMm - request.frame.jambMm * 2 - request.leaf.insetMm * 2; const leafLoop = loop(g, leafStart, leafStart + leafWidth, -request.hostWall.thicknessMm / 2, request.leaf.thicknessMm); const result = { host: bounds(wallLoop, request.hostWall.z0Mm, request.hostWall.heightMm), jambLeft: bounds(leftLoop, g.openingZ, request.opening.heightMm), jambRight: bounds(rightLoop, g.openingZ, request.opening.heightMm), head: bounds(headLoop, g.openingZ + request.opening.heightMm - request.frame.headMm, request.frame.headMm), leaf: bounds(leafLoop, g.openingZ, request.opening.heightMm - request.frame.headMm) }; if (!request.glazing) return result; const glazingLoop = loop(g, request.opening.offsetMm + request.glazing.insetMm, request.opening.offsetMm + request.opening.widthMm - request.glazing.insetMm, 0, request.glazing.thicknessMm); return { ...result, glazing: bounds(glazingLoop, g.openingZ + request.glazing.insetMm, request.opening.heightMm - request.glazing.insetMm * 2) }; }
function expectedOpeningVolumes(request: ArchitectureOpeningExactGeometryRequest): { before: number; after: number; jamb: number; head: number; leaf: number; glazing?: number } { const wallArea = Math.hypot(request.hostWall.endMm[0] - request.hostWall.startMm[0], request.hostWall.endMm[1] - request.hostWall.startMm[1]) * request.hostWall.thicknessMm; const before = wallArea * request.hostWall.heightMm; const cut = request.opening.widthMm * request.hostWall.thicknessMm * request.opening.heightMm; const jamb = request.frame.jambMm * request.frame.depthMm * request.opening.heightMm; const head = request.opening.widthMm * request.frame.depthMm * request.frame.headMm; const leafWidth = request.opening.widthMm - request.frame.jambMm * 2 - request.leaf.insetMm * 2; const leaf = leafWidth * request.leaf.thicknessMm * (request.opening.heightMm - request.frame.headMm); const glazing = request.glazing ? (request.opening.widthMm - request.glazing.insetMm * 2) * request.glazing.thicknessMm * (request.opening.heightMm - request.glazing.insetMm * 2) : undefined; return { before, after: before - cut, jamb, head, leaf, glazing }; }

export function validateArchitectureOpeningExactGeometryReceipt(receiptValue: ArchitectureOpeningExactGeometryReceipt, request: ArchitectureOpeningExactGeometryRequest): boolean {
  if (!receiptValue || !request || receiptValue.contractVersion !== ARCHITECTURE_OPENING_EXACT_CONTRACT_VERSION || receiptValue.units !== 'mm' || receiptValue.releaseReady !== false || canonical(receiptValue.hold) !== canonical(HOLD) || canonical(receiptValue.binding) !== canonical(request.binding) || canonical(receiptValue.coordinateFrame) !== canonical(request.coordinateFrame) || receiptValue.hostWallId !== request.hostWall.id || receiptValue.storeyId !== request.hostLevel.storeyId || receiptValue.spaceId !== request.hostLevel.spaceId || receiptValue.openingId !== request.opening.id || receiptValue.openingKind !== request.opening.kind || receiptValue.offsetMm !== request.opening.offsetMm || receiptValue.widthMm !== request.opening.widthMm || receiptValue.heightMm !== request.opening.heightMm || receiptValue.sillMm !== request.opening.sillMm || receiptValue.handing !== request.opening.handing || receiptValue.swing !== request.opening.swing || receiptValue.swingClearanceMm !== request.opening.swingClearanceMm || receiptValue.jambMm !== request.frame.jambMm || receiptValue.headMm !== request.frame.headMm || receiptValue.frameDepthMm !== request.frame.depthMm || receiptValue.leafThicknessMm !== request.leaf.thicknessMm || receiptValue.hostWallSourceHash !== request.hostWallSourceHash || receiptValue.levelSourceHash !== request.hostLevel.sourceHash || receiptValue.openingSourceHash !== request.opening.sourceHash || receiptValue.frameSourceHash !== request.frame.sourceHash || receiptValue.leafSourceHash !== request.leaf.sourceHash || (request.glazing ? receiptValue.glazingSourceHash !== request.glazing.sourceHash : receiptValue.glazing) || !hash(receiptValue.contentHash)) return false;
if (receiptValue.hostWall.kind !== 'host_wall_final' || receiptValue.hostWall.elementId !== request.hostWall.id || receiptValue.hostWall.sourceHash !== request.hostWallSourceHash || receiptValue.frameJambs.some((shape, index) => shape.kind !== 'frame_jamb' || shape.elementId !== `${request.opening.id}:frame:jamb:${index === 0 ? 'left' : 'right'}` || shape.sourceHash !== request.frame.sourceHash) || receiptValue.frameHead.kind !== 'frame_head' || receiptValue.frameHead.elementId !== `${request.opening.id}:frame:head` || receiptValue.frameHead.sourceHash !== request.frame.sourceHash || receiptValue.leaf.kind !== 'leaf' || receiptValue.leaf.elementId !== `${request.opening.id}:leaf` || receiptValue.leaf.sourceHash !== request.leaf.sourceHash || (receiptValue.glazing && (receiptValue.glazing.kind !== 'glazing' || receiptValue.glazing.elementId !== `${request.opening.id}:glazing` || receiptValue.glazing.sourceHash !== request.glazing?.sourceHash))) return false; const all = [receiptValue.hostWall, ...receiptValue.frameJambs, receiptValue.frameHead, receiptValue.leaf, ...(receiptValue.glazing ? [receiptValue.glazing] : [])]; if (!all.every(shapeConsistent) || receiptValue.frameJambs.length !== 2) return false; if (request.glazing ? !receiptValue.glazing || receiptValue.glazingThicknessMm !== request.glazing.thicknessMm : receiptValue.glazing || receiptValue.glazingThicknessMm !== undefined) return false; const expected = expectedOpeningBounds(request); if (!expected || !bboxMatches(receiptValue.hostWall, expected.host, request.toleranceMm) || !bboxMatches(receiptValue.frameJambs[0]!, expected.jambLeft, request.toleranceMm) || !bboxMatches(receiptValue.frameJambs[1]!, expected.jambRight, request.toleranceMm) || !bboxMatches(receiptValue.frameHead, expected.head, request.toleranceMm) || !bboxMatches(receiptValue.leaf, expected.leaf, request.toleranceMm) || (receiptValue.glazing && (!expected.glazing || !bboxMatches(receiptValue.glazing, expected.glazing, request.toleranceMm)))) return false; const volumes = expectedOpeningVolumes(request); if (!volumeMatches(receiptValue.hostVolumeBeforeCut, volumes.before, request.toleranceMm) || !volumeMatches(receiptValue.hostVolumeAfterCut, volumes.after, request.toleranceMm)) return false; if (!volumeMatches(receiptValue.frameJambs[0]!.absoluteVolume, volumes.jamb, request.toleranceMm) || !volumeMatches(receiptValue.frameJambs[1]!.absoluteVolume, volumes.jamb, request.toleranceMm) || !volumeMatches(receiptValue.frameHead.absoluteVolume, volumes.head, request.toleranceMm) || !volumeMatches(receiptValue.leaf.absoluteVolume, volumes.leaf, request.toleranceMm) || (receiptValue.glazing && (volumes.glazing === undefined || !volumeMatches(receiptValue.glazing.absoluteVolume, volumes.glazing, request.toleranceMm)))) return false;
  if (receiptValue.hostVolumeAfterCut >= receiptValue.hostVolumeBeforeCut || receiptValue.hostVolumeBeforeCut <= 0) return false; const { contentHash: _contentHash, ...unsigned } = receiptValue; return contentHash(unsigned) === receiptValue.contentHash;
}

export async function generateArchitectureOpeningExactGeometry(request: ArchitectureOpeningExactGeometryRequest, adapter: ArchitectureExactKernelAdapter): Promise<ArchitectureOpeningExactGeometryResult> {
  const issues = validateRequest(request); if (issues.length) return fail('EXACT_OPENING_INVALID_REQUEST', ...issues); const g = geometry(request)!; const wall = request.hostWall; const wallLoop = loop(g, 0, g.wallLengthMm, 0, wall.thicknessMm); const base = await adapter.buildPrismAt(wallLoop, wall.z0Mm, wall.heightMm); if (!base.ok || !base.shape) return fail('EXACT_OPENING_KERNEL_FAILED', 'host_wall_build_failed');
  let before = 0; try { const detailed = adapter.inspectShapeDetailed ? await adapter.inspectShapeDetailed(base.shape) : undefined; before = detailed?.absoluteVolume ?? 0; } finally { /* base remains live for the boolean */ }
  const cutterLoop = loop(g, g.openingStart, g.openingEnd, 0, wall.thicknessMm + request.toleranceMm * 2); const cutter = await adapter.buildPrismAt(cutterLoop, g.openingZ, request.opening.heightMm); if (!cutter.ok || !cutter.shape) { try { adapter.release(base.shape); } catch { /* best effort */ } return fail('EXACT_OPENING_KERNEL_FAILED', 'opening_cutter_build_failed'); }
  let cut; try { cut = await adapter.subtract(base.shape, cutter.shape, { baseId: wall.id, toolId: request.opening.id, opId: `opening:${request.opening.id}` }); } finally { try { adapter.release(base.shape); } catch { /* best effort */ } try { adapter.release(cutter.shape); } catch { /* best effort */ } }
  const wallShape = await receipt(adapter, 'host_wall_final', wall.id, request.hostWallSourceHash, cut, bounds(wallLoop, wall.z0Mm, wall.heightMm), request.toleranceMm); if (!('kind' in wallShape)) return wallShape; const after = wallShape.absoluteVolume; if (before <= 0 || after >= before) return fail('EXACT_OPENING_VERIFICATION_FAILED', 'host_boolean_volume_not_reduced');
  const frameOffset = request.opening.offsetMm; const jambHeight = request.opening.heightMm; const jambLeft = await receipt(adapter, 'frame_jamb', `${request.opening.id}:frame:jamb:left`, request.frame.sourceHash, await adapter.buildPrismAt(loop(g, frameOffset, frameOffset + request.frame.jambMm, 0, request.frame.depthMm), g.openingZ, jambHeight), bounds(loop(g, frameOffset, frameOffset + request.frame.jambMm, 0, request.frame.depthMm), g.openingZ, jambHeight), request.toleranceMm); if (!('kind' in jambLeft)) return jambLeft;
  const rightStart = request.opening.offsetMm + request.opening.widthMm - request.frame.jambMm; const jambRight = await receipt(adapter, 'frame_jamb', `${request.opening.id}:frame:jamb:right`, request.frame.sourceHash, await adapter.buildPrismAt(loop(g, rightStart, rightStart + request.frame.jambMm, 0, request.frame.depthMm), g.openingZ, jambHeight), bounds(loop(g, rightStart, rightStart + request.frame.jambMm, 0, request.frame.depthMm), g.openingZ, jambHeight), request.toleranceMm); if (!('kind' in jambRight)) return jambRight;
  const headLoop = loop(g, request.opening.offsetMm, request.opening.offsetMm + request.opening.widthMm, 0, request.frame.depthMm); const headZ = g.openingZ + request.opening.heightMm - request.frame.headMm; const head = await receipt(adapter, 'frame_head', `${request.opening.id}:frame:head`, request.frame.sourceHash, await adapter.buildPrismAt(headLoop, headZ, request.frame.headMm), bounds(headLoop, headZ, request.frame.headMm), request.toleranceMm); if (!('kind' in head)) return head;
  const leafStart = request.opening.offsetMm + request.frame.jambMm + request.leaf.insetMm; const leafWidth = request.opening.widthMm - request.frame.jambMm * 2 - request.leaf.insetMm * 2; const leafLoop = loop(g, leafStart, leafStart + leafWidth, -wall.thicknessMm / 2, request.leaf.thicknessMm); const leaf = await receipt(adapter, 'leaf', `${request.opening.id}:leaf`, request.leaf.sourceHash, await adapter.buildPrismAt(leafLoop, g.openingZ, request.opening.heightMm - request.frame.headMm), bounds(leafLoop, g.openingZ, request.opening.heightMm - request.frame.headMm), request.toleranceMm); if (!('kind' in leaf)) return leaf;
  let glazing: OpeningExactShapeReceipt | undefined; if (request.glazing) { const inset = request.glazing.insetMm; const glazingLoop = loop(g, request.opening.offsetMm + inset, request.opening.offsetMm + request.opening.widthMm - inset, 0, request.glazing.thicknessMm); const glass = await receipt(adapter, 'glazing', `${request.opening.id}:glazing`, request.glazing.sourceHash, await adapter.buildPrismAt(glazingLoop, g.openingZ + inset, request.opening.heightMm - inset * 2), bounds(glazingLoop, g.openingZ + inset, request.opening.heightMm - inset * 2), request.toleranceMm); if (!('kind' in glass)) return glass; glazing = glass; }
  const unsigned: Omit<ArchitectureOpeningExactGeometryReceipt, 'contentHash'> = { contractVersion: ARCHITECTURE_OPENING_EXACT_CONTRACT_VERSION, units: 'mm', binding: request.binding, coordinateFrame: request.coordinateFrame, hostWallId: wall.id, storeyId: request.hostLevel.storeyId, spaceId: request.hostLevel.spaceId, openingId: request.opening.id, openingKind: request.opening.kind, offsetMm: request.opening.offsetMm, widthMm: request.opening.widthMm, heightMm: request.opening.heightMm, sillMm: request.opening.sillMm, handing: request.opening.handing, swing: request.opening.swing, swingClearanceMm: request.opening.swingClearanceMm, jambMm: request.frame.jambMm, headMm: request.frame.headMm, frameDepthMm: request.frame.depthMm, leafThicknessMm: request.leaf.thicknessMm, glazingThicknessMm: request.glazing?.thicknessMm, hostVolumeBeforeCut: before, hostVolumeAfterCut: after, hostWallSourceHash: request.hostWallSourceHash, levelSourceHash: request.hostLevel.sourceHash, openingSourceHash: request.opening.sourceHash, frameSourceHash: request.frame.sourceHash, leafSourceHash: request.leaf.sourceHash, glazingSourceHash: request.glazing?.sourceHash, hostWall: wallShape, frameJambs: [jambLeft, jambRight], frameHead: head, leaf, glazing, releaseReady: false, hold: HOLD };
  return { ok: true, receipt: { ...unsigned, contentHash: contentHash(unsigned) } };
}
