import { createHash } from 'node:crypto';

export const CABLE_TRAY_CONDUIT_RELEASE_SCHEMA = 'nexyfab.cable-tray-conduit-release.v1' as const;
export const CABLE_TRAY_CONDUIT_EXCHANGE_SCHEMA = 'nexyfab.cable-tray-conduit-exchange.v1' as const;
const PARSER_ID = 'nexyfab.cable-tray-conduit-independent-parser.v1' as const;
const SHA256 = /^[a-f0-9]{64}$/;
const EPSILON = 1e-8;
export interface CableRouteSourceBindingV1 { workspaceId: string; modelId: string; modelPath: string; modelSha256: string; contentHash: string; rawArtifactSha256: string; revisionSha256: string; revision: number; }
export interface CablePointMmV1 { xMm: number; yMm: number; zMm: number; }
export type CableRouteKind = 'tray' | 'conduit';
export type VoltageClass = 'low' | 'medium' | 'high';
export interface CableRouteV1 { id: string; kind: CableRouteKind; voltageClass: VoltageClass; segmentIds: readonly string[]; fittingIds: readonly string[]; portIds: readonly string[]; maxSupportSpacingMm: number; fillRatioLimit: number; minimumClearanceMm: number; }
export interface CablePortV1 { id: string; ownerType: 'segment' | 'fitting'; ownerId: string; positionMm: CablePointMmV1; direction: CablePointMmV1; connectedPortIds: readonly string[]; }
export interface CableRouteSegmentV1 { id: string; routeId: string; startPortId: string; endPortId: string; kind: CableRouteKind; widthMm?: number; depthMm?: number; diameterMm?: number; centerlineMm: readonly CablePointMmV1[]; lengthMm: number; bendRadiusMm: number; cableIds: readonly string[]; }
export type CableFittingType = 'elbow' | 'tee' | 'reducer';
export interface CableRouteFittingV1 { id: string; routeId: string; type: CableFittingType; portIds: readonly string[]; bendRadiusMm: number; }
export interface CableV1 { id: string; routeId: string; voltageClass: VoltageClass; crossSectionAreaMm2: number; minimumBendRadiusMm: number; }
export interface CableSupportV1 { id: string; segmentId: string; positionAlongMm: number; spacingMm: number; supportType: string; }
export interface CableClearanceZoneV1 { id: string; ownerId: string; originMm: CablePointMmV1; widthMm: number; depthMm: number; heightMm: number; }
export interface CableRouteOutputV1 { format: 'nexyfab-exchange-json'; targetFormat: 'ifc-neutral' | 'step' | 'json'; revision: number; content: string; bytes: number; sha256: string; }
export interface CableRouteExchangeV1 { schema: typeof CABLE_TRAY_CONDUIT_EXCHANGE_SCHEMA; revision: number; sourceWorkspaceId: string; sourceModelId: string; sourceModelSha256: string; sourceContentHash: string; sourceRawArtifactSha256: string; routeIds: string[]; portIds: string[]; segmentIds: string[]; fittingIds: string[]; cableIds: string[]; supportIds: string[]; }
export interface CableTrayConduitReleaseInputV1 { schema: typeof CABLE_TRAY_CONDUIT_RELEASE_SCHEMA; units: 'mm-A-V'; revision: number; source: CableRouteSourceBindingV1; routes: readonly CableRouteV1[]; ports: readonly CablePortV1[]; segments: readonly CableRouteSegmentV1[]; fittings: readonly CableRouteFittingV1[]; cables: readonly CableV1[]; supports: readonly CableSupportV1[]; clearanceZones: readonly CableClearanceZoneV1[]; output: CableRouteOutputV1; }
export interface CableRouteParserReadbackV1 { parserId: typeof PARSER_ID; parserSourceSha256: string; sourceWorkspaceId: string; sourceModelId: string; sourceModelSha256: string; sourceContentHash: string; sourceRawArtifactSha256: string; sourceRevision: number; outputSha256: string; routeIds: readonly string[]; portIds: readonly string[]; segmentIds: readonly string[]; fittingIds: readonly string[]; cableIds: readonly string[]; supportIds: readonly string[]; verificationSha256: string; }
export interface CableRouteValidationResult { valid: boolean; issues: string[]; }
export interface CableRouteReleaseAssessment { schema: typeof CABLE_TRAY_CONDUIT_RELEASE_SCHEMA; releaseReady: false; status: 'HOLD'; internalParserVerified: boolean; independentAttestationVerified: boolean; /** @deprecated Use internalParserVerified. */ parserVerified: boolean; blockers: string[]; holdBoundary: readonly string[]; }
export interface CableRouteReadbackResult { valid: boolean; issues: string[]; }
const holdBoundary = ['native_ifc_step_parser_not_verified', 'load_and_short_circuit_analysis_not_run', 'protection_coordination_not_run', 'electrical_code_authority_not_verified', 'native_ifc_ecad_roundtrip_not_verified', 'field_inspection_receipt_not_available'] as const;
const sha256 = (value: string): string => createHash('sha256').update(value, 'utf8').digest('hex');
const finite = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value);
const positive = (value: unknown): value is number => finite(value) && value > 0;
const nonnegative = (value: unknown): value is number => finite(value) && value >= 0;
const arrays = <T>(value: unknown): readonly T[] => Array.isArray(value) ? value as readonly T[] : [];
const equal = (a: number, b: number): boolean => Math.abs(a - b) <= Math.max(EPSILON, Math.max(Math.abs(a), Math.abs(b)) * 1e-9);
const point = (value: unknown): value is CablePointMmV1 => Boolean(value && typeof value === 'object' && finite((value as CablePointMmV1).xMm) && finite((value as CablePointMmV1).yMm) && finite((value as CablePointMmV1).zMm));
const distance = (a: CablePointMmV1, b: CablePointMmV1): number => Math.hypot(a.xMm - b.xMm, a.yMm - b.yMm, a.zMm - b.zMm);
const bendRadius = (a: CablePointMmV1, b: CablePointMmV1, c: CablePointMmV1): number => { const ab = distance(a, b); const bc = distance(b, c); const ac = distance(a, c); const cross = Math.hypot((b.yMm - a.yMm) * (c.zMm - a.zMm) - (b.zMm - a.zMm) * (c.yMm - a.yMm), (b.zMm - a.zMm) * (c.xMm - a.xMm) - (b.xMm - a.xMm) * (c.zMm - a.zMm), (b.xMm - a.xMm) * (c.yMm - a.yMm) - (b.yMm - a.yMm) * (c.xMm - a.xMm)); return cross <= EPSILON ? Infinity : ab * bc * ac / (2 * cross); };
const routeBounds = (segment: CableRouteSegmentV1): { originMm: CablePointMmV1; widthMm: number; depthMm: number; heightMm: number } => {
  const r = segment.kind === 'tray' ? Math.max(segment.widthMm ?? 0, segment.depthMm ?? 0) / 2 : (segment.diameterMm ?? 0) / 2; const radius = { x: r, y: r, z: r };
  const points = segment.centerlineMm; const minX = Math.min(...points.map(p => p.xMm)) - radius.x; const minY = Math.min(...points.map(p => p.yMm)) - radius.y; const minZ = Math.min(...points.map(p => p.zMm)) - radius.z; const maxX = Math.max(...points.map(p => p.xMm)) + radius.x; const maxY = Math.max(...points.map(p => p.yMm)) + radius.y; const maxZ = Math.max(...points.map(p => p.zMm)) + radius.z;
  return { originMm: { xMm: minX, yMm: minY, zMm: minZ }, widthMm: maxX - minX, depthMm: maxY - minY, heightMm: maxZ - minZ };
};
const ids = (values: readonly { id?: unknown }[]): Set<string> => new Set(values.map(value => value?.id).filter((id): id is string => typeof id === 'string'));
const exactKeys = (value: unknown, keys: readonly string[]): value is Record<string, unknown> => Boolean(value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === keys.length && Object.keys(value).every(key => keys.includes(key)));
const stableIdArray = (value: unknown): value is string[] => Array.isArray(value) && value.every(id => typeof id === 'string' && id.trim() === id && id.length > 0) && new Set(value).size === value.length;
function register(values: readonly { id?: unknown }[], label: string, issues: string[], all: Set<string>): void { for (const value of values) { const id = value?.id; if (typeof id !== 'string' || !id.trim() || all.has(id)) issues.push(`${label}_id_invalid:${String(id)}`); else all.add(id); } }
function crossSection(item: { kind?: CableRouteKind; widthMm?: number; depthMm?: number; diameterMm?: number }): number { return item.kind === 'tray' && positive(item.widthMm) && positive(item.depthMm) ? item.widthMm * item.depthMm : item.kind === 'conduit' && positive(item.diameterMm) ? Math.PI * (item.diameterMm / 2) ** 2 : 0; }
function overlap(a: CableClearanceZoneV1, b: { originMm: CablePointMmV1; widthMm: number; depthMm: number; heightMm: number }): boolean { return a.originMm.xMm < b.originMm.xMm + b.widthMm - EPSILON && a.originMm.xMm + a.widthMm > b.originMm.xMm + EPSILON && a.originMm.yMm < b.originMm.yMm + b.depthMm - EPSILON && a.originMm.yMm + a.depthMm > b.originMm.yMm + EPSILON && a.originMm.zMm < b.originMm.zMm + b.heightMm - EPSILON && a.originMm.zMm + a.heightMm > b.originMm.zMm + EPSILON; }
export function validateCableTrayConduitRelease(input: CableTrayConduitReleaseInputV1 | null | undefined): CableRouteValidationResult {
  const issues: string[] = []; if (!input || typeof input !== 'object') return { valid: false, issues: ['input_missing'] }; if (input.schema !== CABLE_TRAY_CONDUIT_RELEASE_SCHEMA) issues.push('schema_invalid'); if (input.units !== 'mm-A-V') issues.push('canonical_units_required'); if (!Number.isSafeInteger(input.revision) || input.revision < 0) issues.push('revision_invalid');
  const source = input.source; if (!source || typeof source !== 'object') issues.push('source_binding_missing'); else { if (typeof source.workspaceId !== 'string' || !source.workspaceId.trim() || typeof source.modelId !== 'string' || !source.modelId.trim()) issues.push('source_identity_invalid'); if (typeof source.modelPath !== 'string' || !source.modelPath.trim() || source.modelPath.replaceAll('\\', '/').split('/').includes('..') || source.modelPath.startsWith('/') || /^[A-Za-z]:[\\/]/.test(source.modelPath)) issues.push('source_model_path_invalid'); if (![source.modelSha256, source.contentHash, source.rawArtifactSha256, source.revisionSha256].every(value => typeof value === 'string' && SHA256.test(value))) issues.push('source_hash_invalid'); if (!Number.isSafeInteger(source.revision) || source.revision !== input.revision) issues.push('stale_source_revision'); }
  const routes = arrays<CableRouteV1>(input.routes); const ports = arrays<CablePortV1>(input.ports); const segments = arrays<CableRouteSegmentV1>(input.segments); const fittings = arrays<CableRouteFittingV1>(input.fittings); const cables = arrays<CableV1>(input.cables); const supports = arrays<CableSupportV1>(input.supports); const zones = arrays<CableClearanceZoneV1>(input.clearanceZones); for (const [value, label] of [[input.routes, 'routes'], [input.ports, 'ports'], [input.segments, 'segments'], [input.fittings, 'fittings'], [input.cables, 'cables'], [input.supports, 'supports'], [input.clearanceZones, 'clearance_zones']] as const) if (!Array.isArray(value)) issues.push(`${label}_array_required`);
  const all = new Set<string>(); register(routes, 'route', issues, all); register(ports, 'port', issues, all); register(segments, 'segment', issues, all); register(fittings, 'fitting', issues, all); register(cables, 'cable', issues, all); register(supports, 'support', issues, all); register(zones, 'clearance_zone', issues, all);
  const routeIds = ids(routes); const portIds = ids(ports); const segmentIds = ids(segments); const fittingIds = ids(fittings); const cableIds = ids(cables); const routeMap = new Map(routes.map(item => [item?.id, item])); const portMap = new Map(ports.map(item => [item?.id, item])); const segmentMap = new Map(segments.map(item => [item?.id, item])); const cableMap = new Map(cables.map(item => [item?.id, item]));
  for (const route of routes) if (!route || typeof route !== 'object' || !['tray', 'conduit'].includes(route.kind) || !['low', 'medium', 'high'].includes(route.voltageClass) || !positive(route.maxSupportSpacingMm) || !positive(route.fillRatioLimit) || route.fillRatioLimit > 1 || !nonnegative(route.minimumClearanceMm) || arrays<string>(route.segmentIds).length === 0 || arrays<string>(route.segmentIds).some(id => !segmentIds.has(id)) || arrays<string>(route.fittingIds).some(id => !fittingIds.has(id)) || arrays<string>(route.portIds).some(id => !portIds.has(id))) issues.push(`route_invalid:${route?.id}`);
  for (const port of ports) { const ownerValid = port?.ownerType === 'segment' ? segmentIds.has(port.ownerId) : port?.ownerType === 'fitting' && fittingIds.has(port.ownerId); if (!port || typeof port !== 'object' || !ownerValid || !point(port.positionMm) || !point(port.direction) || distance({ xMm: 0, yMm: 0, zMm: 0 }, port.direction) <= EPSILON || arrays<string>(port.connectedPortIds).some(id => !portIds.has(id))) issues.push(`port_invalid:${port?.id}`); for (const otherId of arrays<string>(port?.connectedPortIds)) { if (!arrays<string>(portMap.get(otherId)?.connectedPortIds).includes(port?.id)) issues.push(`port_bidirectional_ownership_invalid:${port?.id}`); const other = portMap.get(otherId); if (other && point(port.positionMm) && point(other.positionMm) && distance(port.positionMm, other.positionMm) > EPSILON) issues.push(`port_spatial_continuity_invalid:${port?.id}`); } }
  for (const cable of cables) if (!cable || typeof cable !== 'object' || !routeIds.has(cable.routeId) || !['low', 'medium', 'high'].includes(cable.voltageClass) || !positive(cable.crossSectionAreaMm2) || !positive(cable.minimumBendRadiusMm)) issues.push(`cable_invalid:${cable?.id}`);
  for (const segment of segments) { const route = routeMap.get(segment?.routeId); const start = portMap.get(segment?.startPortId); const end = portMap.get(segment?.endPortId); const section = crossSection(segment ?? {}); const startOwned = start && ((start.ownerType === 'segment' && start.ownerId === segment?.id) || (start.ownerType === 'fitting' && arrays<string>(route?.fittingIds).includes(start.ownerId))); const endOwned = end && ((end.ownerType === 'segment' && end.ownerId === segment?.id) || (end.ownerType === 'fitting' && arrays<string>(route?.fittingIds).includes(end.ownerId))); if (!segment || !route || !start || !end || !startOwned || !endOwned || segment.startPortId === segment.endPortId || section <= 0 || !Array.isArray(segment.centerlineMm) || segment.centerlineMm.length < 2 || segment.centerlineMm.some((value: unknown) => !point(value)) || !positive(segment.lengthMm) || !positive(segment.bendRadiusMm) || arrays<string>(segment.cableIds).some(id => !cableIds.has(id))) { issues.push(`segment_invalid_or_dangling:${segment?.id}`); continue; } let length = 0; for (let index = 1; index < segment.centerlineMm.length; index += 1) { const part = distance(segment.centerlineMm[index - 1]!, segment.centerlineMm[index]!); if (part <= EPSILON) issues.push(`segment_zero_length:${segment.id}`); length += part; } if (!equal(length, segment.lengthMm)) issues.push(`segment_length_mismatch:${segment.id}`); if (!equal(distance(start.positionMm, segment.centerlineMm[0]!), 0) || !equal(distance(end.positionMm, segment.centerlineMm[segment.centerlineMm.length - 1]!), 0)) issues.push(`segment_port_geometry_mismatch:${segment.id}`); const travel = { xMm: end.positionMm.xMm - start.positionMm.xMm, yMm: end.positionMm.yMm - start.positionMm.yMm, zMm: end.positionMm.zMm - start.positionMm.zMm }; if (travel.xMm * start.direction.xMm + travel.yMm * start.direction.yMm + travel.zMm * start.direction.zMm <= 0) issues.push(`segment_direction_invalid:${segment.id}`); const fill = arrays<string>(segment.cableIds).reduce((sum, id) => sum + (cableMap.get(id)?.crossSectionAreaMm2 ?? 0), 0) / section; if (fill > route.fillRatioLimit) issues.push(`cable_fill_exceeded:${segment.id}`); for (const cableId of arrays<string>(segment.cableIds)) { const cable = cableMap.get(cableId); if (cable && cable.routeId === route.id && cable.voltageClass !== route.voltageClass) issues.push(`voltage_class_segregation_invalid:${segment.id}`); if (cable && cable.minimumBendRadiusMm > segment.bendRadiusMm) issues.push(`cable_bend_radius_invalid:${segment.id}`); } }
  for (const fitting of fittings) if (!fitting || typeof fitting !== 'object' || !routeIds.has(fitting.routeId) || !['elbow', 'tee', 'reducer'].includes(fitting.type) || !positive(fitting.bendRadiusMm) || arrays<string>(fitting.portIds).length < 2 || arrays<string>(fitting.portIds).some(id => !portIds.has(id) || portMap.get(id)?.ownerType !== 'fitting' || portMap.get(id)?.ownerId !== fitting.id)) issues.push(`fitting_invalid_or_dangling:${fitting?.id}`);
  for (const segment of segments) { const route = routeMap.get(segment?.routeId); if (!route || segment.kind !== route.kind || !route.segmentIds.includes(segment.id) || !route.portIds.includes(segment.startPortId) || !route.portIds.includes(segment.endPortId) || arrays<string>(segment.cableIds).length === 0 || arrays<string>(segment.cableIds).some(id => !cableMap.has(id) || cableMap.get(id)?.routeId !== route.id)) issues.push(`segment_ownership_invalid:${segment?.id}`); }
  for (const fitting of fittings) { const route = routeMap.get(fitting?.routeId); if (!route || !route.fittingIds.includes(fitting.id) || arrays<string>(fitting.portIds).some(id => !route.portIds.includes(id))) issues.push(`fitting_ownership_invalid:${fitting?.id}`); }
  for (const segment of segments) { const start = portMap.get(segment?.startPortId); const end = portMap.get(segment?.endPortId); const points = segment?.centerlineMm; if (!start || !end || !Array.isArray(points) || points.length < 2 || !point(points[0]) || !point(points[1]) || !point(points[points.length - 2]) || !point(points[points.length - 1])) continue; const first = { xMm: points[1]!.xMm - points[0]!.xMm, yMm: points[1]!.yMm - points[0]!.yMm, zMm: points[1]!.zMm - points[0]!.zMm }; const last = { xMm: points[points.length - 1]!.xMm - points[points.length - 2]!.xMm, yMm: points[points.length - 1]!.yMm - points[points.length - 2]!.yMm, zMm: points[points.length - 1]!.zMm - points[points.length - 2]!.zMm }; if (first.xMm * start.direction.xMm + first.yMm * start.direction.yMm + first.zMm * start.direction.zMm <= EPSILON || last.xMm * end.direction.xMm + last.yMm * end.direction.yMm + last.zMm * end.direction.zMm <= EPSILON) issues.push(`port_direction_tangent_invalid:${segment.id}`); }
  for (const support of supports) { const segment = segmentMap.get(support?.segmentId); const route = segment ? routeMap.get(segment.routeId) : undefined; if (!segment || !route || !finite(support.positionAlongMm) || support.positionAlongMm < 0 || support.positionAlongMm > segment.lengthMm || !positive(support.spacingMm) || typeof support.supportType !== 'string' || !support.supportType.trim() || support.spacingMm > route.maxSupportSpacingMm) issues.push(`support_spacing_invalid:${support?.id}`); }
  for (const segment of segments) { const route = routeMap.get(segment?.routeId); if (!route) continue; const positions = supports.filter(support => support?.segmentId === segment.id && finite(support.positionAlongMm)).map(support => support.positionAlongMm).sort((a, b) => a - b); if (positions.length === 0) issues.push(`support_missing:${segment.id}`); else { if (positions[0]! > route.maxSupportSpacingMm + EPSILON) issues.push(`support_endpoint_gap_exceeded:${segment.id}:start`); if (segment.lengthMm - positions[positions.length - 1]! > route.maxSupportSpacingMm + EPSILON) issues.push(`support_endpoint_gap_exceeded:${segment.id}:end`); for (let index = 1; index < positions.length; index += 1) if (positions[index]! - positions[index - 1]! > route.maxSupportSpacingMm + EPSILON) issues.push(`support_gap_exceeded:${segment.id}`); } }
  for (const zone of zones) if (!zone || typeof zone !== 'object' || !all.has(zone.ownerId) || !point(zone.originMm) || !positive(zone.widthMm) || !positive(zone.depthMm) || !positive(zone.heightMm)) issues.push(`clearance_zone_invalid:${zone?.id}`);
  for (const segment of segments) { const route = routeMap.get(segment?.routeId); if (!route || !Array.isArray(segment.centerlineMm)) continue; const raw = routeBounds(segment); const bounds = { originMm: { xMm: raw.originMm.xMm - route.minimumClearanceMm, yMm: raw.originMm.yMm - route.minimumClearanceMm, zMm: raw.originMm.zMm - route.minimumClearanceMm }, widthMm: raw.widthMm + route.minimumClearanceMm * 2, depthMm: raw.depthMm + route.minimumClearanceMm * 2, heightMm: raw.heightMm + route.minimumClearanceMm * 2 }; for (const zone of zones) if (zone && overlap(zone, bounds)) issues.push(`route_clearance_or_clash:${segment.id}`); }
  for (const segment of segments) if (Array.isArray(segment?.centerlineMm) && segment.centerlineMm.length > 2) for (let index = 1; index < segment.centerlineMm.length - 1; index += 1) { const radius = bendRadius(segment.centerlineMm[index - 1]!, segment.centerlineMm[index]!, segment.centerlineMm[index + 1]!); if (Number.isFinite(radius)) issues.push(`bend_geometry_not_verified:${segment.id}`); }
  const output = input.output; if (!output || typeof output !== 'object' || output.format !== 'nexyfab-exchange-json' || !['ifc-neutral', 'step', 'json'].includes(output.targetFormat) || output.revision !== input.revision || typeof output.content !== 'string' || !Number.isSafeInteger(output.bytes) || output.bytes !== Buffer.byteLength(output.content, 'utf8') || !SHA256.test(output.sha256) || sha256(output.content) !== output.sha256) issues.push('output_binding_invalid'); else { try { if (!verifyCableTrayConduitReadback(input, parseCableTrayConduitOutput(input)).valid) issues.push('output_readback_invalid'); } catch { issues.push('output_readback_invalid'); } } return { valid: issues.length === 0, issues };
}
function verificationHash(value: Omit<CableRouteParserReadbackV1, 'verificationSha256'>): string { return sha256(JSON.stringify({ ...value, routeIds: [...value.routeIds].sort(), portIds: [...value.portIds].sort(), segmentIds: [...value.segmentIds].sort(), fittingIds: [...value.fittingIds].sort(), cableIds: [...value.cableIds].sort(), supportIds: [...value.supportIds].sort() })); }
export function parseCableTrayConduitOutput(input: CableTrayConduitReleaseInputV1): CableRouteParserReadbackV1 { let parsed: unknown; try { parsed = JSON.parse(input.output.content) as unknown; } catch { throw new Error('CABLE_TRAY_CONDUIT_OUTPUT_JSON_INVALID'); } const keys = ['schema', 'revision', 'sourceWorkspaceId', 'sourceModelId', 'sourceModelSha256', 'sourceContentHash', 'sourceRawArtifactSha256', 'routeIds', 'portIds', 'segmentIds', 'fittingIds', 'cableIds', 'supportIds'] as const; if (!exactKeys(parsed, keys) || parsed.schema !== CABLE_TRAY_CONDUIT_EXCHANGE_SCHEMA || !Number.isSafeInteger(parsed.revision) || typeof parsed.sourceWorkspaceId !== 'string' || !parsed.sourceWorkspaceId.trim() || typeof parsed.sourceModelId !== 'string' || !parsed.sourceModelId.trim() || ![parsed.sourceModelSha256, parsed.sourceContentHash, parsed.sourceRawArtifactSha256].every(value => typeof value === 'string' && SHA256.test(value)) || !keys.slice(7).every(key => stableIdArray(parsed[key]))) throw new Error('CABLE_TRAY_CONDUIT_OUTPUT_SCHEMA_INVALID'); const exchange = parsed as unknown as CableRouteExchangeV1; const unsigned = { parserId: PARSER_ID, parserSourceSha256: sha256(parseCableTrayConduitOutput.toString()), sourceWorkspaceId: exchange.sourceWorkspaceId, sourceModelId: exchange.sourceModelId, sourceModelSha256: exchange.sourceModelSha256, sourceContentHash: exchange.sourceContentHash, sourceRawArtifactSha256: exchange.sourceRawArtifactSha256, sourceRevision: exchange.revision, outputSha256: sha256(input.output.content), routeIds: exchange.routeIds, portIds: exchange.portIds, segmentIds: exchange.segmentIds, fittingIds: exchange.fittingIds, cableIds: exchange.cableIds, supportIds: exchange.supportIds } as const; return { ...unsigned, verificationSha256: verificationHash(unsigned) }; }
export function verifyCableTrayConduitReadback(input: CableTrayConduitReleaseInputV1, readback: CableRouteParserReadbackV1 | null | undefined): CableRouteReadbackResult { if (!readback || typeof readback !== 'object') return { valid: false, issues: ['readback_missing'] }; const expected = { parserId: PARSER_ID, parserSourceSha256: sha256(parseCableTrayConduitOutput.toString()), sourceWorkspaceId: input.source.workspaceId, sourceModelId: input.source.modelId, sourceModelSha256: input.source.modelSha256, sourceContentHash: input.source.contentHash, sourceRawArtifactSha256: input.source.rawArtifactSha256, sourceRevision: input.revision, outputSha256: sha256(input.output.content), routeIds: input.routes.map(item => item.id), portIds: input.ports.map(item => item.id), segmentIds: input.segments.map(item => item.id), fittingIds: input.fittings.map(item => item.id), cableIds: input.cables.map(item => item.id), supportIds: input.supports.map(item => item.id) } as const; const issues: string[] = []; for (const key of ['parserId', 'parserSourceSha256', 'sourceWorkspaceId', 'sourceModelId', 'sourceModelSha256', 'sourceContentHash', 'sourceRawArtifactSha256', 'sourceRevision', 'outputSha256', 'routeIds', 'portIds', 'segmentIds', 'fittingIds', 'cableIds', 'supportIds'] as const) if (JSON.stringify(readback[key]) !== JSON.stringify(expected[key])) issues.push(`readback_${key}_mismatch`); const { verificationSha256, ...unsigned } = readback; if (verificationSha256 !== verificationHash(unsigned)) issues.push('readback_verification_hash_invalid'); return { valid: issues.length === 0, issues }; }
export function assessCableTrayConduitRelease(input: CableTrayConduitReleaseInputV1, readback?: CableRouteParserReadbackV1 | null): CableRouteReleaseAssessment { const validation = validateCableTrayConduitRelease(input); const internalParserVerified = readback ? verifyCableTrayConduitReadback(input, readback).valid : false; const independentAttestationVerified = false; const blockers: string[] = [...holdBoundary]; if (!validation.valid) blockers.unshift(...validation.issues); blockers.unshift('independent_parser_attestation_required'); return { schema: CABLE_TRAY_CONDUIT_RELEASE_SCHEMA, releaseReady: false, status: 'HOLD', internalParserVerified, independentAttestationVerified, parserVerified: false, blockers, holdBoundary }; }
