import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { assessCableTrayConduitRelease, CABLE_TRAY_CONDUIT_EXCHANGE_SCHEMA, parseCableTrayConduitOutput, type CableTrayConduitReleaseInputV1, validateCableTrayConduitRelease, verifyCableTrayConduitReadback } from './cableTrayConduitRouteReleaseContract';

const hash = (value: string): string => createHash('sha256').update(value, 'utf8').digest('hex');
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;

function fixture(): CableTrayConduitReleaseInputV1 {
  const outputContent = JSON.stringify({ schema: CABLE_TRAY_CONDUIT_EXCHANGE_SCHEMA, revision: 3, sourceWorkspaceId: 'workspace-tray-1', sourceModelId: 'tray-model-1', sourceModelSha256: hash('tray-model'), sourceContentHash: hash('tray-content'), sourceRawArtifactSha256: hash('tray-raw'), routeIds: ['route-1'], portIds: ['port-1', 'port-2', 'port-3', 'port-4'], segmentIds: ['segment-1', 'segment-2'], fittingIds: ['fitting-1'], cableIds: ['cable-1', 'cable-2'], supportIds: ['support-1', 'support-2'] });
  return {
    schema: 'nexyfab.cable-tray-conduit-release.v1', units: 'mm-A-V', revision: 3,
    source: { workspaceId: 'workspace-tray-1', modelId: 'tray-model-1', modelPath: 'models/tray.ifc', modelSha256: hash('tray-model'), contentHash: hash('tray-content'), rawArtifactSha256: hash('tray-raw'), revisionSha256: hash('tray-revision-3'), revision: 3 },
    routes: [{ id: 'route-1', kind: 'tray', voltageClass: 'low', segmentIds: ['segment-1', 'segment-2'], fittingIds: ['fitting-1'], portIds: ['port-1', 'port-2', 'port-3', 'port-4'], maxSupportSpacingMm: 1200, fillRatioLimit: 0.4, minimumClearanceMm: 50 }],
    ports: [
      { id: 'port-1', ownerType: 'segment', ownerId: 'segment-1', positionMm: { xMm: 0, yMm: 0, zMm: 0 }, direction: { xMm: 1, yMm: 0, zMm: 0 }, connectedPortIds: [] },
      { id: 'port-2', ownerType: 'fitting', ownerId: 'fitting-1', positionMm: { xMm: 300, yMm: 0, zMm: 0 }, direction: { xMm: 1, yMm: 0, zMm: 0 }, connectedPortIds: ['port-3'] },
      { id: 'port-3', ownerType: 'fitting', ownerId: 'fitting-1', positionMm: { xMm: 300, yMm: 0, zMm: 0 }, direction: { xMm: 0, yMm: 1, zMm: 0 }, connectedPortIds: ['port-2'] },
      { id: 'port-4', ownerType: 'segment', ownerId: 'segment-2', positionMm: { xMm: 300, yMm: 300, zMm: 0 }, direction: { xMm: 0, yMm: 1, zMm: 0 }, connectedPortIds: [] },
    ],
    segments: [
      { id: 'segment-1', routeId: 'route-1', startPortId: 'port-1', endPortId: 'port-2', kind: 'tray', widthMm: 300, depthMm: 100, centerlineMm: [{ xMm: 0, yMm: 0, zMm: 0 }, { xMm: 300, yMm: 0, zMm: 0 }], lengthMm: 300, bendRadiusMm: 200, cableIds: ['cable-1', 'cable-2'] },
      { id: 'segment-2', routeId: 'route-1', startPortId: 'port-3', endPortId: 'port-4', kind: 'tray', widthMm: 300, depthMm: 100, centerlineMm: [{ xMm: 300, yMm: 0, zMm: 0 }, { xMm: 300, yMm: 300, zMm: 0 }], lengthMm: 300, bendRadiusMm: 200, cableIds: ['cable-1', 'cable-2'] },
    ],
    fittings: [{ id: 'fitting-1', routeId: 'route-1', type: 'elbow', portIds: ['port-2', 'port-3'], bendRadiusMm: 200 }],
    cables: [{ id: 'cable-1', routeId: 'route-1', voltageClass: 'low', crossSectionAreaMm2: 1000, minimumBendRadiusMm: 100 }, { id: 'cable-2', routeId: 'route-1', voltageClass: 'low', crossSectionAreaMm2: 500, minimumBendRadiusMm: 100 }],
    supports: [{ id: 'support-1', segmentId: 'segment-1', positionAlongMm: 100, spacingMm: 600, supportType: 'trapeze' }, { id: 'support-2', segmentId: 'segment-2', positionAlongMm: 100, spacingMm: 600, supportType: 'trapeze' }],
    clearanceZones: [{ id: 'zone-1', ownerId: 'segment-1', originMm: { xMm: 0, yMm: 500, zMm: 0 }, widthMm: 100, depthMm: 100, heightMm: 100 }],
    output: { format: 'nexyfab-exchange-json', targetFormat: 'ifc-neutral', revision: 3, content: outputContent, bytes: Buffer.byteLength(outputContent, 'utf8'), sha256: hash(outputContent) },
  };
}

describe('cable tray and conduit route release contract', () => {
  it('validates tray geometry, cable fill and actual output readback', () => { const input = fixture(); expect(validateCableTrayConduitRelease(input)).toEqual({ valid: true, issues: [] }); const readback = parseCableTrayConduitOutput(input); expect(verifyCableTrayConduitReadback(input, readback)).toEqual({ valid: true, issues: [] }); const assessment = assessCableTrayConduitRelease(input, readback); expect(assessment.releaseReady).toBe(false); expect(assessment.blockers).toContain('native_ifc_step_parser_not_verified'); });
  it('fails closed for port, fill, bend, segregation, support, and clash mutations', () => { const broken = clone(fixture()); broken.ports[2]!.connectedPortIds = []; broken.cables[0]!.crossSectionAreaMm2 = 20_000; broken.cables[1]!.voltageClass = 'high'; broken.cables[0]!.minimumBendRadiusMm = 500; broken.supports[0]!.spacingMm = 2000; broken.clearanceZones[0]!.originMm = { xMm: 50, yMm: 0, zMm: 0 }; expect(validateCableTrayConduitRelease(broken).issues).toEqual(expect.arrayContaining(['port_bidirectional_ownership_invalid:port-2', 'cable_fill_exceeded:segment-1', 'voltage_class_segregation_invalid:segment-1', 'cable_bend_radius_invalid:segment-1', 'support_spacing_invalid:support-1', 'route_clearance_or_clash:segment-1'])); });
  it('rejects hash-valid forged output identity and readback tamper', () => { const input = fixture(); const readback = parseCableTrayConduitOutput(input); const tampered = clone(readback); tampered.outputSha256 = hash('tampered'); expect(verifyCableTrayConduitReadback(input, tampered).valid).toBe(false); const forged = clone(input); const payload = JSON.parse(forged.output.content) as { segmentIds: string[] }; payload.segmentIds = ['forged']; forged.output.content = JSON.stringify(payload); forged.output.bytes = Buffer.byteLength(forged.output.content); forged.output.sha256 = hash(forged.output.content); expect(validateCableTrayConduitRelease(forged).issues).toContain('output_readback_invalid'); });
  it('does not throw on malformed collections', () => { const malformed = clone(fixture()) as unknown as Record<string, unknown>; malformed.routes = null; malformed.ports = null; malformed.segments = null; expect(() => validateCableTrayConduitRelease(malformed as unknown as CableTrayConduitReleaseInputV1)).not.toThrow(); expect(validateCableTrayConduitRelease(malformed as unknown as CableTrayConduitReleaseInputV1).valid).toBe(false); });
  it('fails closed on support gaps and a clearance zone intersecting the route AABB', () => { const gap = clone(fixture()); gap.supports[0]!.positionAlongMm = 0; gap.supports[1]!.segmentId = 'segment-1'; gap.supports[1]!.positionAlongMm = 100; gap.routes[0]!.maxSupportSpacingMm = 50; expect(validateCableTrayConduitRelease(gap).issues).toContain('support_gap_exceeded:segment-1'); const clash = clone(fixture()); clash.clearanceZones[0]!.originMm = { xMm: 100, yMm: -20, zMm: -20 }; expect(validateCableTrayConduitRelease(clash).issues).toContain('route_clearance_or_clash:segment-1'); });
  it('rejects route-kind and cable-route ownership spoofing and missing support', () => { const spoof = clone(fixture()); spoof.segments[0]!.kind = 'conduit'; expect(validateCableTrayConduitRelease(spoof).issues).toContain('segment_ownership_invalid:segment-1'); const cable = clone(fixture()); cable.segments[0]!.cableIds = ['cable-2']; cable.cables[1]!.routeId = 'route-other'; expect(validateCableTrayConduitRelease(cable).issues).toContain('segment_ownership_invalid:segment-1'); const missing = clone(fixture()); missing.supports = []; expect(validateCableTrayConduitRelease(missing).issues).toContain('support_missing:segment-1'); });
  it('rejects disconnected port geometry and unproven interior bend radius', () => { const ports = clone(fixture()); ports.ports[2]!.positionMm = { xMm: 301, yMm: 0, zMm: 0 }; expect(validateCableTrayConduitRelease(ports).issues).toContain('port_spatial_continuity_invalid:port-2'); const bend = clone(fixture()); bend.segments[1]!.centerlineMm = [{ xMm: 300, yMm: 0, zMm: 0 }, { xMm: 350, yMm: 150, zMm: 0 }, { xMm: 300, yMm: 300, zMm: 0 }]; bend.segments[1]!.lengthMm = 2 * Math.hypot(50, 150); expect(validateCableTrayConduitRelease(bend).issues).toContain('bend_geometry_not_verified:segment-2'); });
});
