import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { canonicalDesignJson, designRevisionSha256 } from '@/lib/designArtifactBinding';
import { buildCivilFoundationGeotechnicalReceipt, claimCivilFoundationGeotechnicalReceipt, exportCivilFoundationGeotechnicalArtifact, parseCivilFoundationGeotechnicalArtifact, verifyCivilFoundationGeotechnical, type FoundationInput } from './civilFoundationGeotechnicalCoordinationContract';
const encoder = new TextEncoder(); const sha = (bytes: Uint8Array) => createHash('sha256').update(bytes).digest('hex'); const revisionValue = { project: 'foundation', revision: 3 }; const workspaceRevisionId = 'foundation-workspace:r3'; const workspaceContentHash = designRevisionSha256(revisionValue); const artifact = (id: string, kind: 'tin' | 'geotech_model', value: string) => ({ id, kind, bytes: encoder.encode(value) });
function input(): FoundationInput { const tinArtifact = artifact('artifact:tin', 'tin', 'TIN-R3'); const geotechArtifact = artifact('artifact:geotech', 'geotech_model', 'GEOTECH-R3'); return { workspaceRevisionId, expectedWorkspaceRevisionId: workspaceRevisionId, workspaceRevisionValue: revisionValue, expectedWorkspaceContentHash: workspaceContentHash, tinArtifact, geotechArtifact, expectedTinArtifactSha256: sha(tinArtifact.bytes), expectedGeotechArtifactSha256: sha(geotechArtifact.bytes), crs: { epsg: 5186, horizontalDatum: 'Korea2000', verticalDatum: 'KVD2002' }, boreholes: [{ id: 'borehole:01', positionM: [0, 0], groundElevationM: 100, totalDepthM: 12, sourceId: 'survey:b01', sourceSha256: 'a'.repeat(64) }], soilLayers: [{ id: 'soil:01', boreholeId: 'borehole:01', topDepthM: 0, bottomDepthM: 12, material: 'dense sand', unitWeightKNm3: 18, cohesionKPa: 5, frictionAngleDeg: 32, allowableBearingKPa: 250, sourceId: 'lab:01', sourceSha256: 'b'.repeat(64) }], designBearings: [{ id: 'bearing:01', footingId: 'footing:01', allowableBearingKPa: 250, groundwaterElevationM: 90, provenanceId: 'geotech:design', provenanceSha256: 'c'.repeat(64) }, { id: 'bearing:02', footingId: 'pile:01', allowableBearingKPa: 250, groundwaterElevationM: 90, provenanceId: 'geotech:design', provenanceSha256: 'c'.repeat(64) }], footings: [{ id: 'footing:01', positionM: [0, 0], elevationM: 98, widthM: 2, lengthM: 2, thicknessM: 0.5, coverM: 0.08, serviceLoadKN: 500, designBearingId: 'bearing:01' }], piles: [{ id: 'pile:01', positionM: [10, 0], headElevationM: 98, toeElevationM: 88, diameterM: 0.5, allowableCapacityKN: 800, serviceLoadKN: 400, coverM: 0.1, designBearingId: 'bearing:02' }], minimumFootingSpacingM: 2, minimumPileSpacingM: 1, minimumCoverM: 0.05 }; }
describe('civil foundation/geotechnical coordination contract', () => {
  it('binds geotech/TIN/workspace, checks bearing and emits receipt deterministically', () => {
    const first = exportCivilFoundationGeotechnicalArtifact(input()); const second = exportCivilFoundationGeotechnicalArtifact(input());
    expect(first.artifactSha256).toBe(second.artifactSha256); expect(first.payload.units).toEqual({ length: 'm', force: 'kN', stress: 'kPa' }); expect(first.payload.criteria).toEqual({ minimumFootingSpacingM: 2, minimumPileSpacingM: 1, minimumCoverM: 0.05 }); expect(first.payload.checks.every(item => item.status === 'passed')).toBe(true); expect(first.payload.geotechApproval).toBe('HOLD');
    const parsed = parseCivilFoundationGeotechnicalArtifact(first.bytes, first.payload.binding); expect(verifyCivilFoundationGeotechnical({ artifact: parsed, ...first.payload.binding })).toMatchObject({ status: 'passed' }); const parserOutputBytes = encoder.encode(canonicalDesignJson(parsed)); const verifierEvidenceBytes = encoder.encode(canonicalDesignJson({ schema: 'nexyfab.civil-foundation-geotechnical-verification.v1', verifierId: 'civil-foundation-geotechnical-structural.v1', status: 'passed', artifactSha256: first.artifactSha256, contentHash: first.contentHash, releaseReady: false })); const receiptBytes = buildCivilFoundationGeotechnicalReceipt({ artifact: first, parserOutputBytes, verifierEvidenceBytes }); expect(claimCivilFoundationGeotechnicalReceipt({ artifact: first, receiptBytes, parserOutputBytes, verifierEvidenceBytes }).claim).toBe('internal-civil-foundation-geotechnical-verified');
  });
  it('rejects cover, bearing, spacing, stale artifact and parser/receipt tamper', () => {
    const cover = input(); cover.footings[0]!.coverM = 0; expect(() => exportCivilFoundationGeotechnicalArtifact(cover)).toThrow('FOOTING_CAPACITY_INVALID'); const bearing = input(); bearing.footings[0]!.serviceLoadKN = 2000; expect(() => exportCivilFoundationGeotechnicalArtifact(bearing)).toThrow('FOOTING_CAPACITY_INVALID');
    const spacing = input(); spacing.piles.push({ ...spacing.piles[0]!, id: 'pile:02', positionM: [10.5, 0] }); expect(() => exportCivilFoundationGeotechnicalArtifact(spacing)).toThrow('PILE_SPACING_INVALID'); const stale = input(); stale.expectedWorkspaceContentHash = 'd'.repeat(64); expect(() => exportCivilFoundationGeotechnicalArtifact(stale)).toThrow('STALE_REVISION_HASH'); const artifactTamper = input(); artifactTamper.geotechArtifact.bytes = encoder.encode('GEOTECH-R4'); expect(() => exportCivilFoundationGeotechnicalArtifact(artifactTamper)).toThrow('STALE_ARTIFACT_HASH');
    const exported = exportCivilFoundationGeotechnicalArtifact(input()); const envelope = JSON.parse(new TextDecoder().decode(exported.bytes)) as { payload: Record<string, unknown>; contentHash: string }; envelope.payload.releaseReady = true; expect(() => parseCivilFoundationGeotechnicalArtifact(encoder.encode(canonicalDesignJson(envelope)), exported.payload.binding)).toThrow('INVALID'); const parsed = parseCivilFoundationGeotechnicalArtifact(exported.bytes); const parserOutputBytes = encoder.encode(canonicalDesignJson(parsed)); const verifierEvidenceBytes = encoder.encode(canonicalDesignJson({ schema: 'nexyfab.civil-foundation-geotechnical-verification.v1', verifierId: 'civil-foundation-geotechnical-structural.v1', status: 'passed', artifactSha256: exported.artifactSha256, contentHash: exported.contentHash, releaseReady: false })); const receiptBytes = buildCivilFoundationGeotechnicalReceipt({ artifact: exported, parserOutputBytes, verifierEvidenceBytes }); expect(() => claimCivilFoundationGeotechnicalReceipt({ artifact: exported, receiptBytes, parserOutputBytes: encoder.encode('{"tampered":true}'), verifierEvidenceBytes })).toThrow('PARSER_OUTPUT_MISMATCH');
  });
  it('rejects forged cover and recomputed bearing checks after envelope rehash', () => {
    const exported = exportCivilFoundationGeotechnicalArtifact(input());
    const envelope = JSON.parse(new TextDecoder().decode(exported.bytes)) as { payload: typeof exported.payload; contentHash: string };
    envelope.payload.footings[0]!.coverM = 0;
    envelope.payload.checks[0]!.utilization = 0.1;
    envelope.contentHash = designRevisionSha256(envelope.payload);
    const bytes = encoder.encode(canonicalDesignJson(envelope));
    const parsed = parseCivilFoundationGeotechnicalArtifact(bytes);
    expect(verifyCivilFoundationGeotechnical({ artifact: parsed, ...parsed.payload.binding })).toMatchObject({ status: 'failed', issues: expect.arrayContaining(['foundation_footing_cover_invalid:footing:01', 'foundation_check_computation_mismatch']) });
  });
  it('rejects swapped semantic artifact roles and colliding artifact ids', () => {
    const swapped = input(); (swapped.tinArtifact as { kind: string }).kind = 'geotech_model';
    expect(() => exportCivilFoundationGeotechnicalArtifact(swapped)).toThrow('ARTIFACT_HASH_MISMATCH');
    const collision = input(); collision.geotechArtifact.id = collision.tinArtifact.id;
    expect(() => exportCivilFoundationGeotechnicalArtifact(collision)).toThrow('ARTIFACT_ID_COLLISION');
  });
});
