import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { designRevisionSha256 } from '@/lib/designArtifactBinding';
import type { CivilDocument } from './civilDocument';
import { buildCivilEarthworkProbeReceipt, claimCivilEarthworkProbe, exportCivilEarthworkArtifact, parseCivilEarthworkArtifact, verifyCivilEarthworkArtifact } from './civilEarthworkArtifact';
const hash = (v: Uint8Array | string) => createHash('sha256').update(v).digest('hex');
const doc = (): CivilDocument => ({ schema:'nexyfab.civil.v1', revision:4, coordinateSystemId:'site', crs:{epsg:5186,horizontalDatum:'Korea2000',verticalDatum:'KVD2002',units:'m'}, sourceEvidence:[{id:'evidence',kind:'survey',sourceRef:'sampled-grid',capturedAt:'2026-08-22T00:00:00.000Z'}], surveyControls:[], points:[{id:'e00',positionM:[0,0,10],evidenceId:'evidence'},{id:'e10',positionM:[1,0,10.2],evidenceId:'evidence'},{id:'e01',positionM:[0,1,10.1],evidenceId:'evidence'},{id:'e11',positionM:[1,1,10.3],evidenceId:'evidence'},{id:'p00',positionM:[0,0,9.8],evidenceId:'evidence'},{id:'p10',positionM:[1,0,10],evidenceId:'evidence'},{id:'p01',positionM:[0,1,10],evidenceId:'evidence'},{id:'p11',positionM:[1,1,10.1],evidenceId:'evidence'}], surfaces:[{id:'existing',kind:'existing',pointIds:['e00','e10','e01','e11'],triangles:[['e00','e10','e11'],['e00','e11','e01']],sourceEvidenceIds:['evidence']},{id:'proposed',kind:'proposed',pointIds:['p00','p10','p01','p11'],triangles:[['p00','p10','p11'],['p00','p11','p01']],sourceEvidenceIds:['evidence']}], alignments:[],profiles:[],crossSections:[],corridors:[],drainageNodes:[],drainageLinks:[],catchments:[],structures:[],stages:[] });
const grid = { originM:[0,0] as [number,number], cellSizeM:1, rows:2, cols:2, existingElevationM:[[10,10.2],[10.1,10.3]], proposedElevationM:[[9.8,10],[10,10.1]], existingPointIds:[['e00','e10'],['e01','e11']], proposedPointIds:[['p00','p10'],['p01','p11']] };
const input = () => { const revisionValue={workspace:'civil-earthwork',revision:4}; const revisionSha256=designRevisionSha256(revisionValue); return { projectId:'project-1',revisionId:'civil:r4',revisionValue,expectedRevisionId:'civil:r4',expectedRevisionSha256:revisionSha256,document:doc(),existingSurfaceId:'existing',proposedSurfaceId:'proposed',grid }; };
describe('civil internal earthwork artifact', () => {
  it('calls the grid calculator and binds sampled source ids, units and signs', () => { const artifact=exportCivilEarthworkArtifact(input()); expect(artifact.payload.calculator.output.volumes).toMatchObject({cut_m3:0.17,fill_m3:0,net_m3:0.17}); expect(artifact.payload.counts).toMatchObject({gridPointCount:4,cellCount:1}); expect(parseCivilEarthworkArtifact(artifact.bytes).payload.surfaces).toEqual({existingSurfaceId:'existing',proposedSurfaceId:'proposed'}); expect(verifyCivilEarthworkArtifact({artifact:parseCivilEarthworkArtifact(artifact.bytes),document:doc(),projectId:'project-1',revisionId:'civil:r4',revisionSha256:input().expectedRevisionSha256})).toMatchObject({status:'passed'}); });
  it('fails closed for stale, duplicate/missing source refs, nonpositive spacing and sampled tamper', () => { const a=input(); expect(()=>exportCivilEarthworkArtifact({...a,revisionId:'civil:r3'})).toThrow('CIVIL_EARTHWORK_STALE_REVISION'); expect(()=>exportCivilEarthworkArtifact({...a,grid:{...grid,cellSizeM:0}})).toThrow('CIVIL_EARTHWORK_INPUT_INVALID'); expect(()=>exportCivilEarthworkArtifact({...a,grid:{...grid,existingPointIds:[['e00','e10'],['e01','e00']]}})).toThrow('CIVIL_EARTHWORK_INPUT_INVALID'); const tampered=doc(); tampered.points[0]!.positionM=[0,0,11]; expect(()=>exportCivilEarthworkArtifact({...a,document:tampered})).toThrow('CIVIL_EARTHWORK_INPUT_INVALID'); });
  it('executes exporter/parser/probe and rebinds every raw byte hash', () => { const root=resolve(process.cwd()); const probe=JSON.parse(execFileSync(process.execPath,['scripts/drawing-to-3d/civil-earthwork-probe.mjs'],{cwd:root,encoding:'utf8'})) as Record<string,unknown>; const bytes=(k:string)=>Buffer.from(String(probe[k]),'base64'); const artifactBytes=bytes('artifactBase64'), parserOutputBytes=bytes('parserOutputBase64'), calculatorOutputBytes=bytes('calculatorOutputBase64'), verifierEvidenceBytes=bytes('verifierEvidenceBase64'); const artifactParsed=parseCivilEarthworkArtifact(artifactBytes); const artifact={payload:artifactParsed.payload,contentHash:artifactParsed.contentHash,bytes:artifactBytes,artifactSha256:hash(artifactBytes),artifactName:'civil-earthwork.json',artifactMime:'application/json' as const,sourceDocumentSha256:artifactParsed.payload.binding.sourceDocumentSha256}; const exporterSourceBytes=readFileSync(resolve(String(probe.exporterId))), parserSourceBytes=readFileSync(resolve(String(probe.parserId))), calculatorSourceBytes=readFileSync(resolve('scripts/engineering-core/calculators/earthwork-grid.mjs')); const evidence=buildCivilEarthworkProbeReceipt({artifact,exporterId:String(probe.exporterId),exporterSourceSha256:String(probe.exporterSourceSha256),parserId:String(probe.parserId),parserSourceSha256:String(probe.parserSourceSha256),calculatorSourceSha256:String(probe.calculatorSourceSha256),parserResult:{status:'verified',sourceArtifactSha256:artifact.artifactSha256,outputBytes:parserOutputBytes,stableIds:probe.stableIds as { existingSurfaceId: string; proposedSurfaceId: string; existingPointIds: string[]; proposedPointIds: string[] }},verifierEvidenceBytes,calculatorOutputBytes}); expect(claimCivilEarthworkProbe({artifact,evidenceBytes:evidence,exporterSourceBytes,parserSourceBytes,calculatorSourceBytes,parserOutputBytes,calculatorOutputBytes,verifierEvidenceBytes})).toMatchObject({claim:'internal-earthwork-verified',releaseReady:false,requiredArtifactKinds:[]}); expect(()=>claimCivilEarthworkProbe({artifact,evidenceBytes:evidence,exporterSourceBytes:Buffer.from('tampered'),parserSourceBytes,calculatorSourceBytes,parserOutputBytes,calculatorOutputBytes,verifierEvidenceBytes})).toThrow('CIVIL_EARTHWORK_EVIDENCE_BINDING_MISMATCH'); });
});
