import { createHash } from 'node:crypto';

export const CNC_MACHINING_RELEASE_SCHEMA = 'nexyfab.cnc-machining-release.v1' as const;
export const CNC_MACHINING_EXCHANGE_SCHEMA = 'nexyfab.cnc-machining-exchange.v1' as const;
const PARSER_ID = 'nexyfab.cnc-machining-independent-parser.v1' as const;
const SHA256 = /^[a-f0-9]{64}$/;
const EPSILON = 1e-8;
export interface CncSourceBindingV1 { workspaceId: string; modelId: string; modelPath: string; modelSha256: string; toolLibrarySha256: string; rawArtifactSha256: string; contentHash: string; revisionSha256: string; revision: number; }
export interface CncPointMmV1 { xMm: number; yMm: number; zMm: number; }
export interface CncBoxV1 { originMm: CncPointMmV1; widthMm: number; depthMm: number; heightMm: number; }
export interface CncStockV1 extends CncBoxV1 { id: string; materialId: string; }
export interface CncSetupV1 { id: string; stockId: string; originMm: CncPointMmV1; workholdingIds: readonly string[]; operationIds: readonly string[]; }
export interface CncWorkholdingV1 extends CncBoxV1 { id: string; setupId: string; clearanceMm: number; }
export interface CncToolV1 { id: string; toolType: 'endmill' | 'drill'; diameterMm: number; fluteLengthMm: number; overallLengthMm: number; maxRpm: number; maxFeedMmMin: number; }
export type CncOperationKind = 'pocket' | 'drill' | 'contour';
export interface CncFeatureV1 extends CncBoxV1 { id: string; kind: CncOperationKind; stockId: string; }
export interface CncOperationV1 { id: string; setupId: string; toolId: string; featureId: string; kind: CncOperationKind; spindleRpm: number; feedMmMin: number; depthMm: number; pathPointsMm: readonly CncPointMmV1[]; toolpathLengthMm: number; removedVolumeMm3: number; }
export interface CncOutputV1 { format: 'nexyfab-exchange-json'; targetFormat: 'step' | 'toolpath-neutral' | 'json'; revision: number; content: string; bytes: number; sha256: string; }
export interface CncMachiningExchangeV1 { schema: typeof CNC_MACHINING_EXCHANGE_SCHEMA; revision: number; sourceWorkspaceId: string; sourceModelId: string; sourceModelSha256: string; sourceToolLibrarySha256: string; sourceRawArtifactSha256: string; sourceContentHash: string; stockId: string; setupIds: string[]; workholdingIds: string[]; toolIds: string[]; featureIds: string[]; operationIds: string[]; }
export interface CncMachiningReleaseInputV1 { schema: typeof CNC_MACHINING_RELEASE_SCHEMA; units: 'mm-rpm-mmMin'; revision: number; source: CncSourceBindingV1; stock: CncStockV1; setups: readonly CncSetupV1[]; workholding: readonly CncWorkholdingV1[]; tools: readonly CncToolV1[]; features: readonly CncFeatureV1[]; operations: readonly CncOperationV1[]; output: CncOutputV1; }
export interface CncParserReadbackV1 { parserId: typeof PARSER_ID; parserSourceSha256: string; sourceWorkspaceId: string; sourceModelId: string; sourceModelSha256: string; sourceToolLibrarySha256: string; sourceRawArtifactSha256: string; sourceContentHash: string; sourceRevision: number; outputSha256: string; stockId: string; setupIds: readonly string[]; workholdingIds: readonly string[]; toolIds: readonly string[]; featureIds: readonly string[]; operationIds: readonly string[]; verificationSha256: string; }
export interface CncValidationResult { valid: boolean; issues: string[]; }
export interface CncReleaseAssessment { schema: typeof CNC_MACHINING_RELEASE_SCHEMA; releaseReady: false; status: 'HOLD'; internalParserVerified: boolean; independentAttestationVerified: boolean; /** @deprecated Use internalParserVerified. */ parserVerified: boolean; blockers: string[]; holdBoundary: readonly string[]; }
export interface CncReadbackResult { valid: boolean; issues: string[]; }
const holdBoundary = ['native_step_toolpath_parser_not_verified', 'machine_postprocessor_not_verified', 'gcode_dry_run_not_run', 'tool_calibration_not_verified', 'metrology_and_fai_not_run', 'operator_approval_not_available'] as const;
const sha256 = (value: string): string => createHash('sha256').update(value, 'utf8').digest('hex'); const finite = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value); const positive = (value: unknown): value is number => finite(value) && value > 0; const nonnegative = (value: unknown): value is number => finite(value) && value >= 0; const arrays = <T>(value: unknown): readonly T[] => Array.isArray(value) ? value as readonly T[] : []; const equal = (a: number, b: number): boolean => Math.abs(a - b) <= Math.max(EPSILON, Math.max(Math.abs(a), Math.abs(b)) * 1e-9); const point = (value: unknown): value is CncPointMmV1 => Boolean(value && typeof value === 'object' && finite((value as CncPointMmV1).xMm) && finite((value as CncPointMmV1).yMm) && finite((value as CncPointMmV1).zMm)); const distance = (a: CncPointMmV1, b: CncPointMmV1): number => Math.hypot(a.xMm - b.xMm, a.yMm - b.yMm, a.zMm - b.zMm); const ids = (values: readonly { id?: unknown }[]): Set<string> => new Set(values.map(value => value?.id).filter((id): id is string => typeof id === 'string'));
const exactKeys = (value: unknown, keys: readonly string[]): value is Record<string, unknown> => Boolean(value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === keys.length && Object.keys(value).every(key => keys.includes(key))); const stableIdArray = (value: unknown): value is string[] => Array.isArray(value) && value.every(id => typeof id === 'string' && id.trim() === id && id.length > 0) && new Set(value).size === value.length;
function register(values: readonly { id?: unknown }[], label: string, issues: string[], all: Set<string>): void { for (const value of values) { const id = value?.id; if (typeof id !== 'string' || !id.trim() || all.has(id)) issues.push(`${label}_id_invalid:${String(id)}`); else all.add(id); } }
function inside(pointValue: CncPointMmV1, box: CncBoxV1, margin = 0): boolean { return pointValue.xMm >= box.originMm.xMm + margin && pointValue.yMm >= box.originMm.yMm + margin && pointValue.zMm >= box.originMm.zMm + margin && pointValue.xMm <= box.originMm.xMm + box.widthMm - margin && pointValue.yMm <= box.originMm.yMm + box.depthMm - margin && pointValue.zMm <= box.originMm.zMm + box.heightMm - margin; }
function insideExpanded(pointValue: CncPointMmV1, box: CncBoxV1, margin: number): boolean { return pointValue.xMm >= box.originMm.xMm - margin && pointValue.yMm >= box.originMm.yMm - margin && pointValue.zMm >= box.originMm.zMm - margin && pointValue.xMm <= box.originMm.xMm + box.widthMm + margin && pointValue.yMm <= box.originMm.yMm + box.depthMm + margin && pointValue.zMm <= box.originMm.zMm + box.heightMm + margin; }
function segmentIntersectsExpandedBox(a: CncPointMmV1, b: CncPointMmV1, box: CncBoxV1, margin: number): boolean { let t0 = 0; let t1 = 1; const min = [box.originMm.xMm - margin, box.originMm.yMm - margin, box.originMm.zMm - margin]; const max = [box.originMm.xMm + box.widthMm + margin, box.originMm.yMm + box.depthMm + margin, box.originMm.zMm + box.heightMm + margin]; const av = [a.xMm, a.yMm, a.zMm]; const dv = [b.xMm - a.xMm, b.yMm - a.yMm, b.zMm - a.zMm]; for (let i = 0; i < 3; i += 1) { if (Math.abs(dv[i]!) <= EPSILON) { if (av[i]! < min[i]! || av[i]! > max[i]!) return false; continue; } const enter = (min[i]! - av[i]!) / dv[i]!; const exit = (max[i]! - av[i]!) / dv[i]!; const lo = Math.min(enter, exit); const hi = Math.max(enter, exit); t0 = Math.max(t0, lo); t1 = Math.min(t1, hi); if (t0 > t1 + EPSILON) return false; } return true; }
function volume(feature: CncFeatureV1): number { return feature.kind === 'drill' ? Math.PI * (feature.widthMm / 2) ** 2 * feature.depthMm : feature.widthMm * feature.depthMm * feature.heightMm; }
export function validateCncMachiningRelease(input: CncMachiningReleaseInputV1 | null | undefined): CncValidationResult {
  const issues: string[] = []; if (!input || typeof input !== 'object') return { valid: false, issues: ['input_missing'] }; if (input.schema !== CNC_MACHINING_RELEASE_SCHEMA) issues.push('schema_invalid'); if (input.units !== 'mm-rpm-mmMin') issues.push('canonical_units_required'); if (!Number.isSafeInteger(input.revision) || input.revision < 0) issues.push('revision_invalid'); const source = input.source; if (!source || typeof source !== 'object') issues.push('source_binding_missing'); else { if (typeof source.workspaceId !== 'string' || !source.workspaceId.trim() || typeof source.modelId !== 'string' || !source.modelId.trim()) issues.push('source_identity_invalid'); if (typeof source.modelPath !== 'string' || !source.modelPath.trim() || source.modelPath.replaceAll('\\', '/').split('/').includes('..') || source.modelPath.startsWith('/') || /^[A-Za-z]:[\\/]/.test(source.modelPath)) issues.push('source_model_path_invalid'); if (![source.modelSha256, source.toolLibrarySha256, source.rawArtifactSha256, source.contentHash, source.revisionSha256].every(value => typeof value === 'string' && SHA256.test(value))) issues.push('source_hash_invalid'); if (!Number.isSafeInteger(source.revision) || source.revision !== input.revision) issues.push('stale_source_revision'); }
  const stock = input.stock; if (!stock || typeof stock !== 'object' || typeof stock.id !== 'string' || !stock.id.trim() || !positive(stock.widthMm) || !positive(stock.depthMm) || !positive(stock.heightMm) || !point(stock.originMm) || typeof stock.materialId !== 'string' || !stock.materialId.trim()) issues.push(`stock_invalid:${stock?.id}`);
  const setups = arrays<CncSetupV1>(input.setups); const holders = arrays<CncWorkholdingV1>(input.workholding); const tools = arrays<CncToolV1>(input.tools); const features = arrays<CncFeatureV1>(input.features); const operations = arrays<CncOperationV1>(input.operations); for (const [value, label] of [[input.setups, 'setups'], [input.workholding, 'workholding'], [input.tools, 'tools'], [input.features, 'features'], [input.operations, 'operations']] as const) if (!Array.isArray(value)) issues.push(`${label}_array_required`); const all = new Set<string>(); register([stock], 'stock', issues, all); register(setups, 'setup', issues, all); register(holders, 'workholding', issues, all); register(tools, 'tool', issues, all); register(features, 'feature', issues, all); register(operations, 'operation', issues, all); const setupIds = ids(setups); const holderIds = ids(holders); const operationIds = ids(operations); const setupMap = new Map(setups.map(item => [item?.id, item])); const toolMap = new Map(tools.map(item => [item?.id, item])); const featureMap = new Map(features.map(item => [item?.id, item]));
  for (const setup of setups) if (!setup || typeof setup !== 'object' || setup.stockId !== stock?.id || !point(setup.originMm) || arrays<string>(setup.workholdingIds).some(id => !holderIds.has(id)) || arrays<string>(setup.operationIds).some(id => !operationIds.has(id))) issues.push(`setup_invalid_or_ownership:${setup?.id}`);
  for (const holder of holders) { const owner = setupMap.get(holder?.setupId); if (!holder || typeof holder !== 'object' || !setupIds.has(holder.setupId) || !owner?.workholdingIds.includes(holder.id) || !point(holder.originMm) || !positive(holder.widthMm) || !positive(holder.depthMm) || !positive(holder.heightMm) || !nonnegative(holder.clearanceMm) || !inside(holder.originMm, stock) || !inside({ xMm: holder.originMm.xMm + holder.widthMm, yMm: holder.originMm.yMm + holder.depthMm, zMm: holder.originMm.zMm + holder.heightMm }, stock)) issues.push(`workholding_invalid:${holder?.id}`); }
  for (const tool of tools) if (!tool || typeof tool !== 'object' || !['endmill', 'drill'].includes(tool.toolType) || !positive(tool.diameterMm) || !positive(tool.fluteLengthMm) || !positive(tool.overallLengthMm) || tool.fluteLengthMm > tool.overallLengthMm || !positive(tool.maxRpm) || !positive(tool.maxFeedMmMin)) issues.push(`tool_invalid:${tool?.id}`);
  for (const feature of features) if (!feature || typeof feature !== 'object' || !['pocket', 'drill', 'contour'].includes(feature.kind) || feature.stockId !== stock?.id || !positive(feature.widthMm) || !positive(feature.depthMm) || !positive(feature.heightMm) || !point(feature.originMm) || !inside(feature.originMm, stock) || feature.originMm.xMm + feature.widthMm > stock.widthMm + stock.originMm.xMm || feature.originMm.yMm + feature.depthMm > stock.depthMm + stock.originMm.yMm || feature.originMm.zMm + feature.heightMm > stock.heightMm + stock.originMm.zMm) issues.push(`feature_invalid_or_out_of_stock:${feature?.id}`);
  for (const operation of operations) { const setup = setupMap.get(operation?.setupId); const tool = toolMap.get(operation?.toolId); const feature = featureMap.get(operation?.featureId); if (!operation || typeof operation !== 'object' || !setup || !tool || !feature || setup.operationIds.length === 0 || !arrays<string>(setup.operationIds).includes(operation.id) || operation.kind !== feature.kind || !['pocket', 'drill', 'contour'].includes(operation.kind) || !positive(operation.spindleRpm) || operation.spindleRpm > tool.maxRpm || !positive(operation.feedMmMin) || operation.feedMmMin > tool.maxFeedMmMin || !positive(operation.depthMm) || operation.depthMm > feature.heightMm || operation.depthMm > tool.fluteLengthMm || tool.diameterMm > Math.min(feature.widthMm, feature.depthMm) || !Array.isArray(operation.pathPointsMm) || operation.pathPointsMm.length < 2 || operation.pathPointsMm.some((value: unknown) => !point(value)) || !positive(operation.toolpathLengthMm) || !positive(operation.removedVolumeMm3) || operation.toolId === '') { issues.push(`operation_invalid_or_ownership:${operation?.id}`); continue; } let length = 0; for (let index = 1; index < operation.pathPointsMm.length; index += 1) { const part = distance(operation.pathPointsMm[index - 1]!, operation.pathPointsMm[index]!); if (part <= EPSILON) issues.push(`toolpath_zero_length:${operation.id}`); length += part; } if (!equal(length, operation.toolpathLengthMm)) issues.push(`toolpath_length_mismatch:${operation.id}`); if (!equal(operation.removedVolumeMm3, volume({ ...feature, heightMm: operation.depthMm }))) issues.push(`material_removal_mismatch:${operation.id}`); for (const pathPoint of operation.pathPointsMm) { if (!inside(pathPoint, stock)) issues.push(`toolpath_out_of_stock:${operation.id}`); if (!inside(pathPoint, { ...feature, heightMm: operation.depthMm })) issues.push(`toolpath_out_of_feature:${operation.id}`); } for (const holderId of arrays<string>(setup.workholdingIds)) { const holder = holders.find(item => item?.id === holderId); if (holder && operation.pathPointsMm.some(pathPoint => insideExpanded(pathPoint, holder, holder.clearanceMm + tool.diameterMm / 2))) issues.push(`toolpath_workholding_collision:${operation.id}`); } }
  for (const operation of operations) { if (operation?.kind === 'drill' && Array.isArray(operation.pathPointsMm) && operation.pathPointsMm.length >= 2 && operation.pathPointsMm.every(point) && (!operation.pathPointsMm.every(item => equal(item.xMm, operation.pathPointsMm[0]!.xMm) && equal(item.yMm, operation.pathPointsMm[0]!.yMm)) || !equal(Math.abs(operation.pathPointsMm[operation.pathPointsMm.length - 1]!.zMm - operation.pathPointsMm[0]!.zMm), operation.depthMm))) issues.push(`drill_orientation_or_depth_invalid:${operation.id}`); const setup = setupMap.get(operation?.setupId); const tool = toolMap.get(operation?.toolId); if (operation?.kind === 'drill' && tool?.toolType !== 'drill') issues.push(`drill_tool_type_invalid:${operation?.id}`); if (operation?.kind === 'drill' && tool && !equal(operation.removedVolumeMm3, Math.PI * (tool.diameterMm / 2) ** 2 * operation.depthMm)) issues.push(`drill_removed_volume_mismatch:${operation.id}`); if (setup && tool && Array.isArray(operation.pathPointsMm)) for (const holderId of arrays<string>(setup.workholdingIds)) { const holder = holders.find(item => item?.id === holderId); if (holder && operation.pathPointsMm.some((p, i, path) => insideExpanded(p, holder, holder.clearanceMm + tool.diameterMm / 2) || (i > 0 && segmentIntersectsExpandedBox(path[i - 1]!, p, holder, holder.clearanceMm + tool.diameterMm / 2)))) issues.push(`toolpath_swept_workholding_collision:${operation.id}`); } }
  const output = input.output; if (!output || typeof output !== 'object' || output.format !== 'nexyfab-exchange-json' || !['step', 'toolpath-neutral', 'json'].includes(output.targetFormat) || output.revision !== input.revision || typeof output.content !== 'string' || !Number.isSafeInteger(output.bytes) || output.bytes !== Buffer.byteLength(output.content, 'utf8') || !SHA256.test(output.sha256) || sha256(output.content) !== output.sha256) issues.push('output_binding_invalid'); else { try { if (!verifyCncMachiningReadback(input, parseCncMachiningOutput(input)).valid) issues.push('output_readback_invalid'); } catch { issues.push('output_readback_invalid'); } } return { valid: issues.length === 0, issues };
}
function verificationHash(value: Omit<CncParserReadbackV1, 'verificationSha256'>): string { return sha256(JSON.stringify({ ...value, setupIds: [...value.setupIds].sort(), workholdingIds: [...value.workholdingIds].sort(), toolIds: [...value.toolIds].sort(), featureIds: [...value.featureIds].sort(), operationIds: [...value.operationIds].sort() })); }
export function parseCncMachiningOutput(input: CncMachiningReleaseInputV1): CncParserReadbackV1 { let parsed: unknown; try { parsed = JSON.parse(input.output.content) as unknown; } catch { throw new Error('CNC_MACHINING_OUTPUT_JSON_INVALID'); } const keys = ['schema', 'revision', 'sourceWorkspaceId', 'sourceModelId', 'sourceModelSha256', 'sourceToolLibrarySha256', 'sourceRawArtifactSha256', 'sourceContentHash', 'stockId', 'setupIds', 'workholdingIds', 'toolIds', 'featureIds', 'operationIds'] as const; if (!exactKeys(parsed, keys) || parsed.schema !== CNC_MACHINING_EXCHANGE_SCHEMA || !Number.isSafeInteger(parsed.revision) || typeof parsed.sourceWorkspaceId !== 'string' || !parsed.sourceWorkspaceId.trim() || typeof parsed.sourceModelId !== 'string' || !parsed.sourceModelId.trim() || typeof parsed.stockId !== 'string' || !parsed.stockId.trim() || ![parsed.sourceModelSha256, parsed.sourceToolLibrarySha256, parsed.sourceRawArtifactSha256, parsed.sourceContentHash].every(value => typeof value === 'string' && SHA256.test(value)) || !keys.slice(9).every(key => stableIdArray(parsed[key]))) throw new Error('CNC_MACHINING_OUTPUT_SCHEMA_INVALID'); const exchange = parsed as unknown as CncMachiningExchangeV1; const unsigned = { parserId: PARSER_ID, parserSourceSha256: sha256(parseCncMachiningOutput.toString()), sourceWorkspaceId: exchange.sourceWorkspaceId, sourceModelId: exchange.sourceModelId, sourceModelSha256: exchange.sourceModelSha256, sourceToolLibrarySha256: exchange.sourceToolLibrarySha256, sourceRawArtifactSha256: exchange.sourceRawArtifactSha256, sourceContentHash: exchange.sourceContentHash, sourceRevision: exchange.revision, outputSha256: sha256(input.output.content), stockId: exchange.stockId, setupIds: exchange.setupIds, workholdingIds: exchange.workholdingIds, toolIds: exchange.toolIds, featureIds: exchange.featureIds, operationIds: exchange.operationIds } as const; return { ...unsigned, verificationSha256: verificationHash(unsigned) }; }
export function verifyCncMachiningReadback(input: CncMachiningReleaseInputV1, readback: CncParserReadbackV1 | null | undefined): CncReadbackResult { if (!readback || typeof readback !== 'object') return { valid: false, issues: ['readback_missing'] }; const expected = { parserId: PARSER_ID, parserSourceSha256: sha256(parseCncMachiningOutput.toString()), sourceWorkspaceId: input.source.workspaceId, sourceModelId: input.source.modelId, sourceModelSha256: input.source.modelSha256, sourceToolLibrarySha256: input.source.toolLibrarySha256, sourceRawArtifactSha256: input.source.rawArtifactSha256, sourceContentHash: input.source.contentHash, sourceRevision: input.revision, outputSha256: sha256(input.output.content), stockId: input.stock.id, setupIds: input.setups.map(item => item.id), workholdingIds: input.workholding.map(item => item.id), toolIds: input.tools.map(item => item.id), featureIds: input.features.map(item => item.id), operationIds: input.operations.map(item => item.id) } as const; const issues: string[] = []; for (const key of ['parserId', 'parserSourceSha256', 'sourceWorkspaceId', 'sourceModelId', 'sourceModelSha256', 'sourceToolLibrarySha256', 'sourceRawArtifactSha256', 'sourceContentHash', 'sourceRevision', 'outputSha256', 'stockId', 'setupIds', 'workholdingIds', 'toolIds', 'featureIds', 'operationIds'] as const) if (JSON.stringify(readback[key]) !== JSON.stringify(expected[key])) issues.push(`readback_${key}_mismatch`); const { verificationSha256, ...unsigned } = readback; if (verificationSha256 !== verificationHash(unsigned)) issues.push('readback_verification_hash_invalid'); return { valid: issues.length === 0, issues }; }
export function assessCncMachiningRelease(input: CncMachiningReleaseInputV1, readback?: CncParserReadbackV1 | null): CncReleaseAssessment { const validation = validateCncMachiningRelease(input); const internalParserVerified = readback ? verifyCncMachiningReadback(input, readback).valid : false; const independentAttestationVerified = false; const blockers: string[] = [...holdBoundary]; if (!validation.valid) blockers.unshift(...validation.issues); blockers.unshift('independent_parser_attestation_required'); return { schema: CNC_MACHINING_RELEASE_SCHEMA, releaseReady: false, status: 'HOLD', internalParserVerified, independentAttestationVerified, parserVerified: false, blockers, holdBoundary }; }


