import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { assessCncMachiningRelease, CNC_MACHINING_EXCHANGE_SCHEMA, parseCncMachiningOutput, type CncMachiningReleaseInputV1, validateCncMachiningRelease, verifyCncMachiningReadback } from './cncMachiningProcessReleaseContract';

const hash = (value: string): string => createHash('sha256').update(value).digest('hex');
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
function fixture(): CncMachiningReleaseInputV1 {
  const content = JSON.stringify({ schema: CNC_MACHINING_EXCHANGE_SCHEMA, revision: 8, sourceWorkspaceId: 'workspace-cnc-1', sourceModelId: 'cnc-model-1', sourceModelSha256: hash('cnc-model'), sourceToolLibrarySha256: hash('tool-library'), sourceRawArtifactSha256: hash('cnc-raw'), sourceContentHash: hash('cnc-content'), stockId: 'stock-1', setupIds: ['setup-1'], workholdingIds: ['holder-1'], toolIds: ['tool-1'], featureIds: ['feature-pocket'], operationIds: ['operation-pocket'] });
  return {
    schema: 'nexyfab.cnc-machining-release.v1', units: 'mm-rpm-mmMin', revision: 8,
    source: { workspaceId: 'workspace-cnc-1', modelId: 'cnc-model-1', modelPath: 'models/part.step', modelSha256: hash('cnc-model'), toolLibrarySha256: hash('tool-library'), rawArtifactSha256: hash('cnc-raw'), contentHash: hash('cnc-content'), revisionSha256: hash('cnc-revision-8'), revision: 8 },
    stock: { id: 'stock-1', materialId: 'aluminum-6061', originMm: { xMm: 0, yMm: 0, zMm: 0 }, widthMm: 100, depthMm: 100, heightMm: 30 },
    setups: [{ id: 'setup-1', stockId: 'stock-1', originMm: { xMm: 0, yMm: 0, zMm: 0 }, workholdingIds: ['holder-1'], operationIds: ['operation-pocket'] }],
    workholding: [{ id: 'holder-1', setupId: 'setup-1', originMm: { xMm: 80, yMm: 80, zMm: 0 }, widthMm: 10, depthMm: 10, heightMm: 10, clearanceMm: 2 }],
    tools: [{ id: 'tool-1', toolType: 'endmill', diameterMm: 6, fluteLengthMm: 20, overallLengthMm: 50, maxRpm: 10_000, maxFeedMmMin: 2000 }],
    features: [{ id: 'feature-pocket', kind: 'pocket', stockId: 'stock-1', originMm: { xMm: 20, yMm: 20, zMm: 10 }, widthMm: 20, depthMm: 20, heightMm: 5 }],
    operations: [{ id: 'operation-pocket', setupId: 'setup-1', toolId: 'tool-1', featureId: 'feature-pocket', kind: 'pocket', spindleRpm: 5000, feedMmMin: 800, depthMm: 5, pathPointsMm: [{ xMm: 20, yMm: 20, zMm: 10 }, { xMm: 40, yMm: 20, zMm: 10 }, { xMm: 40, yMm: 40, zMm: 10 }, { xMm: 20, yMm: 40, zMm: 10 }], toolpathLengthMm: 60, removedVolumeMm3: 2000 }],
    output: { format: 'nexyfab-exchange-json', targetFormat: 'toolpath-neutral', revision: 8, content, bytes: Buffer.byteLength(content), sha256: hash(content) },
  };
}

describe('CNC machining process release contract', () => {
  it('validates process geometry and actual output readback', () => { const input = fixture(); expect(validateCncMachiningRelease(input)).toEqual({ valid: true, issues: [] }); const readback = parseCncMachiningOutput(input); expect(verifyCncMachiningReadback(input, readback)).toEqual({ valid: true, issues: [] }); const assessment = assessCncMachiningRelease(input, readback); expect(assessment.releaseReady).toBe(false); expect(assessment.blockers).toContain('native_step_toolpath_parser_not_verified'); });
  it('fails closed for stale, ownership and output tamper', () => { const stale = clone(fixture()); stale.revision = 9; expect(validateCncMachiningRelease(stale).issues).toContain('stale_source_revision'); const broken = clone(fixture()); broken.operations[0]!.featureId = 'missing'; expect(validateCncMachiningRelease(broken).issues).toContain('operation_invalid_or_ownership:operation-pocket'); const changed = clone(fixture()); changed.output.content += 'tamper'; expect(validateCncMachiningRelease(changed).issues).toContain('output_binding_invalid'); });
  it('rejects hash-valid forged output identity and parser tamper', () => { const input = fixture(); const readback = parseCncMachiningOutput(input); const tampered = clone(readback); tampered.outputSha256 = hash('tampered'); expect(verifyCncMachiningReadback(input, tampered).valid).toBe(false); const forged = clone(input); const payload = JSON.parse(forged.output.content) as { operationIds: string[] }; payload.operationIds = ['forged']; forged.output.content = JSON.stringify(payload); forged.output.bytes = Buffer.byteLength(forged.output.content); forged.output.sha256 = hash(forged.output.content); expect(validateCncMachiningRelease(forged).issues).toContain('output_readback_invalid'); });
  it('rejects a toolpath outside the feature and holder collision despite valid stock bounds', () => { const outside = clone(fixture()); outside.operations[0]!.pathPointsMm = [{ xMm: 20, yMm: 20, zMm: 10 }, { xMm: 40, yMm: 20, zMm: 10 }, { xMm: 70, yMm: 70, zMm: 10 }, { xMm: 20, yMm: 40, zMm: 10 }]; outside.operations[0]!.toolpathLengthMm = 60 + Math.hypot(30, 50); expect(validateCncMachiningRelease(outside).issues).toContain('toolpath_out_of_feature:operation-pocket'); const holder = clone(fixture()); holder.workholding[0]!.originMm = { xMm: 38, yMm: 18, zMm: 8 }; expect(validateCncMachiningRelease(holder).issues).toContain('toolpath_workholding_collision:operation-pocket'); });
  it('rejects a swept cutter crossing a holder and unsupported drill orientation/depth', () => { const sweep = clone(fixture()); sweep.workholding[0]!.originMm = { xMm: 28, yMm: 18, zMm: 8 }; sweep.operations[0]!.pathPointsMm = [{ xMm: 20, yMm: 20, zMm: 10 }, { xMm: 40, yMm: 20, zMm: 10 }, { xMm: 20, yMm: 40, zMm: 10 }]; sweep.operations[0]!.toolpathLengthMm = 20 + Math.hypot(20, 20); expect(validateCncMachiningRelease(sweep).issues).toContain('toolpath_swept_workholding_collision:operation-pocket'); });
  it('rejects a drill operation paired with an endmill', () => { const input = clone(fixture()); input.operations[0]!.kind = 'drill'; expect(validateCncMachiningRelease(input).issues).toContain('drill_tool_type_invalid:operation-pocket'); });
});
