import { createHash } from 'node:crypto';
import type { GenerationRunState } from './generationRunState';

const SHA256 = /^[a-f0-9]{64}$/;
const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
export const UNBOUND_GENERATION_PROGRAM_SHA256 = '0'.repeat(64);
export interface CommercialGenerationRunBinding { schema: 'nexyfab.commercial-generation-run-binding.v1'; tenantId: string; projectId: string; workspaceId: string; workspaceRevision: number; runId: string; revision: number; programSha256: string; workspaceHeadSha256: string; previousRevision: number; previousHeadSha256: string; previousStateSha256: string; stateSha256: string; generationProgramSha256: string; }
function canonical(value: unknown): string { if (value === null || typeof value === 'boolean' || typeof value === 'string') return JSON.stringify(value); if (typeof value === 'number') { if (!Number.isFinite(value)) throw new Error('NONFINITE_BINDING'); return JSON.stringify(value); } if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if (value && typeof value === 'object') return `{${Object.keys(value as Record<string, unknown>).sort().map(key => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(',')}}`; throw new Error('NONCANONICAL_BINDING'); }
export function commercialGenerationBindingSha256(value: unknown): string { return createHash('sha256').update(canonical(value)).digest('hex'); }
export function validateCommercialGenerationRunBinding(value: CommercialGenerationRunBinding): string[] { const issues: string[] = []; if (value.schema !== 'nexyfab.commercial-generation-run-binding.v1') issues.push('schema'); for (const key of ['tenantId', 'projectId', 'workspaceId', 'runId'] as const) if (!ID.test(value[key])) issues.push(`${key}_invalid`); for (const key of ['programSha256', 'workspaceHeadSha256', 'previousHeadSha256', 'previousStateSha256', 'stateSha256', 'generationProgramSha256'] as const) if (!SHA256.test(value[key])) issues.push(`${key}_invalid`); if (!Number.isSafeInteger(value.workspaceRevision) || value.workspaceRevision < 0) issues.push('workspace_revision_invalid'); const initial = value.revision === 0 && value.previousRevision === -1 && value.previousHeadSha256 === UNBOUND_GENERATION_PROGRAM_SHA256 && value.previousStateSha256 === UNBOUND_GENERATION_PROGRAM_SHA256; const append = Number.isSafeInteger(value.revision) && value.revision > 0 && Number.isSafeInteger(value.previousRevision) && value.previousRevision >= 0 && value.previousRevision < value.revision && SHA256.test(value.previousStateSha256) && value.previousStateSha256 !== UNBOUND_GENERATION_PROGRAM_SHA256; if (!initial && !append) issues.push('revision_chain_invalid'); if (value.programSha256 !== value.generationProgramSha256) issues.push('program_hash_alias_mismatch'); return [...new Set(issues)]; }
export function buildCommercialGenerationRunBinding(input: Omit<CommercialGenerationRunBinding, 'schema' | 'generationProgramSha256' | 'previousStateSha256'> & { generationProgramSha256?: string; previousStateSha256?: string }): CommercialGenerationRunBinding { const value: CommercialGenerationRunBinding = { schema: 'nexyfab.commercial-generation-run-binding.v1', ...input, previousStateSha256: input.previousStateSha256 ?? UNBOUND_GENERATION_PROGRAM_SHA256, generationProgramSha256: input.generationProgramSha256 ?? input.programSha256 }; const issues = validateCommercialGenerationRunBinding(value); if (issues.length) throw new Error(`COMMERCIAL_GENERATION_BINDING_INVALID:${issues.join(',')}`); return value; }
export function assertServerGenerationStateBinding(binding: CommercialGenerationRunBinding, state: GenerationRunState, expected: { tenantId: string; projectId: string; workspaceId: string; workspaceRevision: number; programSha256: string }): void { const issues = validateCommercialGenerationRunBinding(binding); if (issues.length || binding.tenantId !== expected.tenantId || binding.projectId !== expected.projectId || binding.workspaceId !== expected.workspaceId || binding.workspaceRevision !== expected.workspaceRevision || binding.runId !== state.runId || binding.revision !== state.revision || binding.programSha256 !== expected.programSha256 || binding.generationProgramSha256 !== expected.programSha256) throw new Error('COMMERCIAL_GENERATION_BINDING_MISMATCH'); }
