import { describe, expect, it } from 'vitest';
import { buildComplexAssemblyScaleFixture } from './complexAssemblyScaleBenchmark.testFixture';
import { verifyComplexAssemblyScaleBenchmarkBytes } from './complexAssemblyScaleBenchmark';
const encode = (value: unknown) => new TextEncoder().encode(JSON.stringify(value));
describe('complex assembly scale benchmark contract', () => {
  it('recomputes four fixed tiers, cold/warm repetitions, fidelity and approved SLA', () => { const fixture = buildComplexAssemblyScaleFixture(), report = verifyComplexAssemblyScaleBenchmarkBytes(fixture.bytes, fixture.artifacts); expect(report).toMatchObject({ status: 'passed', benchmarkExecutionReady: true, checks: { tierCoverage: true, workflowPolicy: true, environment: true, artifactBytes: true, repetitions: true, zeroErrors: true, deterministicFidelity: true, correctness: true, sla: true }, independentBenchmarkApprovalComplete: false, releaseReady: false }); expect(report.tierSummaries.map(item => item.occurrenceCount)).toEqual([20, 100, 500, 1000]); });
  it('rejects missing tiers, duplicate runs and non-deterministic hashes', () => { const fixture = buildComplexAssemblyScaleFixture(); fixture.benchmark.tiers[1]!.occurrenceCount = 20; fixture.benchmark.tiers[2]!.runs[1]!.runId = fixture.benchmark.tiers[2]!.runs[0]!.runId; fixture.benchmark.tiers[3]!.runs[1]!.hashes.bom = '9'.repeat(64); const report = verifyComplexAssemblyScaleBenchmarkBytes(encode(fixture.benchmark), fixture.artifacts); expect(report.errors).toEqual(expect.arrayContaining(['benchmark_tier_coverage_invalid', 'scale_benchmark_check_failed:repetitions', 'scale_benchmark_check_failed:deterministicFidelity'])); expect(report.benchmarkExecutionReady).toBe(false); });
  it('rejects SLA misses, runtime errors and tampered artifacts', () => { const fixture = buildComplexAssemblyScaleFixture(); fixture.benchmark.tiers[0]!.runs[0]!.metrics.errorCount = 1; fixture.benchmark.tiers[0]!.approvedSla.p95FirstEditableMs = 1; fixture.artifacts.set('timing.jsonl', encode('tampered')); const report = verifyComplexAssemblyScaleBenchmarkBytes(encode(fixture.benchmark), fixture.artifacts); expect(report.errors).toEqual(expect.arrayContaining(['artifact_hash_mismatch:timing.jsonl', 'scale_benchmark_check_failed:zeroErrors', 'scale_benchmark_check_failed:sla'])); expect(report.releaseReady).toBe(false); });
  it('rejects post-dated SLA approval and runs without timing or trace evidence', () => { const fixture = buildComplexAssemblyScaleFixture(); fixture.benchmark.slaApproval.approvedAt = '2026-08-13T00:00:00.000Z'; fixture.benchmark.tiers[0]!.runs[0]!.evidenceArtifactNames = ['assembly-source.nfab']; const report = verifyComplexAssemblyScaleBenchmarkBytes(encode(fixture.benchmark), fixture.artifacts); expect(report.errors).toEqual(expect.arrayContaining(['benchmark_environment_invalid', 'scale_benchmark_check_failed:correctness'])); expect(report.benchmarkExecutionReady).toBe(false); });
});
