import { describe, expect, it } from 'vitest';
import { assertLockedIntentUnchanged, createComplexGenerationCheckpoint, finishComplexGenerationStage, rollbackComplexGenerationTo, startComplexGenerationStage } from './complexGenerationCheckpoint';
const h = (c: string) => c.repeat(64), base = () => createComplexGenerationCheckpoint({ runId: 'r1', caseId: 'c1', promptVersion: 'p1', modelRevision: 'm1', kernelRevision: 'k1', lockedIntent: { 'parts.base.width': h('a') } });
describe('complex generation checkpoints', () => {
  it('enforces ordered stages and hash-bound pass artifacts', () => { let state = base(); expect(() => startComplexGenerationStage(state, 'S1_REQUIREMENTS', [h('b')])).toThrow('previous_stage_not_passed'); state = startComplexGenerationStage(state, 'S0_INPUT', [h('b')]); expect(() => finishComplexGenerationStage(state, 'S0_INPUT', { status: 'pass' })).toThrow('pass_artifact_required'); state = finishComplexGenerationStage(state, 'S0_INPUT', { status: 'pass', outputArtifactHashes: [h('c')] }); expect(state.stages[0]).toMatchObject({ status: 'pass', attempts: [{ attempt: 1 }] }); });
  it('resumes the same failed stage without erasing its evidence trail', () => { let state = startComplexGenerationStage(base(), 'S0_INPUT', [h('b')]); state = finishComplexGenerationStage(state, 'S0_INPUT', { status: 'fail', reasons: ['transport_truncated'] }); state = startComplexGenerationStage(state, 'S0_INPUT', [h('b')]); state = finishComplexGenerationStage(state, 'S0_INPUT', { status: 'pass', outputArtifactHashes: [h('c')] }); expect(state.stages[0]!.attempts.map(item => item.status)).toEqual(['fail', 'pass']); });
  it('rolls downstream state back while retaining attempt history', () => { let state = startComplexGenerationStage(base(), 'S0_INPUT', [h('a')]); state = finishComplexGenerationStage(state, 'S0_INPUT', { status: 'pass', outputArtifactHashes: [h('b')] }); state = startComplexGenerationStage(state, 'S1_REQUIREMENTS', [h('b')]); state = finishComplexGenerationStage(state, 'S1_REQUIREMENTS', { status: 'pass', outputArtifactHashes: [h('c')] }); state = rollbackComplexGenerationTo(state, 'S1_REQUIREMENTS'); expect(state.stages[1]).toMatchObject({ status: 'pending', attempts: [{ status: 'pass' }] }); expect(state.stages[0]!.status).toBe('pass'); });
  it('prevents repair from mutating user-confirmed intent hashes', () => { expect(() => assertLockedIntentUnchanged(base(), { 'parts.base.width': h('z') })).toThrow('locked_intent_modified:parts.base.width'); });
});
