import { describe, expect, it } from 'vitest';
import { buildComplexBenchmarkReportV2, migrateComplexBenchmarkCaseV1, validateComplexBenchmarkV2, type ComplexBenchmarkCaseV2, type ComplexBenchmarkRunV2 } from './complexProductBenchmarkV2';
const hash = (c: string) => c.repeat(64).slice(0, 64), fixture: ComplexBenchmarkCaseV2 = { schema: 'nexyfab.complex-benchmark-case.v2', caseId: 'robot-1', family: 'robot', tier: 'T2', holdoutGroup: 'robot-1', sourceHash: hash('a'), split: 'holdout', assertions: [{ id: 'd1', axis: 'dimensions', required: true, kpiEligible: true, provenance: 'authoritative-cad', tolerancePolicy: 'linear-0.01mm', artifactHashes: [hash('b')] }, { id: 'j1', axis: 'joints', required: true, kpiEligible: true, provenance: 'authoritative-cad', tolerancePolicy: 'axis-0.01deg', artifactHashes: [hash('c')] }] };
const run = (campaign: number, repeat: number, second: 'pass' | 'fail' | 'not_run' = 'pass'): ComplexBenchmarkRunV2 => ({ schema: 'nexyfab.complex-benchmark-run.v2', subject: 'ai_generation', caseId: 'robot-1', campaign, repeat, usedForTuning: false, requiredGatesPassed: true, verified: second === 'pass', falseVerified: false, falseClear: false, destructivePartMerge: false, assertions: [{ assertionId: 'd1', status: 'pass', reason: 'measured', artifactHashes: [hash('d')] }, { assertionId: 'j1', status: second, reason: 'measured or unavailable', artifactHashes: [hash('e')] }] });
describe('complex product benchmark v2', () => {
  it('separates conditional accuracy from governed coverage', () => { const report = buildComplexBenchmarkReportV2([fixture], [run(1, 1, 'not_run')], { minimumCasesPerFamily: 1, repeatsPerCampaign: 1, consecutiveCampaigns: 1, minimumAccuracy: 0.95, minimumCoverage: 0.95, requiredGatePassRate: 1, maximumFalseVerified: 0, maximumFalseClear: 0, maximumDestructivePartMerge: 0 }); const joint = report.overall.axes.find(item => item.axis === 'joints')!; expect(joint).toMatchObject({ expected: 1, measured: 0, notRun: 1, microAccuracy: null, coverage: 0 }); expect(report.eligible).toBe(false); });
  it('requires every campaign/repeat and passes a complete perfect fixture', () => { const runs = [1, 2, 3].flatMap(campaign => [1, 2].map(repeat => run(campaign, repeat))); const report = buildComplexBenchmarkReportV2([fixture], runs, { minimumCasesPerFamily: 1, repeatsPerCampaign: 2, consecutiveCampaigns: 3, minimumAccuracy: 0.95, minimumCoverage: 0.95, requiredGatePassRate: 1, maximumFalseVerified: 0, maximumFalseClear: 0, maximumDestructivePartMerge: 0 }); expect(report.families.find(item => item.group === 'robot')).toMatchObject({ minimumRepeats: 6, campaigns: 3, eligible: true }); expect(report.overall).toMatchObject({ minimumRunAccuracy: 1, runAccuracyStdDev: 0, eligible: true }); });
  it('rejects skewed repeats even when total runs and campaign count are sufficient', () => { const skewed = [run(1, 1), run(1, 2), run(1, 3), run(1, 4), run(2, 1), run(3, 1)]; const report = buildComplexBenchmarkReportV2([fixture], skewed, { minimumCasesPerFamily: 1, repeatsPerCampaign: 2, consecutiveCampaigns: 3, minimumAccuracy: 0.95, minimumCoverage: 0.95, requiredGatePassRate: 1, maximumFalseVerified: 0, maximumFalseClear: 0, maximumDestructivePartMerge: 0 }); expect(report.overall).toMatchObject({ minimumRepeats: 6, campaigns: 3, minimumRepeatsPerCampaign: 1, eligible: false }); expect(report.overall.blockers).toContain('campaign_repeats_below_minimum:1/2'); });
  it('blocks false-clear and destructive merge independently of average accuracy', () => { const bad = run(1, 1); bad.falseClear = true; bad.destructivePartMerge = true; const report = buildComplexBenchmarkReportV2([fixture], [bad], { minimumCasesPerFamily: 1, repeatsPerCampaign: 1, consecutiveCampaigns: 1, minimumAccuracy: 0.95, minimumCoverage: 0.95, requiredGatePassRate: 1, maximumFalseVerified: 0, maximumFalseClear: 0, maximumDestructivePartMerge: 0 }); expect(report.overall.blockers).toEqual(expect.arrayContaining(['false_clear', 'destructive_part_merge'])); });
  it('rejects duplicate executions and verified results without gates', () => { const invalid = run(1, 1); invalid.verified = true; invalid.requiredGatesPassed = false; expect(validateComplexBenchmarkV2([fixture], [invalid, invalid])).toEqual(expect.arrayContaining(['verified_without_gates:robot-1:1:1', 'run_duplicate:robot-1:1:1'])); });
  it('migrates legacy aggregate checks without making them KPI ground truth', () => { const migrated = migrateComplexBenchmarkCaseV1({ caseId: 'old', family: 'robot', holdoutGroup: 'old', sourceHash: hash('f'), sourceKind: 'standard_corpus', split: 'holdout', expectedDefinitions: 2, expectedOccurrences: 3, requiredChecks: ['dimensions', 'features', 'parts', 'assembly', 'step_roundtrip'] }, 'T2'); expect(migrated.assertions.every(item => !item.kpiEligible && item.provenance === 'legacy-unreviewed')).toBe(true); const report = buildComplexBenchmarkReportV2([migrated], [], { minimumCasesPerFamily: 1, repeatsPerCampaign: 1, consecutiveCampaigns: 1, minimumAccuracy: 0.95, minimumCoverage: 0.95, requiredGatePassRate: 1, maximumFalseVerified: 0, maximumFalseClear: 0, maximumDestructivePartMerge: 0 }); expect(report.overall.blockers).toContain('no_kpi_eligible_assertions'); });
  it('never counts reference ground-truth extraction as an AI generation run', () => { const reference = run(1, 1); reference.subject = 'reference_ground_truth'; const report = buildComplexBenchmarkReportV2([fixture], [reference], { minimumCasesPerFamily: 1, repeatsPerCampaign: 1, consecutiveCampaigns: 1, minimumAccuracy: 0.95, minimumCoverage: 0.95, requiredGatePassRate: 1, maximumFalseVerified: 0, maximumFalseClear: 0, maximumDestructivePartMerge: 0 }); expect(report).toMatchObject({ referenceGroundTruthRuns: 1, aiGenerationRuns: 0, eligible: false }); expect(report.overall.runs).toBe(0); });
  it('supports an explicit family promotion scope while retaining portfolio signals', () => { const report = buildComplexBenchmarkReportV2([fixture], [run(1, 1)], { minimumCasesPerFamily: 1, repeatsPerCampaign: 1, consecutiveCampaigns: 1, minimumAccuracy: 0.95, minimumCoverage: 0.95, requiredGatePassRate: 1, maximumFalseVerified: 0, maximumFalseClear: 0, maximumDestructivePartMerge: 0, requiredFamilies: ['robot'] }); expect(report).toMatchObject({ requiredFamilies: ['robot'], eligible: true, coreMechanicalEligible: false, auxiliaryServicesEligible: false }); });
});
