import { createHash } from 'node:crypto';
import type { ComplexAssemblyScaleBenchmark } from './complexAssemblyScaleBenchmark';
const bytes = (value: string) => new TextEncoder().encode(value), hash = (value: Uint8Array) => createHash('sha256').update(value).digest('hex');
export function buildComplexAssemblyScaleFixture() {
  const source = bytes('deterministic assembly source'), timing = bytes('raw timing trace'), sla = bytes('reviewer-approved SLA profile'), artifacts = new Map([['assembly-source.nfab', source], ['timing.jsonl', timing], ['sla-profile.json', sla]]);
  const fixed = (character: string) => character.repeat(64), metrics = (count: number) => ({ importMs: count, firstUsableRenderMs: count * 2, firstEditableMs: count * 2.5, mateSolveMs: count, broadInterferenceMs: count, exactInterferenceMs: count * 3, motionVerificationMs: count * 2, partialRecomputeMs: count, saveResumeMs: count, stepExportMs: count * 2, stepImportMs: count * 2, peakMemoryBytes: 10_000_000 + count * 1000, workerQueuePeak: Math.ceil(count / 100), timeoutCount: 0, errorCount: 0 });
  const tiers = ([20, 100, 500, 1000] as const).map(count => ({ occurrenceCount: count, workflow: count <= 100 ? 'interactive_edit' as const : count === 500 ? 'batch_partial_edit' as const : 'review_streaming' as const, approvedSla: { p95FirstUsableRenderMs: count * 3, p95FirstEditableMs: count * 3, p95PartialRecomputeMs: count * 2, p95ExactInterferenceMs: count * 4, maximumPeakMemoryBytes: 20_000_000, maximumWorkerQueuePeak: 20 }, runs: (['cold', 'warm'] as const).flatMap(mode => [1, 2, 3].map(repeat => ({ runId: `${count}-${mode}-${repeat}`, executionMode: mode, repeat, occurrenceCount: count, metrics: metrics(count), hashes: { hierarchy: fixed('a'), occurrences: fixed('b'), transforms: fixed('c'), bom: fixed('d'), saveResume: fixed('e'), stepRoundtrip: fixed('f') }, correctness: { mateSolvePassed: true as const, exactInterferenceComplete: true as const, motionVerified: true as const, saveResumeMatched: true as const, stepStructurePreserved: true as const, deterministicHashMatched: true as const }, evidenceArtifactNames: ['timing.jsonl'] }))) }));
  const benchmark: ComplexAssemblyScaleBenchmark = { schema: 'nexyfab.complex-assembly-scale-benchmark.v1', benchmarkId: 'scale-rc-1', generatedAt: '2026-08-12T00:00:00.000Z', environment: { sourceCommit: '1'.repeat(40), buildId: 'build-1', kernelId: 'occt-1', workerId: 'worker-1', cpuModel: 'fixed-cpu', logicalCores: 8, memoryBytes: 32_000_000, os: 'test-os', nodeVersion: 'v24', browser: 'chromium-test', concurrency: 2 }, source: { artifactName: 'assembly-source.nfab', sha256: hash(source), deterministicSeed: 'seed-1' }, artifacts: [{ name: 'assembly-source.nfab', sha256: hash(source), kind: 'source', authority: 'benchmark-runner' }, { name: 'timing.jsonl', sha256: hash(timing), kind: 'raw-timing', authority: 'benchmark-runner' }, { name: 'sla-profile.json', sha256: hash(sla), kind: 'sla-profile', authority: 'reviewer-approved' }], tiers, slaApproval: { profileArtifactName: 'sla-profile.json', approvedBy: 'performance-reviewer', approvedAt: '2026-08-11T00:00:00.000Z' } };
  return { benchmark, bytes: bytes(JSON.stringify(benchmark)), artifacts };
}
