export interface ProductRequirementNode { id: string; kind: 'function' | 'envelope' | 'interface' | 'motion' | 'load' | 'manufacturing' | 'material' | 'tolerance' | 'prohibition'; text: string; status: 'confirmed' | 'unresolved' | 'conflict'; sourceRefs: string[]; }
export interface ProductDefinitionNode { id: string; name: string; kind: 'product' | 'subassembly' | 'part'; sourcing: 'make' | 'buy' | 'standard'; independentlyReplaceable: boolean; bodyIntent: { policy: 'single_body' | 'multi_body'; expectedBodies: number | null; }; requirementIds: string[]; }
export interface ProductOccurrenceNode { id: string; definitionId: string; parentOccurrenceId: string | null; quantityIndex: number; }
export interface ProductInterfaceNode { id: string; occurrenceA: string; occurrenceB: string; type: 'fixed' | 'revolute' | 'prismatic' | 'cylindrical' | 'planar' | 'spherical' | 'contact'; datumA: string; datumB: string; requirementIds: string[]; }
export interface ComplexProductArchitecture { schema: 'nexyfab.complex-product-architecture.v1'; requirements: ProductRequirementNode[]; definitions: ProductDefinitionNode[]; occurrences: ProductOccurrenceNode[]; interfaces: ProductInterfaceNode[]; interfaceExpectation?: 'none' | 'fixed' | 'articulated' | 'unknown'; }
export interface ProductArchitectureValidation { status: 'pass' | 'fail' | 'not_run'; errors: string[]; unresolved: string[]; }
export function validateComplexProductArchitecture(value: ComplexProductArchitecture): ProductArchitectureValidation {
  const errors: string[] = [], unresolved: string[] = [], req = new Set<string>(), defs = new Set<string>(), occ = new Set<string>(), iface = new Set<string>();
  for (const item of value.requirements) { if (!item.id || req.has(item.id)) errors.push(`requirement_id_invalid:${item.id}`); req.add(item.id); if (!item.text.trim() || !item.sourceRefs.length) errors.push(`requirement_evidence_missing:${item.id}`); if (item.status !== 'confirmed') unresolved.push(`requirement_${item.status}:${item.id}`); }
  for (const item of value.definitions) { if (!item.id || defs.has(item.id)) errors.push(`definition_id_invalid:${item.id}`); defs.add(item.id); if (item.requirementIds.some(id => !req.has(id))) errors.push(`definition_requirement_missing:${item.id}`); if (item.kind === 'part' && item.bodyIntent.expectedBodies !== null && item.bodyIntent.expectedBodies < 1) errors.push(`part_body_count_invalid:${item.id}`); if (item.bodyIntent.policy === 'single_body' && item.bodyIntent.expectedBodies !== null && item.bodyIntent.expectedBodies !== 1) errors.push(`single_body_intent_conflict:${item.id}`); if (item.bodyIntent.policy === 'multi_body' && item.bodyIntent.expectedBodies === 1) errors.push(`multi_body_intent_conflict:${item.id}`); }
  for (const item of value.occurrences) { if (!item.id || occ.has(item.id)) errors.push(`occurrence_id_invalid:${item.id}`); occ.add(item.id); if (!defs.has(item.definitionId)) errors.push(`occurrence_definition_missing:${item.id}`); if (!Number.isInteger(item.quantityIndex) || item.quantityIndex < 1) errors.push(`occurrence_quantity_index_invalid:${item.id}`); }
  for (const item of value.occurrences) if (item.parentOccurrenceId && !occ.has(item.parentOccurrenceId)) errors.push(`occurrence_parent_missing:${item.id}`);
  const roots = value.occurrences.filter(item => item.parentOccurrenceId === null); if (roots.length !== 1) errors.push(`product_root_count_invalid:${roots.length}`);
  const parent = new Map(value.occurrences.map(item => [item.id, item.parentOccurrenceId])); for (const item of value.occurrences) { const seen = new Set<string>(); let cursor: string | null = item.id; while (cursor) { if (seen.has(cursor)) { errors.push(`occurrence_cycle:${item.id}`); break; } seen.add(cursor); cursor = parent.get(cursor) ?? null; } }
  for (const item of value.interfaces) { if (!item.id || iface.has(item.id)) errors.push(`interface_id_invalid:${item.id}`); iface.add(item.id); if (item.occurrenceA === item.occurrenceB || !occ.has(item.occurrenceA) || !occ.has(item.occurrenceB)) errors.push(`interface_occurrence_invalid:${item.id}`); if (!item.datumA.trim() || !item.datumB.trim()) errors.push(`interface_datum_missing:${item.id}`); if (item.requirementIds.some(id => !req.has(id))) errors.push(`interface_requirement_missing:${item.id}`); }
  const replaceableOccurrences = value.occurrences.filter(item => value.definitions.find(definition => definition.id === item.definitionId)?.independentlyReplaceable); if (new Set(replaceableOccurrences.map(item => item.id)).size !== replaceableOccurrences.length) errors.push('replaceable_occurrence_flattened');
  return { status: errors.length ? 'fail' : unresolved.length ? 'not_run' : 'pass', errors, unresolved };
}
