import { createHash, verify } from 'node:crypto';
import { findExternalVerifier, type ExternalCommercialVerifierRegistry } from './externalCommercialVerifierRegistry';
import type { ExternalCommercialEvidence, ExternalCommercialEvidenceStore } from './externalCommercialEvidenceStore';
import type { DbAdapter } from '../db-adapter';
const SHA256 = /^[a-f0-9]{64}$/;
const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
export const EXTERNAL_EVIDENCE_ROLES = ['command', 'approval', 'execution_journal', 'persistence_receipt', 'verification_receipt', 'common_receipt'] as const;
export type ExternalEvidenceRole = typeof EXTERNAL_EVIDENCE_ROLES[number];
export interface ExternalCommercialVerificationRequest { schema: 'nexyfab.external-commercial-verification-request.v1'; requestId: string; tenantId: string; projectId: string; executionId: string; generationRunId: string; revision: number; modelContentHash: string; targetSha256: string; evidence: readonly { evidenceId: string; role: ExternalEvidenceRole; sha256: string; size: number }[]; evidenceManifestSha256: string; status: 'PENDING' | 'HOLD' | 'VERIFIED'; sequence: number; issuedAt: string; expiresAt: string; }
export interface ExternalVerifierCallback { schema: 'nexyfab.external-commercial-verifier-callback.v1'; requestId: string; claimLeaseId: string; keyId: string; fingerprintSha256: string; requestSha256: string; evidenceManifestSha256: string; finalReceiptSha256: string; executionId: string; generationRunId: string; revision: number; modelContentHash: string; targetSha256: string; sequence: number; issuedAt: string; expiresAt: string; signatureBase64: string; }
export interface ExternalCommercialVerificationRequestStore { put(request: ExternalCommercialVerificationRequest): Promise<{ ok: true } | { ok: false; code: string }>; get(requestId: string, tenantId?: string, projectId?: string): Promise<ExternalCommercialVerificationRequest | undefined>; updateStatus(requestId: string, status: ExternalCommercialVerificationRequest['status'], sequence: number): Promise<boolean>; claim(requestId: string, keyId: string, fingerprintSha256: string, leaseId: string, now: number, leaseExpiresAt: number): Promise<boolean>; }
function canonical(value: unknown): string { if (value === null || typeof value === 'boolean' || typeof value === 'string') return JSON.stringify(value); if (typeof value === 'number') { if (!Number.isFinite(value)) throw new Error('nonfinite'); return JSON.stringify(value); } if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if (value && typeof value === 'object') return `{${Object.keys(value as Record<string, unknown>).sort().map(key => `${JSON.stringify(key)}:${canonical((value as Record<string, unknown>)[key])}`).join(',')}}`; throw new Error('noncanonical'); }
function sha(value: unknown): string { return createHash('sha256').update(canonical(value)).digest('hex'); }
export function canonicalExternalVerifierCallbackPayload(callback: Omit<ExternalVerifierCallback, 'signatureBase64'>): string { return canonical(callback); }
export function externalVerifierCallbackSha256(callback: ExternalVerifierCallback): string { const { signatureBase64: _signature, ...unsigned } = callback; return sha(unsigned); }
export function externalVerificationRequestSha(request: ExternalCommercialVerificationRequest): string { return sha(request); }
export function buildExternalEvidenceManifest(evidence: readonly ExternalCommercialEvidence[]): { manifest: ExternalCommercialVerificationRequest['evidence']; sha256: string } { const manifest = evidence.map(item => ({ evidenceId: item.evidenceId, role: item.role as ExternalEvidenceRole, sha256: item.sha256, size: item.size })).sort((a, b) => a.role.localeCompare(b.role)); return { manifest, sha256: sha(manifest) }; }
export async function createExternalVerificationRequest(input: Omit<ExternalCommercialVerificationRequest, 'schema' | 'evidenceManifestSha256' | 'status' | 'sequence' | 'evidence'> & { evidenceIds: readonly string[]; store: ExternalCommercialEvidenceStore }): Promise<ExternalCommercialVerificationRequest> { const evidence = (await Promise.all(input.evidenceIds.map(id => input.store.get(input.tenantId, input.projectId, id)))).filter((item): item is ExternalCommercialEvidence => !!item); const built = buildExternalEvidenceManifest(evidence); const roles = new Set(built.manifest.map(item => item.role)); const exactRoles = roles.size === EXTERNAL_EVIDENCE_ROLES.length && EXTERNAL_EVIDENCE_ROLES.every(role => roles.has(role)); if (evidence.length !== input.evidenceIds.length || !exactRoles || new Set(input.evidenceIds).size !== input.evidenceIds.length || !ID.test(input.requestId) || !ID.test(input.executionId) || !ID.test(input.generationRunId) || !SHA256.test(input.modelContentHash) || !SHA256.test(input.targetSha256) || !Number.isSafeInteger(input.revision) || input.revision < 0) throw new Error('external_evidence_request_invalid'); if (!Number.isFinite(Date.parse(input.issuedAt)) || !Number.isFinite(Date.parse(input.expiresAt)) || Date.parse(input.expiresAt) <= Date.parse(input.issuedAt)) throw new Error('external_evidence_request_dates_invalid'); if (evidence.some(item => item.executionId !== input.executionId || item.generationRunId !== input.generationRunId || item.revision !== input.revision || item.modelContentHash !== input.modelContentHash || item.targetSha256 !== input.targetSha256)) throw new Error('external_evidence_binding_mismatch'); return { schema: 'nexyfab.external-commercial-verification-request.v1', requestId: input.requestId, tenantId: input.tenantId, projectId: input.projectId, executionId: input.executionId, generationRunId: input.generationRunId, revision: input.revision, modelContentHash: input.modelContentHash, targetSha256: input.targetSha256, evidence: built.manifest, evidenceManifestSha256: built.sha256, status: 'PENDING', sequence: 0, issuedAt: input.issuedAt, expiresAt: input.expiresAt }; }
export function verifyExternalVerifierCallback(request: ExternalCommercialVerificationRequest, callback: ExternalVerifierCallback, registry: ExternalCommercialVerifierRegistry, now: Date): boolean { try { const verifier = findExternalVerifier(registry, callback.keyId, callback.fingerprintSha256); const { signatureBase64: _signature, ...unsigned } = callback; const nowMs = now.getTime(); const issuedMs = Date.parse(callback.issuedAt); const expiresMs = Date.parse(callback.expiresAt); const requestIssuedMs = Date.parse(request.issuedAt); const requestExpiresMs = Date.parse(request.expiresAt); return !!verifier && callback.schema === 'nexyfab.external-commercial-verifier-callback.v1' && ID.test(callback.claimLeaseId) && SHA256.test(callback.requestSha256) && SHA256.test(callback.evidenceManifestSha256) && SHA256.test(callback.finalReceiptSha256) && SHA256.test(callback.modelContentHash) && SHA256.test(callback.targetSha256) && callback.requestId === request.requestId && callback.requestSha256 === sha(request) && callback.evidenceManifestSha256 === request.evidenceManifestSha256 && callback.executionId === request.executionId && callback.generationRunId === request.generationRunId && callback.revision === request.revision && callback.modelContentHash === request.modelContentHash && callback.targetSha256 === request.targetSha256 && callback.sequence === request.sequence + 1 && Number.isFinite(issuedMs) && Number.isFinite(expiresMs) && Number.isFinite(requestIssuedMs) && Number.isFinite(requestExpiresMs) && issuedMs >= requestIssuedMs && expiresMs <= requestExpiresMs && issuedMs <= nowMs && expiresMs > nowMs && expiresMs > issuedMs && typeof callback.signatureBase64 === 'string' && callback.signatureBase64.length <= 256 && verify(null, Buffer.from(canonical(unsigned)), verifier.publicKeyPem, Buffer.from(callback.signatureBase64, 'base64')); } catch { return false; } }

export function createDbExternalCommercialVerificationRequestStore(db: DbAdapter): ExternalCommercialVerificationRequestStore {
  return {
    async put(request) {
      if (db.backend !== 'postgres') return { ok: false, code: 'COMMERCIAL_POSTGRES_REQUIRED' };
      const requestSha256 = sha(request);
      const old = await db.queryOne<Record<string, unknown>>('SELECT request_sha256, request_json FROM nf_external_commercial_verification_requests WHERE request_id = ?', request.requestId);
      if (old) return old.request_sha256 === requestSha256 && old.request_json === canonical(request) ? { ok: true } : { ok: false, code: 'REQUEST_IMMUTABLE_CONFLICT' };
      try { await db.execute('INSERT INTO nf_external_commercial_verification_requests (request_id, tenant_id, project_id, execution_id, generation_run_id, revision, model_content_hash, target_sha256, evidence_manifest_sha256, request_sha256, request_json, status, sequence, issued_at, expires_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', request.requestId, request.tenantId, request.projectId, request.executionId, request.generationRunId, request.revision, request.modelContentHash, request.targetSha256, request.evidenceManifestSha256, requestSha256, canonical(request), request.status, request.sequence, Date.parse(request.issuedAt), Date.parse(request.expiresAt), Date.now(), Date.now()); return { ok: true }; } catch { return { ok: false, code: 'REQUEST_IMMUTABLE_CONFLICT' }; }
    },
    async get(requestId, tenantId, projectId) {
      if (db.backend !== 'postgres') return undefined;
      const row = await db.queryOne<Record<string, unknown>>('SELECT request_json, request_sha256, status, sequence FROM nf_external_commercial_verification_requests WHERE request_id = ?' + (tenantId && projectId ? ' AND tenant_id = ? AND project_id = ?' : ''), ...(tenantId && projectId ? [requestId, tenantId, projectId] : [requestId]));
      if (!row || typeof row.request_json !== 'string' || typeof row.request_sha256 !== 'string') return undefined;
      try { const parsed = JSON.parse(row.request_json) as ExternalCommercialVerificationRequest; if (parsed.schema !== 'nexyfab.external-commercial-verification-request.v1' || row.request_sha256 !== sha(parsed) || !['PENDING', 'HOLD', 'VERIFIED'].includes(String(row.status)) || !Number.isSafeInteger(Number(row.sequence)) || Number(row.sequence) < parsed.sequence) return undefined; return { ...parsed, status: String(row.status) as ExternalCommercialVerificationRequest['status'], sequence: Number(row.sequence) }; } catch { return undefined; }
    },
    async updateStatus(requestId, status, sequence) { if (db.backend !== 'postgres') return false; const result = await db.execute('UPDATE nf_external_commercial_verification_requests SET status = ?, sequence = ?, updated_at = ? WHERE request_id = ? AND sequence < ?', status, sequence, Date.now(), requestId, sequence); return result.changes === 1; },
    async claim(requestId, keyId, fingerprintSha256, leaseId, now, leaseExpiresAt) { if (db.backend !== 'postgres') return false; try { const result = await db.execute('INSERT INTO nf_external_commercial_verifier_claims (request_id, verifier_key_id, verifier_fingerprint_sha256, lease_id, claimed_at, lease_expires_at, status) VALUES (?, ?, ?, ?, ?, ?, ?)', requestId, keyId, fingerprintSha256, leaseId, now, leaseExpiresAt, 'CLAIMED'); return result.changes === 1; } catch { return false; } },
  };
}
