import type { MepRoutingObstacle } from './mepRouting3d';
type V2 = [number, number]; type V3 = [number, number, number];
export interface GravityDrainRouteRequest { id: string; startMm: V3; endMm: V3; gridMm: number; clearanceMm: number; minimumSlopePercent: number; maximumSlopePercent: number; obstacles: MepRoutingObstacle[]; maxVisitedNodes?: number }
export interface GravityDrainRouteResult { status: 'routed' | 'failed'; pathMm: V3[]; planLengthMm?: number; slopePercent?: number; visitedNodes: number; reason?: string; method: 'conservative_projected_astar_uniform_slope' }
const key = (point: V2) => point.join(','), manhattan = (a: V2, b: V2) => Math.abs(a[0] - b[0]) + Math.abs(a[1] - b[1]), aligned = (value: number, grid: number) => Math.round(value / grid) * grid;
const blocked = (point: V2, obstacle: MepRoutingObstacle, clearance: number) => point[0] >= obstacle.minMm[0] - clearance && point[0] <= obstacle.maxMm[0] + clearance && point[1] >= obstacle.minMm[1] - clearance && point[1] <= obstacle.maxMm[1] + clearance;
function segmentRectIntersects(a: V2, b: V2, obstacle: MepRoutingObstacle, clearance: number): boolean { let low = 0, high = 1; const min: V2 = [obstacle.minMm[0] - clearance, obstacle.minMm[1] - clearance], max: V2 = [obstacle.maxMm[0] + clearance, obstacle.maxMm[1] + clearance]; for (let axis = 0; axis < 2; axis++) { const delta = b[axis]! - a[axis]!; if (Math.abs(delta) < 1e-12) { if (a[axis]! < min[axis]! || a[axis]! > max[axis]!) return false; continue; } let first = (min[axis]! - a[axis]!) / delta, second = (max[axis]! - a[axis]!) / delta; if (first > second) [first, second] = [second, first]; low = Math.max(low, first); high = Math.min(high, second); if (low >= high) return false; } return true; }
function compress(path: V2[]): V2[] { return path.filter((point, index) => index === 0 || index === path.length - 1 || (path[index - 1]![0] === point[0]) !== (point[0] === path[index + 1]![0])); }

/** Routes in plan conservatively around every projected obstacle, then assigns one continuous gravity slope. */
export function routeGravityDrain(request: GravityDrainRouteRequest): GravityDrainRouteResult {
  if (!(request.gridMm > 0) || request.clearanceMm < 0 || !(request.minimumSlopePercent > 0) || request.maximumSlopePercent < request.minimumSlopePercent || ![...request.startMm, ...request.endMm, request.gridMm, request.clearanceMm, request.minimumSlopePercent, request.maximumSlopePercent].every(Number.isFinite)) throw new Error('Gravity drainage routing inputs are invalid.');
  const drop = request.startMm[2] - request.endMm[2]; if (!(drop > 0)) return { status: 'failed', pathMm: [], visitedNodes: 0, reason: 'Drain endpoint must be below the start point.', method: 'conservative_projected_astar_uniform_slope' };
  const start: V2 = [aligned(request.startMm[0], request.gridMm), aligned(request.startMm[1], request.gridMm)], goal: V2 = [aligned(request.endMm[0], request.gridMm), aligned(request.endMm[1], request.gridMm)];
  if (request.obstacles.some(item => blocked(start, item, request.clearanceMm) || blocked(goal, item, request.clearanceMm))) return { status: 'failed', pathMm: [], visitedNodes: 0, reason: 'A drain endpoint is inside projected obstacle clearance.', method: 'conservative_projected_astar_uniform_slope' };
  const margin = request.gridMm * 8 + request.clearanceMm, xs = [start[0], goal[0], ...request.obstacles.flatMap(item => [item.minMm[0], item.maxMm[0]])], ys = [start[1], goal[1], ...request.obstacles.flatMap(item => [item.minMm[1], item.maxMm[1]])], min: V2 = [aligned(Math.min(...xs) - margin, request.gridMm), aligned(Math.min(...ys) - margin, request.gridMm)], max: V2 = [aligned(Math.max(...xs) + margin, request.gridMm), aligned(Math.max(...ys) + margin, request.gridMm)];
  const open = new Set([key(start)]), points = new Map([[key(start), start]]), costs = new Map([[key(start), 0]]), previous = new Map<string, string>(), directions: V2[] = [[1, 0], [-1, 0], [0, 1], [0, -1]], limit = request.maxVisitedNodes ?? 100_000; let visited = 0, raw: V2[] | undefined;
  while (open.size && visited < limit) { let currentKey = ''; open.forEach(candidate => { if (!currentKey || costs.get(candidate)! + manhattan(points.get(candidate)!, goal) < costs.get(currentKey)! + manhattan(points.get(currentKey)!, goal)) currentKey = candidate; }); const current = points.get(currentKey)!; open.delete(currentKey); visited++; if (currentKey === key(goal)) { raw = []; let cursor: string | undefined = currentKey; while (cursor) { raw.unshift(points.get(cursor)!); cursor = previous.get(cursor); } break; } for (const direction of directions) { const next: V2 = [current[0] + direction[0] * request.gridMm, current[1] + direction[1] * request.gridMm]; if (next[0] < min[0] || next[0] > max[0] || next[1] < min[1] || next[1] > max[1] || request.obstacles.some(item => blocked(next, item, request.clearanceMm) || segmentRectIntersects(current, next, item, request.clearanceMm))) continue; const nextKey = key(next), candidate = costs.get(currentKey)! + request.gridMm; if (candidate < (costs.get(nextKey) ?? Infinity)) { costs.set(nextKey, candidate); previous.set(nextKey, currentKey); points.set(nextKey, next); open.add(nextKey); } } }
  if (!raw) return { status: 'failed', pathMm: [], visitedNodes: visited, reason: visited >= limit ? 'Routing node budget exhausted.' : 'No projected clearance route exists.', method: 'conservative_projected_astar_uniform_slope' };
  const planLengthMm = raw.slice(1).reduce((sum, point, index) => sum + manhattan(point, raw![index]!), 0), slopePercent = drop / planLengthMm * 100;
  if (slopePercent < request.minimumSlopePercent || slopePercent > request.maximumSlopePercent) return { status: 'failed', pathMm: [], planLengthMm, slopePercent, visitedNodes: visited, reason: 'Available elevation drop does not satisfy governed slope limits on the shortest route.', method: 'conservative_projected_astar_uniform_slope' };
  let progressed = 0; const plan = compress(raw), pathMm = plan.map((point, index) => { if (index) progressed += manhattan(plan[index - 1]!, point); return [point[0], point[1], request.startMm[2] - progressed / planLengthMm * drop] as V3; }); pathMm[0] = [...request.startMm]; pathMm[pathMm.length - 1] = [...request.endMm];
  return { status: 'routed', pathMm, planLengthMm, slopePercent, visitedNodes: visited, method: 'conservative_projected_astar_uniform_slope' };
}
