import { createHash } from 'node:crypto';

export const HVAC_DUCT_ROUTE_RELEASE_SCHEMA = 'nexyfab.hvac-duct-route-release.v1' as const;
export const HVAC_DUCT_ROUTE_EXCHANGE_SCHEMA = 'nexyfab.hvac-duct-route-exchange.v1' as const;
const PARSER_ID = 'nexyfab.hvac-duct-route-independent-parser.v1' as const;
const SHA256 = /^[a-f0-9]{64}$/;
const EPSILON = 1e-8;

export interface HvacSourceBindingV1 { workspaceId: string; modelId: string; modelPath: string; modelSha256: string; contentHash: string; rawArtifactSha256: string; revisionSha256: string; revision: number; }
export interface HvacPointMmV1 { xMm: number; yMm: number; zMm: number; }
export type HvacSectionShape = 'rectangular' | 'round';
export interface HvacPortV1 { id: string; ownerType: 'segment' | 'fitting' | 'equipment'; ownerId: string; positionMm: HvacPointMmV1; direction: HvacPointMmV1; connectedPortIds: readonly string[]; shape: HvacSectionShape; widthMm?: number; heightMm?: number; diameterMm?: number; }
export interface HvacRouteV1 { id: string; segmentIds: readonly string[]; fittingIds: readonly string[]; portIds: readonly string[]; maxSupportSpacingMm: number; minimumClearanceMm: number; }
export interface HvacDuctSegmentV1 { id: string; routeId: string; startPortId: string; endPortId: string; shape: HvacSectionShape; widthMm?: number; heightMm?: number; diameterMm?: number; centerlineMm: readonly HvacPointMmV1[]; lengthMm: number; flowM3s: number; pressureLossPa: number; }
export type HvacFittingType = 'elbow' | 'transition' | 'tee';
export interface HvacFittingV1 { id: string; routeId: string; type: HvacFittingType; portIds: readonly string[]; lengthMm: number; pressureLossPa: number; }
export interface HvacSupportV1 { id: string; segmentId: string; positionAlongMm: number; spacingMm: number; supportType: string; }
export interface HvacClearanceZoneV1 { id: string; ownerId: string; originMm: HvacPointMmV1; widthMm: number; depthMm: number; heightMm: number; }
export interface HvacOutputV1 { format: 'nexyfab-exchange-json'; targetFormat: 'ifc-neutral' | 'step' | 'json'; revision: number; content: string; bytes: number; sha256: string; }
export interface HvacExchangeV1 { schema: typeof HVAC_DUCT_ROUTE_EXCHANGE_SCHEMA; revision: number; sourceWorkspaceId: string; sourceModelId: string; sourceModelSha256: string; sourceContentHash: string; sourceRawArtifactSha256: string; routeIds: string[]; portIds: string[]; segmentIds: string[]; fittingIds: string[]; supportIds: string[]; }
export interface HvacDuctRouteReleaseInputV1 { schema: typeof HVAC_DUCT_ROUTE_RELEASE_SCHEMA; units: 'mm-Pa-m3s'; revision: number; source: HvacSourceBindingV1; routes: readonly HvacRouteV1[]; ports: readonly HvacPortV1[]; segments: readonly HvacDuctSegmentV1[]; fittings: readonly HvacFittingV1[]; supports: readonly HvacSupportV1[]; clearanceZones: readonly HvacClearanceZoneV1[]; output: HvacOutputV1; }
export interface HvacParserReadbackV1 { parserId: typeof PARSER_ID; parserSourceSha256: string; sourceWorkspaceId: string; sourceModelId: string; sourceModelSha256: string; sourceContentHash: string; sourceRawArtifactSha256: string; sourceRevision: number; outputSha256: string; routeIds: readonly string[]; portIds: readonly string[]; segmentIds: readonly string[]; fittingIds: readonly string[]; supportIds: readonly string[]; verificationSha256: string; }
export interface HvacValidationResult { valid: boolean; issues: string[]; }
export interface HvacReleaseAssessment { schema: typeof HVAC_DUCT_ROUTE_RELEASE_SCHEMA; releaseReady: false; status: 'HOLD'; internalParserVerified: boolean; independentAttestationVerified: boolean; /** @deprecated Use internalParserVerified. */ parserVerified: boolean; blockers: string[]; holdBoundary: readonly string[]; }
export interface HvacReadbackResult { valid: boolean; issues: string[]; }

const holdBoundary = ['native_ifc_step_parser_not_verified', 'tab_measurement_not_run', 'energy_and_air_balance_not_run', 'fire_and_building_code_authority_not_verified', 'manufacturing_cam_and_native_ifc_not_verified', 'field_inspection_receipt_not_available'] as const;
const sha256 = (value: string): string => createHash('sha256').update(value, 'utf8').digest('hex');
const finite = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value);
const positive = (value: unknown): value is number => finite(value) && value > 0;
const nonnegative = (value: unknown): value is number => finite(value) && value >= 0;
const equal = (a: number, b: number): boolean => Math.abs(a - b) <= Math.max(EPSILON, Math.max(Math.abs(a), Math.abs(b)) * 1e-9);
const arrays = <T>(value: unknown): readonly T[] => Array.isArray(value) ? value as readonly T[] : [];
const point = (value: unknown): value is HvacPointMmV1 => Boolean(value && typeof value === 'object' && finite((value as HvacPointMmV1).xMm) && finite((value as HvacPointMmV1).yMm) && finite((value as HvacPointMmV1).zMm));
const distance = (a: HvacPointMmV1, b: HvacPointMmV1): number => Math.hypot(a.xMm - b.xMm, a.yMm - b.yMm, a.zMm - b.zMm);
const routeBounds = (segment: HvacDuctSegmentV1): { originMm: HvacPointMmV1; widthMm: number; depthMm: number; heightMm: number } => {
  const r = segment.shape === 'rectangular' ? Math.max(segment.widthMm ?? 0, segment.heightMm ?? 0) / 2 : (segment.diameterMm ?? 0) / 2; const radius = { x: r, y: r, z: r };
  const points = segment.centerlineMm;
  const minX = Math.min(...points.map(p => p.xMm)) - radius.x; const minY = Math.min(...points.map(p => p.yMm)) - radius.y; const minZ = Math.min(...points.map(p => p.zMm)) - radius.z;
  const maxX = Math.max(...points.map(p => p.xMm)) + radius.x; const maxY = Math.max(...points.map(p => p.yMm)) + radius.y; const maxZ = Math.max(...points.map(p => p.zMm)) + radius.z;
  return { originMm: { xMm: minX, yMm: minY, zMm: minZ }, widthMm: maxX - minX, depthMm: maxY - minY, heightMm: maxZ - minZ };
};
const ids = (values: readonly { id?: unknown }[]): Set<string> => new Set(values.map(value => value?.id).filter((id): id is string => typeof id === 'string'));
const exactKeys = (value: unknown, keys: readonly string[]): value is Record<string, unknown> => Boolean(value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === keys.length && Object.keys(value).every(key => keys.includes(key)));
const stableIdArray = (value: unknown): value is string[] => Array.isArray(value) && value.every(id => typeof id === 'string' && id.trim() === id && id.length > 0) && new Set(value).size === value.length;
function register(values: readonly { id?: unknown }[], label: string, issues: string[], all: Set<string>): void { for (const value of values) { const id = value?.id; if (typeof id !== 'string' || !id.trim() || all.has(id)) issues.push(`${label}_id_invalid:${String(id)}`); else all.add(id); } }
function sectionArea(item: { shape?: HvacSectionShape; widthMm?: number; heightMm?: number; diameterMm?: number }): number { return item.shape === 'rectangular' && positive(item.widthMm) && positive(item.heightMm) ? item.widthMm * item.heightMm : item.shape === 'round' && positive(item.diameterMm) ? Math.PI * (item.diameterMm / 2) ** 2 : 0; }
function pressureLoss(lengthMm: number, flowM3s: number, areaMm2: number): number { return lengthMm * flowM3s ** 2 / areaMm2; }
function boxOverlap(a: HvacClearanceZoneV1, b: { originMm: HvacPointMmV1; widthMm: number; depthMm: number; heightMm: number }): boolean { return a.originMm.xMm < b.originMm.xMm + b.widthMm - EPSILON && a.originMm.xMm + a.widthMm > b.originMm.xMm + EPSILON && a.originMm.yMm < b.originMm.yMm + b.depthMm - EPSILON && a.originMm.yMm + a.depthMm > b.originMm.yMm + EPSILON && a.originMm.zMm < b.originMm.zMm + b.heightMm - EPSILON && a.originMm.zMm + a.heightMm > b.originMm.zMm + EPSILON; }

export function validateHvacDuctRouteRelease(input: HvacDuctRouteReleaseInputV1 | null | undefined): HvacValidationResult {
  const issues: string[] = []; if (!input || typeof input !== 'object') return { valid: false, issues: ['input_missing'] };
  if (input.schema !== HVAC_DUCT_ROUTE_RELEASE_SCHEMA) issues.push('schema_invalid'); if (input.units !== 'mm-Pa-m3s') issues.push('canonical_units_required'); if (!Number.isSafeInteger(input.revision) || input.revision < 0) issues.push('revision_invalid');
  const source = input.source; if (!source || typeof source !== 'object') issues.push('source_binding_missing'); else { if (typeof source.workspaceId !== 'string' || !source.workspaceId.trim() || typeof source.modelId !== 'string' || !source.modelId.trim()) issues.push('source_identity_invalid'); if (typeof source.modelPath !== 'string' || !source.modelPath.trim() || source.modelPath.replaceAll('\\', '/').split('/').includes('..') || source.modelPath.startsWith('/') || /^[A-Za-z]:[\\/]/.test(source.modelPath)) issues.push('source_model_path_invalid'); if (![source.modelSha256, source.contentHash, source.rawArtifactSha256, source.revisionSha256].every(value => typeof value === 'string' && SHA256.test(value))) issues.push('source_hash_invalid'); if (!Number.isSafeInteger(source.revision) || source.revision !== input.revision) issues.push('stale_source_revision'); }
  const routes = arrays<HvacRouteV1>(input.routes); const ports = arrays<HvacPortV1>(input.ports); const segments = arrays<HvacDuctSegmentV1>(input.segments); const fittings = arrays<HvacFittingV1>(input.fittings); const supports = arrays<HvacSupportV1>(input.supports); const zones = arrays<HvacClearanceZoneV1>(input.clearanceZones);
  for (const [value, label] of [[input.routes, 'routes'], [input.ports, 'ports'], [input.segments, 'segments'], [input.fittings, 'fittings'], [input.supports, 'supports'], [input.clearanceZones, 'clearance_zones']] as const) if (!Array.isArray(value)) issues.push(`${label}_array_required`);
  const all = new Set<string>(); register(routes, 'route', issues, all); register(ports, 'port', issues, all); register(segments, 'segment', issues, all); register(fittings, 'fitting', issues, all); register(supports, 'support', issues, all); register(zones, 'clearance_zone', issues, all);
  const routeIds = ids(routes); const portIds = ids(ports); const segmentIds = ids(segments); const fittingIds = ids(fittings); const routeMap = new Map(routes.map(item => [item?.id, item])); const portMap = new Map(ports.map(item => [item?.id, item])); const segmentMap = new Map(segments.map(item => [item?.id, item]));
  for (const route of routes) if (!route || typeof route !== 'object' || !positive(route.maxSupportSpacingMm) || !nonnegative(route.minimumClearanceMm) || arrays<string>(route.segmentIds).length === 0 || arrays<string>(route.segmentIds).some(id => !segmentIds.has(id)) || arrays<string>(route.fittingIds).some(id => !fittingIds.has(id)) || arrays<string>(route.portIds).some(id => !portIds.has(id))) issues.push(`route_invalid:${route?.id}`);
  for (const port of ports) { const ownerValid = port?.ownerType === 'segment' ? segmentIds.has(port.ownerId) : port?.ownerType === 'fitting' ? fittingIds.has(port.ownerId) : port?.ownerType === 'equipment' && typeof port.ownerId === 'string' && port.ownerId.trim().length > 0; if (!port || typeof port !== 'object' || !ownerValid || !point(port.positionMm) || !point(port.direction) || distance({ xMm: 0, yMm: 0, zMm: 0 }, port.direction) <= EPSILON || !['rectangular', 'round'].includes(port.shape) || sectionArea(port) <= 0 || arrays<string>(port.connectedPortIds).some(id => !portIds.has(id))) issues.push(`port_invalid:${port?.id}`); for (const connected of arrays<string>(port?.connectedPortIds)) { if (!arrays<string>(portMap.get(connected)?.connectedPortIds).includes(port?.id)) issues.push(`port_bidirectional_ownership_invalid:${port?.id}`); const other = portMap.get(connected); if (other && point(port.positionMm) && point(other.positionMm) && distance(port.positionMm, other.positionMm) > EPSILON) issues.push(`port_spatial_continuity_invalid:${port?.id}`); } }
  for (const segment of segments) {
    const start = portMap.get(segment?.startPortId); const end = portMap.get(segment?.endPortId); const area = sectionArea(segment ?? {});
    const startOwned = start && ((start.ownerType === 'segment' && start.ownerId === segment?.id) || (start.ownerType === 'fitting' && arrays<string>(routeMap.get(segment?.routeId)?.fittingIds).includes(start.ownerId)));
    const endOwned = end && ((end.ownerType === 'segment' && end.ownerId === segment?.id) || (end.ownerType === 'fitting' && arrays<string>(routeMap.get(segment?.routeId)?.fittingIds).includes(end.ownerId)));
    if (!segment || typeof segment !== 'object' || !routeIds.has(segment.routeId) || !routeMap.get(segment.routeId)?.segmentIds.includes(segment.id) || !routeMap.get(segment.routeId)?.portIds.includes(segment.startPortId) || !routeMap.get(segment.routeId)?.portIds.includes(segment.endPortId) || !start || !end || segment.startPortId === segment.endPortId || !startOwned || !endOwned || !['rectangular', 'round'].includes(segment.shape) || area <= 0 || !Array.isArray(segment.centerlineMm) || segment.centerlineMm.length < 2 || segment.centerlineMm.some((value: unknown) => !point(value)) || !positive(segment.lengthMm) || !finite(segment.flowM3s) || !finite(segment.pressureLossPa)) { issues.push(`segment_invalid_or_dangling:${segment?.id}`); continue; }
    if (segment.flowM3s <= 0) issues.push(`segment_flow_invalid:${segment.id}`); if (segment.pressureLossPa < 0) issues.push(`segment_pressure_loss_invalid:${segment.id}`);
    let length = 0; for (let index = 1; index < segment.centerlineMm.length; index += 1) { const a = segment.centerlineMm[index - 1]!, b = segment.centerlineMm[index]!; const part = distance(a, b); if (part <= EPSILON) issues.push(`segment_zero_length:${segment.id}`); length += part; }
    if (!equal(length, segment.lengthMm)) issues.push(`segment_length_mismatch:${segment.id}`); if (!equal(segment.pressureLossPa, pressureLoss(segment.lengthMm, Math.abs(segment.flowM3s), area))) issues.push(`segment_pressure_loss_mismatch:${segment.id}`); if (!equal(distance(start.positionMm, segment.centerlineMm[0]!), 0) || !equal(distance(end.positionMm, segment.centerlineMm[segment.centerlineMm.length - 1]!), 0)) issues.push(`segment_port_geometry_mismatch:${segment.id}`); const travel = { xMm: end.positionMm.xMm - start.positionMm.xMm, yMm: end.positionMm.yMm - start.positionMm.yMm, zMm: end.positionMm.zMm - start.positionMm.zMm }; const directionLength = distance({ xMm: 0, yMm: 0, zMm: 0 }, start.direction); if (travel.xMm * start.direction.xMm + travel.yMm * start.direction.yMm + travel.zMm * start.direction.zMm <= EPSILON * directionLength) issues.push(`segment_flow_direction_invalid:${segment.id}`);
  }
  for (const segment of segments) { const start = portMap.get(segment?.startPortId); const end = portMap.get(segment?.endPortId); const points = segment?.centerlineMm; if (!start || !end || !Array.isArray(points) || points.length < 2 || !point(points[0]) || !point(points[1]) || !point(points[points.length - 2]) || !point(points[points.length - 1])) continue; const first = { xMm: points[1]!.xMm - points[0]!.xMm, yMm: points[1]!.yMm - points[0]!.yMm, zMm: points[1]!.zMm - points[0]!.zMm }; const last = { xMm: points[points.length - 1]!.xMm - points[points.length - 2]!.xMm, yMm: points[points.length - 1]!.yMm - points[points.length - 2]!.yMm, zMm: points[points.length - 1]!.zMm - points[points.length - 2]!.zMm }; if (first.xMm * start.direction.xMm + first.yMm * start.direction.yMm + first.zMm * start.direction.zMm <= EPSILON || last.xMm * end.direction.xMm + last.yMm * end.direction.yMm + last.zMm * end.direction.zMm <= EPSILON) issues.push(`port_direction_tangent_invalid:${segment.id}`); }
  for (const fitting of fittings) { const route = routeMap.get(fitting?.routeId); if (!fitting || typeof fitting !== 'object' || !route || !route.fittingIds.includes(fitting.id) || !['elbow', 'transition', 'tee'].includes(fitting.type) || arrays<string>(fitting.portIds).length < 2 || arrays<string>(fitting.portIds).some(id => !portIds.has(id) || !route.portIds.includes(id) || portMap.get(id)?.ownerType !== 'fitting' || portMap.get(id)?.ownerId !== fitting.id) || !positive(fitting.lengthMm) || !nonnegative(fitting.pressureLossPa)) issues.push(`fitting_invalid_or_dangling:${fitting?.id}`); }
  for (const support of supports) { const segment = segmentMap.get(support?.segmentId); const route = segment ? routeMap.get(segment.routeId) : undefined; if (!segment || !route || !finite(support.positionAlongMm) || support.positionAlongMm < 0 || support.positionAlongMm > segment.lengthMm || !positive(support.spacingMm) || typeof support.supportType !== 'string' || !support.supportType.trim() || support.spacingMm > route.maxSupportSpacingMm) issues.push(`support_spacing_invalid:${support?.id}`); }
  for (const segment of segments) { const route = routeMap.get(segment?.routeId); if (!route) continue; const positions = supports.filter(support => support?.segmentId === segment.id && finite(support.positionAlongMm)).map(support => support.positionAlongMm).sort((a, b) => a - b); if (positions.length === 0) issues.push(`support_missing:${segment.id}`); else { if (positions[0]! > route.maxSupportSpacingMm + EPSILON) issues.push(`support_endpoint_gap_exceeded:${segment.id}:start`); if (segment.lengthMm - positions[positions.length - 1]! > route.maxSupportSpacingMm + EPSILON) issues.push(`support_endpoint_gap_exceeded:${segment.id}:end`); for (let index = 1; index < positions.length; index += 1) if (positions[index]! - positions[index - 1]! > route.maxSupportSpacingMm + EPSILON) issues.push(`support_gap_exceeded:${segment.id}`); } }
  for (const zone of zones) if (!zone || typeof zone !== 'object' || !all.has(zone.ownerId) || !point(zone.originMm) || !positive(zone.widthMm) || !positive(zone.depthMm) || !positive(zone.heightMm)) issues.push(`clearance_zone_invalid:${zone?.id}`);
  for (const segment of segments) { const route = routeMap.get(segment?.routeId); if (!route || !Array.isArray(segment.centerlineMm)) continue; const raw = routeBounds(segment); const bounds = { originMm: { xMm: raw.originMm.xMm - route.minimumClearanceMm, yMm: raw.originMm.yMm - route.minimumClearanceMm, zMm: raw.originMm.zMm - route.minimumClearanceMm }, widthMm: raw.widthMm + route.minimumClearanceMm * 2, depthMm: raw.depthMm + route.minimumClearanceMm * 2, heightMm: raw.heightMm + route.minimumClearanceMm * 2 }; for (const zone of zones) if (zone && boxOverlap(zone, bounds)) issues.push(`route_clearance_or_clash:${segment.id}`); }
  const output = input.output; if (!output || typeof output !== 'object' || output.format !== 'nexyfab-exchange-json' || !['ifc-neutral', 'step', 'json'].includes(output.targetFormat) || output.revision !== input.revision || typeof output.content !== 'string' || !Number.isSafeInteger(output.bytes) || output.bytes !== Buffer.byteLength(output.content, 'utf8') || !SHA256.test(output.sha256) || sha256(output.content) !== output.sha256) issues.push('output_binding_invalid');
  else { try { if (!verifyHvacDuctRouteReadback(input, parseHvacDuctRouteOutput(input)).valid) issues.push('output_readback_invalid'); } catch { issues.push('output_readback_invalid'); } }
  return { valid: issues.length === 0, issues };
}
function verificationHash(value: Omit<HvacParserReadbackV1, 'verificationSha256'>): string { return sha256(JSON.stringify({ ...value, routeIds: [...value.routeIds].sort(), portIds: [...value.portIds].sort(), segmentIds: [...value.segmentIds].sort(), fittingIds: [...value.fittingIds].sort(), supportIds: [...value.supportIds].sort() })); }
export function parseHvacDuctRouteOutput(input: HvacDuctRouteReleaseInputV1): HvacParserReadbackV1 { let parsed: unknown; try { parsed = JSON.parse(input.output.content) as unknown; } catch { throw new Error('HVAC_DUCT_OUTPUT_JSON_INVALID'); } const keys = ['schema', 'revision', 'sourceWorkspaceId', 'sourceModelId', 'sourceModelSha256', 'sourceContentHash', 'sourceRawArtifactSha256', 'routeIds', 'portIds', 'segmentIds', 'fittingIds', 'supportIds'] as const; if (!exactKeys(parsed, keys) || parsed.schema !== HVAC_DUCT_ROUTE_EXCHANGE_SCHEMA || !Number.isSafeInteger(parsed.revision) || typeof parsed.sourceWorkspaceId !== 'string' || !parsed.sourceWorkspaceId.trim() || typeof parsed.sourceModelId !== 'string' || !parsed.sourceModelId.trim() || ![parsed.sourceModelSha256, parsed.sourceContentHash, parsed.sourceRawArtifactSha256].every(value => typeof value === 'string' && SHA256.test(value)) || !keys.slice(7).every(key => stableIdArray(parsed[key]))) throw new Error('HVAC_DUCT_OUTPUT_SCHEMA_INVALID'); const exchange = parsed as unknown as HvacExchangeV1; const unsigned = { parserId: PARSER_ID, parserSourceSha256: sha256(parseHvacDuctRouteOutput.toString()), sourceWorkspaceId: exchange.sourceWorkspaceId, sourceModelId: exchange.sourceModelId, sourceModelSha256: exchange.sourceModelSha256, sourceContentHash: exchange.sourceContentHash, sourceRawArtifactSha256: exchange.sourceRawArtifactSha256, sourceRevision: exchange.revision, outputSha256: sha256(input.output.content), routeIds: exchange.routeIds, portIds: exchange.portIds, segmentIds: exchange.segmentIds, fittingIds: exchange.fittingIds, supportIds: exchange.supportIds } as const; return { ...unsigned, verificationSha256: verificationHash(unsigned) }; }
export function verifyHvacDuctRouteReadback(input: HvacDuctRouteReleaseInputV1, readback: HvacParserReadbackV1 | null | undefined): HvacReadbackResult { if (!readback || typeof readback !== 'object') return { valid: false, issues: ['readback_missing'] }; const expected = { parserId: PARSER_ID, parserSourceSha256: sha256(parseHvacDuctRouteOutput.toString()), sourceWorkspaceId: input.source.workspaceId, sourceModelId: input.source.modelId, sourceModelSha256: input.source.modelSha256, sourceContentHash: input.source.contentHash, sourceRawArtifactSha256: input.source.rawArtifactSha256, sourceRevision: input.revision, outputSha256: sha256(input.output.content), routeIds: input.routes.map(item => item.id), portIds: input.ports.map(item => item.id), segmentIds: input.segments.map(item => item.id), fittingIds: input.fittings.map(item => item.id), supportIds: input.supports.map(item => item.id) } as const; const issues: string[] = []; for (const key of ['parserId', 'parserSourceSha256', 'sourceWorkspaceId', 'sourceModelId', 'sourceModelSha256', 'sourceContentHash', 'sourceRawArtifactSha256', 'sourceRevision', 'outputSha256', 'routeIds', 'portIds', 'segmentIds', 'fittingIds', 'supportIds'] as const) if (JSON.stringify(readback[key]) !== JSON.stringify(expected[key])) issues.push(`readback_${key}_mismatch`); const { verificationSha256, ...unsigned } = readback; if (verificationSha256 !== verificationHash(unsigned)) issues.push('readback_verification_hash_invalid'); return { valid: issues.length === 0, issues }; }
export function assessHvacDuctRouteRelease(input: HvacDuctRouteReleaseInputV1, readback?: HvacParserReadbackV1 | null): HvacReleaseAssessment { const validation = validateHvacDuctRouteRelease(input); const internalParserVerified = readback ? verifyHvacDuctRouteReadback(input, readback).valid : false; const independentAttestationVerified = false; const blockers: string[] = [...holdBoundary]; if (!validation.valid) blockers.unshift(...validation.issues); blockers.unshift('independent_parser_attestation_required'); return { schema: HVAC_DUCT_ROUTE_RELEASE_SCHEMA, releaseReady: false, status: 'HOLD', internalParserVerified, independentAttestationVerified, parserVerified: false, blockers, holdBoundary }; }
