import { describe, expect, it } from 'vitest';
import { createDesignWorkspaceRevision } from './designWorkspaceRevision';
import { DESIGN_ARTIFACT_GRAPH_SCHEMA, type DesignArtifactGraph } from './designArtifactGraph';
import type { ArchitectureDocument, InteriorDocument } from './architectureInteriorDocuments';
import { buildInteriorReleaseCertificate, type BoundInteriorEvidence, type InteriorAxisEvidence, type InteriorDeliverableEvidence, type InteriorHostAuthorityEvidence, type InteriorReleaseCertificateInput } from './interiorReleaseCertificate';
import { CAD_WORKSPACE_ENVELOPE_SCHEMA, hashCadPayload, type CadWorkspaceEnvelopeInput } from '@/lib/cad/workspaceRevisionStore';

const hash = (value: string) => value.repeat(64);
function architecture(): ArchitectureDocument { const boundary: [number, number][] = [[0, 0], [6000, 0], [6000, 4000], [0, 4000]]; return {
  schema: 'nexyfab.architecture.v1', revision: 3, storeys: [{ id: 'l1', name: 'L1', elevationMm: 0, heightMm: 3000 }],
  spaces: [{ id: 'room', storeyId: 'l1', name: 'Office', usage: 'office', boundaryMm: boundary, wallIds: ['w1', 'w2', 'w3', 'w4'], slabId: 'slab', ceilingId: 'ceiling' }],
  walls: [{ id: 'w1', kind: 'line', storeyId: 'l1', startMm: [0, 0], endMm: [6000, 0], thicknessMm: 200, heightMm: 3000 }, { id: 'w2', kind: 'line', storeyId: 'l1', startMm: [6000, 0], endMm: [6000, 4000], thicknessMm: 200, heightMm: 3000 }, { id: 'w3', kind: 'line', storeyId: 'l1', startMm: [6000, 4000], endMm: [0, 4000], thicknessMm: 200, heightMm: 3000 }, { id: 'w4', kind: 'line', storeyId: 'l1', startMm: [0, 4000], endMm: [0, 0], thicknessMm: 200, heightMm: 3000 }],
  slabs: [{ id: 'slab', storeyId: 'l1', spaceId: 'room', boundaryMm: boundary, thicknessMm: 180 }], ceilings: [{ id: 'ceiling', storeyId: 'l1', spaceId: 'room', boundaryMm: boundary, elevationMm: 2700 }],
  openings: [{ id: 'door', kind: 'door', hostWallId: 'w1', offsetMm: 1000, widthMm: 900, heightMm: 2100, sillMm: 0, positionMm: [1000, 0, 0], connectsSpaceIds: ['room'], isExit: true, doorOperation: { pivotMm: [550, 0], closedAngleDeg: 0, openAngleDeg: 90, leafThicknessMm: 40, requiredClearanceMm: 300 } }],
}; }
function interior(): InteriorDocument { return { schema: 'nexyfab.interior.v1', revision: 0, architectureDocumentId: 'architecture', fieldMeasurement: { sourceRef: 'scan:verified', measuredAt: '2026-08-09T00:00:00Z', architectureRevision: 3, toleranceMm: 5 }, lights: [{ id: 'light', spaceId: 'room', hostCeilingId: 'ceiling', positionMm: [3000, 2000, 2600], suspensionMm: 100, lumens: 5000, cctK: 4000, iesProfileId: 'ies:verified' }], furniture: [{ id: 'desk', spaceId: 'room', positionMm: [3000, 2000, 0], sizeMm: [1200, 600, 750], clearanceMm: 400 }], finishes: [{ id: 'finish', spaceId: 'room', hostId: 'slab', surface: 'floor', material: 'oak' }], millwork: [{ id: 'casework', spaceId: 'room', hostWallId: 'w3', positionMm: [3000, 3900, 0], sizeMm: [1800, 500, 900], material: 'plywood', clearanceMm: 300 }], ceilingSystems: [{ id: 'grid', spaceId: 'room', hostCeilingId: 'ceiling', kind: 'grid', elevationMm: 2700, moduleMm: [600, 600] }], acousticZones: [{ id: 'acoustic', spaceId: 'room', targetRt60Sec: 0.6, absorptionClass: 'A' }] }; }
function graph(): DesignArtifactGraph { return { schema: DESIGN_ARTIFACT_GRAPH_SCHEMA, projectId: 'interior-project', revision: 0, artifacts: ([['model', 'model', 'b'], ['drawing', 'drawing', 'c'], ['quantity', 'quantity', 'd'], ['ifc', 'ifc', 'e']] as const).map(([id, kind, content]) => ({ id, kind, revision: 0, contentHash: hash(content), state: 'current', inputs: [], staleBecause: [], verification: { status: 'passed', verifierId: `${id}-verify`, evidenceHash: hash('f'), issues: [] } })), dependencies: [] }; }
function workspace(): CadWorkspaceEnvelopeInput { const document = interior(), requirements = { occupancy: 'office' }, relations = [{ from: 'light', to: 'ceiling' }]; return { schema: CAD_WORKSPACE_ENVELOPE_SCHEMA, workspace: createDesignWorkspaceRevision({ projectId: 'interior-project', lineageId: 'interior-lineage', domain: 'interior', documentHash: hashCadPayload(document) }), requirements: { contentHash: hashCadPayload(requirements), payload: requirements }, semanticDocument: { schema: document.schema, contentHash: hashCadPayload(document), payload: document }, geometry: { fidelity: 'exact_brep', contentHash: hash('b'), shapeIdentityHash: hash('1') }, objectRelations: { contentHash: hashCadPayload(relations), payload: relations }, artifactGraph: graph(), provenance: [{ sourceId: 'scan', kind: 'import', contentHash: hash('2') }], kernelIdentity: { mode: 'wasm', kernelId: 'occt-7.9', buildSha256: hash('3'), wasmSha256: hash('4'), stubFallback: false } }; }
function bound<T>(payload: T): BoundInteriorEvidence<T> { return { workspaceRevision: 0, modelContentHash: hash('b'), contentHash: hashCadPayload(payload), payload }; }
const axis = (): InteriorAxisEvidence => ({ status: 'pass', expected: 3, checked: 3, issues: [], artifactHashes: [hash('5')] });
function host(): InteriorHostAuthorityEvidence { const model = architecture(); return { ...axis(), architectureDocumentId: 'architecture', architectureContentHash: hashCadPayload(model), coordinateSystemId: 'project-local', architecture: model, federatedValidationIssues: [] }; }
const deliverables = (): InteriorDeliverableEvidence => ({ ...axis(), requiredDrawings: 5, verifiedDrawings: 5, expectedScheduleRows: 7, verifiedScheduleRows: 7, expectedQuantityItems: 8, verifiedQuantityItems: 8 });
function completeInput(): InteriorReleaseCertificateInput { return { workspace: workspace(), hostAuthority: bound(host()), spatial: bound(axis()), ceilingMep: bound(axis()), finishes: bound(axis()), millwork: bound(axis()), lighting: bound(axis()), acoustics: bound(axis()), ifcRoundtrip: bound(axis()), deliverables: bound(deliverables()), repair: bound(axis()) }; }

describe('interior release certificate', () => {
  it('passes exactly all 25 axes with revision-bound host and fit-out evidence', () => { const certificate = buildInteriorReleaseCertificate(completeInput()); expect(certificate.assertions).toHaveLength(25); expect(certificate.assertions.every(item => item.status === 'pass')).toBe(true); expect(certificate.releaseReady).toBe(true); });
  it('fails stale field measurement against the architecture host', () => { const input = completeInput(), value = host(); value.architecture.revision = 4; value.architectureContentHash = hashCadPayload(value.architecture); input.hostAuthority = bound(value); const certificate = buildInteriorReleaseCertificate(input); expect(certificate.releaseReady).toBe(false); expect(certificate.assertions.find(item => item.axis === 'field_measurement')).toMatchObject({ status: 'fail' }); });
  it('keeps photometric lighting not_run when evidence is absent', () => { const input = completeInput(); delete input.lighting; expect(buildInteriorReleaseCertificate(input).assertions.find(item => item.axis === 'lighting')).toMatchObject({ status: 'not_run' }); });
  it('fails release when the IFC artifact is stale', () => { const input = completeInput(), ifc = input.workspace.artifactGraph.artifacts.find(item => item.kind === 'ifc')!; ifc.state = 'stale'; ifc.verification.status = 'not_run'; ifc.verification.evidenceHash = undefined; ifc.staleBecause = ['model']; const certificate = buildInteriorReleaseCertificate(input); expect(certificate.releaseReady).toBe(false); expect(certificate.assertions.find(item => item.axis === 'output_consistency')).toMatchObject({ status: 'fail' }); });
});
