import type { ArchitectureDocument, InteriorDocument } from './architectureInteriorDocuments';
import { furnitureClearancePolygon } from './interiorFurnitureGeometry';
type V2 = [number, number];
const EPS = 1e-8;
const distance = (a: V2, b: V2) => Math.hypot(a[0] - b[0], a[1] - b[1]);
const cross = (a: V2, b: V2, c: V2) => (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0]);
function pointOnSegment(point: V2, a: V2, b: V2): boolean { return Math.abs(cross(a, b, point)) <= EPS && point[0] >= Math.min(a[0], b[0]) - EPS && point[0] <= Math.max(a[0], b[0]) + EPS && point[1] >= Math.min(a[1], b[1]) - EPS && point[1] <= Math.max(a[1], b[1]) + EPS; }
function pointInPolygon(point: V2, polygon: readonly V2[], includeBoundary: boolean): boolean { if (polygon.some((a, index) => pointOnSegment(point, a, polygon[(index + 1) % polygon.length]!))) return includeBoundary; let inside = false; for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) { const a = polygon[i]!, b = polygon[j]!; if ((a[1] > point[1]) !== (b[1] > point[1]) && point[0] < (b[0] - a[0]) * (point[1] - a[1]) / (b[1] - a[1]) + a[0]) inside = !inside; } return inside; }
function segmentIntersectionParameter(a: V2, b: V2, c: V2, d: V2): number | null { const rx = b[0] - a[0], ry = b[1] - a[1], sx = d[0] - c[0], sy = d[1] - c[1], denominator = rx * sy - ry * sx; if (Math.abs(denominator) <= EPS) return null; const qx = c[0] - a[0], qy = c[1] - a[1], t = (qx * sy - qy * sx) / denominator, u = (qx * ry - qy * rx) / denominator; return t >= -EPS && t <= 1 + EPS && u >= -EPS && u <= 1 + EPS ? Math.max(0, Math.min(1, t)) : null; }
function segmentIntervals(a: V2, b: V2, polygon: readonly V2[]): number[] { const values = new Set<number>([0, 1]); polygon.forEach((point, index) => { const t = segmentIntersectionParameter(a, b, point, polygon[(index + 1) % polygon.length]!); if (t !== null) values.add(t); }); return [...values].sort((left, right) => left - right); }
function segmentInsideRoom(a: V2, b: V2, room: readonly V2[]): boolean { if (!pointInPolygon(a, room, true) || !pointInPolygon(b, room, true)) return false; const values = segmentIntervals(a, b, room); return values.slice(1).every((value, index) => { const t = (values[index]! + value) / 2; return pointInPolygon([a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t], room, true); }); }
function segmentAvoidsInterior(a: V2, b: V2, polygon: readonly V2[]): boolean { const values = segmentIntervals(a, b, polygon); return values.slice(1).every((value, index) => { const t = (values[index]! + value) / 2; return !pointInPolygon([a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t], polygon, false); }); }

export interface PolygonInteriorRouteResult { status: 'passed' | 'failed' | 'not_run'; distanceMm?: number; pathMm: V2[]; reason?: string; method: 'exact_polygon_visibility_graph' }
export function verifyPolygonInteriorRoute(architecture: ArchitectureDocument, interior: InteriorDocument, spaceId: string, originMm: V2, destinationMm: V2, maximumDistanceMm: number): PolygonInteriorRouteResult {
  const space = architecture.spaces.find(item => item.id === spaceId); if (!space) return { status: 'not_run', pathMm: [], reason: 'Space is missing.', method: 'exact_polygon_visibility_graph' };
  if (!(maximumDistanceMm > 0) || ![...originMm, ...destinationMm, maximumDistanceMm].every(Number.isFinite)) throw new Error('Route inputs must be finite and maximum distance positive.');
  const obstacles = interior.furniture.filter(item => item.spaceId === spaceId).map(furnitureClearancePolygon);
  if (!pointInPolygon(originMm, space.boundaryMm, true) || !pointInPolygon(destinationMm, space.boundaryMm, true) || obstacles.some(polygon => pointInPolygon(originMm, polygon, true) || pointInPolygon(destinationMm, polygon, true))) return { status: 'failed', pathMm: [], reason: 'Origin or destination is outside usable space.', method: 'exact_polygon_visibility_graph' };
  const nodes = [originMm, destinationMm, ...obstacles.flatMap(polygon => polygon)], count = nodes.length, costs = Array<number>(count).fill(Number.POSITIVE_INFINITY), previous = Array<number>(count).fill(-1), pending = new Set(nodes.map((_, index) => index)); costs[0] = 0;
  const clear = (a: V2, b: V2) => segmentInsideRoom(a, b, space.boundaryMm) && obstacles.every(polygon => segmentAvoidsInterior(a, b, polygon));
  while (pending.size) { let current = -1; pending.forEach(index => { if (current < 0 || costs[index]! < costs[current]!) current = index; }); if (current < 0 || !Number.isFinite(costs[current]!)) break; pending.delete(current); for (const neighbor of pending) if (clear(nodes[current]!, nodes[neighbor]!)) { const candidate = costs[current]! + distance(nodes[current]!, nodes[neighbor]!); if (candidate < costs[neighbor]!) { costs[neighbor] = candidate; previous[neighbor] = current; } } }
  if (!Number.isFinite(costs[1]!)) return { status: 'failed', pathMm: [], reason: 'No polygon-clear path exists.', method: 'exact_polygon_visibility_graph' };
  const pathMm: V2[] = []; for (let cursor = 1; cursor >= 0; cursor = previous[cursor]!) { pathMm.unshift(nodes[cursor]!); if (cursor === 0) break; }
  return { status: costs[1]! <= maximumDistanceMm ? 'passed' : 'failed', distanceMm: costs[1], pathMm, ...(costs[1]! > maximumDistanceMm ? { reason: 'Route exceeds governed maximum distance.' } : {}), method: 'exact_polygon_visibility_graph' };
}
