import type { AgenticCommercialQualificationReceipt, AgenticCommercialQualificationVerificationContext } from './agenticCommercialQualificationReceipt';
import { verifyAgenticCommercialQualificationReceipt } from './agenticCommercialQualificationReceipt';
import type { VerifiedAgenticCommercialReceiptStore } from './verifiedAgenticCommercialReceiptStore';

export interface LoadVerifiedAgenticCommercialReceiptResult { ok: boolean; status: 'QUALIFIED' | 'HOLD'; releaseReady: boolean; receipt?: AgenticCommercialQualificationReceipt; finalEnvelopeSha256?: string; issues: string[]; }
export async function loadVerifiedAgenticCommercialReceiptForGeneration(store: VerifiedAgenticCommercialReceiptStore, input: { tenantId: string; projectId: string; receiptId: string; executionId: string; generationRunId: string; generationStateRevision: number; generationProgramSha256: string; revision: number; modelContentHash: string; targetSha256: string }, context: AgenticCommercialQualificationVerificationContext): Promise<LoadVerifiedAgenticCommercialReceiptResult> {
  const stored = await store.get(input.tenantId, input.projectId, input.receiptId); if (!stored) return { ok: false, status: 'HOLD', releaseReady: false, issues: ['verified_final_receipt_not_found'] };
  if (stored.executionId !== input.executionId || stored.generationRunId !== input.generationRunId || stored.revision !== input.revision || stored.modelContentHash !== input.modelContentHash || stored.targetSha256 !== input.targetSha256) return { ok: false, status: 'HOLD', releaseReady: false, finalEnvelopeSha256: stored.finalEnvelopeSha256, issues: ['verified_final_receipt_binding_mismatch'] };
  const now = context.now.getTime(); const issued = Date.parse(stored.issuedAt); const expires = Date.parse(stored.expiresAt); if (!Number.isFinite(issued) || !Number.isFinite(expires) || issued > now || expires <= now) return { ok: false, status: 'HOLD', releaseReady: false, finalEnvelopeSha256: stored.finalEnvelopeSha256, issues: ['verified_final_receipt_expired_or_future'] };
  const receipt = stored.payload as unknown as AgenticCommercialQualificationReceipt; if (!Number.isSafeInteger(input.generationStateRevision) || input.generationStateRevision < 0 || receipt.generationStateRevision !== input.generationStateRevision || !/^[a-f0-9]{64}$/.test(input.generationProgramSha256) || receipt.generationProgramSha256 !== input.generationProgramSha256) return { ok: false, status: 'HOLD', releaseReady: false, finalEnvelopeSha256: stored.finalEnvelopeSha256, issues: ['verified_final_receipt_program_binding_mismatch'] }; const verification = verifyAgenticCommercialQualificationReceipt(receipt, context); return { ok: verification.ok, status: verification.status, releaseReady: verification.releaseReady, receipt, finalEnvelopeSha256: stored.finalEnvelopeSha256, issues: verification.issues };
}
