type V3 = [number, number, number];
export type MepSystem = 'electrical' | 'data' | 'cold_water' | 'hot_water' | 'drain' | 'supply_air' | 'return_air';
export interface EquipmentPort { id: string; ownerObjectId: string; system: MepSystem; connector: string; positionMm: V3; required: boolean }
export interface MepNode { id: string; system: MepSystem; connector: string; positionMm: V3 }
export interface MepConnection { id: string; portId: string; nodeId: string }
export interface MepRun { id: string; system: MepSystem; fromNodeId: string; toNodeId: string; lengthMm: number; elevationDropMm?: number; diameterMm?: number }
export interface MepConnectionRules { maximumConnectionDistanceMm: number; minimumDrainSlopePercent: number; requireMatchingConnector: boolean }
export interface MepConnectionResult { status: 'passed' | 'failed' | 'not_run'; failures: Array<{ objectId: string; code: 'REQUIRED_PORT_UNCONNECTED' | 'UNKNOWN_ENDPOINT' | 'SYSTEM_MISMATCH' | 'CONNECTOR_MISMATCH' | 'CONNECTION_TOO_FAR' | 'INVALID_RUN' | 'DRAIN_SLOPE_LOW'; measured?: number; required?: number }>; method: 'explicit_port_network' }
const finiteV3 = (point: V3) => point.length === 3 && point.every(Number.isFinite);
export function verifyMepConnections(ports: EquipmentPort[], nodes: MepNode[], connections: MepConnection[], runs: MepRun[], rules?: MepConnectionRules): MepConnectionResult {
  if (!rules) return { status: 'not_run', failures: [], method: 'explicit_port_network' };
  if (!(rules.maximumConnectionDistanceMm >= 0) || !(rules.minimumDrainSlopePercent >= 0) || !Number.isFinite(rules.maximumConnectionDistanceMm) || !Number.isFinite(rules.minimumDrainSlopePercent)) throw new Error('MEP connection rules are invalid.');
  const failures: MepConnectionResult['failures'] = [], portMap = new Map(ports.map(item => [item.id, item])), nodeMap = new Map(nodes.map(item => [item.id, item]));
  for (const port of ports) { if (!finiteV3(port.positionMm) || !port.id.trim() || !port.connector.trim()) failures.push({ objectId: port.id, code: 'UNKNOWN_ENDPOINT' }); if (port.required && !connections.some(item => item.portId === port.id)) failures.push({ objectId: port.id, code: 'REQUIRED_PORT_UNCONNECTED' }); }
  for (const connection of connections) { const port = portMap.get(connection.portId), node = nodeMap.get(connection.nodeId); if (!port || !node || !finiteV3(node.positionMm)) { failures.push({ objectId: connection.id, code: 'UNKNOWN_ENDPOINT' }); continue; } if (port.system !== node.system) failures.push({ objectId: connection.id, code: 'SYSTEM_MISMATCH' }); if (rules.requireMatchingConnector && port.connector !== node.connector) failures.push({ objectId: connection.id, code: 'CONNECTOR_MISMATCH' }); const distance = Math.hypot(port.positionMm[0] - node.positionMm[0], port.positionMm[1] - node.positionMm[1], port.positionMm[2] - node.positionMm[2]); if (distance > rules.maximumConnectionDistanceMm) failures.push({ objectId: connection.id, code: 'CONNECTION_TOO_FAR', measured: distance, required: rules.maximumConnectionDistanceMm }); }
  for (const run of runs) { const from = nodeMap.get(run.fromNodeId), to = nodeMap.get(run.toNodeId); if (!from || !to || from.system !== run.system || to.system !== run.system || !(run.lengthMm > 0) || !Number.isFinite(run.lengthMm) || (run.diameterMm !== undefined && !(run.diameterMm > 0))) { failures.push({ objectId: run.id, code: 'INVALID_RUN' }); continue; } if (run.system === 'drain') { if (!Number.isFinite(run.elevationDropMm)) failures.push({ objectId: run.id, code: 'INVALID_RUN' }); else { const slope = Math.abs(run.elevationDropMm!) / run.lengthMm * 100; if (slope < rules.minimumDrainSlopePercent) failures.push({ objectId: run.id, code: 'DRAIN_SLOPE_LOW', measured: slope, required: rules.minimumDrainSlopePercent }); } } }
  return { status: failures.length ? 'failed' : 'passed', failures, method: 'explicit_port_network' };
}
