import type { MepSystem } from './mepConnectionVerification';
type V3 = [number, number, number];
export interface MepRoutingObstacle { id: string; minMm: V3; maxMm: V3 }
export interface MepRouteRequest { id: string; system: MepSystem; startMm: V3; endMm: V3; clearanceMm: number; gridMm: number; obstacles: MepRoutingObstacle[]; maxVisitedNodes?: number }
export interface MepRouteResult { status: 'routed' | 'failed' | 'not_run'; pathMm: V3[]; lengthMm?: number; visitedNodes: number; reason?: string; method: 'bounded_orthogonal_astar' }
const key = (point: V3) => point.join(','), distance = (a: V3, b: V3) => Math.abs(a[0] - b[0]) + Math.abs(a[1] - b[1]) + Math.abs(a[2] - b[2]);
const inside = (point: V3, obstacle: MepRoutingObstacle, clearance: number) => point[0] >= obstacle.minMm[0] - clearance && point[0] <= obstacle.maxMm[0] + clearance && point[1] >= obstacle.minMm[1] - clearance && point[1] <= obstacle.maxMm[1] + clearance && point[2] >= obstacle.minMm[2] - clearance && point[2] <= obstacle.maxMm[2] + clearance;
const aligned = (value: number, grid: number) => Math.round(value / grid) * grid;
function compress(path: V3[]): V3[] { return path.filter((point, index) => { if (index === 0 || index === path.length - 1) return true; const previous = path[index - 1]!, next = path[index + 1]!; return !((point[0] - previous[0]) * (next[1] - point[1]) === 0 && (point[0] - previous[0]) * (next[2] - point[2]) === 0 && (point[1] - previous[1]) * (next[0] - point[0]) === 0 && (point[1] - previous[1]) * (next[2] - point[2]) === 0 && (point[2] - previous[2]) * (next[0] - point[0]) === 0 && (point[2] - previous[2]) * (next[1] - point[1]) === 0); }); }

export function routeMepOrthogonal3d(request: MepRouteRequest): MepRouteResult {
  if (request.system === 'drain') return { status: 'not_run', pathMm: [], visitedNodes: 0, reason: 'Gravity drainage requires a governed sloped-route solver.', method: 'bounded_orthogonal_astar' };
  if (!(request.gridMm > 0) || request.clearanceMm < 0 || ![...request.startMm, ...request.endMm, request.gridMm, request.clearanceMm].every(Number.isFinite)) throw new Error('MEP routing inputs are invalid.');
  const start = request.startMm.map(value => aligned(value, request.gridMm)) as V3, goal = request.endMm.map(value => aligned(value, request.gridMm)) as V3;
  if (request.obstacles.some(obstacle => inside(start, obstacle, request.clearanceMm) || inside(goal, obstacle, request.clearanceMm))) return { status: 'failed', pathMm: [], visitedNodes: 0, reason: 'A route endpoint is inside required obstacle clearance.', method: 'bounded_orthogonal_astar' };
  const margin = request.gridMm * 8 + request.clearanceMm, coordinates = [...request.startMm, ...request.endMm, ...request.obstacles.flatMap(item => [...item.minMm, ...item.maxMm])], xs = coordinates.filter((_, index) => index % 3 === 0), ys = coordinates.filter((_, index) => index % 3 === 1), zs = coordinates.filter((_, index) => index % 3 === 2), bounds = { min: [aligned(Math.min(...xs) - margin, request.gridMm), aligned(Math.min(...ys) - margin, request.gridMm), aligned(Math.min(...zs) - margin, request.gridMm)] as V3, max: [aligned(Math.max(...xs) + margin, request.gridMm), aligned(Math.max(...ys) + margin, request.gridMm), aligned(Math.max(...zs) + margin, request.gridMm)] as V3 };
  const open = new Set([key(start)]), points = new Map([[key(start), start]]), costs = new Map([[key(start), 0]]), previous = new Map<string, string>(), maxVisited = request.maxVisitedNodes ?? 100_000; let visited = 0;
  const directions: V3[] = [[1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1], [0, 0, -1]];
  while (open.size && visited < maxVisited) {
    let currentKey = ''; open.forEach(candidate => { if (!currentKey || costs.get(candidate)! + distance(points.get(candidate)!, goal) < costs.get(currentKey)! + distance(points.get(currentKey)!, goal)) currentKey = candidate; });
    const current = points.get(currentKey)!; open.delete(currentKey); visited++;
    if (currentKey === key(goal)) { const path: V3[] = []; let cursor: string | undefined = currentKey; while (cursor) { path.unshift(points.get(cursor)!); cursor = previous.get(cursor); } const compressed = compress(path); return { status: 'routed', pathMm: compressed, lengthMm: path.slice(1).reduce((sum, point, index) => sum + distance(point, path[index]!), 0), visitedNodes: visited, method: 'bounded_orthogonal_astar' }; }
    for (const direction of directions) { const next = current.map((value, axis) => value + direction[axis]! * request.gridMm) as V3; const crossesObstacle = request.obstacles.some(obstacle => segmentBoxInterval(current, next, obstacle.minMm.map(value => value - request.clearanceMm) as V3, obstacle.maxMm.map(value => value + request.clearanceMm) as V3)); if (next.some((value, axis) => value < bounds.min[axis]! || value > bounds.max[axis]!) || request.obstacles.some(obstacle => inside(next, obstacle, request.clearanceMm)) || crossesObstacle) continue; const nextKey = key(next), candidate = costs.get(currentKey)! + request.gridMm; if (candidate < (costs.get(nextKey) ?? Number.POSITIVE_INFINITY)) { costs.set(nextKey, candidate); previous.set(nextKey, currentKey); points.set(nextKey, next); open.add(nextKey); } }
  }
  return { status: 'failed', pathMm: [], visitedNodes: visited, reason: visited >= maxVisited ? 'Routing node budget exhausted.' : 'No clearance-respecting route exists.', method: 'bounded_orthogonal_astar' };
}

export interface PenetrationHost { id: string; kind: 'wall' | 'slab' | 'structure'; minMm: V3; maxMm: V3; penetrationAllowed: boolean; approvalId?: string }
export interface SleevePlan { id: string; routeId: string; hostId: string; centerMm: V3; axis: V3; lengthMm: number; insideDiameterMm: number; approvalId?: string }
export interface PenetrationPlanResult { status: 'passed' | 'blocked'; sleeves: SleevePlan[]; blockers: Array<{ hostId: string; code: 'PENETRATION_FORBIDDEN' | 'STRUCTURAL_APPROVAL_REQUIRED' }> }
function segmentBoxInterval(a: V3, b: V3, min: V3, max: V3): [number, number] | null { let low = 0, high = 1; for (let axis = 0; axis < 3; axis++) { const delta = b[axis]! - a[axis]!; if (Math.abs(delta) < 1e-12) { if (a[axis]! < min[axis]! || a[axis]! > max[axis]!) return null; continue; } let first = (min[axis]! - a[axis]!) / delta, second = (max[axis]! - a[axis]!) / delta; if (first > second) [first, second] = [second, first]; low = Math.max(low, first); high = Math.min(high, second); if (low >= high) return null; } return [low, high]; }
export function planMepPenetrationSleeves(routeId: string, pathMm: V3[], outsideDiameterMm: number, radialClearanceMm: number, hosts: PenetrationHost[]): PenetrationPlanResult {
  if (pathMm.length < 2 || !(outsideDiameterMm > 0) || radialClearanceMm < 0) throw new Error('Route and sleeve dimensions are invalid.');
  const sleeves: SleevePlan[] = [], blockers: PenetrationPlanResult['blockers'] = [];
  pathMm.slice(1).forEach((end, index) => { const start = pathMm[index]!, dx = end[0] - start[0], dy = end[1] - start[1], dz = end[2] - start[2], segmentLength = Math.hypot(dx, dy, dz); for (const host of hosts) { const interval = segmentBoxInterval(start, end, host.minMm, host.maxMm); if (!interval) continue; if (!host.penetrationAllowed) { blockers.push({ hostId: host.id, code: 'PENETRATION_FORBIDDEN' }); continue; } if (host.kind === 'structure' && !host.approvalId) { blockers.push({ hostId: host.id, code: 'STRUCTURAL_APPROVAL_REQUIRED' }); continue; } const midpoint = (interval[0] + interval[1]) / 2; sleeves.push({ id: `sleeve:${routeId}:${host.id}:${index}`, routeId, hostId: host.id, centerMm: [start[0] + dx * midpoint, start[1] + dy * midpoint, start[2] + dz * midpoint], axis: [dx / segmentLength, dy / segmentLength, dz / segmentLength], lengthMm: segmentLength * (interval[1] - interval[0]), insideDiameterMm: outsideDiameterMm + radialClearanceMm * 2, approvalId: host.approvalId }); } });
  return { status: blockers.length ? 'blocked' : 'passed', sleeves, blockers };
}
