import { createHash } from 'node:crypto';

export const ROBOT_CELL_KINEMATIC_RELEASE_SCHEMA = 'nexyfab.robot-cell-kinematic-release.v1' as const;
export const ROBOT_CELL_KINEMATIC_EXCHANGE_SCHEMA = 'nexyfab.robot-cell-kinematic-exchange.v1' as const;
const PARSER_ID = 'nexyfab.robot-cell-kinematic-independent-parser.v1' as const;
const SHA256 = /^[a-f0-9]{64}$/;
const EPSILON = 1e-8;
export interface RobotCellSourceBindingV1 { workspaceId: string; modelId: string; modelPath: string; modelSha256: string; librarySha256: string; rawArtifactSha256: string; contentHash: string; revisionSha256: string; revision: number; }
export interface RobotPointMmV1 { xMm: number; yMm: number; zMm: number; }
export interface RobotLinkV1 { id: string; lengthMm: number; collisionRadiusMm: number; parentJointId?: string; childJointIds: readonly string[]; }
export type RobotJointType = 'revolute' | 'prismatic';
export interface RobotJointV1 { id: string; parentLinkId: string; childLinkId: string; type: RobotJointType; originMm: RobotPointMmV1; axis: RobotPointMmV1; minValue: number; maxValue: number; }
export interface RobotToolV1 { id: string; linkId: string; tipOffsetMm: RobotPointMmV1; payloadKg: number; }
export interface RobotFixtureV1 { id: string; originMm: RobotPointMmV1; widthMm: number; depthMm: number; heightMm: number; clearanceMm: number; }
export interface RobotEnvelopeV1 { minMm: RobotPointMmV1; maxMm: RobotPointMmV1; }
export interface RobotOperationV1 { id: string; robotId: string; jointIds: readonly string[]; sampleValues: readonly (readonly number[])[]; toolId: string; fixtureIds: readonly string[]; envelope: RobotEnvelopeV1; }
export interface RobotCellV1 { id: string; baseLinkId: string; linkIds: readonly string[]; jointIds: readonly string[]; toolIds: readonly string[]; operationIds: readonly string[]; }
export interface RobotOutputV1 { format: 'nexyfab-exchange-json'; targetFormat: 'step' | 'urdf-neutral' | 'json'; revision: number; content: string; bytes: number; sha256: string; }
export interface RobotCellExchangeV1 { schema: typeof ROBOT_CELL_KINEMATIC_EXCHANGE_SCHEMA; revision: number; sourceWorkspaceId: string; sourceModelId: string; sourceModelSha256: string; sourceLibrarySha256: string; sourceRawArtifactSha256: string; sourceContentHash: string; robotIds: string[]; linkIds: string[]; jointIds: string[]; toolIds: string[]; fixtureIds: string[]; operationIds: string[]; }
export interface RobotCellReleaseInputV1 { schema: typeof ROBOT_CELL_KINEMATIC_RELEASE_SCHEMA; units: 'mm-deg-kg'; revision: number; source: RobotCellSourceBindingV1; robots: readonly RobotCellV1[]; links: readonly RobotLinkV1[]; joints: readonly RobotJointV1[]; tools: readonly RobotToolV1[]; fixtures: readonly RobotFixtureV1[]; operations: readonly RobotOperationV1[]; output: RobotOutputV1; }
export interface RobotParserReadbackV1 { parserId: typeof PARSER_ID; parserSourceSha256: string; sourceWorkspaceId: string; sourceModelId: string; sourceModelSha256: string; sourceLibrarySha256: string; sourceRawArtifactSha256: string; sourceContentHash: string; sourceRevision: number; outputSha256: string; robotIds: readonly string[]; linkIds: readonly string[]; jointIds: readonly string[]; toolIds: readonly string[]; fixtureIds: readonly string[]; operationIds: readonly string[]; verificationSha256: string; }
export interface RobotValidationResult { valid: boolean; issues: string[]; }
export interface RobotReleaseAssessment { schema: typeof ROBOT_CELL_KINEMATIC_RELEASE_SCHEMA; releaseReady: false; status: 'HOLD'; internalParserVerified: boolean; independentAttestationVerified: boolean; /** @deprecated Use internalParserVerified. */ parserVerified: boolean; blockers: string[]; holdBoundary: readonly string[]; }
export interface RobotReadbackResult { valid: boolean; issues: string[]; }
const holdBoundary = ['native_step_urdf_parser_not_verified', 'continuous_collision_check_not_run', 'dynamics_and_payload_analysis_not_run', 'safety_plc_and_iso_risk_assessment_not_verified', 'oem_controller_and_native_step_urdf_not_verified', 'field_commissioning_receipt_not_available'] as const;
const sha256 = (value: string): string => createHash('sha256').update(value, 'utf8').digest('hex'); const finite = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value); const positive = (value: unknown): value is number => finite(value) && value > 0; const nonnegative = (value: unknown): value is number => finite(value) && value >= 0; const arrays = <T>(value: unknown): readonly T[] => Array.isArray(value) ? value as readonly T[] : []; const equal = (a: number, b: number): boolean => Math.abs(a - b) <= Math.max(EPSILON, Math.max(Math.abs(a), Math.abs(b)) * 1e-9); const point = (value: unknown): value is RobotPointMmV1 => Boolean(value && typeof value === 'object' && finite((value as RobotPointMmV1).xMm) && finite((value as RobotPointMmV1).yMm) && finite((value as RobotPointMmV1).zMm)); const ids = (values: readonly { id?: unknown }[]): Set<string> => new Set(values.map(value => value?.id).filter((id): id is string => typeof id === 'string'));
const exactKeys = (value: unknown, keys: readonly string[]): value is Record<string, unknown> => Boolean(value && typeof value === 'object' && !Array.isArray(value) && Object.keys(value).length === keys.length && Object.keys(value).every(key => keys.includes(key))); const stableIdArray = (value: unknown): value is string[] => Array.isArray(value) && value.every(id => typeof id === 'string' && id.trim() === id && id.length > 0) && new Set(value).size === value.length;
function register(values: readonly { id?: unknown }[], label: string, issues: string[], all: Set<string>): void { for (const value of values) { const id = value?.id; if (typeof id !== 'string' || !id.trim() || all.has(id)) issues.push(`${label}_id_invalid:${String(id)}`); else all.add(id); } }
function vectorLength(v: RobotPointMmV1): number { return Math.hypot(v.xMm, v.yMm, v.zMm); }
function terminalLinkId(robot: RobotCellV1, links: readonly RobotLinkV1[], joints: readonly RobotJointV1[]): string | undefined { const linkMap = new Map(links.map(link => [link.id, link])); const jointMap = new Map(joints.map(joint => [joint.id, joint])); let current: string | undefined = robot.baseLinkId; const seen = new Set<string>(); while (current && !seen.has(current)) { seen.add(current); const child: string | undefined = linkMap.get(current)?.childJointIds[0]; current = child ? jointMap.get(child)?.childLinkId : undefined; } const ids = [...seen]; return ids[ids.length - 1]; }
function fkEnvelope(robot: RobotCellV1, links: readonly RobotLinkV1[], joints: readonly RobotJointV1[], samples: readonly (readonly number[])[], tool?: RobotToolV1): RobotEnvelopeV1 {
  const linkMap = new Map(links.map(link => [link.id, link])); const jointMap = new Map(joints.map(joint => [joint.id, joint]));
  const min = { xMm: Infinity, yMm: Infinity, zMm: Infinity }; const max = { xMm: -Infinity, yMm: -Infinity, zMm: -Infinity };
  const include = (x: number, y: number, z: number, radius = 0): void => { min.xMm = Math.min(min.xMm, x - radius); max.xMm = Math.max(max.xMm, x + radius); min.yMm = Math.min(min.yMm, y - radius); max.yMm = Math.max(max.yMm, y + radius); min.zMm = Math.min(min.zMm, z - radius); max.zMm = Math.max(max.zMm, z + radius); };
  for (const sample of samples) { let x = 0; let y = 0; let z = 0; let angle = 0; let linkId: string | undefined = robot.baseLinkId; let tip: { x: number; y: number; z: number } | undefined; const seen = new Set<string>();
    while (linkId && !seen.has(linkId)) { seen.add(linkId); const link = linkMap.get(linkId); if (!link) break; const start = { x, y, z }; const end = { x: x + link.lengthMm * Math.cos(angle), y: y + link.lengthMm * Math.sin(angle), z };
      include(start.x, start.y, start.z, link.collisionRadiusMm); include(end.x, end.y, end.z, link.collisionRadiusMm); const child = link.childJointIds[0]; const joint = child ? jointMap.get(child) : undefined; const index = joint ? robot.jointIds.indexOf(joint.id) : -1; const value = index >= 0 ? sample[index] ?? 0 : 0; x = end.x + (joint?.originMm.xMm ?? 0); y = end.y + (joint?.originMm.yMm ?? 0); z = end.z + (joint?.originMm.zMm ?? 0); if (joint?.type === 'revolute') angle += value * Math.PI / 180; else if (joint?.type === 'prismatic') { const axisLength = vectorLength(joint.axis); const ax = joint.axis.xMm * Math.cos(angle) - joint.axis.yMm * Math.sin(angle); const ay = joint.axis.xMm * Math.sin(angle) + joint.axis.yMm * Math.cos(angle); x += value * ax / axisLength; y += value * ay / axisLength; z += value * joint.axis.zMm / axisLength; } linkId = joint?.childLinkId; tip = { x: end.x, y: end.y, z: end.z }; }
    if (tool && tip) { const c = Math.cos(angle); const s = Math.sin(angle); include(tip.x + tool.tipOffsetMm.xMm * c - tool.tipOffsetMm.yMm * s, tip.y + tool.tipOffsetMm.xMm * s + tool.tipOffsetMm.yMm * c, tip.z + tool.tipOffsetMm.zMm); }
  }
  return { minMm: min, maxMm: max };
}
function boxesOverlap(a: RobotEnvelopeV1, b: RobotFixtureV1): boolean { const c = b.clearanceMm; return a.minMm.xMm < b.originMm.xMm + b.widthMm + c - EPSILON && a.maxMm.xMm > b.originMm.xMm - c + EPSILON && a.minMm.yMm < b.originMm.yMm + b.depthMm + c - EPSILON && a.maxMm.yMm > b.originMm.yMm - c + EPSILON && a.minMm.zMm < b.originMm.zMm + b.heightMm + c - EPSILON && a.maxMm.zMm > b.originMm.zMm - c + EPSILON; }
export function validateRobotCellKinematicRelease(input: RobotCellReleaseInputV1 | null | undefined): RobotValidationResult {
  const issues: string[] = []; if (!input || typeof input !== 'object') return { valid: false, issues: ['input_missing'] }; if (input.schema !== ROBOT_CELL_KINEMATIC_RELEASE_SCHEMA) issues.push('schema_invalid'); if (input.units !== 'mm-deg-kg') issues.push('canonical_units_required'); if (!Number.isSafeInteger(input.revision) || input.revision < 0) issues.push('revision_invalid'); const source = input.source; if (!source || typeof source !== 'object') issues.push('source_binding_missing'); else { if (typeof source.workspaceId !== 'string' || !source.workspaceId.trim() || typeof source.modelId !== 'string' || !source.modelId.trim()) issues.push('source_identity_invalid'); if (typeof source.modelPath !== 'string' || !source.modelPath.trim() || source.modelPath.replaceAll('\\', '/').split('/').includes('..') || source.modelPath.startsWith('/') || /^[A-Za-z]:[\\/]/.test(source.modelPath)) issues.push('source_model_path_invalid'); if (![source.modelSha256, source.librarySha256, source.rawArtifactSha256, source.contentHash, source.revisionSha256].every(value => typeof value === 'string' && SHA256.test(value))) issues.push('source_hash_invalid'); if (!Number.isSafeInteger(source.revision) || source.revision !== input.revision) issues.push('stale_source_revision'); }
  const robots = arrays<RobotCellV1>(input.robots); const links = arrays<RobotLinkV1>(input.links); const joints = arrays<RobotJointV1>(input.joints); const tools = arrays<RobotToolV1>(input.tools); const fixtures = arrays<RobotFixtureV1>(input.fixtures); const operations = arrays<RobotOperationV1>(input.operations); for (const [value, label] of [[input.robots, 'robots'], [input.links, 'links'], [input.joints, 'joints'], [input.tools, 'tools'], [input.fixtures, 'fixtures'], [input.operations, 'operations']] as const) if (!Array.isArray(value)) issues.push(`${label}_array_required`); const all = new Set<string>(); register(robots, 'robot', issues, all); register(links, 'link', issues, all); register(joints, 'joint', issues, all); register(tools, 'tool', issues, all); register(fixtures, 'fixture', issues, all); register(operations, 'operation', issues, all); const linkIds = ids(links); const jointIds = ids(joints); const toolIds = ids(tools); const fixtureIds = ids(fixtures); const linkMap = new Map(links.map(item => [item?.id, item])); const jointMap = new Map(joints.map(item => [item?.id, item])); const toolMap = new Map(tools.map(item => [item?.id, item])); const fixtureMap = new Map(fixtures.map(item => [item?.id, item]));
  for (const robot of robots) if (!robot || typeof robot !== 'object' || !linkIds.has(robot.baseLinkId) || linkMap.get(robot.baseLinkId)?.parentJointId !== undefined || robot.linkIds.length === 0 || new Set(robot.linkIds).size !== robot.linkIds.length || robot.linkIds.some(id => !linkIds.has(id)) || new Set(robot.jointIds).size !== robot.jointIds.length || robot.jointIds.some(id => !jointIds.has(id)) || new Set(robot.toolIds).size !== robot.toolIds.length || robot.toolIds.some(id => !toolIds.has(id)) || new Set(robot.operationIds).size !== robot.operationIds.length || robot.operationIds.some(id => !operations.some(operation => operation?.id === id && operation.robotId === robot.id))) issues.push(`robot_chain_registry_invalid:${robot?.id}`);
  for (const robot of robots) { const reachableLinks = new Set<string>(); const reachableJoints = new Set<string>(); let current: string | undefined = robot?.baseLinkId; while (current && !reachableLinks.has(current)) { reachableLinks.add(current); const link = linkMap.get(current); const child = link?.childJointIds[0]; if (!child) break; reachableJoints.add(child); current = jointMap.get(child)?.childLinkId; } if (reachableLinks.size !== robot.linkIds.length || robot.linkIds.some(id => !reachableLinks.has(id)) || reachableJoints.size !== robot.jointIds.length || robot.jointIds.some(id => !reachableJoints.has(id))) issues.push(`robot_chain_registry_invalid:${robot?.id}`); }
  for (const link of links) if (!link || typeof link !== 'object' || !positive(link.lengthMm) || !positive(link.collisionRadiusMm) || (link.parentJointId !== undefined && !jointIds.has(link.parentJointId)) || new Set(link.childJointIds).size !== link.childJointIds.length || link.childJointIds.length > 1 || arrays<string>(link.childJointIds).some(id => !jointIds.has(id))) issues.push(`link_invalid:${link?.id}`);
  for (const joint of joints) { const parent = linkMap.get(joint?.parentLinkId); const child = linkMap.get(joint?.childLinkId); const axisLength = point(joint?.axis) ? vectorLength(joint.axis) : 0; const supportedAxis = joint?.type === 'revolute' ? axisLength > EPSILON && Math.abs(joint.axis.xMm) <= EPSILON && Math.abs(joint.axis.yMm) <= EPSILON && Math.abs(Math.abs(joint.axis.zMm / axisLength) - 1) <= EPSILON : axisLength > EPSILON; if (!joint || typeof joint !== 'object' || !parent || !child || parent.id === child.id || !['revolute', 'prismatic'].includes(joint.type) || !point(joint.originMm) || !point(joint.axis) || !supportedAxis || !finite(joint.minValue) || !finite(joint.maxValue) || joint.minValue >= joint.maxValue || !arrays<string>(parent.childJointIds).includes(joint.id) || child.parentJointId !== joint.id) issues.push(`joint_chain_ownership_or_limits_invalid:${joint?.id}`); }
  for (const tool of tools) if (!tool || typeof tool !== 'object' || !linkIds.has(tool.linkId) || !point(tool.tipOffsetMm) || !nonnegative(tool.payloadKg)) issues.push(`tool_invalid_or_dangling:${tool?.id}`);
  for (const fixture of fixtures) if (!fixture || typeof fixture !== 'object' || !point(fixture.originMm) || !positive(fixture.widthMm) || !positive(fixture.depthMm) || !positive(fixture.heightMm) || !nonnegative(fixture.clearanceMm)) issues.push(`fixture_invalid:${fixture?.id}`);
  for (const operation of operations) { const robot = robots.find(item => item?.id === operation?.robotId); const tool = toolMap.get(operation?.toolId); const sampleValues = arrays<readonly number[]>(operation?.sampleValues); if (!operation || typeof operation !== 'object' || !robot || !tool || !robot.toolIds.includes(operation.toolId) || !robot.operationIds.includes(operation.id) || !robot.linkIds.includes(tool.linkId) || tool.linkId !== terminalLinkId(robot, links, joints) || arrays<string>(operation.jointIds).length !== robot.jointIds.length || arrays<string>(operation.jointIds).some((id, index) => id !== robot.jointIds[index]) || sampleValues.length === 0 || sampleValues.some(sample => sample.length !== robot.jointIds.length || sample.some((value: unknown, index: number) => !finite(value) || value < (jointMap.get(robot.jointIds[index]!)?.minValue ?? 0) || value > (jointMap.get(robot.jointIds[index]!)?.maxValue ?? 0))) || arrays<string>(operation.fixtureIds).some(id => !fixtureIds.has(id))) { issues.push(`operation_invalid_or_dangling:${operation?.id}`); continue; } const expected = fkEnvelope(robot, links, joints, sampleValues, tool); if (!point(operation.envelope.minMm) || !point(operation.envelope.maxMm) || !equal(operation.envelope.minMm.xMm, expected.minMm.xMm) || !equal(operation.envelope.minMm.yMm, expected.minMm.yMm) || !equal(operation.envelope.minMm.zMm, expected.minMm.zMm) || !equal(operation.envelope.maxMm.xMm, expected.maxMm.xMm) || !equal(operation.envelope.maxMm.yMm, expected.maxMm.yMm) || !equal(operation.envelope.maxMm.zMm, expected.maxMm.zMm)) issues.push(`operation_envelope_mismatch:${operation.id}`); for (const fixtureId of arrays<string>(operation.fixtureIds)) { const fixture = fixtureMap.get(fixtureId); if (fixture && boxesOverlap(expected, fixture)) issues.push(`fixture_collision:${operation.id}:${fixtureId}`); } }
  const output = input.output; if (!output || typeof output !== 'object' || output.format !== 'nexyfab-exchange-json' || !['step', 'urdf-neutral', 'json'].includes(output.targetFormat) || output.revision !== input.revision || typeof output.content !== 'string' || !Number.isSafeInteger(output.bytes) || output.bytes !== Buffer.byteLength(output.content, 'utf8') || !SHA256.test(output.sha256) || sha256(output.content) !== output.sha256) issues.push('output_binding_invalid'); else { try { if (!verifyRobotCellReadback(input, parseRobotCellOutput(input)).valid) issues.push('output_readback_invalid'); } catch { issues.push('output_readback_invalid'); } } return { valid: issues.length === 0, issues };
}
function verificationHash(value: Omit<RobotParserReadbackV1, 'verificationSha256'>): string { return sha256(JSON.stringify({ ...value, robotIds: [...value.robotIds].sort(), linkIds: [...value.linkIds].sort(), jointIds: [...value.jointIds].sort(), toolIds: [...value.toolIds].sort(), fixtureIds: [...value.fixtureIds].sort(), operationIds: [...value.operationIds].sort() })); }
export function parseRobotCellOutput(input: RobotCellReleaseInputV1): RobotParserReadbackV1 { let parsed: unknown; try { parsed = JSON.parse(input.output.content) as unknown; } catch { throw new Error('ROBOT_CELL_OUTPUT_JSON_INVALID'); } const keys = ['schema', 'revision', 'sourceWorkspaceId', 'sourceModelId', 'sourceModelSha256', 'sourceLibrarySha256', 'sourceRawArtifactSha256', 'sourceContentHash', 'robotIds', 'linkIds', 'jointIds', 'toolIds', 'fixtureIds', 'operationIds'] as const; if (!exactKeys(parsed, keys) || parsed.schema !== ROBOT_CELL_KINEMATIC_EXCHANGE_SCHEMA || !Number.isSafeInteger(parsed.revision) || typeof parsed.sourceWorkspaceId !== 'string' || !parsed.sourceWorkspaceId.trim() || typeof parsed.sourceModelId !== 'string' || !parsed.sourceModelId.trim() || ![parsed.sourceModelSha256, parsed.sourceLibrarySha256, parsed.sourceRawArtifactSha256, parsed.sourceContentHash].every(value => typeof value === 'string' && SHA256.test(value)) || !keys.slice(8).every(key => stableIdArray(parsed[key]))) throw new Error('ROBOT_CELL_OUTPUT_SCHEMA_INVALID'); const exchange = parsed as unknown as RobotCellExchangeV1; const unsigned = { parserId: PARSER_ID, parserSourceSha256: sha256(parseRobotCellOutput.toString()), sourceWorkspaceId: exchange.sourceWorkspaceId, sourceModelId: exchange.sourceModelId, sourceModelSha256: exchange.sourceModelSha256, sourceLibrarySha256: exchange.sourceLibrarySha256, sourceRawArtifactSha256: exchange.sourceRawArtifactSha256, sourceContentHash: exchange.sourceContentHash, sourceRevision: exchange.revision, outputSha256: sha256(input.output.content), robotIds: exchange.robotIds, linkIds: exchange.linkIds, jointIds: exchange.jointIds, toolIds: exchange.toolIds, fixtureIds: exchange.fixtureIds, operationIds: exchange.operationIds } as const; return { ...unsigned, verificationSha256: verificationHash(unsigned) }; }
export function verifyRobotCellReadback(input: RobotCellReleaseInputV1, readback: RobotParserReadbackV1 | null | undefined): RobotReadbackResult { if (!readback || typeof readback !== 'object') return { valid: false, issues: ['readback_missing'] }; const expected = { parserId: PARSER_ID, parserSourceSha256: sha256(parseRobotCellOutput.toString()), sourceWorkspaceId: input.source.workspaceId, sourceModelId: input.source.modelId, sourceModelSha256: input.source.modelSha256, sourceLibrarySha256: input.source.librarySha256, sourceRawArtifactSha256: input.source.rawArtifactSha256, sourceContentHash: input.source.contentHash, sourceRevision: input.revision, outputSha256: sha256(input.output.content), robotIds: input.robots.map(item => item.id), linkIds: input.links.map(item => item.id), jointIds: input.joints.map(item => item.id), toolIds: input.tools.map(item => item.id), fixtureIds: input.fixtures.map(item => item.id), operationIds: input.operations.map(item => item.id) } as const; const issues: string[] = []; for (const key of ['parserId', 'parserSourceSha256', 'sourceWorkspaceId', 'sourceModelId', 'sourceModelSha256', 'sourceLibrarySha256', 'sourceRawArtifactSha256', 'sourceContentHash', 'sourceRevision', 'outputSha256', 'robotIds', 'linkIds', 'jointIds', 'toolIds', 'fixtureIds', 'operationIds'] as const) if (JSON.stringify(readback[key]) !== JSON.stringify(expected[key])) issues.push(`readback_${key}_mismatch`); const { verificationSha256, ...unsigned } = readback; if (verificationSha256 !== verificationHash(unsigned)) issues.push('readback_verification_hash_invalid'); return { valid: issues.length === 0, issues }; }
export function assessRobotCellRelease(input: RobotCellReleaseInputV1, readback?: RobotParserReadbackV1 | null): RobotReleaseAssessment { const validation = validateRobotCellKinematicRelease(input); const internalParserVerified = readback ? verifyRobotCellReadback(input, readback).valid : false; const independentAttestationVerified = false; const blockers: string[] = [...holdBoundary]; if (!validation.valid) blockers.unshift(...validation.issues); blockers.unshift('independent_parser_attestation_required'); return { schema: ROBOT_CELL_KINEMATIC_RELEASE_SCHEMA, releaseReady: false, status: 'HOLD', internalParserVerified, independentAttestationVerified, parserVerified: false, blockers, holdBoundary }; }
