type V3 = [number, number, number];
export interface SolarPosition { elevationDeg: number; azimuthDeg: number; directionEnu: V3 }
const rad = (degrees: number) => degrees * Math.PI / 180, deg = (radians: number) => radians * 180 / Math.PI;
export function calculateSolarPosition(latitudeDeg: number, longitudeDeg: number, instant: Date): SolarPosition {
  if (latitudeDeg < -90 || latitudeDeg > 90 || longitudeDeg < -180 || longitudeDeg > 180 || ![latitudeDeg, longitudeDeg, instant.getTime()].every(Number.isFinite)) throw new Error('Solar location and instant are invalid.');
  const yearStart = Date.UTC(instant.getUTCFullYear(), 0, 0), day = Math.floor((instant.getTime() - yearStart) / 86_400_000), hour = instant.getUTCHours() + instant.getUTCMinutes() / 60 + instant.getUTCSeconds() / 3600, gamma = 2 * Math.PI / 365 * (day - 1 + (hour - 12) / 24);
  const equationMinutes = 229.18 * (0.000075 + 0.001868 * Math.cos(gamma) - 0.032077 * Math.sin(gamma) - 0.014615 * Math.cos(2 * gamma) - 0.040849 * Math.sin(2 * gamma)), declination = 0.006918 - 0.399912 * Math.cos(gamma) + 0.070257 * Math.sin(gamma) - 0.006758 * Math.cos(2 * gamma) + 0.000907 * Math.sin(2 * gamma) - 0.002697 * Math.cos(3 * gamma) + 0.00148 * Math.sin(3 * gamma), solarMinutes = ((hour * 60 + equationMinutes + 4 * longitudeDeg) % 1440 + 1440) % 1440, hourAngle = rad(solarMinutes / 4 - 180), latitude = rad(latitudeDeg), cosineZenith = Math.max(-1, Math.min(1, Math.sin(latitude) * Math.sin(declination) + Math.cos(latitude) * Math.cos(declination) * Math.cos(hourAngle))), elevation = Math.asin(cosineZenith), azimuth = Math.atan2(Math.sin(hourAngle), Math.cos(hourAngle) * Math.sin(latitude) - Math.tan(declination) * Math.cos(latitude)) + Math.PI;
  return { elevationDeg: deg(elevation), azimuthDeg: (deg(azimuth) + 360) % 360, directionEnu: [Math.sin(azimuth) * Math.cos(elevation), Math.cos(azimuth) * Math.cos(elevation), Math.sin(elevation)] };
}

export interface SolarObstacle { id: string; minMm: V3; maxMm: V3 }
export interface DaylightWindow { id: string; centerMm: V3; outwardNormalEnu: V3; glazingAreaMm2: number; visibleTransmittance: number }
export interface WindowSunSample { instant: string; sunAboveHorizon: boolean; facesSun: boolean; obstructed: boolean; directSun: boolean; obstructingIds: string[] }
export interface WindowSunAccess { windowId: string; directSunHours: number; samples: WindowSunSample[]; method: 'solar_position_ray_aabb' }
function rayHitsBox(origin: V3, direction: V3, obstacle: SolarObstacle): boolean { let near = 0, far = Number.POSITIVE_INFINITY; for (let axis = 0; axis < 3; axis++) { if (Math.abs(direction[axis]!) < 1e-12) { if (origin[axis]! < obstacle.minMm[axis]! || origin[axis]! > obstacle.maxMm[axis]!) return false; continue; } let first = (obstacle.minMm[axis]! - origin[axis]!) / direction[axis]!, second = (obstacle.maxMm[axis]! - origin[axis]!) / direction[axis]!; if (first > second) [first, second] = [second, first]; near = Math.max(near, first); far = Math.min(far, second); if (near > far) return false; } return far > 1e-6; }
export function calculateWindowSunAccess(latitudeDeg: number, longitudeDeg: number, instants: Date[], windows: DaylightWindow[], obstacles: SolarObstacle[]): WindowSunAccess[] {
  if (instants.length < 2) throw new Error('At least two ordered solar samples are required.');
  const times = instants.map(item => item.getTime()); if (times.some((value, index) => !Number.isFinite(value) || (index > 0 && value <= times[index - 1]!))) throw new Error('Solar sample instants must be valid and strictly increasing.');
  return windows.map(window => { const normalLength = Math.hypot(...window.outwardNormalEnu); if (Math.abs(normalLength - 1) > 1e-6 || !(window.glazingAreaMm2 > 0) || !(window.visibleTransmittance > 0 && window.visibleTransmittance <= 1)) throw new Error(`${window.id}: invalid window daylight properties.`); const samples = instants.map(instant => { const solar = calculateSolarPosition(latitudeDeg, longitudeDeg, instant), above = solar.elevationDeg > 0, faces = window.outwardNormalEnu.reduce((sum, value, axis) => sum + value * solar.directionEnu[axis]!, 0) > 0, obstructingIds = above && faces ? obstacles.filter(obstacle => rayHitsBox(window.centerMm, solar.directionEnu, obstacle)).map(item => item.id) : []; return { instant: instant.toISOString(), sunAboveHorizon: above, facesSun: faces, obstructed: obstructingIds.length > 0, directSun: above && faces && obstructingIds.length === 0, obstructingIds }; }); let directSunHours = 0; for (let index = 0; index < samples.length - 1; index++) if (samples[index]!.directSun && samples[index + 1]!.directSun) directSunHours += (times[index + 1]! - times[index]!) / 3_600_000; return { windowId: window.id, directSunHours, samples, method: 'solar_position_ray_aabb' }; });
}

export interface DaylightSimulationEvidence { ran: boolean; engine: string; weatherFileHash: string; sensorCount: number; spatialDaylightAutonomyPercent: number; annualSunlightExposurePercent: number }
export interface DaylightCriteria { minimumSpatialDaylightAutonomyPercent: number; maximumAnnualSunlightExposurePercent: number }
export function gateDaylightRelease(evidence?: DaylightSimulationEvidence, criteria?: DaylightCriteria): { status: 'passed' | 'failed' | 'not_run'; reason: string } {
  if (!evidence?.ran || !evidence.engine.trim() || !evidence.weatherFileHash.trim() || evidence.sensorCount < 1) return { status: 'not_run', reason: 'Executed annual daylight simulation evidence and weather-file provenance are required.' };
  if (![evidence.spatialDaylightAutonomyPercent, evidence.annualSunlightExposurePercent].every(value => Number.isFinite(value) && value >= 0 && value <= 100)) return { status: 'failed', reason: 'Annual daylight metrics are invalid.' };
  if (!criteria || ![criteria.minimumSpatialDaylightAutonomyPercent, criteria.maximumAnnualSunlightExposurePercent].every(value => Number.isFinite(value) && value >= 0 && value <= 100)) return { status: 'not_run', reason: 'Governed project daylight criteria are required.' };
  return evidence.spatialDaylightAutonomyPercent >= criteria.minimumSpatialDaylightAutonomyPercent && evidence.annualSunlightExposurePercent <= criteria.maximumAnnualSunlightExposurePercent ? { status: 'passed', reason: 'Annual daylight evidence satisfies governed criteria.' } : { status: 'failed', reason: 'Annual daylight evidence does not satisfy governed criteria.' };
}
