import type { DbAdapter } from '@/lib/db-adapter';
import type { StorageAdapter } from '@/lib/storage';
import { decodeAgenticCommercialReceiptEnvelope, encodeAgenticCommercialReceiptEnvelope, type DecodedAgenticCommercialReceiptEnvelope } from './agenticCommercialReceiptCodec';
import { agenticCommercialSha256 } from './agenticCommercialQualificationReceipt';

const SHA256 = /^[a-f0-9]{64}$/;
const ID = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const MAX_BYTES = 128 * 1024 * 1024;
export interface VerifiedAgenticCommercialReceiptInput { receiptId: string; tenantId: string; projectId: string; executionId: string; generationRunId: string; revision: number; modelContentHash: string; targetSha256: string; candidateEnvelopeSha256: string; finalEnvelopeBytes: Uint8Array; verifierKeyId: string; verifierFingerprintSha256: string; issuedAt: string; expiresAt: string; }
export interface VerifiedAgenticCommercialReceipt extends VerifiedAgenticCommercialReceiptInput { finalEnvelopeSha256: string; objectKey?: string; payload: Record<string, unknown>; }
export interface VerifiedAgenticCommercialReceiptStore { put(value: VerifiedAgenticCommercialReceiptInput): Promise<{ ok: true; objectKey?: string; finalEnvelopeSha256: string } | { ok: false; code: string }>; get(tenantId: string, projectId: string, receiptId: string): Promise<VerifiedAgenticCommercialReceipt | undefined>; }

function validInput(value: VerifiedAgenticCommercialReceiptInput): boolean { const issued = Date.parse(value.issuedAt), expires = Date.parse(value.expiresAt); return ID.test(value.receiptId) && ID.test(value.tenantId) && ID.test(value.projectId) && ID.test(value.executionId) && ID.test(value.generationRunId) && Number.isSafeInteger(value.revision) && value.revision >= 0 && SHA256.test(value.modelContentHash) && SHA256.test(value.targetSha256) && SHA256.test(value.candidateEnvelopeSha256) && SHA256.test(value.verifierFingerprintSha256) && ID.test(value.verifierKeyId) && value.finalEnvelopeBytes instanceof Uint8Array && value.finalEnvelopeBytes.length > 0 && value.finalEnvelopeBytes.length <= MAX_BYTES && Number.isFinite(issued) && Number.isFinite(expires) && expires > issued; }
function binding(decoded: DecodedAgenticCommercialReceiptEnvelope, value: VerifiedAgenticCommercialReceiptInput): boolean { if (decoded.kind !== 'final') return false; const payload = decoded.payload; const project = payload.project as Record<string, unknown> | undefined; const parser = payload.parser as Record<string, unknown> | undefined; const journal = payload.executionJournal as Record<string, unknown> | undefined; return payload.executionId === value.executionId && payload.generationRunId === value.generationRunId && SHA256.test(String(payload.generationProgramSha256 ?? '')) && payload.targetSha256 === value.targetSha256 && project?.projectId === value.projectId && project.revision === value.revision && project.modelContentHash === value.modelContentHash && SHA256.test(String(payload.artifactManifestSha256 ?? '')) && SHA256.test(String(parser?.receiptSha256 ?? '')) && SHA256.test(String(journal?.sha256 ?? '')); }
function decode(value: VerifiedAgenticCommercialReceiptInput): DecodedAgenticCommercialReceiptEnvelope | undefined { try { const decoded = decodeAgenticCommercialReceiptEnvelope(value.finalEnvelopeBytes); const candidateSha = agenticCommercialSha256(encodeAgenticCommercialReceiptEnvelope('candidate', decoded.payload)); return binding(decoded, value) && candidateSha === value.candidateEnvelopeSha256 ? decoded : undefined; } catch { return undefined; } }
function safeKey(key: string): boolean { return key.startsWith('private/verified-agentic-commercial-receipts/') && !key.includes('..') && !key.includes('\\') && key.length <= 1024; }

export async function assertVerifiedAgenticCommercialReceiptMigration(db: DbAdapter): Promise<void> { const row = await db.queryOne<{ version: number; checksum?: string }>('SELECT version, checksum FROM nf_schema_migrations WHERE version = ?', 2026082206).catch(() => undefined); const expected = process.env.POSTGRES_MIGRATION_CHECKSUM_2026082206?.trim(); if (!row || Number(row.version) !== 2026082206 || !SHA256.test(row.checksum ?? '') || (expected && expected !== row.checksum)) throw new Error('verified_agentic_receipt_migration_required:v2026082206'); }

export function createDbVerifiedAgenticCommercialReceiptStore(db: DbAdapter, storage: StorageAdapter): VerifiedAgenticCommercialReceiptStore {
  return {
    async put(value) {
      if (!validInput(value)) return { ok: false, code: 'VERIFIED_RECEIPT_METADATA_INVALID' };
      const decoded = decode(value); if (!decoded) return { ok: false, code: 'FINAL_ENVELOPE_INVALID_OR_UNBOUND' };
      const finalSha = agenticCommercialSha256(value.finalEnvelopeBytes); await assertVerifiedAgenticCommercialReceiptMigration(db);
      const existing = await db.queryOne<Record<string, unknown>>('SELECT * FROM nf_agentic_commercial_verified_receipts WHERE receipt_id = ?', value.receiptId);
      if (existing) return existing.final_envelope_sha256 === finalSha && existing.tenant_id === value.tenantId && existing.project_id === value.projectId && existing.execution_id === value.executionId && existing.generation_run_id === value.generationRunId && Number(existing.revision) === value.revision && existing.model_content_hash === value.modelContentHash && existing.target_sha256 === value.targetSha256 && existing.candidate_envelope_sha256 === value.candidateEnvelopeSha256 ? { ok: true, objectKey: String(existing.object_key), finalEnvelopeSha256: finalSha } : { ok: false, code: 'VERIFIED_RECEIPT_IMMUTABLE_CONFLICT' };
      if (!storage.download || !storage.sha256) return { ok: false, code: 'PRIVATE_STORAGE_HASH_REQUIRED' };
      const uploaded = await storage.uploadPrivate(Buffer.from(value.finalEnvelopeBytes), `${finalSha}.json`, `verified-agentic-commercial-receipts/${value.tenantId}/${value.projectId}/${value.receiptId}`); if (!safeKey(uploaded.key) || uploaded.size !== value.finalEnvelopeBytes.length) { await storage.delete(uploaded.key).catch(() => undefined); return { ok: false, code: 'PRIVATE_STORAGE_BINDING_INVALID' }; }
      const authoritative = await storage.sha256(uploaded.key).catch(() => undefined); if (!authoritative || authoritative.size !== value.finalEnvelopeBytes.length || authoritative.contentSha256 !== finalSha) { await storage.delete(uploaded.key).catch(() => undefined); return { ok: false, code: 'PRIVATE_STORAGE_HASH_INVALID' }; }
      const artifactManifest = typeof (decoded.payload as { artifactManifestSha256?: unknown }).artifactManifestSha256 === 'string' ? (decoded.payload as { artifactManifestSha256: string }).artifactManifestSha256 : '';
      const parser = (decoded.payload as { parser?: { receiptSha256?: unknown } }).parser?.receiptSha256; const journal = (decoded.payload as { executionJournal?: { sha256?: unknown } }).executionJournal?.sha256;
      if (!SHA256.test(artifactManifest) || typeof parser !== 'string' || !SHA256.test(parser) || typeof journal !== 'string' || !SHA256.test(journal)) { await storage.delete(uploaded.key).catch(() => undefined); return { ok: false, code: 'FINAL_RECEIPT_BINDING_FIELDS_MISSING' }; }
      try {
        await db.transaction(async tx => { await tx.execute('INSERT INTO nf_agentic_commercial_verified_receipts (receipt_id, tenant_id, project_id, execution_id, generation_run_id, revision, model_content_hash, target_sha256, artifact_manifest_sha256, parser_receipt_sha256, execution_journal_sha256, candidate_envelope_sha256, final_envelope_sha256, object_key, byte_length, issued_at, expires_at, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', value.receiptId, value.tenantId, value.projectId, value.executionId, value.generationRunId, value.revision, value.modelContentHash, value.targetSha256, artifactManifest, parser, journal, value.candidateEnvelopeSha256, finalSha, uploaded.key, value.finalEnvelopeBytes.length, value.issuedAt, value.expiresAt, Date.now()); await tx.execute('INSERT INTO nf_agentic_commercial_verified_ledger (final_envelope_sha256, receipt_id, candidate_envelope_sha256, verifier_key_id, verifier_fingerprint_sha256, committed_at) VALUES (?, ?, ?, ?, ?, ?)', finalSha, value.receiptId, value.candidateEnvelopeSha256, value.verifierKeyId, value.verifierFingerprintSha256, Date.now()); });
      } catch { await storage.delete(uploaded.key).catch(() => undefined); return { ok: false, code: 'VERIFIED_RECEIPT_IMMUTABLE_CONFLICT' }; }
      return { ok: true, objectKey: uploaded.key, finalEnvelopeSha256: finalSha };
    },
    async get(tenantId, projectId, receiptId) {
      if (!ID.test(tenantId) || !ID.test(projectId) || !ID.test(receiptId) || !storage.download) return undefined;
      await assertVerifiedAgenticCommercialReceiptMigration(db); const row = await db.queryOne<Record<string, unknown>>('SELECT * FROM nf_agentic_commercial_verified_receipts WHERE tenant_id = ? AND project_id = ? AND receipt_id = ?', tenantId, projectId, receiptId); if (!row || typeof row.object_key !== 'string' || !safeKey(row.object_key)) return undefined;
      const ledger = await db.queryOne<Record<string, unknown>>('SELECT candidate_envelope_sha256, verifier_key_id, verifier_fingerprint_sha256 FROM nf_agentic_commercial_verified_ledger WHERE final_envelope_sha256 = ? AND receipt_id = ?', row.final_envelope_sha256, receiptId);
      if (!ledger || ledger.candidate_envelope_sha256 !== row.candidate_envelope_sha256 || !ID.test(String(ledger.verifier_key_id ?? '')) || !SHA256.test(String(ledger.verifier_fingerprint_sha256 ?? ''))) return undefined;
      const raw = await storage.download(row.object_key).catch(() => undefined); if (!raw || raw.length !== Number(row.byte_length) || agenticCommercialSha256(raw) !== row.final_envelope_sha256) return undefined;
      const bytes = new Uint8Array(raw); let decoded: DecodedAgenticCommercialReceiptEnvelope; try { decoded = decodeAgenticCommercialReceiptEnvelope(bytes); } catch { return undefined; }
      const value: VerifiedAgenticCommercialReceiptInput = { receiptId, tenantId, projectId, executionId: String(row.execution_id), generationRunId: String(row.generation_run_id), revision: Number(row.revision), modelContentHash: String(row.model_content_hash), targetSha256: String(row.target_sha256), candidateEnvelopeSha256: String(row.candidate_envelope_sha256), finalEnvelopeBytes: bytes, verifierKeyId: '', verifierFingerprintSha256: '', issuedAt: String(row.issued_at), expiresAt: String(row.expires_at) }; if (!binding(decoded, value)) return undefined;
      return { ...value, finalEnvelopeSha256: String(row.final_envelope_sha256), objectKey: row.object_key, payload: decoded.payload };
    },
  };
}

export function createInMemoryVerifiedAgenticCommercialReceiptStore(): VerifiedAgenticCommercialReceiptStore { const records = new Map<string, VerifiedAgenticCommercialReceipt>(); return { async put(value) { if (!validInput(value)) return { ok: false, code: 'VERIFIED_RECEIPT_METADATA_INVALID' }; const decoded = decode(value); if (!decoded) return { ok: false, code: 'FINAL_ENVELOPE_INVALID_OR_UNBOUND' }; const finalEnvelopeSha256 = agenticCommercialSha256(value.finalEnvelopeBytes); const key = `${value.tenantId}:${value.projectId}:${value.receiptId}`; const old = records.get(key); if (old) return old.finalEnvelopeSha256 === finalEnvelopeSha256 ? { ok: true, finalEnvelopeSha256 } : { ok: false, code: 'VERIFIED_RECEIPT_IMMUTABLE_CONFLICT' }; const result = { ...value, finalEnvelopeSha256, payload: decoded.payload, finalEnvelopeBytes: new Uint8Array(value.finalEnvelopeBytes) }; records.set(key, result); return { ok: true, finalEnvelopeSha256 }; }, async get(tenantId, projectId, receiptId) { const value = records.get(`${tenantId}:${projectId}:${receiptId}`); return value ? { ...value, finalEnvelopeBytes: new Uint8Array(value.finalEnvelopeBytes) } : undefined; } }; }
