/**
 * 2D→3D v1 — 결정론 재구성 (③): intent JSON → OpenSCAD 소스 + 해석적 재투영 뷰.
 * AI 산출물(intent)을 기하 게이트로 검증 후에만 형상 생성 — "LLM=이해, 결정론=형상".
 * 해석적 재투영(④ 검증 루프 입력): 파라메트릭이라 뷰 치수를 폐형식으로 계산 가능.
 */
export function gate(intent) {
  const errs = [];
  if (intent.type !== 'plate_with_holes') errs.push(`unsupported type '${intent.type}'`);
  for (const k of ['width', 'depth', 'thickness']) {
    if (!(intent[k] > 0 && intent[k] < 5000)) errs.push(`${k} out of range: ${intent[k]}`);
  }
  if (intent.thickness >= Math.min(intent.width, intent.depth)) errs.push('thickness ≥ min(width,depth) — 판재 아님');
  for (const [i, h] of (intent.holes ?? []).entries()) {
    if (!(h.d > 0 && h.d < Math.min(intent.width, intent.depth))) errs.push(`hole[${i}] d invalid`);
    if (!(h.x - h.d / 2 >= 0 && h.x + h.d / 2 <= intent.width)) errs.push(`hole[${i}] x=${h.x} outside plate`);
    if (!(h.y - h.d / 2 >= 0 && h.y + h.d / 2 <= intent.depth)) errs.push(`hole[${i}] y=${h.y} outside plate`);
  }
  return errs;
}

export function toOpenScad(intent) {
  const errs = gate(intent);
  if (errs.length) throw new Error('geometry gate: ' + errs.join('; '));
  const holes = (intent.holes ?? [])
    .map((h) => `    translate([${h.x}, ${h.y}, -1]) cylinder(h=${intent.thickness + 2}, d=${h.d}, $fn=64);`)
    .join('\n');
  return `// generated by drawing-to-3d v1 (deterministic reconstruction)
// intent: ${JSON.stringify(intent)}
difference() {
  cube([${intent.width}, ${intent.depth}, ${intent.thickness}]);
${holes}
}
`;
}

/** 해석적 재투영 — 3면도 외곽 치수+구멍 (검증 루프에서 원 도면 추출값과 대조) */
export function analyticViews(intent) {
  return {
    top: { w: intent.width, h: intent.depth, holes: intent.holes ?? [] },
    front: { w: intent.width, h: intent.thickness },
    side: { w: intent.depth, h: intent.thickness },
    consistency: {
      frontWidthEqualsTopWidth: true, // 파라메트릭이므로 구조적 보장 — 도면 추출값 대조는 verify에서
      sideWidthEqualsTopDepth: true,
    },
  };
}
