import { NextRequest, NextResponse } from 'next/server';
import { applyBuildingInteriorEdits, validateBuildingInteriorModel, type BuildingInteriorEdit, type BuildingInteriorModel } from '@/lib/ai/buildingInteriorDesign';
import { planBuildingInteriorChatEdit } from '@/lib/ai/buildingInteriorChatEdit';
import { editBuildingInteriorProject } from '@/lib/ai/buildingInteriorProjectAdapter';
import { validateUnifiedDesignProject, type UnifiedDesignProject } from '@/lib/ai/unifiedDesignProject';
import { boundedJsonError, readBoundedJson } from '@/lib/boundedJsonBody';
import { getTrustedClientIp } from '@/lib/client-ip'; import { rateLimit } from '@/lib/rate-limit';
export const runtime = 'nodejs'; export const dynamic = 'force-dynamic';
const MAX_INTERIOR_LAYOUT_EDIT_BODY_BYTES = 16 * 1024 * 1024;
export async function POST(req: NextRequest) { const ip = getTrustedClientIp(req.headers); if (!rateLimit(`cad-v1-interior-layout-edit:${ip}`, 60, 60_000).allowed) return NextResponse.json({ ok: false, code: 'RATE_LIMIT' }, { status: 429 }); type Body = { model?: BuildingInteriorModel; project?: UnifiedDesignProject; documentId?: string; edits?: BuildingInteriorEdit[]; selectedObjectId?: string; command?: string }; let body: Body | null; try { body = await readBoundedJson<Body>(req, MAX_INTERIOR_LAYOUT_EDIT_BODY_BYTES); } catch (error) { const bounded = boundedJsonError(error); if (bounded?.code === 'PAYLOAD_TOO_LARGE') return NextResponse.json({ ok: false, code: bounded.code }, { status: bounded.status }); body = null; } const document = body?.project?.documents.find(item => item.id === body.documentId); const model = body?.model ?? document?.payload as BuildingInteriorModel | undefined; if (!body || !model) return NextResponse.json({ ok: false, code: 'BAD_REQUEST', message: 'model, or project plus documentId, is required' }, { status: 400 }); const issues = [...validateBuildingInteriorModel(model), ...(body.project ? validateUnifiedDesignProject(body.project) : [])]; if (issues.length) return NextResponse.json({ ok: false, code: 'INVALID_MODEL', issues }, { status: 422 }); try { const edits = Array.isArray(body.edits) ? body.edits : body.selectedObjectId && body.command ? [planBuildingInteriorChatEdit(model, body.selectedObjectId, body.command)] : []; if (edits.length < 1 || edits.length > 100) return NextResponse.json({ ok: false, code: 'BAD_REQUEST', message: '1..100 edits or selectedObjectId plus command are required' }, { status: 400 }); if (body.project && body.documentId) { const transaction = editBuildingInteriorProject(body.project, body.documentId, edits); return NextResponse.json({ ok: transaction.committed, transaction, plannedEdits: edits, quoteOrRfqSideEffects: false }, { status: transaction.committed ? 200 : 409 }); } return NextResponse.json({ ok: true, ...applyBuildingInteriorEdits(model, edits), plannedEdits: edits, quoteOrRfqSideEffects: false }); } catch (error) { return NextResponse.json({ ok: false, code: 'INVALID_EDIT', message: error instanceof Error ? error.message : 'Invalid layout edit' }, { status: 422 }); } }
