import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { NextRequest } from 'next/server';
import { generateRobot6Axis } from '@/lib/ai/robot/robotGenerator';
import { ROBOT_6AXIS_DEMONSTRATOR_SPEC } from '@/lib/ai/robot/robotDemonstrator';
import { POST } from './route';

const enc = (value: unknown) => new TextEncoder().encode(`${JSON.stringify(value)}\n`); const artifact = new TextEncoder().encode('api integration evidence'); const hash = createHash('sha256').update(artifact).digest('hex');
const base = { manufacturer: 'M', revision: 'A', source: 'datasheet', artifactHash: hash, massSource: 'confirmed', interface: { axisRef: 'axis', mountingPlaneRef: 'face', shaftDiameterMm: 30 } };
const catalog = { schema: 'nexyfab.robot-component-catalog.v1', components: [{ ...base, id: 'M', model: 'M', kind: 'motor', massKg: 1, envelopeMm: { x: 60, y: 60, z: 100 }, ratedTorqueNm: 10, peakTorqueNm: 20, maxRpm: 5000, rotorInertiaKgM2: 0.01 }, { ...base, id: 'R', model: 'R', kind: 'reducer', massKg: 2, envelopeMm: { x: 90, y: 90, z: 80 }, ratio: 100, ratedOutputTorqueNm: 1000, peakOutputTorqueNm: 1500, maxInputRpm: 6000, efficiency: 0.9, backlashArcmin: 2 }, { ...base, id: 'B', model: 'B', kind: 'bearing', massKg: 0.5, envelopeMm: { x: 80, y: 80, z: 20 }, boreMm: 30, odMm: 80, widthMm: 20, dynamicLoadN: 20000, staticLoadN: 10000, limitingRpm: 5000 }], artifacts: [{ path: 'evidence.pdf', sha256: hash, source: 'datasheet' }] };
const requirements = { schema: 'nexyfab.robot-selection-requirements.v1', requirements: Array.from({ length: 6 }, (_, i) => ({ joint: i + 1, requiredOutputTorqueNm: 100, requiredOutputRpm: 10, radialLoadN: 1000, minShaftDiameterMm: 25, safetyFactor: 1.5 })) };
function request(z: number, ip: string) { const program = enc(generateRobot6Axis(ROBOT_6AXIS_DEMONSTRATOR_SPEC).program); const programHash = createHash('sha256').update(program).digest('hex'); const revision = { schema: 'nexyfab.ai-assembly-revision-package.v1', lineageId: 'robot-lineage', revision: 2, baseProgramHash: 'a'.repeat(64), programHash, programArtifact: `editable-program-${programHash}.json`, createdAt: '2026-08-09T00:00:00.000Z', sideEffects: { sourceModified: false, quoteCreated: false, rfqSent: false } }; const housing = { schema: 'nexyfab.robot-housing-capacities.v1', capacities: Array.from({ length: 6 }, (_, i) => ({ joint: i + 1, internalMm: { x: 110, y: 110, z }, radialClearanceMm: 5, axialClearanceMm: 10, source: 'measured CAD', artifactHash: hash })) }; const form = new FormData(); form.set('program', new File([program], 'program.json')); form.set('revision', new File([enc(revision)], 'revision.json')); form.set('housing', new File([enc(housing)], 'housing.json')); form.set('requirements', new File([enc(requirements)], 'requirements.json')); form.set('manifest', new File([enc(catalog)], 'catalog.json')); form.append('artifact', new File([artifact], 'evidence.pdf')); return new NextRequest('http://localhost/api/cad/v1/robot/integration/prepare', { method: 'POST', body: form, headers: { 'x-forwarded-for': ip } }); }
describe('CAD v1 robot integration prepare', () => {
  it('prepares an immutable review target without applying CAD', async () => { const response = await POST(request(240, 'integration-ok')); expect(response.status).toBe(200); const body = await response.json(); expect(body).toMatchObject({ ok: true, expertReviewRequired: true, cadModified: false, releaseReady: false, quoteOrRfqSideEffects: false, packet: { readiness: 'review_pending', cadIntegrationStatus: 'not_applied', releaseReady: false, sideEffects: { persisted: false, cadModified: false } } }); expect(body.packet.replacements).toHaveLength(6); });
  it('does not prepare a dimensionally invalid target', async () => { const response = await POST(request(100, 'integration-small')); expect(response.status).toBe(422); expect(await response.json()).toMatchObject({ ok: false, packet: { readiness: 'not_ready', replacements: [] }, cadModified: false }); });
  it('requires every governed input', async () => { const response = await POST(new NextRequest('http://localhost/api/cad/v1/robot/integration/prepare', { method: 'POST', body: new FormData(), headers: { 'x-forwarded-for': 'integration-empty' } })); expect(response.status).toBe(400); });
});
