// ─── Modeler shell chrome i18n (6-language standard) ────────────────────────
//
// One typed dict for the shell-v2 chrome (ModelerShell, HubFrame, side panes,
// viewport chips, banners, share modal). The interface enforces key parity
// across all six locales at compile time — same pattern as
// drawing/_content.tsx's PageDict and shapeDict.ts.
//
// Lang matching follows src/lib/i18n/normalize.ts: route segments
// ('kr','en','ja','cn','es','ar'), ISO codes ('ko','zh') and legacy variants
// all resolve through toIsoLang. RTL is handled at the root layout level
// (<html dir="rtl"> for ar) — no per-container work here.

import { toIsoLang, type IsoLang } from '@/lib/i18n/normalize';

// Sub-record key unions — typed so each locale must cover every entry.
type EntityTypeKey = 'line' | 'arc' | 'circle' | 'rect' | 'polygon' | 'ellipse' | 'slot' | 'nurbs';
type MateTypeKey =
  | 'coincident' | 'concentric' | 'distance' | 'angle' | 'parallel'
  | 'perpendicular' | 'tangent' | 'hinge' | 'slider' | 'gear';
type EngRouteKey = 'modeling' | 'cam' | 'mold' | 'sheet-metal' | 'plant' | 'hvac' | 'cost' | 'dfm';
type StdCategoryKey = 'all' | 'fastener' | 'bearing' | 'pulley' | 'rail' | 'spring' | 'gear';

export interface ShellDict {
  // ── ModelerShell · File menu ──
  fmNewDesign: string;
  fmOpen: string;
  fmSave: string;
  fmSaveAs: string;
  fmImport: string;
  fmExportStl: string;
  fmExportStep: string;
  fmExportPapercraft: string;
  fmExportSlice: string;
  fmAllProjects: string;
  fmBackToHub: string;
  // ── ModelerShell · relative time ('{n}' = number) ──
  tJustNow: string;
  tSecondsAgo: string;
  tMinutesAgo: string;
  tHoursAgo: string;
  tDaysAgo: string;
  // ── ModelerShell · title bar / mode chips ──
  modeSketch: string;
  modeAssembly: string;
  exitSketchHint: string;
  exitAssemblyHint: string;
  saving: string;
  saveError: string;
  versionConflict: string;
  savedAgo: string; // '{t}' = relative time
  autosaveReady: string;
  untitledFile: string;
  untitled: string;
  share: string;
  publish: string;
  toggleTheme: string;
  // ── ModelerShell · signup gate ──
  signupPdf: string;
  signupDxf: string;
  signupShare: string;
  signupAi: string;
  signupGeneric: string;
  // ── ModelerShell · drawer tabs / status bar ──
  drawerCost: string;
  drawerVariants: string;
  drawerMotion: string;
  drawerVersions: string;
  featCount: string; // '{n}'
  pillSynced: string;
  pillSaving: string;
  pillError: string;
  // ── ModelerShell · drawer contents ──
  variantsTitle: string;
  variantsDesc: string;
  runArrow: string;
  settings: string;
  drawerRunHint: string;
  feaTitle: string;
  feaPick: string;
  feaLinear: string;
  feaNonlinear: string;
  feaModal: string;
  feaLinearDesc: string;
  feaNonlinearDesc: string;
  feaModalDesc: string;
  costTitle: string;
  quantity: string;
  costEstimateBtn: string; // '{n}'
  dfmTitle: string;
  dfmNoRun: string;
  dfmOpenFull: string;
  // ── HubFrame ──
  navRecent: string;
  navProjects: string;
  navShared: string;
  navBranches: string;
  navAiStudio: string;
  navPartLibrary: string;
  comingSoon: string;
  soonChip: string;
  storage: string;
  projectsWord: string;
  planWord: string;
  guest: string;
  qsNewPart: string;
  qsNewPartSub: string;
  qsNewAsm: string;
  qsNewAsmSub: string;
  qsNewDrawing: string;
  qsNewDrawingSub: string;
  qsFromSketch: string;
  qsFromSketchSub: string;
  fromGuestMode: string;
  welcomeBack: string; // '{name}'
  startNoSignup: string;
  hubProjectsCount: string; // '{n}'
  searchPlaceholder: string;
  aiAssist: string;
  aiHeroTitle: string;
  aiHeroBody: string;
  openAiStudio: string;
  seeTutorial: string;
  startWithExample: string;
  recentlyOpened: string;
  tour60: string;
  acrossAll: string;
  viewAll: string;
  trySample: string;
  allProjects: string;
  opsDashboard: string;
  thName: string;
  thType: string;
  thUpdated: string;
  loading: string;
  noMatch: string; // '{q}'
  noProjectsYet: string;
  signInToSave: string;
  newPartCta: string;
  signIn: string;
  // ── GuestExpiryBanner ──
  guestMode: string;
  guestLocalOnly: string;
  signUpNow: string;
  // ── ShareProjectModal ──
  shareTitle: string;
  shareNoProject: string;
  emailAddress: string;
  roleViewer: string;
  roleEditor: string;
  add: string;
  members: string;
  shareEmpty: string;
  remove: string;
  ownerYou: string;
  shareNotFound: string;
  shareHint: string;
  shareInvited: string;
  close: string;
  // ── ModelerLeftPane ──
  tabFeatures: string;
  tabBodies: string;
  tabComponents: string;
  filterFeatures: string;
  noFeatures: string;
  noBodies: string;
  singleBody: string;
  // ── StandardPartsGrid ──
  stdCategories: Record<StdCategoryKey, string>;
  insertIntoAssembly: string;
  // ── ModelerRightPane ──
  tabInspector: string;
  tabEngineering: string;
  tabComments: string;
  selectToInspect: string;
  edgeGroup: string; // '{n}'
  edgesTitle: string;
  geometryTitle: string;
  paramsTitle: string;
  noEditableParams: string;
  analyzeTitle: string;
  dfmCheck: string;
  runLower: string;
  warnCount: string; // '{n}'
  feaRowLabel: string;
  costEstimate: string;
  motionStudy: string;
  simLower: string;
  triangles: string;
  controller: string;
  machine: string;
  exportGcode: string;
  appearance: string;
  material: string;
  engRoutes: Record<EngRouteKey, string>;
  catEngTitle: string;
  catSketchTitle: string;
  catAsmTitle: string;
  catReady: string;
  catRun: string;
  catFailed: string;
  catEmpty: string;
  // ── SketchLeftPane ──
  sketchPaneTitle: string;
  emptySketch: string;
  onXyPlane: string;
  entitiesTitle: string;
  noEntities: string;
  constraintsTitle: string;
  noConstraints: string;
  dimensionsTitle: string;
  noDimensions: string;
  errSyntax: string;
  errUnknownVar: string;
  errCycle: string;
  errRuntime: string;
  errNonFinite: string;
  valueOrExpr: string;
  clickToEdit: string;
  removeDimension: string;
  // ── SketchRightPane ──
  sketchProps: string;
  activeSelection: string;
  clickEntity: string;
  selectedLabel: string;
  typeLabel: string;
  infoLabel: string;
  construction: string;
  yes: string;
  constraintsOnSel: string;
  noSelection: string;
  noConstraintsOnEntity: string;
  unsatisfied: string;
  removeConstraint: string;
  noDimsOnEntity: string;
  solver: string;
  statusLower: string;
  entitiesLower: string;
  constraintsLower: string;
  constraintsShort: string;
  dimensionsLower: string;
  redundantLower: string;
  solveTime: string;
  sketchToolsLive: string;
  entityTypes: Record<EntityTypeKey, string>;
  // ── Assembly panes ──
  asmTitle: string;
  addMate: string;
  insertPartsFirst: string;
  noMatesYet: string;
  deleteWord: string;
  tabMates: string;
  noComponents: string;
  bomEmpty: string;
  thPart: string;
  thQty: string;
  thMass: string;
  totalRow: string;
  matesOn: string; // '{name}'
  billOfMaterials: string;
  calculatorsLive: string;
  mateTypes: Record<MateTypeKey, string>;
  // ── ViewportChips ──
  vpShaded: string;
  vpWireframe: string;
  vpEdges: string;
  vpSection: string;
  // ── SelectionBubble ──
  nEdge: string;
  nEdges: string;
  nFace: string;
  nFaces: string;
  nVertex: string;
  nVertices: string;
  nItem: string;
  nItems: string;
  editBtn: string;
  suppress: string;
  // ── sketchStatusUi ──
  stFullyConstrained: string;
  stUnderDefined: string; // '{dof}'
  stOverDefinedRedundant: string; // '{n}'
  stOverDefined: string;
  stConflicting: string;
}

const ko: ShellDict = {
  fmNewDesign: '새 디자인',
  fmOpen: '열기…',
  fmSave: '저장',
  fmSaveAs: '다른 이름으로 저장',
  fmImport: 'STEP/IGES 가져오기…',
  fmExportStl: 'STL 내보내기',
  fmExportStep: 'STEP 내보내기',
  fmExportPapercraft: '종이로 펼치기 (DXF)',
  fmExportSlice: '적층 슬라이스 (DXF)',
  fmAllProjects: '프로젝트 목록',
  fmBackToHub: '허브로',
  tJustNow: '방금',
  tSecondsAgo: '{n}초 전',
  tMinutesAgo: '{n}분 전',
  tHoursAgo: '{n}시간 전',
  tDaysAgo: '{n}일 전',
  modeSketch: '스케치 모드',
  modeAssembly: '어셈블리 모드',
  exitSketchHint: 'S 키로 나가기',
  exitAssemblyHint: 'A 키로 나가기',
  saving: '저장 중…',
  saveError: '저장 오류',
  versionConflict: '버전 충돌',
  savedAgo: '{t} 저장됨',
  autosaveReady: '자동 저장 대기',
  untitledFile: '무제.nxpart',
  untitled: '무제',
  share: '공유',
  publish: '게시',
  toggleTheme: '테마 전환',
  signupPdf: 'PDF 내보내기를 사용하려면 가입하세요',
  signupDxf: 'DWG/DXF 내보내기를 사용하려면 가입하세요',
  signupShare: '공유 링크 생성에 가입이 필요합니다',
  signupAi: 'AI 무제한 사용에 가입이 필요합니다',
  signupGeneric: '계속하려면 가입하세요',
  drawerCost: '비용',
  drawerVariants: '변형',
  drawerMotion: '모션',
  drawerVersions: '버전',
  featCount: '{n}개 피처',
  pillSynced: '동기화됨',
  pillSaving: '저장 중',
  pillError: '오류',
  variantsTitle: '설계 변형',
  variantsDesc: '크기 / 재료 / 피처 대안을 나란히 탐색.',
  runArrow: '실행 →',
  settings: '설정',
  drawerRunHint: '실행하면 전체 패널이 모달로 열리고 결과 오버레이가 뷰포트에 표시됩니다.',
  feaTitle: '유한요소해석',
  feaPick: '솔버 모드를 선택하고 실행하세요.',
  feaLinear: '선형',
  feaNonlinear: '비선형',
  feaModal: '모달',
  feaLinearDesc: '작은 변형 · 정적 응력 — Hookean 재료.',
  feaNonlinearDesc: '대변형 · 하이퍼탄성 (Mooney-Rivlin), Newton-Raphson 반복.',
  feaModalDesc: '고유주파수 · 진동 모드, inverse iteration.',
  costTitle: '비용 코파일럿',
  quantity: '수량',
  costEstimateBtn: '{n}개 단가 계산 →',
  dfmTitle: '제조성 분석 (DFM)',
  dfmNoRun: '아직 분석을 실행하지 않았습니다.',
  dfmOpenFull: '전체 패널 열기 →',
  navRecent: '최근',
  navProjects: '프로젝트',
  navShared: '공유된 항목',
  navBranches: '브랜치',
  navAiStudio: 'Nexy AI 스튜디오',
  navPartLibrary: '부품 라이브러리',
  comingSoon: '곧 출시',
  soonChip: '준비중',
  storage: '저장 용량',
  projectsWord: '프로젝트',
  planWord: '플랜',
  guest: '게스트',
  qsNewPart: '새 파트',
  qsNewPartSub: '솔리드 · 파라메트릭',
  qsNewAsm: '새 어셈블리',
  qsNewAsmSub: '부품 결합',
  qsNewDrawing: '새 도면',
  qsNewDrawingSub: '파트 또는 어셈블리에서',
  qsFromSketch: '스케치에서',
  qsFromSketchSub: 'DXF / SVG 가져오기',
  fromGuestMode: '게스트 작업',
  welcomeBack: '다시 오신 것을 환영합니다, {name}',
  startNoSignup: '시작해 볼까요 — 가입 없이 바로 설계',
  hubProjectsCount: '{n}개 프로젝트',
  searchPlaceholder: '파트·프로젝트·브랜치 검색…',
  aiAssist: '디자인 어시스트',
  aiHeroTitle: '자연어로 설명하면 파라메트릭 모델을 즉시 생성합니다.',
  aiHeroBody: 'Nexy AI 가 OpenSCAD 파이프라인으로 즉시 STL 출력까지 도와드립니다. 자동 DFM · 비용 추정 · 제조사 매칭 포함.',
  openAiStudio: 'AI 스튜디오 열기',
  seeTutorial: '튜토리얼 보기',
  startWithExample: '예제로 시작',
  recentlyOpened: '최근 열어본 항목',
  tour60: '60초 둘러보기',
  acrossAll: '모든 프로젝트',
  viewAll: '모두 보기 →',
  trySample: '예제 프로젝트로 60초 안에 둘러보기',
  allProjects: '모든 프로젝트',
  opsDashboard: '운영 대시보드 (주문·견적·정산) →',
  thName: '이름',
  thType: '유형',
  thUpdated: '수정일',
  loading: '불러오는 중…',
  noMatch: "'{q}' 에 해당하는 프로젝트가 없습니다.",
  noProjectsYet: '아직 프로젝트가 없습니다. 첫 파트를 만들어보세요.',
  signInToSave: '로그인하면 프로젝트가 클라우드에 영구 저장됩니다.',
  newPartCta: '+ 새 파트',
  signIn: '로그인',
  guestMode: '게스트 모드',
  guestLocalOnly: '작업물은 이 브라우저에만 저장돼요. 로그인하면 클라우드에 영구 저장됩니다.',
  signUpNow: '지금 가입',
  shareTitle: '프로젝트 공유',
  shareNoProject: '먼저 프로젝트를 저장하면 공유할 수 있습니다.',
  emailAddress: '이메일 주소',
  roleViewer: '보기 전용',
  roleEditor: '편집 가능',
  add: '추가',
  members: '멤버',
  shareEmpty: '아직 공유한 멤버가 없습니다.',
  remove: '제거',
  ownerYou: '소유자(나)',
  shareNotFound: '해당 이메일의 사용자를 찾을 수 없습니다.',
  shareHint: 'NexyFab 계정이 있으면 바로 추가되고, 없으면 초대 이메일이 발송됩니다. “공유된 항목”에 표시됩니다.',
  shareInvited: '초대 이메일을 보냈습니다. 상대가 수락하면 멤버로 추가됩니다.',
  close: '닫기',
  tabFeatures: '피처',
  tabBodies: '바디',
  tabComponents: '컴포넌트',
  filterFeatures: '피처 필터…',
  noFeatures: '기본 형상 활성 · 추가 피처 없음',
  noBodies: '바디 없음 — 피처를 만들면 솔리드 바디가 생깁니다.',
  singleBody: '현재 파트는 단일 솔리드 바디입니다.',
  stdCategories: { all: '전체', fastener: '체결', bearing: '베어링', pulley: '풀리', rail: '리니어 레일', spring: '스프링', gear: '기어' },
  insertIntoAssembly: '어셈블리에 추가',
  tabInspector: '인스펙터',
  tabEngineering: '엔지니어링',
  tabComments: '코멘트',
  selectToInspect: '피처나 엣지를 선택해 속성을 표시합니다.',
  edgeGroup: '{n}개 엣지 · 엣지 그룹',
  edgesTitle: '엣지',
  geometryTitle: '지오메트리',
  paramsTitle: '파라미터',
  noEditableParams: '편집 가능한 파라미터 없음',
  analyzeTitle: '분석',
  dfmCheck: 'DFM 검사',
  runLower: '실행',
  warnCount: '경고 {n}개',
  feaRowLabel: 'FEA · 정적/비선형/모달',
  costEstimate: '비용 예상',
  motionStudy: '모션 스터디',
  simLower: '시뮬',
  triangles: '삼각형',
  controller: '컨트롤러',
  machine: '머신',
  exportGcode: 'G-code 내보내기',
  appearance: '외형',
  material: '재질',
  engRoutes: { modeling: '모델링/역학', cam: 'CAM 가공', mold: '금형', 'sheet-metal': '판금', plant: '플랜트 배관', hvac: '공조', cost: '견적/원가', dfm: 'DFM' },
  catEngTitle: '엔지니어링 계산기',
  catSketchTitle: '스케치 도구',
  catAsmTitle: '체결/끼워맞춤 계산기',
  catReady: '준비됨',
  catRun: '실행',
  catFailed: '불러오기 실패',
  catEmpty: '해당 기능이 없습니다',
  sketchPaneTitle: '스케치 1 — 기본 프로파일',
  emptySketch: '빈 스케치 — 그리기로 시작',
  onXyPlane: 'XY 평면 위',
  entitiesTitle: '엔티티',
  noEntities: '엔티티 없음 — 라인 / 사각형 / 원으로 시작',
  constraintsTitle: '구속조건',
  noConstraints: '구속조건 없음',
  dimensionsTitle: '치수',
  noDimensions: '치수 없음',
  errSyntax: '수식 오류',
  errUnknownVar: '미정의 변수',
  errCycle: '순환 참조',
  errRuntime: '실행 오류',
  errNonFinite: '유효하지 않은 값',
  valueOrExpr: '값 또는 수식 (예: 2*D1)',
  clickToEdit: '클릭하여 편집',
  removeDimension: '치수 제거',
  sketchProps: '스케치 속성',
  activeSelection: '활성 선택',
  clickEntity: '선택 도구로 엔티티를 클릭하세요',
  selectedLabel: '선택',
  typeLabel: '유형',
  infoLabel: '정보',
  construction: '구성선',
  yes: '예',
  constraintsOnSel: '선택에 적용된 구속조건',
  noSelection: '선택 없음',
  noConstraintsOnEntity: '이 엔티티에 구속조건 없음',
  unsatisfied: '솔버가 만족시키지 못한 구속조건',
  removeConstraint: '구속조건 제거',
  noDimsOnEntity: '이 엔티티에 치수 없음 — 치수 도구로 추가',
  solver: '솔버',
  statusLower: '상태',
  entitiesLower: '엔티티',
  constraintsLower: '구속조건',
  constraintsShort: '구속',
  dimensionsLower: '치수',
  redundantLower: '잉여 구속',
  solveTime: '풀이 시간',
  sketchToolsLive: '스케치 도구 (라이브)',
  entityTypes: { line: '선', arc: '호', circle: '원', rect: '사각형', polygon: '다각형', ellipse: '타원', slot: '슬롯', nurbs: '스플라인' },
  asmTitle: '어셈블리',
  addMate: '메이트 추가',
  insertPartsFirst: '부품을 먼저 삽입하세요.',
  noMatesYet: '메이트가 없습니다. 위 버튼이나 리본의 메이트 도구로 추가하세요.',
  deleteWord: '삭제',
  tabMates: '메이트',
  noComponents: '아직 컴포넌트가 없습니다. 상단 Insert로 부품을 추가하세요.',
  bomEmpty: '부품이 없어 BOM이 비어 있습니다.',
  thPart: '부품',
  thQty: '수량',
  thMass: '중량',
  totalRow: '합계',
  matesOn: '{name} 메이트',
  billOfMaterials: '재료 명세서',
  calculatorsLive: '계산기 (라이브)',
  mateTypes: { coincident: '일치', concentric: '동심', distance: '거리', angle: '각도', parallel: '평행', perpendicular: '수직', tangent: '접함', hinge: '경첩', slider: '슬라이더', gear: '기어' },
  vpShaded: '음영',
  vpWireframe: '와이어',
  vpEdges: '모서리',
  vpSection: '단면',
  nEdge: '엣지',
  nEdges: '엣지',
  nFace: '면',
  nFaces: '면',
  nVertex: '꼭짓점',
  nVertices: '꼭짓점',
  nItem: '항목',
  nItems: '항목',
  editBtn: '편집',
  suppress: '억제',
  stFullyConstrained: '완전 정의 · DOF 0',
  stUnderDefined: '미정의 · DOF {dof}',
  stOverDefinedRedundant: '과정의 · 잉여 {n}개',
  stOverDefined: '과정의',
  stConflicting: '구속조건 충돌',
};

const en: ShellDict = {
  fmNewDesign: 'New Design',
  fmOpen: 'Open…',
  fmSave: 'Save',
  fmSaveAs: 'Save As…',
  fmImport: 'Import STEP/IGES…',
  fmExportStl: 'Export STL',
  fmExportStep: 'Export STEP',
  fmExportPapercraft: 'Unfold to papercraft (DXF)',
  fmExportSlice: 'Slice into layers (DXF)',
  fmAllProjects: 'All Projects',
  fmBackToHub: 'Back to Hub',
  tJustNow: 'just now',
  tSecondsAgo: '{n}s ago',
  tMinutesAgo: '{n}m ago',
  tHoursAgo: '{n}h ago',
  tDaysAgo: '{n}d ago',
  modeSketch: 'SKETCH MODE',
  modeAssembly: 'ASSEMBLY MODE',
  exitSketchHint: 'Press S to exit',
  exitAssemblyHint: 'Press A to exit',
  saving: 'Saving…',
  saveError: 'Save error',
  versionConflict: 'Version conflict',
  savedAgo: 'Saved · {t}',
  autosaveReady: 'Auto-save ready',
  untitledFile: 'Untitled.nxpart',
  untitled: 'Untitled',
  share: 'Share',
  publish: 'Publish',
  toggleTheme: 'Toggle theme',
  signupPdf: 'Sign up to export PDF',
  signupDxf: 'Sign up to export DWG/DXF',
  signupShare: 'Sign up to share your design',
  signupAi: 'Sign up for unlimited AI',
  signupGeneric: 'Sign up to continue',
  drawerCost: 'Cost',
  drawerVariants: 'Variants',
  drawerMotion: 'Motion',
  drawerVersions: 'Versions',
  featCount: '{n} feat',
  pillSynced: 'Synced',
  pillSaving: 'Saving',
  pillError: 'Error',
  variantsTitle: 'Design Variants',
  variantsDesc: 'Explore size, material, and feature alternatives side-by-side.',
  runArrow: 'Run →',
  settings: 'Settings',
  drawerRunHint: 'Click Run to launch the full panel as a modal with viewport overlay.',
  feaTitle: 'Finite Element Analysis',
  feaPick: 'Pick a solver mode and run.',
  feaLinear: 'Linear',
  feaNonlinear: 'Nonlinear',
  feaModal: 'Modal',
  feaLinearDesc: 'Small deformation · static stress — Hookean material.',
  feaNonlinearDesc: 'Large deformation · hyperelastic (Mooney-Rivlin), Newton-Raphson loop.',
  feaModalDesc: 'Natural frequency · vibration modes, inverse iteration.',
  costTitle: 'Cost Copilot',
  quantity: 'Quantity',
  costEstimateBtn: 'Estimate × {n} →',
  dfmTitle: 'Design for Manufacturing',
  dfmNoRun: 'No analysis run yet.',
  dfmOpenFull: 'Open full panel →',
  navRecent: 'Recent',
  navProjects: 'Projects',
  navShared: 'Shared with me',
  navBranches: 'Branches',
  navAiStudio: 'Nexy AI Studio',
  navPartLibrary: 'Part Library',
  comingSoon: 'Coming soon',
  soonChip: 'Soon',
  storage: 'Storage',
  projectsWord: 'projects',
  planWord: 'plan',
  guest: 'Guest',
  qsNewPart: 'New Part',
  qsNewPartSub: 'Solid · parametric',
  qsNewAsm: 'New Assembly',
  qsNewAsmSub: 'Mate components',
  qsNewDrawing: 'New Drawing',
  qsNewDrawingSub: 'From a part or assembly',
  qsFromSketch: 'From Sketch',
  qsFromSketchSub: 'Import DXF / SVG',
  fromGuestMode: 'from guest mode',
  welcomeBack: 'Welcome back, {name}',
  startNoSignup: 'Start designing — no sign-up needed',
  hubProjectsCount: '{n} projects',
  searchPlaceholder: 'Search parts, projects, branches…',
  aiAssist: 'Design Assist',
  aiHeroTitle: 'Describe a part in words — get a parametric 3D model instantly.',
  aiHeroBody: 'Nexy AI ships your idea straight to STL via OpenSCAD, with DFM, cost, and manufacturer matching baked in.',
  openAiStudio: 'Open AI Studio',
  seeTutorial: 'See tutorial',
  startWithExample: 'Start with an example',
  recentlyOpened: 'Recently opened',
  tour60: '60-second tour',
  acrossAll: 'Across all projects',
  viewAll: 'View all →',
  trySample: 'Try a sample project — explore in 60 seconds',
  allProjects: 'All projects',
  opsDashboard: 'Ops dashboard (orders · RFQ · settlements) →',
  thName: 'Name',
  thType: 'Type',
  thUpdated: 'Updated',
  loading: 'Loading…',
  noMatch: "No projects match '{q}'.",
  noProjectsYet: 'No projects yet — create your first part.',
  signInToSave: 'Sign in to save your projects to the cloud.',
  newPartCta: '+ New part',
  signIn: 'Sign in',
  guestMode: 'Guest mode',
  guestLocalOnly: 'Your work is saved in this browser only. Sign in to save it to the cloud.',
  signUpNow: 'Sign in',
  shareTitle: 'Share project',
  shareNoProject: 'Save the project first to share it.',
  emailAddress: 'Email address',
  roleViewer: 'Viewer',
  roleEditor: 'Editor',
  add: 'Add',
  members: 'Members',
  shareEmpty: 'No members yet.',
  remove: 'Remove',
  ownerYou: 'Owner (you)',
  shareNotFound: 'No user with that email.',
  shareHint: 'If they have a NexyFab account they’re added instantly; otherwise an email invite is sent. Appears under “Shared with me”.',
  shareInvited: 'Invite email sent — they become a member once they accept.',
  close: 'Close',
  tabFeatures: 'Features',
  tabBodies: 'Bodies',
  tabComponents: 'Components',
  filterFeatures: 'Filter features…',
  noFeatures: 'Base shape active · no added features',
  noBodies: 'No bodies — create a feature to form a solid body.',
  singleBody: 'This part is a single solid body.',
  stdCategories: { all: 'All', fastener: 'Fasteners', bearing: 'Bearings', pulley: 'Pulleys', rail: 'Linear rails', spring: 'Springs', gear: 'Gears' },
  insertIntoAssembly: 'Insert into assembly',
  tabInspector: 'Inspector',
  tabEngineering: 'Engineering',
  tabComments: 'Comments',
  selectToInspect: 'Select a feature or edge to inspect.',
  edgeGroup: 'Edge group · {n} edges',
  edgesTitle: 'Edges',
  geometryTitle: 'Geometry',
  paramsTitle: 'Parameters',
  noEditableParams: 'No editable parameters',
  analyzeTitle: 'Analyze',
  dfmCheck: 'DFM check',
  runLower: 'run',
  warnCount: '{n} warns',
  feaRowLabel: 'FEA — linear/nonlinear/modal',
  costEstimate: 'Cost estimate',
  motionStudy: 'Motion study',
  simLower: 'sim',
  triangles: 'Triangles',
  controller: 'Controller',
  machine: 'Machine',
  exportGcode: 'Export G-code',
  appearance: 'Appearance',
  material: 'Material',
  engRoutes: { modeling: 'Modeling/Dynamics', cam: 'CAM', mold: 'Mold', 'sheet-metal': 'Sheet Metal', plant: 'Plant Piping', hvac: 'HVAC', cost: 'Cost/Estimate', dfm: 'DFM' },
  catEngTitle: 'Engineering Calculators',
  catSketchTitle: 'Sketch Tools',
  catAsmTitle: 'Joint / Fit Calculators',
  catReady: 'Ready',
  catRun: 'Run',
  catFailed: 'Load failed',
  catEmpty: 'No matching feature',
  sketchPaneTitle: 'SKETCH 1 — BASE PROFILE',
  emptySketch: 'Empty sketch — start drawing',
  onXyPlane: 'On XY Plane',
  entitiesTitle: 'Entities',
  noEntities: 'No entities — draw a line / rect / circle to start',
  constraintsTitle: 'Constraints',
  noConstraints: 'No constraints',
  dimensionsTitle: 'Dimensions',
  noDimensions: 'No dimensions',
  errSyntax: 'Syntax error',
  errUnknownVar: 'Unknown variable',
  errCycle: 'Cyclic reference',
  errRuntime: 'Runtime error',
  errNonFinite: 'Non-finite value',
  valueOrExpr: 'Value or expression (e.g. 2*D1)',
  clickToEdit: 'Click to edit',
  removeDimension: 'Remove dimension',
  sketchProps: 'SKETCH PROPERTIES',
  activeSelection: 'Active Selection',
  clickEntity: 'Click an entity with the Select tool',
  selectedLabel: 'Selected',
  typeLabel: 'Type',
  infoLabel: 'Info',
  construction: 'Construction',
  yes: 'Yes',
  constraintsOnSel: 'Constraints on Selection',
  noSelection: 'No selection',
  noConstraintsOnEntity: 'No constraints on this entity',
  unsatisfied: 'Constraint the solver could not satisfy',
  removeConstraint: 'Remove constraint',
  noDimsOnEntity: 'No dimensions on this entity — add with the Dimension tool',
  solver: 'Solver',
  statusLower: 'status',
  entitiesLower: 'entities',
  constraintsLower: 'constraints',
  constraintsShort: 'constraints',
  dimensionsLower: 'dimensions',
  redundantLower: 'redundant',
  solveTime: 'solve time',
  sketchToolsLive: 'Sketch Tools (live)',
  entityTypes: { line: 'line', arc: 'arc', circle: 'circle', rect: 'rect', polygon: 'polygon', ellipse: 'ellipse', slot: 'slot', nurbs: 'spline' },
  asmTitle: 'ASSEMBLY',
  addMate: 'Add mate',
  insertPartsFirst: 'Insert parts first.',
  noMatesYet: 'No mates yet. Use the button above or the ribbon mate tools.',
  deleteWord: 'Delete',
  tabMates: 'Mates',
  noComponents: 'No components yet. Use Insert to add parts.',
  bomEmpty: 'No parts — the BOM is empty.',
  thPart: 'PART',
  thQty: 'QTY',
  thMass: 'MASS',
  totalRow: 'TOTAL',
  matesOn: 'MATES ON {name}',
  billOfMaterials: 'Bill of Materials',
  calculatorsLive: 'Calculators (live)',
  mateTypes: { coincident: 'Coincident', concentric: 'Concentric', distance: 'Distance', angle: 'Angle', parallel: 'Parallel', perpendicular: 'Perpendicular', tangent: 'Tangent', hinge: 'Hinge', slider: 'Slider', gear: 'Gear' },
  vpShaded: 'Shaded',
  vpWireframe: 'Wireframe',
  vpEdges: 'Edges',
  vpSection: 'Section',
  nEdge: 'edge',
  nEdges: 'edges',
  nFace: 'face',
  nFaces: 'faces',
  nVertex: 'vertex',
  nVertices: 'vertices',
  nItem: 'item',
  nItems: 'items',
  editBtn: 'Edit',
  suppress: 'Suppress',
  stFullyConstrained: 'Fully constrained · DOF 0',
  stUnderDefined: 'Under-defined · DOF {dof}',
  stOverDefinedRedundant: 'Over-defined · {n} redundant',
  stOverDefined: 'Over-defined',
  stConflicting: 'Conflicting constraints',
};

const ja: ShellDict = {
  fmNewDesign: '新規デザイン',
  fmOpen: '開く…',
  fmSave: '保存',
  fmSaveAs: '名前を付けて保存',
  fmImport: 'STEP/IGES をインポート…',
  fmExportStl: 'STL をエクスポート',
  fmExportStep: 'STEP をエクスポート',
  fmExportPapercraft: 'ペーパークラフトに展開 (DXF)',
  fmExportSlice: 'レイヤーにスライス (DXF)',
  fmAllProjects: 'すべてのプロジェクト',
  fmBackToHub: 'ハブに戻る',
  tJustNow: 'たった今',
  tSecondsAgo: '{n}秒前',
  tMinutesAgo: '{n}分前',
  tHoursAgo: '{n}時間前',
  tDaysAgo: '{n}日前',
  modeSketch: 'スケッチモード',
  modeAssembly: 'アセンブリモード',
  exitSketchHint: 'S キーで終了',
  exitAssemblyHint: 'A キーで終了',
  saving: '保存中…',
  saveError: '保存エラー',
  versionConflict: 'バージョン競合',
  savedAgo: '保存済み · {t}',
  autosaveReady: '自動保存 待機中',
  untitledFile: '無題.nxpart',
  untitled: '無題',
  share: '共有',
  publish: '公開',
  toggleTheme: 'テーマ切替',
  signupPdf: 'PDF エクスポートには登録が必要です',
  signupDxf: 'DWG/DXF エクスポートには登録が必要です',
  signupShare: '共有リンクの作成には登録が必要です',
  signupAi: 'AI 無制限利用には登録が必要です',
  signupGeneric: '続行するには登録してください',
  drawerCost: 'コスト',
  drawerVariants: 'バリエーション',
  drawerMotion: 'モーション',
  drawerVersions: 'バージョン',
  featCount: 'フィーチャー {n} 個',
  pillSynced: '同期済み',
  pillSaving: '保存中',
  pillError: 'エラー',
  variantsTitle: '設計バリエーション',
  variantsDesc: 'サイズ / 材料 / フィーチャーの代替案を並べて比較。',
  runArrow: '実行 →',
  settings: '設定',
  drawerRunHint: '実行するとフルパネルがモーダルで開き、結果オーバーレイがビューポートに表示されます。',
  feaTitle: '有限要素解析',
  feaPick: 'ソルバーモードを選択して実行してください。',
  feaLinear: '線形',
  feaNonlinear: '非線形',
  feaModal: 'モーダル',
  feaLinearDesc: '微小変形 · 静的応力 — フック弾性材料。',
  feaNonlinearDesc: '大変形 · 超弾性 (Mooney-Rivlin)、Newton-Raphson 反復。',
  feaModalDesc: '固有振動数 · 振動モード、逆反復法。',
  costTitle: 'コストコパイロット',
  quantity: '数量',
  costEstimateBtn: '{n}個の単価を計算 →',
  dfmTitle: '製造性解析 (DFM)',
  dfmNoRun: 'まだ解析を実行していません。',
  dfmOpenFull: 'フルパネルを開く →',
  navRecent: '最近',
  navProjects: 'プロジェクト',
  navShared: '共有アイテム',
  navBranches: 'ブランチ',
  navAiStudio: 'Nexy AI スタジオ',
  navPartLibrary: '部品ライブラリ',
  comingSoon: '近日公開',
  soonChip: '準備中',
  storage: 'ストレージ',
  projectsWord: 'プロジェクト',
  planWord: 'プラン',
  guest: 'ゲスト',
  qsNewPart: '新規パーツ',
  qsNewPartSub: 'ソリッド · パラメトリック',
  qsNewAsm: '新規アセンブリ',
  qsNewAsmSub: '部品を合致',
  qsNewDrawing: '新規図面',
  qsNewDrawingSub: 'パーツまたはアセンブリから',
  qsFromSketch: 'スケッチから',
  qsFromSketchSub: 'DXF / SVG をインポート',
  fromGuestMode: 'ゲストモードから',
  welcomeBack: 'おかえりなさい、{name} さん',
  startNoSignup: 'さっそく設計を始めましょう — 登録不要',
  hubProjectsCount: '{n} 件のプロジェクト',
  searchPlaceholder: 'パーツ・プロジェクト・ブランチを検索…',
  aiAssist: 'デザインアシスト',
  aiHeroTitle: '言葉で説明するだけで、パラメトリック 3D モデルを即座に生成。',
  aiHeroBody: 'Nexy AI が OpenSCAD パイプラインで STL 出力まで直行。DFM・コスト見積・メーカーマッチングも組み込み済み。',
  openAiStudio: 'AI スタジオを開く',
  seeTutorial: 'チュートリアルを見る',
  startWithExample: 'サンプルから始める',
  recentlyOpened: '最近開いたアイテム',
  tour60: '60秒ツアー',
  acrossAll: 'すべてのプロジェクト',
  viewAll: 'すべて表示 →',
  trySample: 'サンプルプロジェクトを試す — 60秒で体験',
  allProjects: 'すべてのプロジェクト',
  opsDashboard: '運用ダッシュボード（注文·見積·精算）→',
  thName: '名前',
  thType: '種類',
  thUpdated: '更新日',
  loading: '読み込み中…',
  noMatch: "'{q}' に一致するプロジェクトはありません。",
  noProjectsYet: 'プロジェクトはまだありません。最初のパーツを作成しましょう。',
  signInToSave: 'サインインするとプロジェクトがクラウドに保存されます。',
  newPartCta: '+ 新規パーツ',
  signIn: 'サインイン',
  guestMode: 'ゲストモード',
  guestLocalOnly: '作業データはこのブラウザにのみ保存されます。サインインするとクラウドに永続保存されます。',
  signUpNow: '今すぐ登録',
  shareTitle: 'プロジェクトを共有',
  shareNoProject: '共有するには、まずプロジェクトを保存してください。',
  emailAddress: 'メールアドレス',
  roleViewer: '閲覧のみ',
  roleEditor: '編集可能',
  add: '追加',
  members: 'メンバー',
  shareEmpty: '共有しているメンバーはまだいません。',
  remove: '削除',
  ownerYou: '所有者（自分）',
  shareNotFound: 'そのメールアドレスのユーザーが見つかりません。',
  shareHint: 'NexyFab アカウントがあれば即座に追加され、なければ招待メールが送信されます。「共有アイテム」に表示されます。',
  shareInvited: '招待メールを送信しました。承諾されるとメンバーに追加されます。',
  close: '閉じる',
  tabFeatures: 'フィーチャー',
  tabBodies: 'ボディ',
  tabComponents: 'コンポーネント',
  filterFeatures: 'フィーチャーを絞り込み…',
  noFeatures: '基本形状が有効 · 追加フィーチャーなし',
  noBodies: 'ボディなし — フィーチャーを作成するとソリッドボディが生成されます。',
  singleBody: 'このパーツは単一のソリッドボディです。',
  stdCategories: { all: 'すべて', fastener: '締結部品', bearing: 'ベアリング', pulley: 'プーリー', rail: 'リニアレール', spring: 'ばね', gear: '歯車' },
  insertIntoAssembly: 'アセンブリに挿入',
  tabInspector: 'インスペクタ',
  tabEngineering: 'エンジニアリング',
  tabComments: 'コメント',
  selectToInspect: 'フィーチャーまたはエッジを選択するとプロパティを表示します。',
  edgeGroup: 'エッジグループ · {n} エッジ',
  edgesTitle: 'エッジ',
  geometryTitle: 'ジオメトリ',
  paramsTitle: 'パラメータ',
  noEditableParams: '編集可能なパラメータはありません',
  analyzeTitle: '解析',
  dfmCheck: 'DFM チェック',
  runLower: '実行',
  warnCount: '警告 {n} 件',
  feaRowLabel: 'FEA · 線形/非線形/モーダル',
  costEstimate: 'コスト見積',
  motionStudy: 'モーションスタディ',
  simLower: 'シミュ',
  triangles: '三角形',
  controller: 'コントローラ',
  machine: 'マシン',
  exportGcode: 'G コードをエクスポート',
  appearance: '外観',
  material: '材料',
  engRoutes: { modeling: 'モデリング/力学', cam: 'CAM 加工', mold: '金型', 'sheet-metal': '板金', plant: 'プラント配管', hvac: '空調', cost: '見積/原価', dfm: 'DFM' },
  catEngTitle: 'エンジニアリング計算機',
  catSketchTitle: 'スケッチツール',
  catAsmTitle: '締結/はめあい計算機',
  catReady: '準備完了',
  catRun: '実行',
  catFailed: '読み込み失敗',
  catEmpty: '該当する機能がありません',
  sketchPaneTitle: 'スケッチ 1 — ベースプロファイル',
  emptySketch: '空のスケッチ — 描画を開始',
  onXyPlane: 'XY 平面上',
  entitiesTitle: 'エンティティ',
  noEntities: 'エンティティなし — 線 / 矩形 / 円から開始',
  constraintsTitle: '拘束',
  noConstraints: '拘束なし',
  dimensionsTitle: '寸法',
  noDimensions: '寸法なし',
  errSyntax: '数式エラー',
  errUnknownVar: '未定義の変数',
  errCycle: '循環参照',
  errRuntime: '実行時エラー',
  errNonFinite: '無効な値',
  valueOrExpr: '値または数式（例: 2*D1）',
  clickToEdit: 'クリックして編集',
  removeDimension: '寸法を削除',
  sketchProps: 'スケッチプロパティ',
  activeSelection: 'アクティブな選択',
  clickEntity: '選択ツールでエンティティをクリックしてください',
  selectedLabel: '選択',
  typeLabel: '種類',
  infoLabel: '情報',
  construction: '構築線',
  yes: 'はい',
  constraintsOnSel: '選択への拘束',
  noSelection: '選択なし',
  noConstraintsOnEntity: 'このエンティティに拘束はありません',
  unsatisfied: 'ソルバーが満たせなかった拘束',
  removeConstraint: '拘束を削除',
  noDimsOnEntity: 'このエンティティに寸法はありません — 寸法ツールで追加',
  solver: 'ソルバー',
  statusLower: '状態',
  entitiesLower: 'エンティティ',
  constraintsLower: '拘束',
  constraintsShort: '拘束',
  dimensionsLower: '寸法',
  redundantLower: '冗長拘束',
  solveTime: '解析時間',
  sketchToolsLive: 'スケッチツール（ライブ）',
  entityTypes: { line: '線', arc: '円弧', circle: '円', rect: '矩形', polygon: '多角形', ellipse: '楕円', slot: 'スロット', nurbs: 'スプライン' },
  asmTitle: 'アセンブリ',
  addMate: '合致を追加',
  insertPartsFirst: '先に部品を挿入してください。',
  noMatesYet: '合致はまだありません。上のボタンかリボンの合致ツールで追加してください。',
  deleteWord: '削除',
  tabMates: '合致',
  noComponents: 'コンポーネントはまだありません。Insert で部品を追加してください。',
  bomEmpty: '部品がないため BOM は空です。',
  thPart: '部品',
  thQty: '数量',
  thMass: '質量',
  totalRow: '合計',
  matesOn: '{name} の合致',
  billOfMaterials: '部品表 (BOM)',
  calculatorsLive: '計算機（ライブ）',
  mateTypes: { coincident: '一致', concentric: '同心', distance: '距離', angle: '角度', parallel: '平行', perpendicular: '垂直', tangent: '正接', hinge: 'ヒンジ', slider: 'スライダー', gear: '歯車' },
  vpShaded: 'シェイド',
  vpWireframe: 'ワイヤー',
  vpEdges: 'エッジ',
  vpSection: '断面',
  nEdge: 'エッジ',
  nEdges: 'エッジ',
  nFace: '面',
  nFaces: '面',
  nVertex: '頂点',
  nVertices: '頂点',
  nItem: 'アイテム',
  nItems: 'アイテム',
  editBtn: '編集',
  suppress: '抑制',
  stFullyConstrained: '完全定義 · DOF 0',
  stUnderDefined: '未定義 · DOF {dof}',
  stOverDefinedRedundant: '重複定義 · 冗長 {n} 件',
  stOverDefined: '重複定義',
  stConflicting: '拘束の競合',
};

const zh: ShellDict = {
  fmNewDesign: '新建设计',
  fmOpen: '打开…',
  fmSave: '保存',
  fmSaveAs: '另存为…',
  fmImport: '导入 STEP/IGES…',
  fmExportStl: '导出 STL',
  fmExportStep: '导出 STEP',
  fmExportPapercraft: '展开为纸艺 (DXF)',
  fmExportSlice: '切片为层 (DXF)',
  fmAllProjects: '所有项目',
  fmBackToHub: '返回中心',
  tJustNow: '刚刚',
  tSecondsAgo: '{n}秒前',
  tMinutesAgo: '{n}分钟前',
  tHoursAgo: '{n}小时前',
  tDaysAgo: '{n}天前',
  modeSketch: '草图模式',
  modeAssembly: '装配模式',
  exitSketchHint: '按 S 键退出',
  exitAssemblyHint: '按 A 键退出',
  saving: '保存中…',
  saveError: '保存出错',
  versionConflict: '版本冲突',
  savedAgo: '已保存 · {t}',
  autosaveReady: '自动保存就绪',
  untitledFile: '未命名.nxpart',
  untitled: '未命名',
  share: '共享',
  publish: '发布',
  toggleTheme: '切换主题',
  signupPdf: '注册后可导出 PDF',
  signupDxf: '注册后可导出 DWG/DXF',
  signupShare: '创建共享链接需要注册',
  signupAi: '注册后可无限使用 AI',
  signupGeneric: '注册后继续',
  drawerCost: '成本',
  drawerVariants: '变体',
  drawerMotion: '运动',
  drawerVersions: '版本',
  featCount: '{n} 个特征',
  pillSynced: '已同步',
  pillSaving: '保存中',
  pillError: '出错',
  variantsTitle: '设计变体',
  variantsDesc: '并排探索尺寸 / 材料 / 特征替代方案。',
  runArrow: '运行 →',
  settings: '设置',
  drawerRunHint: '点击运行将以模态打开完整面板，并在视口显示结果叠加。',
  feaTitle: '有限元分析',
  feaPick: '选择求解器模式并运行。',
  feaLinear: '线性',
  feaNonlinear: '非线性',
  feaModal: '模态',
  feaLinearDesc: '小变形 · 静应力 — 胡克材料。',
  feaNonlinearDesc: '大变形 · 超弹性 (Mooney-Rivlin)，Newton-Raphson 迭代。',
  feaModalDesc: '固有频率 · 振动模态，逆迭代法。',
  costTitle: '成本副驾驶',
  quantity: '数量',
  costEstimateBtn: '估算 {n} 件单价 →',
  dfmTitle: '可制造性分析 (DFM)',
  dfmNoRun: '尚未运行分析。',
  dfmOpenFull: '打开完整面板 →',
  navRecent: '最近',
  navProjects: '项目',
  navShared: '与我共享',
  navBranches: '分支',
  navAiStudio: 'Nexy AI 工作室',
  navPartLibrary: '零件库',
  comingSoon: '即将推出',
  soonChip: '即将上线',
  storage: '存储空间',
  projectsWord: '个项目',
  planWord: '套餐',
  guest: '访客',
  qsNewPart: '新建零件',
  qsNewPartSub: '实体 · 参数化',
  qsNewAsm: '新建装配体',
  qsNewAsmSub: '配合零部件',
  qsNewDrawing: '新建图纸',
  qsNewDrawingSub: '从零件或装配体创建',
  qsFromSketch: '从草图开始',
  qsFromSketchSub: '导入 DXF / SVG',
  fromGuestMode: '来自访客模式',
  welcomeBack: '欢迎回来，{name}',
  startNoSignup: '开始设计 — 无需注册',
  hubProjectsCount: '{n} 个项目',
  searchPlaceholder: '搜索零件、项目、分支…',
  aiAssist: '设计助手',
  aiHeroTitle: '用语言描述零件 — 立即生成参数化 3D 模型。',
  aiHeroBody: 'Nexy AI 通过 OpenSCAD 管线直达 STL 输出，内置 DFM、成本估算与制造商匹配。',
  openAiStudio: '打开 AI 工作室',
  seeTutorial: '查看教程',
  startWithExample: '从示例开始',
  recentlyOpened: '最近打开',
  tour60: '60 秒导览',
  acrossAll: '所有项目',
  viewAll: '查看全部 →',
  trySample: '试用示例项目 — 60 秒内上手',
  allProjects: '所有项目',
  opsDashboard: '运营仪表板（订单·询价·结算）→',
  thName: '名称',
  thType: '类型',
  thUpdated: '更新时间',
  loading: '加载中…',
  noMatch: "没有与'{q}'匹配的项目。",
  noProjectsYet: '还没有项目 — 创建您的第一个零件。',
  signInToSave: '登录后项目将永久保存到云端。',
  newPartCta: '+ 新建零件',
  signIn: '登录',
  guestMode: '访客模式',
  guestLocalOnly: '您的作品仅保存在此浏览器中。登录后可永久保存到云端。',
  signUpNow: '立即注册',
  shareTitle: '共享项目',
  shareNoProject: '请先保存项目再共享。',
  emailAddress: '电子邮箱地址',
  roleViewer: '仅查看',
  roleEditor: '可编辑',
  add: '添加',
  members: '成员',
  shareEmpty: '尚未共享给任何成员。',
  remove: '移除',
  ownerYou: '所有者（我）',
  shareNotFound: '找不到该邮箱对应的用户。',
  shareHint: '若对方有 NexyFab 账号会立即添加；否则将发送邀请邮件。项目会显示在"与我共享"中。',
  shareInvited: '邀请邮件已发送 — 对方接受后即成为成员。',
  close: '关闭',
  tabFeatures: '特征',
  tabBodies: '实体',
  tabComponents: '零部件',
  filterFeatures: '筛选特征…',
  noFeatures: '基础形状已启用 · 无附加特征',
  noBodies: '无实体 — 创建特征后将生成实体。',
  singleBody: '当前零件为单一实体。',
  stdCategories: { all: '全部', fastener: '紧固件', bearing: '轴承', pulley: '皮带轮', rail: '直线导轨', spring: '弹簧', gear: '齿轮' },
  insertIntoAssembly: '插入装配体',
  tabInspector: '检查器',
  tabEngineering: '工程',
  tabComments: '评论',
  selectToInspect: '选择特征或边以查看属性。',
  edgeGroup: '边组 · {n} 条边',
  edgesTitle: '边',
  geometryTitle: '几何',
  paramsTitle: '参数',
  noEditableParams: '无可编辑参数',
  analyzeTitle: '分析',
  dfmCheck: 'DFM 检查',
  runLower: '运行',
  warnCount: '{n} 个警告',
  feaRowLabel: 'FEA · 线性/非线性/模态',
  costEstimate: '成本估算',
  motionStudy: '运动算例',
  simLower: '仿真',
  triangles: '三角形',
  controller: '控制器',
  machine: '机床',
  exportGcode: '导出 G 代码',
  appearance: '外观',
  material: '材料',
  engRoutes: { modeling: '建模/力学', cam: 'CAM 加工', mold: '模具', 'sheet-metal': '钣金', plant: '工厂管道', hvac: '暖通空调', cost: '报价/成本', dfm: 'DFM' },
  catEngTitle: '工程计算器',
  catSketchTitle: '草图工具',
  catAsmTitle: '连接/配合计算器',
  catReady: '就绪',
  catRun: '运行',
  catFailed: '加载失败',
  catEmpty: '没有匹配的功能',
  sketchPaneTitle: '草图 1 — 基准轮廓',
  emptySketch: '空草图 — 开始绘制',
  onXyPlane: '位于 XY 平面',
  entitiesTitle: '实体元素',
  noEntities: '无元素 — 绘制直线 / 矩形 / 圆开始',
  constraintsTitle: '约束',
  noConstraints: '无约束',
  dimensionsTitle: '尺寸',
  noDimensions: '无尺寸',
  errSyntax: '表达式错误',
  errUnknownVar: '未定义变量',
  errCycle: '循环引用',
  errRuntime: '运行时错误',
  errNonFinite: '无效数值',
  valueOrExpr: '数值或表达式（如 2*D1）',
  clickToEdit: '点击编辑',
  removeDimension: '删除尺寸',
  sketchProps: '草图属性',
  activeSelection: '当前选择',
  clickEntity: '使用选择工具点击元素',
  selectedLabel: '已选',
  typeLabel: '类型',
  infoLabel: '信息',
  construction: '构造线',
  yes: '是',
  constraintsOnSel: '所选元素的约束',
  noSelection: '未选择',
  noConstraintsOnEntity: '此元素没有约束',
  unsatisfied: '求解器无法满足的约束',
  removeConstraint: '删除约束',
  noDimsOnEntity: '此元素没有尺寸 — 用尺寸工具添加',
  solver: '求解器',
  statusLower: '状态',
  entitiesLower: '元素',
  constraintsLower: '约束',
  constraintsShort: '约束',
  dimensionsLower: '尺寸',
  redundantLower: '冗余约束',
  solveTime: '求解时间',
  sketchToolsLive: '草图工具（实时）',
  entityTypes: { line: '直线', arc: '圆弧', circle: '圆', rect: '矩形', polygon: '多边形', ellipse: '椭圆', slot: '槽', nurbs: '样条曲线' },
  asmTitle: '装配体',
  addMate: '添加配合',
  insertPartsFirst: '请先插入零件。',
  noMatesYet: '尚无配合。使用上方按钮或功能区的配合工具添加。',
  deleteWord: '删除',
  tabMates: '配合',
  noComponents: '尚无零部件。使用 Insert 添加零件。',
  bomEmpty: '没有零件 — BOM 为空。',
  thPart: '零件',
  thQty: '数量',
  thMass: '质量',
  totalRow: '合计',
  matesOn: '{name} 的配合',
  billOfMaterials: '物料清单 (BOM)',
  calculatorsLive: '计算器（实时）',
  mateTypes: { coincident: '重合', concentric: '同心', distance: '距离', angle: '角度', parallel: '平行', perpendicular: '垂直', tangent: '相切', hinge: '铰链', slider: '滑块', gear: '齿轮' },
  vpShaded: '着色',
  vpWireframe: '线框',
  vpEdges: '边线',
  vpSection: '剖面',
  nEdge: '条边',
  nEdges: '条边',
  nFace: '个面',
  nFaces: '个面',
  nVertex: '个顶点',
  nVertices: '个顶点',
  nItem: '个项目',
  nItems: '个项目',
  editBtn: '编辑',
  suppress: '压缩',
  stFullyConstrained: '完全定义 · DOF 0',
  stUnderDefined: '欠定义 · DOF {dof}',
  stOverDefinedRedundant: '过定义 · {n} 个冗余',
  stOverDefined: '过定义',
  stConflicting: '约束冲突',
};

const es: ShellDict = {
  fmNewDesign: 'Nuevo diseño',
  fmOpen: 'Abrir…',
  fmSave: 'Guardar',
  fmSaveAs: 'Guardar como…',
  fmImport: 'Importar STEP/IGES…',
  fmExportStl: 'Exportar STL',
  fmExportStep: 'Exportar STEP',
  fmExportPapercraft: 'Desplegar a papercraft (DXF)',
  fmExportSlice: 'Cortar en capas (DXF)',
  fmAllProjects: 'Todos los proyectos',
  fmBackToHub: 'Volver al hub',
  tJustNow: 'ahora mismo',
  tSecondsAgo: 'hace {n} s',
  tMinutesAgo: 'hace {n} min',
  tHoursAgo: 'hace {n} h',
  tDaysAgo: 'hace {n} d',
  modeSketch: 'MODO CROQUIS',
  modeAssembly: 'MODO ENSAMBLAJE',
  exitSketchHint: 'Pulsa S para salir',
  exitAssemblyHint: 'Pulsa A para salir',
  saving: 'Guardando…',
  saveError: 'Error al guardar',
  versionConflict: 'Conflicto de versión',
  savedAgo: 'Guardado · {t}',
  autosaveReady: 'Autoguardado listo',
  untitledFile: 'SinTitulo.nxpart',
  untitled: 'Sin título',
  share: 'Compartir',
  publish: 'Publicar',
  toggleTheme: 'Cambiar tema',
  signupPdf: 'Regístrate para exportar PDF',
  signupDxf: 'Regístrate para exportar DWG/DXF',
  signupShare: 'Regístrate para compartir tu diseño',
  signupAi: 'Regístrate para IA ilimitada',
  signupGeneric: 'Regístrate para continuar',
  drawerCost: 'Coste',
  drawerVariants: 'Variantes',
  drawerMotion: 'Movimiento',
  drawerVersions: 'Versiones',
  featCount: '{n} operaciones',
  pillSynced: 'Sincronizado',
  pillSaving: 'Guardando',
  pillError: 'Error',
  variantsTitle: 'Variantes de diseño',
  variantsDesc: 'Explora alternativas de tamaño, material y operaciones en paralelo.',
  runArrow: 'Ejecutar →',
  settings: 'Ajustes',
  drawerRunHint: 'Al ejecutar se abre el panel completo como modal con superposición de resultados en el visor.',
  feaTitle: 'Análisis por elementos finitos',
  feaPick: 'Elige un modo de solver y ejecuta.',
  feaLinear: 'Lineal',
  feaNonlinear: 'No lineal',
  feaModal: 'Modal',
  feaLinearDesc: 'Pequeñas deformaciones · tensión estática — material hookeano.',
  feaNonlinearDesc: 'Grandes deformaciones · hiperelástico (Mooney-Rivlin), iteración Newton-Raphson.',
  feaModalDesc: 'Frecuencias propias · modos de vibración, iteración inversa.',
  costTitle: 'Copiloto de costes',
  quantity: 'Cantidad',
  costEstimateBtn: 'Estimar × {n} →',
  dfmTitle: 'Diseño para fabricación (DFM)',
  dfmNoRun: 'Aún no se ha ejecutado ningún análisis.',
  dfmOpenFull: 'Abrir panel completo →',
  navRecent: 'Recientes',
  navProjects: 'Proyectos',
  navShared: 'Compartido conmigo',
  navBranches: 'Ramas',
  navAiStudio: 'Estudio Nexy AI',
  navPartLibrary: 'Biblioteca de piezas',
  comingSoon: 'Próximamente',
  soonChip: 'Pronto',
  storage: 'Almacenamiento',
  projectsWord: 'proyectos',
  planWord: 'plan',
  guest: 'Invitado',
  qsNewPart: 'Nueva pieza',
  qsNewPartSub: 'Sólido · paramétrico',
  qsNewAsm: 'Nuevo ensamblaje',
  qsNewAsmSub: 'Relacionar componentes',
  qsNewDrawing: 'Nuevo plano',
  qsNewDrawingSub: 'Desde una pieza o ensamblaje',
  qsFromSketch: 'Desde croquis',
  qsFromSketchSub: 'Importar DXF / SVG',
  fromGuestMode: 'desde modo invitado',
  welcomeBack: 'Bienvenido de nuevo, {name}',
  startNoSignup: 'Empieza a diseñar — sin registro',
  hubProjectsCount: '{n} proyectos',
  searchPlaceholder: 'Buscar piezas, proyectos, ramas…',
  aiAssist: 'Asistente de diseño',
  aiHeroTitle: 'Describe una pieza con palabras — obtén un modelo 3D paramétrico al instante.',
  aiHeroBody: 'Nexy AI lleva tu idea directa a STL vía OpenSCAD, con DFM, costes y búsqueda de fabricantes integrados.',
  openAiStudio: 'Abrir Estudio AI',
  seeTutorial: 'Ver tutorial',
  startWithExample: 'Empieza con un ejemplo',
  recentlyOpened: 'Abiertos recientemente',
  tour60: 'Tour de 60 segundos',
  acrossAll: 'En todos los proyectos',
  viewAll: 'Ver todo →',
  trySample: 'Prueba un proyecto de ejemplo — explóralo en 60 segundos',
  allProjects: 'Todos los proyectos',
  opsDashboard: 'Panel de operaciones (pedidos · RFQ · liquidaciones) →',
  thName: 'Nombre',
  thType: 'Tipo',
  thUpdated: 'Actualizado',
  loading: 'Cargando…',
  noMatch: "Ningún proyecto coincide con '{q}'.",
  noProjectsYet: 'Aún no hay proyectos — crea tu primera pieza.',
  signInToSave: 'Inicia sesión para guardar tus proyectos en la nube.',
  newPartCta: '+ Nueva pieza',
  signIn: 'Iniciar sesión',
  guestMode: 'Modo invitado',
  guestLocalOnly: 'Tu trabajo solo se guarda en este navegador. Inicia sesión para guardarlo en la nube.',
  signUpNow: 'Registrarse',
  shareTitle: 'Compartir proyecto',
  shareNoProject: 'Guarda el proyecto primero para compartirlo.',
  emailAddress: 'Dirección de correo',
  roleViewer: 'Solo lectura',
  roleEditor: 'Editor',
  add: 'Añadir',
  members: 'Miembros',
  shareEmpty: 'Aún no hay miembros.',
  remove: 'Quitar',
  ownerYou: 'Propietario (tú)',
  shareNotFound: 'No hay ningún usuario con ese correo.',
  shareHint: 'Si tiene cuenta de NexyFab se añade al instante; si no, se envía una invitación por correo. Aparece en «Compartido conmigo».',
  shareInvited: 'Invitación enviada — será miembro cuando la acepte.',
  close: 'Cerrar',
  tabFeatures: 'Operaciones',
  tabBodies: 'Cuerpos',
  tabComponents: 'Componentes',
  filterFeatures: 'Filtrar operaciones…',
  noFeatures: 'Forma base activa · sin operaciones añadidas',
  noBodies: 'Sin cuerpos — crea una operación para formar un cuerpo sólido.',
  singleBody: 'Esta pieza es un único cuerpo sólido.',
  stdCategories: { all: 'Todo', fastener: 'Tornillería', bearing: 'Rodamientos', pulley: 'Poleas', rail: 'Guías lineales', spring: 'Resortes', gear: 'Engranajes' },
  insertIntoAssembly: 'Insertar en el ensamblaje',
  tabInspector: 'Inspector',
  tabEngineering: 'Ingeniería',
  tabComments: 'Comentarios',
  selectToInspect: 'Selecciona una operación o arista para inspeccionar.',
  edgeGroup: 'Grupo de aristas · {n} aristas',
  edgesTitle: 'Aristas',
  geometryTitle: 'Geometría',
  paramsTitle: 'Parámetros',
  noEditableParams: 'Sin parámetros editables',
  analyzeTitle: 'Analizar',
  dfmCheck: 'Comprobación DFM',
  runLower: 'ejecutar',
  warnCount: '{n} avisos',
  feaRowLabel: 'FEA — lineal/no lineal/modal',
  costEstimate: 'Estimación de costes',
  motionStudy: 'Estudio de movimiento',
  simLower: 'sim',
  triangles: 'Triángulos',
  controller: 'Controlador',
  machine: 'Máquina',
  exportGcode: 'Exportar G-code',
  appearance: 'Apariencia',
  material: 'Material',
  engRoutes: { modeling: 'Modelado/Dinámica', cam: 'CAM', mold: 'Molde', 'sheet-metal': 'Chapa metálica', plant: 'Tuberías de planta', hvac: 'HVAC', cost: 'Coste/Presupuesto', dfm: 'DFM' },
  catEngTitle: 'Calculadoras de ingeniería',
  catSketchTitle: 'Herramientas de croquis',
  catAsmTitle: 'Calculadoras de uniones/ajustes',
  catReady: 'Listo',
  catRun: 'Ejecutar',
  catFailed: 'Error de carga',
  catEmpty: 'Sin funciones coincidentes',
  sketchPaneTitle: 'CROQUIS 1 — PERFIL BASE',
  emptySketch: 'Croquis vacío — empieza a dibujar',
  onXyPlane: 'En el plano XY',
  entitiesTitle: 'Entidades',
  noEntities: 'Sin entidades — dibuja una línea / rectángulo / círculo para empezar',
  constraintsTitle: 'Restricciones',
  noConstraints: 'Sin restricciones',
  dimensionsTitle: 'Cotas',
  noDimensions: 'Sin cotas',
  errSyntax: 'Error de sintaxis',
  errUnknownVar: 'Variable desconocida',
  errCycle: 'Referencia circular',
  errRuntime: 'Error de ejecución',
  errNonFinite: 'Valor no finito',
  valueOrExpr: 'Valor o expresión (p. ej. 2*D1)',
  clickToEdit: 'Clic para editar',
  removeDimension: 'Eliminar cota',
  sketchProps: 'PROPIEDADES DEL CROQUIS',
  activeSelection: 'Selección activa',
  clickEntity: 'Haz clic en una entidad con la herramienta Seleccionar',
  selectedLabel: 'Seleccionado',
  typeLabel: 'Tipo',
  infoLabel: 'Info',
  construction: 'Construcción',
  yes: 'Sí',
  constraintsOnSel: 'Restricciones de la selección',
  noSelection: 'Sin selección',
  noConstraintsOnEntity: 'Sin restricciones en esta entidad',
  unsatisfied: 'Restricción que el solver no pudo satisfacer',
  removeConstraint: 'Eliminar restricción',
  noDimsOnEntity: 'Sin cotas en esta entidad — añade con la herramienta Cota',
  solver: 'Solver',
  statusLower: 'estado',
  entitiesLower: 'entidades',
  constraintsLower: 'restricciones',
  constraintsShort: 'restricc.',
  dimensionsLower: 'cotas',
  redundantLower: 'redundantes',
  solveTime: 'tiempo de cálculo',
  sketchToolsLive: 'Herramientas de croquis (en vivo)',
  entityTypes: { line: 'línea', arc: 'arco', circle: 'círculo', rect: 'rectángulo', polygon: 'polígono', ellipse: 'elipse', slot: 'ranura', nurbs: 'spline' },
  asmTitle: 'ENSAMBLAJE',
  addMate: 'Añadir relación',
  insertPartsFirst: 'Inserta piezas primero.',
  noMatesYet: 'Aún no hay relaciones. Usa el botón de arriba o las herramientas de relación de la cinta.',
  deleteWord: 'Eliminar',
  tabMates: 'Relaciones',
  noComponents: 'Aún no hay componentes. Usa Insert para añadir piezas.',
  bomEmpty: 'Sin piezas — el BOM está vacío.',
  thPart: 'PIEZA',
  thQty: 'CANT.',
  thMass: 'MASA',
  totalRow: 'TOTAL',
  matesOn: 'RELACIONES DE {name}',
  billOfMaterials: 'Lista de materiales',
  calculatorsLive: 'Calculadoras (en vivo)',
  mateTypes: { coincident: 'Coincidente', concentric: 'Concéntrica', distance: 'Distancia', angle: 'Ángulo', parallel: 'Paralela', perpendicular: 'Perpendicular', tangent: 'Tangente', hinge: 'Bisagra', slider: 'Deslizadera', gear: 'Engranaje' },
  vpShaded: 'Sombreado',
  vpWireframe: 'Alámbrico',
  vpEdges: 'Aristas',
  vpSection: 'Sección',
  nEdge: 'arista',
  nEdges: 'aristas',
  nFace: 'cara',
  nFaces: 'caras',
  nVertex: 'vértice',
  nVertices: 'vértices',
  nItem: 'elemento',
  nItems: 'elementos',
  editBtn: 'Editar',
  suppress: 'Suprimir',
  stFullyConstrained: 'Completamente definido · DOF 0',
  stUnderDefined: 'Subdefinido · DOF {dof}',
  stOverDefinedRedundant: 'Sobredefinido · {n} redundantes',
  stOverDefined: 'Sobredefinido',
  stConflicting: 'Restricciones en conflicto',
};

const ar: ShellDict = {
  fmNewDesign: 'تصميم جديد',
  fmOpen: 'فتح…',
  fmSave: 'حفظ',
  fmSaveAs: 'حفظ باسم…',
  fmImport: 'استيراد STEP/IGES…',
  fmExportStl: 'تصدير STL',
  fmExportStep: 'تصدير STEP',
  fmExportPapercraft: 'فرد إلى ورق (DXF)',
  fmExportSlice: 'تقطيع إلى طبقات (DXF)',
  fmAllProjects: 'كل المشاريع',
  fmBackToHub: 'العودة إلى المركز',
  tJustNow: 'الآن',
  tSecondsAgo: 'قبل {n} ث',
  tMinutesAgo: 'قبل {n} د',
  tHoursAgo: 'قبل {n} س',
  tDaysAgo: 'قبل {n} يوم',
  modeSketch: 'وضع الرسم التخطيطي',
  modeAssembly: 'وضع التجميع',
  exitSketchHint: 'اضغط S للخروج',
  exitAssemblyHint: 'اضغط A للخروج',
  saving: 'جارٍ الحفظ…',
  saveError: 'خطأ في الحفظ',
  versionConflict: 'تعارض في الإصدار',
  savedAgo: 'تم الحفظ · {t}',
  autosaveReady: 'الحفظ التلقائي جاهز',
  untitledFile: 'بدون عنوان.nxpart',
  untitled: 'بدون عنوان',
  share: 'مشاركة',
  publish: 'نشر',
  toggleTheme: 'تبديل السمة',
  signupPdf: 'سجّل لتصدير PDF',
  signupDxf: 'سجّل لتصدير DWG/DXF',
  signupShare: 'يلزم التسجيل لإنشاء رابط مشاركة',
  signupAi: 'سجّل لاستخدام الذكاء الاصطناعي بلا حدود',
  signupGeneric: 'سجّل للمتابعة',
  drawerCost: 'التكلفة',
  drawerVariants: 'المتغيرات',
  drawerMotion: 'الحركة',
  drawerVersions: 'الإصدارات',
  featCount: '{n} ميزة',
  pillSynced: 'تمت المزامنة',
  pillSaving: 'جارٍ الحفظ',
  pillError: 'خطأ',
  variantsTitle: 'متغيرات التصميم',
  variantsDesc: 'استكشف بدائل الحجم والمادة والميزات جنبًا إلى جنب.',
  runArrow: 'تشغيل ←',
  settings: 'الإعدادات',
  drawerRunHint: 'عند التشغيل تُفتح اللوحة الكاملة كنافذة منبثقة مع عرض النتائج فوق المنفذ.',
  feaTitle: 'تحليل العناصر المحدودة',
  feaPick: 'اختر وضع الحل ثم شغّل.',
  feaLinear: 'خطي',
  feaNonlinear: 'لا خطي',
  feaModal: 'الأنماط',
  feaLinearDesc: 'تشوه صغير · إجهاد ساكن — مادة هوكية.',
  feaNonlinearDesc: 'تشوه كبير · فرط المرونة (Mooney-Rivlin)، تكرار Newton-Raphson.',
  feaModalDesc: 'التردد الطبيعي · أنماط الاهتزاز، التكرار العكسي.',
  costTitle: 'مساعد التكلفة',
  quantity: 'الكمية',
  costEstimateBtn: 'تقدير × {n} ←',
  dfmTitle: 'التصميم من أجل التصنيع (DFM)',
  dfmNoRun: 'لم يُنفَّذ أي تحليل بعد.',
  dfmOpenFull: 'فتح اللوحة الكاملة ←',
  navRecent: 'الأحدث',
  navProjects: 'المشاريع',
  navShared: 'تمت مشاركته معي',
  navBranches: 'الفروع',
  navAiStudio: 'استوديو Nexy AI',
  navPartLibrary: 'مكتبة الأجزاء',
  comingSoon: 'قريبًا',
  soonChip: 'قريبًا',
  storage: 'التخزين',
  projectsWord: 'مشاريع',
  planWord: 'الخطة',
  guest: 'ضيف',
  qsNewPart: 'جزء جديد',
  qsNewPartSub: 'مجسم · بارامتري',
  qsNewAsm: 'تجميع جديد',
  qsNewAsmSub: 'اقتران المكونات',
  qsNewDrawing: 'رسم هندسي جديد',
  qsNewDrawingSub: 'من جزء أو تجميع',
  qsFromSketch: 'من رسم تخطيطي',
  qsFromSketchSub: 'استيراد DXF / SVG',
  fromGuestMode: 'من وضع الضيف',
  welcomeBack: 'مرحبًا بعودتك، {name}',
  startNoSignup: 'ابدأ التصميم — دون تسجيل',
  hubProjectsCount: '{n} مشروع',
  searchPlaceholder: 'ابحث في الأجزاء والمشاريع والفروع…',
  aiAssist: 'مساعد التصميم',
  aiHeroTitle: 'صِف الجزء بكلمات — واحصل على نموذج ثلاثي الأبعاد بارامتري فورًا.',
  aiHeroBody: 'يحوّل Nexy AI فكرتك مباشرة إلى STL عبر OpenSCAD، مع DFM وتقدير التكلفة ومطابقة المصنّعين.',
  openAiStudio: 'فتح استوديو AI',
  seeTutorial: 'عرض الشرح',
  startWithExample: 'ابدأ بمثال',
  recentlyOpened: 'المفتوحة مؤخرًا',
  tour60: 'جولة 60 ثانية',
  acrossAll: 'عبر كل المشاريع',
  viewAll: 'عرض الكل ←',
  trySample: 'جرّب مشروعًا نموذجيًا — استكشفه في 60 ثانية',
  allProjects: 'كل المشاريع',
  opsDashboard: 'لوحة العمليات (الطلبات · عروض الأسعار · التسويات) ←',
  thName: 'الاسم',
  thType: 'النوع',
  thUpdated: 'آخر تحديث',
  loading: 'جارٍ التحميل…',
  noMatch: "لا توجد مشاريع مطابقة لـ '{q}'.",
  noProjectsYet: 'لا توجد مشاريع بعد — أنشئ جزءك الأول.',
  signInToSave: 'سجّل الدخول لحفظ مشاريعك في السحابة.',
  newPartCta: '+ جزء جديد',
  signIn: 'تسجيل الدخول',
  guestMode: 'وضع الضيف',
  guestLocalOnly: 'يُحفظ عملك في هذا المتصفح فقط. سجّل الدخول لحفظه في السحابة بشكل دائم.',
  signUpNow: 'سجّل الآن',
  shareTitle: 'مشاركة المشروع',
  shareNoProject: 'احفظ المشروع أولًا لمشاركته.',
  emailAddress: 'البريد الإلكتروني',
  roleViewer: 'عرض فقط',
  roleEditor: 'تحرير',
  add: 'إضافة',
  members: 'الأعضاء',
  shareEmpty: 'لا يوجد أعضاء بعد.',
  remove: 'إزالة',
  ownerYou: 'المالك (أنت)',
  shareNotFound: 'لا يوجد مستخدم بهذا البريد.',
  shareHint: 'إذا كان لديه حساب NexyFab يُضاف فورًا؛ وإلا تُرسل دعوة بالبريد. يظهر ضمن «تمت مشاركته معي».',
  shareInvited: 'أُرسلت دعوة بالبريد — يصبح عضوًا عند القبول.',
  close: 'إغلاق',
  tabFeatures: 'الميزات',
  tabBodies: 'الأجسام',
  tabComponents: 'المكونات',
  filterFeatures: 'تصفية الميزات…',
  noFeatures: 'الشكل الأساسي نشط · لا ميزات مضافة',
  noBodies: 'لا أجسام — أنشئ ميزة لتكوين جسم مصمت.',
  singleBody: 'هذا الجزء جسم مصمت واحد.',
  stdCategories: { all: 'الكل', fastener: 'مثبتات', bearing: 'محامل', pulley: 'بكرات', rail: 'سكك خطية', spring: 'نوابض', gear: 'تروس' },
  insertIntoAssembly: 'إدراج في التجميع',
  tabInspector: 'الفاحص',
  tabEngineering: 'الهندسة',
  tabComments: 'التعليقات',
  selectToInspect: 'حدّد ميزة أو حافة لعرض الخصائص.',
  edgeGroup: 'مجموعة حواف · {n} حافة',
  edgesTitle: 'الحواف',
  geometryTitle: 'الهندسة الشكلية',
  paramsTitle: 'المعاملات',
  noEditableParams: 'لا معاملات قابلة للتحرير',
  analyzeTitle: 'تحليل',
  dfmCheck: 'فحص DFM',
  runLower: 'تشغيل',
  warnCount: '{n} تحذير',
  feaRowLabel: 'FEA · خطي/لا خطي/أنماط',
  costEstimate: 'تقدير التكلفة',
  motionStudy: 'دراسة الحركة',
  simLower: 'محاكاة',
  triangles: 'مثلثات',
  controller: 'وحدة التحكم',
  machine: 'الماكينة',
  exportGcode: 'تصدير G-code',
  appearance: 'المظهر',
  material: 'المادة',
  engRoutes: { modeling: 'النمذجة/الديناميكا', cam: 'تشغيل CAM', mold: 'القوالب', 'sheet-metal': 'الصاج', plant: 'أنابيب المصانع', hvac: 'التكييف', cost: 'التسعير/التكلفة', dfm: 'DFM' },
  catEngTitle: 'حاسبات هندسية',
  catSketchTitle: 'أدوات الرسم التخطيطي',
  catAsmTitle: 'حاسبات الوصلات/التوافقات',
  catReady: 'جاهز',
  catRun: 'تشغيل',
  catFailed: 'فشل التحميل',
  catEmpty: 'لا توجد ميزة مطابقة',
  sketchPaneTitle: 'رسم تخطيطي 1 — المقطع الأساسي',
  emptySketch: 'رسم تخطيطي فارغ — ابدأ بالرسم',
  onXyPlane: 'على مستوى XY',
  entitiesTitle: 'العناصر',
  noEntities: 'لا عناصر — ارسم خطًا / مستطيلًا / دائرة للبدء',
  constraintsTitle: 'القيود',
  noConstraints: 'لا قيود',
  dimensionsTitle: 'الأبعاد',
  noDimensions: 'لا أبعاد',
  errSyntax: 'خطأ في الصيغة',
  errUnknownVar: 'متغير غير معروف',
  errCycle: 'مرجع دائري',
  errRuntime: 'خطأ أثناء التنفيذ',
  errNonFinite: 'قيمة غير صالحة',
  valueOrExpr: 'قيمة أو تعبير (مثل 2*D1)',
  clickToEdit: 'انقر للتحرير',
  removeDimension: 'إزالة البعد',
  sketchProps: 'خصائص الرسم التخطيطي',
  activeSelection: 'التحديد النشط',
  clickEntity: 'انقر على عنصر بأداة التحديد',
  selectedLabel: 'المحدد',
  typeLabel: 'النوع',
  infoLabel: 'معلومات',
  construction: 'خط إنشائي',
  yes: 'نعم',
  constraintsOnSel: 'قيود على التحديد',
  noSelection: 'لا تحديد',
  noConstraintsOnEntity: 'لا قيود على هذا العنصر',
  unsatisfied: 'قيد لم يستطع المحلّ تلبيته',
  removeConstraint: 'إزالة القيد',
  noDimsOnEntity: 'لا أبعاد على هذا العنصر — أضِف بأداة الأبعاد',
  solver: 'المحلّ',
  statusLower: 'الحالة',
  entitiesLower: 'العناصر',
  constraintsLower: 'القيود',
  constraintsShort: 'القيود',
  dimensionsLower: 'الأبعاد',
  redundantLower: 'قيود زائدة',
  solveTime: 'زمن الحل',
  sketchToolsLive: 'أدوات الرسم التخطيطي (مباشر)',
  entityTypes: { line: 'خط', arc: 'قوس', circle: 'دائرة', rect: 'مستطيل', polygon: 'مضلع', ellipse: 'قطع ناقص', slot: 'مجرى', nurbs: 'منحنى Spline' },
  asmTitle: 'التجميع',
  addMate: 'إضافة اقتران',
  insertPartsFirst: 'أدرج الأجزاء أولًا.',
  noMatesYet: 'لا اقترانات بعد. استخدم الزر أعلاه أو أدوات الاقتران في الشريط.',
  deleteWord: 'حذف',
  tabMates: 'الاقترانات',
  noComponents: 'لا مكونات بعد. استخدم Insert لإضافة الأجزاء.',
  bomEmpty: 'لا أجزاء — قائمة المواد فارغة.',
  thPart: 'الجزء',
  thQty: 'الكمية',
  thMass: 'الكتلة',
  totalRow: 'الإجمالي',
  matesOn: 'اقترانات {name}',
  billOfMaterials: 'قائمة المواد (BOM)',
  calculatorsLive: 'حاسبات (مباشر)',
  mateTypes: { coincident: 'تطابق', concentric: 'تمركز', distance: 'مسافة', angle: 'زاوية', parallel: 'توازٍ', perpendicular: 'تعامد', tangent: 'تماس', hinge: 'مفصلة', slider: 'منزلق', gear: 'ترس' },
  vpShaded: 'مظلل',
  vpWireframe: 'سلكي',
  vpEdges: 'الحواف',
  vpSection: 'مقطع',
  nEdge: 'حافة',
  nEdges: 'حواف',
  nFace: 'وجه',
  nFaces: 'وجوه',
  nVertex: 'رأس',
  nVertices: 'رؤوس',
  nItem: 'عنصر',
  nItems: 'عناصر',
  editBtn: 'تحرير',
  suppress: 'كبت',
  stFullyConstrained: 'معرَّف بالكامل · DOF 0',
  stUnderDefined: 'ناقص التعريف · DOF {dof}',
  stOverDefinedRedundant: 'زائد التعريف · {n} زائدة',
  stOverDefined: 'زائد التعريف',
  stConflicting: 'قيود متعارضة',
};

const SHELL_DICT: Record<IsoLang, ShellDict> = { ko, en, ja, zh, es, ar };

/**
 * Picks the shell dict for any lang spelling — route ('kr','cn'), ISO
 * ('ko','zh') or legacy variants — via toIsoLang. Unknown → en.
 */
export function pickShellDict(lang: string | undefined | null): ShellDict {
  return SHELL_DICT[toIsoLang(lang)] ?? SHELL_DICT.en;
}

/** Tiny '{x}' template substitution for dict strings with placeholders. */
export function fmtShell(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (m, k: string) =>
    k in vars ? String(vars[k]) : m);
}
