import { NextResponse } from "next/server";

export const runtime = "nodejs";

export async function GET() {
  return NextResponse.json({
    ok: true,
    version: "v1",
    quoteOrRfqSideEffects: false,
    operations: [
      {
        id: "product-decomposition",
        method: "POST",
        path: "/api/cad/v1/product-decomposition",
        cli: "design",
        mcp: "product_decomposition",
      },
      {
        id: "feature-program",
        method: "POST",
        path: "/api/cad/v1/feature-program",
        cli: "part",
        mcp: "cad_feature_program",
        selectionContext: true,
      },
      {
        id: "feature-tree-mesh",
        method: "POST",
        path: "/api/cad/v1/feature-tree-mesh",
        cli: "mesh",
        mcp: "feature_tree_mesh",
        artifact: "stl-base64",
      },
      {
        id: "part-step",
        method: "POST",
        path: "/api/cad/v1/part-step",
        cli: "step",
        mcp: "export_part_step",
        artifact: "step-base64",
        manufacturingGates: true,
      },
      {
        id: "release-decision",
        method: "POST",
        path: "/api/cad/v1/release/decision",
        cli: "release decision",
        mcp: "decide_cad_release",
        checks: [
          "workflow-status",
          "step-roundtrip",
          "ifc-roundtrip",
          "bom-roundtrip",
          "drawing-roundtrip",
          "distinct-trusted-reviewer-signatures",
        ],
        sideEffects: false,
        failClosed: true,
      },
      {
        id: "reference-analyze",
        method: "POST",
        path: "/api/cad/v1/reference/analyze",
        cli: "reference analyze",
        mcp: "analyze_cad_reference",
        checks: ["exact-brep", "evidence-ir-v2", "scale-aware-tolerance"],
        accepts: ["inline-step"],
        sideEffects: false,
      },
      {
        id: "ifc-semantic-roundtrip",
        method: "POST",
        path: "/api/cad/v1/ifc/semantic-roundtrip",
        cli: "ifc semantic-roundtrip",
        mcp: "verify_ifc_semantic_roundtrip",
        checks: [
          "global-id",
          "spatial-parent",
          "property-quantity-material-definition",
          "projected-crs-map-conversion",
        ],
        accepts: ["inline-ifc-pair"],
        sideEffects: false,
      },
      {
        id: "ifc-domain-ir",
        method: "POST",
        path: "/api/cad/v1/ifc/domain-ir",
        cli: "ifc domain-ir",
        mcp: "build_ifc_domain_ir",
        checks: [
          "alignment-horizontal-vertical-cant",
          "horizontal-endpoint-direction-evaluation",
          "line-circle-analytic",
          "cubic-arc-length-inversion",
          "viennese-cant-gravity-center-coupling",
          "transition-curvature-rk4",
          "scale-aware-horizontal-continuity",
          "vertical-cant-station-continuity",
          "structural-node-member-connectivity",
          "all-ifc4-static-numeric-load-subtypes",
          "conversion-derived-unit-normalization",
          "load-coverage-accounting",
          "fail-closed-missing-viennese-authority",
          "fail-closed-unknown-load-unit",
          "fail-closed-unknown-load-type",
        ],
        accepts: ["inline-ifc", "optional-provenance-bearing-viennese-inputs"],
        sideEffects: false,
      },
      {
        id: "ifc-spatial-ir",
        method: "POST",
        path: "/api/cad/v1/ifc/spatial-ir",
        cli: "ifc spatial-ir",
        mcp: "build_ifc_spatial_ir",
        checks: [
          "spatial-hierarchy",
          "local-placement-chain",
          "straight-grid-placement",
          "linear-cartesian-placement",
          "point-by-distance-alignment-placement",
          "lateral-vertical-longitudinal-offset",
          "explicit-vs-derived-cross-check",
          "fail-closed-transform",
        ],
        accepts: ["inline-ifc"],
        sideEffects: false,
      },
      {
        id: "step-mechanical-relations",
        method: "POST",
        path: "/api/cad/v1/step/mechanical-relations",
        cli: "reference mechanical-relations",
        mcp: "analyze_step_mechanical_relations",
        checks: [
          "occurrence-world-cylinder-axes",
          "distinct-part-coaxiality",
          "shaft-bearing-layout",
          "linear-circular-pattern-pitch",
          "constant-thickness-independent-panels",
          "weldment-member-profile-length-cut-list",
          "fail-closed-unresolved-flat-pattern-bends-miters-density",
          "governed-angular-linear-tolerance",
        ],
        accepts: ["inline-step"],
        sideEffects: false,
      },
      {
        id: "ifc-recovery-plan",
        method: "POST",
        path: "/api/cad/v1/ifc/recovery-plan",
        cli: "ifc recovery-plan",
        mcp: "plan_ifc_geometry_recovery",
        checks: [
          "occurrence-global-id",
          "missing-axis",
          "evidence-scoped-action",
          "required-authoritative-inputs",
        ],
        accepts: ["inline-ifc"],
        sideEffects: false,
      },
      {
        id: "ifc-recover-geometry",
        method: "POST",
        path: "/api/cad/v1/ifc/recover-geometry",
        cli: "ifc recover-geometry",
        mcp: "recover_ifc_geometry",
        checks: [
          "exact-global-id-binding",
          "single-missing-axis",
          "positive-width",
          "required-provenance",
          "complete-geometry-overwrite-denied",
          "application-evidence",
          "remaining-request-gate",
        ],
        accepts: ["inline-ifc", "authoritative-inputs"],
        sideEffects: false,
      },
      {
        id: "topology-reconcile",
        method: "POST",
        path: "/api/cad/v1/topology/reconcile",
        cli: "topology reconcile",
        mcp: "reconcile_topology_references",
      },
      {
        id: "assembly-verify",
        method: "POST",
        path: "/api/cad/v1/assembly/verify",
        cli: "assembly verify",
        mcp: "verify_cad_assembly",
        checks: [
          "mates",
          "dof",
          "static-interference",
          "motion-frame-interference",
          "feature-tree-triangle-narrow-phase",
          "occt-boolean-fillet-chamfer-hole-tessellation",
          "conservative-fallback",
        ],
      },
      {
        id: "project-verify",
        method: "POST",
        path: "/api/cad/v1/project/verify",
        cli: "project verify",
        mcp: "verify_cad_project",
        checks: [
          "product-spatial-hierarchy",
          "world-placement",
          "assembly-dof",
          "precise-interference",
          "space-boundary",
          "egress",
          "mep-interference",
          "continuous-door-swing",
        ],
        sideEffects: false,
      },
      {
        id: "door-swing-verify",
        method: "POST",
        path: "/api/cad/v1/interior/door-swing/verify",
        cli: "interior door-swing --file",
        mcp: "verify_door_swing_clearance",
        checks: [
          "continuous-sector",
          "finite-leaf-thickness",
          "required-clearance",
        ],
        sideEffects: false,
      },
      {
        id: "space-boundary-verify",
        method: "POST",
        path: "/api/cad/v1/interior/space-boundary/verify",
        cli: "interior space-boundary --file",
        mcp: "verify_space_boundary_closure",
        checks: [
          "endpoint-snapping",
          "planar-graph-degree",
          "self-intersection",
          "minimum-area",
        ],
        sideEffects: false,
      },
      {
        id: "egress-verify",
        method: "POST",
        path: "/api/cad/v1/interior/egress/verify",
        cli: "interior egress --file",
        mcp: "verify_egress_routes",
        checks: [
          "governed-inputs",
          "clear-width-filter",
          "shortest-route",
          "travel-distance",
          "independent-exits",
        ],
        sideEffects: false,
      },
      {
        id: "mep-interference-verify",
        method: "POST",
        path: "/api/cad/v1/interior/mep-interference/verify",
        cli: "interior mep-interference --file",
        mcp: "verify_mep_interference",
        checks: [
          "continuous-capsules",
          "run-run",
          "run-obstacle",
          "clearance",
          "missing-geometry",
        ],
        sideEffects: false,
      },
      {
        id: "assembly-animation-evaluate",
        method: "POST",
        path: "/api/cad/v1/assembly/animation/evaluate",
        cli: "animation evaluate",
        mcp: "evaluate_assembly_animation",
        checks: [
          "frame-range",
          "part-targets",
          "keyframes",
          "quaternion-slerp",
        ],
        sideEffects: false,
      },
      {
        id: "assembly-animation-command",
        method: "POST",
        path: "/api/cad/v1/assembly/animation/command",
        cli: "animation command",
        mcp: "apply_assembly_animation_command",
        deterministic: true,
        supported: ["part-name-or-id", "frame-range", "x-y-z-translation-mm"],
        sideEffects: false,
      },
      {
        id: "assembly-selection-edit",
        method: "POST",
        path: "/api/cad/v1/assembly/selection-edit",
        cli: "assembly edit --verify-brep",
        mcp: "preview_assembly_selection_edit",
        deterministic: true,
        supported: [
          "part-transform",
          "extrude-depth",
          "extrude-exact-cap-offset",
          "extrude-exact-side-face-offset",
          "revolve-exact-side-face-offset",
          "boolean-provenance-face-offset",
          "hole",
          "draft",
          "occt-exact-edge-fillet",
          "occt-exact-edge-chamfer",
          "shell-rect-extrude",
          "occt-exact-cap-shell",
          "pattern",
          "mate-value",
          "multi-intent-atomic",
          "feature-tree-diff-evidence",
          "exact-brep-diff",
          "generation-stage-invalidation",
        ],
        unavailable: [
          "occt-arbitrary-face-shell",
          "selection-edit-imported-step-face-offset",
        ],
        sideEffects: false,
      },
      {
        id: "brep-push-pull",
        method: "POST",
        path: "/api/cad/v1/brep/push-pull",
        cli: "brep push-pull",
        mcp: "push_pull_step_face",
        deterministic: true,
        supported: [
          "imported-step-planar-face-push-pull",
          "exact-brep-validation",
          "step-artifact",
        ],
        unavailable: ["imported-step-curved-face-push-pull"],
        sideEffects: false,
      },
      {
        id: "assembly-animation-verify",
        method: "POST",
        path: "/api/cad/v1/assembly/animation/verify",
        cli: "animation verify",
        mcp: "verify_assembly_animation",
        checks: [
          "sampled-frames",
          "exact-linear-swept-aabb",
          "linear-mesh-refinement",
          "adaptive-rotational-ccd",
          "interval-coverage",
          "bounded-auto-refinement",
          "mesh-minimum-distance",
          "interval-motion-bound",
          "left-to-right-earliest-collision-search",
          "conservative-toi-bracket",
          "toi-depth-and-evaluation-budget",
          "precise-work-budget",
          "recovery-attempt-evidence",
          "unresolved-fail-closed",
          "failure-code-recovery",
          "feature-tree-mesh",
          "occt-fallback",
        ],
        sideEffects: false,
      },
      {
        id: "generation-verify",
        method: "POST",
        path: "/api/cad/v1/generation/verify",
        cli: "generation verify",
        mcp: "verify_ai_generation",
        checks: [
          "intent",
          "decomposition",
          "part-manufacturing",
          "mate-residuals",
          "declared-dof",
          "precise-interference",
          "motion",
          "step-roundtrip",
        ],
        sideEffects: false,
      },
      {
        id: "generation-state",
        method: "POST",
        path: "/api/cad/v1/generation/state",
        cli: "generation state --file",
        mcp: "transition_ai_generation_state",
        checks: [
          "sha256-artifacts",
          "ordered-stages",
          "checkpoints",
          "failure-fingerprint",
          "bounded-retry",
          "partial-part-retry",
          "edit-invalidation",
        ],
        sideEffects: false,
      },
      {
        id: "generation-advance",
        method: "POST",
        path: "/api/cad/v1/generation/advance",
        cli: "generation advance --file",
        mcp: "advance_ai_generation",
        checks: [
          "feature-tree-validation",
          "kernel-geometry",
          "watertight-topology",
          "assembly-certificate",
          "fail-closed-optional-stages",
        ],
        sideEffects: false,
      },
      {
        id: "generation-finalize",
        method: "POST",
        path: "/api/cad/v1/generation/finalize",
        cli: "generation finalize --file",
        mcp: "finalize_ai_generation",
        checks: [
          "server-motion-frames",
          "per-part-G0-G7",
          "server-reference-step-domain-evidence",
          "flat-pattern-bend-table-member-miter-cut-list",
          "server-step-measurement-comparison",
          "exact-artifact-G9",
          "stage-local-recovery",
          "affected-part-only-recovery",
        ],
        sideEffects: false,
      },
      {
        id: "robot-generate",
        method: "POST",
        path: "/api/cad/v1/robot/generate",
        cli: "robot generate",
        mcp: "generate_robot_6axis",
        checks: [
          "fk",
          "ik",
          "continuous-path",
          "joint-velocity-acceleration-jerk",
          "velocity-jacobian",
          "workspace",
          "singularity",
          "self-collision",
          "static-torque",
          "3d-cable-routing",
          "service-envelope",
        ],
        sideEffects: false,
      },
      {
        id: "manufacturing-verify",
        method: "POST",
        path: "/api/cad/v1/manufacturing/verify",
        cli: "manufacturing verify",
        mcp: "verify_manufacturing_evidence",
        checks: [
          "G0-provenance",
          "G1-intent",
          "G2-program",
          "G3-kernel",
          "G4-topology",
          "G5-dimensions",
          "G6-features",
          "G7-dfm",
          "G8-step-roundtrip",
          "G9-release-evidence",
        ],
        sideEffects: false,
      },
      {
        id: "sheet-metal-verify",
        method: "POST",
        path: "/api/cad/v1/sheet-metal/verify",
        cli: "sheet-metal verify",
        mcp: "verify_sheet_metal",
        artifacts: ["flat-pattern", "bend-table", "dxf"],
        sideEffects: false,
      },
      {
        id: "weldment-verify",
        method: "POST",
        path: "/api/cad/v1/weldment/verify",
        cli: "weldment verify",
        mcp: "verify_weldment",
        artifacts: ["members", "cut-list", "mass"],
        sideEffects: false,
      },
      {
        id: "tolerance-analyze",
        method: "POST",
        path: "/api/cad/v1/tolerance/analyze",
        cli: "tolerance analyze",
        mcp: "analyze_tolerance_stack",
        checks: ["worst-case", "rss", "specification"],
      },
      {
        id: "pmi-verify",
        method: "POST",
        path: "/api/cad/v1/pmi/verify",
        cli: "pmi verify",
        mcp: "verify_cad_pmi",
        checks: ["gdt-schema", "topology-reference"],
      },
    ],
    compatibility: {
      legacyUrlsRemainSupported: true,
      legacyCliCommands: ["assemble", "package"],
      legacyMcpToolsRemainSupported: true,
      note: "Legacy domain calculators and drawing-package tools keep their existing deterministic/local contracts; common AI CAD operations use CAD v1.",
    },
  });
}
