import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { NextRequest } from 'next/server';
import { POST } from './route';

const artifact = new TextEncoder().encode('housing evidence'); const hash = createHash('sha256').update(artifact).digest('hex');
const base = { manufacturer: 'M', revision: 'A', source: 'datasheet', artifactHash: hash, massSource: 'confirmed', interface: { axisRef: 'axis', mountingPlaneRef: 'face', shaftDiameterMm: 30 } };
const manifest = { schema: 'nexyfab.robot-component-catalog.v1', components: [{ ...base, id: 'M', model: 'M', kind: 'motor', massKg: 1, envelopeMm: { x: 60, y: 60, z: 100 }, ratedTorqueNm: 10, peakTorqueNm: 20, maxRpm: 5000, rotorInertiaKgM2: 0.01 }, { ...base, id: 'R', model: 'R', kind: 'reducer', massKg: 2, envelopeMm: { x: 90, y: 90, z: 80 }, ratio: 100, ratedOutputTorqueNm: 1000, peakOutputTorqueNm: 1500, maxInputRpm: 6000, efficiency: 0.9, backlashArcmin: 2 }, { ...base, id: 'B', model: 'B', kind: 'bearing', massKg: 0.5, envelopeMm: { x: 80, y: 80, z: 20 }, boreMm: 30, odMm: 80, widthMm: 20, dynamicLoadN: 20000, staticLoadN: 10000, limitingRpm: 5000 }], artifacts: [{ path: 'evidence.pdf', sha256: hash, source: 'datasheet' }] };
const requirements = { schema: 'nexyfab.robot-selection-requirements.v1', requirements: Array.from({ length: 6 }, (_, index) => ({ joint: index + 1, requiredOutputTorqueNm: 100, requiredOutputRpm: 10, radialLoadN: 1000, minShaftDiameterMm: 25, safetyFactor: 1.5 })) };
const housing = (z = 240, artifactHash = hash) => ({ schema: 'nexyfab.robot-housing-capacities.v1', capacities: Array.from({ length: 6 }, (_, index) => ({ joint: index + 1, internalMm: { x: 110, y: 110, z }, radialClearanceMm: 5, axialClearanceMm: 10, source: 'measured CAD', artifactHash })) });
function request(capacities: unknown, ip: string) { const form = new FormData(); form.set('housing', new File([JSON.stringify(capacities)], 'housing.json')); form.set('requirements', new File([JSON.stringify(requirements)], 'requirements.json')); form.set('manifest', new File([JSON.stringify(manifest)], 'manifest.json')); form.append('artifact', new File([artifact], 'evidence.pdf')); return new NextRequest('http://localhost/api/cad/v1/robot/catalog/housing-fit', { method: 'POST', body: form, headers: { 'x-forwarded-for': ip } }); }

describe('CAD v1 robot catalog housing fit', () => {
  it('returns six fits without CAD or release side effects', async () => { const response = await POST(request(housing(), 'housing-ok')); expect(response.status).toBe(200); const body = await response.json(); expect(body).toMatchObject({ ok: true, releaseReady: false, cadModified: false, quoteOrRfqSideEffects: false, report: { housingStatus: 'passed', cadIntegrationStatus: 'not_run', releaseReady: false, sideEffects: { persisted: false, cadModified: false } } }); expect(body.report.fits).toHaveLength(6); });
  it('distinguishes dimensional failure from missing provenance', async () => { const failed = await POST(request(housing(100), 'housing-small')); expect(failed.status).toBe(422); expect(await failed.json()).toMatchObject({ report: { housingStatus: 'failed' } }); const unbound = await POST(request(housing(240, 'a'.repeat(64)), 'housing-unbound')); expect(unbound.status).toBe(422); expect(await unbound.json()).toMatchObject({ report: { housingStatus: 'not_run', fits: [] } }); });
  it('requires every file', async () => { const response = await POST(new NextRequest('http://localhost/api/cad/v1/robot/catalog/housing-fit', { method: 'POST', body: new FormData(), headers: { 'x-forwarded-for': 'housing-empty' } })); expect(response.status).toBe(400); });
});
