/**
 * piezoelectric.ts — linear electro-mechanical (piezoelectric) coupling, the 1-D
 * coupled constitutive law (strain-charge form):
 *
 *   [ S ]   [ s   d ] [ T ]      S = mechanical strain,  T = stress
 *   [ D ] = [ d   ε ] [ E ]      D = electric displacement, E = field
 *
 * s = elastic compliance (at constant E), d = piezoelectric coefficient (the same
 * in both equations by reciprocity), ε = permittivity (at constant T). This captures
 * the actuator (a field makes free strain S = d·E) and sensor (a stress makes
 * open-circuit field E = −d·T/ε) effects. Verified against those closed forms and
 * the electromechanical coupling factor k² = d²/(s·ε).
 */

export interface PiezoMaterial {
  s: number;    // elastic compliance s^E
  d: number;    // piezoelectric strain coefficient
  eps: number;  // permittivity ε^T
}

/** Free (unconstrained, T=0) actuator strain under an applied field. */
export function freeStrain(E: number, mat: PiezoMaterial): number {
  return mat.d * E;
}

/** Blocked (S=0) actuator stress under an applied field: T = −d·E/s. */
export function blockedStress(E: number, mat: PiezoMaterial): number {
  return -(mat.d * E) / mat.s;
}

/** Open-circuit (D=0) sensor field generated by a stress: E = −d·T/ε. */
export function openCircuitField(T: number, mat: PiezoMaterial): number {
  return -(mat.d * T) / mat.eps;
}

/** Short-circuit (E=0) charge density generated by a stress: D = d·T. */
export function shortCircuitCharge(T: number, mat: PiezoMaterial): number {
  return mat.d * T;
}

/** Electromechanical coupling factor squared k² = d²/(s·ε). */
export function couplingFactorSquared(mat: PiezoMaterial): number {
  return (mat.d * mat.d) / (mat.s * mat.eps);
}

export interface PiezoState { S: number; T: number; E: number; D: number; }

/**
 * Solve the coupled constitutive law given any two of {S,T,E,D}. The mechanical and
 * electrical control variables are (T,E); supplying S and/or D inverts as needed.
 */
export function solvePiezo(given: Partial<PiezoState>, mat: PiezoMaterial): PiezoState {
  const { s, d, eps } = mat;
  let { S, T, E, D } = given;
  // resolve to (T, E) first.
  if (T === undefined || E === undefined) {
    if (T !== undefined && S !== undefined) E = (S - s * T) / d;             // S, T → E
    else if (E !== undefined && S !== undefined) T = (S - d * E) / s;        // S, E → T
    else if (T !== undefined && D !== undefined) E = (D - d * T) / eps;      // T, D → E
    else if (E !== undefined && D !== undefined) T = (D - eps * E) / d;      // E, D → T
    else if (S !== undefined && D !== undefined) {                           // S, D → (T,E)
      // [s d; d eps][T;E] = [S;D]
      const det = s * eps - d * d;
      T = (eps * S - d * D) / det; E = (s * D - d * S) / det;
    } else throw new Error('need two independent quantities');
  }
  S = s * (T as number) + d * (E as number);
  D = d * (T as number) + eps * (E as number);
  return { S, T: T as number, E: E as number, D };
}
