/**
 * Exact orthographic drawing evidence for Design Driver packages.
 *
 * Every view is generated by importing the already verified STEP body and
 * running OCCT HLR through Replicad. Mesh projection is never a fallback.
 */

import { createHash } from 'node:crypto';
import {
  projectReplicadShapeExact,
  type ReplicadProjectionView,
} from '@/lib/drawing/replicadExactProjection';
import { occtHlrSerializedToDxf } from '@/lib/drawing/occtHlrDxf';
import { loadServerReplicad } from '@/lib/occt/serverReplicad';
import type { ExactCadArtifact } from './exactCadGate';
import type { GateResult, PlanPart } from './types';

const REQUIRED_VIEWS = ['front', 'top', 'right'] as const satisfies ReadonlyArray<ReplicadProjectionView>;

export interface ExactDrawingViewArtifact {
  bodyId: string;
  view: typeof REQUIRED_VIEWS[number];
  method: 'replicad-hlr' | 'analytic-sphere-fallback';
  visiblePathCount: number;
  hiddenPathCount: number;
  analyticCurveEvidence: boolean;
  sourceStepSha256: string;
  svgSha256: string;
  svg: string;
  curveRecordSha256: string;
  curveCount: number;
  curveTypes: number[];
  exactDxfSha256: string;
  exactDxf: string;
}

export interface ExactDrawingArtifact {
  ok: boolean;
  partId: string;
  views: ExactDrawingViewArtifact[];
  reason?: string;
  kernelUnavailable?: boolean;
}

function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

function flattenSvgPaths(value: unknown): string[] {
  if (typeof value === 'string') return value.trim() ? [value] : [];
  if (!Array.isArray(value)) return [];
  return value.flatMap(flattenSvgPaths);
}

function safeViewBox(value: unknown): string {
  if (typeof value !== 'string') return '-10 -10 20 20';
  const numbers = value.trim().split(/[ ,]+/).map(Number);
  return numbers.length === 4 && numbers.every(Number.isFinite) && numbers[2]! > 0 && numbers[3]! > 0
    ? numbers.join(' ')
    : '-10 -10 20 20';
}

function svgDocument(viewBox: string, visible: ReadonlyArray<string>, hidden: ReadonlyArray<string>): string {
  const path = (d: string, layer: string) => `<path data-layer="${layer}" d="${d}"/>`;
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" fill="none" stroke="black" stroke-width="0.25" vector-effect="non-scaling-stroke">`,
    '<g id="visible">',
    ...visible.map(d => path(d, 'visible')),
    '</g>',
    '<g id="hidden" stroke-dasharray="2 1">',
    ...hidden.map(d => path(d, 'hidden')),
    '</g>',
    '</svg>',
  ].join('\n');
}

function failure(partId: string, reason: string, kernelUnavailable = false): ExactDrawingArtifact {
  return { ok: false, partId, views: [], reason, kernelUnavailable };
}

export async function buildExactDrawingArtifact(
  part: PlanPart,
  exactCad: ExactCadArtifact | null,
): Promise<ExactDrawingArtifact> {
  if (!exactCad?.ok) return failure(part.partId, 'verified exact CAD artifact unavailable');
  try {
    const replicad = await loadServerReplicad();
    const views: ExactDrawingViewArtifact[] = [];
    for (const body of exactCad.bodies) {
      const shape = await replicad.importSTEP(new Blob([body.step], { type: 'application/step' })) as {
        delete?: () => void;
      };
      try {
        for (const view of REQUIRED_VIEWS) {
          const projected = projectReplicadShapeExact(replicad as never, shape as never, view);
          const visible = flattenSvgPaths(projected.visible.toSVGPaths());
          const hidden = flattenSvgPaths(projected.hidden.toSVGPaths());
          if (visible.length === 0) {
            throw new Error(`body '${body.bodyId}' ${view}: OCCT HLR returned no visible geometry`);
          }
          const viewBox = safeViewBox(projected.visible.toSVGViewBox?.(5));
          const svg = svgDocument(viewBox, visible, hidden);
          const visibleSerialized = projected.visible.serialize?.();
          const hiddenSerialized = projected.hidden.serialize?.();
          if (typeof visibleSerialized !== 'string' || typeof hiddenSerialized !== 'string') {
            throw new Error(`body '${body.bodyId}' ${view}: OCCT HLR curve records unavailable`);
          }
          const exactDxf = occtHlrSerializedToDxf(visibleSerialized, hiddenSerialized);
          views.push({
            bodyId: body.bodyId,
            view,
            method: projected.method,
            visiblePathCount: visible.length,
            hiddenPathCount: hidden.length,
            analyticCurveEvidence: projected.analyticCurveEvidence,
            sourceStepSha256: sha256(body.step),
            svgSha256: sha256(svg),
            svg,
            curveRecordSha256: sha256(`${visibleSerialized}\n--HIDDEN--\n${hiddenSerialized}`),
            curveCount: exactDxf.curveCount,
            curveTypes: exactDxf.curveTypes,
            exactDxfSha256: sha256(exactDxf.dxf),
            exactDxf: exactDxf.dxf,
          });
        }
      } finally {
        try { shape.delete?.(); } catch { /* best effort */ }
      }
    }
    const expected = exactCad.bodies.length * REQUIRED_VIEWS.length;
    if (views.length !== expected) {
      return failure(part.partId, `expected ${expected} exact HLR views, got ${views.length}`);
    }
    return { ok: true, partId: part.partId, views };
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    return failure(part.partId, reason, /wasm|kernel|opencascade/i.test(reason));
  }
}

export function exactDrawingGate(
  part: PlanPart,
  exactCad: ExactCadArtifact | null,
  artifact: ExactDrawingArtifact | null,
): GateResult {
  const notes = [
    'Each front/top/right view is generated by OCCT HLR from the packaged, round-trip-verified STEP body.',
    'No mesh or caller-supplied projection can satisfy this gate; an HLR error is a fail-closed refusal.',
    'Per-view DXF is emitted directly from OCCT GeomTools line/circle/arc/B-spline records; unsupported curve types fail closed instead of being dropped.',
    'The exact HLR SVG is a geometry-view artifact, not a signed production drawing release.',
  ];
  if (!artifact) {
    return { id: `exact-drawing:${part.partId}`, kind: 'exact-drawing', pass: false, metrics: {}, reason: 'exact drawing artifact missing', notes };
  }
  const expected = (exactCad?.bodies.length ?? 0) * REQUIRED_VIEWS.length;
  const sourceHashes = new Set(artifact.views.map(view => view.sourceStepSha256));
  const metrics: Record<string, number> = {
    requiredViewCount: expected,
    exactViewCount: artifact.views.length,
    visiblePathCount: artifact.views.reduce((sum, view) => sum + view.visiblePathCount, 0),
    hiddenPathCount: artifact.views.reduce((sum, view) => sum + view.hiddenPathCount, 0),
    analyticCurveViewCount: artifact.views.filter(view => view.analyticCurveEvidence).length,
    exactDxfCurveCount: artifact.views.reduce((sum, view) => sum + view.curveCount, 0),
    exactDxfViewCount: artifact.views.filter(view => view.curveCount > 0 && sha256(view.exactDxf) === view.exactDxfSha256).length,
    uniqueSourceStepCount: sourceHashes.size,
  };
  const pass = artifact.ok && exactCad?.ok === true && artifact.views.length === expected && expected > 0
    && artifact.views.every(view => view.curveCount > 0 && sha256(view.exactDxf) === view.exactDxfSha256);
  return {
    id: `exact-drawing:${part.partId}`,
    kind: 'exact-drawing',
    pass,
    metrics,
    ...(!pass ? { reason: artifact.reason ?? `exact HLR coverage ${artifact.views.length}/${expected}` } : {}),
    notes,
  };
}
