import { describe, it, expect } from 'vitest';
import { existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FEATURE_REGISTRY } from './registry';
import { LOADER_MAPS } from './featureLoaders';

// One-off generator: emit static dynamic-import loader entries for every
// registry feature that has an importable module but no loader yet, so the
// catalog reaches 100% wired coverage. Static literal import() paths keep it
// bundler-safe. Re-run after adding new modules to refresh.
describe('coverage audit + auto-loader generator', () => {
  it('generates featureLoaders.auto.ts for all wireable unwired features', () => {
    const here = dirname(fileURLToPath(import.meta.url)); // .../featureCatalog
    // Exclude the 'auto' map itself so regeneration is idempotent (otherwise it
    // would see everything as wired and emit an empty file).
    const wired = new Set<string>();
    for (const [label, map] of Object.entries(LOADER_MAPS)) {
      if (label === 'auto') continue;
      for (const id of Object.keys(map)) wired.add(id);
    }

    // Modules that export only a FeatureDefinition object (applied via the
    // modeling pipeline, not the catalog launcher) have no callable export and
    // can't be "run" from the catalog — exclude them from auto-wiring.
    const EXCLUDE = new Set<string>(['features.variable-shell']);

    const lines: string[] = [];
    let skipped = 0;
    for (const e of FEATURE_REGISTRY) {
      if (wired.has(e.id) || EXCLUDE.has(e.id)) continue;
      const base = join(here, '..', e.entryHint);
      const exists = existsSync(base + '.ts') || existsSync(base + '.tsx') || existsSync(base + '/index.ts');
      if (!exists) { skipped++; continue; }
      lines.push(`  ${JSON.stringify(e.id)}: () => import(${JSON.stringify('../' + e.entryHint)}),`);
    }

    const content =
      `import type { ModuleLoader } from './moduleResolver';\n\n` +
      `/**\n * featureLoaders.auto.ts — AUTO-GENERATED by _coverageAudit.test.ts.\n` +
      ` * Static dynamic-import loaders for registry features that have a module\n` +
      ` * but were not hand-wired into a domain map. Regenerate after adding\n` +
      ` * modules; do not hand-edit. (${lines.length} entries.)\n */\n\n` +
      `export const AUTO_WIRED_LOADERS: Record<string, ModuleLoader> = {\n` +
      lines.join('\n') + `\n};\n`;

    writeFileSync(join(here, 'featureLoaders.auto.ts'), content, 'utf8');
     
    console.log(`[GEN] wrote featureLoaders.auto.ts with ${lines.length} loaders (skipped ${skipped} without module)`);
    expect(lines.length).toBeGreaterThan(290);
    expect(skipped).toBe(0);
  });
});
