/**
 * featureLoaders.ts — Static import map wiring registry feature ids to
 * their implementation modules, so the catalog UI can lazy-load and run
 * a feature on demand.
 *
 * Each loader is a static `() => import('...')` arrow — a specifier the
 * bundler can statically analyse, so each module lands in its own chunk
 * (no blanket context module, no `../../../lib` escape problems).
 *
 * This is the *opt-in* counterpart to moduleResolver's loader registry:
 * we register loaders for the domains that are actually surfaced in the
 * UI, growing the map domain-by-domain rather than maintaining 598
 * hand-written entries up front.
 *
 * First wired domain: the inspection GD&T form/orientation/runout
 * evaluators (a cohesive, fully-tested family).
 */

import { registerLoaders, type ModuleLoader } from './moduleResolver';

/** Inspection GD&T evaluators — flatness, profile, runout, orientation. */
export const INSPECTION_GDT_LOADERS: Record<string, ModuleLoader> = {
  'inspection.flatness-tolerance': () => import('../inspection/flatnessTolerance'),
  'inspection.profile-of-line': () => import('../inspection/profileOfLineTolerance'),
  'inspection.profile-of-surface': () => import('../inspection/profileOfSurfaceTolerance'),
  'inspection.circular-runout': () => import('../inspection/circularRunoutEvaluator'),
  'inspection.total-runout': () => import('../inspection/totalRunoutEvaluator'),
  'inspection.cylindricity': () => import('../inspection/cylindricityEvaluator'),
  'inspection.straightness': () => import('../inspection/straightnessEvaluator'),
  'inspection.angularity': () => import('../inspection/angularityEvaluator'),
  'inspection.concentricity': () => import('../inspection/concentricityEvaluator'),
  'inspection.symmetry': () => import('../inspection/symmetryEvaluator'),
  'inspection.parallelism': () => import('../inspection/parallelismEvaluator'),
  'inspection.perpendicularity': () => import('../inspection/perpendicularityEvaluator'),
};

/** Mold design modules — base, parting, cooling, ejection, gating, flow. */
export const MOLD_LOADERS: Record<string, ModuleLoader> = {
  'mold.base-library': () => import('../mold/moldBaseLibrary'),
  'mold.parting-line': () => import('../mold/partingLine'),
  'mold.draft-analysis': () => import('../mold/draftAnalysis'),
  'mold.core-cavity-split': () => import('../mold/coreCavitySplit'),
  'mold.undercut-detect': () => import('../mold/undercutDetect'),
  'mold.pull-direction-optimizer': () => import('../mold/pullDirectionOptimizer'),
  'mold.runner-gate-layout': () => import('../mold/runnerGateLayout'),
  'mold.gate-suitability': () => import('../mold/gateSuitability'),
  'mold.cooling-layout': () => import('../mold/coolingLineLayout'),
  'mold.ejector-pin': () => import('../mold/ejectorPinPlacement'),
  'mold.venting': () => import('../mold/ventingPlacement'),
  'mold.runner-balance': () => import('../mold/runnerBalanceOptimizer'),
  'mold.sprue-bushing': () => import('../mold/sprueBushingSizer'),
  'mold.cooling-interference': () => import('../mold/coolingInterferenceCheck'),
  'mold.lifter-cam': () => import('../mold/lifterCamMechanism'),
  'mold.ejector-balance': () => import('../mold/ejectorForceBalance'),
  'mold.cooling-time': () => import('../mold/coolingTimeEstimator'),
  'mold.sprue-runner': () => import('../mold/sprueRunnerSizer'),
  'mold.venting-layout': () => import('../mold/ventingLayout'),
  'mold.parting-line-detector': () => import('../mold/partingLineDetector'),
  'mold.gate-location': () => import('../mold/gateLocationOptimizer'),
  'mold.shrinkage-comp': () => import('../mold/shrinkageCompensator'),
  'mold.clamp-force': () => import('../mold/clampForceEstimator'),
  'mold.sink-mark': () => import('../mold/sinkMarkPredictor'),
  'mold.cooling-baffle': () => import('../mold/coolingBaffleLayout'),
  'mold.hot-runner-balance': () => import('../mold/hotRunnerBalance'),
  'mold.cavity-count': () => import('../mold/cavityCount'),
  'mold.injection-pressure': () => import('../mold/injectionPressure'),
};

/** CAM toolpath + machining modules. */
export const CAM_LOADERS: Record<string, ModuleLoader> = {
  'cam.adaptive-clearing': () => import('../cam/adaptiveClearing'),
  'cam.collision': () => import('../cam/toolpathCollision'),
  'cam.5-axis': () => import('../cam/multiAxisSimultaneous'),
  'cam.mill-turn': () => import('../cam/millTurnToolpath'),
  'cam.edm': () => import('../cam/edmToolpath'),
  'cam.gcode': () => import('../cam/gcodeEmitter'),
  'cam.post-processor': () => import('../cam/postProcessor'),
  'cam.cutting-time': () => import('../cam/cuttingTime'),
  'cam.drilling-cycle': () => import('../cam/drillingCycle'),
  'cam.feed-speed': () => import('../cam/feedSpeed'),
  'cam.pocket-strategy': () => import('../cam/pocketStrategy'),
  'cam.pocket-toolpath': () => import('../cam/pocketToolpath'),
  'cam.toolpath-safety': () => import('../cam/toolpathSafety'),
  'cam.multi-axis-index': () => import('../cam/multiAxisIndex'),
  'cam.tool-library': () => import('../cam/toolLibrary'),
  'cam.operation-ordering': () => import('../cam/operationOrdering'),
  'cam.toolpath-simulator': () => import('../cam/toolpathSimulator'),
  'cam.lead-in-out': () => import('../cam/leadInOut'),
  'cam.pocket-recognition': () => import('../cam/pocketRecognition'),
  'cam.tool-wear-taylor': () => import('../cam/toolWearTaylor'),
  'cam.clearance-plane-calculator': () => import('../cam/clearancePlaneCalculator'),
  'cam.multi-axis-orientation-selector': () => import('../cam/multiAxisOrientationSelector'),
  'cam.tool-change-sequencer': () => import('../cam/toolChangeSequencer'),
  'cam.gcode-reader': () => import('../cam/gcodeReader'),
  'cam.tool-holder-library': () => import('../cam/toolHolderLibrary'),
  'cam.chip-load-chart': () => import('../cam/chipLoadChart'),
  'cam.gcode-dialect-translator': () => import('../cam/gcodeDialectTranslator'),
  'cam.tool-average-wear': () => import('../cam/toolAverageWear'),
  'cam.cut-vs-air-time-ratio': () => import('../cam/cutVsAirTimeRatio'),
  'cam.cycle-time-distribution': () => import('../cam/cycleTimeDistribution'),
  'cam.finishing-pass-generator': () => import('../cam/finishingPassGenerator'),
  'cam.trochoidal-milling': () => import('../cam/trochoidalMilling'),
  'cam.canned-cycle': () => import('../cam/cannedCycleLibrary'),
  'cam.tool-life-remaining': () => import('../cam/toolLifeRemaining'),
  'cam.rest-machining': () => import('../cam/restMachiningDetector'),
  'cam.ramp-entry': () => import('../cam/rampEntryStrategy'),
  'cam.helical-interpolation': () => import('../cam/helicalInterpolationGen'),
  'cam.thread-milling': () => import('../cam/threadMillingToolpath'),
  'cam.coolant-strategy': () => import('../cam/coolantStrategyPicker'),
  'cam.corner-engagement': () => import('../cam/cornerToolEngagement'),
  'cam.peck-drill-schedule': () => import('../cam/peckDrillSchedule'),
  'cam.probe-macro': () => import('../cam/probeMacroGenerator'),
  'cam.scribe-pass': () => import('../cam/scribePassGenerator'),
  'cam.stock-engagement': () => import('../cam/stockEngagementLimiter'),
  'cam.corner-decel': () => import('../cam/cornerDecelerationProfile'),
  'cam.jog-tool-change': () => import('../cam/jogToolChangeGenerator'),
  'cam.tool-standoff': () => import('../cam/toolStandOffDetector'),
  'cam.stock-catalog': () => import('../cam/stockMaterialCatalog'),
  'cam.holder-collision': () => import('../cam/holderCollisionSweep'),
  'cam.stock-remainder': () => import('../cam/stockSurfaceRemainder'),
  'cam.coolant-volume': () => import('../cam/coolantVolumeEstimator'),
  'cam.micro-lift': () => import('../cam/microLiftRetract'),
  'cam.stock-probe': () => import('../cam/stockProbeMacro'),
  'cam.facing-spiral': () => import('../cam/facingStrategySpiral'),
  'cam.spindle-load': () => import('../cam/spindleLoadEstimator'),
  'cam.turning': () => import('../cam/turningToolpath'),
  'cam.dwell-sequencer': () => import('../cam/dwellSequencer'),
  'cam.cutting-force': () => import('../cam/cuttingForceEstimator'),
  'cam.5axis-collision': () => import('../cam/fiveAxisCollisionSweep'),
  'cam.lead-arc-opt': () => import('../cam/leadOptimizationArc'),
  'cam.corner-accel': () => import('../cam/cornerAcceleratorProfile'),
  'cam.scallop-calc': () => import('../cam/finishingScallopCalculator'),
  'cam.rest-boundary': () => import('../cam/restMachiningBoundary'),
  'cam.trochoidal-slot': () => import('../cam/trochoidalSlotPath'),
  'cam.plunge-roughing': () => import('../cam/plungeRoughingPattern'),
  'cam.chamfer-deburr': () => import('../cam/chamferDeburrPath'),
  'cam.corner-rounding': () => import('../cam/cornerRoundingPath'),
  'cam.helical-bore': () => import('../cam/helicalBorePath'),
  'cam.tapping-cycle': () => import('../cam/tappingCycle'),
  'cam.groove-turning': () => import('../cam/grooveTurningCycle'),
  'cam.thread-whirling': () => import('../cam/threadWhirlingPath'),
  'cam.tool-deflection': () => import('../cam/toolDeflection'),
  'cam.turning-surface-finish': () => import('../cam/turningSurfaceFinish'),
};

export const ASSEMBLY_LOADERS: Record<string, ModuleLoader> = {
  'assembly.mate-dof': () => import('../assembly/mateDofAnalysis'),
  'assembly.motion-pro': () => import('../assembly/motionStudyPro'),
  'assembly.advanced-pattern': () => import('../assembly/advancedComponentPattern'),
  'assembly.exploded-view': () => import('../assembly/ExplodedView'),
  'assembly.interference': () => import('../assembly/InterferenceDetection'),
  'assembly.tree': () => import('../assembly/assemblyTree'),
  'assembly.geometry-mates': () => import('../assembly/applyGeometryMatesToPlaced'),
  'assembly.sub-motion': () => import('../assembly/subAssemblyMotion'),
  'assembly.flexible-part': () => import('../assembly/flexiblePart'),
  'assembly.motion-study': () => import('../assembly/motionStudy'),
  'assembly.position-drivers': () => import('../assembly/positionDrivers'),
  'drawing.exploded-drawing': () => import('../assembly/autoExplodedDrawing'),
  'assembly.explode-step-sequencer': () => import('../assembly/explodeStepSequencer'),
  'assembly.mate-conflict-resolver': () => import('../assembly/mateConflictResolver'),
  'assembly.frame-transform-chain': () => import('../assembly/frameTransformChain'),
  'assembly.assembly-diff-comparator': () => import('../assembly/assemblyDiffComparator'),
  'assembly.explode-line-connector': () => import('../assembly/explodeLineConnector'),
  'assembly.sub-assembly-explode-group': () => import('../assembly/subAssemblyExplodeGroup'),
  'assembly.instance-manager': () => import('../assembly/instanceManager'),
  'assembly.assembly-notes': () => import('../assembly/assemblyNotes'),
  'assembly.grounded-body-detector': () => import('../assembly/groundedBodyDetector'),
  'assembly.mate-force-balance': () => import('../assembly/mateForceBalance'),
  'assembly.mate-redundancy': () => import('../assembly/mateRedundancyDetector'),
  'assembly.explode-collision': () => import('../assembly/explodeCollisionCheck'),
  'assembly.torque-spec': () => import('../assembly/torqueSpecGenerator'),
  'assembly.bom-rollup-phantom': () => import('../assembly/bomRollupPhantom'),
  'assembly.center-of-mass': () => import('../assembly/centerOfMassCalculator'),
  'assembly.motion-clearance': () => import('../assembly/motionClearanceScrub'),
  'assembly.fit-class': () => import('../assembly/fitClassLookup'),
  'assembly.mate-graph': () => import('../assembly/mateDependencyGraph'),
  'assembly.cg-envelope': () => import('../assembly/cgEnvelopeChecker'),
  'assembly.snap-fit': () => import('../assembly/snapFitRetention'),
  'assembly.buoyancy': () => import('../assembly/centerOfBuoyancy'),
  'assembly.screw-pattern': () => import('../assembly/screwPatternGenerator'),
  'assembly.part-replacement': () => import('../assembly/partReplacementDiff'),
  'assembly.torque-reach': () => import('../assembly/torqueToolReachCheck'),
  'assembly.thread-fit': () => import('../assembly/threadFitValidator'),
  'assembly.multi-config': () => import('../assembly/multiConfigPartVariant'),
  'assembly.mate-pinning': () => import('../assembly/matePinningKit'),
  'assembly.washer-pattern': () => import('../assembly/washerPatternPicker'),
  'assembly.modular-split': () => import('../assembly/modularSectionSplit'),
  'assembly.bearing-seat': () => import('../assembly/bearingSeatSizer'),
  'assembly.weight-leveler': () => import('../assembly/weightDistributionLeveler'),
  'assembly.torque-sequencer': () => import('../assembly/fastenerTorqueSequencer'),
  'assembly.clearance-fan': () => import('../assembly/clearanceFanChecker'),
  'assembly.press-fit-stress': () => import('../assembly/pressFitStress'),
  'assembly.bolt-preload': () => import('../assembly/boltPreloadCalculator'),
  'assembly.keyway-sizer': () => import('../assembly/keywaySizer'),
  'assembly.spline-fit': () => import('../assembly/splineFitSizer'),
  'assembly.retaining-ring': () => import('../assembly/retainingRingGroove'),
  'assembly.shrink-fit-heating': () => import('../assembly/shrinkFitHeating'),
  'assembly.rivet-joint': () => import('../assembly/rivetJoint'),
  'assembly.press-fit-torque': () => import('../assembly/pressFitTorque'),
};

export const DRAWING_LOADERS: Record<string, ModuleLoader> = {
  'drawing.line-art': () => import('../drawing/lineArt'),
  'drawing.leader-line-router': () => import('../drawing/leaderLineRouter'),
  'drawing.dimension-style-manager': () => import('../drawing/dimensionStyleManager'),
  'drawing.hatch-pattern-library': () => import('../drawing/hatchPatternLibrary'),
  'drawing.revision-cloud-generator': () => import('../drawing/revisionCloudGenerator'),
  'drawing.balloon-auto-numbering': () => import('../drawing/balloonAutoNumbering'),
  'drawing.detail-view-auto-placer': () => import('../drawing/detailViewAutoPlacer'),
  'drawing.spline-dimension': () => import('../drawing/splineDimension'),
  'drawing.csv-bom-importer': () => import('../drawing/csvBomImporter'),
  'drawing.coordinate-grid-overlay': () => import('../drawing/coordinateGridOverlay'),
  'drawing.scale-bar': () => import('../drawing/scaleBar'),
  'drawing.layer-auto-assign': () => import('../drawing/layerAutoAssign'),
  'drawing.dimension-chain-builder': () => import('../drawing/dimensionChainBuilder'),
  'drawing.centerline-pattern-generator': () => import('../drawing/centerlinePatternGenerator'),
  'drawing.image-placement': () => import('../drawing/imagePlacement'),
  'drawing.multi-sheet-manager': () => import('../drawing/multiSheetManager'),
  'drawing.typ-annotation-collapse': () => import('../drawing/typAnnotationCollapse'),
  'drawing.balloon-zone-map': () => import('../drawing/balloonZoneMap'),
  'drawing.reference-dimension': () => import('../drawing/referenceDimension'),
  'drawing.third-angle-layout': () => import('../drawing/thirdAngleLayoutBuilder'),
  'drawing.flag-note': () => import('../drawing/flagNoteManager'),
  'drawing.detail-callout-group': () => import('../drawing/detailCalloutGrouping'),
  'drawing.sheet-format-picker': () => import('../drawing/sheetFormatPicker'),
  'drawing.dim-overlap-resolver': () => import('../drawing/dimensionOverlapResolver'),
  'drawing.gdt-datum-chain': () => import('../drawing/gdtDatumChainValidator'),
  'drawing.section-line-stagger': () => import('../drawing/sectionLineAutoStagger'),
  'drawing.dim-reuse': () => import('../drawing/dimensionReuseDetector'),
  'drawing.centerline-extender': () => import('../drawing/centerlineAutoExtender'),
  'drawing.surface-finish-place': () => import('../drawing/surfaceFinishAutoPlace'),
  'drawing.balloon-bom-check': () => import('../drawing/balloonBomCrossChecker'),
  'drawing.tol-budget-overlay': () => import('../drawing/toleranceBudgetOverlay'),
  'drawing.ecn-diff': () => import('../drawing/ecnDiffViewer'),
  'drawing.dim-origin': () => import('../drawing/dimensionOriginSelector'),
  'drawing.cross-hatch': () => import('../drawing/crossHatchGenerator'),
  'drawing.iso-grid': () => import('../drawing/isometricGridGenerator'),
  'drawing.parts-list': () => import('../drawing/partsListEmitter'),
  'drawing.aux-breakout': () => import('../drawing/breakoutAuxViewGenerator'),
  'drawing.dim-override': () => import('../drawing/dimensionOverrideList'),
  'drawing.line-weight-bias': () => import('../drawing/lineWeightBiasDetector'),
  'drawing.thread-callout': () => import('../drawing/threadCalloutGenerator'),
  'drawing.balloon-arrow': () => import('../drawing/balloonArrowStylePicker'),
  'drawing.dim-chain-stagger': () => import('../drawing/dimensionChainStagger'),
  'drawing.tolerance-frame': () => import('../drawing/toleranceFrameComposer'),
  'drawing.tolerance-ladder': () => import('../drawing/toleranceLadderNote'),
  'drawing.zone-overlay': () => import('../drawing/zoneIdentifierOverlay'),
  'drawing.balloon-layout': () => import('../drawing/balloonCalloutLayout'),
  'drawing.revision-cloud': () => import('../drawing/revisionCloudLayout'),
  'drawing.section-hatch': () => import('../drawing/sectionViewHatch'),
  'drawing.detail-bubble': () => import('../drawing/detailViewBubble'),
  'drawing.break-line': () => import('../drawing/breakLineGenerator'),
  'drawing.chamfer-dim': () => import('../drawing/chamferDimensionCallout'),
  'drawing.datum-target': () => import('../drawing/datumTargetSymbol'),
};

export const SHEET_METAL_LOADERS: Record<string, ModuleLoader> = {
  'sheet-metal.forming-limit-diagram': () => import('../sheetmetal/formingLimitDiagram'),
  'sheet-metal.hem-standards': () => import('../sheetmetal/hemStandards'),
  'sheet-metal.punch-library': () => import('../sheetmetal/punchLibrary'),
  'sheet-metal.corner-blend': () => import('../sheetmetal/cornerBlend'),
  'sheet-metal.grain-direction-planner': () => import('../sheetmetal/grainDirectionPlanner'),
  'sheet-metal.louver-pattern': () => import('../sheetmetal/louverPattern'),
  'sheet-metal.flange-clearance': () => import('../sheetmetal/flangeClearance'),
  'sheet-metal.grain-flow': () => import('../sheetmetal/grainFlowOptimizer'),
  'sheet-metal.corner-relief': () => import('../sheetmetal/cornerReliefPlacer'),
  'sheet-metal.corner-trim-rounder': () => import('../sheetmetal/cornerTrimAutoRounder'),
  'sheet-metal.bend-deduction': () => import('../sheetmetal/bendDeductionCalculator'),
  'sheet-metal.coining': () => import('../sheetmetal/coiningCheck'),
  'sheet-metal.louver-direction': () => import('../sheetmetal/louverDirectionPicker'),
  'sheet-metal.corner-overlap-relief': () => import('../sheet-metal/cornerOverlapRelief'),
  'sheet-metal.jog-bend': () => import('../sheet-metal/jogBendDeveloper'),
  'sheet-metal.deep-draw': () => import('../sheet-metal/deepDraw'),
  'sheet-metal.cone-development': () => import('../sheet-metal/coneDevelopment'),
};

export const ESTIMATION_LOADERS: Record<string, ModuleLoader> = {
  'cost.estimator': () => import('../estimation/costEstimatorStage2'),
  'cost.supplier-match': () => import('../estimation/supplierMatchingStage2'),
  'cost.multi-step': () => import('../estimation/multiStepRouting'),
  'dfm.process-router': () => import('../estimation/processRouter'),
  'estimation.cost-regression': () => import('../estimation/costRegression'),
  'estimation.cost-cascade': () => import('../estimation/costCascade'),
  'estimation.batch-quote': () => import('../estimation/batchQuoteService'),
  'estimation.margin-rules-engine': () => import('../estimation/marginRulesEngine'),
  'estimation.machining-cost': () => import('../estimation/machiningCycleCost'),
  'estimation.molding-piece-cost': () => import('../estimation/moldingPieceCost'),
  'estimation.surface-treatment-cost': () => import('../estimation/surfaceTreatmentCost'),
  'estimation.casting-cost': () => import('../estimation/castingCost'),
  'estimation.laser-cut-cost': () => import('../estimation/laserCutCost'),
  'estimation.forging-cost': () => import('../estimation/forgingCost'),
  'estimation.extrusion-cost': () => import('../estimation/extrusionCost'),
  'estimation.stamping-cost': () => import('../estimation/stampingCost'),
  'estimation.heat-treat-cost': () => import('../estimation/heatTreatCost'),
  'estimation.assembly-labor': () => import('../estimation/assemblyLaborCost'),
  'estimation.mold-tooling-cost': () => import('../estimation/moldToolingCost'),
  'estimation.machine-hour-rate': () => import('../estimation/machineHourRate'),
  'estimation.print-build-cost': () => import('../estimation/printBuildCost'),
  'estimation.molding-cycle-time': () => import('../estimation/moldingCycleTime'),
  'estimation.weld-joint-cost': () => import('../estimation/weldJointCost'),
  'estimation.make-vs-buy': () => import('../estimation/makeVsBuy'),
  'estimation.freight-cost': () => import('../estimation/freightCost'),
  'estimation.oee': () => import('../estimation/oee'),
};

export const DYNAMICS_LOADERS: Record<string, ModuleLoader> = {
  'dynamics.cardan-joint': () => import('../dynamics/cardanJoint'),
  'dynamics.campbell-diagram': () => import('../dynamics/campbellDiagram'),
  'dynamics.gear-tooth-bending': () => import('../dynamics/gearToothBending'),
  'dynamics.unbalance-response': () => import('../dynamics/unbalanceResponse'),
  'dynamics.friction-clutch': () => import('../dynamics/frictionClutch'),
  'dynamics.geneva-mechanism': () => import('../dynamics/genevaMechanism'),
  'dynamics.planetary-gear': () => import('../dynamics/planetaryGearRatio'),
  'dynamics.flat-belt-slip': () => import('../dynamics/flatBeltSlip'),
  'dynamics.worm-gear': () => import('../dynamics/wormGearSelfLocking'),
  'dynamics.bearing-defect-freq': () => import('../dynamics/bearingDefectFreq'),
  'dynamics.rigid-body': () => import('../dynamics/rigidBody'),
  'dynamics.constraints': () => import('../dynamics/constraints'),
  'dynamics.actuators': () => import('../dynamics/actuators'),
  'dynamics.contact': () => import('../dynamics/contactDetection'),
  'dynamics.flywheel-sizer': () => import('../dynamics/flywheelSizer'),
  'dynamics.two-plane-balancing': () => import('../dynamics/twoPlaneBalancing'),
  'dynamics.critical-speed': () => import('../dynamics/criticalSpeedCalculator'),
  'dynamics.gear-train': () => import('../dynamics/gearTrainRatio'),
  'dynamics.belt-drive': () => import('../dynamics/beltDriveTension'),
  'dynamics.cam-follower': () => import('../dynamics/camFollowerMotion'),
  'dynamics.vibration-isolator': () => import('../dynamics/vibrationIsolator'),
  'dynamics.shaft-coupling-alignment': () => import('../dynamics/shaftCouplingAlignment'),
  'dynamics.torsional-vibration': () => import('../dynamics/torsionalVibration'),
};

export const ROUTING_LOADERS: Record<string, ModuleLoader> = {
  'routing.wire-harness': () => import('../routing/wireHarness'),
  'routing.path': () => import('../routing/routingPath'),
  'routing.fittings': () => import('../routing/routingFittings'),
  'routing.validate': () => import('../routing/routingValidate'),
  'routing.tube-bend-springback': () => import('../routing/tubeBendSpringback'),
  'routing.pipe-support-span': () => import('../routing/pipeSupportSpan'),
  'routing.pipe-wall-thickness': () => import('../routing/pipeWallThickness'),
  'routing.thermal-expansion-loop': () => import('../routing/thermalExpansionLoop'),
  'routing.pump-npsh': () => import('../routing/pumpNpsh'),
  'routing.orifice-plate': () => import('../routing/orificePlateSizing'),
  'routing.relief-valve': () => import('../routing/reliefValveSizing'),
  'wiring.conductor-ampacity': () => import('../routing/conductorAmpacity'),
  'routing.two-phase-flow': () => import('../routing/twoPhaseFlowRegime'),
  'routing.water-hammer': () => import('../routing/waterHammerSurge'),
  'routing.steam-trap': () => import('../routing/steamTrapSizing'),
  'routing.pump-system-curve': () => import('../routing/pumpSystemCurve'),
  'routing.pipe-insulation': () => import('../routing/pipeInsulationThickness'),
  'routing.control-valve-cv': () => import('../routing/controlValveCv'),
  'routing.steam-pipe-sizing': () => import('../routing/steamPipeSizing'),
  'routing.flange-rating': () => import('../routing/flangeRating'),
  'routing.gravity-drain': () => import('../routing/gravityDrainSlope'),
  'routing.expansion-joint': () => import('../routing/expansionJoint'),
  'routing.external-pressure-collapse': () => import('../routing/externalPressureCollapse'),
  'routing.hazen-williams': () => import('../routing/hazenWilliams'),
  'routing.pump-specific-speed': () => import('../routing/pumpSpecificSpeed'),
  'routing.gas-pipe-weymouth': () => import('../routing/gasPipeWeymouth'),
};

export const HVAC_LOADERS: Record<string, ModuleLoader> = {
  'routing.hvac': () => import('../hvac/ductSizing'),
  'hvac.duct-transition-loss': () => import('../hvac/ductTransitionLoss'),
  'hvac.damper-authority': () => import('../hvac/damperAuthority'),
  'hvac.fan-affinity': () => import('../hvac/fanAffinityLaws'),
  'hvac.diffuser-throw': () => import('../hvac/diffuserThrow'),
  'hvac.psychrometric-state': () => import('../hvac/psychrometricState'),
  'hvac.coil-load': () => import('../hvac/coilLoad'),
  'hvac.fan-static-budget': () => import('../hvac/fanStaticBudget'),
  'hvac.vav-box': () => import('../hvac/vavBoxSizing'),
  'hvac.coil-rows': () => import('../hvac/coilRowsSelector'),
  'hvac.economizer': () => import('../hvac/economizerChangeover'),
  'hvac.duct-leakage': () => import('../hvac/ductLeakage'),
  'hvac.air-mixing': () => import('../hvac/airMixing'),
  'hvac.cooling-tower': () => import('../hvac/coolingTower'),
  'hvac.chiller-iplv': () => import('../hvac/chillerIPLV'),
  'hvac.humidifier-load': () => import('../hvac/humidifierLoad'),
  'hvac.duct-acoustics': () => import('../hvac/ductAcoustics'),
  'hvac.ventilation-rate': () => import('../hvac/ventilationRate'),
  'hvac.vrf-piping': () => import('../hvac/vrfRefrigerantPiping'),
  'hvac.air-curtain': () => import('../hvac/airCurtain'),
  'hvac.fan-coil-unit': () => import('../hvac/fanCoilUnit'),
};

export const WELDING_LOADERS: Record<string, ModuleLoader> = {
  'weld.bead': () => import('../welding/weldBeadGeometry'),
  'welding.symbols': () => import('../welding/weldingSymbols'),
  'welding.weld-symbol-suggester': () => import('../welding/weldSymbolSuggester'),
  'welding.bead-sequence': () => import('../welding/beadSequencePlanner'),
  'welding.bead-path': () => import('../welding/weldBeadPathGenerator'),
  'welding.fillet-throat': () => import('../welding/filletThroatSizer'),
  'welding.preheat-temp': () => import('../welding/preheatTemperature'),
  'welding.electrode-consumption': () => import('../welding/electrodeConsumption'),
  'welding.heat-input': () => import('../welding/heatInput'),
};

/** All loader maps registered so far, keyed by a human label (for diagnostics). */
export const LOADER_MAPS: Record<string, Record<string, ModuleLoader>> = {
  'inspection-gdt': INSPECTION_GDT_LOADERS,
  'mold': MOLD_LOADERS,
  'cam': CAM_LOADERS,
  'assembly': ASSEMBLY_LOADERS,
  'drawing': DRAWING_LOADERS,
  'sheet-metal': SHEET_METAL_LOADERS,
  'estimation': ESTIMATION_LOADERS,
  'dynamics': DYNAMICS_LOADERS,
  'routing': ROUTING_LOADERS,
  'hvac': HVAC_LOADERS,
  'welding': WELDING_LOADERS,
};

/** Register every wired loader map into the moduleResolver registry.
 *  Idempotent — safe to call from app init more than once. */
export function registerAllFeatureLoaders(): void {
  for (const map of Object.values(LOADER_MAPS)) {
    registerLoaders(map);
  }
}

/** Ids that have a static loader in this file. */
export function wiredFeatureIds(): string[] {
  return Object.values(LOADER_MAPS).flatMap(m => Object.keys(m));
}
