// ─── COTS Parts Catalog ───────────────────────────────────────────────────────
// Standard Commercial-Off-The-Shelf hardware parts with parametric data.

export interface COTSPart {
  id: string;
  category: 'bolt' | 'nut' | 'bearing' | 'collar' | 'clip' | 'washer';
  name: string;
  nameKo: string;
  standard: string;
  params: Record<string, number>;
  unitWeightG: number;
  unitPriceKRW: number;
  suppliers: string[];
}

export const COTS_PARTS: COTSPart[] = [
  // ── Bolts (ISO 4762 / KS B 1003 Socket Head Cap Screws) ──────────────────
  {
    id: 'bolt-m3-10',
    category: 'bolt',
    name: 'M3×10 Socket Head Cap Screw',
    nameKo: 'M3×10 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 3, length: 10, pitch: 0.5, headDia: 5.5, headH: 3 },
    unitWeightG: 0.5,
    unitPriceKRW: 45,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'bolt-m3-20',
    category: 'bolt',
    name: 'M3×20 Socket Head Cap Screw',
    nameKo: 'M3×20 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 3, length: 20, pitch: 0.5, headDia: 5.5, headH: 3 },
    unitWeightG: 0.9,
    unitPriceKRW: 55,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'bolt-m4-10',
    category: 'bolt',
    name: 'M4×10 Socket Head Cap Screw',
    nameKo: 'M4×10 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 4, length: 10, pitch: 0.7, headDia: 7, headH: 4 },
    unitWeightG: 1.1,
    unitPriceKRW: 60,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'bolt-m4-20',
    category: 'bolt',
    name: 'M4×20 Socket Head Cap Screw',
    nameKo: 'M4×20 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 4, length: 20, pitch: 0.7, headDia: 7, headH: 4 },
    unitWeightG: 1.8,
    unitPriceKRW: 75,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'bolt-m5-16',
    category: 'bolt',
    name: 'M5×16 Socket Head Cap Screw',
    nameKo: 'M5×16 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 5, length: 16, pitch: 0.8, headDia: 8.5, headH: 5 },
    unitWeightG: 2.5,
    unitPriceKRW: 90,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'bolt-m5-30',
    category: 'bolt',
    name: 'M5×30 Socket Head Cap Screw',
    nameKo: 'M5×30 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 5, length: 30, pitch: 0.8, headDia: 8.5, headH: 5 },
    unitWeightG: 4.0,
    unitPriceKRW: 110,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'bolt-m6-20',
    category: 'bolt',
    name: 'M6×20 Socket Head Cap Screw',
    nameKo: 'M6×20 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 6, length: 20, pitch: 1.0, headDia: 10, headH: 6 },
    unitWeightG: 4.8,
    unitPriceKRW: 120,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'bolt-m6-40',
    category: 'bolt',
    name: 'M6×40 Socket Head Cap Screw',
    nameKo: 'M6×40 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 6, length: 40, pitch: 1.0, headDia: 10, headH: 6 },
    unitWeightG: 8.0,
    unitPriceKRW: 155,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'bolt-m8-25',
    category: 'bolt',
    name: 'M8×25 Socket Head Cap Screw',
    nameKo: 'M8×25 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 8, length: 25, pitch: 1.25, headDia: 13, headH: 8 },
    unitWeightG: 10.5,
    unitPriceKRW: 200,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'bolt-m10-30',
    category: 'bolt',
    name: 'M10×30 Socket Head Cap Screw',
    nameKo: 'M10×30 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 10, length: 30, pitch: 1.5, headDia: 16, headH: 10 },
    unitWeightG: 20.0,
    unitPriceKRW: 320,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'bolt-m12-40',
    category: 'bolt',
    name: 'M12×40 Socket Head Cap Screw',
    nameKo: 'M12×40 육각 소켓 볼트',
    standard: 'ISO 4762 / KS B 1003',
    params: { M: 12, length: 40, pitch: 1.75, headDia: 18, headH: 12 },
    unitWeightG: 38.0,
    unitPriceKRW: 520,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },

  // ── Hex Nuts (ISO 4032) ───────────────────────────────────────────────────
  {
    id: 'nut-m3',
    category: 'nut',
    name: 'M3 Hex Nut',
    nameKo: 'M3 육각 너트',
    standard: 'ISO 4032',
    params: { M: 3, pitch: 0.5, width: 5.5, height: 2.4 },
    unitWeightG: 0.3,
    unitPriceKRW: 25,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'nut-m4',
    category: 'nut',
    name: 'M4 Hex Nut',
    nameKo: 'M4 육각 너트',
    standard: 'ISO 4032',
    params: { M: 4, pitch: 0.7, width: 7, height: 3.2 },
    unitWeightG: 0.7,
    unitPriceKRW: 30,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'nut-m5',
    category: 'nut',
    name: 'M5 Hex Nut',
    nameKo: 'M5 육각 너트',
    standard: 'ISO 4032',
    params: { M: 5, pitch: 0.8, width: 8, height: 4.0 },
    unitWeightG: 1.2,
    unitPriceKRW: 38,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'nut-m6',
    category: 'nut',
    name: 'M6 Hex Nut',
    nameKo: 'M6 육각 너트',
    standard: 'ISO 4032',
    params: { M: 6, pitch: 1.0, width: 10, height: 5.0 },
    unitWeightG: 2.3,
    unitPriceKRW: 50,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'nut-m8',
    category: 'nut',
    name: 'M8 Hex Nut',
    nameKo: 'M8 육각 너트',
    standard: 'ISO 4032',
    params: { M: 8, pitch: 1.25, width: 13, height: 6.5 },
    unitWeightG: 5.0,
    unitPriceKRW: 75,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'nut-m10',
    category: 'nut',
    name: 'M10 Hex Nut',
    nameKo: 'M10 육각 너트',
    standard: 'ISO 4032',
    params: { M: 10, pitch: 1.5, width: 17, height: 8.0 },
    unitWeightG: 9.5,
    unitPriceKRW: 110,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'nut-m12',
    category: 'nut',
    name: 'M12 Hex Nut',
    nameKo: 'M12 육각 너트',
    standard: 'ISO 4032',
    params: { M: 12, pitch: 1.75, width: 19, height: 10.0 },
    unitWeightG: 17.0,
    unitPriceKRW: 170,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },

  // ── Deep Groove Ball Bearings ─────────────────────────────────────────────
  {
    id: 'bearing-608zz',
    category: 'bearing',
    name: '608ZZ Deep Groove Ball Bearing',
    nameKo: '608ZZ 깊은홈 볼 베어링',
    standard: 'JIS B 1521 / ISO 15',
    params: { bore: 8, OD: 22, width: 7, dynamicLoadN: 3250, staticLoadN: 1370 },
    unitWeightG: 24,
    unitPriceKRW: 1800,
    suppliers: ['NSK', 'NTN', 'Misumi'],
  },
  {
    id: 'bearing-6001',
    category: 'bearing',
    name: '6001 Deep Groove Ball Bearing',
    nameKo: '6001 깊은홈 볼 베어링',
    standard: 'JIS B 1521 / ISO 15',
    params: { bore: 12, OD: 28, width: 8, dynamicLoadN: 5100, staticLoadN: 2360 },
    unitWeightG: 32,
    unitPriceKRW: 2200,
    suppliers: ['NSK', 'NTN', 'Misumi'],
  },
  {
    id: 'bearing-6004',
    category: 'bearing',
    name: '6004 Deep Groove Ball Bearing',
    nameKo: '6004 깊은홈 볼 베어링',
    standard: 'JIS B 1521 / ISO 15',
    params: { bore: 20, OD: 42, width: 12, dynamicLoadN: 9950, staticLoadN: 5000 },
    unitWeightG: 100,
    unitPriceKRW: 4500,
    suppliers: ['NSK', 'NTN', 'Misumi'],
  },
  {
    id: 'bearing-6008',
    category: 'bearing',
    name: '6008 Deep Groove Ball Bearing',
    nameKo: '6008 깊은홈 볼 베어링',
    standard: 'JIS B 1521 / ISO 15',
    params: { bore: 40, OD: 68, width: 15, dynamicLoadN: 16800, staticLoadN: 9500 },
    unitWeightG: 260,
    unitPriceKRW: 9800,
    suppliers: ['NSK', 'NTN', 'Misumi'],
  },
  {
    id: 'bearing-51100',
    category: 'bearing',
    name: '51100 Thrust Ball Bearing',
    nameKo: '51100 스러스트 볼 베어링',
    standard: 'JIS B 1532',
    params: { bore: 10, OD: 24, height: 9, staticLoadN: 6200 },
    unitWeightG: 40,
    unitPriceKRW: 5500,
    suppliers: ['NSK', 'NTN', 'Misumi'],
  },

  // ── Shaft Collars (one-piece, set-screw) ──────────────────────────────────
  {
    id: 'collar-6',
    category: 'collar',
    name: 'Shaft Collar Bore 6mm',
    nameKo: '샤프트 칼라 내경 6mm',
    standard: 'JIS B 1554',
    params: { bore: 6, OD: 14, width: 10 },
    unitWeightG: 6,
    unitPriceKRW: 980,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'collar-8',
    category: 'collar',
    name: 'Shaft Collar Bore 8mm',
    nameKo: '샤프트 칼라 내경 8mm',
    standard: 'JIS B 1554',
    params: { bore: 8, OD: 18, width: 12 },
    unitWeightG: 11,
    unitPriceKRW: 1100,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'collar-10',
    category: 'collar',
    name: 'Shaft Collar Bore 10mm',
    nameKo: '샤프트 칼라 내경 10mm',
    standard: 'JIS B 1554',
    params: { bore: 10, OD: 22, width: 14 },
    unitWeightG: 18,
    unitPriceKRW: 1300,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'collar-12',
    category: 'collar',
    name: 'Shaft Collar Bore 12mm',
    nameKo: '샤프트 칼라 내경 12mm',
    standard: 'JIS B 1554',
    params: { bore: 12, OD: 26, width: 16 },
    unitWeightG: 28,
    unitPriceKRW: 1500,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'collar-15',
    category: 'collar',
    name: 'Shaft Collar Bore 15mm',
    nameKo: '샤프트 칼라 내경 15mm',
    standard: 'JIS B 1554',
    params: { bore: 15, OD: 32, width: 18 },
    unitWeightG: 50,
    unitPriceKRW: 1900,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },

  // ── Retaining Rings / C-Clips (DIN 471 — external shaft) ─────────────────
  {
    id: 'clip-din471-6',
    category: 'clip',
    name: 'Retaining Ring DIN 471 d=6mm',
    nameKo: 'C형 멈춤링 DIN 471 d=6',
    standard: 'DIN 471',
    params: { d: 6, thickness: 0.7, d1: 5.6, b: 1.6 },
    unitWeightG: 0.2,
    unitPriceKRW: 55,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'clip-din471-10',
    category: 'clip',
    name: 'Retaining Ring DIN 471 d=10mm',
    nameKo: 'C형 멈춤링 DIN 471 d=10',
    standard: 'DIN 471',
    params: { d: 10, thickness: 1.0, d1: 9.3, b: 2.0 },
    unitWeightG: 0.5,
    unitPriceKRW: 70,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'clip-din471-15',
    category: 'clip',
    name: 'Retaining Ring DIN 471 d=15mm',
    nameKo: 'C형 멈춤링 DIN 471 d=15',
    standard: 'DIN 471',
    params: { d: 15, thickness: 1.1, d1: 14.1, b: 2.5 },
    unitWeightG: 0.9,
    unitPriceKRW: 90,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },

  // ── Flat Washers (ISO 7089) ───────────────────────────────────────────────
  {
    id: 'washer-m5',
    category: 'washer',
    name: 'M5 Flat Washer',
    nameKo: 'M5 평 와셔',
    standard: 'ISO 7089',
    params: { M: 5, innerDia: 5.3, outerDia: 10, thickness: 1.0 },
    unitWeightG: 0.4,
    unitPriceKRW: 20,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'washer-m6',
    category: 'washer',
    name: 'M6 Flat Washer',
    nameKo: 'M6 평 와셔',
    standard: 'ISO 7089',
    params: { M: 6, innerDia: 6.4, outerDia: 12, thickness: 1.6 },
    unitWeightG: 0.8,
    unitPriceKRW: 25,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
  {
    id: 'washer-m8',
    category: 'washer',
    name: 'M8 Flat Washer',
    nameKo: 'M8 평 와셔',
    standard: 'ISO 7089',
    params: { M: 8, innerDia: 8.4, outerDia: 16, thickness: 1.6 },
    unitWeightG: 1.8,
    unitPriceKRW: 35,
    suppliers: ['Misumi', 'SGIS', 'Boseong'],
  },
  {
    id: 'washer-m10',
    category: 'washer',
    name: 'M10 Flat Washer',
    nameKo: 'M10 평 와셔',
    standard: 'ISO 7089',
    params: { M: 10, innerDia: 10.5, outerDia: 20, thickness: 2.0 },
    unitWeightG: 3.8,
    unitPriceKRW: 50,
    suppliers: ['Misumi', 'SGIS', 'Daewoo'],
  },
];
