import { buildComplexSystemGraphFixture } from '../../complexSystemGraph.testFixture';
import { verifyComplexSystemGraphBytes } from '../../complexSystemGraph';
import type { MachineSkidFamilyContract } from './machineSkidContract';
const encode = (value: unknown) => new TextEncoder().encode(JSON.stringify(value));
export function buildMachineSkidFamilyContractFixture() {
  const base = buildComplexSystemGraphFixture(), graph = structuredClone(base.graph), sourceArtifactNames = ['system-source.json']; graph.family = 'machine_skid'; graph.systemId = 'machine-skid-pilot-01'; graph.nodes.find(node => node.id === 'part-made')!.attributes.role = 'base_frame'; graph.nodes.find(node => node.id === 'part-buy')!.attributes.role = 'equipment';
  for (const [id, role] of [['anchor-a', 'anchor'], ['anchor-b', 'anchor'], ['lift-a', 'lifting_point'], ['lift-b', 'lifting_point']] as const) { graph.nodes.push({ id, kind: 'part', name: id, status: 'confirmed', sourceArtifactNames, attributes: { role } }); graph.edges.push({ id: `contains-${id}`, kind: 'contains', from: 'assembly', to: id, status: 'confirmed', sourceArtifactNames }, { id: `supply-${id}`, kind: 'supplied_by', from: id, to: 'supplier', status: 'confirmed', sourceArtifactNames }, { id: `inspect-${id}`, kind: 'inspected_at', from: id, to: 'datum', status: 'confirmed', sourceArtifactNames }, { id: `accept-${id}`, kind: 'accepted_by', from: id, to: 'acceptance', status: 'confirmed', sourceArtifactNames }); }
  graph.nodes.push({ id: 'port-a', kind: 'interface', name: 'port-a', status: 'confirmed', sourceArtifactNames, attributes: { role: 'port' } }); graph.edges.push({ id: 'contains-port-a', kind: 'contains', from: 'assembly', to: 'port-a', status: 'confirmed', sourceArtifactNames }); graph.evidence[0]!.subjectNodeIds = graph.nodes.map(node => node.id); graph.evidence[0]!.supportingEdgeIds = graph.edges.map(edge => edge.id);
  const graphBytes = encode(graph), graphHash = verifyComplexSystemGraphBytes(graphBytes, base.artifacts).graphHash!;
  const contract: MachineSkidFamilyContract = { schema: 'nexyfab.machine-skid-family-contract.v1', systemGraphHash: graphHash, target: { maximumMassKg: 1000, maximumEnvelopeMm: [3000, 1600, 2200], maximumAlignmentErrorMm: 0.2, minimumLoadPathSafetyFactor: 1.5, minimumAnchorSafetyFactor: 1.5, minimumLiftingSafetyFactor: 2, operatingFrequencyHz: [20, 30], minimumFrequencySeparationRatio: 1.2 }, massItems: [{ nodeId: 'part-made', massKg: 500 }, { nodeId: 'part-buy', massKg: 300 }], baseFrame: { nodeId: 'part-made', predictedDeflectionMm: 0.3, maximumDeflectionMm: 0.5 }, loadCases: [{ id: 'operating', demandedN: 10_000, allowableN: 20_000, demandedMomentNm: 2_000, allowableMomentNm: 4_000 }], anchors: [{ nodeId: 'anchor-a', demandedN: 2000, allowableN: 4000 }, { nodeId: 'anchor-b', demandedN: 2000, allowableN: 4000 }], alignment: [{ equipmentNodeId: 'part-buy', predictedErrorMm: 0.1 }], vibrationModesHz: [5, 100], lifting: [{ nodeId: 'lift-a', demandedN: 4000, allowableN: 10_000 }, { nodeId: 'lift-b', demandedN: 4000, allowableN: 10_000 }], centerOfGravityInsideLiftPolygon: true, ports: [{ nodeId: 'port-a', connected: true, ratingMargin: 1.2 }], service: [{ nodeId: 'part-buy', availableClearanceMm: 900, requiredClearanceMm: 700, removableWithoutDestructiveDisassembly: true }], transport: { envelopeMm: [2800, 1500, 2100], totalMassKg: 800, approvedLiftAndTieDownPlan: true }, evidenceArtifactNames: ['system-source.json'] };
  return { graph, graphBytes, contract, contractBytes: encode(contract), artifacts: base.artifacts };
}
